module.exports = (H) => [
  H.chapter("Ein- und Ausgabe"),
  H.p("Ein Programm, das nichts anzeigt und nichts erfragt, wäre eine stille Sache. In diesem Kapitel lernst du die beiden Befehle kennen, mit denen dein Programm mit dem Menschen davor spricht: PRINT schreibt etwas auf den Bildschirm, INPUT liest etwas von der Tastatur. Zum Schluss kommen die f-Strings dazu – eine elegante Art, Text und Werte zu einem Satz zu verweben."),

  H.h2("Ausgeben mit PRINT"),
  H.p("PRINT kennst du schon aus den ersten Kapiteln. Es gibt einen oder mehrere Werte aus und springt anschließend in die nächste Zeile. Werte zählst du auf, indem du sie mit einem Trennzeichen aneinanderreihst – und genau dieses Trennzeichen entscheidet über das Aussehen der Ausgabe."),
  H.cmd("PRINT", "PRINT wert1 [, wert2 ...]   ' oder mit ;",
    "Gibt die Werte aus und beginnt danach eine neue Zeile. Mehrere Werte trennst du mit Komma oder Semikolon – siehe unten. PRINT ganz ohne Argument gibt eine leere Zeile aus.",
    ['PRINT "Hallo!"', 'PRINT 2 + 3', 'PRINT'],
    { out: ["Hallo!", "5", ""] }),

  H.h2("Komma oder Semikolon – der feine Unterschied"),
  H.p("Beide Trennzeichen hängen die Werte hintereinander – aber das Komma setzt ein Leerzeichen dazwischen, das Semikolon nicht. So hast du die Ausgabe genau in der Hand:"),
  H.bulletRich("Komma  ,  ", "trennt mit einem Leerzeichen."),
  H.bulletRich("Semikolon  ;  ", "trennt ohne Zwischenraum – die Werte kleben aneinander."),
  H.code([
    'PRINT "a", "b", "c"',
    'PRINT "a"; "b"; "c"',
    'PRINT "Punkte: "; 42',
  ]),
  H.code(["a b c", "abc", "Punkte: 42"], { out: true }),
  H.p("Ein Semikolon am Zeilenende hat noch einen Spezialeffekt: Es unterdrückt den Zeilenumbruch. Der nächste PRINT schließt dann direkt an – praktisch, um eine Zeile in mehreren Schritten aufzubauen."),
  H.code([
    'PRINT "Lade";',
    'PRINT "...";',
    'PRINT "fertig"',
  ]),
  H.code(["Lade...fertig"], { out: true }),

  H.h2("Eingeben mit INPUT"),
  H.p("INPUT hält das Programm an, wartet auf eine Eingabe des Benutzers (abgeschlossen mit der Eingabetaste) und legt das Getippte in einer Variablen ab. Der Clou: Drachenhauch wandelt die Eingabe automatisch in den Typ der Variablen um. Steht dort eine INTEGER-Variable, wird aus dem getippten Text eine Zahl; bei STRING bleibt es Text."),
  H.cmd("INPUT", 'INPUT variable\nINPUT "Frage", variable',
    "Liest eine Zeile von der Tastatur in die angegebene Variable. Optional stellst du einen Text als Frage voran – dann erscheint dieser vor dem Eingabe-Cursor. Ohne eigenen Text zeigt Drachenhauch schlicht „? “ an. Die Variable muss vorher mit DIM angelegt sein.",
    [
      'DIM name AS STRING',
      'INPUT "Wie heißt du? ", name',
      'PRINT "Hallo, " + name + "!"',
    ]),
  H.p("Weil die Variable den Typ vorgibt, kannst du direkt mit Zahlen weiterrechnen, wenn du eine Zahl-Variable benutzt:"),
  H.code([
    'DIM alter AS INTEGER',
    'INPUT "Dein Alter: ", alter',
    'PRINT "Nächstes Jahr bist du "; alter + 1',
  ]),
  H.note("Tippt der Benutzer bei einer INTEGER- oder FLOAT-Variablen etwas ein, das keine Zahl ist (z. B. „hallo“), meldet Drachenhauch einen Fehler. Willst du das abfangen, lies stattdessen in eine STRING-Variable ein und wandle den Text behutsam mit TRYVAL um – dort kannst du einen Ersatzwert angeben."),
  H.note("INPUT ist für Konsolen-Programme gedacht. In einem Grafik-Spiel mit eigenem Fenster fragst du Eingaben nicht mit INPUT ab, sondern liest Tastatur und Maus pro Bild aus – das lernst du in Teil IV (Kapitel „Eingabe“)."),

  H.h2("f-Strings: Text und Werte verweben"),
  H.p("Sätze aus Bausteinen mit + zusammenzusetzen funktioniert, wird aber schnell unübersichtlich – überall Anführungszeichen, Pluszeichen und STR$-Umwandlungen. Schöner geht es mit einem f-String: Du schreibst ein kleines f direkt vor das öffnende Anführungszeichen und setzt die Werte in geschweifte Klammern { } mitten in den Text. Drachenhauch füllt sie beim Ausgeben automatisch ein."),
  H.cmd('f"..."', 'f"text {ausdruck} text ..."',
    "Ein String mit Platzhaltern. Was in geschweiften Klammern steht, wird als Ausdruck berechnet und an dieser Stelle eingesetzt. Drin darf alles stehen: Variablen, Rechnungen, sogar Funktionsaufrufe.",
    [
      'DIM name AS STRING',
      'DIM hp AS INTEGER',
      'name = "Anna"',
      'hp = 75',
      'PRINT f"{name} hat {hp} HP"',
      'PRINT f"In Summe: {7 + 5}"',
    ],
    { out: ["Anna hat 75 HP", "In Summe: 12"] }),
  H.p("Brauchst du eine echte geschweifte Klammer im Text, schreibst du sie doppelt – {{ und }} werden zu einer einzelnen Klammer und nicht als Platzhalter gedeutet:"),
  H.code([
    'DIM hp AS INTEGER',
    'hp = 75',
    'PRINT f"literal {{Klammern}}, aber {hp}"',
  ]),
  H.code(["literal {Klammern}, aber 75"], { out: true }),

  H.h2("Zahlen hübsch formatieren"),
  H.p("Manchmal soll eine Zahl in einer bestimmten Form erscheinen: eine Kommazahl mit genau einer Nachkommastelle, oder eine Punktzahl mit führenden Nullen. Dafür hängst du im Platzhalter einen Doppelpunkt und eine Format-Angabe an – im selben Stil wie das gleich vorgestellte FORMAT$."),
  H.code([
    'DIM fps AS FLOAT',
    'DIM punkte AS INTEGER',
    'fps = 59.7',
    'punkte = 75',
    'PRINT f"FPS {fps:.1f}  Punkte {punkte:05d}"',
  ]),
  H.code(["FPS 59.7  Punkte 00075"], { out: true }),
  H.p("Dabei bedeutet .1f „Kommazahl mit einer Nachkommastelle“ und 05d „ganze Zahl, mindestens 5 Stellen, vorn mit Nullen aufgefüllt“. Dieselben Angaben kennt auch der Befehl FORMAT$, falls du außerhalb eines f-Strings formatieren willst:"),
  H.cmd("FORMAT$", 'FORMAT$(wert, format$)',
    "Formatiert einen Wert nach einer Format-Angabe im C-Stil und liefert einen String zurück. Typische Angaben: \"%.2f\" (zwei Nachkommastellen), \"%05d\" (Zahl mit führenden Nullen), \"%x\" (hexadezimal).",
    [
      'PRINT FORMAT$(3.14159, "%.2f")',
      'PRINT FORMAT$(42, "%05d")',
    ],
    { out: ["3.14", "00042"] }),

  H.tip("Faustregel", "Für die meiste Ausgabe sind f-Strings die angenehmste Wahl – sie lesen sich fast wie der fertige Satz. Greife nur dann zu PRINT mit Komma/Semikolon zurück, wenn du das Trennverhalten ganz genau steuern willst."),
];
