module.exports = (H) => [
  H.chapter("Verzweigungen"),
  H.p("Bisher liefen unsere Programme stur von oben nach unten – Zeile für Zeile. Spannend wird es, wenn ein Programm Entscheidungen trifft: „Wenn die Lebenspunkte null sind, ist das Spiel vorbei.“ Genau dafür gibt es Verzweigungen. Sie prüfen eine Bedingung und führen je nach Ergebnis unterschiedliche Befehle aus. In diesem Kapitel lernst du IF, SELECT CASE und den kompakten Einzeiler IIF kennen."),

  H.h2("Die einfachste Entscheidung: IF ... THEN"),
  H.p("Ein IF prüft eine Bedingung – einen Ausdruck, der TRUE oder FALSE ergibt (du erinnerst dich an die Vergleichs-Operatoren aus dem letzten Kapitel). Ist sie wahr, läuft der Block zwischen THEN und END IF; ist sie falsch, wird er übersprungen."),
  H.cmd("IF ... THEN ... END IF", "IF bedingung THEN\n    ...\nEND IF",
    "Führt den eingerückten Block nur aus, wenn die Bedingung wahr ist. Das THEN steht am Ende der IF-Zeile, das END IF schließt den Block ab.",
    [
      'DIM leben AS INTEGER',
      'leben = 0',
      'IF leben <= 0 THEN',
      '    PRINT "Game Over"',
      'END IF',
    ],
    { out: ["Game Over"] }),

  H.h2("Eine Alternative: ELSE"),
  H.p("Oft willst du das eine ODER das andere tun. Mit ELSE gibst du einen zweiten Block an, der genau dann läuft, wenn die Bedingung falsch ist:"),
  H.code([
    'DIM alter AS INTEGER',
    'alter = 16',
    'IF alter >= 18 THEN',
    '    PRINT "volljährig"',
    'ELSE',
    '    PRINT "noch minderjährig"',
    'END IF',
  ]),
  H.code(["noch minderjährig"], { out: true }),

  H.h2("Mehrere Fälle: ELSEIF"),
  H.p("Manchmal gibt es nicht nur zwei Möglichkeiten, sondern eine ganze Treppe von Fällen. Mit ELSEIF hängst du weitere Bedingungen an. Drachenhauch prüft sie von oben nach unten und nimmt den ersten Block, dessen Bedingung zutrifft – die übrigen werden übersprungen. Ein abschließendes ELSE fängt alles ab, was bis dahin nicht gepasst hat."),
  H.cmd("IF / ELSEIF / ELSE", "IF a THEN ... ELSEIF b THEN ... ELSE ... END IF",
    "Eine Kette von Bedingungen. Der erste passende Zweig gewinnt; ELSE ist der Auffang-Zweig für alle übrigen Fälle. (ELIF ist eine erlaubte Kurzschreibweise für ELSEIF.)",
    [
      'DIM punkte AS INTEGER',
      'punkte = 75',
      'IF punkte >= 90 THEN',
      '    PRINT "Note 1"',
      'ELSEIF punkte >= 75 THEN',
      '    PRINT "Note 2"',
      'ELSEIF punkte >= 50 THEN',
      '    PRINT "Note 3"',
      'ELSE',
      '    PRINT "durchgefallen"',
      'END IF',
    ],
    { out: ["Note 2"] }),
  H.note("Die Reihenfolge zählt! Hier passt sowohl „>= 75“ als auch „>= 50“ – aber weil 75 zuerst geprüft wird, gewinnt „Note 2“. Ordne deine Bedingungen also vom Speziellsten zum Allgemeinsten."),

  H.h2("Alles in einer Zeile"),
  H.p("Geht es nur um einen einzigen Befehl, darfst du IF auch komplett in eine Zeile schreiben – ohne END IF. Das hält kurze Prüfungen knapp und lesbar:"),
  H.code([
    'DIM leben AS INTEGER',
    'leben = 0',
    'IF leben <= 0 THEN PRINT "Game Over"',
  ]),
  H.code(["Game Over"], { out: true }),
  H.warn("Beim einzeiligen IF folgt direkt nach THEN der auszuführende Befehl – und es gibt KEIN END IF. Sobald du mehrere Zeilen oder einen ELSE-Zweig brauchst, nimm die ausführliche Form mit END IF."),

  H.h2("Viele Fälle übersichtlich: SELECT CASE"),
  H.p("Wenn du ein und denselben Wert gegen viele Möglichkeiten prüfst, wird eine lange IF-ELSEIF-Treppe schnell unübersichtlich. SELECT CASE ist dafür gemacht: Du nennst den zu prüfenden Wert einmal, und listest darunter die Fälle auf. Der erste passende CASE gewinnt; CASE ELSE fängt den Rest."),
  H.cmd("SELECT CASE", "SELECT CASE wert\n    CASE muster\n        ...\n    CASE ELSE\n        ...\nEND SELECT",
    "Wertet den Ausdruck einmal aus und vergleicht ihn der Reihe nach mit den CASE-Mustern. Ein CASE kann ein einzelner Wert, eine kommagetrennte Liste oder ein Bereich sein.",
    [
      'DIM tag AS INTEGER',
      'tag = 6',
      'SELECT CASE tag',
      '    CASE 1, 2, 3, 4, 5',
      '        PRINT "Wochentag"',
      '    CASE 6, 7',
      '        PRINT "Wochenende"',
      'END SELECT',
    ],
    { out: ["Wochenende"] }),

  H.h2("Bereiche und Vergleiche im CASE"),
  H.p("Ein CASE muss nicht auf exakte Werte warten. Mit TO gibst du einen Bereich an (beide Grenzen zählen mit), mit IS einen Vergleich. Alle Formen lassen sich auch mischen, etwa CASE 1, 5 TO 8, IS > 100."),
  H.bulletRich("CASE 1, 2, 3   ", "– eine Liste einzelner Werte"),
  H.bulletRich("CASE 10 TO 20   ", "– ein Bereich von 10 bis 20 (einschließlich)"),
  H.bulletRich("CASE IS > 100   ", "– ein Vergleich (=, <>, <, >, <=, >=)"),
  H.code([
    'DIM x AS INTEGER',
    'x = 150',
    'SELECT CASE x',
    '    CASE IS <= 0',
    '        PRINT "null oder negativ"',
    '    CASE 1 TO 100',
    '        PRINT "klein"',
    '    CASE IS > 100',
    '        PRINT "gross"',
    'END SELECT',
  ]),
  H.code(["gross"], { out: true }),
  H.note("Der zu prüfende Wert wird nur ein einziges Mal berechnet – selbst wenn dort ein aufwändiger Funktionsaufruf steht. Das ist ein Vorteil gegenüber einer IF-Treppe, in der du den Ausdruck bei jeder Prüfung wiederholen müsstest."),

  H.h2("Zusätzliche Bedingung: CASE ... WHERE"),
  H.p("Manchmal soll ein CASE nur greifen, wenn zusätzlich eine weitere Bedingung erfüllt ist. Dafür hängst du WHERE an. Passt das Muster, der WHERE-Ausdruck ist aber falsch, probiert Drachenhauch den nächsten CASE. So kombinierst du den Wert mit beliebigem Zusatzwissen:"),
  H.code([
    'DIM hp AS INTEGER',
    'DIM trank AS BOOLEAN',
    'hp = 20',
    'trank = TRUE',
    'SELECT CASE hp',
    '    CASE IS <= 0',
    '        PRINT "tot"',
    '    CASE IS <= 30 WHERE trank',
    '        PRINT "heilen"',
    '    CASE IS <= 30',
    '        PRINT "fliehen"',
    '    CASE ELSE',
    '        PRINT "ok"',
    'END SELECT',
  ]),
  H.code(["heilen"], { out: true }),
  H.p("Wäre trank hier FALSE, würde der „heilen“-Fall nicht greifen und der nächste passende CASE („fliehen“) übernehmen."),

  H.h2("Die Entscheidung als Ausdruck: IIF"),
  H.p("Bisher waren Verzweigungen ganze Anweisungs-Blöcke. Manchmal willst du aber nur zwischen zwei Werten wählen – etwa eine Richtung, einen Text, eine Farbe. Dafür gibt es IIF („inline if“): Es nimmt eine Bedingung und zwei Werte und liefert je nach Bedingung den einen oder den anderen zurück. IIF passt mitten in eine Zuweisung oder einen PRINT."),
  H.cmd("IIF", "IIF(bedingung, dann, sonst)",
    "Liefert den zweiten Wert, wenn die Bedingung wahr ist, sonst den dritten. Nur der jeweils gewählte Zweig wird ausgewertet – die andere Seite wird gar nicht erst berechnet (kein Division-durch-Null-Unfall im ungenutzten Zweig).",
    [
      'DIM richtung AS INTEGER',
      'richtung = -1',
      'PRINT IIF(richtung < 0, "links", "rechts")',
      'PRINT IIF(5 > 3, 100, 200)',
    ],
    { out: ["links", "100"] }),
  H.tip("Wann IIF, wann IF?", "Nimm IIF, wenn du genau einen Wert auswählst und ihn sofort verwenden willst (dx = IIF(links, -speed, speed)). Sobald je Zweig mehrere Befehle laufen sollen, ist das ausführliche IF ... END IF die klarere Wahl."),
];
