module.exports = (H) => [
  H.chapter("Schleifen"),
  H.p("Computer sind unermüdlich – und genau das machen wir uns mit Schleifen zunutze. Eine Schleife wiederholt einen Block von Befehlen, bis eine bestimmte Bedingung erfüllt ist. Ob du von 1 bis 100 zählst, alle Gegner eines Spiels aktualisierst oder so lange würfelst, bis eine Sechs fällt: Schleifen sind das Herz fast jedes Programms. Drachenhauch kennt mehrere Sorten, jede für eine andere Situation."),

  H.h2("Eine feste Anzahl: FOR ... NEXT"),
  H.p("Die FOR-Schleife zählt eine Variable von einem Startwert bis zu einem Endwert hoch und führt für jeden Wert den Block aus. Das NEXT markiert das Ende des Blocks – dort springt Drachenhauch zurück und erhöht die Zählvariable."),
  H.cmd("FOR ... NEXT", "FOR var = start TO ende\n    ...\nNEXT",
    "Wiederholt den Block, während die Zählvariable von start bis ende läuft (beide Grenzen eingeschlossen). Nach jedem Durchlauf wird die Variable um 1 erhöht. Die Zählvariable muss vorher mit DIM angelegt sein.",
    [
      'DIM i AS INTEGER',
      'FOR i = 1 TO 5',
      '    PRINT i',
      'NEXT',
    ],
    { out: ["1", "2", "3", "4", "5"] }),

  H.h2("In Schritten zählen: STEP"),
  H.p("Standardmäßig zählt FOR in Einerschritten aufwärts. Mit STEP gibst du eine andere Schrittweite an – auch eine negative, um rückwärts zu zählen:"),
  H.code([
    'DIM i AS INTEGER',
    'FOR i = 10 TO 0 STEP -2',
    '    PRINT i;',
    '    PRINT " ";',
    'NEXT',
  ]),
  H.code(["10 8 6 4 2 0"], { out: true }),
  H.warn("STEP ist ein Schlüsselwort. Nenne deine Zählvariable also nicht „step“ – nimm i, j, zaehler oder etwas Aussagekräftiges."),

  H.h2("Solange eine Bedingung gilt: WHILE ... WEND"),
  H.p("Manchmal weißt du vorher nicht, wie oft etwas wiederholt werden muss – nur, unter welcher Bedingung. Die WHILE-Schleife prüft ihre Bedingung VOR jedem Durchlauf und läuft, solange sie wahr ist. Ist sie schon zu Beginn falsch, läuft der Block kein einziges Mal."),
  H.cmd("WHILE ... WEND", "WHILE bedingung\n    ...\nWEND",
    "Wiederholt den Block, solange die Bedingung wahr ist. Die Prüfung erfolgt am Anfang jedes Durchlaufs. WEND schließt die Schleife ab.",
    [
      'DIM n AS INTEGER',
      'n = 1',
      'WHILE n <= 100',
      '    n = n * 2',
      'WEND',
      'PRINT n',
    ],
    { out: ["128"] }),
  H.warn("Achte darauf, dass sich in der Schleife etwas verändert, das die Bedingung irgendwann falsch macht – sonst läuft die Schleife endlos und dein Programm hängt. Im Beispiel verdoppelt n sich jedes Mal und überschreitet schließlich 100."),

  H.h2("Mindestens einmal: REPEAT ... UNTIL"),
  H.p("Die REPEAT-Schleife ist das Gegenstück zu WHILE: Sie prüft ihre Bedingung erst am ENDE. Dadurch läuft der Block garantiert mindestens einmal – ideal, wenn du etwas zuerst tun und dann erst entscheiden willst, ob du es wiederholst (etwa „würfeln, bis eine Drei fällt“)."),
  H.cmd("REPEAT ... UNTIL", "REPEAT\n    ...\nUNTIL bedingung",
    "Wiederholt den Block, bis die Bedingung wahr wird. Die Prüfung erfolgt am Ende – der Block läuft also immer mindestens einmal.",
    [
      'DIM wurf AS INTEGER',
      'wurf = 0',
      'REPEAT',
      '    wurf = wurf + 1',
      'UNTIL wurf >= 3',
      'PRINT "Würfe: "; wurf',
    ],
    { out: ["Würfe: 3"] }),
  H.note("Der Unterschied auf einen Blick: WHILE prüft VORHER (läuft evtl. nie), REPEAT prüft NACHHER (läuft mindestens einmal). Und Vorsicht beim Wort: WHILE läuft, solange die Bedingung WAHR ist – REPEAT läuft, BIS sie wahr wird."),

  H.h2("Über eine Sammlung: FOR EACH"),
  H.p("Sehr oft willst du nicht Zahlen hochzählen, sondern jedes Element einer Sammlung der Reihe nach bearbeiten – alle Namen in einer Liste, alle Buchstaben eines Wortes, alle Gegner im Spiel. Dafür ist FOR EACH gemacht: Es reicht dir bei jedem Durchlauf direkt das nächste Element."),
  H.cmd("FOR EACH ... NEXT", "FOR EACH var IN sammlung\n    ...\nNEXT",
    "Durchläuft jedes Element der Sammlung und legt es nacheinander in var ab. Funktioniert mit Tupeln, Arrays, den Zeichen eines Strings und den Schlüsseln einer Map (diese Sammlungen lernst du in den folgenden Kapiteln kennen).",
    [
      'DIM namen AS TUPLE',
      'namen = ("Anna", "Bert", "Cilly")',
      'FOR EACH name IN namen',
      '    PRINT name',
      'NEXT',
    ],
    { out: ["Anna", "Bert", "Cilly"] }),

  H.h2("Eingreifen: BREAK und CONTINUE"),
  H.p("Zwei kleine Befehle geben dir mitten in einer Schleife die Kontrolle zurück. Sie funktionieren in allen vier Schleifenarten:"),
  H.bulletRich("BREAK   ", "bricht die Schleife sofort ganz ab und springt hinter das NEXT bzw. WEND."),
  H.bulletRich("CONTINUE   ", "überspringt den Rest des aktuellen Durchlaufs und macht sofort mit dem nächsten weiter."),
  H.code([
    'DIM i AS INTEGER',
    'FOR i = 1 TO 10',
    '    IF i MOD 2 = 0 THEN CONTINUE',
    '    IF i > 7 THEN BREAK',
    '    PRINT i;',
    '    PRINT " ";',
    'NEXT',
  ]),
  H.code(["1 3 5 7"], { out: true }),
  H.p("Hier überspringt CONTINUE alle geraden Zahlen, und sobald i über 7 steigt, beendet BREAK die Schleife – ausgegeben werden also nur die ungeraden Zahlen bis 7."),

  H.h2("Schleifen verschachteln"),
  H.p("Du darfst Schleifen ineinander setzen. Für jeden Durchlauf der äußeren Schleife läuft die innere komplett durch. So baust du zum Beispiel ein Gitter, ein kleines Einmaleins oder zeichnest später eine Kachelkarte Reihe für Reihe:"),
  H.code([
    'DIM zeile AS INTEGER',
    'DIM spalte AS INTEGER',
    'FOR zeile = 1 TO 3',
    '    FOR spalte = 1 TO 3',
    '        PRINT zeile * spalte;',
    '        PRINT " ";',
    '    NEXT',
    '    PRINT',
    'NEXT',
  ]),
  H.code(["1 2 3", "2 4 6", "3 6 9"], { out: true }),
  H.tip("Welche Schleife wann?", "Kennst du die Anzahl der Durchläufe im Voraus, nimm FOR. Hast du eine Sammlung, nimm FOR EACH. Hängt die Wiederholung an einer Bedingung, nimm WHILE (Prüfung vorher) oder REPEAT (mindestens ein Durchlauf)."),
];
