module.exports = (H) => [
  H.chapter("Funktionen & SUBs"),
  H.p("Sobald ein Programm wächst, willst du dieselbe Aufgabe nicht zehnmal hinschreiben. Funktionen und SUBs sind benannte Bausteine: Du verpackst ein Stück Arbeit einmal, gibst ihm einen Namen – und rufst es danach beliebig oft auf. Das macht Programme kürzer, lesbarer und leichter zu reparieren, denn jede Logik wohnt an genau einer Stelle. Dieses Kapitel zeigt alles, was Drachenhauch dir dabei in die Hand gibt."),

  H.h2("FUNCTION: ein Ergebnis berechnen"),
  H.p("Eine FUNCTION nimmt Werte entgegen, rechnet etwas aus und gibt mit RETURN ein Ergebnis zurück. Hinter AS steht der Typ des Rückgabewerts. Aufgerufen wird sie wie ein eingebauter Befehl – das Ergebnis kannst du direkt weiterverwenden."),
  H.cmd("FUNCTION ... RETURN", "FUNCTION name(param AS Typ) AS Rückgabetyp\n    RETURN wert\nEND FUNCTION",
    "Definiert eine Funktion mit Parametern und einem Rückgabetyp. RETURN liefert das Ergebnis und beendet die Funktion sofort. Der Aufruf name(...) wird zum berechneten Wert.",
    [
      'FUNCTION quadrat(x AS INTEGER) AS INTEGER',
      '    RETURN x * x',
      'END FUNCTION',
      '',
      'PRINT quadrat(5)',
    ],
    { out: ["25"] }),

  H.h2("SUB: etwas erledigen"),
  H.p("Eine SUB ist eine Funktion ohne Rückgabewert. Sie erledigt eine Aufgabe – etwas ausgeben, einen Zustand ändern, eine Datei schreiben – aber sie liefert kein Ergebnis zum Weiterrechnen. Du rufst sie als eigenständige Anweisung auf."),
  H.cmd("SUB ... END SUB", "SUB name(param AS Typ)\n    ...\nEND SUB",
    "Definiert einen benannten Befehlsblock ohne Rückgabewert. Aufgerufen wird er als eigene Anweisung. Ein RETURN ohne Wert kann eine SUB vorzeitig verlassen.",
    [
      'SUB gruesse(name AS STRING)',
      '    PRINT "Hallo, " + name + "!"',
      'END SUB',
      '',
      'gruesse("Mario")',
    ],
    { out: ["Hallo, Mario!"] }),
  H.note("Faustregel: Liefert der Baustein einen Wert, den du weiterverwendest, nimm FUNCTION. Tut er einfach etwas, nimm SUB."),

  H.h2("Mehrere Parameter"),
  H.p("Du kannst beliebig viele Parameter angeben – durch Kommas getrennt, jeder mit eigenem Typ. Beim Aufruf gibst du die Werte in derselben Reihenfolge an. Diese Werte heißen Argumente."),
  H.code([
    'FUNCTION addiere(a AS INTEGER, b AS INTEGER) AS INTEGER',
    '    RETURN a + b',
    'END FUNCTION',
    '',
    'PRINT addiere(3, 4)',
  ]),
  H.code(["7"], { out: true }),
  H.note("Parameter sind lokal: Sie existieren nur innerhalb der Funktion. Änderst du sie dort, bleibt der Wert draußen unberührt (außer bei BYREF – gleich mehr dazu). Funktionen sehen außerdem keine lokalen Variablen des Aufrufers; was sie brauchen, bekommen sie als Parameter."),

  H.h2("Werte verändern: BYREF"),
  H.p("Normalerweise bekommt eine Funktion eine Kopie ihrer Argumente – Änderungen daran bleiben innen. Stellst du einem Parameter BYREF voran, arbeitet die Funktion direkt auf der übergebenen Variablen. Eine Zuweisung wirkt dann auch außerhalb. So gibst du Werte zurück, ohne RETURN zu benutzen."),
  H.cmd("BYREF", "SUB name(BYREF param AS Typ)",
    "Übergibt die Variable selbst statt einer Kopie. Schreibzugriffe in der Funktion verändern die Variable des Aufrufers. Nur echte Variablen lassen sich per BYREF übergeben, keine festen Werte wie 5.",
    [
      'SUB verdopple(BYREF n AS INTEGER)',
      '    n = n * 2',
      'END SUB',
      '',
      'DIM wert AS INTEGER',
      'wert = 21',
      'verdopple(wert)',
      'PRINT wert',
    ],
    { out: ["42"] }),
  H.tip("Mehrere Ergebnisse?", "Wenn du mehr als einen Wert zurückgeben willst, gibt es neben BYREF eine elegantere Möglichkeit: ein Tupel zurückgeben und es beim Aufruf zerlegen. Das lernst du im Kapitel „Tupel & Destructuring“."),

  H.h2("Vorgabewerte (Defaults)"),
  H.p("Einem Parameter kannst du einen Standardwert mitgeben. Lässt der Aufrufer dieses Argument weg, springt der Vorgabewert ein. Praktisch für Optionen, die meistens gleich sind. Parameter mit Vorgabewert stehen am Ende der Liste."),
  H.code([
    'FUNCTION potenz(basis AS INTEGER, exp AS INTEGER = 2) AS INTEGER',
    '    DIM r AS INTEGER',
    '    DIM j AS INTEGER',
    '    r = 1',
    '    FOR j = 1 TO exp',
    '        r = r * basis',
    '    NEXT',
    '    RETURN r',
    'END FUNCTION',
    '',
    'PRINT potenz(5)        \' exp ist standardmäßig 2',
    'PRINT potenz(2, 10)',
  ]),
  H.code(["25", "1024"], { out: true }),

  H.h2("Argumente benennen"),
  H.p("Bei vielen oder ähnlichen Parametern verliert man leicht den Überblick, welcher Wert wohin gehört. Du darfst Argumente beim Aufruf auch beim Namen nennen – dann ist die Reihenfolge egal und der Aufruf liest sich selbsterklärend."),
  H.code([
    'SUB info(name AS STRING, alter AS INTEGER)',
    '    PRINT name + " ist " + STR$(alter)',
    'END SUB',
    '',
    'info(alter: 30, name: "Anna")',
  ]),
  H.code(["Anna ist 30"], { out: true }),

  H.h2("Beliebig viele Argumente: ..."),
  H.p("Manchmal weißt du nicht im Voraus, wie viele Werte übergeben werden. Ein Parameter mit drei Punkten davor sammelt alle übrigen Argumente in einem Tupel. Er muss der letzte sein."),
  H.code([
    'FUNCTION summe(...zahlen) AS INTEGER',
    '    DIM s AS INTEGER',
    '    DIM j AS INTEGER',
    '    s = 0',
    '    FOR j = 0 TO zahlen.length() - 1',
    '        s = s + zahlen[j]',
    '    NEXT',
    '    RETURN s',
    'END FUNCTION',
    '',
    'PRINT summe(1, 2, 3, 4, 5)',
  ]),
  H.code(["15"], { out: true }),

  H.h2("Funktionen als Werte: FUNCREF"),
  H.p("In Drachenhauch ist eine Funktion selbst ein Wert, den du in einer Variablen vom Typ FUNCREF ablegen und später aufrufen kannst. So übergibst du „was zu tun ist“ als Argument – etwa eine Vergleichsfunktion zum Sortieren oder einen Rückruf für ein Ereignis."),
  H.cmd("FUNCREF", "DIM f AS FUNCREF\nf = funktionsname\nf(args)",
    "Eine Variable, die auf eine Funktion verweist. Der bloße Funktionsname (ohne Klammern) wird zur Referenz; mit f(...) rufst du die dahinterliegende Funktion auf.",
    [
      'FUNCTION verdreifache(x AS INTEGER) AS INTEGER',
      '    RETURN x * 3',
      'END FUNCTION',
      '',
      'DIM f AS FUNCREF',
      'f = verdreifache',
      'PRINT f(7)',
    ],
    { out: ["21"] }),

  H.h2("Sich selbst aufrufen: Rekursion"),
  H.p("Eine Funktion darf sich selbst aufrufen. Das nennt man Rekursion und es eignet sich für Probleme, die sich in kleinere Versionen ihrer selbst zerlegen lassen – etwa die Fakultät (5! = 5 · 4 · 3 · 2 · 1). Wichtig ist ein Abbruchfall, der die Kette beendet, sonst ruft sich die Funktion endlos selbst auf."),
  H.code([
    'FUNCTION fakultaet(n AS INTEGER) AS INTEGER',
    '    IF n <= 1 THEN RETURN 1      \' Abbruchfall',
    '    RETURN n * fakultaet(n - 1)  \' ruft sich selbst auf',
    'END FUNCTION',
    '',
    'PRINT fakultaet(5)',
  ]),
  H.code(["120"], { out: true }),
  H.warn("Jede Rekursion braucht einen Abbruchfall, der ohne weiteren Selbstaufruf zurückkehrt – hier n <= 1. Fehlt er, läuft die Funktion immer tiefer, bis das Programm mit einem Fehler abbricht."),

  H.warn("Die Aufruftiefe ist auf 1000 begrenzt. Wer tiefer geht, bekommt „Maximale Aufruftiefe (1000) ueberschritten -- unendliche Rekursion?“ – und der Fehler lässt sich mit TRY/CATCH fangen. Die Zahl ist keine Willkür, sondern die Grenze, die auf allen Betriebssystemen gleich sicher ist. Für einen Abstieg durch einen Baum oder ein Verzeichnis reicht sie bei weitem; wer eine Liste mit hunderttausend Einträgen rekursiv durchgeht, schreibt sie besser als Schleife.",
    "Wie tief es gehen darf"),

  H.tip("Gute Bausteine", "Gib Funktionen sprechende Namen (berechne_schaden statt bs), halte sie kurz und lass jede genau eine Sache tun. Brauchst du eine Funktion an vielen Stellen, lagere sie in eine eigene Datei aus und binde sie mit IMPORT ein – das lernst du im Kapitel „Module importieren“."),
];
