module.exports = (H) => [
  H.chapter("Strings im Detail"),
  H.p("Ein String ist eine Zeichenkette – Text, eingeschlossen in Anführungszeichen. Du hast Strings längst benutzt; hier lernst du sie richtig kennen: ihre Länge messen, Teile herausschneiden, suchen, ersetzen, zerlegen und wieder zusammenbauen. Für fast jede Textaufgabe gibt es einen passenden eingebauten Befehl."),
  H.note("Viele String-Funktionen tragen ein $ am Namensende (LEFT$, MID$, UPPER$ …). Das ist eine alte BASIC-Tradition und kennzeichnet, dass die Funktion einen String zurückgibt. In Drachenhauch darfst du das $ auch weglassen: UPPER$ und UPPER sind dasselbe."),

  H.h2("Wie lang ist der Text?"),
  H.cmd("LEN", "LEN(s$)",
    "Liefert die Anzahl der Zeichen in einem String. (LEN funktioniert auch für Arrays und liefert dort die Anzahl der Elemente.)",
    ['PRINT LEN("Drachenhauch")', 'PRINT LEN("")'],
    { out: ["9", "0"] }),

  H.h2("Groß und klein"),
  H.cmd("UPPER$  /  LOWER$", "UPPER$(s$)   LOWER$(s$)",
    "Wandelt den ganzen Text in Groß- bzw. Kleinbuchstaben um. Praktisch, um Eingaben zu vergleichen, ohne auf die Schreibweise zu achten.",
    ['PRINT UPPER$("hallo")', 'PRINT LOWER$("HALLO")'],
    { out: ["HALLO", "hallo"] }),

  H.h2("Teile herausschneiden"),
  H.p("Mit LEFT$ und RIGHT$ holst du dir die ersten oder letzten Zeichen. MID$ schneidet ab einer beliebigen Stelle. Wichtig: Die Position bei MID$ wird ab 0 gezählt – das erste Zeichen hat die Position 0, das zweite die Position 1 und so weiter."),
  H.cmd("LEFT$  /  RIGHT$", "LEFT$(s$, n)   RIGHT$(s$, n)",
    "LEFT$ liefert die ersten n Zeichen, RIGHT$ die letzten n.",
    ['PRINT LEFT$("Drachenhauch", 4)', 'PRINT RIGHT$("Drachenhauch", 5)'],
    { out: ["Game", "Basic"] }),
  H.cmd("MID$", "MID$(s$, start[, n])",
    "Liefert ab der Position start (0-basiert!) bis zu n Zeichen. Lässt du n weg, geht es bis zum Ende des Strings.",
    ['PRINT MID$("Drachenhauch", 4)', 'PRINT MID$("Drachenhauch", 4, 5)'],
    { out: ["Basic", "Basic"] }),
  H.warn("Anders als manche älteren BASIC-Dialekte zählt Drachenhauch Zeichen-Positionen ab 0, nicht ab 1. Das erste Zeichen von \"Drachenhauch\" (das D) sitzt an Position 0, das erste h an Position 4. Das gilt auch für INSTR und den Index-Zugriff weiter unten."),

  H.h2("Einzelne Zeichen mit dem Index"),
  H.p("Du kannst auf ein einzelnes Zeichen direkt über seine Position zugreifen – mit eckigen Klammern, wie bei einem Array. Mit der Doppelpunkt-Schreibweise schneidest du sogar einen ganzen Bereich heraus (das nennt man Slicing)."),
  H.code([
    'DIM wort AS STRING',
    'wort = "Drachenhauch"',
    'PRINT wort[0]',
    'PRINT wort[4:9]',
  ]),
  H.code(["G", "Basic"], { out: true }),
  H.p("Beim Slicing wort[4:9] ist die untere Grenze dabei, die obere nicht – es werden die Positionen 4 bis 8 geliefert. Beide Grenzen darfst du auch weglassen: wort[:4] sind die ersten vier Zeichen, wort[4:] der Rest ab Position 4."),

  H.h2("Suchen"),
  H.cmd("INSTR", "INSTR(s$, teil$[, start])",
    "Sucht teil$ in s$ und liefert dessen Position (ab 0 gezählt) oder -1, wenn es nicht vorkommt. Optional gibst du an, ab welcher Position gesucht wird.",
    ['PRINT INSTR("hello world", "world")', 'PRINT INSTR("hello world", "xyz")'],
    { out: ["6", "-1"] }),
  H.p("Willst du nur wissen, OB ein Text enthalten ist, sind CONTAINS oder der IN-Operator bequemer – beide liefern einen Wahrheitswert:"),
  H.code([
    'PRINT CONTAINS("hello world", "wor")',
    'PRINT "World" IN "Hello World"',
    'PRINT STARTSWITH("hello", "he")',
    'PRINT ENDSWITH("hello", "lo")',
  ]),
  H.code(["TRUE", "TRUE", "TRUE", "TRUE"], { out: true }),

  H.h2("Ersetzen und Säubern"),
  H.cmd("REPLACE$", "REPLACE$(s$, alt$, neu$)",
    "Ersetzt alle Vorkommen von alt$ durch neu$ und liefert den neuen String.",
    ['PRINT REPLACE$("a-b-c", "-", "_")'],
    { out: ["a_b_c"] }),
  H.cmd("TRIM$", "TRIM$(s$)",
    "Entfernt Leerzeichen (und andere Leerraum-Zeichen) am Anfang und Ende. Unverzichtbar bei Benutzereingaben, wo sich gern ein versehentliches Leerzeichen einschleicht. (LTRIM$ / RTRIM$ säubern nur links bzw. rechts.)",
    ['PRINT TRIM$("   hallo   ") + "|"'],
    { out: ["hallo|"] }),

  H.h2("Zerlegen und Zusammensetzen"),
  H.p("SPLIT$ zerschneidet einen Text an einem Trennzeichen in seine Bestandteile – das Ergebnis ist ein Array von Strings (Arrays lernst du im nächsten Kapitel kennen). JOIN$ ist die Umkehrung: Es fügt die Teile mit einem Trenner wieder zusammen."),
  H.code([
    'DIM teile AS ARRAY OF STRING',
    'teile = SPLIT$("Anna,Bert,Cilly", ",")',
    'PRINT teile[0]',
    'PRINT JOIN$(teile, " | ")',
  ]),
  H.code(["Anna", "Anna | Bert | Cilly"], { out: true }),

  H.h2("Auffüllen und Wiederholen"),
  H.cmd("PADL$  /  PADR$", "PADL$(s$, breite[, füll$])   PADR$(...)",
    "Füllt den String auf die gewünschte Breite auf – PADL$ links (rechtsbündig), PADR$ rechts (linksbündig). Ohne Füllzeichen wird das Leerzeichen verwendet. Gut für Tabellen und führende Nullen.",
    ['PRINT PADL$("42", 6, "0")'],
    { out: ["000042"] }),
  H.cmd("REPEAT$", "REPEAT$(s$, n)",
    "Hängt den String n-mal aneinander. Auch der Stern funktioniert dafür: \"-\" * 20 ergibt 20 Bindestriche.",
    ['PRINT REPEAT$("=*", 5)', 'PRINT "-" * 20'],
    { out: ["=*=*=*=*=*", "--------------------"] }),

  H.h2("Zwischen Text und Zahl wandeln"),
  H.p("Eine Zahl ist kein String – willst du sie in Text einbauen, musst du sie umwandeln (oder einen f-String benutzen). Umgekehrt machst du aus getipptem Text eine Zahl, mit der du rechnen kannst."),
  H.cmd("STR$  /  VAL", "STR$(zahl)   VAL(s$)",
    "STR$ wandelt eine Zahl in ihren Text um, VAL einen Text in eine Zahl. Lässt sich der Text nicht deuten, liefert VAL eine 0 – mit TRYVAL(s, ersatz) kannst du stattdessen einen eigenen Ersatzwert bestimmen.",
    ['PRINT "Punkte: " + STR$(42)', 'PRINT VAL("42") + 1', 'PRINT TRYVAL("oops", -1)'],
    { out: ["Punkte: 42", "43", "-1"] }),
  H.cmd("CHR$  /  ASC", "CHR$(code)   ASC(s$)",
    "CHR$ macht aus einer Zeichen-Nummer (dem Unicode-Codepoint) das zugehörige Zeichen, ASC umgekehrt aus dem ersten Zeichen seine Nummer. A ist 65, B ist 66, und so weiter.",
    ['PRINT CHR$(65)', 'PRINT ASC("Anna")'],
    { out: ["A", "65"] }),

  H.h2("Auch als Methode aufrufbar"),
  H.p("Viele dieser Funktionen kannst du wahlweise auch in Punkt-Schreibweise an den String hängen – das liest sich oft flüssiger und lässt sich verketten:"),
  H.code([
    'PRINT "hallo".upper()',
    'PRINT "  hi  ".trim().upper()',
    'PRINT "Drachenhauch".length()',
  ]),
  H.code(["HALLO", "HI", "9"], { out: true }),
  H.tip("Text bauen mit f-Strings", "Für das Zusammensetzen von Text aus Werten ist ein f-String meist die angenehmste Wahl: f\"{name} hat {punkte} Punkte\" spart dir die vielen + und STR$. Siehe Kapitel „Ein- und Ausgabe“."),
];
