module.exports = (H) => [
  H.chapter("Arrays"),
  H.p("Bisher hatte jede Variable genau einen Wert. Doch oft gehören viele Werte zusammen: die Punkte aller Spieler, die Lebenspunkte jedes Gegners, die Kacheln einer Spielkarte. Für jeden eine eigene Variable anzulegen (gegner1, gegner2, gegner3 …) wäre mühsam und unflexibel. Ein Array löst das: Es ist eine einzige Variable, die viele Werte unter einem Namen bündelt – nummeriert und in Reih und Glied."),
  H.p("Stell dir ein Array wie eine Reihe nummerierter Schließfächer vor. Alle tragen denselben Namen (etwa punkte), aber jedes hat eine eigene Nummer. Über diese Nummer – den Index – sprichst du ein einzelnes Fach an. So kannst du mit einer Schleife mühelos über hunderte oder tausende Werte laufen, ohne je einen neuen Variablennamen erfinden zu müssen."),

  H.h2("Ein Array anlegen"),
  H.p("Ein Array deklarierst du mit DIM – wie eine normale Variable, aber mit der Anzahl der Fächer in eckigen Klammern. Hinter AS steht der Typ, den jedes Fach aufnimmt. Frisch angelegt ist jedes Fach mit dem Standardwert gefüllt: bei Zahlen 0, bei Strings der leere Text, bei Wahrheitswerten FALSE."),
  H.cmd("DIM ... [n] AS Typ", "DIM name[anzahl] AS Typ",
    "Legt ein Array mit der angegebenen Anzahl Fächer an, alle vom genannten Typ und mit dessen Standardwert vorbelegt. Die Anzahl steht in eckigen Klammern.",
    [
      'DIM punkte[5] AS INTEGER',
      'PRINT punkte[0]      \' noch der Standardwert',
    ],
    { out: ["0"] }),

  H.h2("Fächer lesen und beschreiben"),
  H.p("Ein einzelnes Fach sprichst du über seinen Index in eckigen Klammern an. Und hier kommt der wichtigste Punkt überhaupt: Die Zählung beginnt bei 0, nicht bei 1. Ein Array mit 5 Fächern hat also die gültigen Indizes 0, 1, 2, 3 und 4 – das letzte Fach trägt die Nummer 4, nicht 5."),
  H.p("Das fühlt sich am Anfang ungewohnt an, ist aber in fast allen modernen Programmiersprachen so. Merke dir: Der Index ist der „Abstand vom Anfang“. Das erste Element ist null Schritte vom Anfang entfernt, also Index 0."),
  H.code([
    'DIM punkte[5] AS INTEGER',
    'punkte[0] = 42      \' erstes Fach',
    'punkte[1] = 17',
    'punkte[4] = 99      \' letztes Fach (nicht 5!)',
    '',
    'PRINT punkte[0]',
    'PRINT punkte[4]',
  ]),
  H.code(["42", "99"], { out: true }),
  H.warn("Greifst du auf ein Fach zu, das es nicht gibt – etwa punkte[5] bei nur 5 Fächern (gültig sind 0 bis 4) – bricht das Programm mit einem Fehler ab. Achte immer darauf, innerhalb der Grenzen zu bleiben. Die Grenze liefert dir LEN (siehe unten)."),

  H.h2("Ein Array gleich mit Werten füllen: das Array-Literal"),
  H.p("Jedes Fach einzeln zu beschreiben ist umständlich, wenn du die Werte schon kennst. Dafür gibt es das Array-Literal: eine Liste von Werten in eckigen Klammern, durch Komma getrennt. Damit legst du ein fertig gefülltes Array in einer einzigen Zeile an. Welchen Typ die Fächer haben, erkennt Drachenhauch an den Werten selbst."),
  H.cmd("Array-Literal", "[wert1, wert2, ...]",
    "Erzeugt ein fertig gefülltes Array. Nur Ganzzahlen ergeben ein INTEGER-Array, Kommazahlen ein FLOAT-Array, Texte ein STRING-Array. Die Länge ist die Anzahl der Werte.",
    [
      'DIM punkte AS ARRAY OF INTEGER',
      'punkte = [42, 17, 99]',
      'PRINT punkte[0]; " "; punkte[2]; "   Länge: "; LEN(punkte)',
    ],
    { out: ["42 99   Länge: 3"] }),
  H.p("Ein Array-Literal kannst du überall einsetzen, wo ein Array erwartet wird – sogar direkt in einer Schleife, ohne es vorher einer Variablen zuzuweisen:"),
  H.code([
    'DIM summe AS INTEGER',
    'summe = 0',
    'FOR EACH n IN [10, 20, 30]',
    '    summe = summe + n',
    'NEXT',
    'PRINT summe',
  ]),
  H.code(["60"], { out: true }),
  H.note("Ein leeres Array-Literal [] ist nicht erlaubt – ohne Werte ließe sich der Typ nicht erkennen. Für ein leeres Array, das du erst nach und nach füllst, nimmst du DIM name[0] AS Typ (siehe „Arrays, die wachsen und schrumpfen“ weiter unten). Und Vorsicht: [x FOR x IN …] mit dem Schlüsselwort FOR ist KEIN Array-Literal, sondern eine „Comprehension“ – ein anderes Werkzeug, das du in einem späteren Kapitel kennenlernst."),

  H.h2("Wie viele Fächer? LEN"),
  H.p("LEN sagt dir, wie viele Elemente ein Array hat. Das brauchst du ständig – vor allem, um mit einer Schleife sicher über alle Fächer zu laufen. Weil die Indizes bei 0 beginnen, läuft die Schleife von 0 bis LEN minus 1."),
  H.cmd("LEN", "LEN(arr)",
    "Liefert die Anzahl der Elemente eines Arrays. (Bei mehrdimensionalen Arrays die Größe der ersten Dimension.)",
    [
      'DIM noten[3] AS INTEGER',
      'noten[0] = 1 : noten[1] = 3 : noten[2] = 2',
      '',
      'DIM i AS INTEGER',
      'FOR i = 0 TO LEN(noten) - 1',
      '    PRINT "Note "; i; ": "; noten[i]',
      'NEXT',
    ],
    { out: ['Note 0: 1', 'Note 1: 3', 'Note 2: 2'] }),
  H.p("Geht es dir nur um die Werte und nicht um die Indizes, ist FOR EACH noch kürzer – es reicht dir jedes Element direkt, ohne dass du mit LEN und Index hantieren musst:"),
  H.code([
    'DIM noten[3] AS INTEGER',
    'noten[0] = 1 : noten[1] = 3 : noten[2] = 2',
    '',
    'FOR EACH note IN noten',
    '    PRINT note',
    'NEXT',
  ]),
  H.code(["1", "3", "2"], { out: true }),

  H.h2("Sortieren, Umkehren, Suchen"),
  H.p("Für die häufigsten Aufgaben gibt es fertige Befehle. Wichtig: SORT und REVERSE verändern das Array direkt an Ort und Stelle (man sagt „in place“) – sie geben kein neues Array zurück, sondern krempeln das vorhandene um."),
  H.cmd("SORT  /  REVERSE", "SORT(arr)   REVERSE(arr)",
    "SORT ordnet ein eindimensionales Array aufsteigend, REVERSE kehrt die Reihenfolge um. Beide wirken direkt auf das übergebene Array. (SORT kann auch absteigend sortieren oder mit einer eigenen Vergleichsfunktion arbeiten – dazu später.)",
    [
      'DIM werte[4] AS INTEGER',
      'werte[0]=30 : werte[1]=10 : werte[2]=40 : werte[3]=20',
      '',
      'SORT(werte)',
      'PRINT werte[0]; " "; werte[1]; " "; werte[2]; " "; werte[3]',
    ],
    { out: ["10 20 30 40"] }),
  H.cmd("ARRAY_INDEXOF", "ARRAY_INDEXOF(arr, wert)",
    "Sucht den ersten Index, an dem wert steht, und liefert ihn zurück – oder -1, wenn der Wert nicht vorkommt.",
    [
      'DIM werte[3] AS INTEGER',
      'werte[0]=10 : werte[1]=20 : werte[2]=30',
      'PRINT ARRAY_INDEXOF(werte, 20)',
      'PRINT ARRAY_INDEXOF(werte, 99)',
    ],
    { out: ["1", "-1"] }),

  H.h2("Rechnen über das ganze Array: Aggregate"),
  H.p("Für Arrays aus Zahlen gibt es Befehle, die das ganze Array auf einmal auswerten – Summe, Durchschnitt, kleinster und größter Wert. Sie ersparen dir die Schleife für diese Standardfragen."),
  H.cmd("ARRAY_SUM / AVG / MIN / MAX", "ARRAY_SUM(arr)   ARRAY_AVG(arr)   ARRAY_MIN(arr)   ARRAY_MAX(arr)",
    "Liefern Summe, Durchschnitt, kleinstes und größtes Element eines Zahlen-Arrays. ARRAY_AVG ergibt immer eine Kommazahl; das Array darf für den Durchschnitt nicht leer sein.",
    [
      'DIM werte[3] AS INTEGER',
      'werte[0]=5 : werte[1]=9 : werte[2]=1',
      'PRINT ARRAY_SUM(werte)',
      'PRINT ARRAY_AVG(werte)',
      'PRINT ARRAY_MIN(werte); " "; ARRAY_MAX(werte)',
    ],
    { out: ["15", "5.0", "1 9"] }),
  H.cmd("ARRAY_FILL", "ARRAY_FILL(arr, wert)",
    "Setzt alle Fächer auf denselben Wert – praktisch, um ein Array zurückzusetzen.",
    [
      'DIM raster[4] AS INTEGER',
      'ARRAY_FILL(raster, 7)',
      'PRINT raster[0]; " "; raster[3]',
    ],
    { out: ["7 7"] }),

  H.h2("Arrays, die wachsen und schrumpfen"),
  H.p("Bisher hatten unsere Arrays eine feste Größe. Oft weißt du aber vorher nicht, wie viele Werte zusammenkommen – etwa eine Liste der aktiven Geschosse, die ständig größer und kleiner wird. Dafür kannst du ein Array dynamisch verwenden: Du legst es leer an (mit 0 Fächern) und hängst Elemente nach Bedarf an."),
  H.p("Diese Befehle verändern das Array direkt. ARRAY_PUSH hängt hinten an, ARRAY_POP nimmt das letzte wieder weg – zusammen ergeben sie einen Stapel (engl. stack), wie ein Stapel Teller, von dem du oben auflegst und oben wegnimmst."),
  H.cmd("ARRAY_PUSH  /  ARRAY_POP", "ARRAY_PUSH(arr, wert)   ARRAY_POP(arr)",
    "ARRAY_PUSH hängt einen Wert hinten an und liefert die neue Länge. ARRAY_POP entfernt das letzte Element und liefert es zurück (das Array darf dafür nicht leer sein).",
    [
      'DIM stapel[0] AS INTEGER     \' leer starten',
      'ARRAY_PUSH(stapel, 10)',
      'ARRAY_PUSH(stapel, 20)',
      'ARRAY_PUSH(stapel, 30)',
      'PRINT "Länge: "; LEN(stapel)',
      'PRINT "oben weg: "; ARRAY_POP(stapel)',
      'PRINT "jetzt Länge: "; LEN(stapel)',
    ],
    { out: ["Länge: 3", "oben weg: 30", "jetzt Länge: 2"] }),
  H.cmd("ARRAY_INSERT  /  ARRAY_REMOVE_AT", "ARRAY_INSERT(arr, idx, wert)   ARRAY_REMOVE_AT(arr, idx)",
    "ARRAY_INSERT schiebt einen Wert an Position idx ein (alles dahinter rückt nach hinten); idx darf von 0 bis zur Länge gehen. ARRAY_REMOVE_AT entfernt das Element an idx und liefert es zurück (der Rest rückt nach vorne).",
    [
      'DIM liste[0] AS INTEGER',
      'ARRAY_PUSH(liste, 10)',
      'ARRAY_PUSH(liste, 20)',
      'ARRAY_INSERT(liste, 1, 15)   \' 15 zwischen 10 und 20',
      'PRINT liste[0]; " "; liste[1]; " "; liste[2]',
      'ARRAY_REMOVE_AT(liste, 0)    \' die 10 entfernen',
      'PRINT liste[0]; " "; liste[1]',
    ],
    { out: ["10 15 20", "15 20"] }),
  H.note("REDIM(arr, länge) ändert die Größe eines Arrays nachträglich: Es wächst (neue Fächer bekommen den Standardwert) oder schrumpft (überzählige Fächer fallen weg). Vorhandene Werte bleiben dabei erhalten."),

  H.h2("Ein Stück herausschneiden: Slicing"),
  H.p("Wie bei Strings kannst du mit der Doppelpunkt-Schreibweise einen Ausschnitt eines Arrays kopieren. Die untere Grenze ist dabei, die obere nicht. Wichtig: Das Ergebnis ist eine eigenständige Kopie – Änderungen daran berühren das ursprüngliche Array nicht."),
  H.code([
    'DIM a[5] AS INTEGER',
    'a[0]=10 : a[1]=20 : a[2]=30 : a[3]=40 : a[4]=50',
    '',
    'DIM teil AS ARRAY OF INTEGER',
    'teil = a[1:4]                \' Fächer 1, 2, 3',
    'PRINT teil[0]; " "; teil[1]; " "; teil[2]',
  ]),
  H.code(["20 30 40"], { out: true }),

  H.h2("Vorsicht: Zuweisen kopiert NICHT"),
  H.p("Hier lauert ein klassischer Stolperstein, den du unbedingt verstehen solltest. Schreibst du b = a, entsteht KEINE Kopie des Arrays. Stattdessen zeigen danach beide Namen auf dasselbe Array – als hätte ein Schließfach zwei Namensschilder. Änderst du etwas über b, ändert sich auch a, denn es ist dasselbe Array."),
  H.code([
    'DIM a[2] AS INTEGER',
    'a[0] = 1 : a[1] = 2',
    '',
    'DIM b AS ARRAY OF INTEGER',
    'b = a            \' KEINE Kopie – b und a sind dasselbe Array!',
    'b[0] = 99',
    'PRINT "a[0] = "; a[0]    \' auch a hat sich geändert',
  ]),
  H.code(["a[0] = 99"], { out: true }),
  H.p("Willst du wirklich eine unabhängige Kopie – eine, die du verändern kannst, ohne das Original zu berühren – nimm ARRAY_COPY (oder ein Slice wie a[:], das ebenfalls kopiert):"),
  H.cmd("ARRAY_COPY", "ARRAY_COPY(arr)",
    "Liefert eine unabhängige Kopie des Arrays mit gleicher Form und gleichem Typ. Änderungen an der Kopie lassen das Original unangetastet.",
    [
      'DIM a[2] AS INTEGER',
      'a[0] = 1 : a[1] = 2',
      '',
      'DIM b AS ARRAY OF INTEGER',
      'b = ARRAY_COPY(a)     \' echte Kopie',
      'b[0] = 99',
      'PRINT "a[0] = "; a[0]; "   b[0] = "; b[0]',
    ],
    { out: ["a[0] = 1   b[0] = 99"] }),

  H.h2("Mehrere Dimensionen"),
  H.p("Ein Array kann auch ein Raster sein – etwa ein Schachbrett oder eine Spielkarte. Dafür gibst du mehrere Größen an, durch Komma getrennt. Ein Element sprichst du dann mit ebenso vielen Indizes an. Du kannst es dir als Tabelle mit Zeilen und Spalten vorstellen."),
  H.cmd("Mehrdimensionales Array", "DIM name[zeilen, spalten] AS Typ",
    "Legt ein Raster an. Jedes Element wird mit so vielen Indizes angesprochen, wie es Dimensionen gibt. DIMCOUNT liefert die Anzahl der Dimensionen, DIMSIZE(arr, n) die Größe der n-ten.",
    [
      'DIM brett[3, 3] AS INTEGER',
      'brett[1, 2] = 7',
      'PRINT brett[1, 2]',
      'PRINT DIMCOUNT(brett)',
      'PRINT DIMSIZE(brett, 0); " x "; DIMSIZE(brett, 1)',
    ],
    { out: ["7", "2", "3 x 3"] }),
  H.p("Über ein zweidimensionales Array läufst du mit zwei verschachtelten Schleifen – die äußere über die Zeilen, die innere über die Spalten. Genau dieses Muster brauchst du später, um eine Kachelkarte oder ein Spielfeld zu zeichnen."),

  H.tip("Arrays oder Map?", "Ein Array nummeriert seine Werte mit ganzen Zahlen ab 0 – ideal, wenn die Reihenfolge zählt oder du der Reihe nach durchläufst. Brauchst du stattdessen benannte Schlüssel (\"spieler1\" → 42), ist eine Map die bessere Wahl. Die lernst du im nächsten Kapitel kennen."),
];
