module.exports = (H) => [
  H.chapter("Maps"),
  H.p("Ein Array nummeriert seine Werte mit ganzen Zahlen: 0, 1, 2, … Das ist perfekt, solange die Position der natürliche Zugang ist. Aber manchmal willst du Werte nicht über eine Nummer ansprechen, sondern über einen Namen: die Punktzahl von „Anna“, den Bestand an „Holz“, die Einstellung „lautstärke“. Genau dafür gibt es die Map."),
  H.p("Eine Map ist eine Sammlung von Paaren aus Schlüssel und Wert. Stell sie dir wie ein Wörterbuch vor: Du schlägst ein Stichwort nach (den Schlüssel) und bekommst die zugehörige Erklärung (den Wert). Oder wie ein Telefonbuch – Name nachschlagen, Nummer erhalten. Der Schlüssel ersetzt die Index-Nummer des Arrays durch etwas Sprechendes."),
  H.note("In Drachenhauch sind die Schlüssel einer Map IMMER Strings. Die Werte dagegen haben den Typ, den du bei DIM angibst – MAP OF INTEGER speichert Zahlen, MAP OF STRING speichert Texte, und so weiter."),

  H.h2("Eine Map anlegen und füllen"),
  H.p("Deklariert wird eine Map mit DIM ... AS MAP OF Typ. Frisch angelegt ist sie leer. Mit MAPPUT legst du ein Paar ab: Du nennst den Schlüssel und den Wert. Gibt es den Schlüssel schon, wird sein alter Wert überschrieben – jeder Schlüssel kommt also nur einmal vor."),
  H.cmd("MAPPUT", 'MAPPUT(m, schlüssel$, wert)',
    "Legt unter dem Schlüssel einen Wert ab oder überschreibt den bestehenden. Der Schlüssel ist ein String, der Wert hat den Typ der Map.",
    [
      'DIM punkte AS MAP OF INTEGER',
      'MAPPUT(punkte, "Anna", 95)',
      'MAPPUT(punkte, "Bert", 78)',
      'MAPPUT(punkte, "Anna", 100)   \' überschreibt die 95',
      '',
      'PRINT MAPSIZE(punkte)',
    ],
    { out: ["2"] }),

  H.h2("Einen Wert nachschlagen"),
  H.p("Mit MAPGET holst du den Wert zu einem Schlüssel. Hier musst du aufpassen: Fragst du nach einem Schlüssel, den es gar nicht gibt, bricht MAPGET mit einem Fehler ab. Das ist Absicht – meist ist ein fehlender Schlüssel an dieser Stelle ein echter Programmfehler, den du sofort bemerken willst."),
  H.cmd("MAPGET", 'MAPGET(m, schlüssel$)',
    "Liefert den Wert zum Schlüssel. Existiert der Schlüssel nicht, wird ein Fehler ausgelöst – prüfe im Zweifel vorher mit MAPHAS oder nutze MAPGETOR.",
    [
      'DIM punkte AS MAP OF INTEGER',
      'MAPPUT(punkte, "Anna", 95)',
      'PRINT MAPGET(punkte, "Anna")',
    ],
    { out: ["95"] }),
  H.p("Damit dir ein fehlender Schlüssel nicht das Programm abschießt, gibt es zwei sichere Wege. MAPHAS prüft, ob ein Schlüssel überhaupt vorhanden ist. Und MAPGETOR liefert einen selbst gewählten Ersatzwert, falls der Schlüssel fehlt – sehr praktisch für Standardwerte."),
  H.cmd("MAPHAS", 'MAPHAS(m, schlüssel$)',
    "Liefert TRUE, wenn der Schlüssel in der Map vorhanden ist, sonst FALSE. Dasselbe leistet der IN-Operator: schlüssel$ IN m.",
    [
      'DIM punkte AS MAP OF INTEGER',
      'MAPPUT(punkte, "Anna", 95)',
      'PRINT MAPHAS(punkte, "Anna")',
      'PRINT "Zoe" IN punkte',
    ],
    { out: ["TRUE", "FALSE"] }),
  H.cmd("MAPGETOR", 'MAPGETOR(m, schlüssel$, ersatz)',
    "Liefert den Wert zum Schlüssel – oder den Ersatzwert, falls der Schlüssel fehlt. Bricht nie ab.",
    [
      'DIM punkte AS MAP OF INTEGER',
      'MAPPUT(punkte, "Anna", 95)',
      'PRINT MAPGETOR(punkte, "Anna", 0)',
      'PRINT MAPGETOR(punkte, "Eve", 0)   \' Eve fehlt → 0',
    ],
    { out: ["95", "0"] }),

  H.h2("Größe, Entfernen, Leeren"),
  H.cmd("MAPSIZE / MAPREMOVE / MAPCLEAR", 'MAPSIZE(m)   MAPREMOVE(m, schlüssel$)   MAPCLEAR(m)',
    "MAPSIZE liefert die Anzahl der Paare. MAPREMOVE löscht ein Paar und gibt TRUE zurück, wenn es den Schlüssel gab. MAPCLEAR leert die ganze Map.",
    [
      'DIM lager AS MAP OF INTEGER',
      'MAPPUT(lager, "Holz", 5)',
      'MAPPUT(lager, "Stein", 3)',
      'PRINT MAPREMOVE(lager, "Holz")',
      'PRINT MAPSIZE(lager)',
    ],
    { out: ["TRUE", "1"] }),

  H.h2("Über alle Paare laufen"),
  H.p("Oft willst du jedes Paar einer Map nacheinander bearbeiten – etwa eine Rangliste ausgeben. Dafür gibt es mehrere Wege. Am direktesten läufst du mit FOR EACH über die Map: Die Schleifenvariable bekommt dann nacheinander jeden SCHLÜSSEL, und über MAPGET holst du dir den passenden Wert."),
  H.note("Die Paare erscheinen in der Reihenfolge, in der du sie eingefügt hast – die erste eingefügte zuerst. Darauf kannst du dich verlassen."),
  H.code([
    'DIM punkte AS MAP OF INTEGER',
    'MAPPUT(punkte, "Anna", 95)',
    'MAPPUT(punkte, "Bert", 78)',
    'MAPPUT(punkte, "Cilly", 99)',
    '',
    'FOR EACH name IN punkte',
    '    PRINT name; ": "; MAPGET(punkte, name)',
    'NEXT',
  ]),
  H.code(["Anna: 95", "Bert: 78", "Cilly: 99"], { out: true }),
  H.p("Brauchst du die Schlüssel als Array (etwa um sie zu sortieren), liefert sie dir MAPKEYS. MAPVALUES gibt entsprechend alle Werte, und MAPITEMS alle Paare als kleine Zweier-Bündel (Tupel) aus Schlüssel und Wert:"),
  H.cmd("MAPKEYS / MAPVALUES / MAPITEMS", 'MAPKEYS(m)   MAPVALUES(m)   MAPITEMS(m)',
    "MAPKEYS liefert ein Array aller Schlüssel, MAPVALUES ein Array aller Werte, MAPITEMS ein Array von (Schlüssel, Wert)-Tupeln. Alle in Einfüge-Reihenfolge.",
    [
      'DIM lager AS MAP OF INTEGER',
      'MAPPUT(lager, "Holz", 5)',
      'MAPPUT(lager, "Stein", 3)',
      '',
      'FOR EACH paar IN MAPITEMS(lager)',
      '    PRINT paar[0]; " -> "; paar[1]',
      'NEXT',
    ],
    { out: ["Holz -> 5", "Stein -> 3"] }),
  H.p("In paar[0] steckt jeweils der Schlüssel, in paar[1] der Wert – die beiden Hälften des Paares."),

  H.h2("Auch als Methode aufrufbar"),
  H.p("Wie bei Strings gibt es die meisten Map-Befehle auch in Punkt-Schreibweise, direkt an die Map gehängt. Welche Form du nimmst, ist Geschmackssache – sie tun dasselbe."),
  H.code([
    'DIM lager AS MAP OF INTEGER',
    'lager.put("Holz", 5)',
    'PRINT lager.get("Holz")',
    'PRINT lager.has("Stein")',
    'PRINT lager.getor("Gold", 0)',
    'PRINT lager.size()',
  ]),
  H.code(["5", "FALSE", "0", "1"], { out: true }),

  H.h2("Was, wenn der Schlüssel eine Zahl ist?"),
  H.p("Map-Schlüssel müssen Strings sein. Willst du trotzdem über eine Zahl nachschlagen – etwa einen Wert pro Spieler-Nummer zwischenspeichern – wandle die Zahl einfach mit STR$ in einen String um. Das ist ein häufiges Muster, zum Beispiel bei einem Zwischenspeicher (Cache), der schon berechnete Ergebnisse merkt, damit sie nicht doppelt berechnet werden müssen:"),
  H.code([
    'DIM cache AS MAP OF INTEGER',
    'DIM n AS INTEGER',
    'n = 12',
    '',
    'IF MAPHAS(cache, STR$(n)) THEN',
    '    PRINT "schon bekannt"',
    'ELSE',
    '    MAPPUT(cache, STR$(n), n * n)',
    '    PRINT "berechnet: "; MAPGET(cache, STR$(n))',
    'END IF',
  ]),
  H.code(["berechnet: 144"], { out: true }),

  H.warn("Wie ein Array ist eine Map ein Verweis-Wert: Schreibst du b = a, zeigen danach beide Namen auf DIESELBE Map – eine Änderung über b wirkt auch auf a. Das ist derselbe Stolperstein wie bei Arrays (siehe Kapitel „Arrays“). Brauchst du eine echte Kopie, baue sie dir mit einer Schleife über MAPITEMS neu auf."),

  H.tip("Array oder Map?", "Frag dich, wie du an deine Werte heran willst. Über eine laufende Nummer und in fester Reihenfolge? → Array. Über einen sprechenden Namen? → Map. Beide lassen sich übrigens kombinieren: eine MAP OF (ARRAY …) oder ein Array von Maps ist völlig in Ordnung."),
];
