module.exports = (H) => [
  H.chapter("Klassen & Objekte"),
  H.p("Bis hierhin hast du mit einzelnen Werten gearbeitet – Zahlen, Strings, Arrays. Doch in einem Spiel gehören viele Dinge eng zusammen: Ein Gegner hat eine Position, Lebenspunkte, einen Namen und ein Verhalten. Diese Daten in lose nebeneinanderliegenden Variablen zu verwalten (gegner_x, gegner_y, gegner_hp …) wird schnell unübersichtlich – erst recht, wenn es viele Gegner gibt."),
  H.p("Die objektorientierte Programmierung bietet eine aufgeräumtere Idee: Du fasst zusammengehörige Daten UND die dazu passenden Tätigkeiten in einem einzigen Gebilde zusammen – einer Klasse. Dieses Kapitel führt dich Schritt für Schritt heran. Lass dir Zeit; das Konzept ist mächtig und am Anfang ungewohnt, aber sobald der Groschen fällt, willst du es nicht mehr missen."),

  H.h2("Bauplan und Objekt – der zentrale Gedanke"),
  H.p("Stell dir eine Klasse wie einen Bauplan vor – etwa den Bauplan für ein Haus. Der Plan selbst ist kein Haus; er beschreibt nur, wie ein Haus aussehen soll: wie viele Zimmer es hat, welche Farbe, welche Türen. Aus EINEM Plan kannst du beliebig viele echte Häuser bauen, und jedes ist ein eigenständiges Ding mit eigenen Werten."),
  H.p("Genauso ist es hier: Die Klasse ist der Bauplan, das fertige Ding nennt man ein Objekt (oder eine Instanz). Du schreibst die Klasse einmal und erzeugst daraus dann so viele Objekte, wie du brauchst – jeder Gegner ein eigenes Objekt, mit eigenen Lebenspunkten, aber alle nach demselben Plan gebaut."),
  H.bulletRich("Klasse  ", "= der Bauplan. Beschreibt, welche Daten (Felder) und welche Tätigkeiten (Methoden) ein Objekt hat."),
  H.bulletRich("Objekt  ", "= ein konkretes, aus dem Plan gebautes Exemplar mit eigenen Werten."),

  H.h2("Eine Klasse definieren"),
  H.p("Eine Klasse schreibst du zwischen CLASS und END CLASS. Darin stehen zunächst ihre Felder – das sind Variablen, die jedes Objekt für sich besitzt. Du deklarierst sie wie gewohnt mit DIM. Hier ein einfacher Spieler mit Name und Lebenspunkten:"),
  H.code([
    'CLASS Spieler',
    '    DIM name AS STRING',
    '    DIM hp AS INTEGER',
    'END CLASS',
  ]),
  H.p("Das allein erzeugt noch nichts – es beschreibt nur den Bauplan. Jeder gebaute Spieler wird ein eigenes name- und ein eigenes hp-Feld haben."),

  H.h2("Ein Objekt erzeugen: NEW"),
  H.p("Aus dem Bauplan baust du ein echtes Objekt mit dem Schlüsselwort NEW. Das Ergebnis legst du in einer Variablen ab, deren Typ der Klassenname ist. Frisch gebaut tragen die Felder ihre Standardwerte (0 bei Zahlen, leerer Text bei Strings)."),
  H.code([
    'DIM held AS Spieler        \' eine Variable vom Typ Spieler',
    'held = NEW Spieler()       \' ein Objekt bauen',
    '',
    'held.name = "Mario"        \' Felder über den Punkt ansprechen',
    'held.hp = 100',
    'PRINT held.name; " hat "; held.hp; " HP"',
  ]),
  H.code(["Mario hat 100 HP"], { out: true }),
  H.p("Den Punkt kennst du schon von den Methoden auf Strings und Maps. Bei Objekten führt er dich zu einem Feld (held.hp) oder gleich zu einer Tätigkeit (held.NimmSchaden(...), siehe unten)."),

  H.h2("Der Konstruktor: SUB Init"),
  H.p("Es ist mühsam, nach jedem NEW alle Felder von Hand zu setzen. Dafür gibt es einen besonderen Baustein: eine SUB mit dem Namen Init. Sie wird automatisch ausgeführt, sobald du ein Objekt mit NEW erzeugst – und ihre Argumente gibst du direkt beim NEW an. Man nennt sie den Konstruktor („den Erbauer“)."),
  H.p("In der Init-Methode (und in allen Methoden) brauchst du einen Weg, um „das gerade gebaute Objekt“ anzusprechen. Dafür gibt es das Schlüsselwort Self – es bedeutet immer „dieses Objekt hier, an dem ich gerade arbeite“. Self.hp = 100 setzt also das hp-Feld genau dieses einen Objekts."),
  H.code([
    'CLASS Spieler',
    '    DIM name AS STRING',
    '    DIM hp AS INTEGER',
    '',
    '    SUB Init(n AS STRING)',
    '        Self.name = n        \' das Feld dieses Objekts ...',
    '        Self.hp = 100        \' ... mit Startwerten füllen',
    '    END SUB',
    'END CLASS',
    '',
    'DIM held AS Spieler',
    'held = NEW Spieler("Mario")  \' Init läuft mit n = "Mario"',
    'PRINT held.name; " hat "; held.hp; " HP"',
  ]),
  H.code(["Mario hat 100 HP"], { out: true }),
  H.note("Self verweist immer auf das Objekt, für das die Methode gerade läuft. Rufst du held.NimmSchaden(...) auf, ist Self innerhalb der Methode der held; rufst du gegner.NimmSchaden(...) auf, ist Self der gegner. So arbeitet derselbe Methoden-Code für jedes Objekt mit dessen eigenen Daten."),

  H.h2("Methoden: Tätigkeiten der Klasse"),
  H.p("Bis jetzt hat unsere Klasse nur Daten. Das eigentlich Spannende sind Methoden: Funktionen und SUBs, die INNERHALB der Klasse stehen und auf deren Feldern arbeiten. Eine Methode definierst du genau wie eine normale SUB oder FUNCTION (Kapitel „Funktionen & SUBs“) – nur eben im Klassen-Body und mit Zugriff auf Self."),
  H.p("Erweitern wir den Spieler um Verhalten: Schaden nehmen, prüfen ob er noch lebt, seinen Status ausgeben."),
  H.code([
    'CLASS Spieler',
    '    DIM name AS STRING',
    '    DIM hp AS INTEGER',
    '',
    '    SUB Init(n AS STRING)',
    '        Self.name = n',
    '        Self.hp = 100',
    '    END SUB',
    '',
    '    SUB NimmSchaden(menge AS INTEGER)',
    '        Self.hp = Self.hp - menge',
    '        IF Self.hp < 0 THEN Self.hp = 0',
    '    END SUB',
    '',
    '    FUNCTION IstAmLeben() AS BOOLEAN',
    '        RETURN Self.hp > 0',
    '    END FUNCTION',
    '',
    '    SUB Status()',
    '        PRINT Self.name; ": "; Self.hp; " HP"',
    '    END SUB',
    'END CLASS',
  ]),
  H.p("Jetzt kannst du dem Objekt Befehle geben, indem du die Methode mit dem Punkt aufrufst. Das liest sich fast wie ein Satz: „held, nimm 30 Schaden.“"),
  H.code([
    'DIM held AS Spieler',
    'held = NEW Spieler("Mario")',
    'held.Status()',
    'held.NimmSchaden(30)',
    'held.Status()',
    'PRINT "Noch am Leben? "; held.IstAmLeben()',
    'held.NimmSchaden(100)        \' mehr als die restlichen HP',
    'held.Status()',
    'PRINT "Noch am Leben? "; held.IstAmLeben()',
  ]),
  H.code([
    "Mario: 100 HP",
    "Mario: 70 HP",
    "Noch am Leben? TRUE",
    "Mario: 0 HP",
    "Noch am Leben? FALSE",
  ], { out: true }),
  H.note("Innerhalb einer Methode darfst du eine andere Methode derselben Klasse auch ohne Self. aufrufen – ein bloßes Reset() genügt und ist dasselbe wie Self.Reset(). Beides ist erlaubt; das Self. macht nur besonders deutlich, dass es um eine Methode des eigenen Objekts geht."),

  H.h2("Viele Objekte, jedes für sich"),
  H.p("Der ganze Sinn eines Bauplans ist, dass du daraus viele eigenständige Objekte baust. Jedes hat seinen eigenen Satz Felder – verändere das eine, bleibt das andere unberührt. So verwaltest du mühelos einen ganzen Schwung Spieler oder Gegner, alle mit derselben Klasse:"),
  H.code([
    'DIM held AS Spieler',
    'DIM gegner AS Spieler',
    'held = NEW Spieler("Mario")',
    'gegner = NEW Spieler("Goomba")',
    '',
    'held.NimmSchaden(40)         \' nur der Held nimmt Schaden',
    'held.Status()',
    'gegner.Status()              \' der Gegner ist unberührt',
  ]),
  H.code(["Mario: 60 HP", "Goomba: 100 HP"], { out: true }),

  H.warn("Ein Objekt ist – wie Array und Map – ein Verweis-Wert. Schreibst du zweiterHeld = held, entsteht KEINE Kopie: Beide Namen zeigen auf dasselbe Objekt, und eine Änderung über den einen wirkt auch auf den anderen. Willst du einen echten zweiten Spieler, baue ihn mit einem eigenen NEW."),

  H.tip("Wann eine eigene Klasse?", "Eine Klasse lohnt sich, sobald mehrere Daten zusammengehören und es Tätigkeiten gibt, die auf ihnen arbeiten – ein Spieler, ein Gegner, ein Item, eine Spielkarte. Faustregel: Wenn du dich bei Variablennamen mit gleichem Präfix ertappst (spieler_x, spieler_y, spieler_hp), ist das fast immer der Ruf nach einer Klasse. Im nächsten Kapitel geht es weiter mit Vererbung, Properties, Operatoren und statischen Mitgliedern."),
];
