module.exports = (H) => [
  H.chapter("Vererbung, Properties, Operatoren & Static"),
  H.p("Im letzten Kapitel hast du Klassen und Objekte kennengelernt. Jetzt kommen vier fortgeschrittene Werkzeuge dazu, die das Klassen-System richtig mächtig machen: Vererbung (Klassen bauen auf anderen auf), Properties (kontrollierter Zugriff auf Felder), Operator-Überladung (eigene Typen mit + und = verbinden) und statische Mitglieder (Werte, die zur Klasse selbst gehören). Jedes ist ein eigenes Thema – nimm sie dir der Reihe nach vor."),

  H.h2("Vererbung: auf einer Klasse aufbauen"),
  H.p("Oft sind sich mehrere Klassen ähnlich: Ein Hund und eine Katze sind beide Tiere – sie haben einen Namen und können ein Geräusch machen, unterscheiden sich aber im Detail. Statt alles doppelt zu schreiben, definierst du eine allgemeine Basisklasse (Tier) und leitest davon speziellere Klassen ab. Die abgeleitete Klasse erbt alle Felder und Methoden der Basis und kann eigene hinzufügen."),
  H.p("Abgeleitet wird mit dem Schlüsselwort EXTENDS. Man sagt: Hund ist eine Unterklasse von Tier, Tier ist die Oberklasse. Ein Hund hat damit automatisch auch alles, was ein Tier hat."),
  H.cmd("EXTENDS", "CLASS Unterklasse EXTENDS Oberklasse",
    "Leitet eine Klasse von einer anderen ab. Die Unterklasse erbt deren Felder und Methoden und kann eigene ergänzen. Auf geerbte Felder greifst du genauso über Self zu.",
    [
      'CLASS Tier',
      '    DIM name AS STRING',
      '    SUB Init(n AS STRING)',
      '        Self.name = n',
      '    END SUB',
      '    FUNCTION Beschreibung() AS STRING',
      '        RETURN "Tier namens " + Self.name',
      '    END FUNCTION',
      'END CLASS',
      '',
      'CLASS Hund EXTENDS Tier',
      '    \' erbt name, Init und Beschreibung von Tier',
      'END CLASS',
      '',
      'DIM rex AS Hund',
      'rex = NEW Hund("Rex")        \' geerbtes Init läuft',
      'PRINT rex.Beschreibung()     \' geerbte Methode',
    ],
    { out: ['Tier namens Rex'] }),

  H.h2("Methoden überschreiben"),
  H.p("Eine Unterklasse kann eine geerbte Methode neu definieren – das nennt man überschreiben. Sie ersetzt damit für ihre Objekte die Version der Oberklasse. So macht jedes Tier auf seine eigene Art ein Geräusch, obwohl die Methode überall Sprich heißt."),
  H.code([
    'CLASS Tier',
    '    DIM name AS STRING',
    '    SUB Init(n AS STRING)',
    '        Self.name = n',
    '    END SUB',
    '    SUB Sprich()',
    '        PRINT Self.name; " macht ein Geräusch."',
    '    END SUB',
    'END CLASS',
    '',
    'CLASS Hund EXTENDS Tier',
    '    SUB Sprich()                       \' überschreibt Tier.Sprich',
    '        PRINT Self.name; " bellt: WAU!"',
    '    END SUB',
    'END CLASS',
    '',
    'DIM rex AS Hund',
    'rex = NEW Hund("Rex")',
    'rex.Sprich()',
  ]),
  H.code(["Rex bellt: WAU!"], { out: true }),
  H.note("Überschreibt eine Unterklasse die Init-Methode, wird die Init der Oberklasse NICHT automatisch zusätzlich aufgerufen – die neue Init ersetzt sie ganz. Setze die geerbten Felder dann in deiner eigenen Init selbst. Brauchst du die Eltern-Vorbereitung nicht zu ändern, definiere einfach kein eigenes Init und das geerbte läuft."),

  H.h2("Polymorphie: ein Typ, viele Gestalten"),
  H.p("Hier wird Vererbung erst richtig nützlich. Eine Variable vom Typ der Oberklasse darf auch Objekte der Unterklassen aufnehmen – schließlich ist ein Hund ein Tier. Rufst du dann eine Methode auf, läuft automatisch die Version, die zum tatsächlichen Objekt gehört. Dieses „der passende Code wird zur Laufzeit gewählt“ heißt Polymorphie (Vielgestaltigkeit)."),
  H.p("Das erlaubt dir, ganz verschiedene Objekte gleich zu behandeln – etwa alle Wesen in einer Liste durchzugehen und jedem einfach Sprich() zu sagen, ohne zu wissen, ob es ein Hund oder eine Katze ist:"),
  H.code([
    'CLASS Tier',
    '    DIM name AS STRING',
    '    SUB Init(n AS STRING)',
    '        Self.name = n',
    '    END SUB',
    '    SUB Sprich()',
    '        PRINT Self.name; " macht ein Geräusch."',
    '    END SUB',
    'END CLASS',
    'CLASS Hund EXTENDS Tier',
    '    SUB Sprich()',
    '        PRINT Self.name; " bellt: WAU!"',
    '    END SUB',
    'END CLASS',
    'CLASS Katze EXTENDS Tier',
    '    SUB Sprich()',
    '        PRINT Self.name; " miaut: MIAU!"',
    '    END SUB',
    'END CLASS',
    '',
    'DIM t AS Tier              \' Typ der Oberklasse',
    't = NEW Hund("Rex")',
    't.Sprich()                 \' die Hund-Version läuft',
    't = NEW Katze("Mia")',
    't.Sprich()                 \' die Katze-Version läuft',
  ]),
  H.code(["Rex bellt: WAU!", "Mia miaut: MIAU!"], { out: true }),

  H.h2("Properties: Felder mit Wächter"),
  H.p("Manchmal willst du nicht, dass jeder Code ein Feld direkt und ungeprüft verändert. Beispiel: Die Lebenspunkte sollen nie unter 0 oder über 100 gehen. Eine Property sieht von außen aus wie ein normales Feld (du schreibst objekt.hp = 200), führt beim Lesen und Schreiben aber heimlich deinen Code aus – einen Wächter, der prüfen, begrenzen oder umrechnen kann."),
  H.p("Dazu schreibst du zwei besondere Blöcke: PROPERTY GET liefert den Wert beim Lesen, PROPERTY SET nimmt ihn beim Schreiben entgegen (der zugewiesene Wert steht in value). Das eigentliche Feld versteckst du üblicherweise hinter einem Namen mit Unterstrich, etwa _hp."),
  H.cmd("PROPERTY GET / SET", "PROPERTY GET name() AS Typ ... END PROPERTY\nPROPERTY SET name(value AS Typ) ... END PROPERTY",
    "Definiert kontrollierten Lese- und Schreibzugriff. GET läuft beim Lesen von objekt.name, SET beim Zuweisen objekt.name = ... (der neue Wert kommt als value). Definierst du nur GET, ist die Property nur lesbar; nur SET macht sie nur schreibbar.",
    [
      'CLASS Spieler',
      '    DIM _hp AS INTEGER',
      '',
      '    PROPERTY GET hp() AS INTEGER',
      '        RETURN Self._hp',
      '    END PROPERTY',
      '',
      '    PROPERTY SET hp(value AS INTEGER)',
      '        IF value < 0 THEN value = 0',
      '        IF value > 100 THEN value = 100',
      '        Self._hp = value',
      '    END PROPERTY',
      'END CLASS',
      '',
      'DIM p AS Spieler',
      'p = NEW Spieler()',
      'p.hp = 200        \' der Setter begrenzt auf 100',
      'PRINT p.hp',
      'p.hp = -50        \' der Setter hebt auf 0 an',
      'PRINT p.hp',
    ],
    { out: ["100", "0"] }),

  H.h2("Operatoren überladen"),
  H.p("Für eigene Klassen, die mathematische Werte darstellen – Geldbeträge, Vektoren, Brüche –, kannst du festlegen, was +, -, =, < und so weiter zwischen zwei Objekten bedeuten. Das nennt man Operator-Überladung. Statt geld_a.Plus(geld_b) schreibst du dann einfach geld_a + geld_b – viel natürlicher."),
  H.p("Dazu definierst du im Klassen-Body einen OPERATOR-Block: wie eine Methode, aber statt eines Namens steht das Operator-Zeichen dort. Er bekommt genau einen Parameter (den rechten Operanden) und einen Rückgabetyp."),
  H.cmd("OPERATOR", "OPERATOR zeichen (other AS Typ) AS Rückgabetyp ... END OPERATOR",
    "Legt fest, wie ein Operator zwischen Objekten dieser Klasse wirkt. Erlaubt sind +, -, *, /, MOD, =, <>, <, >, <=, >=. Der eine Parameter ist der rechte Operand; Self ist der linke.",
    [
      'CLASS Geld',
      '    DIM cent AS INTEGER',
      '',
      '    OPERATOR + (other AS Geld) AS Geld',
      '        DIM r AS Geld',
      '        r = NEW Geld()',
      '        r.cent = Self.cent + other.cent',
      '        RETURN r',
      '    END OPERATOR',
      'END CLASS',
      '',
      'DIM a AS Geld',
      'DIM b AS Geld',
      'a = NEW Geld()',
      'b = NEW Geld()',
      'a.cent = 150',
      'b.cent = 250',
      'PRINT (a + b).cent',
    ],
    { out: ["400"] }),
  H.note("Pro Operator gibt es genau eine Definition – ein Mischen von Geld + Geld und Geld + INTEGER in zwei getrennten Blöcken ist nicht möglich. Überladene Operatoren werden wie Methoden mitvererbt. Für fertige mathematische Typen liefert GameBasic übrigens schon Module mit, etwa vec2 für 2D-Vektoren (Teil V)."),

  H.h2("Statische Mitglieder: zur Klasse, nicht zum Objekt"),
  H.p("Bisher gehörte jedes Feld einem Objekt. Manche Werte gehören aber zur Klasse als Ganzes – feste Kennzahlen, die für alle Objekte gleich sind und kein Objekt zum Nachschlagen brauchen: die maximale Lebenspunktzahl, der Spielname, die Schwerkraft. Dafür gibt es STATIC CONST. Du sprichst sie über den Klassennamen an, ohne je ein Objekt zu erzeugen."),
  H.cmd("STATIC CONST", "STATIC CONST NAME AS Typ = wert",
    "Definiert eine zur Klasse gehörende Konstante, abrufbar als Klassenname.NAME. Der Wert muss ein fester Literalwert sein (Zahl, String, Wahrheitswert). So bündelst du feste Kennzahlen sauber bei ihrer Klasse statt in losen globalen Konstanten.",
    [
      'CLASS Config',
      '    STATIC CONST MAX_HP AS INTEGER = 100',
      '    STATIC CONST SPIELNAME AS STRING = "GameBasic"',
      'END CLASS',
      '',
      'PRINT Config.MAX_HP',
      'PRINT Config.SPIELNAME',
    ],
    { out: ["100", "GameBasic"] }),
  H.p("Innerhalb einer Methode der Klasse greifst du genauso zu (Config.MAX_HP). Statische Konstanten sind fest – sie lassen sich zur Laufzeit nicht überschreiben. Brauchst du veränderlichen, geteilten Zustand, nimm stattdessen eine globale Variable."),

  H.tip("Nicht übertreiben", "Vererbung, Properties und Operatoren sind starke Werkzeuge – aber nicht jedes Programm braucht sie. Fang ruhig mit schlichten Klassen aus Feldern und Methoden an (Kapitel 20). Greife zu Vererbung, wenn echte „ist ein“-Beziehungen vorliegen (ein Hund IST ein Tier), zu Properties bei Werten mit Regeln, zu Operatoren nur bei echten Rechen-Typen. Klarheit schlägt Cleverness."),
];
