module.exports = (H) => [
  H.chapter("ENUM"),
  H.p("Programme stecken voller Zustände und Kategorien: Ein Spiel ist im Menü, läuft gerade oder ist pausiert. Solche Fälle könntest du mit Zahlen darstellen (0 = Menü, 1 = läuft, 2 = Pause) – aber wer merkt sich, dass 2 für Pause steht? Ein ENUM (kurz für „Enumeration“, Aufzählung) gibt diesen Zahlen sprechende Namen. Dein Code wird dadurch lesbar und unverwechselbar."),

  H.h2("Ein ENUM definieren"),
  H.p("Im einfachsten Fall zählst du die Namen kompakt in einer Zeile auf. Drachenhauch vergibt automatisch die Zahlen 0, 1, 2 und so weiter. Angesprochen werden die Werte über den ENUM-Namen mit Punkt – also Status.MENU. Diese Schreibweise macht sofort klar, worum es geht."),
  H.cmd("ENUM (kompakt)", "ENUM Name = WERT1, WERT2, ...",
    "Definiert eine Aufzählung. Die Mitglieder bekommen der Reihe nach die Werte 0, 1, 2, … und werden als Name.MITGLIED angesprochen.",
    [
      'ENUM Status = MENU, SPIELT, PAUSE',
      '',
      'PRINT Status.MENU',
      'PRINT Status.SPIELT',
      'PRINT Status.PAUSE',
    ],
    { out: ["0", "1", "2"] }),

  H.h2("Eigene Werte vergeben"),
  H.p("Brauchst du bestimmte Zahlen – etwa weil sie zu Daten von außen passen müssen –, schreibst du das ENUM als Block und gibst jedem Mitglied seinen Wert. Das liest sich übersichtlich, sobald es mehr Einträge werden."),
  H.cmd("ENUM (Block)", "ENUM Name\n    MITGLIED = wert\n    ...\nEND ENUM",
    "Block-Schreibweise mit ausdrücklichen Werten. Lässt du bei einem Mitglied den Wert weg, zählt Drachenhauch vom letzten vergebenen Wert um eins weiter.",
    [
      'ENUM Recht',
      '    KEINS = 0',
      '    LESEN = 1',
      '    SCHREIBEN = 2',
      '    ADMIN = 99',
      'END ENUM',
      '',
      'PRINT Recht.SCHREIBEN',
      'PRINT Recht.ADMIN',
    ],
    { out: ["2", "99"] }),
  H.p("Du darfst beide Stile mischen: Nach einem ausdrücklich gesetzten Wert zählt die automatische Nummerierung von dort weiter. Im folgenden ENUM ist A also 0, B wird auf 5 gesetzt, und C bekommt daraufhin 6:"),
  H.code([
    'ENUM Misch = A, B = 5, C',
    'PRINT Misch.A; " "; Misch.B; " "; Misch.C',
  ]),
  H.code(["0 5 6"], { out: true }),

  H.h2("ENUMs im Einsatz"),
  H.p("Eine Variable, die einen ENUM-Wert halten soll, deklarierst du mit dem ENUM-Namen als Typ (intern ist das eine ganze Zahl). Besonders gut passen ENUMs zu SELECT CASE: Die Fälle tragen sprechende Namen, und du siehst auf einen Blick, dass alle Zustände abgedeckt sind."),
  H.code([
    'ENUM Status = MENU, SPIELT, PAUSE',
    '',
    'DIM s AS Status',
    's = Status.SPIELT',
    '',
    'SELECT CASE s',
    '    CASE Status.MENU',
    '        PRINT "im Menü"',
    '    CASE Status.SPIELT',
    '        PRINT "spielt gerade"',
    '    CASE Status.PAUSE',
    '        PRINT "pausiert"',
    'END SELECT',
  ]),
  H.code(["spielt gerade"], { out: true }),
  H.note("Die Mitglieds-Namen dürfen sogar mit Schlüsselwörtern übereinstimmen (READ, DATA, NEW …). Weil sie immer hinter dem ENUM-Namen und einem Punkt stehen (Befehl.READ), ist eindeutig, dass kein Befehl gemeint ist."),

  H.tip("ENUM oder STATIC CONST?", "Beide ersetzen „magische Zahlen“ durch Namen. Nimm ein ENUM für eine zusammengehörige Gruppe sich gegenseitig ausschließender Möglichkeiten (die Spielzustände, die Himmelsrichtungen). Eine STATIC CONST (Kapitel 21) passt besser für eine einzelne feste Kennzahl, die zu einer bestimmten Klasse gehört."),
];
