module.exports = (H) => [
  H.chapter("Comprehensions"),
  H.p("Sehr oft will man aus einer vorhandenen Sammlung eine neue bauen: aus einer Liste von Zahlen die Liste ihrer Quadrate, aus allen Spielern nur die mit genug Punkten. Das geht natürlich mit einer Schleife. Comprehensions sind eine kürzere, gut lesbare Kurzschreibweise für genau dieses Muster – „nimm jedes Element und mache etwas damit“ – alles in einer einzigen Zeile."),
  H.p("Der Begriff klingt sperrig, die Idee ist einfach. Lies eine Comprehension wie einen Satz: „Bilde n mal n, für jedes n in zahlen.“ Genau in dieser Reihenfolge steht es auch da."),

  H.h2("List-Comprehension"),
  H.p("Die Grundform steht in eckigen Klammern und besteht aus zwei Teilen: vorne der Ausdruck, der für jedes Element berechnet wird, dahinter das FOR, das die Sammlung durchläuft. Das Ergebnis ist ein Tupel mit allen berechneten Werten (Tupel kennst du aus Kapitel „Tupel & Destructuring“ – sie sind unveränderlich)."),
  H.cmd("List-Comprehension", "[ ausdruck FOR variable IN sammlung ]",
    "Berechnet den Ausdruck für jedes Element der Sammlung und sammelt die Ergebnisse in einem Tupel. Als Sammlung dienen Tupel, Arrays, die Zeichen eines Strings oder die Schlüssel einer Map.",
    [
      'DIM zahlen AS TUPLE',
      'zahlen = (1, 2, 3, 4, 5)',
      '',
      'DIM quadrate AS TUPLE',
      'quadrate = [n * n FOR n IN zahlen]',
      'PRINT quadrate',
    ],
    { out: ["(1, 4, 9, 16, 25)"] }),
  H.p("Vergleiche das mit der ausgeschriebenen Schleife – beide tun dasselbe, aber die Comprehension fasst es in eine Zeile:"),
  H.code([
    '\' dieselbe Aufgabe mit einer Schleife:',
    'DIM quadrate AS TUPLE',
    'DIM liste[0] AS INTEGER',
    'DIM n AS INTEGER',
    'FOR n = 1 TO 5',
    '    ARRAY_PUSH(liste, n * n)',
    'NEXT',
  ]),

  H.h2("Mit Bedingung: WHERE"),
  H.p("Hängst du ein WHERE samt Bedingung an, landen nur die Elemente im Ergebnis, für die die Bedingung wahr ist – die anderen werden übersprungen. So filterst und verwandelst du in einem Rutsch. Hier bleiben nur die geraden Zahlen übrig:"),
  H.cmd("Comprehension mit Filter", "[ ausdruck FOR variable IN sammlung WHERE bedingung ]",
    "Wie die List-Comprehension, übernimmt aber nur die Elemente, für die die Bedingung zutrifft.",
    [
      'DIM zahlen AS TUPLE',
      'zahlen = (1, 2, 3, 4, 5, 6)',
      '',
      'DIM gerade AS TUPLE',
      'gerade = [n FOR n IN zahlen WHERE n MOD 2 = 0]',
      'PRINT gerade',
    ],
    { out: ["(2, 4, 6)"] }),
  H.p("Der Ausdruck vorne darf alles sein – eine Rechnung, ein Funktionsaufruf, ein Methodenaufruf. So machst du etwa aus jedem Zeichen eines Strings einen Großbuchstaben:"),
  H.code([
    'DIM gross AS TUPLE',
    'gross = [UPPER$(c) FOR c IN "abc"]',
    'PRINT gross',
  ]),
  H.code(["(A, B, C)"], { out: true }),

  H.h2("Dict-Comprehension: eine Map bauen"),
  H.p("Mit geschweiften Klammern und einem Doppelpunkt baust du in einem Zug eine ganze Map auf. Vor dem Doppelpunkt steht der Schlüssel, dahinter der Wert – beide werden für jedes Element berechnet. Denk daran: Map-Schlüssel sind immer Strings (Kapitel „Maps“), bei Bedarf also mit STR$ umwandeln."),
  H.cmd("Dict-Comprehension", "{ schlüssel : wert FOR variable IN sammlung }",
    "Erzeugt eine Map, indem für jedes Element ein Schlüssel-Wert-Paar berechnet wird. Ein WHERE-Filter ist auch hier erlaubt.",
    [
      'DIM quadr AS MAP OF INTEGER',
      'quadr = {STR$(x) + "sq": x * x FOR x IN (1, 2, 3, 4)}',
      'PRINT MAPGET(quadr, "3sq")',
    ],
    { out: ["9"] }),

  H.h2("Set-Comprehension: doppelte entfernen"),
  H.p("Schreibst du geschweifte Klammern OHNE Doppelpunkt, bekommst du eine Set-Comprehension. Sie berechnet wie eine List-Comprehension einen Wert pro Element, lässt aber Doppelte weg – jeder Wert erscheint nur einmal, in der Reihenfolge seines ersten Auftretens. Das Ergebnis ist wieder ein Tupel."),
  H.cmd("Set-Comprehension", "{ ausdruck FOR variable IN sammlung }",
    "Wie die List-Comprehension, entfernt aber Duplikate. Praktisch, um aus vielen Werten die eindeutigen herauszuziehen.",
    [
      'DIM reste AS TUPLE',
      'reste = {x MOD 3 FOR x IN (0, 1, 2, 3, 4, 5, 6, 7, 8)}',
      'PRINT reste',
    ],
    { out: ["(0, 1, 2)"] }),
  H.p("Obwohl neun Zahlen hineingehen, kommen nur drei verschiedene Reste heraus (0, 1, 2) – die Wiederholungen wurden geschluckt."),

  H.tip("Wann Comprehension, wann Schleife?", "Eine Comprehension glänzt, wenn du aus einer Sammlung schlicht eine neue ableitest – abbilden und/oder filtern. Wird die Logik komplizierter (mehrere Schritte, Zwischenwerte, viele Bedingungen), bleibt die ausgeschriebene Schleife klarer. Lesbarkeit geht vor Kürze."),
];
