module.exports = (H) => [
  H.chapter("Fehlerbehandlung"),
  H.p("Manche Dinge können schiefgehen, ohne dass du als Programmierer schuld bist: Eine Datei fehlt, eine Eingabe ergibt keinen Sinn, eine Berechnung teilt versehentlich durch null. Tritt so ein Laufzeitfehler auf, bricht Drachenhauch das Programm normalerweise mit einer Meldung ab. Oft willst du aber nicht abstürzen, sondern den Fehler sauber auffangen und weitermachen. Genau dafür gibt es TRY, CATCH und THROW."),

  H.h2("Auffangen mit TRY ... CATCH"),
  H.p("Du legst den heiklen Code in einen TRY-Block. Geht alles gut, läuft er ganz normal durch und der CATCH-Teil wird übersprungen. Tritt aber irgendwo im TRY-Block ein Fehler auf, springt Drachenhauch sofort in den CATCH-Block – der Rest des TRY-Blocks wird übersprungen, das Programm aber NICHT abgebrochen. Danach geht es hinter END TRY ganz normal weiter."),
  H.p("Im CATCH kannst du eine Variable angeben (hier e). Sie enthält dann die Fehlermeldung als Text – nützlich, um zu sehen, was passiert ist."),
  H.cmd("TRY ... CATCH ... END TRY", "TRY\n    ...\nCATCH [e]\n    ...\nEND TRY",
    "Führt den TRY-Block aus. Tritt ein Fehler auf, läuft stattdessen der CATCH-Block weiter. Die optionale Variable nach CATCH nimmt die Fehlermeldung als String auf. Nach END TRY läuft das Programm normal weiter – ein abgefangener Fehler beendet es nicht.",
    [
      'TRY',
      '    DIM a AS INTEGER',
      '    a = 10 \\ 0           \' Division durch null!',
      '    PRINT "wird übersprungen"',
      'CATCH e',
      '    PRINT "Fehler abgefangen: "; e',
      'END TRY',
      'PRINT "weiter geht\'s"',
    ],
    { out: ["Fehler abgefangen: Integer-Division durch 0", "weiter geht's"] }),
  H.p("Beachte: Die Zeile nach der Division wurde nie ausgeführt – sobald der Fehler auftrat, sprang die Ausführung direkt in den CATCH. Aber das Programm lief danach weiter und gab „weiter geht's“ aus, statt abzustürzen."),

  H.h2("Eigene Fehler auslösen mit THROW"),
  H.p("Du kannst Fehler auch selbst auslösen – etwa wenn ein Wert nicht zulässig ist. THROW wirft einen Fehler mit einer Nachricht deiner Wahl. Er verhält sich wie ein eingebauter Laufzeitfehler: Er bricht den aktuellen Ablauf ab und wird vom nächsten umgebenden CATCH aufgefangen (auch über Funktionsaufrufe hinweg)."),
  H.cmd("THROW", 'THROW wert',
    "Löst einen Fehler mit dem angegebenen Wert (meist ein String) aus. Der Ablauf bricht ab und springt zum nächsten umgebenden CATCH – egal, wie viele Funktionsaufrufe dazwischenliegen.",
    [
      'SUB pruefe(alter AS INTEGER)',
      '    IF alter < 0 THEN THROW "Alter darf nicht negativ sein"',
      '    PRINT "Alter ok: "; alter',
      'END SUB',
      '',
      'TRY',
      '    pruefe(25)',
      '    pruefe(-5)            \' wirft hier',
      'CATCH msg',
      '    PRINT "Abgefangen: "; msg',
      'END TRY',
    ],
    { out: ["Alter ok: 25", "Abgefangen: Alter darf nicht negativ sein"] }),
  H.p("Schön zu sehen: pruefe(25) lief normal durch, pruefe(-5) warf den Fehler. Dieser sprang aus der SUB heraus bis zum CATCH im aufrufenden Code – so trennst du das Erkennen eines Problems (in der SUB) sauber von seiner Behandlung (im CATCH)."),
  H.note("Die Variable nach CATCH ist optional. Interessiert dich die genaue Meldung nicht, schreibst du einfach CATCH ohne Namen – der Block fängt den Fehler trotzdem ab."),

  H.h2("Wann (und wann nicht) Fehlerbehandlung?"),
  H.p("TRY/CATCH ist mächtig, aber kein Ersatz für gewöhnliche Verzweigungen. Nutze es für Dinge, die WIRKLICH außergewöhnlich sind und die du nicht einfach vorher prüfen kannst – eine fehlende Datei, eine kaputte Benutzereingabe, ein Netzwerkproblem. Für normale Fallunterscheidungen („hat der Spieler genug Gold?“) bleibt ein schlichtes IF die richtige und klarere Wahl."),
  H.tip("Robuste Eingaben", "Ein klassischer Einsatz: Du liest Text ein und willst eine Zahl daraus machen. Statt mit TRY/CATCH um VAL herumzubauen, ist hier oft TRYVAL(text, ersatz) (Kapitel „Strings“) die einfachere Lösung – es liefert bei ungültiger Eingabe still einen Ersatzwert. Greife zu TRY/CATCH, wenn es kein so bequemes Sicherheitsnetz gibt."),
];
