module.exports = (H) => [
  H.chapter("Coroutinen"),
  H.p("Eine gewöhnliche Funktion läuft von oben bis zum RETURN durch und ist dann fertig. Eine Coroutine kann mehr: Sie darf sich mitten in der Ausführung anhalten, einen Wert nach draußen reichen – und später genau dort weiterlaufen, wo sie stehen geblieben ist. Sie merkt sich dabei ihren kompletten Zustand: alle lokalen Variablen, die Stelle im Code, alles. Man kann sie sich wie eine Funktion mit Pausenknopf vorstellen."),
  H.p("Das klingt exotisch, ist aber für Spiele Gold wert: Zwischensequenzen, die Schritt für Schritt ablaufen; Gegner-Muster, die eine Weile dies und dann jenes tun; oder das Erzeugen einer endlosen Zahlenfolge, Wert für Wert. Dieses Kapitel ist anspruchsvoll – lass dir Zeit und probiere die Beispiele selbst aus."),

  H.h2("Was eine Coroutine zur Coroutine macht"),
  H.p("Du brauchst kein besonderes Schlüsselwort bei der Definition. Sobald im Körper einer FUNCTION (oder SUB) irgendwo ein YIELD steht, ist sie automatisch eine Coroutine. YIELD bedeutet „halte hier an und reiche diesen Wert nach draußen“."),
  H.p("Und jetzt das Überraschende: Rufst du eine Coroutine auf, läuft ihr Code zunächst GAR NICHT. Stattdessen bekommst du ein Handle zurück – eine Art Fernbedienung für die pausierte Coroutine, die du in einer Variablen vom Typ COROUTINE aufbewahrst. Erst CORO_RESUME startet und treibt sie an."),
  H.cmd("YIELD  /  CORO_RESUME", "YIELD wert        CORO_RESUME(c)",
    "YIELD hält die Coroutine an und gibt einen Wert nach außen. CORO_RESUME setzt sie bis zum nächsten YIELD fort und liefert dessen Wert. Läuft die Coroutine in diesem Schritt zu Ende, liefert CORO_RESUME stattdessen ihren RETURN-Wert.",
    [
      'FUNCTION zaehler() AS INTEGER',
      '    YIELD 1',
      '    YIELD 2',
      '    YIELD 3',
      '    RETURN 99',
      'END FUNCTION',
      '',
      'DIM c AS COROUTINE',
      'c = zaehler()           \' startet NICHT – liefert ein Handle',
      'PRINT CORO_RESUME(c)    \' läuft bis YIELD 1',
      'PRINT CORO_RESUME(c)    \' weiter bis YIELD 2',
      'PRINT CORO_RESUME(c)    \' weiter bis YIELD 3',
      'PRINT CORO_RESUME(c)    \' läuft zu Ende: der RETURN-Wert',
    ],
    { out: ["1", "2", "3", "99"] }),
  H.p("Jeder CORO_RESUME nimmt den Faden dort wieder auf, wo das letzte YIELD ihn fallen ließ. Die Coroutine erinnert sich an alles dazwischen."),

  H.h2("Ist sie fertig? CORO_DONE und CORO_RESULT"),
  H.p("Mit CORO_DONE fragst du, ob eine Coroutine durchgelaufen ist. Ihren endgültigen RETURN-Wert kannst du danach jederzeit mit CORO_RESULT abholen."),
  H.cmd("CORO_DONE  /  CORO_RESULT", "CORO_DONE(c)        CORO_RESULT(c)",
    "CORO_DONE liefert TRUE, sobald die Coroutine beendet ist. CORO_RESULT liefert ihren finalen RETURN-Wert (erst sinnvoll, wenn sie fertig ist).",
    [
      'FUNCTION zaehler() AS INTEGER',
      '    YIELD 1',
      '    RETURN 99',
      'END FUNCTION',
      '',
      'DIM c AS COROUTINE',
      'c = zaehler()',
      'PRINT CORO_RESUME(c)',
      'PRINT "fertig? "; CORO_DONE(c)',
      'PRINT CORO_RESUME(c)        \' jetzt läuft sie zu Ende',
      'PRINT "fertig? "; CORO_DONE(c)',
      'PRINT "Ergebnis: "; CORO_RESULT(c)',
    ],
    { out: ["1", "fertig? FALSE", "99", "fertig? TRUE", "Ergebnis: 99"] }),

  H.h2("Der bequeme Weg: FOR EACH"),
  H.p("Willst du einfach nur alle Werte einsammeln, die eine Coroutine nach und nach ausspuckt, musst du nicht selbst mit RESUME und DONE hantieren. FOR EACH treibt die Coroutine automatisch bis zum Ende und reicht dir jeden gelieferten Wert. Das ist die klarste Art, eine erzeugende Coroutine (einen „Generator“) zu durchlaufen."),
  H.p("Hier eine Coroutine, die die Fibonacci-Folge erzeugt – sie hält nach jeder Zahl an und rechnet beim nächsten Mal weiter:"),
  H.code([
    'FUNCTION fibo(anzahl AS INTEGER) AS INTEGER',
    '    DIM a AS INTEGER',
    '    DIM b AS INTEGER',
    '    DIM i AS INTEGER',
    '    a = 0 : b = 1',
    '    FOR i = 1 TO anzahl',
    '        YIELD a               \' Zahl rausgeben, dann pausieren',
    '        DIM tmp AS INTEGER',
    '        tmp = a + b',
    '        a = b',
    '        b = tmp',
    '    NEXT',
    'END FUNCTION',
    '',
    'FOR EACH zahl IN fibo(8)',
    '    PRINT zahl; " ";',
    'NEXT',
    'PRINT',
  ]),
  H.code(["0 1 1 2 3 5 8 13"], { out: true }),
  H.warn("Treibe eine UNENDLICHE Coroutine (eine ohne natürliches Ende) niemals mit FOR EACH an – das läuft endlos. Steuere sie dann von Hand mit CORO_RESUME und brich selbst ab, wenn du genug Werte hast. Tipp: Beim manuellen RESUME-Loop liefert der allerletzte (beendende) Aufruf den RETURN-Wert bzw. NIL – für reines Einsammeln ist FOR EACH darum die sicherere Wahl."),

  H.h2("Werte hineingeben: CORO_SEND"),
  H.p("YIELD ist keine Einbahnstraße. YIELD ist nämlich selbst ein Ausdruck: Du kannst sein Ergebnis einer Variablen zuweisen. Mit CORO_SEND setzt du die Coroutine nicht nur fort, sondern schiebst ihr dabei auch einen Wert hinein – genau der wird zum Ergebnis des YIELD, an dem sie gerade pausiert. So entsteht ein echter Dialog zwischen deinem Code und der Coroutine."),
  H.cmd("CORO_SEND", "CORO_SEND(c, wert)",
    "Setzt die Coroutine fort wie CORO_RESUME, aber der YIELD-Ausdruck, an dem sie pausiert, liefert den übergebenen Wert. (Beim allerersten Start gibt es noch kein wartendes YIELD – nutze dort CORO_RESUME.)",
    [
      'FUNCTION echo() AS INTEGER',
      '    DIM x AS INTEGER',
      '    x = YIELD 0          \' x bekommt den hineingegebenen Wert',
      '    YIELD x * 10',
      'END FUNCTION',
      '',
      'DIM e AS COROUTINE',
      'e = echo()',
      'PRINT CORO_RESUME(e)     \' bis zum ersten YIELD: 0',
      'PRINT CORO_SEND(e, 5)    \' schickt 5 hinein -> x=5 -> YIELD 50',
    ],
    { out: ["0", "50"] }),

  H.h2("Wofür Coroutinen?"),
  H.p("Coroutinen sind ein Spezialwerkzeug – für viele Programme brauchst du sie nie. Wo sie aber passen, vereinfachen sie den Code enorm, weil die Coroutine ihren Fortschritt selbst behält, statt dass du ihn mühsam in Variablen mitführst:"),
  H.bullet("Zwischensequenzen / Dialoge: ein Schritt pro YIELD, der Rest wartet."),
  H.bullet("Gegner- oder Boss-Muster: „fahre links, warte, schieße dreimal, von vorn.“"),
  H.bullet("Generatoren: erzeuge eine (auch endlose) Folge von Werten auf Abruf."),
  H.tip("Aufräumen", "Eine pausierte Coroutine, die du nicht zu Ende laufen lässt, kannst du mit CORO_CLOSE(c) sauber beenden. Bei kurzen Programmen ist das selten nötig; bei vielen langlebigen Coroutinen ist es guter Stil."),
];
