module.exports = (H) => [
  H.chapter("Zeichenketten-Funktionen"),
  H.p("Dieses Kapitel listet alle String-Funktionen mit je einem kleinen Beispiel zum Nachschlagen auf. Ausführlich eingeführt sind sie im Kapitel „Strings im Detail“ (Teil II) – dort steht auch der wichtige Hinweis, dass Zeichen-Positionen ab 0 gezählt werden. Funktionen mit $-Endung liefern einen String; das $ darfst du weglassen (UPPER$ ≡ UPPER)."),

  H.h2("Länge & Schreibweise"),
  H.cmd("LEN", "LEN(s$)",
    "Anzahl der Zeichen eines Strings.",
    ['PRINT LEN("Drachenhauch")'], { out: ["9"] }),
  H.cmd("UPPER$ · LOWER$", "UPPER$(s$)   LOWER$(s$)",
    "Wandelt den ganzen Text in Groß- bzw. Kleinbuchstaben.",
    ['PRINT UPPER$("hallo")', 'PRINT LOWER$("HALLO")'], { out: ["HALLO", "hallo"] }),
  H.cmd("REVERSE$", "REVERSE$(s$)",
    "Kehrt die Reihenfolge der Zeichen um.",
    ['PRINT REVERSE$("abc")'], { out: ["cba"] }),

  H.h2("Teile herausschneiden"),
  H.cmd("LEFT$ · RIGHT$", "LEFT$(s$, n)   RIGHT$(s$, n)",
    "Die ersten bzw. letzten n Zeichen.",
    ['PRINT LEFT$("Drachenhauch", 4)', 'PRINT RIGHT$("Drachenhauch", 5)'], { out: ["Game", "Basic"] }),
  H.cmd("MID$", "MID$(s$, start[, n])",
    "Ab Position start (ab 0 gezählt!) bis zu n Zeichen; ohne n bis zum Ende.",
    ['PRINT MID$("Drachenhauch", 4)', 'PRINT MID$("Drachenhauch", 4, 5)'], { out: ["Basic", "Basic"] }),
  H.cmd("Index & Slicing", "s$[i]   s$[a:b]",
    "Einzelnes Zeichen an Position i bzw. Ausschnitt von a bis b (untere Grenze dabei, obere nicht).",
    ['PRINT "Drachenhauch"[0]', 'PRINT "Drachenhauch"[4:9]'], { out: ["G", "Basic"] }),

  H.h2("Suchen & Prüfen"),
  H.cmd("INSTR", "INSTR(s$, teil$[, start])",
    "Position von teil$ in s$ (ab 0) oder -1, wenn nicht enthalten. Optional erst ab Position start suchen.",
    ['PRINT INSTR("hello world", "world")', 'PRINT INSTR("hello world", "xyz")'], { out: ["6", "-1"] }),
  H.cmd("CONTAINS", "CONTAINS(s$, teil$)",
    "TRUE, wenn teil$ in s$ vorkommt (gleichbedeutend mit teil$ IN s$).",
    ['PRINT CONTAINS("hello world", "wor")'], { out: ["TRUE"] }),
  H.cmd("STARTSWITH · ENDSWITH", "STARTSWITH(s$, präfix$)   ENDSWITH(s$, suffix$)",
    "Prüfen, ob s$ mit dem angegebenen Text beginnt bzw. endet.",
    ['PRINT STARTSWITH("hello", "he")', 'PRINT ENDSWITH("hello", "lo")'], { out: ["TRUE", "TRUE"] }),

  H.h2("Ersetzen & Säubern"),
  H.cmd("REPLACE$", "REPLACE$(s$, alt$, neu$)",
    "Ersetzt alle Vorkommen von alt$ durch neu$.",
    ['PRINT REPLACE$("a-b-c", "-", "_")'], { out: ["a_b_c"] }),
  H.cmd("TRIM$", "TRIM$(s$)",
    "Entfernt Leerraum am Anfang und Ende.",
    ['PRINT "[" + TRIM$("  hi  ") + "]"'], { out: ["[hi]"] }),
  H.cmd("LTRIM$ · RTRIM$", "LTRIM$(s$)   RTRIM$(s$)",
    "Entfernt Leerraum nur links bzw. nur rechts.",
    ['PRINT "[" + LTRIM$("  hi  ") + "]"', 'PRINT "[" + RTRIM$("  hi  ") + "]"'], { out: ["[hi  ]", "[  hi]"] }),

  H.h2("Zerlegen & Zusammensetzen"),
  H.cmd("SPLIT$", "SPLIT$(s$, trenner$)",
    "Zerlegt s$ am Trenner in ein ARRAY OF STRING.",
    [
      'DIM teile AS ARRAY OF STRING',
      'teile = SPLIT$("Anna,Bert,Cilly", ",")',
      'PRINT teile[0]; " / "; teile[2]',
    ], { out: ["Anna / Cilly"] }),
  H.cmd("JOIN$", "JOIN$(array, trenner$)",
    "Fügt ein String-Array mit dem Trenner zu einem String zusammen.",
    [
      'DIM teile AS ARRAY OF STRING',
      'teile = SPLIT$("Anna,Bert,Cilly", ",")',
      'PRINT JOIN$(teile, " | ")',
    ], { out: ["Anna | Bert | Cilly"] }),

  H.h2("Auffüllen & Wiederholen"),
  H.cmd("PADL$ · PADR$", "PADL$(s$, breite[, füll$])   PADR$(s$, breite[, füll$])",
    "Füllt auf die Breite auf – PADL$ links (rechtsbündig), PADR$ rechts (linksbündig). Ohne Füllzeichen das Leerzeichen.",
    ['PRINT PADL$("42", 6, "0")', 'PRINT PADR$("x", 4, ".") + "|"'], { out: ["000042", "x...|"] }),
  H.cmd("REPEAT$", "REPEAT$(s$, n)",
    "Hängt s$ n-mal aneinander (gleichbedeutend mit s$ * n).",
    ['PRINT REPEAT$("=*", 5)', 'PRINT "-" * 10'], { out: ["=*=*=*=*=*", "----------"] }),

  H.h2("Als Methode und in Ketten"),
  H.p("Die meisten dieser Funktionen lassen sich auch mit dem Punkt als Methode aufrufen und verketten – oft die lesbarste Form:"),
  H.code([
    'DIM eingabe AS STRING',
    'eingabe = "  Hallo Welt  "',
    'PRINT eingabe.trim().upper()',
    'PRINT eingabe.trim().replace("Welt", "Drachenhauch")',
  ]),
  H.code(["HALLO WELT", "Hallo Drachenhauch"], { out: true }),
  H.h2("Weitere Text-Helfer"),
  H.cmd("TITLE$ · SPACE$", 'TITLE$(text$)   SPACE$(n)',
    "TITLE$ schreibt jedes Wort groß (für Überschriften oder Namen), SPACE$ liefert n Leerzeichen – nützlich, um Spalten auszurichten.",
    [
      'PRINT TITLE$("hallo neue welt")',
      'PRINT "A" + SPACE$(3) + "B"',
    ], { out: ["Hallo Neue Welt", "A   B"] }),
  H.cmd("COUNT", 'COUNT(text$, teil$)',
    "Zählt, wie oft teil$ in text$ vorkommt.",
    [
      'PRINT COUNT("banane", "an")',
    ], { out: ["2"] }),
  H.cmd("ISNUMERIC", 'ISNUMERIC(text$)',
    "Prüft, ob sich der Text als Zahl lesen lässt – der saubere Weg, eine Nutzereingabe zu prüfen, BEVOR du sie mit VAL umwandelst.",
    [
      'DIM s AS STRING',
      's = "42"',
      'IF ISNUMERIC(s) THEN PRINT VAL(s) * 2',
    ], { out: ["84"] }),
  H.cmd("OCT$ · NUMFMT$", 'OCT$(n)   NUMFMT$(zahl[, nachkommastellen])',
    "OCT$ stellt eine Zahl im Achtersystem dar (das Gegenstück zu HEX$). NUMFMT$ kürzt große Zahlen lesbar ab (K, M, T …) – genau das, was Aufbau- und Idle-Spiele ständig brauchen. Die Nachkommastellen sind wählbar, voreingestellt sind zwei; kleine Zahlen bekommen keine Abkürzung, aber dieselbe Nachkommastellen-Zahl.",
    [
      'PRINT OCT$(64)',
      'PRINT NUMFMT$(1500000)',
      'PRINT NUMFMT$(1500000, 1)',
      'PRINT NUMFMT$(999)',
    ], { out: ["100", "1.50M", "1.5M", "999.00"] }),
  H.note("Zum Umwandeln zwischen Text und Zahl (STR$, VAL, CHR$, ASC) siehe das Kapitel „Typumwandlung & Prüfung“. Text bequem aus Werten zusammenbauen kannst du mit f-Strings (Kapitel „Ein- und Ausgabe“)."),
];
