module.exports = (H) => [
  H.chapter("Array-Helfer"),
  H.p("Zu Arrays (Kapitel „Arrays“, Teil II) gibt es viele eingebaute Helfer: zum Abfragen der Größe, zum Sortieren und Suchen, zum Rechnen über alle Elemente und zum dynamischen Wachsen und Schrumpfen. Dieses Kapitel stellt sie einzeln mit Beispiel vor. Beachte: Funktionen wie SORT oder SHUFFLE verändern das Array direkt an Ort und Stelle („in place“), sie liefern kein neues Array zurück."),

  H.h2("Größe abfragen"),
  H.cmd("LEN", "LEN(array)",
    "Anzahl der Elemente. Bei mehrdimensionalen Arrays die Größe der ersten Dimension.",
    [
      'DIM zahlen[5] AS INTEGER',
      'PRINT LEN(zahlen)',
    ], { out: ["5"] }),
  H.cmd("DIMCOUNT · DIMSIZE", "DIMCOUNT(array)   DIMSIZE(array, n)",
    "DIMCOUNT liefert die Anzahl der Dimensionen, DIMSIZE die Größe der n-ten Dimension (ab 0 gezählt).",
    [
      'DIM brett[3, 4] AS INTEGER',
      'PRINT DIMCOUNT(brett)',
      'PRINT DIMSIZE(brett, 0); " x "; DIMSIZE(brett, 1)',
    ], { out: ["2", "3 x 4"] }),

  H.h2("Sortieren, Umkehren, Suchen"),
  H.cmd("SORT", "SORT(array[, absteigend])",
    "Sortiert ein 1D-Array aufsteigend – direkt im Array. Mit TRUE als zweitem Argument absteigend.",
    [
      'DIM a[4] AS INTEGER',
      'a[0]=30 : a[1]=10 : a[2]=40 : a[3]=20',
      'SORT(a)',
      'PRINT a[0]; a[1]; a[2]; a[3]',
      'SORT(a, TRUE)',
      'PRINT a[0]; a[1]; a[2]; a[3]',
    ], { out: ["10203040", "40302010"] }),
  H.cmd("REVERSE", "REVERSE(array)",
    "Kehrt die Reihenfolge der Elemente um – direkt im Array.",
    [
      'DIM a[3] AS INTEGER',
      'a[0]=1 : a[1]=2 : a[2]=3',
      'REVERSE(a)',
      'PRINT a[0]; a[1]; a[2]',
    ], { out: ["321"] }),
  H.cmd("ARRAY_INDEXOF", "ARRAY_INDEXOF(array, wert)",
    "Liefert den ersten Index, an dem wert steht, oder -1, wenn er nicht vorkommt.",
    [
      'DIM a[3] AS INTEGER',
      'a[0]=10 : a[1]=20 : a[2]=30',
      'PRINT ARRAY_INDEXOF(a, 20)',
      'PRINT ARRAY_INDEXOF(a, 99)',
    ], { out: ["1", "-1"] }),

  H.h2("Über das ganze Array rechnen"),
  H.cmd("ARRAY_SUM · ARRAY_AVG", "ARRAY_SUM(array)   ARRAY_AVG(array)",
    "Summe bzw. Durchschnitt eines Zahlen-Arrays. ARRAY_AVG ergibt immer eine Kommazahl und braucht ein nicht-leeres Array.",
    [
      'DIM w[3] AS INTEGER',
      'w[0]=5 : w[1]=9 : w[2]=1',
      'PRINT ARRAY_SUM(w)',
      'PRINT ARRAY_AVG(w)',
    ], { out: ["15", "5.0"] }),
  H.cmd("ARRAY_MIN · ARRAY_MAX", "ARRAY_MIN(array)   ARRAY_MAX(array)",
    "Kleinstes bzw. größtes Element eines Zahlen-Arrays.",
    [
      'DIM w[3] AS INTEGER',
      'w[0]=5 : w[1]=9 : w[2]=1',
      'PRINT ARRAY_MIN(w); " "; ARRAY_MAX(w)',
    ], { out: ["1 9"] }),
  H.cmd("ARRAY_FILL", "ARRAY_FILL(array, wert)",
    "Setzt alle Fächer auf denselben Wert – gut zum Zurücksetzen.",
    [
      'DIM raster[3] AS INTEGER',
      'ARRAY_FILL(raster, 7)',
      'PRINT raster[0]; raster[1]; raster[2]',
    ], { out: ["777"] }),
  H.cmd("ARRAY_COPY", "ARRAY_COPY(array)",
    "Liefert eine unabhängige Kopie. Nötig, weil ein einfaches b = a kein Kopieren ist, sondern beide Namen auf dasselbe Array zeigen lässt (siehe Kapitel „Arrays“).",
    [
      'DIM a[2] AS INTEGER',
      'a[0]=1 : a[1]=2',
      'DIM b AS ARRAY OF INTEGER',
      'b = ARRAY_COPY(a)',
      'b[0] = 99',
      'PRINT a[0]; " "; b[0]',
    ], { out: ["1 99"] }),

  H.h2("Wachsen & schrumpfen"),
  H.cmd("ARRAY_PUSH · ARRAY_POP", "ARRAY_PUSH(array, wert)   ARRAY_POP(array)",
    "ARRAY_PUSH hängt einen Wert hinten an und liefert die neue Länge. ARRAY_POP entfernt das letzte Element und gibt es zurück (Array darf nicht leer sein). Zusammen ergeben sie einen Stapel.",
    [
      'DIM st[0] AS INTEGER',
      'PRINT ARRAY_PUSH(st, 10)',
      'PRINT ARRAY_PUSH(st, 20)',
      'PRINT ARRAY_POP(st)',
      'PRINT LEN(st)',
    ], { out: ["1", "2", "20", "1"] }),
  H.cmd("ARRAY_INSERT · ARRAY_REMOVE_AT", "ARRAY_INSERT(array, idx, wert)   ARRAY_REMOVE_AT(array, idx)",
    "ARRAY_INSERT schiebt einen Wert an Position idx ein (Rest rückt nach hinten; idx von 0 bis Länge). ARRAY_REMOVE_AT entfernt das Element an idx und gibt es zurück (Rest rückt nach vorne).",
    [
      'DIM li[0] AS INTEGER',
      'ARRAY_PUSH(li, 10) : ARRAY_PUSH(li, 30)',
      'ARRAY_INSERT(li, 1, 20)',
      'PRINT li[0]; li[1]; li[2]',
      'PRINT ARRAY_REMOVE_AT(li, 0)',
    ], { out: ["102030", "10"] }),
  H.cmd("REDIM", "REDIM(array, länge)",
    "Ändert die Größe nachträglich: wächst (neue Fächer = Standardwert) oder schrumpft (überzählige fallen weg). Vorhandene Werte bleiben erhalten.",
    [
      'DIM r[2] AS INTEGER',
      'r[0]=1 : r[1]=2',
      'REDIM(r, 4)',
      'PRINT LEN(r); ": "; r[0]; r[1]; r[2]; r[3]',
    ], { out: ["4: 1200"] }),

  H.tip("Verwandtes", "Ein zufälliges Element ziehen (CHOICE) oder das Array mischen (SHUFFLE) findest du im Kapitel „Zufall“. Sortieren mit eigener Vergleichsregel (FUNCREF-Comparator) ist möglich – nutze dafür eine Vergleichsfunktion wie im Kapitel „Funktionen & SUBs“ beschrieben."),
];
