module.exports = (H) => [
  H.chapter("Map-Helfer"),
  H.p("Eine Map verbindet Schlüssel (immer Strings) mit Werten – ausführlich erklärt im Kapitel „Maps“ (Teil II). Hier findest du alle Map-Funktionen einzeln mit Beispiel zum Nachschlagen. Viele gibt es auch in Punkt-Schreibweise (m.get(...), m.put(...) …); das steht am Ende des Kapitels."),

  H.h2("Ablegen & Nachschlagen"),
  H.cmd("MAPPUT", 'MAPPUT(m, schlüssel$, wert)',
    "Legt unter dem Schlüssel einen Wert ab oder überschreibt den vorhandenen.",
    [
      'DIM m AS MAP OF INTEGER',
      'MAPPUT(m, "Holz", 5)',
      'PRINT MAPGET(m, "Holz")',
    ], { out: ["5"] }),
  H.cmd("MAPGET", 'MAPGET(m, schlüssel$)',
    "Liefert den Wert zum Schlüssel. Achtung: Fehlt der Schlüssel, bricht das Programm ab – prüfe vorher mit MAPHAS oder nutze MAPGETOR.",
    [
      'DIM m AS MAP OF STRING',
      'MAPPUT(m, "name", "Anna")',
      'PRINT MAPGET(m, "name")',
    ], { out: ["Anna"] }),
  H.cmd("MAPGETOR", 'MAPGETOR(m, schlüssel$, ersatz)',
    "Liefert den Wert zum Schlüssel oder den Ersatzwert, falls der Schlüssel fehlt. Bricht nie ab.",
    [
      'DIM m AS MAP OF INTEGER',
      'MAPPUT(m, "Holz", 5)',
      'PRINT MAPGETOR(m, "Gold", 0)',
    ], { out: ["0"] }),

  H.h2("Prüfen, Entfernen, Größe"),
  H.cmd("MAPHAS", 'MAPHAS(m, schlüssel$)',
    "TRUE, wenn der Schlüssel vorhanden ist. Gleichbedeutend mit schlüssel$ IN m.",
    [
      'DIM m AS MAP OF INTEGER',
      'MAPPUT(m, "Stein", 3)',
      'PRINT MAPHAS(m, "Stein")',
      'PRINT "Gold" IN m',
    ], { out: ["TRUE", "FALSE"] }),
  H.cmd("MAPSIZE", 'MAPSIZE(m)',
    "Anzahl der Schlüssel-Wert-Paare.",
    [
      'DIM m AS MAP OF INTEGER',
      'MAPPUT(m, "a", 1) : MAPPUT(m, "b", 2)',
      'PRINT MAPSIZE(m)',
    ], { out: ["2"] }),
  H.cmd("MAPREMOVE", 'MAPREMOVE(m, schlüssel$)',
    "Entfernt ein Paar und liefert TRUE, wenn es den Schlüssel gab (sonst FALSE).",
    [
      'DIM m AS MAP OF INTEGER',
      'MAPPUT(m, "Holz", 5)',
      'PRINT MAPREMOVE(m, "Holz")',
      'PRINT MAPSIZE(m)',
    ], { out: ["TRUE", "0"] }),
  H.cmd("MAPCLEAR", 'MAPCLEAR(m)',
    "Leert die ganze Map auf einmal.",
    [
      'DIM m AS MAP OF INTEGER',
      'MAPPUT(m, "a", 1) : MAPPUT(m, "b", 2)',
      'MAPCLEAR(m)',
      'PRINT MAPSIZE(m)',
    ], { out: ["0"] }),

  H.h2("Über alle Einträge"),
  H.p("Die Paare erscheinen stets in der Reihenfolge, in der sie eingefügt wurden."),
  H.cmd("MAPKEYS", 'MAPKEYS(m)',
    "Liefert alle Schlüssel als ARRAY OF STRING (gut zum Sortieren oder Durchlaufen).",
    [
      'DIM m AS MAP OF INTEGER',
      'MAPPUT(m, "Holz", 5) : MAPPUT(m, "Stein", 3)',
      'DIM k AS ARRAY OF STRING',
      'k = MAPKEYS(m)',
      'PRINT k[0]; " "; k[1]',
    ], { out: ["Holz Stein"] }),
  H.cmd("MAPVALUES", 'MAPVALUES(m)',
    "Liefert alle Werte als Array (in Einfüge-Reihenfolge).",
    [
      'DIM m AS MAP OF INTEGER',
      'MAPPUT(m, "Holz", 5) : MAPPUT(m, "Stein", 3)',
      'DIM v AS ARRAY OF INTEGER',
      'v = MAPVALUES(m)',
      'PRINT v[0]; " "; v[1]',
    ], { out: ["5 3"] }),
  H.cmd("MAPITEMS", 'MAPITEMS(m)',
    "Liefert alle Paare als Array von (Schlüssel, Wert)-Tupeln – ideal mit FOR EACH. In paar[0] steht der Schlüssel, in paar[1] der Wert.",
    [
      'DIM m AS MAP OF INTEGER',
      'MAPPUT(m, "Holz", 5) : MAPPUT(m, "Stein", 3)',
      'FOR EACH paar IN MAPITEMS(m)',
      '    PRINT paar[0]; "="; paar[1]',
      'NEXT',
    ], { out: ["Holz=5", "Stein=3"] }),
  H.note("Auch direkt über die Map läuft FOR EACH – die Schleifenvariable bekommt dann jeden SCHLÜSSEL, den Wert holst du mit MAPGET. Siehe Kapitel „Maps“."),

  H.h2("Punkt-Schreibweise (Methoden)"),
  H.p("Dieselben Operationen gibt es als Methode an der Map – oft kürzer zu lesen:"),
  H.code([
    'DIM lager AS MAP OF INTEGER',
    'lager.put("Holz", 5)',
    'PRINT lager.get("Holz")',
    'PRINT lager.has("Stein")',
    'PRINT lager.getor("Gold", 0)',
    'PRINT lager.size()',
  ]),
  H.code(["5", "FALSE", "0", "1"], { out: true }),
];
