module.exports = (H) => [
  H.chapter("Dateien"),
  H.p("Mit Datei-Befehlen speicherst du Daten dauerhaft auf der Festplatte – Spielstände, Highscores, Einstellungen, Level. GameBasic bietet zwei Wege: den klassischen mit einem FILE-Handle (Datei öffnen, zeilenweise lesen/schreiben, schließen) und den bequemen pfadbasierten (ganze Datei in einem Aufruf lesen oder schreiben). Pfade sind relativ zum Verzeichnis deines Programms."),
  H.note("Jedes Beispiel hier schreibt und liest echte Dateien. Achte beim Ausprobieren darauf, in welchem Ordner dein Programm liegt – dort entstehen die Dateien."),

  H.h2("Datei öffnen & schließen"),
  H.cmd("OPENFILE · CLOSEFILE", 'OPENFILE(pfad$, modus$)   CLOSEFILE(f)',
    "OPENFILE öffnet eine Datei und liefert ein FILE-Handle. Der Modus ist \"r\" (lesen), \"w\" (neu schreiben, überschreibt) oder \"a\" (anhängen). CLOSEFILE schließt sie wieder – wichtig, damit Geschriebenes sicher auf der Platte landet.",
    [
      'DIM f AS FILE',
      'f = OPENFILE("notiz.txt", "w")',
      'WRITELINE(f, "Hallo Datei")',
      'CLOSEFILE(f)',
      'PRINT "geschrieben"',
    ], { out: ["geschrieben"] }),

  H.h2("Zeilenweise schreiben"),
  H.cmd("WRITELINE · WRITE", 'WRITELINE(f, text$)   WRITE(f, text$)',
    "WRITELINE schreibt den Text und einen Zeilenumbruch. WRITE schreibt ohne Umbruch, sodass mehrere Stücke in einer Zeile landen.",
    [
      'DIM f AS FILE',
      'f = OPENFILE("scores.txt", "w")',
      'WRITELINE(f, "Anna 95")',
      'WRITE(f, "Bert ")',
      'WRITE(f, "78")',
      'CLOSEFILE(f)',
      'PRINT "fertig"',
    ], { out: ["fertig"] }),

  H.h2("Zeilenweise lesen"),
  H.cmd("READLINE · ENDOFFILE", 'READLINE(f)   ENDOFFILE(f)',
    "READLINE liefert die nächste Zeile (ohne den Umbruch). ENDOFFILE wird TRUE, sobald das Dateiende erreicht ist – die typische Schleife liest, solange NOT ENDOFFILE.",
    [
      'DIM f AS FILE',
      'f = OPENFILE("scores.txt", "w")',
      'WRITELINE(f, "Anna 95")',
      'WRITELINE(f, "Bert 78")',
      'CLOSEFILE(f)',
      '',
      'f = OPENFILE("scores.txt", "r")',
      'WHILE NOT ENDOFFILE(f)',
      '    PRINT READLINE(f)',
      'WEND',
      'CLOSEFILE(f)',
    ], { out: ["Anna 95", "Bert 78"] }),
  H.cmd("READALL$", 'READALL$(f)',
    "Liest den gesamten verbleibenden Inhalt der Datei auf einmal als einen String.",
    [
      'DIM f AS FILE',
      'f = OPENFILE("notiz.txt", "w")',
      'WRITE(f, "abc")',
      'CLOSEFILE(f)',
      'f = OPENFILE("notiz.txt", "r")',
      'PRINT READALL$(f)',
      'CLOSEFILE(f)',
    ], { out: ["abc"] }),

  H.h2("Bequem: ganze Datei auf einmal"),
  H.p("Für viele Fälle brauchst du gar kein Handle. Diese pfadbasierten Befehle erledigen Öffnen, Lesen/Schreiben und Schließen in einem Schritt."),
  H.cmd("WRITEALL", 'WRITEALL(pfad$, text$)',
    "Schreibt den Text komplett in die Datei (erzeugt sie neu bzw. überschreibt sie).",
    [
      'WRITEALL("daten.txt", "score=42")',
      'PRINT FILEEXISTS("daten.txt")',
    ], { out: ["TRUE"] }),
  H.cmd("READLINES", 'READLINES(pfad$)',
    "Liest die ganze Datei und liefert ihre Zeilen als ARRAY OF STRING.",
    [
      'WRITEALL("liste.txt", "eins" + CHR$(10) + "zwei")',
      'DIM z AS ARRAY OF STRING',
      'z = READLINES("liste.txt")',
      'PRINT LEN(z); ": "; z[0]; "/"; z[1]',
    ], { out: ["2: eins/zwei"] }),
  H.cmd("APPENDFILE", 'APPENDFILE(pfad$, text$)',
    "Hängt Text ans Ende einer Datei an (legt sie an, falls sie noch nicht existiert).",
    [
      'WRITEALL("log.txt", "Start")',
      'APPENDFILE("log.txt", CHR$(10) + "Ende")',
      'PRINT LEN(READLINES("log.txt"))',
    ], { out: ["2"] }),
  H.cmd("FILESIZE", 'FILESIZE(pfad$)',
    "Liefert die Größe der Datei in Bytes.",
    [
      'WRITEALL("daten.txt", "12345")',
      'PRINT FILESIZE("daten.txt")',
    ], { out: ["5"] }),

  H.h2("Vorhandensein & Verwaltung"),
  H.cmd("FILEEXISTS", 'FILEEXISTS(pfad$)',
    "TRUE, wenn die Datei existiert. Praktisch, um vor dem Lesen zu prüfen, ob z. B. ein Spielstand vorhanden ist.",
    [
      'WRITEALL("save.dat", "x")',
      'PRINT FILEEXISTS("save.dat")',
      'PRINT FILEEXISTS("gibtsnicht.dat")',
    ], { out: ["TRUE", "FALSE"] }),
  H.cmd("COPYFILE · RENAME · DELETEFILE", 'COPYFILE(src$, dst$)   RENAME(alt$, neu$)   DELETEFILE(pfad$)',
    "COPYFILE kopiert eine Datei, RENAME benennt sie um bzw. verschiebt sie, DELETEFILE löscht sie.",
    [
      'WRITEALL("a.txt", "hi")',
      'COPYFILE("a.txt", "b.txt")',
      'RENAME("b.txt", "c.txt")',
      'DELETEFILE("c.txt")',
      'PRINT FILEEXISTS("a.txt"); " "; FILEEXISTS("c.txt")',
    ], { out: ["TRUE FALSE"] }),

  H.h2("Verzeichnisse"),
  H.cmd("MKDIR · DIREXISTS", 'MKDIR(pfad$)   DIREXISTS(pfad$)',
    "MKDIR legt ein Verzeichnis an (samt fehlender Elternverzeichnisse). DIREXISTS prüft, ob ein Verzeichnis vorhanden ist.",
    [
      'MKDIR("saves")',
      'PRINT DIREXISTS("saves")',
    ], { out: ["TRUE"] }),
  H.cmd("DIRLIST", 'DIRLIST(pfad$)',
    "Liefert die Namen der Einträge eines Verzeichnisses als (sortiertes) ARRAY OF STRING.",
    [
      'MKDIR("ordner")',
      'WRITEALL("ordner/datei.txt", "x")',
      'DIM e AS ARRAY OF STRING',
      'e = DIRLIST("ordner")',
      'PRINT e[0]',
    ], { out: ["datei.txt"] }),

  H.h2("Pfade zusammenbauen"),
  H.cmd("PATHJOIN", 'PATHJOIN(teil1$, teil2$, ...)',
    "Verbindet Pfadteile sauber mit Schrägstrichen – besser, als Strings von Hand mit \"/\" zu verketten.",
    [
      'PRINT PATHJOIN("saves", "level1", "p.txt")',
    ], { out: ["saves/level1/p.txt"] }),
  H.cmd("BASENAME · DIRNAME", 'BASENAME(pfad$)   DIRNAME(pfad$)',
    "BASENAME liefert den letzten Bestandteil eines Pfads (den Datei- oder Ordnernamen), DIRNAME den Verzeichnis-Anteil davor.",
    [
      'PRINT BASENAME("saves/level1/p.txt")',
      'PRINT DIRNAME("saves/level1/p.txt")',
    ], { out: ["p.txt", "saves/level1"] }),

  H.h2("Native Datei-Dialoge"),
  H.p("Statt einen Pfad im Code fest zu verdrahten, kannst du den Nutzer mit dem gewohnten Betriebssystem-Dialog wählen lassen – „Öffnen“, „Speichern unter“ oder „Ordner wählen“. Die drei Befehle blockieren das Programm, bis der Nutzer eine Wahl trifft oder abbricht (abgebrochen = leerer String \"\") – deshalb nicht in einem laufenden Spiel-Loop verwenden, sondern z. B. beim Programmstart oder über einen Menüpunkt."),
  H.warn("Nicht automatisiert testbar", "Diese drei Befehle öffnen ein echtes System-Fenster und warten auf eine Nutzer-Eingabe. Die folgenden Beispiele zeigen daher die Verwendung, ohne eine Ausgabe abzudrucken."),
  H.cmd("FILE_OPEN_DIALOG", 'FILE_OPEN_DIALOG([titel$[, endungen$]]) AS STRING',
    "Öffnet den „Datei öffnen“-Dialog. endungen$ filtert die Anzeige, komma-getrennt ohne Punkt (z. B. \"png,jpg\"). Liefert den gewählten Pfad oder \"\" bei Abbruch.",
    [
      'DIM pfad AS STRING',
      'pfad = FILE_OPEN_DIALOG("Level laden", "json")',
      'IF pfad <> "" THEN',
      '    PRINT "Gewaehlt:", pfad',
      'END IF',
    ]),
  H.cmd("FILE_SAVE_DIALOG", 'FILE_SAVE_DIALOG([titel$[, vorschlag$[, endungen$]]]) AS STRING',
    "Öffnet den „Speichern unter“-Dialog mit optionalem vorgeschlagenem Dateinamen. Liefert den gewählten Pfad oder \"\" bei Abbruch.",
    [
      'DIM pfad AS STRING',
      'pfad = FILE_SAVE_DIALOG("Spielstand speichern", "save1.json", "json")',
      'IF pfad <> "" THEN WRITEALL(pfad, "{}")',
    ]),
  H.cmd("FOLDER_DIALOG", 'FOLDER_DIALOG([titel$]) AS STRING',
    "Öffnet den „Ordner wählen“-Dialog. Liefert den gewählten Ordnerpfad oder \"\" bei Abbruch.",
    [
      'DIM ordner AS STRING',
      'ordner = FOLDER_DIALOG("Assets-Ordner waehlen")',
      'IF ordner <> "" THEN PRINT DIRLIST(ordner)',
    ]),

  H.h2("Text packen: COMPRESS$ & DECOMPRESS$"),
  H.cmd("COMPRESS$ · DECOMPRESS$", 'COMPRESS$(text$)   DECOMPRESS$(gepackt$)',
    "COMPRESS$ packt einen Text zusammen (DEFLATE) und liefert das Ergebnis als Base64-Text – also wieder als ganz normalen String, den du speichern oder verschicken kannst. DECOMPRESS$ packt ihn wieder aus. Bei Spielstand-artigem Text schrumpft die Größe typisch auf etwa ein Neuntel.",
    [
      'DIM stand AS STRING',
      'stand = "gold=1200;level=7;name=Anna"',
      'DIM klein AS STRING',
      'klein = COMPRESS$(stand)',
      'PRINT DECOMPRESS$(klein) = stand',
    ], { out: ["TRUE"] }),
  H.tip("Speicherstände leicht gemacht", "Für echte Spielstände musst du Dateien nicht selbst Zeile für Zeile verwalten: Das save-Modul (Teil V) bietet komfortable Save-Slots mit benannten Werten, und das json-Modul speichert ganze Datenstrukturen. Die rohen Datei-Befehle hier sind die Grundlage darunter."),
  H.p("Damit endet Teil III. Du kennst nun die wichtigsten eingebauten Befehle für Konsole, Mathematik, Zufall, Text, Typen, Sammlungen, Zeit und Dateien. In Teil IV geht es um das, wofür GameBasic gemacht ist: Grafik, Sound und Spiele."),
];
