module.exports = (H) => [
  H.chapter("Bytes und Binärdateien"),
  H.p("STRING ist UTF-8-Text. Er kann gar nicht jede Bytefolge tragen, und LEN zählt darin Zeichen, nicht Bytes. Sobald es um Daten statt um Text geht – ein eigenes Dateiformat, ein Bild, ein Netz-Protokoll, eine Prüfsumme – braucht es einen zweiten Typ. Das ist BUFFER: eine veränderliche Folge von Bytes."),
  H.code([
    "DIM b AS BUFFER",
    "b = BUFFER_NEW(4)          ' 4 Bytes, alle 0",
    "BUFFER_SET(b, 0, 222)",
    "PRINT BUFFER_TO_HEX$(b)    ' de000000",
  ]),
  H.p("BUFFER braucht kein IMPORT. Und es ist ein Referenz-Typ wie ARRAY: Gibt man ihn an eine SUB, teilen sich beide Seiten dieselben Bytes – eine Änderung drinnen ist auch draußen sichtbar."),

  H.h2("Anlegen und einzelne Bytes"),
  H.cmd("BUFFER_NEW · BUFFER_LEN", "BUFFER_NEW(groesse)   BUFFER_LEN(b)",
    "Legt einen Puffer der angegebenen Größe an, gefüllt mit Nullen. BUFFER_LEN liefert die Länge in Bytes – nicht in Zeichen, das ist hier derselbe Unterschied wie zwischen Byte und Buchstabe.",
    [
      "DIM b AS BUFFER",
      "b = BUFFER_NEW(8)",
      "PRINT BUFFER_LEN(b)     ' 8",
    ]),
  H.cmd("BUFFER_GET · BUFFER_SET", "BUFFER_GET(b, pos)   BUFFER_SET(b, pos, byte)",
    "Liest bzw. schreibt ein einzelnes Byte (0 bis 255). BUFFER_SET verändert den Puffer an Ort und Stelle – es entsteht keine Kopie.",
    [
      "BUFFER_SET(b, 0, 222)",
      "PRINT BUFFER_GET(b, 0)     ' 222",
    ]),
  H.cmd("BUFFER_FILL · BUFFER_RESIZE", "BUFFER_FILL(b, byte)   BUFFER_RESIZE(b, groesse)",
    "BUFFER_FILL setzt alle Bytes auf denselben Wert. BUFFER_RESIZE ändert die Größe: Der Puffer wächst mit Nullen und schrumpft, indem hinten abgeschnitten wird.",
    [
      "BUFFER_FILL(b, 255)",
      "BUFFER_RESIZE(b, 4)",
      "PRINT BUFFER_TO_HEX$(b)    ' ffffffff",
    ]),
  H.warn("Ein Index daneben ist ein Fehler, ein Ausschnitt klemmt. BUFFER_GET(b, 99) auf einen Vier-Byte-Puffer bricht ab; BUFFER_SLICE(b, 0, 99) liefert einfach die vorhandenen vier Bytes. Und ein Byte außerhalb 0 bis 255 wird nicht still beschnitten, sondern abgelehnt – beschnitten fiele es erst in der fertigen Ausgabedatei auf.",
    "Zwei verschiedene Strengen"),

  H.h2("Teile und Fundstellen"),
  H.cmd("BUFFER_SLICE · BUFFER_CONCAT", "BUFFER_SLICE(b, von, bis)   BUFFER_CONCAT(a, b)",
    "BUFFER_SLICE liefert eine Kopie der Bytes von einer Stelle bis vor eine andere. BUFFER_CONCAT setzt zwei Puffer zu einem neuen zusammen. Beide erzeugen einen neuen Puffer – die Ausgangsdaten bleiben, wie sie waren.",
    [
      "DIM kopf AS BUFFER",
      "kopf = BUFFER_SLICE(b, 0, 2)",
      "PRINT BUFFER_LEN(BUFFER_CONCAT(kopf, kopf))    ' 4",
    ]),
  H.cmd("BUFFER_INDEXOF", "BUFFER_INDEXOF(b, nadel[, ab])",
    "Sucht eine Bytefolge im Puffer und liefert die erste Fundstelle oder -1. Mit ab suchst du weiter hinten – so findest du alle Vorkommen nacheinander.",
    [
      "DIM daten AS BUFFER",
      "DIM marke AS BUFFER",
      'daten = BUFFER_FROM_STRING("abcXYZabc")',
      'marke = BUFFER_FROM_STRING("XYZ")',
      "PRINT BUFFER_INDEXOF(daten, marke)     ' 3",
    ]),

  H.h2("Zwischen Text und Bytes"),
  H.cmd("BUFFER_FROM_STRING · BUFFER_TO_STRING$", "BUFFER_FROM_STRING(text$)   BUFFER_TO_STRING$(b)",
    "Der Weg hin und zurück: Text als UTF-8-Bytes und Bytes wieder als Text.",
    [
      "DIM t AS BUFFER",
      't = BUFFER_FROM_STRING("Grüße")',
      "PRINT BUFFER_LEN(t)            ' 7 Bytes für 5 Zeichen",
      "PRINT BUFFER_TO_STRING$(t)",
    ]),
  H.warn("BUFFER_TO_STRING$ ist streng: Sind die Bytes kein gültiges UTF-8, gibt es einen Fehler statt stillschweigend ersetzter Zeichen. Ein Fragezeichen an der falschen Stelle fälscht die Daten und fällt erst viel später auf. Für Daten, die gar kein Text sein sollen, ist BUFFER_TO_HEX$ das richtige Werkzeug.",
    "Nicht jede Bytefolge ist Text"),
  H.cmd("BUFFER_TO_HEX$ · BUFFER_FROM_HEX", "BUFFER_TO_HEX$(b)   BUFFER_FROM_HEX(text$)",
    "Bytes als Hex-Text und zurück. Beim Lesen sind Leerzeichen erlaubt, weil Hex-Dumps üblicherweise gruppiert geschrieben werden.",
    [
      "DIM h AS BUFFER",
      'h = BUFFER_FROM_HEX("de ad be ef")',
      "PRINT BUFFER_TO_HEX$(h)        ' deadbeef",
    ]),
  H.cmd("BUFFER_TO_BASE64$ · BUFFER_FROM_BASE64", "BUFFER_TO_BASE64$(b)   BUFFER_FROM_BASE64(text$)",
    "Bytes als Base64 und zurück – die Form, in der Binärdaten durch JSON, XML und E-Mail passen. BUFFER_FROM_BASE64 liefert rohe Bytes, im Unterschied zu BASE64_DECODE, das gültiges UTF-8 verlangt und sonst abbricht.",
    [
      "PRINT BUFFER_TO_BASE64$(BUFFER_FROM_HEX(\"deadbeef\"))",
    ]),

  H.h2("Zahlen packen"),
  H.p("Ein eigenes Dateiformat besteht selten nur aus einzelnen Bytes. Diese Befehle legen ganze Zahlen und Kommazahlen an eine Stelle im Puffer – und holen sie wieder heraus."),
  H.cmd("BUFFER_SET_I16 · U16 · I32 · U32 · I64", "BUFFER_SET_I32(b, pos, wert[, reihenfolge$])",
    "Schreibt eine ganze Zahl an die Stelle pos. Die Breite steckt im Namen: I16 und U16 sind zwei Bytes, I32 und U32 vier, I64 acht. Das U steht für vorzeichenlos.",
    [
      "DIM b AS BUFFER",
      "b = BUFFER_NEW(8)",
      "BUFFER_SET_I32(b, 0, 1000)          ' e8030000",
      'BUFFER_SET_I32(b, 4, 1000, "be")    \' 000003e8',
      "PRINT BUFFER_TO_HEX$(b)",
    ]),
  H.cmd("BUFFER_GET_I16 · U16 · I32 · U32 · I64", "BUFFER_GET_I32(b, pos[, reihenfolge$])",
    "Liest eine ganze Zahl von der Stelle pos, in derselben Breite und Reihenfolge, in der sie geschrieben wurde.",
    [
      "PRINT BUFFER_GET_I32(b, 0)          ' 1000",
      'PRINT BUFFER_GET_I32(b, 4, "be")    \' 1000',
    ]),
  H.cmd("BUFFER_SET_F32 · BUFFER_SET_F64 · BUFFER_GET_F32 · BUFFER_GET_F64", "BUFFER_SET_F64(b, pos, wert[, reihenfolge$])   BUFFER_GET_F64(b, pos[, reihenfolge$])",
    "Dasselbe für Kommazahlen: F32 belegt vier Bytes, F64 acht. F32 ist deutlich ungenauer – für Bildschirmkoordinaten reicht es, für Geldbeträge nicht.",
    [
      "DIM f AS BUFFER",
      "f = BUFFER_NEW(8)",
      "BUFFER_SET_F64(f, 0, 3.5)",
      "PRINT BUFFER_GET_F64(f, 0)          ' 3.5",
    ]),
  H.note("Die Reihenfolge (\"le\" oder \"be\") sagt, ob das niederwertigste Byte zuerst steht. Wer einen Puffer selbst schreibt und wieder liest, kann sie ignorieren – beide Seiten benutzen dieselbe Vorgabe. Die Angabe braucht nur, wer ein fremdes Format bedient: PNG, ZIP und die meisten Netz-Protokolle sind big-endian.",
    "Wozu die Byte-Reihenfolge"),
  H.warn("Ein Wert, der nicht in die Breite passt, ist ein Fehler – BUFFER_SET_U16(b, 0, 70000) bricht ab. Still abgeschnitten käme eine völlig andere Zahl wieder heraus, und zwar erst beim Wiedereinlesen.",
    "Merke"),

  H.h2("Binärdateien lesen und schreiben"),
  H.cmd("READALL_BYTES · WRITEALL_BYTES", "READALL_BYTES(pfad$)   WRITEALL_BYTES(pfad$, b)",
    "Eine ganze Datei als Bytes lesen bzw. Bytes in eine Datei schreiben (die dabei überschrieben wird). Für alles, was in den Speicher passt, ist das der kürzeste Weg.",
    [
      "DIM bild AS BUFFER",
      'bild = READALL_BYTES("logo.png")',
      "PRINT BUFFER_LEN(bild)",
      'WRITEALL_BYTES("kopie.png", bild)',
    ]),
  H.cmd("READ_BYTES · WRITE_BYTES", "READ_BYTES(datei, anzahl)   WRITE_BYTES(datei, b)",
    "Stückweise von einem Datei-Handle lesen bzw. dorthin schreiben – für Dateien, die zu groß für den Speicher sind. READ_BYTES liefert am Dateiende weniger als angefordert, bis hin zu gar nichts; das ist kein Fehler, sondern die übliche Abbruchbedingung.",
    [
      "DIM f AS FILE",
      "DIM stueck AS BUFFER",
      "DIM gesamt AS INTEGER",
      'f = OPENFILE("gross.bin", "r")',
      "REPEAT",
      "    stueck = READ_BYTES(f, 65536)",
      "    gesamt = gesamt + BUFFER_LEN(stueck)",
      "UNTIL BUFFER_LEN(stueck) = 0",
      "CLOSEFILE(f)",
      "PRINT gesamt",
    ]),
  H.cmd("SEEK · TELL", "SEEK(datei, position)   TELL(datei)",
    "Setzt die Leseposition in einer offenen Datei bzw. fragt sie ab (0 ist der Anfang). Damit springst du gezielt an eine Stelle, statt alles davor zu lesen – etwa zu einem Eintrag, dessen Position im Kopf der Datei steht.",
    [
      "DIM f AS FILE",
      'f = OPENFILE("gross.bin", "r")',
      "SEEK(f, 1024)",
      "PRINT TELL(f)        ' 1024",
      "CLOSEFILE(f)",
    ]),
  H.note("Es gibt keine eigenen Binär-Modi wie „rb“ oder „wb“. Drachenhauch-Dateien sind immer byte-genau: Es gibt keine Umsetzung von Zeilenenden und kein Ctrl-Z als Dateiende wie in alten BASICs. Getrennte Modi würden einen Unterschied vorgaukeln, den es nicht gibt – READ_BYTES, WRITE_BYTES und SEEK arbeiten auf denselben Handles wie READLINE und WRITELINE.",
    "Merke"),

  H.h2("Ein eigenes Dateiformat"),
  H.p("Alles zusammen: ein winziges Format mit Kennung, Version und einer Zahl. Genau so sind die großen Formate auch aufgebaut, nur länger."),
  H.code([
    "DIM b AS BUFFER",
    "DIM kennung AS BUFFER",
    "",
    'kennung = BUFFER_FROM_STRING("DH01")',
    "b = BUFFER_NEW(12)",
    "",
    "' 0..3 Kennung, 4..7 Punktestand, 8..11 Spielzeit",
    "BUFFER_SET(b, 0, BUFFER_GET(kennung, 0))",
    "BUFFER_SET(b, 1, BUFFER_GET(kennung, 1))",
    "BUFFER_SET(b, 2, BUFFER_GET(kennung, 2))",
    "BUFFER_SET(b, 3, BUFFER_GET(kennung, 3))",
    "BUFFER_SET_I32(b, 4, 4711)",
    "BUFFER_SET_F32(b, 8, 63.5)",
    "",
    'WRITEALL_BYTES("spielstand.dh1", b)',
    "",
    "' ... und wieder einlesen",
    "DIM e AS BUFFER",
    'e = READALL_BYTES("spielstand.dh1")',
    'IF BUFFER_TO_STRING$(BUFFER_SLICE(e, 0, 4)) <> "DH01" THEN',
    '    PRINT "keine Spielstand-Datei"',
    "ELSE",
    '    PRINT "Punkte: "; BUFFER_GET_I32(e, 4)',
    '    PRINT "Zeit:   "; BUFFER_GET_F32(e, 8)',
    "END IF",
  ]),
  H.tip("Erst die Kennung prüfen, dann lesen", "Die vier Bytes am Anfang kosten nichts und verhindern den ärgerlichsten Fall: dass eine fremde Datei als Spielstand gelesen wird und irgendwelche Zahlen ergibt. Jedes verbreitete Format macht das so – PNG, ZIP und PDF fangen alle mit einer festen Kennung an."),
];
