module.exports = (H) => [
  H.chapter("CSV, ZIP & Mengen"),
  H.p("Drei kleine Werkzeuge, die man selten sucht und dann dringend braucht: Tabellen austauschen, mehrere Dateien als eine weitergeben, und sich merken, was man schon gesehen hat."),

  H.h2("CSV: der häufigste Datenaustausch überhaupt"),
  H.p("Und mit SPLIT$ nicht richtig zu machen. Sobald ein Feld das Trennzeichen enthält, liefert SPLIT$ zu viele Felder und sagt nichts davon – aus der Zeile Mueller;\"Berlin; Mitte\";42 werden vier Felder statt drei."),
  H.cmd("CSV_PARSE · CSV_LOAD", "CSV_PARSE(text$[, trenner$])   CSV_LOAD(pfad$[, trenner$[, kodierung$]])",
    "Zerlegt CSV-Text bzw. eine CSV-Datei in ein zweidimensionales ARRAY OF STRING: erste Achse Zeilen, zweite Spalten. Ohne Angabe ist der Trenner ein Komma; Excel schreibt im deutschen Gebietsschema ein Semikolon.",
    [
      "DIM t AS ARRAY OF STRING",
      't = CSV_LOAD("kunden.csv", ";")',
      "PRINT DIMSIZE(t, 0)     ' Zeilen",
      "PRINT DIMSIZE(t, 1)     ' Spalten",
      "PRINT t[1, 2]           ' zweite Zeile, dritte Spalte",
    ]),
  H.tip("Aus Excel kommt meist cp1252", "Wer eine Datei öffnet, die Excel im deutschen Gebietsschema geschrieben hat, braucht beides: CSV_LOAD(\"kunden.csv\", \";\", \"cp1252\"). Sonst stehen an den Umlauten Fragezeichen oder es bricht ab."),
  H.cmd("CSV_FORMAT$ · CSV_SAVE", "CSV_FORMAT$(tabelle[, trenner$])   CSV_SAVE(pfad$, tabelle[, trenner$[, kodierung$]])",
    "Der Weg zurück: ein zweidimensionales Array als CSV-Text bzw. direkt in eine Datei. Anführungszeichen setzt Drachenhauch nur, wo sie nötig sind – unnötige machen die Datei unleserlich und den Vergleich zweier Fassungen größer.",
    [
      "DIM z AS ARRAY OF STRING",
      "z = CSV_PARSE(\"a,b\" + CHR$(10) + \"c,d\")",
      'CSV_SAVE("kopie.csv", z, ";")',
      "PRINT CSV_FORMAT$(z)",
    ]),
  H.cmd("CSV_ROW$", "CSV_ROW$(felder[, trenner$])",
    "Baut eine einzelne CSV-Zeile aus einem eindimensionalen Array – für den Fall, dass du eine Datei Zeile für Zeile schreibst, statt erst die ganze Tabelle im Speicher aufzubauen.",
    [
      "DIM f AS ARRAY OF STRING",
      'f = SPLIT$("Mueller|Berlin, Mitte|42", "|")',
      "PRINT CSV_ROW$(f, \";\")   ' Mueller;Berlin, Mitte;42",
      "PRINT CSV_ROW$(f)        ' Mueller,\"Berlin, Mitte\",42",
    ]),
  H.p("Die beiden Zeilen zeigen die Regel besser als jede Erklärung: Derselbe Datensatz bekommt mit Semikolon als Trenner keine Anführungszeichen, mit Komma schon – weil das mittlere Feld dann eines enthält."),
  H.note("Ungleich lange Zeilen werden auf die breiteste aufgefüllt, weil ein Array rechteckig sein muss – abschneiden würde Daten wegwerfen, ohne es zu sagen. Eine kaputte Datei bricht den Import nicht ab: Eine fehlende Schluss-Anführung liest bis zum Dateiende. Beide Zeilenenden gelten, und ein BOM am Dateianfang wird abgeschnitten – sonst hieße die erste Spalte für immer mit einem unsichtbaren Zeichen davor.",
    "Was beim Lesen passiert"),

  H.h2("ZIP: mehrere Dateien als eine"),
  H.p("Sicherungen, Belegsammlungen, Export – der übliche Weg, mehreres zusammen weiterzugeben. Alle Befehle arbeiten direkt auf der Archivdatei; es gibt kein Handle, das offen bleibt."),
  H.cmd("ZIP_LIST", "ZIP_LIST(archiv$)",
    "Die Namen aller Einträge als ARRAY OF STRING, ohne etwas zu entpacken.",
    [
      "DIM drin AS ARRAY OF STRING",
      'drin = ZIP_LIST("sicherung.zip")',
      'PRINT JOIN$(drin, ", ")',
    ]),
  H.cmd("ZIP_READ$ · ZIP_READ", "ZIP_READ$(archiv$, name$)   ZIP_READ(archiv$, name$)",
    "Einen einzelnen Eintrag herausholen – als Text oder als BUFFER, ohne das ganze Archiv auszupacken. Für ein Bild oder eine Datenbank aus dem Archiv nimmst du die Byte-Fassung.",
    [
      'PRINT ZIP_READ$("sicherung.zip", "brief.txt")',
    ]),
  H.cmd("ZIP_EXTRACT", "ZIP_EXTRACT(archiv$, ordner$)",
    "Packt alles in einen Ordner aus und liefert die Zahl der wirklich entstandenen Dateien.",
    [
      'PRINT ZIP_EXTRACT("sicherung.zip", "entpackt")',
    ]),
  H.warn("Beim Entpacken wird geprüft, wohin geschrieben wird. Ein Archiv darf Einträge wie ../../autoexec.bat oder C:/Windows/x.dll enthalten; wer den Namen aus dem Archiv einfach an den Zielordner hängt, schreibt damit außerhalb davon – der Angreifer wählt die Datei, du entpackst sie. Solche Einträge werden übersprungen. Deshalb liefert ZIP_EXTRACT die Zahl der entstandenen Dateien zurück: Ein Unterschied zur Länge von ZIP_LIST fällt so auf.",
    "Ein Archiv ist fremder Text"),
  H.cmd("ZIP_CREATE · ZIP_WRITE", "ZIP_CREATE(archiv$, dateien)   ZIP_WRITE(archiv$, namen, inhalte)",
    "Zwei Wege, ein Archiv zu bauen: ZIP_CREATE aus einer Liste vorhandener Dateipfade, ZIP_WRITE aus Namen und Texten ohne Umweg über die Platte. Beide liefern die Zahl der geschriebenen Einträge.",
    [
      "DIM namen AS ARRAY OF STRING",
      "DIM inhalte AS ARRAY OF STRING",
      'namen = SPLIT$("brief.txt|unter/notiz.txt", "|")',
      'inhalte = SPLIT$("Hallo Welt|zweite Datei", "|")',
      'PRINT ZIP_WRITE("sicherung.zip", namen, inhalte)',
    ]),
  H.note("ZIP_CREATE speichert nur den Dateinamen, nicht den Pfad, unter dem die Datei lag – sonst trägt ein Archiv die Verzeichnisstruktur des Rechners nach außen, auf dem es entstanden ist. Wer eine Ordnerstruktur im Archiv haben will, baut sie mit ZIP_WRITE über die Namen auf.",
    "Merke"),

  H.h2("Mengen: was habe ich schon gesehen?"),
  H.p("Eine Menge ist eine MAP OF INTEGER, deren Werte niemanden interessieren – es gibt keinen eigenen Typ. Die Befehle nehmen dir nur den STR$-Umweg und den Dummy-Wert ab."),
  H.cmd("SET_ADD · SET_HAS · SET_REMOVE", "SET_ADD(menge, wert)   SET_HAS(menge, wert)   SET_REMOVE(menge, wert)",
    "Aufnehmen, nachfragen, entfernen. Etwas zweimal aufzunehmen ist kein Fehler und ändert nichts. SET_REMOVE liefert TRUE, wenn das Element wirklich drin war.",
    [
      "DIM gesehen AS MAP OF INTEGER",
      "SET_ADD(gesehen, 4711)",
      "SET_ADD(gesehen, 4711)             ' kein Effekt",
      'IF SET_HAS(gesehen, 4711) THEN PRINT "kenne ich schon"',
      "PRINT SET_REMOVE(gesehen, 4711)    ' TRUE",
    ]),
  H.cmd("SET_SIZE · SET_ITEMS · SET_CLEAR", "SET_SIZE(menge)   SET_ITEMS(menge)   SET_CLEAR(menge)",
    "Die Anzahl der Elemente, alle Elemente als ARRAY in Aufnahme-Reihenfolge, und alles wieder leeren.",
    [
      "DIM m AS MAP OF INTEGER",
      "DIM alle AS ARRAY OF STRING",
      'SET_ADD(m, "gruen")',
      'SET_ADD(m, "blau")',
      "PRINT SET_SIZE(m)      ' 2",
      "alle = SET_ITEMS(m)",
      'PRINT JOIN$(alle, ", ")',
      "SET_CLEAR(m)",
    ]),
  H.warn("Eine Menge führt eine Elementart. Elemente dürfen Zahlen oder Zeichenketten sein, aber nicht gemischt – die erste Aufnahme legt die Art fest, jede spätere Abweichung meldet einen Fehler. Das ist Absicht: Innen sind Schlüssel immer Zeichenketten, und ohne diese Regel fielen die Zahl 5 und der Text \"5\" auf denselben Eintrag. Die Menge hätte danach ein Element statt zwei – still und ohne Hinweis.",
    "Zahlen oder Text, nicht beides"),
  H.h2("Doppelte aussortieren"),
  H.p("Der häufigste Grund für eine Menge: eine Liste durchgehen und jedes Element nur einmal behandeln."),
  H.code([
    "DIM gesehen AS MAP OF INTEGER",
    "DIM zeilen AS ARRAY OF STRING",
    "DIM i AS INTEGER",
    "",
    'zeilen = SPLIT$("Meier|Schulz|Meier|Kunze", "|")',
    "FOR i = 0 TO LEN(zeilen) - 1",
    "    IF NOT SET_HAS(gesehen, zeilen[i]) THEN",
    "        SET_ADD(gesehen, zeilen[i])",
    "        PRINT zeilen[i]",
    "    END IF",
    "NEXT",
    'PRINT "verschiedene: "; SET_SIZE(gesehen)',
  ]),
];
