module.exports = (H) => [
  H.chapter("Programme, Aufträge & Umgebung"),
  H.p("Bis hierher war ein Drachenhauch-Programm für sich allein. Dieses Kapitel öffnet es nach außen: Es liest die Argumente seiner eigenen Kommandozeile, startet andere Programme, lässt eigene Funktionen nebenher rechnen und findet sich im Dateisystem zurecht."),

  H.h2("Die eigene Kommandozeile"),
  H.cmd("ARGC · ARG$", "ARGC()   ARG$(n)",
    "Wie viele Argumente beim Start mitgegeben wurden und wie das n-te lautet (ab 0 gezählt). Ein Index außerhalb liefert einen leeren Text statt eines Fehlers – so kann man ein fehlendes Argument abfragen, ohne erst zu zählen.",
    [
      "DIM pfad AS STRING",
      "IF ARGC() < 1 THEN",
      '    EPRINT("Verwendung: zaehle <datei>")',
      "    EXIT(2)",
      "END IF",
      "pfad = ARG$(0)",
    ]),
  H.cmd("EXIT · EPRINT", "EXIT([code])   EPRINT(text)",
    "EXIT beendet das Programm sofort mit einem Rückgabewert (0 bis 255, ohne Angabe 0). EPRINT schreibt eine Zeile nach stderr statt nach stdout – dorthin gehören Fehlermeldungen, damit sie sich nicht unter die Nutzdaten mischen, wenn jemand die Ausgabe weiterleitet.",
    [
      'EPRINT("Datei nicht gefunden")',
      "EXIT(1)",
    ]),
  H.tip("Warum stderr und ein Rückgabewert zusammengehören", "Ein Werkzeug, das in einer Kette steht, wird an zwei Dingen gemessen: was auf stdout kommt und ob der Rückgabewert 0 ist. Wer Fehlermeldungen nach stdout schreibt, verdirbt der nächsten Stufe die Daten; wer immer 0 zurückgibt, lässt ein Skript fröhlich weiterlaufen, obwohl nichts entstanden ist."),

  H.h2("Umgebung und Arbeitsverzeichnis"),
  H.cmd("GETENV$ · SETENV", "GETENV$(name$[, vorgabe$])   SETENV(name$, wert$)",
    "Eine Umgebungsvariable lesen bzw. setzen. Gesetzt wird sie für dieses Programm und alle Programme, die es startet – nicht für die Konsole, aus der es kam.",
    [
      "DIM heim AS STRING",
      'heim = GETENV$("USERPROFILE", "C:/")',
      'SETENV("MEIN_MODUS", "test")',
    ]),
  H.cmd("CWD$ · CHDIR", "CWD$()   CHDIR(pfad$)",
    "Das aktuelle Arbeitsverzeichnis lesen bzw. wechseln – die Grundlage aller relativen Pfade.",
    [
      "PRINT CWD$()",
      'CHDIR("daten")',
    ]),
  H.warn("CWD$() ist nicht das Verzeichnis, aus dem der Benutzer gestartet hat. dhrt wechselt beim Start ins Verzeichnis der .dh-Datei, damit LOADIMAGE(\"assets/...\") von überall funktioniert; eine exportierte Anwendung wechselt ins Verzeichnis ihrer eigenen Datei. Ein Pfad, den der Benutzer als Argument übergibt, ist also relativ zu seinem Verzeichnis, nicht zu CWD$(). Im Zweifel nach einem vollständigen Pfad fragen.",
    "Die häufigste Verwechslung"),

  H.h2("Andere Programme starten"),
  H.cmd("SHELL · SHELL_OUT$", "SHELL(programm$, ...)   SHELL_OUT$(programm$, ...)",
    "Startet ein Programm und wartet, bis es fertig ist. SHELL liefert dessen Rückgabewert und reicht die Ausgabe zur Konsole durch; SHELL_OUT$ sammelt stattdessen dessen stdout ein und liefert es als Text, während dessen stderr stderr bleibt – sonst mischten sich Fehlermeldungen unbemerkt in die Nutzdaten.",
    [
      "DIM zweige AS STRING",
      'zweige = SHELL_OUT$("git", "branch", "--list")',
      "PRINT zweige",
    ]),
  H.warn("SHELL nimmt die Argumente einzeln, nicht als eine Kommandozeile: SHELL(\"git\", \"commit\", \"-m\", \"Nachricht mit Leerzeichen\"). So gibt es keine Anführungsregeln zu lernen, und ein Dateiname mit Leerzeichen zerfällt nicht in zwei Argumente. Wer wirklich eine Shell braucht – für Pipes oder Umleitungen – ruft sie ausdrücklich auf und unterliegt dann deren eigenen Regeln.",
    "Argumente einzeln"),
  H.cmd("SHELL_START · SHELL_READY · SHELL_RESULT$", "SHELL_START(programm$, ...)   SHELL_READY(auftrag)   SHELL_RESULT$(auftrag)",
    "Dasselbe, ohne zu warten: SHELL_START liefert eine Auftragsnummer, SHELL_READY fragt nach, SHELL_RESULT$ holt die Ausgabe ab und gibt den Platz frei. Dauert ein Programm länger als ein Bild, ist das der Weg – sonst steht das Spiel.",
    [
      "DIM auftrag AS INTEGER",
      "DIM ausgabe AS STRING",
      'auftrag = SHELL_START("git", "log", "--oneline")',
      "WHILE NOT SHELL_READY(auftrag)",
      "    ' ... hier weiterarbeiten, zeichnen, auf Tasten hören ...",
      "    SLEEP(1)",
      "WEND",
      "ausgabe = SHELL_RESULT$(auftrag)",
    ]),
  H.cmd("SHELL_CODE · SHELL_ERR$", "SHELL_CODE()   SHELL_ERR$()",
    "Der Rückgabewert und die Fehlerausgabe des zuletzt abgeholten Auftrags. Beide nehmen kein Argument – dasselbe Muster wie HTTP_STATUS zur zuletzt geholten Antwort. Ein Programm, das gar nicht erst startet, meldet sich beim Abholen, nicht beim Starten.",
    [
      "IF SHELL_CODE() <> 0 THEN",
      '    EPRINT("git meldet: " + SHELL_ERR$())',
      "END IF",
    ]),
  H.cmd("SHELL_CANCEL · SHELL_PENDING", "SHELL_CANCEL(auftrag)   SHELL_PENDING()",
    "Einen Auftrag verwerfen bzw. zählen, wie viele noch nicht abgeholt sind.",
    [
      "PRINT SHELL_PENDING()",
    ]),

  H.h2("Eigene Funktionen im Hintergrund"),
  H.p("TASK_START lässt deine eigene Funktion nebenher rechnen, während die Hauptschleife weiterläuft – für eine Kartengenerierung, eine große Auswertung, alles was länger dauert als ein Bild."),
  H.cmd("WINDOW_OPEN · WINDOW_SEND · WINDOW_RECV$ · WINDOW_ALIVE · WINDOW_CLOSE", 'WINDOW_OPEN(datei$ [, arg1, ...]) AS INTEGER   WINDOW_SEND(fenster, text$)   WINDOW_RECV$(fenster) AS STRING   WINDOW_ALIVE(fenster) AS BOOLEAN   WINDOW_CLOSE(fenster)',
    "Ein zweites OS-Fenster ist ein zweiter dhrt: WINDOW_OPEN startet datei$ als eigenes Programm mit eigenem SCREEN (Argumente kommen dort als ARG$ an) und liefert eine Fensternummer. Beide Seiten reden über Textzeilen: WINDOW_SEND schickt eine, WINDOW_RECV$ holt die nächste (\"\" wenn keine da ist), WINDOW_ALIVE sagt, ob der Prozess noch läuft, WINDOW_CLOSE beendet ihn. Kein geteilter Speicher – was hinüber soll, wird Text; ein Dokument liegt in einer Datei oder Datenbank, die beide öffnen. Fällt die Verbindung, beendet sich das Kind von selbst.",
    [
      'DIM k AS INTEGER : k = WINDOW_OPEN("rechnung_fenster.dh", "rechnungen.db", 7)',
      'IF WINDOW_RECV$(k) = "geaendert 7" THEN neuLaden()',
      'IF NOT WINDOW_ALIVE(k) THEN PRINT "Fenster geschlossen"',
    ]),
  H.cmd("PARENT_SEND · PARENT_RECV$ · PARENT_ALIVE", 'PARENT_SEND(text$)   PARENT_RECV$() AS STRING   PARENT_ALIVE() AS BOOLEAN',
    "Die Gegenseite im Kindprogramm: eine Zeile an das Hauptprogramm schicken, die nächste von ihm holen, und fragen, ob es Eltern gibt. PARENT_ALIVE liefert FALSE, wenn das Programm allein gestartet wurde – so läuft dieselbe Datei auch ohne Hauptprogramm, nur ohne die Meldungen.",
    [
      'IF PARENT_ALIVE() THEN PARENT_SEND("geaendert " + STR$(id))',
      'IF PARENT_RECV$() = "neu" THEN laden()',
    ]),
  H.cmd("TASK_START · TASK_READY · TASK_RESULT$", "TASK_START(funktion[, arg1, arg2, …])   TASK_READY(auftrag)   TASK_RESULT$(auftrag)",
    "Startet die Funktion (ohne Klammern hingeschrieben, wie eine FUNCREF) und liefert eine Auftragsnummer. TASK_READY fragt nach, TASK_RESULT$ holt das Ergebnis ab – einmal.",
    [
      "DIM auftrag AS INTEGER",
      "auftrag = TASK_START(BerechneKarte, 4242)",
      "WHILE NOT TASK_READY(auftrag)",
      "    SLEEP(10)",
      "WEND",
      "PRINT TASK_RESULT$(auftrag)",
    ]),
  H.cmd("TASK_CANCEL · TASK_PENDING", "TASK_CANCEL(auftrag)   TASK_PENDING()",
    "Ein Ergebnis verwerfen bzw. zählen, wie viele Aufträge noch nicht abgeholt sind.",
    [
      "TASK_CANCEL(auftrag)",
    ]),
  H.warn("Warte nicht ohne Pause. TASK_READY fragt nur nach und kehrt sofort zurück – eine Schleife darum herum läuft so schnell, wie der Rechner kann, und verbrennt einen Kern, während der Auftrag daneben rechnen soll. In einem Spiel bremst FLIP() die Schleife ohnehin auf die Bildrate; in einem Konsolenprogramm gehört ein SLEEP(10) hinein.",
    "Die leerlaufende Warteschleife"),
  H.h2("Drei Dinge, die aus dem eigenen Prozess folgen"),
  H.p("Ein Auftrag läuft als eigener Prozess, nicht als Thread. Daraus folgt dreierlei, und alle drei überraschen beim ersten Mal."),
  H.p("Erstens: Ein Auftrag sieht deine globalen Variablen nicht, auch keine CONST auf oberster Ebene. Das Hauptprogramm läuft im Auftragsprozess nämlich gar nicht. Gib der Funktion als Parameter mit, was sie braucht – die Meldung erklärt das, wenn es passiert. Dieselbe Grenze gilt für ein mit AS importiertes Modul, und dort wie hier ist sie der eigentliche Gewinn: Die Funktion hängt nicht mehr davon ab, was zufällig oben im Programm steht."),
  H.p("Zweitens: Argumente und Ergebnis sind Zahl, Text oder BOOLEAN. Beliebig viele Argumente sind erlaubt, aber ein Objekt oder ein Array geht nicht über eine Prozessgrenze – wer mehr braucht, reicht JSON durch. Ein Text mit Leerzeichen bleibt ein Argument. Das Ergebnis kommt immer als STRING zurück; für eine Zahl also VAL(TASK_RESULT$(a))."),
  H.p("Drittens: Ein Start kostet rund zwölf Millisekunden. Für „rechne nebenher, während die Schleife sich dreht“ fällt das nicht auf. Für tausend kleine Aufträge je Sekunde ist es der falsche Befehl – dann rechne im Hauptprogramm."),
  H.warn("TASK_PENDING zählt, was noch nicht abgeholt ist – nicht, was noch rechnet. Ein fertiger, aber nicht abgeholter Auftrag zählt mit. Deshalb wartet WHILE TASK_PENDING() > 0 ewig, wenn erst danach abgeholt wird: Gefragt wird pro Auftrag mit TASK_READY. Dasselbe gilt für SHELL_PENDING und DB_QUERY_PENDING.",
    "Was PENDING wirklich zählt"),
  H.note("Was der Auftrag selbst mit PRINT ausgibt, kommt nicht zurück – ein Auftrag rechnet, er redet nicht.",
    "Merke"),

  H.h2("Standardeingabe lesen"),
  H.cmd("STDIN", "STDIN([kodierung$])",
    "Liefert die Standardeingabe als Datei-Handle. Damit liest ein Drachenhauch-Programm, was ein anderes hineinschiebt – die Voraussetzung dafür, in einer Kette von Werkzeugen mitzuspielen.",
    [
      "DIM f AS FILE",
      "DIM zeile AS STRING",
      "f = STDIN()",
      "WHILE NOT EOF(f)",
      "    zeile = READLINE(f)",
      "    PRINT UPPER$(zeile)",
      "WEND",
    ]),
];
