module.exports = (H) => [
  H.chapter("Prüfen, Melden & Prüfsummen"),
  H.p("Drei Dinge, die ein Programm erwachsen machen: Es prüft sich selbst, es sagt beim Laufen, was es tut, und es kann feststellen, ob Daten unterwegs verändert wurden."),

  H.h2("Sich selbst prüfen"),
  H.cmd("ASSERT", "ASSERT(bedingung[, meldung$])",
    "Schlägt fehl, wenn die Bedingung FALSE ist. Ohne weitere Einstellung endet das Programm dann mit einem Laufzeitfehler samt Datei und Zeile – genau wie jeder andere Fehler. Das ist die Vorgabe und der richtige Weg für eine Vorbedingung mitten im Programm.",
    [
      "DIM spieler_zahl AS INTEGER",
      "spieler_zahl = 2",
      'ASSERT(spieler_zahl > 0, "ohne Spieler geht es nicht")',
    ]),
  H.cmd("ASSERT_EQ", "ASSERT_EQ(ist, soll[, was$])",
    "Dasselbe für einen Vergleich – mit dem Unterschied, dass die Meldung beide Werte zeigt. „erhalten 2, erwartet 0“ sagt weit mehr als „Prüfung fehlgeschlagen“.",
    [
      'ASSERT_EQ(LEN("abc"), 3, "Laenge")',
    ]),
  H.warn("ASSERT verlangt einen BOOLEAN. ASSERT(anzahl) ist ein Fehler und nicht etwa „wahr, weil nicht null“. Eine Prüfung, die aus Versehen immer durchgeht, ist schlimmer als gar keine – also einen Vergleich schreiben: ASSERT(anzahl > 0).",
    "Kein Wahrheitswert aus Versehen"),
  H.note("ASSERT_EQ vergleicht genau wie der Gleichheits-Operator der Sprache, einschließlich 1 = 1.0. Eine zweite Vorstellung davon, wann zwei Werte gleich sind, wäre die sicherste Art, das Vertrauen in die Prüfungen zu verspielen.",
    "Merke"),

  H.h2("Ein Prüfprogramm schreiben"),
  H.p("In einem Prüfprogramm will man alle Fehler sehen, nicht nur den ersten. Dafür schaltet man einmal am Anfang den Sammel-Modus ein."),
  H.cmd("ASSERT_COLLECT · ASSERT_COUNT · ASSERT_FAILED", "ASSERT_COLLECT(an)   ASSERT_COUNT()   ASSERT_FAILED()",
    "ASSERT_COLLECT(TRUE) lässt fehlgeschlagene Prüfungen weiterlaufen, statt abzubrechen. ASSERT_COUNT sagt, wie viele Prüfungen gelaufen sind, ASSERT_FAILED wie viele davon fehlschlugen.",
    [
      "ASSERT_COLLECT(TRUE)",
      "ASSERT_EQ(2 + 2, 4)",
      "ASSERT_EQ(2 * 2, 5)          ' schlaegt fehl, laeuft aber weiter",
      "PRINT ASSERT_COUNT(); \" Pruefungen, \"; ASSERT_FAILED(); \" davon fehlgeschlagen\"",
    ]),
  H.cmd("ASSERT_REPORT", "ASSERT_REPORT()",
    "Gibt die Bilanz aus und liefert die Zahl der Fehlschläge zurück. Dieser Rückgabewert ist der eigentliche Punkt: Erst damit kann ein Skript oder eine automatische Prüfung zwischen „lief durch“ und „hat Fehler gefunden“ unterscheiden.",
    [
      "ASSERT_COLLECT(TRUE)",
      'ASSERT_EQ(2 + 2, 4, "Addition")',
      "IF ASSERT_REPORT() > 0 THEN",
      "    EXIT(1)",
      "END IF",
    ]),
  H.tip("Fehlschläge nach stderr, Bilanz nach stdout", "Die einzelnen Fehlschläge gehen nach stderr, die Schlusszeile nach stdout. Ein Aufruf, der die Ausgabe in eine Datei umleitet, liefert damit einen sauberen Bericht, während die Einzelheiten weiter im Terminal stehen."),

  H.h2("Melden, was gerade passiert"),
  H.cmd("LOG_DEBUG · LOG_INFO · LOG_WARN · LOG_ERROR", "LOG_INFO(text)   LOG_WARN(text)   LOG_ERROR(text)   LOG_DEBUG(text)",
    "Schreibt eine Meldung mit Uhrzeit nach stderr – etwa „20:45:43 INFO  Saison 2026 geladen“. Nach stderr, damit die eigentliche Ausgabe des Programms als Nutzdaten durchgereicht werden kann.",
    [
      'LOG_INFO("Saison 2026 geladen")',
      'LOG_WARN("Kein Netz -- arbeite mit den gespeicherten Daten")',
      'LOG_ERROR("Datenbank nicht lesbar")',
    ]),
  H.p("Wie viel davon erscheint, steuert die Umgebungsvariable DH_LOG: debug zeigt alles, info ist die Vorgabe (INFO, WARN, ERROR), warn zeigt nur noch Warnungen und Fehler, error nur Fehler, und aus schweigt ganz."),
  H.tip("Debug-Meldungen dürfen stehenbleiben", "LOG_DEBUG schweigt, bis jemand es einschaltet. Damit müssen die Meldungen, die beim Suchen eines Fehlers geholfen haben, nicht wieder aus dem Code – sie stören den Normalbetrieb nicht und sind beim nächsten Mal sofort wieder da."),

  H.h2("Prüfsummen: sind das noch dieselben Daten?"),
  H.p("CRC32 und HASH sind zum Wiedererkennen da – sie sagen „vermutlich dieselben Daten“. Sobald aber jemand die Antwort fälschen könnte, reichen sie nicht: Signaturen, Tokens, Belege und Passwort-Ableitungen brauchen etwas anderes."),
  H.cmd("SHA256$ · SHA1$ · MD5$", "SHA256$(daten)   SHA1$(daten)   MD5$(daten)",
    "Die Prüfsumme als Hex-Text. Die Daten dürfen ein STRING sein (dann werden dessen UTF-8-Bytes genommen) oder ein BUFFER – eine Signatur bildet man über die Bytes, die wirklich übertragen werden.",
    [
      'PRINT SHA256$("abc")',
      "' ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
    ]),
  H.cmd("SHA256_FILE$ · SHA1_FILE$ · MD5_FILE$", "SHA256_FILE$(pfad$)   SHA1_FILE$(pfad$)   MD5_FILE$(pfad$)",
    "Dasselbe für eine Datei – blockweise gelesen, die Dateigröße spielt also keine Rolle.",
    [
      'PRINT SHA256_FILE$("grosses_archiv.zip")',
    ]),
  H.warn("MD5$ und SHA1$ gelten als gebrochen. Sie stehen hier, weil man sie zum Mitspielen braucht – für ETags, alte Prüfsummenlisten, git-Objektnamen. Für eine eigene Sicherheitsentscheidung ist SHA256$ die Antwort.",
    "Nicht für Neues"),

  H.h2("Eine Signatur prüfen"),
  H.cmd("HMAC_SHA256$", "HMAC_SHA256$(schluessel, daten)",
    "Eine Signatur mit geheimem Schlüssel. Wer den Schlüssel nicht hat, kann sie nicht erzeugen – daran erkennt der Empfänger, dass die Daten wirklich vom Absender stammen und unterwegs nicht verändert wurden.",
    [
      "DIM erwartet AS STRING",
      'erwartet = HMAC_SHA256$("geheim", "nutzlast")',
      "PRINT erwartet",
    ]),
  H.cmd("SECURE_EQUALS", "SECURE_EQUALS(a, b)",
    "Vergleicht zwei Zeichenketten in immer derselben Zeit. Das ist genau bei dem Vergleich wichtig, für den HMAC_SHA256$ überhaupt existiert.",
    [
      "DIM erwartet AS STRING",
      "DIM bekommen AS STRING",
      'erwartet = HMAC_SHA256$("geheim", "nutzlast")',
      "bekommen = erwartet",
      "IF SECURE_EQUALS(erwartet, bekommen) THEN",
      '    PRINT "echt"',
      "ELSE",
      '    PRINT "gefaelscht oder veraendert"',
      "END IF",
    ]),
  H.warn("SECURE_EQUALS statt des Gleichheitszeichens. Ein gewöhnlicher Vergleich bricht beim ersten ungleichen Zeichen ab. Wer eine Signatur erraten will, misst die Zeit und hat sie nach ein paar hundert Versuchen Zeichen für Zeichen zusammen. SECURE_EQUALS läuft immer vollständig durch.",
    "Warum nicht einfach ="),

  H.h2("Zufall, der kein Spiel ist"),
  H.cmd("RANDOM_BYTES · UUID4$", "RANDOM_BYTES(anzahl)   UUID4$()",
    "Zufallsbytes aus der Quelle des Betriebssystems bzw. eine zufällige eindeutige Kennung. Für Sitzungsschlüssel, Tokens, Salze und Dateinamen, die sich nicht überschneiden dürfen.",
    [
      "DIM token AS STRING",
      "token = BUFFER_TO_HEX$(RANDOM_BYTES(32))",
      "PRINT LEN(token)      ' 64 Hex-Zeichen",
      "PRINT UUID4$()",
    ]),
  H.warn("RANDOM_BYTES ist nicht RND. RND hängt an RANDOMIZE: Dieselbe Saat liefert dieselbe Folge. Für ein Würfelspiel ist das richtig und sogar erwünscht, weil sich damit ein Level reproduzieren lässt – für ein Kennwort, einen Sitzungsschlüssel oder ein Salz wäre es ein Fehler. RANDOM_BYTES kommt aus der Zufallsquelle des Betriebssystems und lässt sich von RANDOMIZE nicht beeindrucken.",
    "Der Unterschied, der zählt"),
  H.p("Damit endet Teil III. Du kennst nun die wichtigsten eingebauten Befehle für Konsole, Mathematik, Zufall, Text, Typen, Sammlungen, Zeit, Dateien, Bytes, Prozesse und Prüfungen. In Teil IV geht es um das, wofür Drachenhauch gemacht ist: Grafik, Sound und Spiele."),
];
