module.exports = (H) => [
  H.part("Teil IV — Grafik, Sound & Spiele"),
  H.chapter("Das Fenster & der Game-Loop"),
  H.p("Jetzt wird es bunt: In Teil IV verlässt du die Textkonsole und öffnest ein echtes Grafikfenster. Hier zeichnest du Formen und Bilder, spielst Töne ab, fragst Tastatur und Maus ab – kurz: Hier entstehen Spiele. All das übernimmt die Laufzeit gbrt; ein Grafikprogramm läuft also immer im gbrt-Fenster, nicht in der Konsole."),
  H.p("Bevor irgendetwas gezeichnet werden kann, muss ein Fenster geöffnet sein. Und weil ein Spiel sich ständig bewegt, läuft fast jedes Grafikprogramm in einer Schleife, die viele Male pro Sekunde ein neues Bild zeichnet. Dieses Kapitel erklärt beides: das Fenster und diesen Game-Loop."),

  H.h2("Ein Fenster öffnen: SCREEN"),
  H.cmd("SCREEN", "SCREEN(breite, höhe[, titel$[, skala]])",
    "Öffnet das Grafikfenster mit der angegebenen logischen Größe in Pixeln. Optional ein Fenstertitel und eine Skalierung: skala > 1 vergrößert jeden logischen Pixel (für einen Retro-Look). SCREEN muss vor allen anderen Grafikbefehlen stehen.",
    [
      'SCREEN(480, 320, "Mein Spiel")',
      'PRINT SCREENWIDTH(); " x "; SCREENHEIGHT()',
    ], { out: ["480 x 320"] }),

  H.h2("Weitere Wege, ein Fenster zu öffnen"),
  H.cmd("SCREEN_NATIVE", "SCREEN_NATIVE([titel$])",
    "Öffnet ein randloses Fenster, das genau den aktuellen Monitor abdeckt (Borderless-Fullscreen) – die logische Auflösung entspricht der nativen Monitorauflösung. Alternative zu SCREEN, wenn du kein festes Pixelraster willst, sondern die volle Bildschirmfläche.",
    [
      'SCREEN_NATIVE("Mein Vollbild-Spiel")',
      'PRINT SCREENWIDTH() > 0',
    ], { out: ["TRUE"] }),
  H.cmd("SCREEN_TRANSPARENT", "SCREEN_TRANSPARENT(breite, höhe[, titel$[, skala]])",
    "Wie SCREEN, aber das Fenster selbst ist transparent – nur was du zeichnest, ist sichtbar, der Rest des Fensters lässt den Desktop durchscheinen. breite/höhe <= 0 deckt den ganzen aktuellen Monitor als transparentes Overlay ab. MUSS die allererste Grafik-Anweisung sein (Transparenz lässt sich nicht nachträglich einschalten).",
    [
      'SCREEN_TRANSPARENT(400, 300, "Overlay")',
      'CLS(0)              \' mit Alpha 0 = komplett durchsichtig loeschen',
      'CIRCLE(200, 150, 40, RGB(255, 80, 80))',
      'FLIP()',
    ]),
  H.note("SCREEN_NATIVE und SCREEN_TRANSPARENT ersetzen SCREEN – ruf nur einen der drei Fenster-Öffner pro Programm auf, als allererste Grafik-Anweisung."),

  H.h2("Fenster-Eigenschaften steuern"),
  H.p("Ein paar Befehle stellen native Fenster-Eigenschaften des Betriebssystems ein, die über die reine Größe hinausgehen – etwa für Tool-Fenster, Overlays oder Kiosk-Modi."),
  H.cmd("WINDOW_TOPMOST · WINDOW_UNDECORATED", "WINDOW_TOPMOST(an: BOOLEAN)   WINDOW_UNDECORATED(an: BOOLEAN)",
    "WINDOW_TOPMOST hält das Fenster über allen anderen (immer im Vordergrund) – nützlich für ein Overlay-HUD. WINDOW_UNDECORATED entfernt Titelleiste und Rahmen.",
    [
      'SCREEN(320, 240)',
      'WINDOW_TOPMOST(TRUE)',
      'WINDOW_UNDECORATED(TRUE)',
      'CLS() : FLIP()',
      'PRINT "ok"',
    ], { out: ["ok"] }),
  H.cmd("WINDOW_PASSTHROUGH", "WINDOW_PASSTHROUGH(an: BOOLEAN)",
    "Lässt Maus-Klicks durch das Fenster hindurch zum darunterliegenden Fenster – zusammen mit SCREEN_TRANSPARENT + WINDOW_TOPMOST ergibt das ein reines Anzeige-Overlay, das nicht mit der Maus interagiert.",
    [
      'SCREEN(320, 240)',
      'WINDOW_PASSTHROUGH(TRUE)',
      'CLS() : FLIP()',
      'PRINT "ok"',
    ], { out: ["ok"] }),
  H.cmd("WINDOW_ESC_QUIT", "WINDOW_ESC_QUIT(an: BOOLEAN)",
    "Schaltet ein/aus, ob die ESC-Taste automatisch QUITREQUESTED() auslöst (raylib-Standardverhalten). Deaktivieren, wenn dein Spiel ESC selbst belegen will (z. B. Pause-Menü) statt das Fenster zu schließen.",
    [
      'SCREEN(320, 240)',
      'WINDOW_ESC_QUIT(FALSE)   \' ESC schliesst das Fenster NICHT mehr automatisch',
      'CLS() : FLIP()',
      'PRINT "ok"',
    ], { out: ["ok"] }),
  H.cmd("WINDOW_X · WINDOW_Y · SET_WINDOW_POS", "WINDOW_X() AS INTEGER   WINDOW_Y() AS INTEGER   SET_WINDOW_POS(x, y)",
    "WINDOW_X/WINDOW_Y liefern die aktuelle Bildschirmposition der Fenster-Ecke oben links. SET_WINDOW_POS verschiebt das Fenster dorthin.",
    [
      'SCREEN(320, 240)',
      'SET_WINDOW_POS(100, 100)',
      'PRINT WINDOW_X(); " "; WINDOW_Y()',
    ], { out: ["100 100"] }),

  H.h2("Mehrere Monitore"),
  H.p("Auf einem Mehrschirm-Setup willst du vielleicht wissen, wie viele Monitore es gibt und welche Auflösung sie haben – etwa um dein Fenster gezielt auf einem bestimmten Bildschirm zu platzieren."),
  H.cmd("MONITOR_COUNT · CURRENT_MONITOR", "MONITOR_COUNT() AS INTEGER   CURRENT_MONITOR() AS INTEGER",
    "MONITOR_COUNT liefert die Anzahl angeschlossener Monitore. CURRENT_MONITOR liefert den Index (0-basiert) des Monitors, auf dem das Fenster gerade liegt.",
    [
      'SCREEN(320, 240)',
      'PRINT MONITOR_COUNT() >= 1',
      'PRINT CURRENT_MONITOR()',
    ], { out: ["TRUE", "0"] }),
  H.cmd("MONITOR_WIDTH · MONITOR_HEIGHT · MONITOR_NAME · MONITOR_REFRESH", "MONITOR_WIDTH(i) AS INTEGER   MONITOR_HEIGHT(i) AS INTEGER   MONITOR_NAME(i) AS STRING   MONITOR_REFRESH(i) AS INTEGER",
    "Liefern Breite/Höhe in Pixeln, den Anzeigenamen und die Bildwiederholrate (Hz) des Monitors mit Index i (0-basiert, 0 = Hauptmonitor).",
    [
      'SCREEN(320, 240)',
      'PRINT MONITOR_WIDTH(0); " x "; MONITOR_HEIGHT(0)',
      '\' z. B.:  2560 x 1440  (haengt vom Bildschirm ab)',
      'PRINT MONITOR_REFRESH(0)',
      '\' z. B.:  60  (Hz, haengt vom Bildschirm ab)',
    ]),
  H.cmd("MONITOR_X · MONITOR_Y · SET_WINDOW_MONITOR", "MONITOR_X(i) AS INTEGER   MONITOR_Y(i) AS INTEGER   SET_WINDOW_MONITOR(i)",
    "MONITOR_X/MONITOR_Y liefern die Position eines Monitors in der virtuellen Desktop-Fläche. SET_WINDOW_MONITOR verschiebt das Fenster auf den Monitor mit Index i.",
    [
      'SCREEN(320, 240)',
      'SET_WINDOW_MONITOR(0)',
      'PRINT MONITOR_X(0); " "; MONITOR_Y(0)',
    ], { out: ["0 0"] }),

  H.h2("Der Game-Loop"),
  H.p("Ein Spiel zeigt nicht ein einziges Standbild, sondern viele Bilder pro Sekunde – so entsteht Bewegung. Der Game-Loop ist eine Schleife, die immer wieder dasselbe tut: das alte Bild löschen, die Szene neu zeichnen, das fertige Bild anzeigen. Drei Befehle bilden sein Gerüst:"),
  H.bulletRich("CLS([farbe])  ", "löscht das Bild (füllt es mit einer Farbe, Standard Schwarz)."),
  H.bulletRich("… zeichnen …  ", "alle Formen, Bilder und Texte dieses Bildes."),
  H.bulletRich("FLIP()  ", "zeigt das fertige Bild an und wartet kurz (synchronisiert auf 60 Bilder/Sekunde)."),
  H.p("Die Schleife läuft, solange das Fenster offen ist – QUITREQUESTED() wird TRUE, sobald der Benutzer das Fenster schließt. Das ist das Grundgerüst praktisch jedes GameBasic-Spiels:"),
  H.code([
    'SCREEN(480, 320, "Mein erstes Fenster")',
    '',
    'WHILE NOT QUITREQUESTED()',
    '    CLS(RGB(22, 26, 44))                 \' Hintergrund löschen',
    '    TEXT(110, 120, "Mein erstes Fenster", RGB(120, 200, 255))',
    '    BOX(190, 165, 290, 215, RGB(255, 180, 40))',
    '    CIRCLE(240, 250, 18, RGB(90, 220, 140))',
    '    FLIP()                               \' Bild anzeigen',
    'WEND',
  ]),
  H.figure("40_fenster.png", "Das Ergebnis des Game-Loops: ein Fenster mit Text und zwei Formen."),
  H.p("Die einzelnen Zeichenbefehle (TEXT, BOX, CIRCLE …) lernst du im nächsten Kapitel im Detail kennen. Wichtig ist hier das Muster: CLS am Anfang, FLIP am Ende, dazwischen das Zeichnen – Bild für Bild."),

  H.cmd("CLS", "CLS([farbe])",
    "Löscht den Zeichenpuffer, indem es ihn komplett mit einer Farbe füllt (ohne Argument schwarz). Steht üblicherweise als Erstes im Game-Loop, damit das vorige Bild verschwindet.",
    [
      'SCREEN(320, 240)',
      'CLS(RGB(30, 30, 60))     \' dunkelblauer Hintergrund',
      'FLIP()',
    ]),
  H.cmd("FLIP", "FLIP()",
    "Zeigt das fertig gezeichnete Bild im Fenster an und wartet bis zum nächsten Frame (Standard: 60 pro Sekunde). Ohne FLIP bleibt das Gezeichnete unsichtbar.",
    [
      'SCREEN(320, 240)',
      'CLS()',
      'CIRCLE(160, 120, 40, RGB(255, 200, 0))',
      'FLIP()                   \' erst jetzt wird es sichtbar',
    ]),
  H.cmd("QUITREQUESTED", "QUITREQUESTED()",
    "Liefert TRUE, sobald der Benutzer das Fenster schließen will (Schließen-Knopf). Damit beendet sich der Game-Loop sauber.",
    [
      'SCREEN(320, 240)',
      'WHILE NOT QUITREQUESTED()',
      '    CLS()',
      '    FLIP()',
      'WEND',
    ]),

  H.h2("Bewegung mit gleichem Tempo: DELTA"),
  H.p("Nicht jeder Computer schafft gleich viele Bilder pro Sekunde. Würdest du eine Figur bei jedem Bild um feste 5 Pixel bewegen, liefe sie auf einem schnellen Rechner schneller als auf einem langsamen. Die Lösung: DELTA() liefert die Zeit (in Sekunden) seit dem letzten Bild. Multiplizierst du deine Geschwindigkeit damit, ist die Bewegung auf jedem Rechner gleich schnell."),
  H.cmd("DELTA", "DELTA()",
    "Liefert die seit dem letzten FLIP vergangene Zeit in Sekunden (eine kleine Kommazahl). Multipliziere Geschwindigkeiten damit, um framerate-unabhängige Bewegung zu erhalten.",
    [
      'DIM x AS FLOAT',
      'x = 0.0',
      'SCREEN(320, 240)',
      'WHILE NOT QUITREQUESTED()',
      '    x = x + 80.0 * DELTA()    \' 80 Pixel pro Sekunde',
      '    CLS()',
      '    BOX(INT(x), 100, INT(x) + 20, 120, RGB(255, 180, 40))',
      '    FLIP()',
      'WEND',
    ]),

  H.h2("Bildrate steuern"),
  H.cmd("FPS · SETFPS", "FPS()   SETFPS(n)",
    "FPS liefert die aktuell erreichten Bilder pro Sekunde (gut zum Anzeigen). SETFPS legt die Ziel-Bildrate fest; SETFPS(0) hebt die Drosselung auf (so schnell wie möglich).",
    [
      'SCREEN(320, 240)',
      'SETFPS(30)               \' auf 30 Bilder/Sekunde begrenzen',
      'WHILE NOT QUITREQUESTED()',
      '    CLS()',
      '    TEXT(10, 10, "FPS: " + STR$(FPS()))',
      '    FLIP()',
      'WEND',
    ]),
  H.cmd("SCREENWIDTH · SCREENHEIGHT", "SCREENWIDTH()   SCREENHEIGHT()",
    "Liefern die aktuelle Breite und Höhe des Fensters in Pixeln – praktisch, um etwas mittig zu platzieren, ohne feste Zahlen zu verwenden.",
    [
      'SCREEN(480, 320)',
      'DIM mx AS INTEGER',
      'mx = SCREENWIDTH() \\ 2     \' Bildmitte (x)',
      'PRINT mx',
    ], { out: ["240"] }),
  H.h2("Titel, Vollbild, Bildschirmfoto"),
  H.cmd("SETWINDOWTITLE · SET_FULLSCREEN · WINDOW_IS_FULLSCREEN", 'SETWINDOWTITLE(text$)   SET_FULLSCREEN(an)   WINDOW_IS_FULLSCREEN()',
    "Den Fenstertitel kannst du jederzeit ändern (etwa um den Dateinamen oder die Punktzahl anzuzeigen). SET_FULLSCREEN schaltet auf Vollbild um und zurück, WINDOW_IS_FULLSCREEN fragt den Zustand ab.",
    [
      'SETWINDOWTITLE("Mein Spiel - Level 3")',
      'IF KEYHIT(KEY_F11) THEN SET_FULLSCREEN(NOT WINDOW_IS_FULLSCREEN())',
    ]),
  H.cmd("SAVESCREENSHOT", 'SAVESCREENSHOT(datei$)',
    "Speichert den aktuellen Bildschirminhalt als PNG. Ideal für eine Screenshot-Taste im Spiel oder für Belege in einem Fehlerbericht.",
    [
      'IF KEYHIT(KEY_F12) THEN SAVESCREENSHOT("bild.png")',
    ]),
  H.cmd("WINDOW_ICON", 'WINDOW_ICON(bild)',
    "Setzt das Fenstersymbol aus einem per LOADIMAGE geladenen Bild. Ohne das trägt ein exportiertes Spiel das Standardsymbol der Runtime – ein Detail, das den Unterschied zwischen „Bastelei“ und „fertiges Programm“ ausmacht.",
    [
      'DIM icon AS IMAGE',
      'icon = LOADIMAGE("assets/icon.png")',
      'WINDOW_ICON(icon)',
    ]),

  H.h2("Fenstergröße vom Nutzer ändern lassen"),
  H.p("Normalerweise hat ein SCREEN-Fenster eine feste Größe. Du kannst es aber freigeben – dann liefern SCREENWIDTH/SCREENHEIGHT die jeweils aktuelle Größe, und dein Programm muss sein Layout danach richten."),
  H.cmd("WINDOW_RESIZABLE · WINDOW_MIN_SIZE · WINDOW_MAX_SIZE", 'WINDOW_RESIZABLE(an)   WINDOW_MIN_SIZE(w, h)   WINDOW_MAX_SIZE(w, h)',
    "Gibt das Fenster zum Ziehen frei und begrenzt, wie klein oder groß es werden darf.",
    [
      'WINDOW_RESIZABLE(TRUE)',
      'WINDOW_MIN_SIZE(320, 240)',
    ]),
  H.cmd("WINDOW_RESIZED", 'WINDOW_RESIZED()',
    "TRUE in dem Frame, in dem der Nutzer die Größe geändert hat – der richtige Moment, um ein Layout neu zu berechnen, statt das in jedem Frame zu tun.",
    [
      'IF WINDOW_RESIZED() THEN layout_neu_berechnen()',
    ]),
  H.cmd("WINDOW_MAXIMIZE · WINDOW_MINIMIZE · WINDOW_RESTORE", 'WINDOW_MAXIMIZE()   WINDOW_MINIMIZE()   WINDOW_RESTORE()',
    "Steuert den Fensterzustand von Programmseite – maximieren, in die Taskleiste legen, wiederherstellen.",
    [
      'IF KEYHIT(KEY_F10) THEN WINDOW_MAXIMIZE()',
    ]),
  H.cmd("WINDOW_MAXIMIZED · WINDOW_MINIMIZED · WINDOW_HIDDEN", 'WINDOW_MAXIMIZED()   WINDOW_MINIMIZED()   WINDOW_HIDDEN()',
    "Fragen denselben Zustand ab. WINDOW_MINIMIZED ist nützlich, um bei minimiertem Fenster Rechenzeit zu sparen.",
    [
      'IF WINDOW_MINIMIZED() THEN SLEEP(100) : CONTINUE',
    ]),

  H.h2("Fokus, Deckkraft, Bildschirm-Skalierung"),
  H.cmd("WINDOW_FOCUSED · WINDOW_FOCUS", 'WINDOW_FOCUSED()   WINDOW_FOCUS()',
    "WINDOW_FOCUSED sagt, ob dein Fenster gerade im Vordergrund ist – der übliche Weg, ein Spiel automatisch zu pausieren, wenn der Spieler wegklickt. WINDOW_FOCUS holt das Fenster nach vorne.",
    [
      'IF NOT WINDOW_FOCUSED() THEN',
      '    TEXT(200, 150, "PAUSE", RGB(255, 220, 120))',
      '    FLIP()',
      '    CONTINUE',
      'END IF',
    ]),
  H.cmd("WINDOW_OPACITY", 'WINDOW_OPACITY(wert)',
    "Macht das ganze Fenster durchscheinend (1.0 = deckend, 0.0 = unsichtbar) – für Overlays, Einblendungen oder ein sanftes Erscheinen beim Start.",
    [
      'WINDOW_OPACITY(0.85)',
    ]),
  H.cmd("WINDOW_DPI_X · WINDOW_DPI_Y", 'WINDOW_DPI_X()   WINDOW_DPI_Y()',
    "Die Skalierung des Bildschirms: 1.0 ist normal, 2.0 ein HiDPI-/Retina-Display. Ohne diese Werte weiß ein Programm nicht, ob seine Pixelgrößen auf dem Zielgerät winzig herauskommen – etwa um Schrift und Bedienelemente zu vergrößern.",
    [
      'DIM sk AS FLOAT',
      'sk = WINDOW_DPI_X()',
      'TEXT_SIZE(INT(16 * sk))',
    ]),
  H.cmd("GET_TIME", 'GET_TIME()',
    "Sekunden seit Programmstart als Kommazahl, monoton steigend. Anders als TIMER läuft sie unabhängig von der Uhrzeit weiter – gut für Animationen, Zeitmessungen und Abläufe.",
    [
      'DIM t AS FLOAT',
      't = GET_TIME()',
      'y = 100 + SIN(t * 2.0) * 30.0        \' sanftes Schweben',
    ]),

  H.h2("Zwischenablage & Drag-and-Drop"),
  H.cmd("CLIPBOARD_GET · CLIPBOARD_SET", 'CLIPBOARD_GET()   CLIPBOARD_SET(text$)',
    "Lesen und Schreiben der System-Zwischenablage. Damit lässt sich ein Spielstand als Text weitergeben oder ein Level-Code einfügen.",
    [
      'IF KEYPRESSED(KEY_LCTRL) AND KEYHIT(KEY_V) THEN code = CLIPBOARD_GET()',
      'CLIPBOARD_SET("Level-Code: " + code)',
    ]),
  H.cmd("FILES_DROPPED · FILE_DROPPED", 'FILES_DROPPED()   FILE_DROPPED(i)',
    "Zieht der Nutzer Dateien auf das Fenster, liefert FILES_DROPPED in diesem Frame ihre Anzahl und FILE_DROPPED(i) den jeweiligen Pfad – der bequemste Weg, ein Level oder ein Bild zu öffnen.",
    [
      'DIM i AS INTEGER',
      'FOR i = 0 TO FILES_DROPPED() - 1',
      '    PRINT "Geladen: " + FILE_DROPPED(i)',
      'NEXT',
    ]),
  H.cmd("OPENURL", 'OPENURL(adresse$)',
    "Öffnet eine Adresse im Standardbrowser – etwa die Anleitung oder die Seite des Spiels.",
    [
      'IF GUI_CLICKED(hilfe) THEN OPENURL("https://example.org/anleitung")',
    ]),
  H.warn("OPENURL nimmt bewusst keine anderen Schemata an. Die Adresse geht an die System-Shell weiter; ein file:-Schema wäre damit ein Weg, aus einem GameBasic-Programm heraus beliebige Programme zu starten.", "Nur http und https"),

  H.tip("Konsole vs. Fenster", "PRINT und INPUT (Teil III) gehören zur Textkonsole. Sobald SCREEN läuft, gibst du Text mit TEXT ins Fenster und fragst Eingaben mit Tastatur-/Maus-Befehlen ab (Kapitel „Eingabe“). Mische beides nicht im selben Programmteil."),
];
