module.exports = (H) => [
  H.part("Teil IV — Grafik, Sound & Spiele"),
  H.chapter("Das Fenster & der Game-Loop"),
  H.p("Jetzt wird es bunt: In Teil IV verlässt du die Textkonsole und öffnest ein echtes Grafikfenster. Hier zeichnest du Formen und Bilder, spielst Töne ab, fragst Tastatur und Maus ab – kurz: Hier entstehen Spiele. All das übernimmt die Laufzeit gbrt; ein Grafikprogramm läuft also immer im gbrt-Fenster, nicht in der Konsole."),
  H.p("Bevor irgendetwas gezeichnet werden kann, muss ein Fenster geöffnet sein. Und weil ein Spiel sich ständig bewegt, läuft fast jedes Grafikprogramm in einer Schleife, die viele Male pro Sekunde ein neues Bild zeichnet. Dieses Kapitel erklärt beides: das Fenster und diesen Game-Loop."),

  H.h2("Ein Fenster öffnen: SCREEN"),
  H.cmd("SCREEN", "SCREEN(breite, höhe[, titel$[, skala]])",
    "Öffnet das Grafikfenster mit der angegebenen logischen Größe in Pixeln. Optional ein Fenstertitel und eine Skalierung: skala > 1 vergrößert jeden logischen Pixel (für einen Retro-Look). SCREEN muss vor allen anderen Grafikbefehlen stehen.",
    [
      'SCREEN(480, 320, "Mein Spiel")',
      'PRINT SCREENWIDTH(); " x "; SCREENHEIGHT()',
    ], { out: ["480 x 320"] }),

  H.h2("Weitere Wege, ein Fenster zu öffnen"),
  H.cmd("SCREEN_NATIVE", "SCREEN_NATIVE([titel$])",
    "Öffnet ein randloses Fenster, das genau den aktuellen Monitor abdeckt (Borderless-Fullscreen) – die logische Auflösung entspricht der nativen Monitorauflösung. Alternative zu SCREEN, wenn du kein festes Pixelraster willst, sondern die volle Bildschirmfläche.",
    [
      'SCREEN_NATIVE("Mein Vollbild-Spiel")',
      'PRINT SCREENWIDTH() > 0',
    ], { out: ["TRUE"] }),
  H.cmd("SCREEN_TRANSPARENT", "SCREEN_TRANSPARENT(breite, höhe[, titel$[, skala]])",
    "Wie SCREEN, aber das Fenster selbst ist transparent – nur was du zeichnest, ist sichtbar, der Rest des Fensters lässt den Desktop durchscheinen. breite/höhe <= 0 deckt den ganzen aktuellen Monitor als transparentes Overlay ab. MUSS die allererste Grafik-Anweisung sein (Transparenz lässt sich nicht nachträglich einschalten).",
    [
      'SCREEN_TRANSPARENT(400, 300, "Overlay")',
      'CLS(0)              \' mit Alpha 0 = komplett durchsichtig loeschen',
      'CIRCLE(200, 150, 40, RGB(255, 80, 80))',
      'FLIP()',
    ]),
  H.note("SCREEN_NATIVE und SCREEN_TRANSPARENT ersetzen SCREEN – ruf nur einen der drei Fenster-Öffner pro Programm auf, als allererste Grafik-Anweisung."),

  H.h2("Fenster-Eigenschaften steuern"),
  H.p("Ein paar Befehle stellen native Fenster-Eigenschaften des Betriebssystems ein, die über die reine Größe hinausgehen – etwa für Tool-Fenster, Overlays oder Kiosk-Modi."),
  H.cmd("WINDOW_TOPMOST · WINDOW_UNDECORATED", "WINDOW_TOPMOST(an: BOOLEAN)   WINDOW_UNDECORATED(an: BOOLEAN)",
    "WINDOW_TOPMOST hält das Fenster über allen anderen (immer im Vordergrund) – nützlich für ein Overlay-HUD. WINDOW_UNDECORATED entfernt Titelleiste und Rahmen.",
    [
      'SCREEN(320, 240)',
      'WINDOW_TOPMOST(TRUE)',
      'WINDOW_UNDECORATED(TRUE)',
      'CLS() : FLIP()',
      'PRINT "ok"',
    ], { out: ["ok"] }),
  H.cmd("WINDOW_PASSTHROUGH", "WINDOW_PASSTHROUGH(an: BOOLEAN)",
    "Lässt Maus-Klicks durch das Fenster hindurch zum darunterliegenden Fenster – zusammen mit SCREEN_TRANSPARENT + WINDOW_TOPMOST ergibt das ein reines Anzeige-Overlay, das nicht mit der Maus interagiert.",
    [
      'SCREEN(320, 240)',
      'WINDOW_PASSTHROUGH(TRUE)',
      'CLS() : FLIP()',
      'PRINT "ok"',
    ], { out: ["ok"] }),
  H.cmd("WINDOW_ESC_QUIT", "WINDOW_ESC_QUIT(an: BOOLEAN)",
    "Schaltet ein/aus, ob die ESC-Taste automatisch QUITREQUESTED() auslöst (raylib-Standardverhalten). Deaktivieren, wenn dein Spiel ESC selbst belegen will (z. B. Pause-Menü) statt das Fenster zu schließen.",
    [
      'SCREEN(320, 240)',
      'WINDOW_ESC_QUIT(FALSE)   \' ESC schliesst das Fenster NICHT mehr automatisch',
      'CLS() : FLIP()',
      'PRINT "ok"',
    ], { out: ["ok"] }),
  H.cmd("WINDOW_X · WINDOW_Y · SET_WINDOW_POS", "WINDOW_X() AS INTEGER   WINDOW_Y() AS INTEGER   SET_WINDOW_POS(x, y)",
    "WINDOW_X/WINDOW_Y liefern die aktuelle Bildschirmposition der Fenster-Ecke oben links. SET_WINDOW_POS verschiebt das Fenster dorthin.",
    [
      'SCREEN(320, 240)',
      'SET_WINDOW_POS(100, 100)',
      'PRINT WINDOW_X(); " "; WINDOW_Y()',
    ], { out: ["100 100"] }),

  H.h2("Mehrere Monitore"),
  H.p("Auf einem Mehrschirm-Setup willst du vielleicht wissen, wie viele Monitore es gibt und welche Auflösung sie haben – etwa um dein Fenster gezielt auf einem bestimmten Bildschirm zu platzieren."),
  H.cmd("MONITOR_COUNT · CURRENT_MONITOR", "MONITOR_COUNT() AS INTEGER   CURRENT_MONITOR() AS INTEGER",
    "MONITOR_COUNT liefert die Anzahl angeschlossener Monitore. CURRENT_MONITOR liefert den Index (0-basiert) des Monitors, auf dem das Fenster gerade liegt.",
    [
      'SCREEN(320, 240)',
      'PRINT MONITOR_COUNT() >= 1',
      'PRINT CURRENT_MONITOR()',
    ], { out: ["TRUE", "0"] }),
  H.cmd("MONITOR_WIDTH · MONITOR_HEIGHT · MONITOR_NAME · MONITOR_REFRESH", "MONITOR_WIDTH(i) AS INTEGER   MONITOR_HEIGHT(i) AS INTEGER   MONITOR_NAME(i) AS STRING   MONITOR_REFRESH(i) AS INTEGER",
    "Liefern Breite/Höhe in Pixeln, den Anzeigenamen und die Bildwiederholrate (Hz) des Monitors mit Index i (0-basiert, 0 = Hauptmonitor).",
    [
      'SCREEN(320, 240)',
      'PRINT MONITOR_WIDTH(0); " x "; MONITOR_HEIGHT(0)',
      '\' z. B.:  2560 x 1440  (haengt vom Bildschirm ab)',
      'PRINT MONITOR_REFRESH(0)',
      '\' z. B.:  60  (Hz, haengt vom Bildschirm ab)',
    ]),
  H.cmd("MONITOR_X · MONITOR_Y · SET_WINDOW_MONITOR", "MONITOR_X(i) AS INTEGER   MONITOR_Y(i) AS INTEGER   SET_WINDOW_MONITOR(i)",
    "MONITOR_X/MONITOR_Y liefern die Position eines Monitors in der virtuellen Desktop-Fläche. SET_WINDOW_MONITOR verschiebt das Fenster auf den Monitor mit Index i.",
    [
      'SCREEN(320, 240)',
      'SET_WINDOW_MONITOR(0)',
      'PRINT MONITOR_X(0); " "; MONITOR_Y(0)',
    ], { out: ["0 0"] }),

  H.h2("Der Game-Loop"),
  H.p("Ein Spiel zeigt nicht ein einziges Standbild, sondern viele Bilder pro Sekunde – so entsteht Bewegung. Der Game-Loop ist eine Schleife, die immer wieder dasselbe tut: das alte Bild löschen, die Szene neu zeichnen, das fertige Bild anzeigen. Drei Befehle bilden sein Gerüst:"),
  H.bulletRich("CLS([farbe])  ", "löscht das Bild (füllt es mit einer Farbe, Standard Schwarz)."),
  H.bulletRich("… zeichnen …  ", "alle Formen, Bilder und Texte dieses Bildes."),
  H.bulletRich("FLIP()  ", "zeigt das fertige Bild an und wartet kurz (synchronisiert auf 60 Bilder/Sekunde)."),
  H.p("Die Schleife läuft, solange das Fenster offen ist – QUITREQUESTED() wird TRUE, sobald der Benutzer das Fenster schließt. Das ist das Grundgerüst praktisch jedes GameBasic-Spiels:"),
  H.code([
    'SCREEN(480, 320, "Mein erstes Fenster")',
    '',
    'WHILE NOT QUITREQUESTED()',
    '    CLS(RGB(22, 26, 44))                 \' Hintergrund löschen',
    '    TEXT(110, 120, "Mein erstes Fenster", RGB(120, 200, 255))',
    '    BOX(190, 165, 290, 215, RGB(255, 180, 40))',
    '    CIRCLE(240, 250, 18, RGB(90, 220, 140))',
    '    FLIP()                               \' Bild anzeigen',
    'WEND',
  ]),
  H.figure("40_fenster.png", "Das Ergebnis des Game-Loops: ein Fenster mit Text und zwei Formen."),
  H.p("Die einzelnen Zeichenbefehle (TEXT, BOX, CIRCLE …) lernst du im nächsten Kapitel im Detail kennen. Wichtig ist hier das Muster: CLS am Anfang, FLIP am Ende, dazwischen das Zeichnen – Bild für Bild."),

  H.cmd("CLS", "CLS([farbe])",
    "Löscht den Zeichenpuffer, indem es ihn komplett mit einer Farbe füllt (ohne Argument schwarz). Steht üblicherweise als Erstes im Game-Loop, damit das vorige Bild verschwindet.",
    [
      'SCREEN(320, 240)',
      'CLS(RGB(30, 30, 60))     \' dunkelblauer Hintergrund',
      'FLIP()',
    ]),
  H.cmd("FLIP", "FLIP()",
    "Zeigt das fertig gezeichnete Bild im Fenster an und wartet bis zum nächsten Frame (Standard: 60 pro Sekunde). Ohne FLIP bleibt das Gezeichnete unsichtbar.",
    [
      'SCREEN(320, 240)',
      'CLS()',
      'CIRCLE(160, 120, 40, RGB(255, 200, 0))',
      'FLIP()                   \' erst jetzt wird es sichtbar',
    ]),
  H.cmd("QUITREQUESTED", "QUITREQUESTED()",
    "Liefert TRUE, sobald der Benutzer das Fenster schließen will (Schließen-Knopf). Damit beendet sich der Game-Loop sauber.",
    [
      'SCREEN(320, 240)',
      'WHILE NOT QUITREQUESTED()',
      '    CLS()',
      '    FLIP()',
      'WEND',
    ]),

  H.h2("Bewegung mit gleichem Tempo: DELTA"),
  H.p("Nicht jeder Computer schafft gleich viele Bilder pro Sekunde. Würdest du eine Figur bei jedem Bild um feste 5 Pixel bewegen, liefe sie auf einem schnellen Rechner schneller als auf einem langsamen. Die Lösung: DELTA() liefert die Zeit (in Sekunden) seit dem letzten Bild. Multiplizierst du deine Geschwindigkeit damit, ist die Bewegung auf jedem Rechner gleich schnell."),
  H.cmd("DELTA", "DELTA()",
    "Liefert die seit dem letzten FLIP vergangene Zeit in Sekunden (eine kleine Kommazahl). Multipliziere Geschwindigkeiten damit, um framerate-unabhängige Bewegung zu erhalten.",
    [
      'DIM x AS FLOAT',
      'x = 0.0',
      'SCREEN(320, 240)',
      'WHILE NOT QUITREQUESTED()',
      '    x = x + 80.0 * DELTA()    \' 80 Pixel pro Sekunde',
      '    CLS()',
      '    BOX(INT(x), 100, INT(x) + 20, 120, RGB(255, 180, 40))',
      '    FLIP()',
      'WEND',
    ]),

  H.h2("Bildrate steuern"),
  H.cmd("FPS · SETFPS", "FPS()   SETFPS(n)",
    "FPS liefert die aktuell erreichten Bilder pro Sekunde (gut zum Anzeigen). SETFPS legt die Ziel-Bildrate fest; SETFPS(0) hebt die Drosselung auf (so schnell wie möglich).",
    [
      'SCREEN(320, 240)',
      'SETFPS(30)               \' auf 30 Bilder/Sekunde begrenzen',
      'WHILE NOT QUITREQUESTED()',
      '    CLS()',
      '    TEXT(10, 10, "FPS: " + STR$(FPS()))',
      '    FLIP()',
      'WEND',
    ]),
  H.cmd("SCREENWIDTH · SCREENHEIGHT", "SCREENWIDTH()   SCREENHEIGHT()",
    "Liefern die aktuelle Breite und Höhe des Fensters in Pixeln – praktisch, um etwas mittig zu platzieren, ohne feste Zahlen zu verwenden.",
    [
      'SCREEN(480, 320)',
      'DIM mx AS INTEGER',
      'mx = SCREENWIDTH() \\ 2     \' Bildmitte (x)',
      'PRINT mx',
    ], { out: ["240"] }),
  H.tip("Konsole vs. Fenster", "PRINT und INPUT (Teil III) gehören zur Textkonsole. Sobald SCREEN läuft, gibst du Text mit TEXT ins Fenster und fragst Eingaben mit Tastatur-/Maus-Befehlen ab (Kapitel „Eingabe“). Mische beides nicht im selben Programmteil."),
];
