module.exports = (H) => [
  H.part("Teil IV — Grafik, Sound & Spiele"),
  H.chapter("Das Fenster & der Game-Loop"),
  H.p("Jetzt wird es bunt: In Teil IV verlässt du die Textkonsole und öffnest ein echtes Grafikfenster. Hier zeichnest du Formen und Bilder, spielst Töne ab, fragst Tastatur und Maus ab – kurz: Hier entstehen Spiele. All das übernimmt die Laufzeit gbrt; ein Grafikprogramm läuft also immer im gbrt-Fenster, nicht in der Konsole."),
  H.p("Bevor irgendetwas gezeichnet werden kann, muss ein Fenster geöffnet sein. Und weil ein Spiel sich ständig bewegt, läuft fast jedes Grafikprogramm in einer Schleife, die viele Male pro Sekunde ein neues Bild zeichnet. Dieses Kapitel erklärt beides: das Fenster und diesen Game-Loop."),

  H.h2("Ein Fenster öffnen: SCREEN"),
  H.cmd("SCREEN", "SCREEN(breite, höhe[, titel$[, skala]])",
    "Öffnet das Grafikfenster mit der angegebenen logischen Größe in Pixeln. Optional ein Fenstertitel und eine Skalierung: skala > 1 vergrößert jeden logischen Pixel (für einen Retro-Look). SCREEN muss vor allen anderen Grafikbefehlen stehen.",
    [
      'SCREEN(480, 320, "Mein Spiel")',
      'PRINT SCREENWIDTH(); " x "; SCREENHEIGHT()',
    ], { out: ["480 x 320"] }),

  H.h2("Der Game-Loop"),
  H.p("Ein Spiel zeigt nicht ein einziges Standbild, sondern viele Bilder pro Sekunde – so entsteht Bewegung. Der Game-Loop ist eine Schleife, die immer wieder dasselbe tut: das alte Bild löschen, die Szene neu zeichnen, das fertige Bild anzeigen. Drei Befehle bilden sein Gerüst:"),
  H.bulletRich("CLS([farbe])  ", "löscht das Bild (füllt es mit einer Farbe, Standard Schwarz)."),
  H.bulletRich("… zeichnen …  ", "alle Formen, Bilder und Texte dieses Bildes."),
  H.bulletRich("FLIP()  ", "zeigt das fertige Bild an und wartet kurz (synchronisiert auf 60 Bilder/Sekunde)."),
  H.p("Die Schleife läuft, solange das Fenster offen ist – QUITREQUESTED() wird TRUE, sobald der Benutzer das Fenster schließt. Das ist das Grundgerüst praktisch jedes GameBasic-Spiels:"),
  H.code([
    'SCREEN(480, 320, "Mein erstes Fenster")',
    '',
    'WHILE NOT QUITREQUESTED()',
    '    CLS(RGB(22, 26, 44))                 \' Hintergrund löschen',
    '    TEXT(110, 120, "Mein erstes Fenster", RGB(120, 200, 255))',
    '    BOX(190, 165, 290, 215, RGB(255, 180, 40))',
    '    CIRCLE(240, 250, 18, RGB(90, 220, 140))',
    '    FLIP()                               \' Bild anzeigen',
    'WEND',
  ]),
  H.figure("40_fenster.png", "Das Ergebnis des Game-Loops: ein Fenster mit Text und zwei Formen."),
  H.p("Die einzelnen Zeichenbefehle (TEXT, BOX, CIRCLE …) lernst du im nächsten Kapitel im Detail kennen. Wichtig ist hier das Muster: CLS am Anfang, FLIP am Ende, dazwischen das Zeichnen – Bild für Bild."),

  H.cmd("CLS", "CLS([farbe])",
    "Löscht den Zeichenpuffer, indem es ihn komplett mit einer Farbe füllt (ohne Argument schwarz). Steht üblicherweise als Erstes im Game-Loop, damit das vorige Bild verschwindet.",
    [
      'SCREEN(320, 240)',
      'CLS(RGB(30, 30, 60))     \' dunkelblauer Hintergrund',
      'FLIP()',
    ]),
  H.cmd("FLIP", "FLIP()",
    "Zeigt das fertig gezeichnete Bild im Fenster an und wartet bis zum nächsten Frame (Standard: 60 pro Sekunde). Ohne FLIP bleibt das Gezeichnete unsichtbar.",
    [
      'SCREEN(320, 240)',
      'CLS()',
      'CIRCLE(160, 120, 40, RGB(255, 200, 0))',
      'FLIP()                   \' erst jetzt wird es sichtbar',
    ]),
  H.cmd("QUITREQUESTED", "QUITREQUESTED()",
    "Liefert TRUE, sobald der Benutzer das Fenster schließen will (Schließen-Knopf). Damit beendet sich der Game-Loop sauber.",
    [
      'SCREEN(320, 240)',
      'WHILE NOT QUITREQUESTED()',
      '    CLS()',
      '    FLIP()',
      'WEND',
    ]),

  H.h2("Bewegung mit gleichem Tempo: DELTA"),
  H.p("Nicht jeder Computer schafft gleich viele Bilder pro Sekunde. Würdest du eine Figur bei jedem Bild um feste 5 Pixel bewegen, liefe sie auf einem schnellen Rechner schneller als auf einem langsamen. Die Lösung: DELTA() liefert die Zeit (in Sekunden) seit dem letzten Bild. Multiplizierst du deine Geschwindigkeit damit, ist die Bewegung auf jedem Rechner gleich schnell."),
  H.cmd("DELTA", "DELTA()",
    "Liefert die seit dem letzten FLIP vergangene Zeit in Sekunden (eine kleine Kommazahl). Multipliziere Geschwindigkeiten damit, um framerate-unabhängige Bewegung zu erhalten.",
    [
      'DIM x AS FLOAT',
      'x = 0.0',
      'SCREEN(320, 240)',
      'WHILE NOT QUITREQUESTED()',
      '    x = x + 80.0 * DELTA()    \' 80 Pixel pro Sekunde',
      '    CLS()',
      '    BOX(INT(x), 100, INT(x) + 20, 120, RGB(255, 180, 40))',
      '    FLIP()',
      'WEND',
    ]),

  H.h2("Bildrate steuern"),
  H.cmd("FPS · SETFPS", "FPS()   SETFPS(n)",
    "FPS liefert die aktuell erreichten Bilder pro Sekunde (gut zum Anzeigen). SETFPS legt die Ziel-Bildrate fest; SETFPS(0) hebt die Drosselung auf (so schnell wie möglich).",
    [
      'SCREEN(320, 240)',
      'SETFPS(30)               \' auf 30 Bilder/Sekunde begrenzen',
      'WHILE NOT QUITREQUESTED()',
      '    CLS()',
      '    TEXT(10, 10, "FPS: " + STR$(FPS()))',
      '    FLIP()',
      'WEND',
    ]),
  H.cmd("SCREENWIDTH · SCREENHEIGHT", "SCREENWIDTH()   SCREENHEIGHT()",
    "Liefern die aktuelle Breite und Höhe des Fensters in Pixeln – praktisch, um etwas mittig zu platzieren, ohne feste Zahlen zu verwenden.",
    [
      'SCREEN(480, 320)',
      'DIM mx AS INTEGER',
      'mx = SCREENWIDTH() \\ 2     \' Bildmitte (x)',
      'PRINT mx',
    ], { out: ["240"] }),
  H.tip("Konsole vs. Fenster", "PRINT und INPUT (Teil III) gehören zur Textkonsole. Sobald SCREEN läuft, gibst du Text mit TEXT ins Fenster und fragst Eingaben mit Tastatur-/Maus-Befehlen ab (Kapitel „Eingabe“). Mische beides nicht im selben Programmteil."),
];
