module.exports = (H) => [
  H.chapter("2D-Zeichnen"),
  H.p("Mit dem Fenster aus dem letzten Kapitel kannst du jetzt zeichnen. Drachenhauch bietet alle Grundformen: Pixel, Linien, Rechtecke, Kreise, Dreiecke, Polygone, Ellipsen, Bögen und Text. Jeder Befehl wird zwischen CLS und FLIP aufgerufen (siehe Game-Loop). Das letzte Argument ist fast immer eine Farbe – als RGB(r, g, b) oder eine der Farbkonstanten (Kapitel „Farben“)."),
  H.p("Das folgende Bild zeigt die wichtigsten Formen auf einen Blick; danach kommt jeder Befehl einzeln mit Beispiel."),
  H.figure("41_formen.png", "Die 2D-Grundformen: Linie, gefülltes und umrandetes Rechteck, Kreis, Dreieck, Ellipse, Polygon, Bogen und Text."),

  H.note("Koordinaten zählen ab der linken oberen Ecke: x nach rechts, y nach UNTEN. (0, 0) ist also oben links. Bei BOX und RECT gibst du zwei Eckpunkte (x1, y1, x2, y2) an – beide eingeschlossen."),

  H.h2("Pixel & Linien"),
  H.cmd("PLOT", "PLOT(x, y[, farbe])",
    "Setzt ein einzelnes Pixel.",
    [
      'SCREEN(320, 240)',
      'CLS()',
      'PLOT(160, 120, RGB(255, 255, 255))',
      'FLIP()',
    ]),
  H.cmd("LINE", "LINE(x1, y1, x2, y2[, farbe])",
    "Zieht eine Linie von (x1, y1) nach (x2, y2).",
    [
      'CLS()',
      'LINE(0, 0, 319, 239, RGB(255, 80, 80))',
      'FLIP()',
    ]),

  H.h2("Rechtecke"),
  H.cmd("BOX", "BOX(x1, y1, x2, y2[, farbe])",
    "Zeichnet ein GEFÜLLTES Rechteck zwischen den beiden Eckpunkten.",
    [
      'CLS()',
      'BOX(50, 50, 150, 100, RGB(0, 200, 120))',
      'FLIP()',
    ]),
  H.cmd("RECT", "RECT(x1, y1, x2, y2[, farbe])",
    "Zeichnet nur den RAHMEN eines Rechtecks (1 Pixel breit).",
    [
      'CLS()',
      'RECT(50, 50, 150, 100, RGB(0, 200, 120))',
      'FLIP()',
    ]),

  H.h2("Kreise & Ellipsen"),
  H.cmd("CIRCLE", "CIRCLE(x, y, radius[, farbe])",
    "Zeichnet einen gefüllten Kreis mit Mittelpunkt (x, y) und dem angegebenen Radius.",
    [
      'CLS()',
      'CIRCLE(160, 120, 40, RGB(255, 200, 40))',
      'FLIP()',
    ]),
  H.cmd("CIRCLEOUTLINE", "CIRCLEOUTLINE(x, y, radius[, farbe])",
    "Wie CIRCLE, zeichnet aber nur die Kontur (1 Pixel breit) statt eine gefüllte Fläche.",
    [
      'CLS()',
      'CIRCLEOUTLINE(160, 120, 40, RGB(255, 200, 40))',
      'FLIP()',
    ]),
  H.cmd("ELLIPSE · ELLIPSEOUTLINE", "ELLIPSE(x1, y1, x2, y2[, farbe])   ELLIPSEOUTLINE(...)",
    "Zeichnet eine Ellipse, eingepasst in das Rechteck (x1, y1)–(x2, y2). ELLIPSE füllt, ELLIPSEOUTLINE zeichnet nur die Kontur (mit optionaler Breite).",
    [
      'CLS()',
      'ELLIPSE(60, 80, 200, 160, RGB(80, 140, 255))',
      'ELLIPSEOUTLINE(220, 80, 300, 160, RGB(80, 140, 255), 2)',
      'FLIP()',
    ]),

  H.h2("Dreiecke & Polygone"),
  H.cmd("TRIANGLE · TRIANGLEOUTLINE", "TRIANGLE(x1,y1, x2,y2, x3,y3[, farbe])   TRIANGLEOUTLINE(...)",
    "Zeichnet ein Dreieck aus drei Eckpunkten – TRIANGLE gefüllt, TRIANGLEOUTLINE nur als Kontur.",
    [
      'CLS()',
      'TRIANGLE(160, 80, 120, 160, 200, 160, RGB(255, 110, 255))',
      'FLIP()',
    ]),
  H.cmd("POLYGON · POLYGONOUTLINE", "POLYGON(punkte[, farbe])   POLYGONOUTLINE(...)",
    "Zeichnet ein Vieleck. punkte ist ein ARRAY OF INTEGER mit abwechselnd x- und y-Werten ([x1, y1, x2, y2, …], mindestens 3 Punkte). POLYGON füllt, POLYGONOUTLINE zeichnet nur die Kanten.",
    [
      'DIM p[8] AS INTEGER          \' 4 Punkte (Raute)',
      'p[0]=160 : p[1]=60',
      'p[2]=120 : p[3]=120',
      'p[4]=160 : p[5]=180',
      'p[6]=200 : p[7]=120',
      'CLS()',
      'POLYGON(p, RGB(0, 210, 210))',
      'FLIP()',
    ]),
  H.note("Die Reihenfolge der Eckpunkte spielt bei gefüllten Dreiecken und Polygonen keine Rolle – ob im oder gegen den Uhrzeigersinn, die Fläche wird immer gefüllt."),

  H.h2("Bögen"),
  H.cmd("ARC", "ARC(x1, y1, x2, y2, start, ende[, farbe[, breite]])",
    "Zeichnet ein Bogensegment, eingepasst in das Rechteck (x1, y1)–(x2, y2). Die Winkel start und ende sind im Bogenmaß (0 bis 2·PI), gegen den Uhrzeigersinn.",
    [
      'CLS()',
      'ARC(120, 80, 200, 160, 0.0, PI, RGB(255, 255, 0), 3)',
      'FLIP()',
    ]),

  H.h2("Text"),
  H.cmd("TEXT", "TEXT(x, y, text$[, farbe])",
    "Schreibt Text an die Position (x, y) (linke obere Ecke des Textes). In der Konsole nutzt du PRINT, im Fenster TEXT.",
    [
      'CLS()',
      'TEXT(20, 20, "Punkte: 1200", RGB(255, 255, 255))',
      'FLIP()',
    ]),
  H.cmd("TEXTROT", "TEXTROT(x, y, text$, winkel[, skala[, farbe]])",
    "Schreibt Text ZENTRIERT auf (x, y), um diesen Punkt gedreht (Winkel in Grad) und optional skaliert – gut für schräge Beschriftungen oder Punkte-Pop-ups.",
    [
      'CLS()',
      'TEXTROT(160, 120, "+100", -20.0, 2.0, RGB(255, 220, 0))',
      'FLIP()',
    ]),

  H.h2("Schriften"),
  H.p("Standardmäßig zeichnet TEXT in einer eingebauten Schrift. Für Überschriften, ein Menü oder einen eigenen Stil lädst du eine TrueType-Datei – oder eine Pixelschrift aus einem PNG."),
  H.cmd("LOADFONT · SETFONT · TEXT_SIZE", 'LOADFONT(pfad$, groesse [, zeichen$])   SETFONT(font)   TEXT_SIZE(px)',
    "LOADFONT lädt eine .ttf-, .otf- oder .ttc-Datei in einer bestimmten Größe und liefert ein Handle; SETFONT macht sie zur aktiven Schrift (-1 schaltet zurück auf die eingebaute). TEXT_SIZE ändert die Zeichengröße für die folgenden TEXT-Aufrufe. Gebacken werden ASCII, Latin-1 und Latin Extended, Griechisch, Kyrillisch, Interpunktion und das Euro-Zeichen; mit zeichen$ wählt man mehr – Blocknamen wie \"japanisch\", \"kyrillisch, griechisch\", \"emoji\" oder die Zeichen selbst. Fehlt einer Schrift ein Zeichen, springt für dieses Zeichen eine Systemschrift ein (Kanji, Hangul, Emoji werden auf Zuruf nachgeladen).",
    [
      'DIM titel AS INTEGER',
      'titel = LOADFONT("assets/fonts/pixel.ttf", 32)',
      'SETFONT(titel)',
      'TEXT(20, 20, "GAME OVER", RGB(255, 80, 80))',
      'SETFONT(-1)                    \' zurueck zur Standardschrift',
    ]),
  H.note("Backe die Schrift in der Größe, in der du sie brauchst: LOADFONT rastert sie einmal, größer skalierter Text wird unscharf. Für zwei Größen also zwei LOADFONT-Aufrufe."),
  H.cmd("LOADFONT_IMAGE", 'LOADFONT_IMAGE(bild, trennfarbe, erstes_zeichen)',
    "Lädt eine Pixelschrift aus einem PNG, in dem die Zeichen durch eine Trennfarbe voneinander abgesetzt sind. erstes_zeichen ist der Code des ersten Zeichens im Bild (meist 32 für das Leerzeichen). Anders als TrueType-Schriften bleibt diese Schrift ungefiltert – Pixelschrift bleibt also pixelig.",
    [
      'DIM bild AS IMAGE',
      'bild = LOADIMAGE("assets/font8x8.png")',
      'DIM pix AS INTEGER',
      'pix = LOADFONT_IMAGE(bild, RGB(255, 0, 255), 32)',
      'SETFONT(pix)',
    ]),
  H.cmd("TEXT_WIDTH · TEXT_HEIGHT", 'TEXT_WIDTH(text$)   TEXT_HEIGHT()',
    "Wie breit wird dieser Text, und wie hoch ist eine Zeile – in der aktuellen Schrift und Größe. Damit zentrierst du Text sauber oder zeichnest einen passenden Kasten dahinter.",
    [
      'DIM s AS STRING',
      's = "Weiter mit LEERTASTE"',
      'TEXT((SCREENWIDTH() - TEXT_WIDTH(s)) \\ 2, 200, s)   \' zentriert',
    ]),
  H.cmd("TEXT_SPACING · TEXT_LINE_SPACING", 'TEXT_SPACING(px)   TEXT_LINE_SPACING(px)',
    "TEXT_SPACING ändert den Abstand zwischen den Zeichen (Sperrung), TEXT_LINE_SPACING den Zeilenabstand bei mehrzeiligem Text.",
    [
      'TEXT_SPACING(2.0)              \' luftige Ueberschrift',
      'TEXT_LINE_SPACING(24)',
    ]),
  H.cmd("TEXT_BOLD · TEXT_ITALIC", 'TEXT_BOLD(an)   TEXT_ITALIC(an)',
    "Schalten Fett und Kursiv für die folgenden TEXT-Aufrufe ein oder aus. Beides wird künstlich erzeugt (mehrfach versetzt bzw. geschert) – eine eigens geladene Fett-Schrift sieht besser aus, aber für ein Hervorheben im Spiel reicht es.",
    [
      'TEXT_BOLD(TRUE)',
      'TEXT(20, 60, "WARNUNG", RGB(255, 200, 60))',
      'TEXT_BOLD(FALSE)',
    ]),
];
