module.exports = (H) => [
  H.chapter("2D-Extras"),
  H.p("Über die Grundformen hinaus bietet Drachenhauch einige hübsche Extras: dicke Linien, runde Rechtecke, Farbverläufe, weiche Kurven, Mischmodi für Leucht-Effekte, fertig erzeugte Texturen und Zwischen-Zeichenflächen. Alle werden – wie das ganze Kapitel – im Grafikfenster zwischen CLS und FLIP benutzt."),
  H.figure("42_extras.png", "Farbverläufe, ein rundes Rechteck, dicke Linien und eine weiche Spline-Kurve."),

  H.h2("Dicke Linien & runde Rechtecke"),
  H.cmd("LINEW", "LINEW(x1, y1, x2, y2, breite[, farbe])",
    "Wie LINE, aber mit einstellbarer Strichbreite in Pixeln.",
    [
      'CLS()',
      'LINEW(40, 60, 280, 60, 6, RGB(255, 204, 0))',
      'FLIP()',
    ]),
  H.cmd("BOXROUND · RECTROUND", "BOXROUND(x1, y1, x2, y2, radius[, farbe])   RECTROUND(...)",
    "Zeichnen ein Rechteck mit abgerundeten Ecken (Eckradius in Pixeln). BOXROUND füllt, RECTROUND zeichnet nur den Rahmen.",
    [
      'CLS()',
      'BOXROUND(40, 40, 200, 120, 20, RGB(48, 208, 128))',
      'RECTROUND(40, 40, 200, 120, 20, RGB(255, 255, 255))',
      'FLIP()',
    ]),

  H.h2("Farbverläufe"),
  H.cmd("GRADIENTV · GRADIENTH", "GRADIENTV(x1, y1, x2, y2, farbe1, farbe2)   GRADIENTH(...)",
    "Füllen ein Rechteck mit einem weichen Farbverlauf von farbe1 nach farbe2 – GRADIENTV senkrecht (oben→unten), GRADIENTH waagerecht (links→rechts). Gut für Himmel, Hintergründe oder Knöpfe.",
    [
      'CLS()',
      'GRADIENTV(0, 0, 320, 240, RGB(20, 30, 60), RGB(60, 20, 40))',
      'FLIP()',
    ]),

  H.h2("Weiche Kurven"),
  H.cmd("SPLINE", "SPLINE(xs, ys[, farbe[, breite]])",
    "Zeichnet eine weiche Kurve, die durch alle angegebenen Stützpunkte läuft. xs und ys sind zwei gleich lange Arrays mit den x- und y-Koordinaten der Punkte.",
    [
      'DIM xs[4] AS INTEGER',
      'DIM ys[4] AS INTEGER',
      'xs[0]=20  : ys[0]=200',
      'xs[1]=110 : ys[1]=120',
      'xs[2]=210 : ys[2]=200',
      'xs[3]=300 : ys[3]=120',
      'CLS()',
      'SPLINE(xs, ys, RGB(0, 255, 208), 3.0)',
      'FLIP()',
    ]),

  H.h2("Mischmodi für Leucht-Effekte"),
  H.p("Normalerweise überdeckt eine neue Form das, was darunter liegt. Mit einem anderen Mischmodus kannst du Farben stattdessen addieren – überlappende Flächen werden dann heller und leuchten. Ideal für Feuer, Magie oder Lichtkegel."),
  H.figure("42_blend.png", "Oben drei erzeugte Texturen; unten überlappende Kreise im additiven Modus (heller = Glow)."),
  H.cmd("BLEND_MODE", 'BLEND_MODE(modus$)',
    "Stellt den Mischmodus für die folgenden Zeichenbefehle ein: \"alpha\" (normal), \"add\" (addierend – leuchtet), \"mult\" (multiplizierend – verdunkelt) oder \"subtract\". Nach dem Effekt mit BLEND_MODE(\"alpha\") zurückschalten.",
    [
      'CLS()',
      'BLEND_MODE("add")           \' ab jetzt addierend',
      'CIRCLE(150, 120, 50, RGB(64, 32, 0))',
      'CIRCLE(190, 120, 50, RGB(16, 64, 48))',
      'BLEND_MODE("alpha")         \' zurück zum Normalmodus',
      'FLIP()',
    ]),

  H.h2("Texturen erzeugen"),
  H.p("Diese Befehle berechnen ein fertiges Bild (ein IMAGE), das du dann wie ein geladenes Bild mit DRAWIMAGE zeichnest (siehe Kapitel „Bilder“). Praktisch für Hintergründe, ohne eine Bilddatei mitliefern zu müssen."),
  H.cmd("GENTEX_PERLIN", "GENTEX_PERLIN(breite, höhe, skala)",
    "Erzeugt eine weiche, wolkige Rauschtextur (Perlin-Noise). Größere skala = gröbere Muster. Gut für Wolken, Nebel, Terrain.",
    [
      'DIM wolken AS IMAGE',
      'wolken = GENTEX_PERLIN(160, 120, 6.0)',
      'CLS() : DRAWIMAGE(wolken, 0, 0) : FLIP()',
    ]),
  H.cmd("GENTEX_GRADIENT", "GENTEX_GRADIENT(breite, höhe, farbe1, farbe2[, vertikal])",
    "Erzeugt eine Verlaufstextur von farbe1 nach farbe2 (vertikal = TRUE für senkrecht, FALSE für waagerecht; ohne Angabe waagerecht).",
    [
      'DIM himmel AS IMAGE',
      'himmel = GENTEX_GRADIENT(160, 120, RGB(255, 96, 32), RGB(32, 64, 255), TRUE)',
      'CLS() : DRAWIMAGE(himmel, 0, 0) : FLIP()',
    ]),
  H.cmd("GENTEX_CHECKED · GENTEX_COLOR · GENTEX_RADIAL", "GENTEX_CHECKED(b, h, fx, fy, f1, f2)   GENTEX_COLOR(b, h, f)   GENTEX_RADIAL(b, h, innen, außen[, dichte])",
    "GENTEX_CHECKED erzeugt ein Schachbrettmuster (fx × fy Felder), GENTEX_COLOR eine einfarbige Fläche, GENTEX_RADIAL einen runden Verlauf von der Mitte nach außen – perfekt für weiche Lichter und Glows.",
    [
      'DIM brett AS IMAGE',
      'brett = GENTEX_CHECKED(160, 120, 8, 6, RGB(48, 56, 56), RGB(208, 216, 208))',
      'DIM licht AS IMAGE',
      'licht = GENTEX_RADIAL(128, 128, RGB(255, 255, 200), RGB(0, 0, 0))',
      'CLS() : DRAWIMAGE(brett, 0, 0) : FLIP()',
    ]),

  H.h2("Zwischen-Zeichenflächen: Render-Targets"),
  H.p("Ein Render-Target ist eine unsichtbare Zeichenfläche im Hintergrund. Du zeichnest etwas einmal hinein und stempelst es danach beliebig oft ins Bild – das spart Arbeit, wenn ein zusammengesetztes Bild (etwa ein Abzeichen oder eine Minimap) mehrmals erscheint oder sich nur selten ändert."),
  H.cmd("RENDERTARGET_NEW · _BEGIN · _END · _DRAW", "RENDERTARGET_NEW(b, h [, behalten])   RENDERTARGET_BEGIN(rt)   RENDERTARGET_END()   RENDERTARGET_DRAW(rt, x, y[, skala[, tint]])",
    "RENDERTARGET_NEW legt eine Fläche an. Zwischen _BEGIN und _END landen alle Zeichenbefehle in dieser Fläche statt im Fenster. _DRAW stempelt die fertige Fläche an Position (x, y) ins Bild.",
    [
      'DIM rt AS INTEGER',
      'rt = RENDERTARGET_NEW(64, 64)',
      'RENDERTARGET_BEGIN(rt)         \' ab jetzt in die Flaeche zeichnen',
      'CIRCLE(32, 32, 28, RGB(255, 180, 40))',
      'RENDERTARGET_END()',
      '',
      'CLS()',
      'RENDERTARGET_DRAW(rt, 50, 50)  \' Flaeche ins Bild stempeln',
      'RENDERTARGET_DRAW(rt, 150, 50) \' nochmal woanders',
      'FLIP()',
    ]),
  H.cmd("GENTEX_CELLULAR · GENTEX_NOISE · GENTEX_GRADIENT_BOX", "GENTEX_CELLULAR(b, h, kachel)   GENTEX_NOISE(b, h, anteil)   GENTEX_GRADIENT_BOX(b, h, dichte, f1, f2)",
    "Drei weitere Muster: GENTEX_CELLULAR erzeugt Zellrauschen (Voronoi) – Steinboden, Risse, Schuppen; kleinere kachel = feinere Zellen. GENTEX_NOISE ist reines Weißrauschen, anteil (0.0–1.0) steuert, wie viele Pixel gesetzt werden – für Sternenfelder oder Bildkorn. GENTEX_GRADIENT_BOX verläuft rechteckig von innen nach außen und ist damit das eckige Gegenstück zu GENTEX_RADIAL – ideal für Vignetten.",
    [
      'DIM stein AS IMAGE',
      'stein = GENTEX_CELLULAR(160, 120, 12.0)',
      'DIM sterne AS IMAGE',
      'sterne = GENTEX_NOISE(320, 240, 0.02)      \' 2 % der Pixel',
      'DIM vignette AS IMAGE',
      'vignette = GENTEX_GRADIENT_BOX(320, 240, 0.6, RGB(0,0,0), RGB(0,0,0))',
      'CLS() : DRAWIMAGE(stein, 0, 0) : FLIP()',
    ]),

  H.h2("Shader: eigene Effekte auf der Grafikkarte"),
  H.p("Ein Shader ist ein kleines Programm, das die Grafikkarte für JEDEN Pixel ausführt. Damit bekommst du Effekte, die mit normalen Zeichenbefehlen unbezahlbar wären: Bildschirmkrümmung wie an einem Röhrenmonitor, Leuchten (Bloom), Farbstiche, Wellen. Drachenhauch reicht dir den fertigen Frame durch einen Fragment-Shader in der Sprache GLSL."),
  H.cmd("SHADER_LOAD", 'SHADER_LOAD(pfad$_oder_glsl$)',
    "Lädt einen Fragment-Shader – entweder aus einer Datei oder direkt als Quelltext im String. Liefert ein Handle oder -1, wenn das Übersetzen fehlschlägt (die Fehlermeldung der Grafikkarte steht dann in der Konsole).",
    [
      'DIM crt AS INTEGER',
      'crt = SHADER_LOAD("assets/shaders/crt.fs")',
      'IF crt = -1 THEN PRINT "Shader nicht ladbar"',
    ]),
  H.cmd("POSTFX", 'POSTFX(shader)',
    "Schickt ab jetzt jeden fertigen Frame durch den Shader, bevor er im Fenster erscheint. POSTFX(-1) schaltet den Effekt wieder ab. Intern wird die Szene dafür in eine unsichtbare Fläche gerendert und dann mit dem Shader auf den Bildschirm gebracht.",
    [
      'POSTFX(crt)                    \' Effekt an',
      'IF KEYHIT(KEY_F2) THEN POSTFX(-1)   \' und wieder aus',
    ]),
  H.cmd("SHADER_SET · SHADER_SET2 · SHADER_SET3", 'SHADER_SET(sh, name$, wert)   SHADER_SET2(sh, name$, x, y)   SHADER_SET3(sh, name$, x, y, z)',
    "Setzen eine Variable („Uniform“) im Shader: eine einzelne Zahl, ein Zahlenpaar (etwa eine Bildschirmgröße) oder ein Tripel (etwa eine Farbe). Der Name muss genau dem im Shader entsprechen; unbekannte Namen sind kein Fehler (der Übersetzer wirft ungenutzte Variablen weg).",
    [
      'SHADER_SET(crt, "zeit", GET_TIME())',
      'SHADER_SET2(crt, "aufloesung", SCREENWIDTH(), SCREENHEIGHT())',
      'SHADER_SET3(crt, "tint", 1.0, 0.9, 0.8)',
    ]),
  H.cmd("SHADER_SET_ARRAY · SHADER_SET_TEXTURE · SHADER_SET_MATRIX", 'SHADER_SET_ARRAY(sh, name$, werte)   SHADER_SET_TEXTURE(sh, name$, bild)   SHADER_SET_MATRIX(sh, name$, mat)',
    "Für größere Datenmengen: SHADER_SET_ARRAY füllt ein uniform float[] aus einem ARRAY OF FLOAT (etwa mehrere Lichtpositionen), SHADER_SET_TEXTURE belegt einen ZWEITEN Bildsampler (Masken, Farbtabellen, Überblendungen), SHADER_SET_MATRIX übergibt eine MAT4 aus dem Modul m3d.",
    [
      'DIM staerken[4] AS FLOAT',
      'staerken[0] = 0.2 : staerken[1] = 0.4',
      'SHADER_SET_ARRAY(bloom, "stufen", staerken)',
      '',
      'DIM maske AS IMAGE',
      'maske = LOADIMAGE("assets/maske.png")',
      'SHADER_SET_TEXTURE(bloom, "maske", maske)',
    ]),
  H.note("Fertige Beispiel-Shader (CRT, Bloom, Vignette) liegen unter examples/assets/shaders/, eine vollständige Demo ist examples/86_postfx_shaders.dh."),

  H.h2("Eine Fläche, die sich merkt: Schweife"),
  H.p("Normalerweise wird ein Render-Target zu jedem Bild geleert – du zeichnest hinein, stempelst, fertig. Mit behalten = TRUE bleibt der Inhalt dagegen über das Bild hinaus stehen. Damit entsteht Rückkopplung: Was du zeichnest, liegt im nächsten Bild noch da, und was du neu darüber malst, kommt hinzu. Genau so entstehen Leuchtspuren und Schweife."),
  H.cmd("RENDERTARGET_CLEAR", "RENDERTARGET_CLEAR(rt [, farbe])",
    "Leert eine behaltene Fläche von Hand. Bei behalten = TRUE macht das sonst niemand mehr für dich.",
    [
      "DIM rt AS INTEGER",
      "rt = RENDERTARGET_NEW(320, 240, TRUE)   ' Inhalt bleibt stehen",
      "",
      "' jedes Bild: alles ETWAS abdunkeln, dann den Punkt neu setzen",
      "RENDERTARGET_BEGIN(rt)",
      'BLEND_MODE("mult")',
      "BOX(0, 0, 320, 240, RGB(240, 240, 240))   ' 6 % dunkler",
      'BLEND_MODE("alpha")',
      "CIRCLE(x, y, 4, RGB(120, 255, 200))",
      "RENDERTARGET_END()",
      "RENDERTARGET_DRAW(rt, 0, 0)",
    ]),
  H.note("Das Abdunkeln ist der Trick: Ohne es würde die Spur nie verblassen und die Fläche liefe nach ein paar Sekunden voll. Ein Vollbild-Rechteck im Multiplikations-Modus zieht jedes Bild ein paar Prozent Helligkeit ab – der Schweif wird nach hinten von selbst dunkler."),
  H.warn("RENDERTARGET_DRAW innerhalb eines anderen Render-Targets tut nichts. Wer Rückkopplung will, nimmt behalten = TRUE – das ist genau dafür da.", "Ein Ziel kann sich nicht selbst zeichnen"),

  H.h2("Zustand sichern: GFX_PUSH und GFX_POP"),
  H.p("Licht, Nebel, Himmel, Schatten, Kamera, Schrift und der Post-Effekt sind GLOBAL. Wer sie in einer Szene umstellt, muss sie beim Verlassen von Hand zurückstellen – und wer eine Zeile vergisst, sieht den Fehler erst zwei Szenen später: den Nebel im falschen Raum, den Shader über dem Menü. Mit einem Stapel wird daraus eine Eigenschaft der Sprache statt einer Frage der Disziplin."),
  H.cmd("GFX_PUSH · GFX_POP · GFX_DEPTH", "GFX_PUSH()   GFX_POP()   GFX_DEPTH()",
    "GFX_PUSH legt den gesamten Zeichenzustand auf einen Stapel, GFX_POP holt ihn zurück. GFX_DEPTH sagt, wie tief der Stapel gerade ist – ein POP ohne PUSH ist ein Fehler.",
    [
      "GFX_PUSH()",
      "LIGHT_FOG(RGB(120, 100, 90), 0.03)     ' nur fuer diese Szene",
      "SHADOW_ENABLE(2048)",
      "szene_hoehle()",
      "GFX_POP()                              ' alles zurueck wie vorher",
    ]),
  H.p("Gesichert wird ausschließlich EINSTELLUNG, nie Ressource: 2D-Kamera samt Rütteln, aktive Ebene, Hintergrundfarbe, Licht, Umgebung, Schatten, 3D-Kamera, Schrift und POSTFX. Geladene Bilder, Modelle und Shader bleiben natürlich geladen – ein POP schaltet nur ihre Benutzung zurück."),
  H.tip("Auch für den Ton", "AUDIO_PUSH und AUDIO_POP tun dasselbe für alle Bus-Einstellungen – Lautstärke, Balance, Filter, Hall, Echo, Verzerrer, Kompressor, EQ. Mehr dazu im Audio-Kapitel."),

  H.tip("Alles nur in dhrt", "Diese Extras (besonders Blend-Modes, GenTex, Render-Targets und Shader) nutzen die Grafikkarte und laufen nur im dhrt-Fenster – wie der ganze Teil IV. In einem reinen Konsolenprogramm gibt es sie nicht."),
];
