module.exports = (H) => [
  H.chapter("Bilder"),
  H.p("Statt alles aus Formen zu zeichnen, lädst du meist fertige Bilder (Sprites, Hintergründe, Tilesets) aus PNG-Dateien. Ein Bild ist in GameBasic ein IMAGE-Wert; du lädst es einmal vor dem Game-Loop und zeichnest es dann jeden Frame. Häufig steckt in einer Datei ein ganzes „Spritesheet“ – mehrere Einzelbilder nebeneinander, aus dem du das gewünschte herausschneidest."),
  H.figure("43_bilder.png", "Ein Spritesheet als Ganzes, ein einzelner Frame daraus, skaliert/gedreht, sowie gespiegelt und getönt (imgfx)."),
  H.note("Bildpfade sind relativ zum Verzeichnis deines Programms (üblich ist ein Unterordner assets/). Lade Bilder einmalig vor dem Game-Loop – nicht in jedem Frame neu."),

  H.h2("Laden & Größe"),
  H.cmd("LOADIMAGE", 'LOADIMAGE(pfad$)',
    "Lädt eine Bilddatei (PNG, JPG, BMP …) und liefert ein IMAGE. Das Ergebnis wird zwischengespeichert – ein zweiter Aufruf mit demselben Pfad lädt nicht erneut von der Platte.",
    [
      'DIM held AS IMAGE',
      'held = LOADIMAGE("assets/hero.png")',
    ]),
  H.cmd("IMAGEWIDTH · IMAGEHEIGHT", 'IMAGEWIDTH(img)   IMAGEHEIGHT(img)',
    "Liefern Breite und Höhe eines Bildes in Pixeln – nützlich, um es zu zentrieren oder ein Sheet in Frames aufzuteilen.",
    [
      'DIM held AS IMAGE',
      'held = LOADIMAGE("assets/hero.png")',
      'PRINT IMAGEWIDTH(held); " x "; IMAGEHEIGHT(held)',
      '\' z. B.:  256 x 32',
    ]),
  H.cmd("GETPIXEL", 'GETPIXEL(img, x, y) AS INTEGER',
    "Liest die Farbe eines einzelnen Pixels eines geladenen Bildes zurück (als 0xRRGGBB-Zahl, gleiches Format wie RGB()). Liefert -1 bei ungültigen Koordinaten. Kombiniert mit RED()/GREEN()/BLUE() (Kapitel „Farben“) liest du die einzelnen Kanäle aus – praktisch, um z. B. eine Heightmap oder eine Colormap Pixel für Pixel auszuwerten.",
    [
      'IMPORT "imgfx"',
      'DIM img AS IMAGE',
      'img = GENTEX_COLOR(4, 4, RGB(200, 60, 60))',
      'PRINT RED(GETPIXEL(img, 1, 1)); " "; GREEN(GETPIXEL(img, 1, 1)); " "; BLUE(GETPIXEL(img, 1, 1))',
    ],
    { out: ["200 60 60"] }),

  H.h2("Zeichnen"),
  H.cmd("DRAWIMAGE", 'DRAWIMAGE(img, x, y)',
    "Zeichnet das ganze Bild mit der linken oberen Ecke bei (x, y).",
    [
      'CLS()',
      'DRAWIMAGE(held, 100, 80)',
      'FLIP()',
    ]),
  H.cmd("DRAWIMAGEPART", 'DRAWIMAGEPART(img, sx, sy, sw, sh, x, y)',
    "Zeichnet nur einen Ausschnitt des Bildes: das Rechteck (sx, sy, sw, sh) aus der Quelle, gezeichnet bei (x, y). So holst du einen einzelnen Frame aus einem Spritesheet – hier den ersten von acht 32×32-Frames.",
    [
      'CLS()',
      '\' Frame 0 (Spalte 0) aus einem 32x32-Raster:',
      'DRAWIMAGEPART(held, 0, 0, 32, 32, 100, 80)',
      '\' Frame 3 liegt bei sx = 3 * 32 = 96:',
      'DRAWIMAGEPART(held, 96, 0, 32, 32, 140, 80)',
      'FLIP()',
    ]),
  H.cmd("DRAWIMAGEPARTEX", 'DRAWIMAGEPARTEX(img, sx, sy, sw, sh, x, y, w, h)',
    "Wie DRAWIMAGEPART, aber mit eigener Zielgröße (w, h) statt 1:1 – der Ausschnitt wird beim Zeichnen auf die Zielgröße gestreckt oder gestaucht. Praktisch, um einen kleinen Sprite-Frame direkt vergrößert darzustellen, ohne vorher eine skalierte Kopie zu erzeugen.",
    [
      'CLS()',
      '\' Frame 0 (32x32) auf 64x64 vergroessert zeichnen:',
      'DRAWIMAGEPARTEX(held, 0, 0, 32, 32, 100, 80, 64, 64)',
      'FLIP()',
    ]),
  H.cmd("DRAWIMAGEROT", 'DRAWIMAGEROT(img, x, y, winkel[, skala[, tint]])',
    "Zeichnet das Bild ZENTRIERT auf (x, y), um diesen Punkt um winkel Grad gedreht und optional skaliert und eingefärbt (tint). Ideal für rotierende Sprites (Asteroiden, Geschosse, gedrehte Spielfiguren).",
    [
      'CLS()',
      'DRAWIMAGEROT(held, 160, 120, 45.0)         \' 45 Grad gedreht',
      'DRAWIMAGEROT(held, 240, 120, 0.0, 2.0)     \' doppelt so groß',
      'FLIP()',
    ]),

  H.h2("Bilder umrechnen: das Modul imgfx"),
  H.p("Das Modul imgfx erzeugt aus einem Bild ein NEUES, verändertes Bild – skaliert, gedreht, gespiegelt oder eingefärbt. Das Original bleibt unverändert. Mache solche Umrechnungen einmalig vor dem Game-Loop (nicht jeden Frame), denn sie kosten etwas Zeit."),
  H.cmd("IMAGE_SCALE", 'IMAGE_SCALE(img, breite, höhe)',
    "Liefert eine in der angegebenen Größe skalierte Kopie des Bildes.",
    [
      'IMPORT "imgfx"',
      'DIM gross AS IMAGE',
      'gross = IMAGE_SCALE(held, 64, 64)   \' auf 64x64 vergrößern',
    ]),
  H.cmd("IMAGE_FLIP", 'IMAGE_FLIP(img, flipX, flipY)',
    "Liefert eine gespiegelte Kopie – flipX spiegelt waagerecht (links/rechts), flipY senkrecht (oben/unten). Klassisch, um eine nach rechts laufende Figur auch nach links blicken zu lassen.",
    [
      'IMPORT "imgfx"',
      'DIM nachLinks AS IMAGE',
      'nachLinks = IMAGE_FLIP(held, TRUE, FALSE)',
    ]),
  H.cmd("IMAGE_ROTATE · IMAGE_TINT", 'IMAGE_ROTATE(img, grad)   IMAGE_TINT(img, farbe)',
    "IMAGE_ROTATE liefert eine um grad gedrehte Kopie (die Bildgröße wächst ggf. mit). IMAGE_TINT multipliziert jede Pixelfarbe mit farbe – gut, um dasselbe Sprite in Teamfarben einzufärben (rotes / blaues Team).",
    [
      'IMPORT "imgfx"',
      'DIM blau AS IMAGE',
      'blau = IMAGE_TINT(held, RGB(120, 160, 255))',
      'DIM schraeg AS IMAGE',
      'schraeg = IMAGE_ROTATE(held, 30.0)',
    ]),
  H.tip("DRAWIMAGEROT vs. imgfx", "Willst du ein Bild nur beim Zeichnen drehen/skalieren, nimm DRAWIMAGEROT – das ist schnell und braucht kein neues Bild. Brauchst du dagegen die veränderte Version mehrfach (z. B. eine gespiegelte Lauf-Animation), erzeuge sie einmal mit imgfx und zeichne sie dann normal."),

  H.h2("Mehr Bildfilter (imgfx)"),
  H.p("Neben Skalieren/Spiegeln/Drehen/Tönen bringt imgfx weitere Filter mit. Wie IMAGE_SCALE & Co. liefern sie eine NEUE, veränderte Bild-Kopie – das Original bleibt unverändert."),
  H.cmd("IMAGE_GRAYSCALE · IMAGE_INVERT", 'IMAGE_GRAYSCALE(img)   IMAGE_INVERT(img)',
    "IMAGE_GRAYSCALE liefert eine Graustufen-Kopie (alle Kanäle auf denselben Helligkeitswert gemischt). IMAGE_INVERT kehrt jeden Farbkanal um (255 minus Wert) – aus Rot wird Cyan-artig, klassischer Fotonegativ-Effekt.",
    [
      'IMPORT "imgfx"',
      'DIM img AS IMAGE',
      'img = GENTEX_COLOR(4, 4, RGB(200, 60, 60))',
      'DIM grau AS IMAGE',
      'grau = IMAGE_GRAYSCALE(img)',
      'PRINT RED(GETPIXEL(grau, 1, 1)); " "; GREEN(GETPIXEL(grau, 1, 1)); " "; BLUE(GETPIXEL(grau, 1, 1))',
      'DIM inv AS IMAGE',
      'inv = IMAGE_INVERT(img)',
      'PRINT RED(GETPIXEL(inv, 1, 1)); " "; GREEN(GETPIXEL(inv, 1, 1)); " "; BLUE(GETPIXEL(inv, 1, 1))',
    ],
    { out: ["101 101 101", "55 195 195"] }),
  H.cmd("IMAGE_BRIGHTNESS · IMAGE_CONTRAST", 'IMAGE_BRIGHTNESS(img, n: -255..255)   IMAGE_CONTRAST(img, n: -100..100)',
    "IMAGE_BRIGHTNESS hellt jeden Kanal um n auf (negativ = abdunkeln). IMAGE_CONTRAST spreizt oder staucht den Kontrast um n Prozent (negativ = flacher, positiv = knalliger).",
    [
      'IMPORT "imgfx"',
      'DIM img AS IMAGE',
      'img = GENTEX_COLOR(4, 4, RGB(200, 60, 60))',
      'DIM hell AS IMAGE',
      'hell = IMAGE_BRIGHTNESS(img, 40)',
      'PRINT RED(GETPIXEL(hell, 1, 1)); " "; GREEN(GETPIXEL(hell, 1, 1)); " "; BLUE(GETPIXEL(hell, 1, 1))',
      'DIM kontrast AS IMAGE',
      'kontrast = IMAGE_CONTRAST(img, 50)',
      'PRINT RED(GETPIXEL(kontrast, 1, 1)); " "; GREEN(GETPIXEL(kontrast, 1, 1)); " "; BLUE(GETPIXEL(kontrast, 1, 1))',
    ],
    { out: ["240 100 100", "255 0 0"] }),
  H.cmd("IMAGE_BLUR", 'IMAGE_BLUR(img, radius)',
    "Liefert eine weichgezeichnete Kopie – größerer radius = stärkerer Weichzeichner. Gut für Glow-Effekte oder ein Hintergrundbild, das unscharf hinter der Spielfigur liegen soll.",
    [
      'IMPORT "imgfx"',
      'DIM img AS IMAGE',
      'img = GENTEX_COLOR(32, 32, RGB(200, 60, 60))',
      'DIM weich AS IMAGE',
      'weich = IMAGE_BLUR(img, 3)',
      'PRINT IMAGEWIDTH(weich); " x "; IMAGEHEIGHT(weich)',
    ],
    { out: ["32 x 32"] }),
  H.cmd("IMAGE_REPLACE_COLOR", 'IMAGE_REPLACE_COLOR(img, von: INTEGER, nach: INTEGER)',
    "Ersetzt jedes Pixel der Farbe von durch nach – die klassische Farbtausch-Technik für Sprite-Recolors (z. B. ein grünes Team aus einem roten Sprite machen) oder um eine Farbe als transparent zu markieren.",
    [
      'IMPORT "imgfx"',
      'DIM img AS IMAGE',
      'img = GENTEX_COLOR(4, 4, RGB(200, 60, 60))',
      'DIM ersetzt AS IMAGE',
      'ersetzt = IMAGE_REPLACE_COLOR(img, RGB(200, 60, 60), RGB(0, 255, 0))',
      'PRINT RED(GETPIXEL(ersetzt, 1, 1)); " "; GREEN(GETPIXEL(ersetzt, 1, 1)); " "; BLUE(GETPIXEL(ersetzt, 1, 1))',
    ],
    { out: ["0 255 0"] }),
  H.cmd("IMAGE_CROP · IMAGE_RESIZE_CANVAS", 'IMAGE_CROP(img, x, y, w, h)   IMAGE_RESIZE_CANVAS(img, w, h, offx, offy[, fuellfarbe])',
    "IMAGE_CROP schneidet den Bereich (x, y, w, h) aus einem Bild heraus. IMAGE_RESIZE_CANVAS ändert die Leinwandgröße (ohne den Bildinhalt zu skalieren) und platziert das alte Bild bei (offx, offy) – der neue Rand wird mit fuellfarbe gefüllt.",
    [
      'IMPORT "imgfx"',
      'DIM img AS IMAGE',
      'img = GENTEX_COLOR(32, 32, RGB(200, 60, 60))',
      'DIM ausschnitt AS IMAGE',
      'ausschnitt = IMAGE_CROP(img, 4, 4, 10, 10)',
      'PRINT IMAGEWIDTH(ausschnitt); " x "; IMAGEHEIGHT(ausschnitt)',
      'DIM leinwand AS IMAGE',
      'leinwand = IMAGE_RESIZE_CANVAS(img, 48, 48, 8, 8, RGB(0, 0, 0))',
      'PRINT IMAGEWIDTH(leinwand); " x "; IMAGEHEIGHT(leinwand)',
    ],
    { out: ["10 x 10", "48 x 48"] }),

  H.h2("Direkt auf ein Bild malen"),
  H.p("Die folgenden vier Befehle unterscheiden sich von den Filtern oben: Sie verändern das übergebene Bild DIREKT (in place) statt eine Kopie zu liefern – wie ein Mini-Zeichenprogramm auf einer IMAGE-Leinwand. Praktisch, um zur Laufzeit ein Textur-Atlas zusammenzusetzen oder eine Heightmap/Colormap prozedural zu bemalen."),
  H.cmd("IMAGE_DRAW_CIRCLE · IMAGE_DRAW_LINE · IMAGE_DRAW_RECT", 'IMAGE_DRAW_CIRCLE(img, cx, cy, r, farbe)   IMAGE_DRAW_LINE(img, x1, y1, x2, y2, farbe)   IMAGE_DRAW_RECT(img, x, y, w, h, farbe)',
    "Zeichnen einen gefüllten Kreis, eine Linie bzw. ein gefülltes Rechteck direkt in die Pixel des Bildes – dieselben Grundformen wie beim Zeichnen aufs Fenster (Kapitel „2D-Zeichnen“), nur auf ein IMAGE statt den Bildschirm angewendet.",
    [
      'IMPORT "imgfx"',
      'DIM canvas AS IMAGE',
      'canvas = GENTEX_COLOR(16, 16, RGB(0, 0, 0))',
      'IMAGE_DRAW_CIRCLE(canvas, 8, 8, 4, RGB(255, 255, 0))',
      'PRINT RED(GETPIXEL(canvas, 8, 5)); " "; GREEN(GETPIXEL(canvas, 8, 5)); " "; BLUE(GETPIXEL(canvas, 8, 5))',
      'IMAGE_DRAW_LINE(canvas, 0, 0, 15, 15, RGB(255, 0, 0))',
      'PRINT RED(GETPIXEL(canvas, 3, 3)); " "; GREEN(GETPIXEL(canvas, 3, 3)); " "; BLUE(GETPIXEL(canvas, 3, 3))',
      'IMAGE_DRAW_RECT(canvas, 1, 1, 4, 4, RGB(0, 0, 255))',
      'PRINT RED(GETPIXEL(canvas, 2, 2)); " "; GREEN(GETPIXEL(canvas, 2, 2)); " "; BLUE(GETPIXEL(canvas, 2, 2))',
    ],
    { out: ["255 255 0", "255 0 0", "0 0 255"] }),
  H.cmd("IMAGE_DRAW_TEXT", 'IMAGE_DRAW_TEXT(img, x, y, text$, groesse, farbe)',
    "Schreibt Text direkt in die Pixel des Bildes – etwa um eine Beschriftung fest in ein generiertes Icon oder eine Karte einzubrennen.",
    [
      'IMPORT "imgfx"',
      'DIM canvas AS IMAGE',
      'canvas = GENTEX_COLOR(64, 16, RGB(0, 0, 0))',
      'IMAGE_DRAW_TEXT(canvas, 2, 2, "Hi", 12, RGB(255, 255, 255))',
      'PRINT "gezeichnet"',
    ],
    { out: ["gezeichnet"] }),
  H.note("Die vier DRAW-Befehle mutieren das Bild direkt – es entsteht KEINE Kopie. Willst du das Original behalten, machst du vorher selbst eine Kopie (z. B. mit IMAGE_SCALE(img, IMAGEWIDTH(img), IMAGEHEIGHT(img)))."),
];
