module.exports = (H) => [
  H.chapter("Bilder"),
  H.p("Statt alles aus Formen zu zeichnen, lädst du meist fertige Bilder (Sprites, Hintergründe, Tilesets) aus PNG-Dateien. Ein Bild ist in GameBasic ein IMAGE-Wert; du lädst es einmal vor dem Game-Loop und zeichnest es dann jeden Frame. Häufig steckt in einer Datei ein ganzes „Spritesheet“ – mehrere Einzelbilder nebeneinander, aus dem du das gewünschte herausschneidest."),
  H.figure("43_bilder.png", "Ein Spritesheet als Ganzes, ein einzelner Frame daraus, skaliert/gedreht, sowie gespiegelt und getönt (imgfx)."),
  H.note("Bildpfade sind relativ zum Verzeichnis deines Programms (üblich ist ein Unterordner assets/). Lade Bilder einmalig vor dem Game-Loop – nicht in jedem Frame neu."),

  H.h2("Laden & Größe"),
  H.cmd("LOADIMAGE", 'LOADIMAGE(pfad$)',
    "Lädt eine Bilddatei (PNG, JPG, BMP …) und liefert ein IMAGE. Das Ergebnis wird zwischengespeichert – ein zweiter Aufruf mit demselben Pfad lädt nicht erneut von der Platte.",
    [
      'DIM held AS IMAGE',
      'held = LOADIMAGE("assets/hero.png")',
    ]),
  H.cmd("IMAGEWIDTH · IMAGEHEIGHT", 'IMAGEWIDTH(img)   IMAGEHEIGHT(img)',
    "Liefern Breite und Höhe eines Bildes in Pixeln – nützlich, um es zu zentrieren oder ein Sheet in Frames aufzuteilen.",
    [
      'DIM held AS IMAGE',
      'held = LOADIMAGE("assets/hero.png")',
      'PRINT IMAGEWIDTH(held); " x "; IMAGEHEIGHT(held)',
      '\' z. B.:  256 x 32',
    ]),

  H.h2("Zeichnen"),
  H.cmd("DRAWIMAGE", 'DRAWIMAGE(img, x, y)',
    "Zeichnet das ganze Bild mit der linken oberen Ecke bei (x, y).",
    [
      'CLS()',
      'DRAWIMAGE(held, 100, 80)',
      'FLIP()',
    ]),
  H.cmd("DRAWIMAGEPART", 'DRAWIMAGEPART(img, sx, sy, sw, sh, x, y)',
    "Zeichnet nur einen Ausschnitt des Bildes: das Rechteck (sx, sy, sw, sh) aus der Quelle, gezeichnet bei (x, y). So holst du einen einzelnen Frame aus einem Spritesheet – hier den ersten von acht 32×32-Frames.",
    [
      'CLS()',
      '\' Frame 0 (Spalte 0) aus einem 32x32-Raster:',
      'DRAWIMAGEPART(held, 0, 0, 32, 32, 100, 80)',
      '\' Frame 3 liegt bei sx = 3 * 32 = 96:',
      'DRAWIMAGEPART(held, 96, 0, 32, 32, 140, 80)',
      'FLIP()',
    ]),
  H.cmd("DRAWIMAGEROT", 'DRAWIMAGEROT(img, x, y, winkel[, skala[, tint]])',
    "Zeichnet das Bild ZENTRIERT auf (x, y), um diesen Punkt um winkel Grad gedreht und optional skaliert und eingefärbt (tint). Ideal für rotierende Sprites (Asteroiden, Geschosse, gedrehte Spielfiguren).",
    [
      'CLS()',
      'DRAWIMAGEROT(held, 160, 120, 45.0)         \' 45 Grad gedreht',
      'DRAWIMAGEROT(held, 240, 120, 0.0, 2.0)     \' doppelt so groß',
      'FLIP()',
    ]),

  H.h2("Bilder umrechnen: das Modul imgfx"),
  H.p("Das Modul imgfx erzeugt aus einem Bild ein NEUES, verändertes Bild – skaliert, gedreht, gespiegelt oder eingefärbt. Das Original bleibt unverändert. Mache solche Umrechnungen einmalig vor dem Game-Loop (nicht jeden Frame), denn sie kosten etwas Zeit."),
  H.cmd("IMAGE_SCALE", 'IMAGE_SCALE(img, breite, höhe)',
    "Liefert eine in der angegebenen Größe skalierte Kopie des Bildes.",
    [
      'IMPORT "imgfx"',
      'DIM gross AS IMAGE',
      'gross = IMAGE_SCALE(held, 64, 64)   \' auf 64x64 vergrößern',
    ]),
  H.cmd("IMAGE_FLIP", 'IMAGE_FLIP(img, flipX, flipY)',
    "Liefert eine gespiegelte Kopie – flipX spiegelt waagerecht (links/rechts), flipY senkrecht (oben/unten). Klassisch, um eine nach rechts laufende Figur auch nach links blicken zu lassen.",
    [
      'IMPORT "imgfx"',
      'DIM nachLinks AS IMAGE',
      'nachLinks = IMAGE_FLIP(held, TRUE, FALSE)',
    ]),
  H.cmd("IMAGE_ROTATE · IMAGE_TINT", 'IMAGE_ROTATE(img, grad)   IMAGE_TINT(img, farbe)',
    "IMAGE_ROTATE liefert eine um grad gedrehte Kopie (die Bildgröße wächst ggf. mit). IMAGE_TINT multipliziert jede Pixelfarbe mit farbe – gut, um dasselbe Sprite in Teamfarben einzufärben (rotes / blaues Team).",
    [
      'IMPORT "imgfx"',
      'DIM blau AS IMAGE',
      'blau = IMAGE_TINT(held, RGB(120, 160, 255))',
      'DIM schraeg AS IMAGE',
      'schraeg = IMAGE_ROTATE(held, 30.0)',
    ]),
  H.tip("DRAWIMAGEROT vs. imgfx", "Willst du ein Bild nur beim Zeichnen drehen/skalieren, nimm DRAWIMAGEROT – das ist schnell und braucht kein neues Bild. Brauchst du dagegen die veränderte Version mehrfach (z. B. eine gespiegelte Lauf-Animation), erzeuge sie einmal mit imgfx und zeichne sie dann normal."),
];
