module.exports = (H) => [
  H.chapter("Eingabe"),
  H.p("Ein Spiel wird erst lebendig, wenn der Spieler eingreifen kann. Im Grafikfenster fragst du Tastatur, Maus und Gamepad nicht mit INPUT ab (das ist nur für die Konsole), sondern Frame für Frame im Game-Loop. Dieses Kapitel zeigt die direkten Abfragen und das komfortable input-Modul, mit dem du Tasten an benannte Aktionen bindest."),
  H.figure("45_eingabe.png", "Eine kleine Steuerungs-Demo: ein per Tastatur bewegter Spieler und eine Steuerungs-Legende."),

  H.h2("Tastatur"),
  H.cmd("KEYPRESSED", "KEYPRESSED(taste)",
    "Liefert TRUE, solange die angegebene Taste gehalten wird. Die Taste gibst du als KEY_-Konstante an. Im Game-Loop abgefragt, ergibt das flüssige Bewegung.",
    [
      'IF KEYPRESSED(KEY_LEFT)  THEN px = px - 2',
      'IF KEYPRESSED(KEY_RIGHT) THEN px = px + 2',
      'IF KEYPRESSED(KEY_SPACE) THEN \' springen',
    ]),
  H.p("Eingebaute Tasten-Konstanten gibt es für alle wichtigen Tasten: KEY_LEFT, KEY_RIGHT, KEY_UP, KEY_DOWN, KEY_SPACE, KEY_RETURN (= KEY_ENTER), KEY_ESCAPE, KEY_TAB, KEY_BACKSPACE, die Buchstaben KEY_A bis KEY_Z und die Ziffern KEY_0 bis KEY_9."),
  H.note("KEYPRESSED ist „gehalten“ – es ist TRUE, solange die Taste unten ist. Für „genau einmal beim Drücken“ (z. B. Sprung, Menü-Auswahl) nimmst du die Edge-Erkennung des input-Moduls weiter unten (INPUT_PRESSED)."),

  H.h2("Maus"),
  H.cmd("MOUSEX · MOUSEY", "MOUSEX()   MOUSEY()",
    "Liefern die aktuelle Mausposition im Fenster (in logischen Pixeln). Gut, um ein Fadenkreuz oder einen Cursor zu zeichnen oder zu prüfen, worüber die Maus steht.",
    [
      'CLS()',
      'CIRCLE(MOUSEX(), MOUSEY(), 6, RGB(255, 255, 255))  \' Fadenkreuz',
      'FLIP()',
    ]),
  H.cmd("MOUSEBUTTON", "MOUSEBUTTON(n)",
    "Liefert TRUE, wenn die Maustaste n gedrückt ist: 0 = links, 1 = mitte, 2 = rechts.",
    [
      'IF MOUSEBUTTON(0) THEN \' Linksklick: schiessen',
    ]),
  H.cmd("MOUSEWHEEL", "MOUSEWHEEL()",
    "Liefert die Drehung des Mausrads seit dem letzten Aufruf: positiv nach oben, negativ nach unten, 0 wenn nichts gedreht wurde. Gut zum Zoomen oder Blättern.",
    [
      'DIM zoom AS FLOAT',
      'zoom = zoom + MOUSEWHEEL() * 0.1',
    ]),
  H.cmd("MOUSE_VISIBLE · MOUSE_LOCK", "MOUSE_VISIBLE(an)   MOUSE_LOCK(an)",
    "MOUSE_VISIBLE zeigt/versteckt den System-Cursor (verstecken, wenn du ein eigenes Cursor-Sprite zeichnest). MOUSE_LOCK fängt den Cursor im Fenster ein – für Maus-Kamerasteuerung in 3D/Ego-Perspektive.",
    [
      'MOUSE_VISIBLE(FALSE)    \' eigenen Cursor zeichnen',
    ]),

  H.h2("Komfortabel: das input-Modul"),
  H.p("Tasten direkt abzufragen funktioniert, hat aber zwei Schwächen: Die Steuerung ist fest verdrahtet (kein Umbelegen möglich), und „genau einmal beim Drücken“ musst du selbst basteln. Das Modul input löst beides: Du bindest Tasten an benannte Aktionen (\"springen\", \"links\") und fragst diese Aktionen ab. Mehrere Tasten pro Aktion sind erlaubt (Pfeiltaste UND WASD)."),
  H.p("Wichtig: Einmal pro Frame ruft INPUT_UPDATE() auf – das macht die Edge-Erkennung (PRESSED/RELEASED) erst möglich."),
  H.cmd("INPUT_BIND · INPUT_UPDATE", 'INPUT_BIND(aktion$, taste1[, taste2, ...])   INPUT_UPDATE()',
    "INPUT_BIND verbindet eine Aktion mit einer oder mehreren Tasten (einmal beim Start). INPUT_UPDATE liest pro Frame den aktuellen Tastenzustand ein – Pflicht am Anfang des Game-Loops.",
    [
      'IMPORT "input"',
      'INPUT_BIND("links",     KEY_LEFT,  KEY_A)',
      'INPUT_BIND("springen",  KEY_SPACE, KEY_W)',
      '',
      'WHILE NOT QUITREQUESTED()',
      '    INPUT_UPDATE()       \' jeden Frame zuerst',
      '    \' ... abfragen ...',
      '    FLIP()',
      'WEND',
    ]),
  H.cmd("INPUT_HELD · INPUT_PRESSED · INPUT_RELEASED", 'INPUT_HELD(aktion$)   INPUT_PRESSED(aktion$)   INPUT_RELEASED(aktion$)',
    "INPUT_HELD ist TRUE, solange eine gebundene Taste gehalten wird (für Bewegung). INPUT_PRESSED ist nur in dem einen Frame TRUE, in dem die Taste neu gedrückt wird (für Sprung, Menü). INPUT_RELEASED feuert beim Loslassen.",
    [
      'IF INPUT_HELD("links") THEN px = px - 2',
      'IF INPUT_PRESSED("springen") THEN \' genau einmal',
    ]),
  H.cmd("INPUT_AXIS", 'INPUT_AXIS(negativ$, positiv$)',
    "Fasst zwei gegensätzliche Aktionen zu einer Achse zusammen und liefert -1, 0 oder +1. Sehr praktisch für Links/Rechts- oder Hoch/Runter-Bewegung in einer Zeile.",
    [
      'DIM dx AS INTEGER',
      'dx = INPUT_AXIS("links", "rechts")   \' -1, 0 oder +1',
      'px = px + dx * 2',
    ]),
  H.tip("Gamepad", "Das input-Modul unterstützt auch Gamepads: Binde Aktionen an Knopf-Codes wie JOY_BUTTON_A oder JOY_DPAD_LEFT, oder lies einen Analogstick mit INPUT_JOY_AXIS(slot, \"left_x\"). So funktioniert dieselbe Spiellogik mit Tastatur UND Controller, ohne den Code zu ändern."),

  H.h2("Flanken: „genau in DIESEM Frame“"),
  H.p("KEYPRESSED und MOUSEBUTTON melden „wird gehalten“ – für einen Klick ist das fast nie gemeint. Die folgenden Befehle liefern die FLANKE, also den einen Frame, in dem sich etwas ändert. Dafür brauchst du weder das input-Modul noch eigene Buchführung."),
  H.warn("Die Namen sind historisch", "KEYPRESSED und MOUSEBUTTON heißen so, seit es GameBasic gibt, und melden weiterhin „gehalten“. Die Flanken-Varianten haben deshalb eigene Namen: KEYHIT und MOUSE_HIT."),
  H.cmd("KEYHIT · KEYRELEASED · KEYREPEAT", 'KEYHIT(taste)   KEYRELEASED(taste)   KEYREPEAT(taste)',
    "KEYHIT ist TRUE in dem Frame, in dem die Taste gedrückt wird, KEYRELEASED beim Loslassen. KEYREPEAT feuert zusätzlich mit der System-Wiederholrate, solange die Taste gehalten wird – genau das Verhalten, das man beim Tippen oder in Mengen-Eingaben erwartet.",
    [
      'IF KEYHIT(KEY_SPACE) THEN springe()          \' einmal pro Druck',
      'IF KEYRELEASED(KEY_SPACE) THEN sprung_kappen()',
      'IF KEYREPEAT(KEY_BACKSPACE) THEN text = LEFT$(text, LEN(text) - 1)',
    ]),
  H.cmd("MOUSE_HIT · MOUSE_RELEASED", 'MOUSE_HIT(n)   MOUSE_RELEASED(n)',
    "Dasselbe für die Maustasten (0 = links, 1 = rechts, 2 = mitte). Ein Klick ist damit ein Ereignis und kein Zustand mehr – ohne das zählt ein gehaltener Knopf in jedem Frame erneut.",
    [
      'IF MOUSE_HIT(0) THEN schiesse()',
      'IF MOUSE_RELEASED(0) THEN ziehen_beenden()',
    ]),
  H.cmd("KEY_ANY_HIT · KEY_NAME$", 'KEY_ANY_HIT()   KEY_NAME$(code)',
    "Das Paar für einen Belegungsdialog („Drücke eine Taste …“): KEY_ANY_HIT liefert den Code der zuletzt gedrückten Taste (-1 = keine), KEY_NAME$ den Anzeigenamen dazu. Sondertasten bekommen einen sprechenden Namen (LEER, LINKS, UMSCHALT, F5 …), druckbare Tasten den Namen des aktuellen Tastaturlayouts.",
    [
      'DIM code AS INTEGER',
      'code = KEY_ANY_HIT()',
      'IF code <> -1 THEN',
      '    PRINT "Belegt mit: " + KEY_NAME$(code)',
      '    sprung_taste = code',
      'END IF',
    ]),
  H.p("Für Umschalt, Strg, Alt sowie den Navigations- und Ziffernblock gibt es eigene Konstanten: KEY_LSHIFT / KEY_RSHIFT, KEY_LCTRL / KEY_RCTRL, KEY_LALT / KEY_RALT, KEY_LSUPER / KEY_RSUPER, KEY_CAPSLOCK, KEY_INSERT, KEY_DELETE, KEY_HOME, KEY_END, KEY_PAGEUP, KEY_PAGEDOWN sowie KEY_KP0 bis KEY_KP9 mit KEY_KP_ENTER, KEY_KP_PLUS, KEY_KP_MINUS, KEY_KP_MULTIPLY, KEY_KP_DIVIDE und KEY_KP_PERIOD."),
  H.code([
    'IF KEYPRESSED(KEY_LSHIFT) THEN tempo = 5.0 ELSE tempo = 2.5   \' Sprint',
  ]),

  H.h2("Maus-Feinheiten"),
  H.cmd("MOUSE_DELTA_X · MOUSE_DELTA_Y", 'MOUSE_DELTA_X()   MOUSE_DELTA_Y()',
    "Die Bewegung SEIT dem letzten Frame. Bei gefangenem Zeiger (MOUSE_LOCK) stehen MOUSEX/MOUSEY still – nur das Delta bewegt sich noch. Das ist die Grundlage jeder Maus-Blick-Steuerung.",
    [
      'MOUSE_LOCK(TRUE)',
      'blick_x = blick_x + MOUSE_DELTA_X() * 0.2',
      'blick_y = CLAMP(blick_y + MOUSE_DELTA_Y() * 0.2, -80.0, 80.0)',
    ]),
  H.cmd("MOUSEWHEEL_X · MOUSEWHEEL_Y", 'MOUSEWHEEL_X()   MOUSEWHEEL_Y()',
    "Das Mausrad in BEIDEN Achsen und als Kommazahl. MOUSEWHEEL liefert nur die senkrechte Achse ganzzahlig – ein waagerechtes Rad (viele Mäuse, jedes Touchpad) und feine Touchpad-Schritte fallen darin weg.",
    [
      'scroll_x = scroll_x + MOUSEWHEEL_X() * 20.0',
      'zoom = zoom + MOUSEWHEEL_Y() * 0.1',
    ]),
  H.cmd("MOUSE_SET_POS · MOUSE_ON_SCREEN · MOUSE_HIDDEN", 'MOUSE_SET_POS(x, y)   MOUSE_ON_SCREEN()   MOUSE_HIDDEN()',
    "MOUSE_SET_POS setzt den Zeiger (z. B. zum Zentrieren bei Maus-Blick). MOUSE_ON_SCREEN sagt, ob er über dem Fenster steht – praktisch, um das Spiel zu pausieren, wenn er es verlässt. MOUSE_HIDDEN fragt ab, ob der Cursor gerade versteckt ist.",
    [
      'MOUSE_SET_POS(SCREENWIDTH() \\ 2, SCREENHEIGHT() \\ 2)',
      'IF NOT MOUSE_ON_SCREEN() THEN pausiere()',
    ]),
  H.cmd("MOUSE_CURSOR", 'MOUSE_CURSOR(form$)',
    "Wechselt den Systemcursor. Erlaubt sind \"default\", \"hand\", \"ibeam\", \"crosshair\", \"resize_ew\", \"resize_ns\", \"resize_nwse\", \"resize_nesw\", \"resize_all\" und \"not_allowed\". Eine Hand über Knöpfen macht eine Oberfläche sofort runder.",
    [
      'IF ueber_knopf THEN MOUSE_CURSOR("hand") ELSE MOUSE_CURSOR("default")',
    ]),

  H.h2("Gamepad direkt abfragen"),
  H.p("Das input-Modul nimmt dir die Zuordnung ab; manchmal willst du das Pad aber direkt lesen – etwa für eine Anzeige „Controller verbunden“ oder einen Belegungsdialog."),
  H.cmd("JOYSTICK_COUNT · JOYSTICK_NAME · JOYSTICK_AXIS_COUNT", 'JOYSTICK_COUNT()   JOYSTICK_NAME(idx)   JOYSTICK_AXIS_COUNT(idx)',
    "Wie viele Pads sind angeschlossen, wie heißen sie, und wie viele Achsen haben sie? Der Index zählt ab 0.",
    [
      'IF JOYSTICK_COUNT() > 0 THEN PRINT "Pad: " + JOYSTICK_NAME(0)',
    ]),
  H.cmd("JOYSTICK_BUTTON · JOYSTICK_HIT · JOYSTICK_RELEASED", 'JOYSTICK_BUTTON(idx, knopf)   JOYSTICK_HIT(idx, knopf)   JOYSTICK_RELEASED(idx, knopf)',
    "Gehalten, gerade gedrückt, gerade losgelassen – dieselbe Dreiteilung wie bei der Tastatur. Als Knopf-Nummern dienen die JOY_BUTTON_-Konstanten.",
    [
      'IF JOYSTICK_HIT(0, JOY_BUTTON_A) THEN springe()',
    ]),
  H.cmd("JOYSTICK_AXIS · JOYSTICK_HAT_X · JOYSTICK_HAT_Y", 'JOYSTICK_AXIS(idx, achse)   JOYSTICK_HAT_X(idx)   JOYSTICK_HAT_Y(idx)',
    "JOYSTICK_AXIS liefert eine Analogachse zwischen -1.0 und +1.0 (Achse 0/1 = linker Stick, 2/3 = rechter). HAT_X/HAT_Y geben das Steuerkreuz als -1, 0 oder +1.",
    [
      'px = px + JOYSTICK_AXIS(0, 0) * 4.0',
      'IF JOYSTICK_HAT_X(0) = -1 THEN menue_links()',
    ]),
  H.cmd("JOYSTICK_ANY_BUTTON · JOYSTICK_MAPPINGS · JOYSTICK_RUMBLE", 'JOYSTICK_ANY_BUTTON()   JOYSTICK_MAPPINGS(db$)   JOYSTICK_RUMBLE(idx, links, rechts, ms)',
    "JOYSTICK_ANY_BUTTON liefert den zuletzt gedrückten Knopf (-1 = keiner) – das Gegenstück zu KEY_ANY_HIT für Belegungsdialoge. JOYSTICK_MAPPINGS lädt Zeilen aus der SDL-GameControllerDB nach, damit auch exotische Pads richtig belegt sind. JOYSTICK_RUMBLE lässt das Pad vibrieren (Stärke je 0.0–1.0).",
    [
      'JOYSTICK_RUMBLE(0, 0.6, 0.6, 200)      \' kurzer Treffer-Impuls',
    ]),

  H.h2("Touch & Gesten"),
  H.p("Auf Touchgeräten (und am Desktop näherungsweise mit der Maus) kannst du einzelne Finger verfolgen oder gleich fertige Gesten abfragen."),
  H.cmd("TOUCH_COUNT · TOUCH_X · TOUCH_Y · TOUCH_ID", 'TOUCH_COUNT()   TOUCH_X(i)   TOUCH_Y(i)   TOUCH_ID(i)',
    "Wie viele Finger liegen auf, und wo? TOUCH_ID liefert eine über Frames hinweg stabile Kennung für denselben Finger – nur damit kannst du eine Bewegung verfolgen, denn der Index i kann sich ändern, wenn ein anderer Finger losgelassen wird.",
    [
      'DIM i AS INTEGER',
      'FOR i = 0 TO TOUCH_COUNT() - 1',
      '    CIRCLE(INT(TOUCH_X(i)), INT(TOUCH_Y(i)), 20, RGB(255, 92, 162))',
      'NEXT',
    ]),
  H.cmd("GESTURE$", 'GESTURE$()',
    "Liefert die erkannte Geste als NAMEN statt als Zahl: \"tap\", \"doubletap\", \"hold\", \"drag\", \"swipe_left\", \"swipe_right\", \"swipe_up\", \"swipe_down\", \"pinch_in\", \"pinch_out\" – oder \"\", wenn gerade keine erkannt wird.",
    [
      'SELECT CASE GESTURE$()',
      '    CASE "swipe_left"  : naechste_seite()',
      '    CASE "swipe_right" : vorige_seite()',
      '    CASE "pinch_out"   : zoom = zoom * 1.1',
      'END SELECT',
    ]),
  H.cmd("GESTURE_DRAG_X/Y/ANGLE · GESTURE_PINCH_X/Y/ANGLE · GESTURE_HOLD_TIME", 'GESTURE_DRAG_X()   GESTURE_DRAG_Y()   GESTURE_DRAG_ANGLE()   GESTURE_PINCH_X()   GESTURE_PINCH_Y()   GESTURE_PINCH_ANGLE()   GESTURE_HOLD_TIME()',
    "Die Einzelheiten zur laufenden Geste: Richtung und Winkel eines Zugs, Abstand und Winkel beim Auf-/Zuziehen, und wie lange schon gehalten wird (in Sekunden).",
    [
      'IF GESTURE$() = "hold" AND GESTURE_HOLD_TIME() > 1.0 THEN kontextmenue()',
    ]),

  H.h2("Eingabe aufzeichnen und abspielen"),
  H.p("Die Runtime kann den Eingabe-Zustand jedes Frames mitschreiben – Tasten, Maus, Rad, Gamepad, Touch – und ihn später wieder einspeisen. Das Spiel merkt davon nichts: KEYPRESSED, MOUSEX und Co. liefern während der Wiedergabe die aufgezeichneten Werte. Drei Dinge werden damit möglich: ein Demo-Modus, der sich selbst spielt; Fehlerberichte, die man nachspielen kann; und automatische Spieltests."),
  H.cmd("AUTOMATION_RECORD · AUTOMATION_STOP", 'AUTOMATION_RECORD(datei$)   AUTOMATION_STOP()',
    "AUTOMATION_RECORD startet die Aufnahme, AUTOMATION_STOP beendet sie, schreibt die Datei und liefert die Anzahl aufgezeichneter Ereignisse. Aufnahme und Wiedergabe schließen sich gegenseitig aus.",
    [
      'IF KEYHIT(KEY_F9) THEN',
      '    IF AUTOMATION_RECORDING() THEN',
      '        PRINT "gespeichert: " + STR$(AUTOMATION_STOP())',
      '    ELSE',
      '        AUTOMATION_RECORD("aufnahme.txt")',
      '    END IF',
      'END IF',
    ]),
  H.cmd("AUTOMATION_PLAY", 'AUTOMATION_PLAY(datei$)',
    "Lädt eine Aufnahme und spielt sie ab dem nächsten Frame ab; liefert die Anzahl geladener Ereignisse. Die Wiedergabe endet von selbst nach dem letzten Ereignis.",
    [
      'IF KEYHIT(KEY_F10) THEN AUTOMATION_PLAY("aufnahme.txt")',
    ]),
  H.cmd("AUTOMATION_RECORDING · AUTOMATION_PLAYING · AUTOMATION_FRAME · AUTOMATION_COUNT", 'AUTOMATION_RECORDING()   AUTOMATION_PLAYING()   AUTOMATION_FRAME()   AUTOMATION_COUNT()',
    "Der Zustand für die Anzeige: läuft gerade eine Aufnahme oder Wiedergabe, bei welchem Frame ist die Wiedergabe, und wie viele Ereignisse umfasst sie.",
    [
      'IF AUTOMATION_PLAYING() THEN',
      '    TEXT(10, 10, "DEMO  Frame " + STR$(AUTOMATION_FRAME()))',
      'END IF',
    ]),
  H.warn("Aufgezeichnet wird die EINGABE, nicht der Spielablauf", "Die Wiedergabe drückt nur dieselben Tasten zur selben Zeit. Damit dasselbe herauskommt, muss der Rest gleich sein: Startzustand zurücksetzen, Zufall mit festem Startwert (RANDOMIZE 12345) festnageln und pro Frame statt pro Sekunde rechnen – die Wiedergabe zählt in Frames, mit DELTA()-basierter Bewegung ergibt dieselbe Aufnahme bei anderer Bildrate eine leicht andere Bahn."),
  H.note("Ein Ereignis aus Aufnahme-Frame N wirkt im Programmdurchlauf N+1: eingespeist wird am Ende des FLIP, direkt nachdem die echte Eingabe gelesen wurde. Vollständige Demo: examples/153_automation.gb."),
];
