module.exports = (H) => [
  H.chapter("Sound"),
  H.p("Klang macht ein Spiel erst rund: ein Münz-Ploppen, ein Laser-Zischen, treibende Hintergrundmusik. Drachenhauch spielt kurze Soundeffekte und längere Musikstücke ab und kann Töne sogar selbst erzeugen, ohne dass du eine Audiodatei mitliefern musst. Klang kann man im Buch natürlich nicht abdrucken – aber man kann zeigen, was man dazu baut: Dieses Kapitel entwickelt ein kleines, anklickbares Klavier."),
  H.figure("46_sound.png", "Das Mini-Klavier aus diesem Kapitel: Acht Tasten (1 bis 8) spielen die Töne der C-Dur-Tonleiter."),

  H.h2("Sounddateien laden & abspielen"),
  H.cmd("LOADSOUND · PLAYSOUND · STOPSOUND", 'LOADSOUND(pfad$)   PLAYSOUND(sound[, loops[, lautstärke]])   STOPSOUND(sound)',
    "LOADSOUND lädt einen kurzen Effekt (WAV/OGG) und liefert ein SOUND. PLAYSOUND spielt ihn ab – mit optionaler Wiederholungszahl (loops, 0 = einmal) und Lautstärke (0.0–1.0). STOPSOUND hält ihn an. Lade Sounds einmalig vor dem Game-Loop.",
    [
      'DIM muenze AS SOUND',
      'muenze = LOADSOUND("assets/coin.wav")',
      '',
      'IF eingesammelt THEN PLAYSOUND(muenze)',
    ]),
  H.cmd("PLAYMUSIC", 'PLAYMUSIC(pfad$[, loops[, lautstärke]])',
    "Spielt ein längeres Musikstück, das gestreamt statt komplett geladen wird (OGG/MP3 und sogar Tracker-Module .mod/.xm für echten Retro-Sound). loops = -1 bedeutet Endlosschleife (Standard).",
    [
      'PLAYMUSIC("assets/level1.ogg", -1, 0.7)   \' endlos, 70% laut',
    ]),

  H.h2("Töne selbst erzeugen: das audio-Modul"),
  H.p("Mit dem Modul audio synthetisiert Drachenhauch Klänge zur Laufzeit – kein einziges Sounddatei nötig. AUDIO_TONE erzeugt einen Ton einer bestimmten Frequenz; das Ergebnis ist ein SOUND, den du wie gewohnt mit PLAYSOUND abspielst. Die Frequenz (in Hertz) bestimmt die Tonhöhe: 440 Hz ist das Kammerton-A."),
  H.cmd("AUDIO_TONE", 'AUDIO_TONE(frequenz, dauer_ms[, wellenform$[, lautstärke]])',
    "Erzeugt einen Ton der angegebenen Frequenz (Hz) und Dauer (ms). Die Wellenform (\"sine\", \"square\", \"saw\", \"triangle\") prägt den Klangcharakter – \"square\" klingt nach Retro-Spielkonsole. Liefert ein SOUND.",
    [
      'IMPORT "audio"',
      'PLAYSOUND(AUDIO_TONE(440, 300))            \' A, 0,3 s, Sinuston',
      'PLAYSOUND(AUDIO_TONE(800, 80, "square", 0.5))   \' kurzer Laser',
    ]),
  H.cmd("AUDIO_NOISE · AUDIO_SFX", 'AUDIO_NOISE(dauer_ms[, vol])   AUDIO_SFX(...)',
    "AUDIO_NOISE erzeugt Rauschen (Explosionen, Schritte, Wind). AUDIO_SFX ist ein vollwertiger Retro-Soundeffekt-Synth (Tonhöhen-Slide, Hüllkurve, Vibrato) – am bequemsten mit dem Editor dhsfx erzeugt, der fertige AUDIO_SFX-Aufrufe ausgibt.",
    [
      'IMPORT "audio"',
      'PLAYSOUND(AUDIO_NOISE(150))                \' kurzes Rauschen',
    ]),

  H.h2("Das Klavier zusammenbauen"),
  H.p("Jetzt setzen wir die Teile zusammen. Wir legen die acht Frequenzen der C-Dur-Tonleiter in ein Array, zeichnen für jede eine Taste und spielen den passenden Ton, wenn die zugehörige Zifferntaste gedrückt wird. So sieht das ganze Programm aus:"),
  H.code([
    'IMPORT "audio"',
    'SCREEN(480, 320, "Mini-Klavier")',
    '',
    'DIM hz[8] AS INTEGER          \' C-Dur: C D E F G A H C',
    'hz[0]=262 : hz[1]=294 : hz[2]=330 : hz[3]=349',
    'hz[4]=392 : hz[5]=440 : hz[6]=494 : hz[7]=523',
    '',
    'WHILE NOT QUITREQUESTED()',
    '    CLS(RGB(26, 28, 40))',
    '    DIM i AS INTEGER',
    '    FOR i = 0 TO 7',
    '        DIM x AS INTEGER',
    '        x = 30 + i * 53',
    '        BOX(x, 60, x + 46, 250, RGB(238, 240, 245))   \' Taste',
    '        \' Taste 1..8 gedrückt? -> Ton spielen',
    '        IF KEYPRESSED(KEY_1 + i) THEN',
    '            BOX(x + 2, 62, x + 44, 248, RGB(120, 200, 255))',
    '            PLAYSOUND(AUDIO_TONE(hz[i], 200, "square", 0.4))',
    '        END IF',
    '    NEXT',
    '    FLIP()',
    'WEND',
  ]),
  H.p("Der Trick mit KEY_1 + i nutzt aus, dass die Zifferntasten-Konstanten der Reihe nach liegen: KEY_1 + 0 ist Taste 1, KEY_1 + 1 ist Taste 2, und so weiter. So deckt eine einzige Schleife alle acht Tasten ab."),
  H.warn("Erzeugst du sehr viele Töne (etwa in einer langen Melodie-Schleife), summieren sich die Klang-Puffer im Speicher. Gib nicht mehr benötigte Töne mit UNLOADSOUND wieder frei, um den Speicher schlank zu halten."),

  H.h2("Lautstärke, Stereo & mehr"),
  H.p("Das audio-Modul kann weit mehr, als hier gezeigt: einzelne Kanäle in der Lautstärke regeln (AUDIO_VOLUME) oder im Stereobild verschieben (AUDIO_PAN), getrennte Lautstärke-Busse für Effekte und Musik (AUDIO_BUS_VOLUME) sowie Echtzeit-Effekte wie Hall, Echo oder Filter pro Bus. Für die meisten Spiele reichen LOADSOUND/PLAYSOUND und PLAYMUSIC – die feineren Werkzeuge findest du in der Modul-Dokumentation."),
  H.cmd("STOPMUSIC · AUDIO_SOUND_COUNT", 'STOPMUSIC()   AUDIO_SOUND_COUNT()',
    "STOPMUSIC beendet die laufende Musik (etwa beim Szenenwechsel). AUDIO_SOUND_COUNT sagt, wie viele Klänge gerade geladen sind – nützlich beim Aufräumen langer Spielsitzungen.",
    [
      'IF neues_level THEN STOPMUSIC() : PLAYMUSIC("musik/level2.ogg")',
    ]),
  H.tip("Sound-Werkzeuge", "Eigene Soundeffekte bastelst du am schnellsten im Editor dhsfx (er exportiert fertige AUDIO_SFX-Aufrufe), und ganze Musikstücke baust du im Tracker. Beide gehören zum Drachenhauch-Werkzeugkasten rund um den Sound."),
  H.h2("Speicher wieder freigeben"),
  H.cmd("UNLOADSOUND", "UNLOADSOUND(s)",
    "Hält den Sound an und gibt seinen Puffer frei. Für ein Spiel mit einer Handvoll Geräuschen braucht man das nie – die bleiben geladen und das ist richtig so. Nötig wird es, wenn ein Programm über die Zeit immer neue Klänge erzeugt oder lädt, etwa ein Musikwerkzeug: Dort summieren sich die Puffer sonst auf.",
    [
      "DIM s AS SOUND",
      's = LOADSOUND("treffer.wav")',
      "PLAYSOUND(s)",
      "UNLOADSOUND(s)",
    ]),
  H.warn("Der Index bleibt danach gültig, aber ein erneutes Abspielen wirft einen Fehler. Das ist Absicht: Ein stiller Fehlschlag wäre ein Geräusch, das ohne Erklärung ausbleibt – und danach sucht man lange.",
    "Nach dem Freigeben"),
];
