module.exports = (H) => [
  H.chapter("Layer, Sprite-Atlas & Bulk-Draws"),
  H.p("Dieses Kapitel sammelt drei Techniken für aufgeräumte und schnelle Grafik: Layer ordnen das Gezeichnete in Ebenen (Hintergrund hinten, HUD vorne), ein Sprite-Atlas bündelt viele Bilder in einer Textur und zeichnet sie gebündelt, und die Bulk-Befehle zeichnen hunderte gleichartige Formen in einem einzigen Aufruf."),
  H.figure("47_layer.png", "Eine geschichtete Szene: Sternenfeld (PLOTS) und Planeten (CIRCLES) als Bulk-Draws, HUD-Leiste auf der obersten Ebene."),

  H.h2("Ebenen: Layer"),
  H.p("Normalerweise überdeckt später Gezeichnetes das Frühere. Layer befreien dich von dieser strikten Reihenfolge: Du zeichnest auf benannte Ebenen mit einem z-Wert, und beim FLIP werden alle Ebenen von hinten (kleines z) nach vorne (großes z) übereinandergelegt. So bleibt dein HUD immer vorne, egal wann du es zeichnest."),
  H.cmd("LAYER_DEFINE · LAYER", 'LAYER_DEFINE(name$, z)   LAYER(name$)',
    "LAYER_DEFINE registriert eine Ebene mit ihrer Tiefe z (klein = hinten). LAYER schaltet das Zeichenziel auf diese Ebene um – alle folgenden Zeichenbefehle landen dort, bis du auf eine andere Ebene wechselst.",
    [
      'LAYER_DEFINE("bg", 0)',
      'LAYER_DEFINE("hud", 100)',
      '',
      'LAYER("bg")    : CLS(RGB(20, 24, 40))   \' hinten',
      'LAYER("hud")   : TEXT(10, 10, "Punkte: 0")  \' vorne',
      'FLIP()         \' legt bg und hud in z-Reihenfolge übereinander',
    ]),
  H.cmd("LAYER_END · LAYER_CLEAR", 'LAYER_END()   LAYER_CLEAR(name$)',
    "LAYER_END schaltet zurück auf das Haupt-Bild (FLIP macht das ohnehin automatisch). LAYER_CLEAR leert eine einzelne Ebene von Hand – selten nötig, da FLIP nach dem Zusammenlegen alle Ebenen leert.",
    [
      'LAYER("bg") : DRAWIMAGE(himmel, 0, 0)',
      'LAYER_END()                 \' zurück zum Hauptbild',
    ]),

  H.h2("Viele Sprites aus einer Textur: der Sprite-Atlas"),
  H.p("Ein Sprite-Atlas ist ein großes Bild, in dem viele kleine Sprites liegen, plus eine Liste, welcher Name zu welchem Ausschnitt gehört. Das spart Speicher und macht das Zeichnen vieler Sprites schnell. Den Atlas beschreibst du in einer JSON-Datei:"),
  H.code([
    '// hero_atlas.json',
    '{',
    '  "image": "hero.png",',
    '  "sprites": {',
    '    "stand":  [0,  0, 32, 32],',
    '    "walk_a": [32, 0, 32, 32],',
    '    "walk_b": [64, 0, 32, 32]',
    '  }',
    '}',
  ]),
  H.cmd("ATLAS_LOAD · ATLAS_DRAW", 'ATLAS_LOAD(manifest$)   ATLAS_DRAW(atlas, name$, x, y)',
    "ATLAS_LOAD lädt das Manifest und liefert einen SPRITE_ATLAS. ATLAS_DRAW zeichnet das benannte Sub-Sprite bei (x, y).",
    [
      'DIM atlas AS SPRITE_ATLAS',
      'atlas = ATLAS_LOAD("assets/hero_atlas.json")',
      'CLS()',
      'ATLAS_DRAW(atlas, "stand", 100, 80)',
      'FLIP()',
    ]),
  H.cmd("ATLAS_DRAW_FLIPPED", 'ATLAS_DRAW_FLIPPED(atlas, name$, x, y[, flipX[, flipY]])',
    "Zeichnet ein Sub-Sprite gespiegelt: flipX waagerecht, flipY senkrecht (jeweils TRUE/FALSE). Klassisch für Lauf-Animationen – nur die nach rechts blickende Variante liegt im Atlas, nach links wird per flipX abgeleitet.",
    [
      'DIM blicktLinks AS BOOLEAN',
      'blicktLinks = TRUE',
      'ATLAS_DRAW_FLIPPED(atlas, "walk_a", x, y, blicktLinks, FALSE)',
    ]),
  H.cmd("BATCH_DRAW · BATCH_FLUSH", 'BATCH_DRAW(atlas, name$, x, y)   BATCH_FLUSH()',
    "Für sehr viele Sprites aus demselben Atlas: BATCH_DRAW sammelt sie in einer Warteschlange, BATCH_FLUSH zeichnet sie alle in EINEM gebündelten Aufruf – deutlich schneller als hunderte Einzel-Draws. (FLIP und ein Layer-Wechsel lösen den Batch automatisch aus.)",
    [
      'DIM r AS INTEGER',
      'DIM c AS INTEGER',
      'FOR r = 0 TO 19',
      '    FOR c = 0 TO 29',
      '        BATCH_DRAW(atlas, "stand", c * 16, r * 16)',
      '    NEXT',
      'NEXT',
      'BATCH_FLUSH()    \' alle 600 in einem Rutsch',
    ]),

  H.h2("Hunderte Formen auf einmal: Bulk-Draws"),
  H.p("Willst du sehr viele gleichartige Formen zeichnen – ein Sternenfeld, eine Punktwolke, ein Partikelregen –, ist eine Schleife mit einzelnen PLOT-Aufrufen langsam. Die Bulk-Befehle nehmen stattdessen ganze Arrays an Koordinaten und zeichnen alles in einem einzigen Aufruf. Die Farbe ist entweder eine Zahl (alle gleich) oder ein Array (eine Farbe pro Form)."),
  H.cmd("PLOTS", 'PLOTS(xs, ys, farbe)',
    "Zeichnet viele Pixel auf einmal. xs und ys sind gleich lange Arrays mit den Koordinaten. Ideal für Sternenfelder und Punktwolken.",
    [
      'DIM xs[3] AS INTEGER',
      'DIM ys[3] AS INTEGER',
      'xs[0]=10 : xs[1]=50 : xs[2]=90',
      'ys[0]=20 : ys[1]=40 : ys[2]=60',
      'PLOTS(xs, ys, WHITE)',
    ]),
  H.cmd("CIRCLES · BOXES · LINES", 'CIRCLES(xs, ys, rs, farbe)   BOXES(x1s, y1s, x2s, y2s, farbe)   LINES(x1s, y1s, x2s, y2s, farbe)',
    "Die Bulk-Varianten von CIRCLE, BOX und LINE: Jeder Parameter ist ein Array, und alle Formen werden in einem Aufruf gezeichnet. CIRCLES braucht zusätzlich ein Array der Radien.",
    [
      'DIM cx[2] AS INTEGER',
      'DIM cy[2] AS INTEGER',
      'DIM cr[2] AS INTEGER',
      'cx[0]=80  : cy[0]=80  : cr[0]=20',
      'cx[1]=200 : cy[1]=120 : cr[1]=35',
      'CIRCLES(cx, cy, cr, RGB(90, 140, 220))',
    ]),
  H.tip("Wann Bulk?", "Für eine Handvoll Formen sind die normalen Befehle (CIRCLE, BOX …) völlig in Ordnung und lesbarer. Die Bulk-Varianten lohnen sich erst bei vielen hundert oder tausend gleichartigen Formen pro Frame – dann sparen sie spürbar Zeit."),
];
