module.exports = (H) => [
  H.chapter("3D-Grafik"),
  H.p("Drachenhauch kann nicht nur flache 2D-Bilder, sondern auch echte 3D-Welten zeichnen – mit dem Modul g3d. Dazu kommt eine dritte Koordinate hinzu: z (Tiefe). Eine virtuelle Kamera blickt von einem Punkt im Raum auf ein Ziel, und du platzierst Körper wie Würfel, Kugeln und Zylinder an beliebigen Stellen. Dieses Kapitel zeigt die Grundbausteine; 3D ist ein großes Thema, in das du hier nur den ersten Blick wirfst."),
  H.figure("48_3d.png", "Eine einfache 3D-Szene: Boden-Raster, Würfel (mit Drahtgitter), Kugel, Zylinder und Kegel."),
  H.note("3D läuft – wie der ganze Teil IV – nur im dhrt-Fenster. Der Aufbau ist wie in 2D: im Game-Loop CLS, dann zeichnen, dann FLIP. Nur kommt am Anfang jedes Frames die Kamera dazu, und alle Befehle stammen aus dem Modul g3d (IMPORT \"g3d\")."),

  H.h2("Die Kamera"),
  H.cmd("CAMERA3D", 'CAMERA3D(px, py, pz, tx, ty, tz, fov)',
    "Setzt die Kamera für diesen Frame: Sie steht am Punkt (px, py, pz) und blickt auf das Ziel (tx, ty, tz). fov ist der Blickwinkel in Grad (z. B. 45). Diesen Aufruf machst du als Erstes im 3D-Teil jedes Frames – noch vor den Körpern.",
    [
      'IMPORT "g3d"',
      'SCREEN(480, 320)',
      'WHILE NOT QUITREQUESTED()',
      '    CLS(RGB(16, 22, 34))',
      '    CAMERA3D(7.0, 5.5, 9.0,  0.0, 0.5, 0.0,  45.0)',
      '    \' ... 3D-Körper zeichnen ...',
      '    FLIP()',
      'WEND',
    ]),
  H.note("Eine kreisende Kamera baust du, indem du ihre Position über die Zeit mit SIN/COS berechnest: cx = COS(t) * radius, cz = SIN(t) * radius, und t pro Frame erhöhst. So umrundet der Blick das Geschehen."),

  H.h2("Orientierung: das Boden-Raster"),
  H.cmd("GRID3D", 'GRID3D(linien, abstand)',
    "Zeichnet ein Gitter in der Bodenebene – sehr hilfreich, um sich im Raum zu orientieren. linien ist die Anzahl der Linien pro Richtung, abstand ihr Abstand.",
    [
      'GRID3D(16, 1.0)        \' 16x16 Raster, 1 Einheit Abstand',
    ]),

  H.h2("Körper zeichnen"),
  H.p("Die Grundkörper bekommen ihre Position als (x, y, z) und ihre Maße, dann eine Farbe. Zu jedem gefüllten Körper gibt es meist eine Drahtgitter-Variante (…_WIRES), die nur die Kanten zeichnet – schön, um Konturen zu betonen."),
  H.cmd("CUBE · CUBE_WIRES", 'CUBE(x, y, z, breite, höhe, tiefe, farbe)   CUBE_WIRES(...)',
    "Zeichnet einen Quader am Mittelpunkt (x, y, z) mit den drei Kantenlängen. CUBE füllt, CUBE_WIRES zeichnet nur das Drahtgitter (gut kombinierbar: erst CUBE, dann CUBE_WIRES in dunkler Farbe).",
    [
      'CUBE(0.0, 1.0, 0.0,  2.0, 2.0, 2.0,  RED)',
      'CUBE_WIRES(0.0, 1.0, 0.0,  2.0, 2.0, 2.0,  BLACK)',
    ]),
  H.cmd("SPHERE · SPHERE_WIRES", 'SPHERE(x, y, z, radius, farbe)   SPHERE_WIRES(...)',
    "Zeichnet eine Kugel mit Mittelpunkt (x, y, z) und dem Radius.",
    [
      'SPHERE(4.0, 1.0, 0.0,  1.0,  BLUE)',
    ]),
  H.cmd("CYLINDER", 'CYLINDER(x, y, z, radius_oben, radius_unten, höhe, farbe)',
    "Zeichnet einen Zylinder. Mit unterschiedlichen Radien wird er ein Kegelstumpf; setzt du radius_oben auf 0, entsteht ein spitzer Kegel.",
    [
      'CYLINDER(-4.0, 0.0, 0.0,  0.8, 0.8, 2.5,  GREEN)   \' Zylinder',
      'CYLINDER(0.0, 0.0, -4.0,  0.0, 1.2, 2.2,  YELLOW)  \' Kegel',
    ]),
  H.cmd("PLANE · LINE3D · POINT3D", 'PLANE(x, y, z, größe_x, größe_z, farbe)   LINE3D(x1,y1,z1, x2,y2,z2, farbe)   POINT3D(x, y, z, farbe)',
    "PLANE zeichnet eine flache Fläche in der Bodenebene, LINE3D eine Linie zwischen zwei Raumpunkten, POINT3D einen einzelnen Punkt. Gut für Böden, Achsen und Markierungen.",
    [
      'PLANE(0.0, 0.0, 0.0,  10.0, 10.0,  RGB(40, 60, 40))',
      'LINE3D(0.0, 0.0, 0.0,  0.0, 3.0, 0.0,  WHITE)   \' Y-Achse',
    ]),

  H.h2("Die Kamera abfragen und steuern"),
  H.cmd("CAMERA3D_X/Y/Z · CAMERA3D_TARGET_X/Y/Z", 'CAMERA3D_X()   CAMERA3D_Y()   CAMERA3D_Z()   CAMERA3D_TARGET_X()   CAMERA3D_TARGET_Y()   CAMERA3D_TARGET_Z()',
    "Liefern, wo die Kamera steht und worauf sie blickt. Das brauchst du ständig: für den Ursprung eines eigenen Strahls, für Entfernungsberechnungen (was ist nah genug zum Einsammeln?) oder um der Kamera weich zu folgen.",
    [
      'DIM abstand AS FLOAT',
      'abstand = SQR((CAMERA3D_X() - px) ^ 2 + (CAMERA3D_Z() - pz) ^ 2)',
    ]),
  H.cmd("CAMERA3D_UPDATE", 'CAMERA3D_UPDATE(modus)',
    "Schaltet eine fertige Kamerasteuerung ein: 1 = frei, 2 = orbital (umkreist das Ziel), 3 = Ego-Perspektive, 4 = Verfolger. Der Aufruf gehört einmal pro Frame in den Loop und verarbeitet Maus und Tasten selbst.",
    [
      'WHILE NOT QUITREQUESTED()',
      '    CAMERA3D_UPDATE(2)          \' Maus umkreist das Ziel',
      '    CLS(RGB(12, 16, 24))',
      '    GRID3D(20, 1.0)',
      '    FLIP()',
      'WEND',
    ]),

  H.h2("Eigene Formen: Meshes und Modelle"),
  H.p("Ein MODEL ist eine wiederverwendbare Form, die einmal erzeugt und dann beliebig oft gezeichnet wird – anders als CUBE oder SPHERE, die bei jedem Aufruf neu aufgebaut werden. Entweder lädst du eine Datei oder lässt eine Form berechnen."),
  H.cmd("LOADMODEL · MODEL · MODEL_EX · MODEL_WIRES", 'LOADMODEL(pfad$)   MODEL(m, x, y, z[, skala[, tint]])   MODEL_EX(m, x,y,z, ax,ay,az, winkel, skala, tint)   MODEL_WIRES(m, x, y, z[, skala[, tint]])',
    "LOADMODEL lädt eine OBJ- oder GLTF-Datei. MODEL zeichnet sie an einer Position, MODEL_EX zusätzlich um eine frei wählbare Achse (ax, ay, az) um winkel Grad gedreht – Skalierung und Farbe sind dort Pflichtangaben. MODEL_WIRES zeichnet nur das Drahtgitter (gut zum Fehlersuchen).",
    [
      'DIM baum AS INTEGER',
      'baum = LOADMODEL("assets/baum.glb")',
      'MODEL(baum, 2.0, 0.0, -3.0, 1.0, WHITE)',
      'MODEL_EX(baum, 5.0, 0.0, 0.0, 0.0, 1.0, 0.0, 45.0, 1.0, WHITE)',
    ]),
  H.cmd("MESH_CUBE · MESH_SPHERE · MESH_CYLINDER · MESH_PLANE", 'MESH_CUBE(b, h, t)   MESH_SPHERE(radius, ringe, segmente)   MESH_CYLINDER(radius, hoehe, segmente)   MESH_PLANE(b, t, unterteilungen_x, unterteilungen_z)',
    "Erzeugen Standardformen ohne Datei. Mehr Ringe/Segmente bedeuten eine rundere Form, aber auch mehr Rechenarbeit.",
    [
      'DIM kugel AS INTEGER',
      'kugel = MESH_SPHERE(1.0, 16, 16)',
      'MODEL(kugel, 0.0, 1.0, 0.0, 1.0, RGB(220, 80, 80))',
    ]),
  H.cmd("MESH_TORUS · MESH_KNOT · MESH_HEIGHTMAP", 'MESH_TORUS(radius, dicke, seiten, ringe)   MESH_KNOT(radius, dicke, seiten, ringe)   MESH_HEIGHTMAP(bild, breite, hoehe, tiefe)',
    "TORUS ist ein Ring, KNOT ein verschlungener Kleeblattknoten (schönes Demo-Objekt). MESH_HEIGHTMAP baut aus einem Graustufenbild ein Gelände: Helligkeit wird zu Höhe – kombiniert mit GENTEX_PERLIN entsteht in zwei Zeilen eine Landschaft.",
    [
      'DIM karte AS IMAGE',
      'karte = GENTEX_PERLIN(64, 64, 4.0)',
      'DIM gelaende AS INTEGER',
      'gelaende = MESH_HEIGHTMAP(karte, 32.0, 4.0, 32.0)',
      'MODEL(gelaende, -16.0, 0.0, -16.0, 1.0, RGB(90, 140, 80))',
    ]),
  H.cmd("MODEL_TEXTURE · MODEL_TEXTURE_NORMAL", 'MODEL_TEXTURE(m, bild)   MODEL_TEXTURE_NORMAL(m, bild)',
    "MODEL_TEXTURE legt ein Bild als Oberfläche auf das Modell. MODEL_TEXTURE_NORMAL fügt eine Normal-Map hinzu – eine Zusatzkarte, die dem Licht Unebenheiten vortäuscht (Fugen, Nieten, Rinde), ohne dass die Form mehr Dreiecke bekommt. Sie wirkt nur mit eingeschalteter Beleuchtung.",
    [
      'DIM rinde AS IMAGE',
      'rinde = LOADIMAGE("assets/rinde.png")',
      'MODEL_TEXTURE(baum, rinde)',
    ]),

  H.h2("Skelett-Animation"),
  H.p("Geriggte Modelle (GLTF oder IQM) bringen Animationen mit – Gehen, Rennen, Winken. Drachenhauch lädt sie als Satz und setzt pro Frame die gewünschte Pose."),
  H.cmd("MODEL_LOAD_ANIMS · MODEL_ANIM_COUNT · MODEL_ANIM_NAME · MODEL_ANIM_FRAMES", 'MODEL_LOAD_ANIMS(pfad$)   MODEL_ANIM_COUNT(satz)   MODEL_ANIM_NAME(satz, i)   MODEL_ANIM_FRAMES(satz, i)',
    "MODEL_LOAD_ANIMS lädt alle Animationen einer Datei und liefert einen Satz. Die drei Abfragen sagen dir, wie viele es sind, wie sie heißen und wie viele Einzelbilder jede hat.",
    [
      'DIM anims AS INTEGER',
      'anims = MODEL_LOAD_ANIMS("assets/robot.glb")',
      'DIM i AS INTEGER',
      'FOR i = 0 TO MODEL_ANIM_COUNT(anims) - 1',
      '    PRINT MODEL_ANIM_NAME(anims, i) + ": " + STR$(MODEL_ANIM_FRAMES(anims, i))',
      'NEXT',
    ]),
  H.cmd("MODEL_ANIMATE · MODEL_ANIMATE_BLEND", 'MODEL_ANIMATE(m, satz, anim, frame)   MODEL_ANIMATE_BLEND(m, satz, anim_a, frame_a, anim_b, frame_b, anteil)',
    "MODEL_ANIMATE setzt die Pose auf ein bestimmtes Einzelbild (der Zähler läuft von selbst um). MODEL_ANIMATE_BLEND mischt zwei Animationen: anteil 0.0 zeigt ganz A, 1.0 ganz B – so wird aus Gehen weich ein Rennen, statt hart umzuschalten.",
    [
      'DIM f AS INTEGER',
      'f = f + 1',
      'MODEL_ANIMATE(held, anims, 0, f)',
      '\' oder weich zwischen Gehen (0) und Rennen (1):',
      'MODEL_ANIMATE_BLEND(held, anims, 0, f, 1, f, tempo)',
    ]),

  H.h2("Beleuchtung"),
  H.p("Ohne Licht sind 3D-Objekte flache Farbflächen. Drachenhauch bringt eine physikalisch basierte Beleuchtung (PBR) für bis zu vier Lichtquellen mit. Wichtig: Ein Modell muss mit MODEL_LIT angemeldet werden, sonst bleibt es unbeleuchtet."),
  H.cmd("LIGHT_ENABLE · LIGHT_AMBIENT · MODEL_LIT", 'LIGHT_ENABLE()   LIGHT_AMBIENT(farbe, staerke)   MODEL_LIT(m)',
    "LIGHT_ENABLE schaltet die Beleuchtung ein (einmal beim Start). LIGHT_AMBIENT setzt das Grundlicht, das überall hinfällt – ohne das sind Schattenseiten pechschwarz; die Stärke skaliert die Farbe (0.0 = aus). MODEL_LIT meldet ein Modell für die Beleuchtung an.",
    [
      'LIGHT_ENABLE()',
      'LIGHT_AMBIENT(RGB(40, 44, 60), 1.0)',
      'MODEL_LIT(gelaende)',
    ]),
  H.cmd("LIGHT_DIRECTIONAL · LIGHT_POINT", 'LIGHT_DIRECTIONAL(dx, dy, dz, farbe)   LIGHT_POINT(x, y, z, farbe)',
    "Ein gerichtetes Licht scheint aus einer Richtung auf die ganze Szene (die Sonne), ein Punktlicht strahlt von einer Position in alle Richtungen (Fackel, Lampe). Beide liefern eine Licht-Nummer für spätere Änderungen.",
    [
      'DIM sonne AS INTEGER',
      'sonne = LIGHT_DIRECTIONAL(-0.5, -1.0, -0.3, RGB(255, 244, 214))',
      'DIM fackel AS INTEGER',
      'fackel = LIGHT_POINT(2.0, 1.5, 0.0, RGB(255, 160, 60))',
    ]),
  H.cmd("LIGHT_SET_POS · LIGHT_SET_COLOR · LIGHT_SET_ENABLED", 'LIGHT_SET_POS(licht, x, y, z)   LIGHT_SET_COLOR(licht, farbe)   LIGHT_SET_ENABLED(licht, an)',
    "Ändern ein bestehendes Licht zur Laufzeit – die Fackel wandert mit dem Spieler mit, die Sonne wechselt zum Abendrot, das Licht geht aus.",
    [
      'LIGHT_SET_POS(fackel, px, py + 1.0, pz)',
      'LIGHT_SET_COLOR(sonne, RGB(255, 140, 60))     \' Abendstimmung',
    ]),
  H.cmd("MODEL_PBR · MODEL_EMISSIVE", 'MODEL_PBR(m, metallisch, rauheit)   MODEL_EMISSIVE(m, farbe, staerke)',
    "MODEL_PBR bestimmt das Material: metallisch von 0.0 (Kunststoff, Holz) bis 1.0 (Chrom), rauheit von 0.0 (spiegelglatt) bis 1.0 (matt). MODEL_EMISSIVE lässt ein Modell selbst leuchten – zusammen mit einem Bloom-Shader ergibt das echtes Neon.",
    [
      'MODEL_PBR(kugel, 1.0, 0.15)                   \' poliertes Metall',
      'MODEL_EMISSIVE(schild, RGB(60, 255, 200), 2.0)',
    ]),
  H.cmd("LIGHT_FOG", 'LIGHT_FOG(farbe, dichte)',
    "Nebel, der mit der Entfernung zunimmt. Er versteckt den harten Rand der Sichtweite und gibt einer Szene sofort Tiefe. Dichte 0.0 schaltet ihn ab.",
    [
      'LIGHT_FOG(RGB(12, 16, 24), 0.04)',
    ]),
  H.cmd("LIGHT_ENV · LIGHT_ENV_HDR · SKYBOX", 'LIGHT_ENV(himmel, boden, staerke)   LIGHT_ENV_HDR(pfad$[, staerke])   SKYBOX(an)',
    "Umgebungslicht: LIGHT_ENV nimmt vereinfacht zwei Farben an (Himmel oben, Boden unten) – Metalle spiegeln sie dann. LIGHT_ENV_HDR lädt stattdessen ein echtes HDR-Panorama und berechnet daraus die Spiegelungen. SKYBOX zeichnet diese Umgebung zusätzlich als sichtbaren Hintergrund.",
    [
      'LIGHT_ENV(RGB(120, 170, 255), RGB(60, 50, 40), 0.6)',
      '\' oder mit echtem Panorama:',
      'LIGHT_ENV_HDR("assets/ibl_env.hdr", 1.0)',
      'SKYBOX(TRUE)',
    ]),

  H.h2("Schatten"),
  H.cmd("SHADOW_ENABLE · SHADOW_AREA · SHADOW_TARGET", 'SHADOW_ENABLE([aufloesung])   SHADOW_AREA(groesse, entfernung)   SHADOW_TARGET(x, y, z)',
    "SHADOW_ENABLE schaltet Schlagschatten ein (höhere Auflösung = schärfere Kanten, mehr Rechenarbeit). Schatten wirft das erste gerichtete Licht; nur mit MODEL_LIT angemeldete Modelle werfen und empfangen sie. SHADOW_AREA legt fest, wie groß der beschattete Bereich ist – zu groß macht die Schatten grob. SHADOW_TARGET verschiebt diesen Bereich, üblicherweise auf den Spieler.",
    [
      'LIGHT_ENABLE()',
      'LIGHT_DIRECTIONAL(-0.5, -1.0, -0.3, WHITE)',
      'SHADOW_ENABLE(2048)',
      'SHADOW_AREA(30.0, 60.0)',
      'SHADOW_TARGET(px, 0.0, pz)      \' folgt dem Spieler',
    ]),

  H.h2("Billboards"),
  H.cmd("BILLBOARD", 'BILLBOARD(bild, x, y, z, groesse, tint)',
    "Zeichnet ein Bild im Raum, das sich IMMER zur Kamera dreht. Der klassische Trick für Bäume, Funken, Rauch oder Gesundheitsbalken über Gegnern – ein Bild statt eines Modells, aus jeder Richtung ansehnlich.",
    [
      'DIM funke AS IMAGE',
      'funke = GENTEX_RADIAL(64, 64, RGB(255, 220, 120), RGB(0, 0, 0))',
      'BLEND_MODE("add")',
      'BILLBOARD(funke, 0.0, 2.0, 0.0, 1.5, WHITE)',
      'BLEND_MODE("alpha")',
    ]),

  H.h2("Anklicken und Treffer prüfen"),
  H.p("Ein Mausklick zeigt auf einen Pixel – im Raum entspricht dem ein Strahl. Die PICK-Befehle schicken diesen Mausstrahl los, die RAY_HIT-Befehle einen selbst gewählten. Alle liefern die Entfernung zum Treffer oder -1, wenn nichts getroffen wurde; der Trefferpunkt ist damit ursprung + richtung · entfernung."),
  H.cmd("PICK_BOX · PICK_SPHERE · PICK_MODEL", 'PICK_BOX(cx, cy, cz, bx, by, bz)   PICK_SPHERE(cx, cy, cz, r)   PICK_MODEL(m, x, y, z[, skala])',
    "Prüfen gegen einen Hüllkörper (Quader, Kugel) oder gegen die tatsächlichen Dreiecke eines Modells. Für „welches Objekt hat der Spieler angeklickt?“ nimmst du das kleinste nicht-negative Ergebnis.",
    [
      'IF MOUSE_HIT(0) AND PICK_SPHERE(0.0, 1.0, 0.0, 1.0) >= 0.0 THEN',
      '    PRINT "Kugel angeklickt"',
      'END IF',
    ]),
  H.cmd("PICK_TRI · PICK_QUAD", 'PICK_TRI(x1,y1,z1, x2,y2,z2, x3,y3,z3)   PICK_QUAD(x1,y1,z1, x2,y2,z2, x3,y3,z3, x4,y4,z4)',
    "Prüfen gegen eine einzelne Fläche statt gegen einen Hüllkörper – für Bodenkacheln, Wandstücke oder frei im Raum schwebende Bedienflächen. Die vier Punkte eines Vierecks müssen REIHUM liegen (im Kreis, nicht über Kreuz). Getroffen wird auch von hinten.",
    [
      'DIM d AS FLOAT',
      'd = PICK_QUAD(x0, 0.0, z0, x0 + 1.0, 0.0, z0, _',
      '              x0 + 1.0, 0.0, z0 + 1.0, x0, 0.0, z0 + 1.0)',
      'IF d >= 0.0 THEN kachel_markieren()',
    ]),
  H.cmd("RAY_HIT_BOX · RAY_HIT_SPHERE · RAY_HIT_MODEL", 'RAY_HIT_BOX(ox,oy,oz, dx,dy,dz, cx,cy,cz, bx,by,bz)   RAY_HIT_SPHERE(ox,oy,oz, dx,dy,dz, cx,cy,cz, r)   RAY_HIT_MODEL(m, ox,oy,oz, dx,dy,dz, px,py,pz[, skala])',
    "Dieselben Tests mit selbst gewähltem Strahl – für Sichtlinien („sieht der Wächter den Spieler?“), Schüsse oder Bodenkontakt. Die Richtung muss nicht auf Länge 1 gebracht werden, die Entfernung kommt trotzdem in Welt-Einheiten zurück.",
    [
      'DIM sicht AS FLOAT',
      'sicht = RAY_HIT_BOX(wx, wy, wz, px - wx, py - wy, pz - wz, _',
      '                    mx, my, mz, 2.0, 3.0, 2.0)',
      'IF sicht < 0.0 THEN PRINT "freie Sicht auf den Spieler"',
    ]),
  H.cmd("RAY_HIT_TRI · RAY_HIT_QUAD", 'RAY_HIT_TRI(ox,oy,oz, dx,dy,dz, <3 Punkte>)   RAY_HIT_QUAD(ox,oy,oz, dx,dy,dz, <4 Punkte>)',
    "Die Flächen-Tests mit eigenem Strahl – etwa um zu prüfen, ob ein Geschoss eine Wandplatte durchschlägt.",
    [
      'IF RAY_HIT_TRI(sx,sy,sz, rx,ry,rz, ax,ay,az, bx,by,bz, cx,cy,cz) >= 0.0 THEN treffer()',
    ]),
  H.cmd("MOUSE_GROUND_X · MOUSE_GROUND_Z · MOUSE_GROUND_HIT", 'MOUSE_GROUND_X(ebene_y)   MOUSE_GROUND_Z(ebene_y)   MOUSE_GROUND_HIT(ebene_y)',
    "Wohin zeigt die Maus auf dem Boden? Diese drei rechnen den Mausstrahl auf eine waagerechte Ebene um – die Grundlage jeder Aufbau- oder Strategiespiel-Steuerung. MOUSE_GROUND_HIT ist FALSE, wenn der Strahl die Ebene gar nicht trifft (Blick zum Himmel).",
    [
      'IF MOUSE_GROUND_HIT(0.0) THEN',
      '    CUBE(MOUSE_GROUND_X(0.0), 0.5, MOUSE_GROUND_Z(0.0), 1.0, 1.0, 1.0, YELLOW)',
      'END IF',
    ]),
  H.cmd("WORLD_TO_SCREEN_X · WORLD_TO_SCREEN_Y · SCREEN_TO_WORLD_DIR_X/Y/Z", 'WORLD_TO_SCREEN_X(wx, wy, wz)   WORLD_TO_SCREEN_Y(wx, wy, wz)   SCREEN_TO_WORLD_DIR_X(sx, sy)   SCREEN_TO_WORLD_DIR_Y(sx, sy)   SCREEN_TO_WORLD_DIR_Z(sx, sy)',
    "Der Weg in beide Richtungen: WORLD_TO_SCREEN rechnet eine 3D-Position auf Bildschirm-Pixel um – so setzt du ein Namensschild oder einen Lebensbalken über eine Figur (dafür zeichnest du nach dem 3D-Teil ganz normal in 2D). SCREEN_TO_WORLD_DIR liefert umgekehrt die Blickrichtung durch einen Bildschirmpunkt; der Ursprung dieses Strahls ist die Kameraposition.",
    [
      'TEXT(INT(WORLD_TO_SCREEN_X(gx, gy + 2.0, gz)) - 20, _',
      '     INT(WORLD_TO_SCREEN_Y(gx, gy + 2.0, gz)), "Ork")',
    ]),

  H.tip("Klein anfangen", "3D ist mächtig, aber der Einstieg ist anspruchsvoller als 2D. Fang mit einer festen Kamera und ein paar Grundkörpern auf einem Raster an (wie im Bild oben), bring dann Bewegung in die Kamera, und taste dich erst danach an Modelle und Beleuchtung heran. Für die meisten 2D-Spiele brauchst du 3D übrigens gar nicht."),
];
