module.exports = (H) => [
  H.chapter("Abschlussprojekt: Münzfang"),
  H.p("Zum Abschluss bauen wir ein vollständiges kleines Spiel und führen dabei fast alles aus diesem Buch zusammen: den Game-Loop, Variablen und Arrays, Eingabe, framerate-unabhängige Bewegung, Zeichnen, eine Kollisionsprüfung, Sound und ein Punkte-Display. Das Spiel heißt „Münzfang“: Von oben fallen Münzen, und du fängst sie mit einem Korb, den du nach links und rechts bewegst. So sieht das fertige Spiel aus:"),
  H.figure("49_catch.png", "Das fertige Spiel „Münzfang“: fallende Münzen, ein steuerbarer Korb und die Punkteanzeige."),
  H.p("Wir bauen es in fünf Schritten auf. Tippe ruhig mit und probiere nach jedem Schritt aus, was sich tut – so verstehst du jedes Teil."),

  H.h2("Schritt 1: Fenster, Korb und Steuerung"),
  H.p("Zuerst öffnen wir ein Fenster und zeichnen den Korb. Seine x-Position halten wir in einer FLOAT-Variablen (für weiche Bewegung), mit den Pfeiltasten verschieben wir ihn – mal DELTA() für überall gleiches Tempo – und klemmen ihn an den Bildschirmrändern fest."),
  H.code([
    'SCREEN(480, 320, "Münzfang")',
    '',
    'DIM korbx AS FLOAT',
    'korbx = 210.0',
    '',
    'WHILE NOT QUITREQUESTED()',
    '    IF KEYPRESSED(KEY_LEFT)  THEN korbx = korbx - 260.0 * DELTA()',
    '    IF KEYPRESSED(KEY_RIGHT) THEN korbx = korbx + 260.0 * DELTA()',
    '    IF korbx < 0.0   THEN korbx = 0.0',
    '    IF korbx > 420.0 THEN korbx = 420.0',
    '',
    '    CLS(RGB(20, 24, 40))',
    '    BOXROUND(INT(korbx), 290, INT(korbx) + 60, 312, 8, RGB(180, 120, 60))',
    '    FLIP()',
    'WEND',
  ]),
  H.p("Jetzt lässt sich schon ein Korb hin- und herschieben. Beachte INT(korbx): Gezeichnet wird mit ganzen Zahlen, gerechnet aber mit Kommazahlen."),

  H.h2("Schritt 2: Fallende Münzen mit Arrays"),
  H.p("Wir wollen mehrere Münzen gleichzeitig. Statt für jede eigene Variablen zu nehmen, halten wir ihre Werte in Arrays: mx und my für die Position, ms für die Fallgeschwindigkeit. Vor dem Game-Loop füllen wir sie mit Zufallswerten. Im Loop fällt jede Münze nach unten; wer unten herausfällt, taucht oben wieder auf."),
  H.code([
    'CONST ANZAHL AS INTEGER = 6',
    'DIM mx[ANZAHL] AS INTEGER',
    'DIM my[ANZAHL] AS INTEGER',
    'DIM ms[ANZAHL] AS INTEGER',
    '',
    'RANDOMIZE(3)',
    'DIM i AS INTEGER',
    'FOR i = 0 TO ANZAHL - 1',
    '    mx[i] = RANDINT(20, 450)',
    '    my[i] = RANDINT(0, 240)',
    '    ms[i] = RANDINT(90, 170)     \' jede Münze fällt anders schnell',
    'NEXT',
  ]),
  H.p("Im Game-Loop bewegen und zeichnen wir alle Münzen mit einer Schleife:"),
  H.code([
    'FOR i = 0 TO ANZAHL - 1',
    '    my[i] = my[i] + INT(ms[i] * DELTA())',
    '    IF my[i] > 330 THEN          \' unten raus -> neu oben',
    '        my[i] = RANDINT(-90, -10)',
    '        mx[i] = RANDINT(20, 450)',
    '    END IF',
    '    CIRCLE(mx[i], my[i], 10, RGB(255, 205, 40))',
    'NEXT',
  ]),

  H.h2("Schritt 3: Münzen fangen"),
  H.p("Jetzt die eigentliche Spiel-Idee: Berührt eine fallende Münze den Korb, ist sie gefangen. Wir prüfen das in derselben Schleife – ist die Münze auf Korbhöhe (y zwischen 280 und 310) UND liegt ihr x im Bereich des Korbs, dann zählen wir einen Punkt und schicken die Münze wieder nach oben."),
  H.code([
    'IF my[i] > 280 AND my[i] < 310 THEN',
    '    IF mx[i] > INT(korbx) - 10 AND mx[i] < INT(korbx) + 70 THEN',
    '        punkte = punkte + 1',
    '        my[i] = RANDINT(-90, -10)   \' wieder nach oben',
    '        mx[i] = RANDINT(20, 450)',
    '    END IF',
    'END IF',
  ]),
  H.p("Dafür brauchen wir oben noch eine Punkte-Variable: DIM punkte AS INTEGER. Das ist im Kern eine Rechteck-Kollision (Kapitel „2D-Zeichnen“ hat die Koordinaten erklärt) – ein Muster, das in fast jedem Spiel vorkommt."),

  H.h2("Schritt 4: Ein Ton beim Fangen"),
  H.p("Ein Treffer soll sich auch hören lassen. Mit dem audio-Modul erzeugen wir beim Fangen einen kurzen Ton – eine Zeile direkt nach dem Punkte-Zählen:"),
  H.code([
    'IMPORT "audio"        \' ganz oben im Programm',
    '\' ... beim Fangen, direkt nach punkte = punkte + 1:',
    'PLAYSOUND(AUDIO_TONE(880, 90, "square", 0.4))',
  ]),

  H.h2("Schritt 5: Die Punkteanzeige"),
  H.p("Zum Schluss zeigen wir den Punktestand an – mit TEXT, ganz oben ins Bild, nach dem Zeichnen der Münzen und des Korbs:"),
  H.code([
    'TEXT(10, 8, "Punkte: " + STR$(punkte), WHITE)',
    'TEXT(270, 8, "Pfeiltasten: Korb", RGB(150, 160, 190))',
  ]),

  H.h2("Das ganze Spiel"),
  H.p("Hier ist „Münzfang“ komplett – alle Schritte zusammengesetzt. Es ist erstaunlich wenig Code für ein richtiges, spielbares Spiel:"),
  H.code([
    'IMPORT "audio"',
    'SCREEN(480, 320, "Münzfang")',
    '',
    'CONST ANZAHL AS INTEGER = 6',
    'DIM mx[ANZAHL] AS INTEGER',
    'DIM my[ANZAHL] AS INTEGER',
    'DIM ms[ANZAHL] AS INTEGER',
    'RANDOMIZE(3)',
    'DIM i AS INTEGER',
    'FOR i = 0 TO ANZAHL - 1',
    '    mx[i] = RANDINT(20, 450)',
    '    my[i] = RANDINT(0, 240)',
    '    ms[i] = RANDINT(90, 170)',
    'NEXT',
    '',
    'DIM korbx AS FLOAT',
    'korbx = 210.0',
    'DIM punkte AS INTEGER',
    'punkte = 0',
    '',
    'WHILE NOT QUITREQUESTED()',
    '    IF KEYPRESSED(KEY_LEFT)  THEN korbx = korbx - 260.0 * DELTA()',
    '    IF KEYPRESSED(KEY_RIGHT) THEN korbx = korbx + 260.0 * DELTA()',
    '    IF korbx < 0.0   THEN korbx = 0.0',
    '    IF korbx > 420.0 THEN korbx = 420.0',
    '',
    '    FOR i = 0 TO ANZAHL - 1',
    '        my[i] = my[i] + INT(ms[i] * DELTA())',
    '        IF my[i] > 280 AND my[i] < 310 THEN',
    '            IF mx[i] > INT(korbx) - 10 AND mx[i] < INT(korbx) + 70 THEN',
    '                punkte = punkte + 1',
    '                PLAYSOUND(AUDIO_TONE(880, 90, "square", 0.4))',
    '                my[i] = RANDINT(-90, -10)',
    '                mx[i] = RANDINT(20, 450)',
    '            END IF',
    '        END IF',
    '        IF my[i] > 330 THEN',
    '            my[i] = RANDINT(-90, -10)',
    '            mx[i] = RANDINT(20, 450)',
    '        END IF',
    '    NEXT',
    '',
    '    CLS(RGB(20, 24, 40))',
    '    FOR i = 0 TO ANZAHL - 1',
    '        CIRCLE(mx[i], my[i], 10, RGB(255, 205, 40))',
    '    NEXT',
    '    BOXROUND(INT(korbx), 290, INT(korbx) + 60, 312, 8, RGB(180, 120, 60))',
    '    TEXT(10, 8, "Punkte: " + STR$(punkte), WHITE)',
    '    TEXT(270, 8, "Pfeiltasten: Korb", RGB(150, 160, 190))',
    '    FLIP()',
    'WEND',
  ]),

  H.h2("Und jetzt: weiterbauen!"),
  H.p("Dieses kleine Spiel ist erst der Anfang. Mit dem, was du in diesem Buch gelernt hast, kannst du es Stück für Stück zu deinem eigenen Spiel ausbauen. Ein paar Ideen:"),
  H.bullet("Leben statt Endlos-Spiel: Verpasste Münzen kosten ein Leben, bei 0 ist Schluss (Kapitel „Verzweigungen“)."),
  H.bullet("Schwieriger werden: Lass die Münzen mit steigendem Punktestand schneller fallen."),
  H.bullet("Echte Bilder: Ersetze die Kreise und den Korb-Block durch Sprites (Kapitel „Bilder“)."),
  H.bullet("Hintergrundmusik: Spiele mit PLAYMUSIC einen Loop, dazu einen anderen Ton, wenn eine Münze danebengeht."),
  H.bullet("Bonus-Objekte: Lass ab und zu etwas Besonderes fallen, das extra Punkte oder einen Effekt bringt."),
  H.p("Damit endet die Reise durch GameBasic. Du kennst jetzt die Sprache, die eingebauten Befehle und die Werkzeuge für Grafik, Sound und Spiele. Der beste nächste Schritt ist immer derselbe: eine eigene kleine Idee nehmen und sie ausprobieren. Viel Freude beim Programmieren!"),
];
