module.exports = (H) => [
  H.part("Teil V — Die Module"),
  H.chapter("Modul: sprite"),
  H.p("Mit Teil V tauchst du in die mitgelieferten Module ein – fertige Werkzeugkästen für wiederkehrende Spiel-Aufgaben. Jedes holst du mit IMPORT herein (Kapitel „Module importieren“). Den Anfang macht sprite: Es verwandelt ein Spritesheet in eine animierte Spielfigur mit Position, Geschwindigkeit, benannten Animationen, Spiegelung und Kollision – Dinge, die du sonst alle von Hand bauen müsstest."),
  H.figure("50_sprite.png", "Dasselbe animierte Sprite zweimal: links normal, rechts horizontal gespiegelt – beide dreifach skaliert."),
  H.note("Ein Spritesheet ist ein Bild mit mehreren gleich großen Einzelbildern (Frames) nebeneinander. Das Heldenbild hier ist 256×32 Pixel groß und enthält 8 Frames à 32×32 – eine ganze Lauf-Animation."),

  H.h2("Ein Sprite anlegen"),
  H.cmd("SPRITE_NEW", 'SPRITE_NEW(image, frame_breite, frame_höhe)',
    "Erzeugt ein SPRITE aus einem Spritesheet. image ist das ganze Sheet (mit LOADIMAGE geladen), frame_breite × frame_höhe die Größe eines einzelnen Frames. GameBasic teilt das Sheet selbst in Frames auf.",
    [
      'IMPORT "sprite"',
      'DIM sheet AS IMAGE',
      'sheet = LOADIMAGE("assets/hero.png")   \' 256x32',
      'DIM held AS SPRITE',
      'held = SPRITE_NEW(sheet, 32, 32)       \' 8 Frames a 32x32',
    ]),

  H.h2("Position & Bewegung"),
  H.cmd("SPRITE_SET_POS · SPRITE_SET_VELOCITY", 'SPRITE_SET_POS(sp, x, y)   SPRITE_SET_VELOCITY(sp, vx, vy)',
    "SPRITE_SET_POS setzt die Position. SPRITE_SET_VELOCITY gibt eine Geschwindigkeit in Pixeln pro Sekunde vor – das Sprite bewegt sich dann bei jedem SPRITE_UPDATE von selbst weiter (framerate-unabhängig).",
    [
      'SPRITE_SET_POS(held, 100.0, 150.0)',
      'SPRITE_SET_VELOCITY(held, 60.0, 0.0)   \' 60 Pixel/Sek. nach rechts',
    ]),

  H.h2("Animationen"),
  H.p("Eine Animation ist ein benannter Bereich von Frames mit einer Abspielgeschwindigkeit. Du registrierst sie einmal und startest sie dann über den Namen."),
  H.cmd("SPRITE_ADD_ANIM · SPRITE_PLAY", 'SPRITE_ADD_ANIM(sp, name$, erster, letzter, fps)   SPRITE_PLAY(sp, name$)',
    "SPRITE_ADD_ANIM registriert eine Animation von Frame erster bis letzter mit fps Bildern pro Sekunde. SPRITE_PLAY startet sie als Schleife. SPRITE_PLAY ist gefahrlos in jedem Frame aufrufbar – läuft die Animation schon, passiert nichts.",
    [
      'SPRITE_ADD_ANIM(held, "idle", 0, 0, 1.0)    \' nur Frame 0',
      'SPRITE_ADD_ANIM(held, "walk", 0, 7, 10.0)   \' Frames 0-7, 10 fps',
      'SPRITE_PLAY(held, "walk")',
    ]),
  H.cmd("SPRITE_PLAY_ONCE", 'SPRITE_PLAY_ONCE(sp, name$)',
    "Spielt eine Animation genau einmal ab und bleibt am letzten Frame stehen (für Aktionen wie Schlagen oder Springen, die nicht endlos wiederholen sollen).",
    [
      'SPRITE_PLAY_ONCE(held, "punch")',
    ]),

  H.h2("Spiegeln & Skalieren"),
  H.cmd("SPRITE_SET_FLIP", 'SPRITE_SET_FLIP(sp, flipX, flipY)',
    "Spiegelt das Sprite waagerecht (flipX) und/oder senkrecht (flipY). Klassisch: dieselbe Lauf-Animation für beide Richtungen, links per flipX.",
    [
      'SPRITE_SET_FLIP(held, TRUE, FALSE)    \' blickt nach links',
      'SPRITE_SET_FLIP(held, FALSE, FALSE)   \' wieder nach rechts',
    ]),
  H.cmd("SPRITE_SET_SCALE", 'SPRITE_SET_SCALE(sp, sx, sy)',
    "Skaliert die Darstellung. Wichtig: rein visuell – die Kollisionsbox bleibt in Originalgröße (gewollt, z. B. für einen Pop-Effekt beim Einsammeln).",
    [
      'SPRITE_SET_SCALE(held, 3.0, 3.0)   \' dreifach groß',
    ]),

  H.h2("Aktualisieren & Zeichnen"),
  H.cmd("SPRITE_UPDATE · SPRITE_DRAW", 'SPRITE_UPDATE(sp, dt_ms)   SPRITE_DRAW(sp)',
    "SPRITE_UPDATE schreibt Position und Animation fort – dt_ms ist die vergangene Zeit in Millisekunden (ganzzahlig), also INT(DELTA() * 1000). SPRITE_DRAW zeichnet das Sprite an seiner Position (camera-aware).",
    [
      'DIM dt AS INTEGER',
      'dt = INT(DELTA() * 1000.0)',
      'SPRITE_UPDATE(held, dt)',
      'SPRITE_DRAW(held)',
    ]),
  H.cmd("SPRITE_COLLIDES", 'SPRITE_COLLIDES(sp1, sp2)',
    "Liefert TRUE, wenn sich die Boxen zweier Sprites überlappen (AABB-Kollision). Damit prüfst du Treffer zwischen Spieler und Gegner, Geschoss und Ziel und so weiter.",
    [
      'IF SPRITE_COLLIDES(held, gegner) THEN \' getroffen!',
    ]),

  H.h2("Alles zusammen"),
  H.p("So sieht eine typische Sprite-Spielfigur im Game-Loop aus – Richtung per Eingabe, Animation passend dazu, dann aktualisieren und zeichnen:"),
  H.code([
    'IMPORT "sprite"',
    'SCREEN(480, 320)',
    'DIM held AS SPRITE',
    'held = SPRITE_NEW(LOADIMAGE("assets/hero.png"), 32, 32)',
    'SPRITE_ADD_ANIM(held, "idle", 0, 0, 1.0)',
    'SPRITE_ADD_ANIM(held, "walk", 0, 7, 10.0)',
    'SPRITE_SET_POS(held, 220.0, 150.0)',
    '',
    'WHILE NOT QUITREQUESTED()',
    '    DIM vx AS FLOAT',
    '    vx = 0.0',
    '    IF KEYPRESSED(KEY_LEFT)  THEN vx = -80.0 : SPRITE_SET_FLIP(held, TRUE, FALSE)',
    '    IF KEYPRESSED(KEY_RIGHT) THEN vx =  80.0 : SPRITE_SET_FLIP(held, FALSE, FALSE)',
    '    SPRITE_SET_VELOCITY(held, vx, 0.0)',
    '    IF vx <> 0.0 THEN SPRITE_PLAY(held, "walk") ELSE SPRITE_PLAY(held, "idle")',
    '',
    '    SPRITE_UPDATE(held, INT(DELTA() * 1000.0))',
    '    CLS(RGB(28, 32, 50))',
    '    SPRITE_DRAW(held)',
    '    FLIP()',
    'WEND',
  ]),
  H.tip("Sprites selbst zeichnen", "Spritesheets musst du nicht von Hand malen: Der mitgelieferte Pixel-Editor gbsprites zeichnet Frames, Animationen und exportiert fertige Sheets (und sogar Atlas-Manifeste). So schließt sich der Kreis von der Grafik bis ins Spiel."),
];
