module.exports = (H) => [
  H.chapter("Modul: animfsm"),
  H.p("Im sprite-Kapitel hast du Animationen von Hand umgeschaltet (IF vx <> 0 THEN \"walk\" ELSE \"idle\"). Bei vielen Zuständen – stehen, laufen, springen, fallen, angreifen – wird dieses Wenn-Dann schnell unübersichtlich. Das Modul animfsm nimmt dir das ab: Du beschreibst die Zustände und Übergänge einmal in einer Datei, setzt im Spiel nur noch ein paar Parameter (etwa „Tempo“), und die Zustandsmaschine wählt selbst die richtige Animation."),
  H.figure("51_animfsm.png", "Die Zustandsmaschine wählt den Zustand: Weil das Tempo hoch ist, läuft „run“ – ANIM_FSM_STATE zeigt den aktuellen Zustand an."),

  H.h2("Die .gbanim-Datei"),
  H.p("Die Zustandsmaschine wird datengetrieben aus einer .gbanim-Datei geladen (am bequemsten im Editor gbanim gezeichnet). Sie beschreibt drei Dinge: Zustände (jeder an einen Frame-Bereich gebunden), Parameter (Werte, die du im Spiel setzt) und Übergänge (Bedingungen, wann von einem Zustand in einen anderen gewechselt wird). Eine einfache Variante mit zwei Zuständen:"),
  H.code([
    '// held.gbanim',
    '{',
    '  "version": 1,',
    '  "default": "idle",',
    '  "params": [ { "name": "speed", "type": "float", "default": 0.0 } ],',
    '  "states": [',
    '    { "name": "idle", "loop": true, "first": 0, "last": 0, "fps": 2.0 },',
    '    { "name": "run",  "loop": true, "first": 0, "last": 7, "fps": 12.0 }',
    '  ],',
    '  "transitions": [',
    '    { "from": "idle", "to": "run",  "conditions": [{ "param":"speed","op":"gt","value":5.0 }] },',
    '    { "from": "run",  "to": "idle", "conditions": [{ "param":"speed","op":"lt","value":5.0 }] }',
    '  ]',
    '}',
  ]),
  H.note("Übergänge prüfen Parameter mit Operatoren wie gt (größer), lt (kleiner), eq (gleich). Ein from von \"*\" gilt aus JEDEM Zustand (z. B. „springen geht immer“). Mit wait_finished wechselt ein einmaliger Zustand erst, wenn seine Animation durchgelaufen ist."),

  H.h2("Laden & einrichten"),
  H.cmd("ANIM_FSM_LOAD · ANIM_FSM_SETUP", 'ANIM_FSM_LOAD(pfad$)   ANIM_FSM_SETUP(fsm, sprite)',
    "ANIM_FSM_LOAD lädt und prüft die .gbanim-Datei und liefert eine ANIM_FSM (im Default-Zustand). ANIM_FSM_SETUP registriert die Frame-Bereiche aller Zustände als Animationen des Sprites und startet den Default-Zustand. Das Sprite legst du wie gewohnt mit dem sprite-Modul an.",
    [
      'IMPORT "sprite"',
      'IMPORT "animfsm"',
      'DIM held AS SPRITE',
      'held = SPRITE_NEW(LOADIMAGE("assets/hero.png"), 32, 32)',
      'DIM fsm AS ANIM_FSM',
      'fsm = ANIM_FSM_LOAD("assets/held.gbanim")',
      'ANIM_FSM_SETUP(fsm, held)',
    ]),

  H.h2("Parameter setzen & auslösen"),
  H.cmd("ANIM_FSM_SET_FLOAT / _BOOL / _INT", 'ANIM_FSM_SET_FLOAT(fsm, name$, wert)   (auch _BOOL, _INT)',
    "Setzt einen Parameter der Zustandsmaschine. Beim nächsten ANIM_FSM_UPDATE entscheiden die Übergänge anhand dieser Werte über den Zustand.",
    [
      'ANIM_FSM_SET_FLOAT(fsm, "speed", ABS(vx))   \' Tempo melden',
    ]),
  H.cmd("ANIM_FSM_TRIGGER", 'ANIM_FSM_TRIGGER(fsm, name$)',
    "Feuert einen Trigger-Parameter (ein einmaliges Signal, etwa „springen“). Er wird beim nächsten UPDATE einmal ausgewertet und dann automatisch zurückgesetzt.",
    [
      'IF INPUT_PRESSED("jump") THEN ANIM_FSM_TRIGGER(fsm, "jump")',
    ]),

  H.h2("Aktualisieren & abfragen"),
  H.cmd("ANIM_FSM_UPDATE", 'ANIM_FSM_UPDATE(fsm, sprite, dt_ms)',
    "Das Herzstück: schreibt die laufende Animation voran, prüft die Übergänge und schaltet bei Bedarf den Zustand (samt passender Animation). dt_ms ist die vergangene Zeit in Millisekunden. Liefert TRUE zurück, wenn in diesem Frame ein Zustandswechsel passiert ist.",
    [
      'ANIM_FSM_UPDATE(fsm, held, INT(DELTA() * 1000.0))',
    ]),
  H.cmd("ANIM_FSM_STATE · ANIM_FSM_FORCE", 'ANIM_FSM_STATE(fsm)   ANIM_FSM_FORCE(fsm, sprite, state$)',
    "ANIM_FSM_STATE liefert den Namen des aktuellen Zustands (gut zum Anzeigen oder für eigene Logik). ANIM_FSM_FORCE erzwingt einen Zustand ohne Bedingungen – praktisch für Reset oder Respawn.",
    [
      'PRINT ANIM_FSM_STATE(fsm)               \' z. B. "run"',
      'ANIM_FSM_FORCE(fsm, held, "idle")       \' Reset',
    ]),

  H.h2("Im Game-Loop"),
  H.p("Im Spiel meldest du nur noch die Parameter und rufst UPDATE – das ständige Animations-Umschalten von Hand entfällt:"),
  H.code([
    'WHILE NOT QUITREQUESTED()',
    '    DIM vx AS FLOAT',
    '    vx = INPUT_AXIS("links", "rechts") * 80.0',
    '    ANIM_FSM_SET_FLOAT(fsm, "speed", ABS(vx))',
    '    SPRITE_SET_VELOCITY(held, vx, 0.0)',
    '',
    '    DIM dt AS INTEGER',
    '    dt = INT(DELTA() * 1000.0)',
    '    ANIM_FSM_UPDATE(fsm, held, dt)    \' wählt idle/run automatisch',
    '    SPRITE_UPDATE(held, dt)',
    '    CLS(RGB(28, 32, 50))',
    '    SPRITE_DRAW(held)',
    '    FLIP()',
    'WEND',
  ]),
  H.h2("Parameter lesen und weitere Typen"),
  H.cmd("ANIM_FSM_SET_INT · ANIM_FSM_SET_BOOL", 'ANIM_FSM_SET_INT(fsm, name$, wert)   ANIM_FSM_SET_BOOL(fsm, name$, wahr)',
    "Neben Kommazahlen und Auslösern kennt die Zustandsmaschine ganze Zahlen und Wahrheitswerte als Parameter – etwa die Anzahl der Sprünge in einer Kombination oder „steht am Boden“.",
    [
      'ANIM_FSM_SET_BOOL(fsm, "am_boden", CHAR_ON_GROUND(spieler))',
      'ANIM_FSM_SET_INT(fsm, "combo", schlag_nr)',
    ]),
  H.cmd("ANIM_FSM_GET_FLOAT · ANIM_FSM_GET_INT · ANIM_FSM_GET_BOOL", 'ANIM_FSM_GET_FLOAT(fsm, name$)   ANIM_FSM_GET_INT(fsm, name$)   ANIM_FSM_GET_BOOL(fsm, name$)',
    "Lesen einen Parameter zurück – nützlich beim Fehlersuchen, wenn ein Übergang nicht auslöst: einfach den Wert einblenden, den die Zustandsmaschine tatsächlich sieht.",
    [
      'TEXT(10, 10, "tempo=" + STR$(ANIM_FSM_GET_FLOAT(fsm, "tempo")))',
    ]),
  H.tip("Wann lohnt sich animfsm?", "Für eine Figur mit nur zwei Animationen reicht das einfache IF aus dem sprite-Kapitel. Sobald es viele Zustände mit Bedingungen werden (laufen, springen, fallen, landen, treffen …), hält animfsm den Code sauber – und der visuelle Editor gbanim macht das Entwerfen der Zustände zum Kinderspiel."),
];
