module.exports = (H) => [
  H.chapter("Module: physics, physics2d & physics3d"),
  H.p("Drachenhauch bringt drei Physik-Module mit – wähle nach Bedarf: physics ist reine Kollisions-Mathematik ohne eigenen Zustand (du behältst die volle Kontrolle), physics2d und physics3d sind dagegen vollwertige Physik-Engines, die Schwerkraft, Stöße und Reibung selbst berechnen. Dieses Kapitel stellt alle drei vor."),
  H.figure("55_physics2d.png", "physics2d in Aktion: zehn Bälle fallen unter Schwerkraft, prallen ab und sammeln sich – alles von der Engine berechnet."),

  H.h2("physics — Kollisions-Mathematik"),
  H.p("Das Modul physics besteht nur aus reinen Funktionen: Sie rechnen etwas aus und geben ein Ergebnis zurück, ohne sich etwas zu merken. Damit prüfst du Überlappungen, misst Abstände oder lässt einen Ball an einer Wand abprallen – die Bewegung programmierst du selbst. Ideal, wenn du schlanke, vorhersehbare Kontrolle willst."),
  H.cmd("PHYSICS_BOX_BOX · PHYSICS_CIRCLE_CIRCLE", 'PHYSICS_BOX_BOX(x1,y1,w1,h1, x2,y2,w2,h2)   PHYSICS_CIRCLE_CIRCLE(cx1,cy1,r1, cx2,cy2,r2)',
    "Liefern TRUE, wenn sich zwei Rechtecke bzw. zwei Kreise überlappen. PHYSICS_BOX_BOX ist die schnellste Kollisionsprüfung überhaupt – ideal als Spieler-trifft-Gegner-Test.",
    [
      'IMPORT "physics"',
      'PRINT PHYSICS_BOX_BOX(0,0,32,32, 20,20,32,32)',
      'PRINT PHYSICS_BOX_BOX(0,0,32,32, 50,50,32,32)',
    ], { out: ["TRUE", "FALSE"] }),
  H.cmd("PHYSICS_DISTANCE · PHYSICS_LENGTH", 'PHYSICS_DISTANCE(x1,y1, x2,y2)   PHYSICS_LENGTH(vx, vy)',
    "PHYSICS_DISTANCE misst den Abstand zweier Punkte, PHYSICS_LENGTH die Länge eines Vektors. (Für reine Vergleiche „näher als“ gibt es PHYSICS_DISTANCE2 ohne Wurzel – schneller.)",
    [
      'PRINT PHYSICS_DISTANCE(0,0, 3,4)',
      'PRINT PHYSICS_LENGTH(3.0, 4.0)',
    ], { out: ["5.0", "5.0"] }),
  H.cmd("PHYSICS_NORM_X/Y · PHYSICS_REFLECT_X/Y", 'PHYSICS_NORM_X(vx,vy) / _Y   PHYSICS_REFLECT_X(vx,vy, nx,ny) / _Y',
    "NORM liefert die Anteile des auf Länge 1 gebrachten Vektors (Richtung ohne Tempo). REFLECT spiegelt einen Geschwindigkeitsvektor an einer Fläche mit Normale (nx, ny) – das klassische „Ball prallt von der Wand ab“.",
    [
      'PRINT ROUND(PHYSICS_NORM_X(3.0, 4.0), 2); " "; ROUND(PHYSICS_NORM_Y(3.0, 4.0), 2)',
      'PRINT PHYSICS_REFLECT_Y(5.0, 5.0, 0.0, 1.0)   \' am Boden abprallen',
    ], { out: ["0.6 0.8", "-5.0"] }),
  H.note("Es gibt außerdem PHYSICS_BOX_CIRCLE, PHYSICS_POINT_BOX/CIRCLE sowie Strahl-Tests PHYSICS_RAY_BOX/RAY_CIRCLE (für Schüsse und Sichtlinien). Alle sind reine Funktionen – kein Zustand, keine Überraschungen."),

  H.h2("physics2d — echte 2D-Physik"),
  H.p("Während physics nur rechnet, simuliert physics2d eine ganze Welt: Du legst Körper an, gibst eine Schwerkraft vor und rufst pro Frame einen Simulationsschritt – die Engine kümmert sich um Fallen, Stoßen, Stapeln und Abprallen. Praktisch für Sandkästen, Stapel-Puzzles oder alles, was sich glaubwürdig bewegen soll. (Sie nutzt die bewährte Rapier-Physik-Engine.)"),
  H.note("Bildschirm-Konvention: y zeigt nach UNTEN, die Default-Schwerkraft ist (0, 980) – Körper fallen also von selbst nach unten. Box-Maße sind Halb-Extents (die halbe Breite/Höhe).", "Wichtig"),
  H.cmd("PHYS2D_NEW · PHYS2D_SET_GRAVITY", 'PHYS2D_NEW()   PHYS2D_SET_GRAVITY(w, gx, gy)',
    "PHYS2D_NEW erstellt eine Physik-Welt (mit Standard-Schwerkraft nach unten). PHYS2D_SET_GRAVITY ändert die Schwerkraft (gy = 0 für schwerelos, negativ für nach oben).",
    [
      'IMPORT "physics2d"',
      'DIM welt AS PHYS2D_WORLD',
      'welt = PHYS2D_NEW()',
    ]),
  H.cmd("PHYS2D_ADD_BOX · PHYS2D_ADD_CIRCLE", 'PHYS2D_ADD_BOX(w, x, y, hw, hh, dynamisch, bounce)   PHYS2D_ADD_CIRCLE(w, x, y, r, dynamisch, bounce)',
    "Fügen einen Körper hinzu und liefern seine ID. dynamisch = TRUE bewegt sich (fällt, stößt); FALSE ist ein unbeweglicher Körper (Boden, Wand). bounce (0..1) ist die Sprungkraft. Bei der Box sind hw/hh die HALBE Breite und Höhe.",
    [
      'PHYS2D_ADD_BOX(welt, 240, 300, 220, 10, FALSE, 0.2)   \' Boden (statisch)',
      'DIM ball AS INTEGER',
      'ball = PHYS2D_ADD_CIRCLE(welt, 240, 40, 14, TRUE, 0.5) \' Ball (springt)',
    ]),
  H.cmd("PHYS2D_STEP", 'PHYS2D_STEP(w, dt)',
    "Simuliert einen Zeitschritt von dt Sekunden – einmal pro Frame mit DELTA() aufrufen. Erst dadurch bewegt sich überhaupt etwas.",
    [
      'PHYS2D_STEP(welt, DELTA())',
    ]),
  H.cmd("PHYS2D_BODY_X / _Y / _ANGLE", 'PHYS2D_BODY_X(w, id)   PHYS2D_BODY_Y(w, id)   PHYS2D_BODY_ANGLE(w, id)',
    "Lesen Position und Drehwinkel (Radiant) eines Körpers aus – damit zeichnest du dein Sprite an die von der Engine berechnete Stelle (rotiert per DRAWIMAGEROT mit DEG(...)).",
    [
      'DIM x AS INTEGER',
      'DIM y AS INTEGER',
      'x = INT(PHYS2D_BODY_X(welt, ball))',
      'y = INT(PHYS2D_BODY_Y(welt, ball))',
      'CIRCLE(x, y, 14, YELLOW)',
    ]),
  H.p("Im Game-Loop ist das Muster immer gleich: einen Schritt simulieren, dann jeden Körper an seiner aktuellen Position zeichnen. Genau so entstand das Bild oben:"),
  H.code([
    'WHILE NOT QUITREQUESTED()',
    '    PHYS2D_STEP(welt, DELTA())',
    '    CLS(RGB(20, 24, 38))',
    '    CIRCLE(INT(PHYS2D_BODY_X(welt, ball)), INT(PHYS2D_BODY_Y(welt, ball)), 14, YELLOW)',
    '    FLIP()',
    'WEND',
  ]),

  H.cmd("PHYS2D_SET_VEL · PHYS2D_APPLY_IMPULSE · PHYS2D_BODY_VX/VY", 'PHYS2D_SET_VEL(w, id, vx, vy)   PHYS2D_APPLY_IMPULSE(w, id, ix, iy)   PHYS2D_BODY_VX(w, id)   PHYS2D_BODY_VY(w, id)',
    "In die Simulation eingreifen: SET_VEL setzt die Geschwindigkeit hart (Sprung, Katapult), APPLY_IMPULSE gibt einen einmaligen Stoß dazu (Explosion, Schlag), die beiden Getter lesen die aktuelle Geschwindigkeit – etwa um bei hohem Tempo einen Aufprall-Klang zu spielen.",
    [
      'IF INPUT_PRESSED("springen") THEN PHYS2D_SET_VEL(welt, spieler, 0.0, -400.0)',
      'PHYS2D_APPLY_IMPULSE(welt, kiste, 250.0, -120.0)',
      'IF ABS(PHYS2D_BODY_VY(welt, kiste)) > 300.0 THEN PLAYSOUND(rums)',
    ]),
  H.cmd("PHYS2D_SET_POS · PHYS2D_LOCK_ROTATION", 'PHYS2D_SET_POS(w, id, x, y)   PHYS2D_LOCK_ROTATION(w, id, gesperrt)',
    "SET_POS versetzt einen Körper (Wiedereinstieg nach dem Tod, Teleport). LOCK_ROTATION verhindert, dass er sich dreht – genau das braucht eine Spielfigur, die sonst bei jeder Berührung umkippen würde.",
    [
      'PHYS2D_LOCK_ROTATION(welt, spieler, TRUE)',
      'PHYS2D_SET_POS(welt, spieler, 100.0, 50.0)',
    ]),
  H.cmd("PHYS2D_REMOVE · PHYS2D_COUNT", 'PHYS2D_REMOVE(w, id)   PHYS2D_COUNT(w)',
    "Entfernt einen Körper aus der Welt bzw. zählt die vorhandenen. Die Nummern bleiben nach einem REMOVE stabil – eine gemerkte Körper-Nummer zeigt also nie versehentlich auf einen anderen Körper.",
    [
      'PHYS2D_REMOVE(welt, kiste)',
      'PRINT PHYS2D_COUNT(welt)',
    ]),

  H.cmd("PHYS2D_SET_DYNAMIC · PHYS2D_IS_DYNAMIC", 'PHYS2D_SET_DYNAMIC(w, id, dynamisch)   PHYS2D_IS_DYNAMIC(w, id)',
    "Schaltet einen Körper zwischen statisch (unbeweglich, wie eine Wand) und dynamisch (fällt, stößt, rollt) um. Damit steht ein Aufbau erst still und fällt genau dann zusammen, wenn du es willst.",
    [
      "' Turm steht statisch, bis der Ball ihn trifft",
      'IF getroffen THEN PHYS2D_SET_DYNAMIC(welt, stein, TRUE)',
      'PRINT PHYS2D_IS_DYNAMIC(welt, stein)',
    ]),
  H.tip("Erst stellen, dann fallen lassen", "Ein Stapel aus dynamischen Körpern beginnt sofort zu wackeln und sich zurechtzuruckeln, sobald die Welt läuft – bis zum ersten Wurf steht er schief. Baue ihn deshalb statisch auf und schalte die Teile erst beim Treffer auf dynamisch: Dann steht er, bis er soll."),

  H.h2("physics3d — echte 3D-Physik"),
  H.p("physics3d ist das Gegenstück in drei Dimensionen: dieselbe Idee, nur mit z-Achse und 3D-Körpern. Die Körper haben zusätzlich eine räumliche Drehung (als Quaternion), die du beim Zeichnen deines 3D-Modells verwendest. Zusammen mit dem g3d-Modul lassen sich so physikalisch fallende, rollende und stapelnde 3D-Objekte bauen."),
  H.cmd("PHYS3D_NEW · ADD_BOX · ADD_SPHERE · STEP", 'PHYS3D_NEW()   PHYS3D_ADD_BOX(w, x,y,z, hw,hh,hd, dynamisch, bounce)   PHYS3D_ADD_SPHERE(w, x,y,z, r, dynamisch, bounce)   PHYS3D_STEP(w, dt)',
    "Wie bei physics2d, nur mit drei Koordinaten. PHYS3D_NEW erstellt die 3D-Welt, ADD_BOX/ADD_SPHERE fügen Körper hinzu (dynamisch TRUE/FALSE), PHYS3D_STEP simuliert einen Schritt.",
    [
      'IMPORT "physics3d"',
      'DIM w AS PHYS_WORLD',
      'w = PHYS3D_NEW()',
      'PHYS3D_ADD_BOX(w, 0.0, -1.0, 0.0, 10.0, 1.0, 10.0, FALSE, 0.0)  \' Boden',
      'DIM kugel AS INTEGER',
      'kugel = PHYS3D_ADD_SPHERE(w, 0.0, 8.0, 0.0, 1.0, TRUE, 0.5)     \' fällt',
      'PHYS3D_STEP(w, DELTA())',
    ]),
  H.cmd("PHYS3D_BODY_X / _Y / _Z (+ Quaternion)", 'PHYS3D_BODY_X(w, id)   PHYS3D_BODY_Y(w, id)   PHYS3D_BODY_Z(w, id)   PHYS3D_BODY_QX/_QY/_QZ/_QW(w, id)',
    "Lesen die 3D-Position und die Drehung (als Quaternion QX/QY/QZ/QW) eines Körpers. Position und Drehung steckst du in eine Modell-Matrix (Modul m3d) und zeichnest damit dein 3D-Modell an die simulierte Stelle.",
    [
      'DIM y AS FLOAT',
      'y = PHYS3D_BODY_Y(w, kugel)',
      'PRINT ROUND(y, 1)   \' sinkt mit der Zeit',
    ]),

  H.cmd("PHYS3D_SET_GRAVITY · PHYS3D_SET_VEL · PHYS3D_APPLY_IMPULSE", 'PHYS3D_SET_GRAVITY(w, gx, gy, gz)   PHYS3D_SET_VEL(w, id, vx, vy, vz)   PHYS3D_APPLY_IMPULSE(w, id, ix, iy, iz)',
    "Dieselben Eingriffe wie in 2D, nur mit drei Achsen. Die Schwerkraft lässt sich jederzeit ändern – für Mondlandung, Unterwasser-Abschnitte oder einen Schwerkraft-Umkehr-Schalter.",
    [
      "PHYS3D_SET_GRAVITY(w, 0.0, -1.6, 0.0)      ' Mond statt Erde",
      'PHYS3D_APPLY_IMPULSE(w, kiste, 0.0, 8.0, 0.0)',
    ]),
  H.cmd("PHYS3D_SET_POS · PHYS3D_REMOVE · PHYS3D_COUNT", 'PHYS3D_SET_POS(w, id, x, y, z)   PHYS3D_REMOVE(w, id)   PHYS3D_COUNT(w)',
    "Versetzen, entfernen, zählen – wie in 2D, und ebenso mit stabilen Körper-Nummern.",
    [
      'PHYS3D_SET_POS(w, spieler, 0.0, 5.0, 0.0)',
      'PRINT PHYS3D_COUNT(w)',
    ]),

  H.cmd("COLLIDES", 'COLLIDES(x1, y1, w1, h1, x2, y2, w2, h2)',
    "Der einfachste Treffer-Test überhaupt und ohne IMPORT verfügbar: überlappen sich zwei Rechtecke? Angegeben werden jeweils die linke obere Ecke sowie Breite und Höhe. Für die meisten 2D-Spiele – Schuss trifft Gegner, Spieler berührt Münze – reicht genau das.",
    [
      'PRINT COLLIDES(0, 0, 10, 10, 5, 5, 10, 10)',
      'PRINT COLLIDES(0, 0, 10, 10, 20, 0, 10, 10)',
    ], { out: ["TRUE", "FALSE"] }),

  H.h2("Linien und Flächen"),
  H.cmd("PHYSICS_LINES_HIT · PHYSICS_LINES_X · PHYSICS_LINES_Y", 'PHYSICS_LINES_HIT(ax,ay, bx,by, cx,cy, dx,dy)   PHYSICS_LINES_X(...)   PHYSICS_LINES_Y(...)',
    "Schneiden sich zwei STRECKEN? Der klassische Fall für Laser gegen Wand oder Sichtlinie gegen Hindernis. Die beiden anderen liefern den Schnittpunkt – aber nur, wenn es einen gibt: sonst kommt NAN zurück, frage also erst PHYSICS_LINES_HIT.",
    [
      'IF PHYSICS_LINES_HIT(0.0,0.0, 10.0,10.0, 0.0,10.0, 10.0,0.0) THEN',
      '    PRINT PHYSICS_LINES_X(0.0,0.0, 10.0,10.0, 0.0,10.0, 10.0,0.0)',
      'END IF',
    ], { out: ["5.0"] }),
  H.cmd("PHYSICS_POINT_LINE · PHYSICS_CIRCLE_LINE", 'PHYSICS_POINT_LINE(px,py, ax,ay, bx,by, dicke)   PHYSICS_CIRCLE_LINE(cx,cy,r, ax,ay, bx,by)',
    "Liegt ein Punkt auf einer Strecke (mit einer Toleranz für die Klickgenauigkeit)? Und trifft ein Kreis eine Strecke – Ball gegen Schläger, Geschoss gegen Wand?",
    [
      'PRINT PHYSICS_POINT_LINE(5.0, 5.2, 0.0,0.0, 10.0,10.0, 1.0)',
      'PRINT PHYSICS_CIRCLE_LINE(5.0, 7.0, 3.0, 0.0,5.0, 10.0,5.0)',
    ], { out: ["TRUE", "TRUE"] }),
  H.cmd("PHYSICS_POINT_TRI · PHYSICS_POINT_POLY · PHYSICS_POINT_CIRCLE", 'PHYSICS_POINT_TRI(px,py, ax,ay, bx,by, cx,cy)   PHYSICS_POINT_POLY(px, py, xs, ys)   PHYSICS_POINT_CIRCLE(px, py, cx, cy, r)',
    "Punkt in einem Dreieck, in einem beliebigen Polygon oder in einem Kreis. PHYSICS_POINT_POLY nimmt die Ecken als zwei gleich lange Arrays und funktioniert auch bei einwärts gebogenen (konkaven) Formen – damit sind unregelmäßige Klickflächen und Zonen-Karten möglich.",
    [
      'PRINT PHYSICS_POINT_TRI(1.0, 1.0, 0.0,0.0, 10.0,0.0, 0.0,10.0)',
      'PRINT PHYSICS_POINT_CIRCLE(3.0, 4.0, 0.0, 0.0, 5.1)',
    ], { out: ["TRUE", "TRUE"] }),
  H.cmd("PHYSICS_RAY_CIRCLE · PHYSICS_SPHERE_SPHERE · PHYSICS_DISTANCE3", 'PHYSICS_RAY_CIRCLE(rx,ry, dx,dy, cx,cy, r)   PHYSICS_SPHERE_SPHERE(x1,y1,z1,r1, x2,y2,z2,r2)   PHYSICS_DISTANCE3(x1,y1,z1, x2,y2,z2)',
    "PHYSICS_RAY_CIRCLE schickt einen Strahl gegen einen Kreis (Entfernung oder -1). Die beiden anderen sind die 3D-Gegenstücke zu CIRCLE_CIRCLE und DISTANCE – Kugel gegen Kugel und Abstand im Raum, ohne dass du eine ganze Physik-Welt aufsetzen musst.",
    [
      'PRINT PHYSICS_SPHERE_SPHERE(0.0,0.0,0.0, 1.0, 1.5,0.0,0.0, 1.0)',
      'PRINT PHYSICS_DISTANCE3(0.0,0.0,0.0, 1.0,2.0,2.0)',
    ], { out: ["TRUE", "3.0"] }),

  H.h2("Viele Objekte prüfen: die Broadphase"),
  H.p("Prüfst du jedes Objekt gegen jedes andere, wächst der Aufwand quadratisch – bei 500 Geschossen sind das schon 125 000 Vergleiche pro Frame. Die Broadphase sortiert die Objekte vorher in ein Raster und liefert nur die Paare, die sich überhaupt nahe kommen."),
  H.cmd("PHYSICS_BROAD_NEW · PHYSICS_BROAD_ADD · PHYSICS_BROAD_CLEAR · PHYSICS_BROAD_COUNT", 'PHYSICS_BROAD_NEW()   PHYSICS_BROAD_ADD(b, x, y, r)   PHYSICS_BROAD_CLEAR(b)   PHYSICS_BROAD_COUNT(b)',
    "Eine Broadphase anlegen und pro Frame neu befüllen: leeren, dann jeden Kreis (Mittelpunkt und Radius) eintragen. PHYSICS_BROAD_ADD liefert die Nummer, unter der das Objekt in den Paaren auftaucht – trage in derselben Reihenfolge wie deine eigene Objektliste ein, dann passt die Zuordnung.",
    [
      'DIM broad AS PHYSICS_BROAD',
      'broad = PHYSICS_BROAD_NEW()',
      '',
      'PHYSICS_BROAD_CLEAR(broad)',
      'DIM i AS INTEGER',
      'FOR i = 0 TO n - 1',
      '    PHYSICS_BROAD_ADD(broad, x[i], y[i], 8.0)',
      'NEXT',
    ]),
  H.cmd("PHYSICS_BROAD_QUERY · PHYSICS_BROAD_PAIR_COUNT · PHYSICS_BROAD_PAIR_A · PHYSICS_BROAD_PAIR_B", 'PHYSICS_BROAD_QUERY(b)   PHYSICS_BROAD_PAIR_COUNT(b)   PHYSICS_BROAD_PAIR_A(b, i)   PHYSICS_BROAD_PAIR_B(b, i)',
    "QUERY berechnet die möglichen Paare, danach holst du sie einzeln ab. Das Ergebnis ist eine VORAUSWAHL: Die Paare sind nah beieinander, den genauen Treffer prüfst du weiterhin selbst (etwa mit PHYSICS_CIRCLE_CIRCLE) – nur eben für ein paar Dutzend statt für alle Kombinationen.",
    [
      'PHYSICS_BROAD_QUERY(broad)',
      'DIM p AS INTEGER',
      'FOR p = 0 TO PHYSICS_BROAD_PAIR_COUNT(broad) - 1',
      '    DIM a AS INTEGER',
      '    DIM b AS INTEGER',
      '    a = PHYSICS_BROAD_PAIR_A(broad, p)',
      '    b = PHYSICS_BROAD_PAIR_B(broad, p)',
      '    IF PHYSICS_CIRCLE_CIRCLE(x[a],y[a],8.0, x[b],y[b],8.0) THEN treffer(a, b)',
      'NEXT',
    ]),
  H.tip("Welches Physik-Modul?", "Für simple Treffer-Abfragen und selbst gesteuerte Bewegung reicht physics (schnell, vorhersehbar). Soll sich etwas „echt“ anfühlen – fallen, stapeln, abprallen – nimm physics2d bzw. physics3d. Du kannst beides mischen: die Engine für die Welt, physics-Mathe für eigene Sonderfälle."),
];
