module.exports = (H) => [
  H.chapter("Modul: gui"),
  H.p("Das gui-Modul ist das Gegenstück zum ui-Modul: Statt jeden Frame neu aufgebauter Bedienelemente verwaltet es persistente Fenster mit Widgets – verschiebbar an der Titelleiste, überlappend, mit Z-Reihenfolge und Schließen-Knopf, fast wie auf einem Desktop. Du baust Fenster und Widgets EINMAL vor dem Game-Loop auf; danach rufst du pro Frame nur noch GUI_UPDATE (Maus/Tasten verarbeiten) und GUI_DRAW (zeichnen) und fragst Ereignisse per Polling ab."),
  H.figure("59_gui.png", "Ein verschiebbares gui-Fenster mit Titelleiste, Label, Checkbox, Slider und Button (Cyan-Theme)."),

  H.h2("Fenster & Widgets anlegen"),
  H.p("Ein Fenster erstellst du mit GUI_WINDOW; die Widgets bekommen es als ersten Parameter und liegen mit ihren Koordinaten RELATIV zum Fenster-Inhalt. Jeder Konstruktor liefert ein Handle (GUI_WINDOW bzw. GUI_WIDGET), das du dir merkst, um es später abzufragen."),
  H.cmd("GUI_WINDOW", 'GUI_WINDOW(titel$, x, y, w, h)',
    "Legt ein Fenster mit Titelleiste an (per Maus an der Leiste verschiebbar). Liefert ein GUI_WINDOW-Handle.",
    [
      'IMPORT "gui"',
      'DIM win AS GUI_WINDOW',
      'win = GUI_WINDOW("Einstellungen", 90, 50, 300, 210)',
    ]),
  H.cmd("GUI_LABEL · GUI_BUTTON", 'GUI_LABEL(win, text$, x, y[, farbe])   GUI_BUTTON(win, text$, x, y, w, h)',
    "Fügen dem Fenster ein Text-Label bzw. einen Knopf hinzu (Koordinaten relativ zum Fenster). Beide liefern ein GUI_WIDGET-Handle.",
    [
      'GUI_LABEL(win, "Optionen", 20, 16, RGB(255, 220, 120))',
      'DIM start AS GUI_WIDGET',
      'start = GUI_BUTTON(win, "Spiel starten", 20, 140, 130, 32)',
    ]),
  H.cmd("GUI_CHECKBOX · GUI_SLIDER", 'GUI_CHECKBOX(win, label$, x, y[, default])   GUI_SLIDER(win, x, y, w, min, max[, default])',
    "Fügen eine Checkbox bzw. einen Schieberegler hinzu. Ihren Zustand fragst du später per Polling ab (siehe unten).",
    [
      'DIM snd AS GUI_WIDGET',
      'snd = GUI_CHECKBOX(win, "Sound an", 20, 60, TRUE)',
      'DIM vol AS GUI_WIDGET',
      'vol = GUI_SLIDER(win, 20, 100, 250, 0.0, 1.0, 0.7)',
    ]),

  H.h2("Pro Frame: aktualisieren & zeichnen"),
  H.cmd("GUI_UPDATE · GUI_DRAW", 'GUI_UPDATE()   GUI_DRAW()',
    "GUI_UPDATE verarbeitet Maus und Tastatur (Hover, Klick, Fenster-Ziehen, Fokus, Z-Reihenfolge) und muss VOR GUI_DRAW und den Polling-Abfragen stehen. GUI_DRAW zeichnet alle Fenster von hinten nach vorne.",
    [
      'WHILE NOT QUITREQUESTED()',
      '    GUI_UPDATE()        \' zuerst',
      '    CLS(RGB(24, 28, 44))',
      '    GUI_DRAW()',
      '    FLIP()',
      'WEND',
    ]),

  H.h2("Ereignisse abfragen (Polling)"),
  H.cmd("GUI_CLICKED · GUI_CHECKED · GUI_VALUE", 'GUI_CLICKED(widget)   GUI_CHECKED(widget)   GUI_VALUE(widget)',
    "GUI_CLICKED liefert TRUE im Frame, in dem ein Button geklickt wurde. GUI_CHECKED gibt den Zustand einer Checkbox, GUI_VALUE den Wert eines Sliders. Diese Abfragen stehen nach GUI_UPDATE.",
    [
      'IF GUI_CLICKED(start) THEN',
      '    \' Spiel starten',
      'END IF',
      'DIM an AS BOOLEAN',
      'an = GUI_CHECKED(snd)',
      'DIM lautstaerke AS FLOAT',
      'lautstaerke = GUI_VALUE(vol)',
    ]),

  H.h2("Baumansicht (Tree)"),
  H.p("Eine Baumansicht zeigt hierarchische Daten mit aufklappbaren Knoten – ideal für einen Level-Browser, eine Datei-/Ordnerstruktur oder einen Szenegraph-Inspektor."),
  H.cmd("GUI_TREE · GUI_TREE_ADD", 'GUI_TREE(win, x, y, w, h)   GUI_TREE_ADD(tree, parent, label$)',
    "GUI_TREE legt eine leere Baumansicht an. GUI_TREE_ADD hängt einen Knoten an – parent = -1 für einen Wurzelknoten, sonst die id eines bestehenden Knotens. Liefert die neue Knoten-id (stabil bis GUI_TREE_CLEAR).",
    [
      'IMPORT "gui"',
      'DIM win AS GUI_WINDOW',
      'win = GUI_WINDOW("Baum", 20, 20, 300, 220)',
      'DIM tree AS GUI_WIDGET',
      'tree = GUI_TREE(win, 10, 30, 260, 160)',
      'DIM welt AS INTEGER',
      'welt = GUI_TREE_ADD(tree, -1, "Welt 1")',
      'DIM lvl1 AS INTEGER',
      'lvl1 = GUI_TREE_ADD(tree, welt, "Level 1-1")',
    ]),
  H.cmd("GUI_TREE_EXPAND · GUI_TREE_LABEL", 'GUI_TREE_EXPAND(tree, node, an: BOOLEAN)   GUI_TREE_LABEL(tree, node) AS STRING',
    "GUI_TREE_EXPAND klappt einen Knoten auf oder zu (nur aufgeklappte Knoten zeigen ihre Kinder). GUI_TREE_LABEL liest den Beschriftungstext eines Knotens.",
    [
      'GUI_TREE_EXPAND(tree, welt, TRUE)',
      'PRINT GUI_TREE_LABEL(tree, lvl1)',
    ], { out: ["Level 1-1"] }),
  H.cmd("GUI_TREE_SELECTED · GUI_TREE_SET_SELECTED", 'GUI_TREE_SELECTED(tree) AS INTEGER   GUI_TREE_SET_SELECTED(tree, node)',
    "GUI_TREE_SELECTED liefert die id des vom Nutzer angeklickten Knotens (-1 = keine Auswahl). GUI_TREE_SET_SELECTED setzt die Auswahl programmatisch, z. B. um einen zuletzt geöffneten Level vorzumarkieren.",
    [
      'GUI_TREE_SET_SELECTED(tree, lvl1)',
      'PRINT GUI_TREE_SELECTED(tree)',
    ], { out: ["1"] }),
  H.cmd("GUI_TREE_CLEAR", 'GUI_TREE_CLEAR(tree)',
    "Entfernt alle Knoten (z. B. um die Baumansicht mit einer neu geladenen Ordnerstruktur neu zu befüllen). Setzt auch die Auswahl zurück.",
    [
      'GUI_TREE_CLEAR(tree)',
      'PRINT GUI_TREE_SELECTED(tree)',
    ], { out: ["-1"] }),

  H.h2("Menüleiste & Kontextmenü"),
  H.p("GUI_MENU baut die klassische Menüleiste oben im Fenster (\"Datei\", \"Bearbeiten\", …), GUI_CONTEXT ein Kontextmenü, das per Rechtsklick im Fenster erscheint. Beide bekommen ihre Einträge über GUI_MENU_ITEM – jeder Eintrag verhält sich danach wie ein Button: mit GUI_CLICKED abfragen."),
  H.cmd("GUI_MENU · GUI_MENU_ITEM · GUI_MENU_SEPARATOR", 'GUI_MENU(win, label$)   GUI_MENU_ITEM(menu, label$)   GUI_MENU_SEPARATOR(menu)',
    "GUI_MENU fügt der Menüleiste des Fensters einen Eintrag mit Dropdown hinzu (z. B. \"Datei\"). GUI_MENU_ITEM hängt einen klickbaren Eintrag daran, GUI_MENU_SEPARATOR eine Trennlinie zur Gruppierung.",
    [
      'DIM datei AS GUI_WIDGET',
      'datei = GUI_MENU(win, "Datei")',
      'DIM neu AS GUI_WIDGET',
      'neu = GUI_MENU_ITEM(datei, "Neu")',
      'GUI_MENU_SEPARATOR(datei)',
      'DIM beenden AS GUI_WIDGET',
      'beenden = GUI_MENU_ITEM(datei, "Beenden")',
      'IF GUI_CLICKED(neu) THEN PRINT "Neu geklickt"',
    ]),
  H.cmd("GUI_CONTEXT", 'GUI_CONTEXT(win)',
    "Legt ein Kontextmenü für das Fenster an (öffnet sich per Rechtsklick, ohne eigenen Titel in der Menüleiste). Einträge kommen genauso über GUI_MENU_ITEM/GUI_MENU_SEPARATOR dazu.",
    [
      'DIM ctx AS GUI_WIDGET',
      'ctx = GUI_CONTEXT(win)',
      'DIM loeschen AS GUI_WIDGET',
      'loeschen = GUI_MENU_ITEM(ctx, "Loeschen")',
      'IF GUI_CLICKED(loeschen) THEN PRINT "Loeschen geklickt"',
    ]),

  H.h2("Reiter (Tabs)"),
  H.p("Tabs teilen ein Fenster in mehrere Seiten, zwischen denen der Nutzer oben klickt – praktisch, um viele Einstellungen ohne riesiges Fenster unterzubringen. Die Reiter gehören zum FENSTER (GUI_TABS), einzelne Widgets werden dann per GUI_SET_TAB einer Seite zugeordnet."),
  H.cmd("GUI_TABS · GUI_SET_TAB", 'GUI_TABS(win, labels: ARRAY OF STRING)   GUI_SET_TAB(widget, seite: INTEGER)',
    "GUI_TABS legt die Reiter des Fensters fest (0-basiert nummeriert in der übergebenen Reihenfolge). GUI_SET_TAB ordnet ein Widget einer Seite zu (-1 = auf allen Seiten sichtbar, der Standard).",
    [
      'GUI_TABS(win, ["Allgemein", "Grafik"])',
      'DIM lbl AS GUI_WIDGET',
      'lbl = GUI_LABEL(win, "Aufloesung", 10, 40)',
      'GUI_SET_TAB(lbl, 1)   \' nur auf Seite "Grafik" sichtbar',
    ]),
  H.cmd("GUI_ACTIVE_TAB · GUI_SET_ACTIVE_TAB", 'GUI_ACTIVE_TAB(win) AS INTEGER   GUI_SET_ACTIVE_TAB(win, seite: INTEGER)',
    "GUI_ACTIVE_TAB liefert den Index der gerade sichtbaren Seite (ändert sich, wenn der Nutzer einen Reiter anklickt). GUI_SET_ACTIVE_TAB wechselt die Seite programmatisch.",
    [
      'GUI_SET_ACTIVE_TAB(win, 1)',
      'PRINT GUI_ACTIVE_TAB(win)',
    ], { out: ["1"] }),

  H.h2("Weitere Widgets: Spinner, Splitter, Textfeld, Tooltip"),
  H.cmd("GUI_SPINNER", 'GUI_SPINNER(win, x, y, w, min, max[, default[, schritt]])',
    "Ein Zahlenfeld mit Auf/Ab-Pfeilen (und Mausrad-Unterstützung) – wie GUI_SLIDER, aber kompakter und mit exakter Eingabe statt Ziehen. Wert per GUI_VALUE lesen.",
    [
      'DIM sp AS GUI_WIDGET',
      'sp = GUI_SPINNER(win, 10, 70, 100, 0.0, 10.0, 5.0, 2.0)',
      'PRINT GUI_VALUE(sp)',
    ], { out: ["5.0"] }),
  H.cmd("GUI_SPLITTER", 'GUI_SPLITTER(win, x, y, länge, orientierung$, min, max)',
    'Eine ziehbare Trennlinie zum Aufteilen eines Fensters in zwei Bereiche (z. B. eine Baumansicht links, Inhalt rechts). orientierung$ = "v" (senkrechter Balken, waagerecht ziehbar) oder "h" (waagerechter Balken, senkrecht ziehbar). Die Position liest du mit GUI_VALUE (fenster-relativ) und layoutest damit die beiden Bereiche selbst (z. B. via GUI_SET_BOUNDS).',
    [
      'DIM split AS GUI_WIDGET',
      'split = GUI_SPLITTER(win, 150, 20, 180, "v", 80, 280)',
      'PRINT GUI_VALUE(split)',
    ], { out: ["150.0"] }),
  H.cmd("GUI_TEXTAREA", 'GUI_TEXTAREA(win, x, y, w, h[, platzhalter$])',
    "Ein mehrzeiliges Eingabefeld (das einzeilige Gegenstück ist GUI_TEXTINPUT). Text lesen/setzen läuft über die allgemeinen GUI_TEXT/GUI_SET_TEXT-Befehle.",
    [
      'DIM ta AS GUI_WIDGET',
      'ta = GUI_TEXTAREA(win, 10, 110, 200, 60, "Notiz eingeben...")',
      'GUI_SET_TEXT(ta, "Hallo Welt")',
      'PRINT GUI_TEXT(ta)',
    ], { out: ["Hallo Welt"] }),
  H.cmd("GUI_TOOLTIP", 'GUI_TOOLTIP(widget, text$)',
    "Legt einen Hilfetext fest, der erscheint, wenn die Maus eine Weile über dem Widget verharrt – erklärt Symbole oder knappe Beschriftungen ohne den Platz für einen langen Label-Text zu brauchen.",
    [
      'GUI_TOOLTIP(sp, "Wert einstellen")',
    ]),

  H.h2("Werkzeugleiste: Toolbar & Icon-Buttons"),
  H.p("Eine Toolbar ist ein flacher, dekorativer Streifen als Hintergrund für eine Reihe von Icon-Buttons – die Buttons selbst liegen als eigene Widgets darüber."),
  H.cmd("GUI_TOOLBAR · GUI_ICON_BUTTON", 'GUI_TOOLBAR(win, x, y, w, h)   GUI_ICON_BUTTON(win, x, y, w, h, icon_bild[, text$])',
    "GUI_TOOLBAR zeichnet nur den Streifen (selbst nicht klickbar). GUI_ICON_BUTTON ist ein normaler Button mit einem Bild (IMAGE-Handle, z. B. aus LOADIMAGE oder GENTEX_COLOR) statt/zusätzlich zu Text – ganz normal mit GUI_CLICKED abfragen.",
    [
      'DIM tb AS GUI_WIDGET',
      'tb = GUI_TOOLBAR(win, 10, 180, 200, 32)',
      'DIM icon AS IMAGE',
      'icon = GENTEX_COLOR(16, 16, RGB(255, 200, 0))',
      'DIM ib AS GUI_WIDGET',
      'ib = GUI_ICON_BUTTON(win, 12, 182, 28, 28, icon, "")',
      'PRINT GUI_CLICKED(ib)',
    ], { out: ["FALSE"] }),
  H.cmd("GUI_SET_ICON", 'GUI_SET_ICON(button, icon_bild)',
    "Tauscht das Icon eines bestehenden Buttons aus (-1 entfernt es wieder) – z. B. um einen Play/Pause-Button zwischen zwei Icons umzuschalten.",
    [
      'GUI_SET_ICON(ib, -1)   \' Icon entfernen',
    ]),

  H.h2("Native Dialoge & scrollbare Fenster"),
  H.warn("Beide öffnen einen echten System-Dialog und blockieren, bis der Nutzer reagiert – die folgenden Beispiele zeigen daher die Verwendung ohne Ausgabe-Kasten.", "GUI_CONFIRM/GUI_MESSAGE nicht automatisiert testbar"),
  H.cmd("GUI_MESSAGE · GUI_CONFIRM", 'GUI_MESSAGE(titel$, text$)   GUI_CONFIRM(titel$, text$) AS BOOLEAN',
    "GUI_MESSAGE zeigt einen einfachen Hinweis-Dialog mit OK-Knopf. GUI_CONFIRM fragt Ok/Abbrechen und liefert TRUE/FALSE – z. B. für eine „Wirklich beenden?“-Sicherheitsabfrage.",
    [
      'GUI_MESSAGE("Gespeichert", "Der Spielstand wurde gesichert.")',
      'IF GUI_CONFIRM("Beenden?", "Ungespeicherte Aenderungen gehen verloren.") THEN',
      '    \' Programm beenden',
      'END IF',
    ]),
  H.cmd("GUI_WINDOW_SCROLLABLE", 'GUI_WINDOW_SCROLLABLE(win, an: BOOLEAN)',
    "Macht den Fensterinhalt scrollbar (Mausrad + Scrollbalken), wenn mehr Widgets drin sind, als in die sichtbare Höhe passen – praktisch für lange Optionslisten in einem kleinen Fenster.",
    [
      'GUI_WINDOW_SCROLLABLE(win, TRUE)',
    ]),

  H.h2("Auswahl-Widgets: Dropdown, Listbox, Radio"),
  H.p("Für „eines aus vielen“ gibt es drei Bauformen: das Dropdown klappt auf und braucht wenig Platz, die Listbox zeigt mehrere Einträge dauerhaft, und Radioknöpfe sind die klassische Variante, wenn alle Möglichkeiten sichtbar bleiben sollen. Die Einträge übergibst du jeweils als TUPLE oder ARRAY OF STRING."),
  H.cmd("GUI_DROPDOWN · GUI_DROPDOWN_SELECTED · GUI_DROPDOWN_TEXT", 'GUI_DROPDOWN(win, x, y, w, h, eintraege)   GUI_DROPDOWN_SELECTED(dd)   GUI_DROPDOWN_TEXT(dd)',
    "GUI_DROPDOWN legt eine aufklappbare Auswahl an. GUI_DROPDOWN_SELECTED liefert den gewählten Index (0-basiert, -1 = nichts gewählt), GUI_DROPDOWN_TEXT den Text des gewählten Eintrags. Das aufgeklappte Popup zeichnet über allen anderen Widgets.",
    [
      'DIM modus AS GUI_WIDGET',
      'modus = GUI_DROPDOWN(win, 20, 60, 160, 24, ("Leicht", "Normal", "Schwer"))',
      '',
      'IF GUI_DROPDOWN_SELECTED(modus) = 2 THEN PRINT "Schwer gewaehlt"',
      'PRINT GUI_DROPDOWN_TEXT(modus)',
    ]),
  H.cmd("GUI_DROPDOWN_SET_SELECTED · GUI_SET_DROPDOWN", 'GUI_DROPDOWN_SET_SELECTED(dd, index)   GUI_SET_DROPDOWN(dd, eintraege)',
    "Setzt die Auswahl von Programmseite (z. B. beim Laden eines Spielstands) bzw. tauscht die Einträge komplett aus (z. B. Auflösungsliste nach Monitorwechsel). Nach GUI_SET_DROPDOWN ist nichts mehr gewählt.",
    [
      'GUI_DROPDOWN_SET_SELECTED(modus, 1)          \' „Normal“ vorwaehlen',
      'GUI_SET_DROPDOWN(modus, ("800x600", "1280x720", "1920x1080"))',
    ]),
  H.cmd("GUI_LISTBOX · GUI_LISTBOX_SELECTED · GUI_LISTBOX_TEXT", 'GUI_LISTBOX(win, x, y, w, h, eintraege)   GUI_LISTBOX_SELECTED(lb)   GUI_LISTBOX_TEXT(lb)',
    "Wie das Dropdown, nur dauerhaft ausgeklappt: Die Liste ist immer sichtbar und scrollt bei zu vielen Einträgen. Abfrage und Vorbelegung funktionieren identisch (GUI_LISTBOX_SET_SELECTED, GUI_SET_LISTBOX).",
    [
      'DIM lvl AS GUI_WIDGET',
      'lvl = GUI_LISTBOX(win, 20, 20, 200, 120, ("Wald", "Hoehle", "Burg"))',
      'IF GUI_LISTBOX_SELECTED(lvl) >= 0 THEN PRINT "Level: " + GUI_LISTBOX_TEXT(lvl)',
    ]),
  H.cmd("GUI_RADIO · GUI_RADIO_SELECTED", 'GUI_RADIO(win, gruppe$, text$, x, y)   GUI_RADIO_SELECTED(radio)',
    "Radioknöpfe derselben gruppe$ schließen sich gegenseitig aus – klickst du einen an, gehen die anderen der Gruppe aus. GUI_RADIO_SELECTED liefert TRUE für den gerade gewählten Knopf.",
    [
      'DIM leicht AS GUI_WIDGET',
      'DIM schwer AS GUI_WIDGET',
      'leicht = GUI_RADIO(win, "schwierigkeit", "Leicht", 20, 60)',
      'schwer = GUI_RADIO(win, "schwierigkeit", "Schwer", 20, 84)',
      '',
      'IF GUI_RADIO_SELECTED(schwer) THEN PRINT "Harter Modus"',
    ]),

  H.h2("Tabellen"),
  H.p("Eine Tabelle zeigt Zeilen und Spalten mit fixierter Kopfzeile – für Highscores, ein Inventar, eine Serverliste. Sie kann weit mehr als Text anzeigen: jede Zelle trägt eigene Farben, eine Ausrichtung und eine ART (Text, Bild, Haken, Balken, Knopf). Sortieren, Filtern, Bearbeiten und Mehrfach-Auswahl bringt sie selbst mit."),
  H.cmd("GUI_TABLE · GUI_TABLE_HEADERS · GUI_TABLE_COL_WIDTHS", 'GUI_TABLE(win, x, y, w, h)   GUI_TABLE_HEADERS(tab, spalten)   GUI_TABLE_COL_WIDTHS(tab, breiten)',
    "GUI_TABLE legt eine leere Tabelle an. GUI_TABLE_HEADERS setzt die Spaltenüberschriften (ARRAY OF STRING), GUI_TABLE_COL_WIDTHS die Spaltenbreiten in Pixeln (ARRAY OF INTEGER). Ohne Breiten teilt die Tabelle gleichmäßig auf.",
    [
      'DIM tab AS GUI_WIDGET',
      'tab = GUI_TABLE(win, 12, 12, 300, 160)',
      'DIM kopf AS ARRAY OF STRING',
      'kopf = ["Platz", "Name", "Punkte"]',
      'GUI_TABLE_HEADERS(tab, kopf)',
      'DIM breiten AS ARRAY OF INTEGER',
      'breiten = [50, 150, 90]',
      'GUI_TABLE_COL_WIDTHS(tab, breiten)',
    ]),
  H.warn("Beide Befehle wollen ein ARRAY, kein TUPLE. `GUI_TABLE_HEADERS(tab, (\"a\", \"b\"))` wird mit „erwartet ARRAY OF STRING“ abgelehnt."),
  H.cmd("GUI_TABLE_ADD_ROW · GUI_TABLE_ROW_COUNT", 'GUI_TABLE_ADD_ROW(tab, zellen)   GUI_TABLE_ROW_COUNT(tab)',
    "GUI_TABLE_ADD_ROW hängt EINE Zeile an (ARRAY OF STRING) und liefert deren Nummer. Das ist der übliche Weg: Tabellen werden fast immer in einer Schleife gefüllt – aus einer Datei, einer Datenbank, dem Spielstand.",
    [
      'DIM z AS ARRAY OF STRING',
      'z = ["1", "Anna", "9200"]',
      'GUI_TABLE_ADD_ROW(tab, z)',
      'z = ["2", "Bert", "8100"]',
      'GUI_TABLE_ADD_ROW(tab, z)',
      'PRINT GUI_TABLE_ROW_COUNT(tab)',
    ], { out: ["2"] }),
  H.cmd("GUI_TABLE_ROWS · GUI_TABLE_REMOVE_ROW · GUI_TABLE_CLEAR", 'GUI_TABLE_ROWS(tab, zellen)   GUI_TABLE_REMOVE_ROW(tab, zeile)   GUI_TABLE_CLEAR(tab)',
    "GUI_TABLE_ROWS setzt alle Zeilen auf einmal – die Zellen kommen als ZWEIDIMENSIONALES ARRAY OF STRING (Zeile, Spalte). GUI_TABLE_REMOVE_ROW entfernt eine Zeile (die Auswahl rückt mit), GUI_TABLE_CLEAR leert die Tabelle.",
    [
      'DIM zellen[2, 3] AS STRING',
      'zellen[0, 0] = "1" : zellen[0, 1] = "Anna" : zellen[0, 2] = "9200"',
      'zellen[1, 0] = "2" : zellen[1, 1] = "Bert" : zellen[1, 2] = "8100"',
      'GUI_TABLE_ROWS(tab, zellen)',
    ]),
  H.note("Die Spaltenzahl ist frei: Sie ergibt sich aus der breitesten Angabe. Kürzere Zeilen als der Kopf sind einfach leer, längere erweitern die Tabelle – es gibt keine Reihenfolge, die du einhalten müsstest."),

  H.h2("Zellen: mehr als Text"),
  H.p("Jede Zelle hat einen Inhalt, zwei Farben, eine Ausrichtung und eine Art. Die Arten sind: text (Vorgabe), bild (ein IMAGE, in die Zelle eingepasst), haken (Ankreuzfeld – ein Klick schaltet es selbst um), balken (Fortschritt 0..1) und knopf (Schaltfläche)."),
  H.cmd("GUI_TABLE_SET_CELL · GUI_TABLE_GET_CELL", 'GUI_TABLE_SET_CELL(tab, zeile, spalte, text$)   GUI_TABLE_GET_CELL(tab, zeile, spalte)',
    "Inhalt einer einzelnen Zelle schreiben bzw. lesen.",
    [
      'GUI_TABLE_SET_CELL(tab, 0, 1, "Annabell")',
      'PRINT GUI_TABLE_GET_CELL(tab, 0, 1)',
    ], { out: ["Annabell"] }),
  H.cmd("GUI_TABLE_CELL_COLOR · GUI_TABLE_ROW_COLOR", 'GUI_TABLE_CELL_COLOR(tab, zeile, spalte, vg, hg)   GUI_TABLE_ROW_COLOR(tab, zeile, vg, hg)',
    "Farben je Zelle bzw. für eine ganze Zeile. -1 heißt „nicht gesetzt“ und reicht an die nächste Stufe weiter: Zelle → Zeile → Zebra. So färbst du mit EINEM Aufruf eine Zeile und lässt trotzdem einzelne Zellen ausscheren.",
    [
      'GUI_TABLE_CELL_COLOR(tab, 0, 2, RGB(255, 210, 90), -1)   \' nur Schrift',
      'GUI_TABLE_ROW_COLOR(tab, 1, -1, RGB(60, 26, 26))         \' ganze Zeile',
    ]),
  H.cmd("GUI_TABLE_CELL_KIND · GUI_TABLE_CELL_VALUE · GUI_TABLE_GET_VALUE", 'GUI_TABLE_CELL_KIND(tab, zeile, spalte, art$)   GUI_TABLE_CELL_VALUE(tab, zeile, spalte, wert)   GUI_TABLE_GET_VALUE(tab, zeile, spalte)',
    "Art einer Zelle setzen (text/bild/haken/balken/knopf) und ihren Wert schreiben bzw. lesen: beim Haken 0 oder 1, beim Balken 0.0 bis 1.0.",
    [
      'GUI_TABLE_CELL_KIND(tab, 0, 2, "balken")',
      'GUI_TABLE_CELL_VALUE(tab, 0, 2, 0.75)',
      'GUI_TABLE_SET_CELL(tab, 0, 2, "75 %")   \' Text liegt auf dem Balken',
      'PRINT GUI_TABLE_GET_VALUE(tab, 0, 2)',
    ], { out: ["0.75"] }),
  H.cmd("GUI_TABLE_CELL_IMAGE", 'GUI_TABLE_CELL_IMAGE(tab, zeile, spalte, bild)',
    "Legt ein Bild in die Zelle – es wird eingepasst, das Seitenverhältnis bleibt. Setzt die Art gleich mit, ein zweiter Aufruf erübrigt sich.",
    [
      'DIM ampel AS INTEGER',
      'ampel = GENTEX_COLOR(24, 24, RGB(80, 220, 120))',
      'GUI_TABLE_CELL_IMAGE(tab, 0, 0, ampel)',
      'GUI_TABLE_SET(tab, "zeilenhoehe", 34)    \' Bilder brauchen Platz',
    ]),
  H.cmd("GUI_TABLE_CELL_ALIGN · GUI_TABLE_COL_ALIGN", 'GUI_TABLE_CELL_ALIGN(tab, zeile, spalte, wie$)   GUI_TABLE_COL_ALIGN(tab, spalte, wie$)',
    "Ausrichtung („links“, „mitte“, „rechts“) für eine Zelle bzw. eine ganze Spalte. Zahlen gehören rechtsbündig – sonst kann man sie nicht vergleichen.",
    [
      'GUI_TABLE_COL_ALIGN(tab, 2, "rechts")',
    ]),
  H.tip("Auswahl und Hover liegen halbdurchsichtig ÜBER den Zellflächen. Eine eigene Zellfarbe verdeckt also nicht mehr, welche Zeile gerade gewählt ist."),

  H.h2("Auswahl, Sortieren, Filtern"),
  H.cmd("GUI_TABLE_SELECTED · GUI_TABLE_CLICKED · GUI_TABLE_CLICKED_COL", 'GUI_TABLE_SELECTED(tab)   GUI_TABLE_CLICKED(tab)   GUI_TABLE_CLICKED_COL(tab)',
    "GUI_TABLE_SELECTED liefert die markierte Zeile (-1 = keine). GUI_TABLE_CLICKED liefert NUR im Bild des Klicks die getroffene Zeile, sonst -1; GUI_TABLE_CLICKED_COL dazu die Spalte – so unterscheidest du einen Klick auf den Knopf in Spalte 5 von einem auf den Haken in Spalte 4.",
    [
      'IF GUI_TABLE_CLICKED(tab) >= 0 THEN',
      '    PRINT "Zeile " + STR$(GUI_TABLE_SELECTED(tab)) + _',
      '          ", Spalte " + STR$(GUI_TABLE_CLICKED_COL(tab))',
      'END IF',
    ]),
  H.cmd("GUI_TABLE_SET_SELECTED", 'GUI_TABLE_SET_SELECTED(tab, zeile)',
    "Markiert eine Zeile vom Programm aus; -1 hebt die Markierung auf. Eine Zeilennummer außerhalb der Tabelle wird zu -1, statt einen Fehler zu werfen.",
    [
      'GUI_TABLE_SET_SELECTED(tab, 0)        \' erste Zeile vormarkieren',
      'PRINT GUI_TABLE_SELECTED(tab)',
    ], { out: ["0"] }),
  H.warn("Auf `>= 0` prüfen, nicht bloß `IF GUI_TABLE_CLICKED(tab) THEN`! Ohne Klick kommt -1 zurück – und -1 gilt als wahr. Die Bedingung wäre in JEDEM Bild erfüllt."),
  H.cmd("GUI_TABLE_SORT · GUI_TABLE_SORT_COL · GUI_TABLE_SORT_DESC", 'GUI_TABLE_SORT(tab, spalte, absteigend)   GUI_TABLE_SORT_COL(tab)   GUI_TABLE_SORT_DESC(tab)',
    "Ein Klick auf die Kopfzelle sortiert von selbst, ein zweiter dreht die Richtung um. Diese Befehle machen dasselbe vom Programm aus bzw. lesen den Stand. Spalte < 0 hebt die Sortierung auf.",
    [
      'GUI_TABLE_SORT(tab, 2, TRUE)          \' nach Punkten, absteigend',
      'PRINT GUI_TABLE_SORT_COL(tab)',
    ], { out: ["2"] }),
  H.note("Sortiert wird ZAHLENWEISE, wenn beide Zellen als Zahl lesbar sind, sonst nach Text. Ohne das stünde in einer Punktespalte 100 vor 9."),
  H.cmd("GUI_TABLE_FILTER · GUI_TABLE_GET_FILTER", 'GUI_TABLE_FILTER(tab, spalte, text$)   GUI_TABLE_GET_FILTER(tab, spalte)',
    "Filtert eine Spalte nach Teiltext, Groß-/Kleinschreibung egal; mehrere Spalten wirken zusammen. Mit GUI_TABLE_SET(tab, \"filterzeile\", 1) bekommt der Kopf eine Zeile mit Eingabefeldern, in die der Nutzer selbst tippt.",
    [
      'GUI_TABLE_SET(tab, "filterzeile", 1)',
      'GUI_TABLE_FILTER(tab, 1, "an")        \' zeigt nur Namen mit "an"',
    ]),
  H.cmd("GUI_TABLE_VIEW_COUNT · GUI_TABLE_VIEW_ROW", 'GUI_TABLE_VIEW_COUNT(tab)   GUI_TABLE_VIEW_ROW(tab, i)',
    "Wie viele Zeilen sind gerade sichtbar, und welche DATENzeile steht an Ansichtsposition i? Damit gehst du die Tabelle in der sichtbaren Reihenfolge durch.",
    [
      'DIM i AS INTEGER',
      'FOR i = 0 TO GUI_TABLE_VIEW_COUNT(tab) - 1',
      '    PRINT GUI_TABLE_GET_CELL(tab, GUI_TABLE_VIEW_ROW(tab, i), 1)',
      'NEXT',
    ]),
  H.warn("Alle Zeilennummern nach außen sind DATENzeilen. Sortieren und Filtern stellen die Daten nicht um – sie bauen nur eine Ansicht darüber. Eine Zeilennummer, die dein Programm sich gemerkt hat, zeigt also weiter auf denselben Eintrag."),
  H.cmd("Mehrfach-Auswahl", 'GUI_TABLE_SEL_COUNT(tab)   GUI_TABLE_SEL_ROW(tab, i)   GUI_TABLE_IS_SELECTED(tab, zeile)   GUI_TABLE_SELECT(tab, zeile, an)   GUI_TABLE_CLEAR_SELECTION(tab)',
    "Mit GUI_TABLE_SET(tab, \"mehrfachauswahl\", 1) wählt Strg+Klick eine Zeile dazu oder ab, Umschalt+Klick den ganzen Bereich. Vorhandener Code, der nur GUI_TABLE_SELECTED kennt, läuft unverändert – das bleibt die zuletzt angeklickte Zeile.",
    [
      'GUI_TABLE_SET(tab, "mehrfachauswahl", 1)',
      'DIM i AS INTEGER',
      'FOR i = 0 TO GUI_TABLE_SEL_COUNT(tab) - 1',
      '    PRINT GUI_TABLE_GET_CELL(tab, GUI_TABLE_SEL_ROW(tab, i), 1)',
      'NEXT',
    ]),

  H.h2("Zellen bearbeiten"),
  H.cmd("GUI_TABLE_COL_EDIT · GUI_TABLE_EDITING_ROW · GUI_TABLE_EDITING_COL", 'GUI_TABLE_COL_EDIT(tab, spalte, an)   GUI_TABLE_EDITING_ROW(tab)   GUI_TABLE_EDITING_COL(tab)',
    "Gibst du eine Spalte frei, öffnet ein Doppelklick auf eine Textzelle ein Eingabefeld genau in dieser Zelle: Enter übernimmt, ESC nimmt zurück, ein Klick woanders übernimmt ebenfalls. Beim Öffnen ist der ganze Inhalt markiert, das erste Tippen ersetzt ihn also. Die beiden Getter sagen, welche Zelle gerade bearbeitet wird (-1 = keine).",
    [
      'GUI_TABLE_COL_EDIT(tab, 1, TRUE)      \' nur den Namen aenderbar machen',
      'IF GUI_TABLE_EDITING_ROW(tab) >= 0 THEN',
      '    PRINT "wird gerade bearbeitet"',
      'END IF',
    ]),
  H.warn("Benutzt dein Programm ESC zum Beenden, frag vorher `GUI_TABLE_EDITING_ROW(tab) < 0` ab – sonst beendet dieselbe Taste das Programm, mit der man eine Eingabe zurücknehmen will."),

  H.h2("Spalten: Breite, feste Spalten, Reihenfolge"),
  H.cmd("GUI_TABLE_SET · GUI_TABLE_GET", 'GUI_TABLE_SET(tab, schluessel$, wert)   GUI_TABLE_GET(tab, schluessel$)',
    "Ein Setter für alle Schalter der Tabelle: zeilenhoehe, kopfhoehe, zebra, gitter, filterzeile, sortierbar, spalten_ziehbar, spalten_verschiebbar, feste_spalten, mehrfachauswahl. GUI_TABLE_GET liest sie und kennt zusätzlich „spalten“ (die Spaltenzahl). Ein unbekannter Schlüssel ist ein Fehler, der die gültigen aufzählt.",
    [
      'GUI_TABLE_SET(tab, "zeilenhoehe", 28)',
      'GUI_TABLE_SET(tab, "zebra", 1)',
      'GUI_TABLE_SET(tab, "feste_spalten", 2)   \' bleiben beim Scrollen stehen',
      'PRINT GUI_TABLE_GET(tab, "spalten")',
    ]),
  H.cmd("GUI_TABLE_MOVE_COL · GUI_TABLE_COL_AT · GUI_TABLE_COL_POS · GUI_TABLE_RESET_COLS", 'GUI_TABLE_MOVE_COL(tab, von_pos, nach_pos)   GUI_TABLE_COL_AT(tab, pos)   GUI_TABLE_COL_POS(tab, spalte)   GUI_TABLE_RESET_COLS(tab)',
    "Ist „spalten_verschiebbar“ gesetzt, lässt sich eine Kopfzelle seitwärts ziehen. Auch hier bleiben die DATEN unberührt: COL_AT sagt, welche Datenspalte an einer Anzeigeposition steht, COL_POS umgekehrt.",
    [
      'GUI_TABLE_SET(tab, "spalten_verschiebbar", 1)',
      'GUI_TABLE_MOVE_COL(tab, 0, 2)         \' erste Spalte nach hinten',
      'PRINT GUI_TABLE_COL_AT(tab, 0)',
    ]),
  H.tip("Klick und Zug am Kopf sind dieselbe Geste. Erst beim Loslassen steht fest, was gemeint war: ohne Bewegung wird sortiert, mit Bewegung verschoben."),

  H.h2("Kippschalter und Drehregler"),
  H.p("Zwei Bedienelemente, die aussehen wie an einem Gerät: der Kippschalter statt eines Häkchens, der Drehregler statt eines Schiebers. Beide sind vor allem in den plastischen Glas-Themen zu Hause."),
  H.cmd("GUI_TOGGLE", 'GUI_TOGGLE(win, text$, x, y[, an])',
    "Ein Kippschalter – dieselbe Aufgabe wie eine Checkbox, nur als Schalter gezeichnet. Zustand über GUI_CHECKED bzw. GUI_SET_CHECKED.",
    [
      'DIM ton AS GUI_WIDGET',
      'ton = GUI_TOGGLE(win, "Sound", 20, 60, TRUE)',
      'PRINT GUI_CHECKED(ton)',
    ], { out: ["TRUE"] }),
  H.cmd("GUI_KNOB", 'GUI_KNOB(win, x, y, groesse, min, max[, wert])',
    "Ein Drehregler: senkrecht ziehen dreht ihn. Wert über GUI_VALUE bzw. GUI_SET_VALUE – wie beim Slider, nur platzsparender und auf einem Mischpult passender.",
    [
      'DIM vol AS GUI_WIDGET',
      'vol = GUI_KNOB(win, 30, 100, 60, 0.0, 1.0, 0.7)',
      'PRINT GUI_VALUE(vol)',
    ], { out: ["0.7"] }),
  H.cmd("GUI_SET_ROUND", 'GUI_SET_ROUND(widget, rund)',
    "Macht aus einem rechteckigen Knopf einen runden – für Transport-Tasten (Start/Stopp/Aufnahme) und alles, was nach Gerät aussehen soll.",
    [
      'DIM play AS GUI_WIDGET',
      'play = GUI_BUTTON(win, ">", 20, 150, 40, 40)',
      'GUI_SET_ROUND(play, TRUE)',
    ]),
  H.cmd("GUI_SKIN", 'GUI_SKIN(art$, bild[, rand])',
    "Legt eine eigene Grafik unter eine ganze Widget-Art („button“, „panel“ …). Das Bild wird als 9-Slice gedehnt: die Ecken bleiben, die Kanten strecken sich – so passt eine Grafik auf jede Größe.",
    [
      'DIM skin AS IMAGE',
      'skin = LOADIMAGE("assets/button.png")',
      'GUI_SKIN("button", skin, 8)           \' 8 px Eckenbereich',
    ]),

  H.h2("Anzeige-Widgets: Fortschritt, Bild, Trennlinie, Gruppe, Panel"),
  H.cmd("GUI_PROGRESS", 'GUI_PROGRESS(win, x, y, w, h)',
    "Ein Fortschrittsbalken. Seinen Füllstand setzt du mit GUI_SET_VALUE als Anteil zwischen 0.0 und 1.0 – etwa beim Laden oder für eine Lebensleiste.",
    [
      'DIM bar AS GUI_WIDGET',
      'bar = GUI_PROGRESS(win, 20, 100, 240, 18)',
      'GUI_SET_VALUE(bar, 0.35)              \' 35 % gefuellt',
    ]),
  H.cmd("GUI_IMAGE · GUI_SET_IMAGE", 'GUI_IMAGE(win, x, y, w, h, bild)   GUI_SET_IMAGE(widget, bild)',
    "Zeigt ein per LOADIMAGE geladenes Bild im Fenster (auf w×h skaliert) – z. B. eine Vorschau oder ein Logo. GUI_SET_IMAGE tauscht das Bild später aus.",
    [
      'DIM logo AS IMAGE',
      'logo = LOADIMAGE("assets/logo.png")',
      'DIM bild AS GUI_WIDGET',
      'bild = GUI_IMAGE(win, 20, 20, 128, 64, logo)',
    ]),
  H.cmd("GUI_SEPARATOR · GUI_GROUPBOX · GUI_PANEL", 'GUI_SEPARATOR(win, x, y, w)   GUI_GROUPBOX(win, x, y, w, h[, titel$])   GUI_PANEL(win, x, y, w, h[, titel$])',
    "Drei Ordnungshelfer ohne eigene Funktion: GUI_SEPARATOR zieht eine Trennlinie, GUI_GROUPBOX rahmt zusammengehörige Widgets mit eingelassenem Titel ein, GUI_PANEL ist eine schlichte Hintergrundfläche. Alle drei sind rein dekorativ – die Widgets darin bleiben eigenständig.",
    [
      'GUI_SEPARATOR(win, 12, 92, 280)',
      'GUI_GROUPBOX(win, 12, 100, 280, 90, "Grafik")',
    ]),
  H.cmd("GUI_CANVAS · GUI_CANVAS_X/Y/W/H", 'GUI_CANVAS(win, x, y, w, h)   GUI_CANVAS_X(c)   GUI_CANVAS_Y(c)   GUI_CANVAS_W(c)   GUI_CANVAS_H(c)',
    "Reserviert eine Fläche im Fenster, in die du SELBST zeichnest – für eine Vorschau, ein Diagramm oder eine Minikarte. Die vier Getter liefern den Bereich in BILDSCHIRM-Koordinaten (das Fenster ist ja verschiebbar); zeichne nach GUI_DRAW und clippe selbst auf den Bereich.",
    [
      'DIM cv AS GUI_WIDGET',
      'cv = GUI_CANVAS(win, 12, 12, 200, 120)',
      '',
      'GUI_DRAW()                            \' erst die Oberflaeche ...',
      'BOX(GUI_CANVAS_X(cv), GUI_CANVAS_Y(cv), _',
      '    GUI_CANVAS_X(cv) + GUI_CANVAS_W(cv) - 1, _',
      '    GUI_CANVAS_Y(cv) + GUI_CANVAS_H(cv) - 1, RGB(10, 14, 22))',
      'CIRCLE(GUI_CANVAS_X(cv) + 100, GUI_CANVAS_Y(cv) + 60, 30, CYAN)',
    ]),

  H.h2("Callbacks statt Polling"),
  H.p("Statt jeden Frame GUI_CLICKED abzufragen, kannst du einem Widget eine Funktion zuweisen – GUI_UPDATE ruft sie dann selbst auf. Das ist das Muster, das auch der Formular-Designer dhform benutzt."),
  H.cmd("GUI_ON_CLICK · GUI_ON_CHANGE", 'GUI_ON_CLICK(widget, funktion)   GUI_ON_CHANGE(widget, funktion)',
    "GUI_ON_CLICK feuert bei Knopfdruck, GUI_ON_CHANGE bei Wertänderung (Slider, Checkbox, Dropdown). Die Funktion übergibst du als FUNCREF – also ohne Klammern – und sie hat keine Parameter.",
    [
      'SUB spiel_starten()',
      '    PRINT "Los geht\'s!"',
      'END SUB',
      '',
      'GUI_ON_CLICK(start, spiel_starten)',
    ]),

  H.cmd("GUI_ON_HOVER · GUI_ON_LEAVE · GUI_ON_FOCUS · GUI_ON_BLUR", 'GUI_ON_HOVER(widget, fn)   GUI_ON_LEAVE(widget, fn)   GUI_ON_FOCUS(widget, fn)   GUI_ON_BLUR(widget, fn)',
    "Vier weitere Callbacks: Maus betritt bzw. verlässt ein Widget, ein Eingabefeld bekommt bzw. verliert die Tastatur. Sie feuern auf die FLANKE – einmal beim Übergang, nicht in jedem Bild, solange die Maus stehen bleibt. GUI_ON_BLUR ist die Stelle, an der man eine Eingabe prüft.",
    [
      'SUB zeigHilfe()',
      '    PRINT "Hier kannst du deinen Namen eintragen"',
      'END SUB',
      'SUB pruefe()',
      '    IF GUI_TEXT(feld) = "" THEN PRINT "Name fehlt"',
      'END SUB',
      '',
      'GUI_ON_HOVER(feld, zeigHilfe)',
      'GUI_ON_BLUR(feld, pruefe)',
    ]),
  H.note("Fokus bekommen nur Widgets, die Tastatur annehmen (Textfeld, Textbereich, Zahlenfeld). Hover und Leave kann jedes anklickbare Widget."),

  H.h2("Widgets zur Laufzeit ändern"),
  H.p("Alles, was du beim Aufbau festgelegt hast, lässt sich später ändern: Position, Sichtbarkeit, Farbe, Schrift – oder das Widget ganz entfernen. Das ist die Grundlage für Oberflächen, die auf den Spielzustand reagieren."),
  H.cmd("GUI_SET_BOUNDS · GUI_GET_X/Y/W/H", 'GUI_SET_BOUNDS(widget, x, y, w, h)   GUI_GET_X(w)   GUI_GET_Y(w)   GUI_GET_W(w)   GUI_GET_H(w)',
    "Verschiebt und/oder skaliert ein Widget innerhalb seines Fensters; die Getter liefern die aktuelle Lage (relativ zum Fenster-Inhalt).",
    [
      'GUI_SET_BOUNDS(start, 20, 160, 150, 34)',
      'PRINT GUI_GET_W(start)',
    ]),
  H.cmd("GUI_SET_VISIBLE · GUI_VISIBLE · GUI_SET_ENABLED · GUI_ENABLED", 'GUI_SET_VISIBLE(widget, an)   GUI_VISIBLE(widget)   GUI_SET_ENABLED(widget, an)   GUI_ENABLED(widget)',
    "Unsichtbare Widgets werden weder gezeichnet noch angeklickt. Ausgegraute (nicht enabled) bleiben sichtbar, reagieren aber nicht – der richtige Weg für „erst wählbar, wenn …“.",
    [
      'GUI_SET_ENABLED(start, GUI_CHECKED(agb))   \' erst nach Zustimmung',
      'GUI_SET_VISIBLE(hinweis, FALSE)',
    ]),
  H.cmd("GUI_DESTROY · GUI_KIND · GUI_HOVERED", 'GUI_DESTROY(widget)   GUI_KIND(widget)   GUI_HOVERED(widget)',
    "GUI_DESTROY entfernt ein Widget endgültig (sein Handle bleibt gültig, zeigt aber ins Leere – weitere Zugriffe melden das). GUI_KIND liefert die Bauart als Text (\"button\", \"slider\", …), GUI_HOVERED, ob die Maus gerade darüber steht.",
    [
      'IF GUI_HOVERED(start) THEN GUI_LABEL(win, "Startet das Spiel", 20, 190)',
      'PRINT GUI_KIND(start)                 \' button',
      'GUI_DESTROY(hinweis)',
    ]),
  H.cmd("GUI_SET_VALUE · GUI_SET_CHECKED", 'GUI_SET_VALUE(widget, wert)   GUI_SET_CHECKED(widget, an)',
    "Setzen den Zustand von Programmseite: GUI_SET_VALUE den Slider- bzw. Fortschrittswert, GUI_SET_CHECKED den Haken einer Checkbox – zum Beispiel beim Laden der Einstellungen aus einem Spielstand.",
    [
      'GUI_SET_VALUE(vol, SAVE_GET_FLOAT_OR(slot, "lautstaerke", 0.7))',
      'GUI_SET_CHECKED(snd, SAVE_GET_BOOL_OR(slot, "sound", TRUE))',
    ]),
  H.cmd("GUI_SET_COLOR · GUI_SET_FONT · GUI_SET_FONT_SIZE", 'GUI_SET_COLOR(widget, rolle$, farbe)   GUI_SET_FONT(widget, font)   GUI_SET_FONT_SIZE(widget, px)',
    "Übersteuert Farbe und Schrift für EIN Widget. Als rolle$ sind \"bg\", \"fg\", \"border\" und \"accent\" erlaubt; der Font ist ein Handle aus LOADFONT.",
    [
      'GUI_SET_COLOR(start, "accent", RGB(255, 120, 60))',
      'GUI_SET_FONT_SIZE(titel, 24)',
    ]),
  H.cmd("GUI_SET_ANCHOR", 'GUI_SET_ANCHOR(widget, kanten$)',
    "Bindet ein Widget an Fensterkanten, damit es beim Vergrößern mitwandert oder mitwächst. kanten$ ist eine Kombination aus \"l\", \"r\", \"t\", \"b\" – zwei gegenüberliegende Kanten (\"lr\") dehnen das Widget, eine einzelne (\"r\") klebt es an dieser Kante.",
    [
      'GUI_WINDOW_RESIZABLE(win, TRUE)',
      'GUI_SET_ANCHOR(tab, "lrtb")           \' Tabelle fuellt das Fenster',
      'GUI_SET_ANCHOR(ok, "rb")              \' Knopf bleibt unten rechts',
    ]),
  H.cmd("GUI_FOCUS · GUI_HIT_TEST", 'GUI_FOCUS(widget)   GUI_HIT_TEST(x, y)',
    "GUI_FOCUS setzt den Tastatur-Fokus (z. B. auf ein Eingabefeld beim Öffnen). GUI_HIT_TEST liefert das oberste sichtbare Widget an einem Bildschirmpunkt oder -1 – so baut man eine eigene Auswahl per Mausklick.",
    [
      'GUI_FOCUS(namensfeld)',
      'IF MOUSE_HIT(0) THEN PRINT GUI_HIT_TEST(MOUSEX(), MOUSEY())',
    ]),

  H.h2("Fenster zur Laufzeit steuern"),
  H.cmd("GUI_WINDOW_SET_BOUNDS · GUI_WINDOW_GET_X/Y/W/H", 'GUI_WINDOW_SET_BOUNDS(win, x, y, w, h)   GUI_WINDOW_GET_X(win)   GUI_WINDOW_GET_Y(win)   GUI_WINDOW_GET_W(win)   GUI_WINDOW_GET_H(win)',
    "Setzt bzw. liest Position und Größe eines Fensters auf dem Bildschirm – etwa um die Fensterlage im Spielstand zu sichern und beim nächsten Start wiederherzustellen.",
    [
      'GUI_WINDOW_SET_BOUNDS(win, 100, 80, 320, 240)',
      'SAVE_SET_INT(slot, "win_x", GUI_WINDOW_GET_X(win))',
    ]),
  H.cmd("GUI_WINDOW_MOVABLE · GUI_WINDOW_CLOSABLE · GUI_WINDOW_RESIZABLE", 'GUI_WINDOW_MOVABLE(win, an)   GUI_WINDOW_CLOSABLE(win, an)   GUI_WINDOW_RESIZABLE(win, an)',
    "Schalten Verschieben an der Titelleiste, den Schließen-Knopf und den Größengriff unten rechts ab oder an. Ein festgenageltes Fenster (movable = FALSE) eignet sich für eine Statusanzeige, die immer an derselben Stelle bleibt.",
    [
      'GUI_WINDOW_MOVABLE(hud, FALSE)',
      'GUI_WINDOW_CLOSABLE(hud, FALSE)',
      'GUI_WINDOW_RESIZABLE(werkzeuge, TRUE)',
    ]),
  H.cmd("GUI_WINDOW_SET_MIN_SIZE · GUI_WINDOW_SET_MAX_SIZE", 'GUI_WINDOW_SET_MIN_SIZE(win, w, h)   GUI_WINDOW_SET_MAX_SIZE(win, w, h)',
    "Grenzen für das Ziehen am Größengriff – damit ein Fenster nicht so klein wird, dass seine Widgets nicht mehr hineinpassen.",
    [
      'GUI_WINDOW_SET_MIN_SIZE(werkzeuge, 240, 180)',
    ]),
  H.cmd("GUI_WINDOW_CHROME", 'GUI_WINDOW_CHROME(win, an)',
    "Schaltet Titelleiste und Rahmen ab. Das Fenster ist dann randlos und sein Inhalt beginnt oben links – so füllt ein Formular das ganze Programmfenster, ohne dass man ihm ansieht, dass es ein gui-Fenster ist.",
    [
      'GUI_WINDOW_CHROME(form, FALSE)',
    ]),
  H.cmd("GUI_WINDOW_VISIBLE · GUI_WINDOW_CLOSED · GUI_WINDOW_DESTROY", 'GUI_WINDOW_VISIBLE(win, an)   GUI_WINDOW_CLOSED(win)   GUI_WINDOW_DESTROY(win)',
    "GUI_WINDOW_VISIBLE blendet ein Fenster aus und wieder ein (z. B. Inventar auf Tastendruck). GUI_WINDOW_CLOSED ist TRUE, sobald der Nutzer auf das X geklickt hat. GUI_WINDOW_DESTROY entfernt Fenster samt Widgets.",
    [
      'IF KEYHIT(KEY_I) THEN GUI_WINDOW_VISIBLE(inventar, TRUE)',
      'IF GUI_WINDOW_CLOSED(inventar) THEN PRINT "zugemacht"',
    ]),
  H.cmd("GUI_WINDOW_WIDGET_COUNT · GUI_WINDOW_WIDGET", 'GUI_WINDOW_WIDGET_COUNT(win)   GUI_WINDOW_WIDGET(win, i)',
    "Zählt die Widgets eines Fensters und liefert sie einzeln – damit lässt sich eine Oberfläche durchlaufen, ohne jedes Handle einzeln aufgehoben zu haben (etwa um alles auszugrauen).",
    [
      'DIM i AS INTEGER',
      'FOR i = 0 TO GUI_WINDOW_WIDGET_COUNT(win) - 1',
      '    GUI_SET_ENABLED(GUI_WINDOW_WIDGET(win, i), FALSE)',
      'NEXT',
    ]),

  H.h2("Aussehen: Themes, Metriken, Styles"),
  H.cmd("GUI_THEME_PRESET", 'GUI_THEME_PRESET(name$)',
    "Schaltet auf ein fertiges Farbschema um: \"dark\" (Voreinstellung), \"light\", \"retro\" (Grün auf Schwarz), \"contrast\" (hoher Kontrast), \"modern_dark\" und \"modern_light\". Die beiden modernen Presets bringen zusätzlich runde Ecken, Fensterschatten und eine höhere Titelleiste mit.",
    [
      'GUI_THEME_PRESET("modern_dark")',
    ]),
  H.cmd("GUI_THEME_SET · GUI_THEME_GET · GUI_THEME", 'GUI_THEME_SET(rolle$, farbe)   GUI_THEME_GET(rolle$)   GUI_THEME(rolle$, farbe)',
    "Einzelne Farbrollen ändern – etwa \"accent\" (Hervorhebung), \"win_bg\", \"title_bg\", \"text_fg\", \"widget_bg\", \"widget_border\". GUI_THEME ist der ältere Name für GUI_THEME_SET.",
    [
      'GUI_THEME_SET("accent", RGB(255, 160, 40))',
      'PRINT HEX$(GUI_THEME_GET("win_bg"))',
    ]),
  H.cmd("GUI_METRIC_SET · GUI_METRIC_GET", 'GUI_METRIC_SET(name$, wert)   GUI_METRIC_GET(name$)',
    "Maße statt Farben: \"title_h\" (Titelleistenhöhe), \"pad\" (Innenabstand), \"corner_radius\" (Eckenrundung, 0 = eckig), \"shadow\" (Fensterschatten), \"slider_h\", \"check_size\".",
    [
      'GUI_METRIC_SET("corner_radius", 10)',
      'GUI_METRIC_SET("shadow", 20)',
    ]),
  H.cmd("GUI_STYLE_SET · GUI_APPLY_STYLE", 'GUI_STYLE_SET(style$, eigenschaft$, wert)   GUI_APPLY_STYLE(widget, style$)',
    "Ein benannter Style bündelt Eigenschaften (\"bg\", \"fg\", \"border\", \"accent\", \"font\", \"font_size\") und lässt sich auf beliebig viele Widgets anwenden – wie eine Formatvorlage. GUI_STYLE_SET ist mehrfach aufrufbar und ergänzt den Style.",
    [
      'GUI_STYLE_SET("warnung", "fg", RGB(255, 90, 90))',
      'GUI_STYLE_SET("warnung", "font_size", 18)',
      'GUI_APPLY_STYLE(hinweis, "warnung")',
    ]),

  H.h2("Oberflächen speichern und laden"),
  H.p("Ein ganzes Fenster samt Widgets lässt sich als JSON sichern und später wiederherstellen. Genau dieses Format schreibt der Formular-Designer dhform in seine .gbform-Dateien – du kannst eine dort gebaute Oberfläche also direkt laden."),
  H.cmd("GUI_SAVE · GUI_LOAD", 'GUI_SAVE(win, datei$)   GUI_LOAD(datei$)',
    "GUI_SAVE schreibt ein Fenster in eine Datei, GUI_LOAD baut es daraus wieder auf und liefert das neue Fenster-Handle. Sind Event-Handler-Namen hinterlegt (dhform), ruft GUI_UPDATE die passenden Funktionen automatisch auf.",
    [
      'GUI_SAVE(win, "layout.gbform")',
      'DIM geladen AS GUI_WINDOW',
      'geladen = GUI_LOAD("layout.gbform")',
    ]),
  H.cmd("GUI_TO_JSON · GUI_FROM_JSON", 'GUI_TO_JSON(win)   GUI_FROM_JSON(json$)',
    "Dasselbe ohne Datei: als String. Praktisch, um eine Oberfläche in einem Spielstand mitzusichern oder über das Netz zu schicken.",
    [
      'DIM j AS STRING',
      'j = GUI_TO_JSON(win)',
      'DIM w2 AS GUI_WINDOW',
      'w2 = GUI_FROM_JSON(j)',
    ]),
  H.cmd("GUI_RESET", 'GUI_RESET()',
    "Räumt alles ab: alle Fenster, Widgets und Styles. Der saubere Start beim Szenenwechsel, damit keine Fenster der alten Szene stehen bleiben.",
    [
      'GUI_RESET()',
    ]),

  H.h2("Alles zusammen"),
  H.p("Aufbau einmal, Verarbeitung im Loop – so entsteht das verschiebbare Fenster aus dem Bild:"),
  H.code([
    'IMPORT "gui"',
    'SCREEN(480, 320)',
    'DIM win AS GUI_WINDOW',
    'win = GUI_WINDOW("Einstellungen", 90, 50, 300, 210)',
    'GUI_LABEL(win, "Optionen", 20, 16, RGB(255, 220, 120))',
    'DIM start AS GUI_WIDGET',
    'start = GUI_BUTTON(win, "Spiel starten", 20, 140, 130, 32)',
    'DIM snd AS GUI_WIDGET',
    'snd = GUI_CHECKBOX(win, "Sound an", 20, 60, TRUE)',
    '',
    'WHILE NOT QUITREQUESTED()',
    '    GUI_UPDATE()',
    '    CLS(RGB(24, 28, 44))',
    '    GUI_DRAW()',
    '    IF GUI_CLICKED(start) THEN PRINT "Start, Sound=" + STR$(GUI_CHECKED(snd))',
    '    FLIP()',
    'WEND',
  ]),
  H.note("Das gui-Modul kann noch viel mehr: weitere Widgets (Dropdown, Tabelle, Radio, Fortschrittsbalken, Eingabefeld), Laufzeit-Manipulation (verschieben, ein-/ausblenden, zerstören), Speichern/Laden ganzer Oberflächen und sogar Callback-Funktionen statt Polling. Es gibt dafür einen eigenen Formular-Designer (dhform)."),
  H.tip("ui oder gui – nochmal kurz", "ui (voriges Kapitel): schnelle, jeden Frame neu gezeichnete Menüs – ideal für ein Hauptmenü oder Debug-Overlay. gui (dieses Kapitel): echte, verschiebbare Fenster, die bestehen bleiben – ideal für Werkzeuge, Editoren oder komplexere Oberflächen im Spiel."),
];
