module.exports = (H) => [
  H.chapter("Modul: gui"),
  H.p("Das gui-Modul ist das Gegenstück zum ui-Modul: Statt jeden Frame neu aufgebauter Bedienelemente verwaltet es persistente Fenster mit Widgets – verschiebbar an der Titelleiste, überlappend, mit Z-Reihenfolge und Schließen-Knopf, fast wie auf einem Desktop. Du baust Fenster und Widgets EINMAL vor dem Game-Loop auf; danach rufst du pro Frame nur noch GUI_UPDATE (Maus/Tasten verarbeiten) und GUI_DRAW (zeichnen) und fragst Ereignisse per Polling ab."),
  H.figure("59_gui.png", "Ein verschiebbares gui-Fenster mit Titelleiste, Label, Checkbox, Slider und Button (Cyan-Theme)."),

  H.h2("Fenster & Widgets anlegen"),
  H.p("Ein Fenster erstellst du mit GUI_WINDOW; die Widgets bekommen es als ersten Parameter und liegen mit ihren Koordinaten RELATIV zum Fenster-Inhalt. Jeder Konstruktor liefert ein Handle (GUI_WINDOW bzw. GUI_WIDGET), das du dir merkst, um es später abzufragen."),
  H.cmd("GUI_WINDOW", 'GUI_WINDOW(titel$, x, y, w, h)',
    "Legt ein Fenster mit Titelleiste an (per Maus an der Leiste verschiebbar). Liefert ein GUI_WINDOW-Handle.",
    [
      'IMPORT "gui"',
      'DIM win AS GUI_WINDOW',
      'win = GUI_WINDOW("Einstellungen", 90, 50, 300, 210)',
    ]),
  H.cmd("GUI_LABEL · GUI_BUTTON", 'GUI_LABEL(win, text$, x, y[, farbe])   GUI_BUTTON(win, text$, x, y, w, h)',
    "Fügen dem Fenster ein Text-Label bzw. einen Knopf hinzu (Koordinaten relativ zum Fenster). Beide liefern ein GUI_WIDGET-Handle.",
    [
      'GUI_LABEL(win, "Optionen", 20, 16, RGB(255, 220, 120))',
      'DIM start AS GUI_WIDGET',
      'start = GUI_BUTTON(win, "Spiel starten", 20, 140, 130, 32)',
    ]),
  H.cmd("GUI_CHECKBOX · GUI_SLIDER", 'GUI_CHECKBOX(win, label$, x, y[, default])   GUI_SLIDER(win, x, y, w, min, max[, default])',
    "Fügen eine Checkbox bzw. einen Schieberegler hinzu. Ihren Zustand fragst du später per Polling ab (siehe unten).",
    [
      'DIM snd AS GUI_WIDGET',
      'snd = GUI_CHECKBOX(win, "Sound an", 20, 60, TRUE)',
      'DIM vol AS GUI_WIDGET',
      'vol = GUI_SLIDER(win, 20, 100, 250, 0.0, 1.0, 0.7)',
    ]),

  H.h2("Pro Frame: aktualisieren & zeichnen"),
  H.cmd("GUI_UPDATE · GUI_DRAW", 'GUI_UPDATE()   GUI_DRAW()',
    "GUI_UPDATE verarbeitet Maus und Tastatur (Hover, Klick, Fenster-Ziehen, Fokus, Z-Reihenfolge) und muss VOR GUI_DRAW und den Polling-Abfragen stehen. GUI_DRAW zeichnet alle Fenster von hinten nach vorne.",
    [
      'WHILE NOT QUITREQUESTED()',
      '    GUI_UPDATE()        \' zuerst',
      '    CLS(RGB(24, 28, 44))',
      '    GUI_DRAW()',
      '    FLIP()',
      'WEND',
    ]),

  H.h2("Ereignisse abfragen (Polling)"),
  H.cmd("GUI_CLICKED · GUI_CHECKED · GUI_VALUE", 'GUI_CLICKED(widget)   GUI_CHECKED(widget)   GUI_VALUE(widget)',
    "GUI_CLICKED liefert TRUE im Frame, in dem ein Button geklickt wurde. GUI_CHECKED gibt den Zustand einer Checkbox, GUI_VALUE den Wert eines Sliders. Diese Abfragen stehen nach GUI_UPDATE.",
    [
      'IF GUI_CLICKED(start) THEN',
      '    \' Spiel starten',
      'END IF',
      'DIM an AS BOOLEAN',
      'an = GUI_CHECKED(snd)',
      'DIM lautstaerke AS FLOAT',
      'lautstaerke = GUI_VALUE(vol)',
    ]),

  H.h2("Alles zusammen"),
  H.p("Aufbau einmal, Verarbeitung im Loop – so entsteht das verschiebbare Fenster aus dem Bild:"),
  H.code([
    'IMPORT "gui"',
    'SCREEN(480, 320)',
    'DIM win AS GUI_WINDOW',
    'win = GUI_WINDOW("Einstellungen", 90, 50, 300, 210)',
    'GUI_LABEL(win, "Optionen", 20, 16, RGB(255, 220, 120))',
    'DIM start AS GUI_WIDGET',
    'start = GUI_BUTTON(win, "Spiel starten", 20, 140, 130, 32)',
    'DIM snd AS GUI_WIDGET',
    'snd = GUI_CHECKBOX(win, "Sound an", 20, 60, TRUE)',
    '',
    'WHILE NOT QUITREQUESTED()',
    '    GUI_UPDATE()',
    '    CLS(RGB(24, 28, 44))',
    '    GUI_DRAW()',
    '    IF GUI_CLICKED(start) THEN PRINT "Start, Sound=" + STR$(GUI_CHECKED(snd))',
    '    FLIP()',
    'WEND',
  ]),
  H.note("Das gui-Modul kann noch viel mehr: weitere Widgets (Dropdown, Tabelle, Radio, Fortschrittsbalken, Eingabefeld), Laufzeit-Manipulation (verschieben, ein-/ausblenden, zerstören), Speichern/Laden ganzer Oberflächen und sogar Callback-Funktionen statt Polling. Es gibt dafür einen eigenen Formular-Designer (gbform)."),
  H.tip("ui oder gui – nochmal kurz", "ui (voriges Kapitel): schnelle, jeden Frame neu gezeichnete Menüs – ideal für ein Hauptmenü oder Debug-Overlay. gui (dieses Kapitel): echte, verschiebbare Fenster, die bestehen bleiben – ideal für Werkzeuge, Editoren oder komplexere Oberflächen im Spiel."),
];
