module.exports = (H) => [
  H.chapter("Modul: chart"),
  H.p("Zahlen sagen wenig, Bilder viel. Das chart-Modul zeichnet fertige Diagramme: Kuchen und Ringe für Anteile, Balken für Vergleiche, Linien und Flächen für Verläufe, dazu analoge Tachos, Leisten und LED-Ketten für einen einzelnen Messwert. Du legst ein Diagramm einmal an, fütterst es mit Daten und rufst pro Bild CHART_DRAW – um Achsen, Beschriftungen, Legende, Farben und die Maus kümmert sich das Modul."),
  H.figure("59a_chart.png", "Vier der sechs Diagrammarten nebeneinander: Kuchen, Balken, Linie und ein Tacho mit Farbzonen."),

  H.h2("Die sechs Arten"),
  H.p("Welche Art du bekommst, entscheidet der erste Parameter von CHART_NEW. Drei davon zeigen eine ganze Datenreihe, drei einen einzelnen Wert:"),
  H.bullet("kuchen / donut – Anteile an einem Ganzen. „donut“ ist derselbe Kuchen mit einem Loch in der Mitte."),
  H.bullet("balken – Vergleich von Kategorien; wahlweise senkrecht oder waagerecht, gruppiert oder gestapelt."),
  H.bullet("linie / flaeche – Verläufe über die Zeit. Mit einem gleitenden Fenster auch für Live-Werte wie die Bildrate."),
  H.bullet("tacho – Rundskala mit Zeiger und Farbzonen, wie ein Drehzahlmesser."),
  H.bullet("leiste – liegende oder stehende Leiste mit wanderndem Marker (Füllstand, Ladebalken)."),
  H.bullet("led – eine Kette diskreter Zellen, die bis zum Wert leuchten (Aussteuerungsanzeige)."),
  H.note("Die einwertigen Arten (tacho, leiste, led) stellen ihre Ausrichtung selbst auf „waagerecht“ – die Vorgabe „senkrecht“ ist nur für Balkendiagramme richtig."),

  H.h2("Anlegen und zeichnen"),
  H.cmd("CHART_NEW", 'CHART_NEW(art$, x, y, breite, hoehe)',
    "Legt ein Diagramm an und liefert ein CHART-Handle. Die Rechteck-Angaben sind Bildschirm-Koordinaten – das Diagramm zeichnet sich später genau dorthin.",
    [
      'IMPORT "chart"',
      'DIM c AS CHART',
      'c = CHART_NEW("balken", 20, 20, 300, 200)',
    ]),
  H.cmd("CHART_DRAW", 'CHART_DRAW(diagramm)',
    "Zeichnet das Diagramm – in den Game-Loop, nach CLS und vor FLIP. Der einzige Befehl des Moduls, der ein Fenster braucht; alles andere rechnet auch ohne SCREEN.",
    [
      'WHILE NOT QUITREQUESTED()',
      '    CLS(RGB(16, 20, 30))',
      '    CHART_DRAW(c)',
      '    FLIP()',
      'WEND',
    ]),
  H.cmd("CHART_UPDATE", 'CHART_UPDATE(diagramm, sekunden)',
    "Lässt die Werte weich nachziehen, wenn „animation“ gesetzt ist. Ohne Animation brauchst du den Aufruf nicht – dann zeichnet CHART_DRAW direkt die echten Werte.",
    [
      'CHART_SET_NUM(c, "animation", 0.4)   \' Nachziehzeit in Sekunden',
      '\' ... im Game-Loop:',
      'CHART_UPDATE(c, DELTA())',
    ]),
  H.cmd("CHART_BOUNDS", 'CHART_BOUNDS(diagramm, x, y, breite, hoehe)',
    "Verschiebt bzw. skaliert das Diagramm nachträglich – praktisch, wenn sich die Fenstergröße ändert.",
    [
      'CHART_BOUNDS(c, 0, 0, SCREENWIDTH(), SCREENHEIGHT() \\ 2)',
    ]),

  H.h2("Daten: der kurze Weg"),
  H.p("Für ein Diagramm mit EINER Datenreihe – der Normalfall bei Kuchen und Balken – reicht CHART_ADD. Jeder Aufruf hängt eine Kategorie an."),
  H.cmd("CHART_ADD", 'CHART_ADD(diagramm, name$, wert[, farbe])',
    "Fügt eine Kategorie mit Namen und Wert hinzu und liefert deren Index. Ohne Farbangabe nimmt das Diagramm die nächste Farbe aus seiner Palette.",
    [
      'IMPORT "chart"',
      'DIM c AS CHART',
      'c = CHART_NEW("kuchen", 20, 20, 200, 200)',
      'CHART_ADD(c, "Holz", 45.0)',
      'CHART_ADD(c, "Stein", 30.0)',
      'CHART_ADD(c, "Gold", 25.0, RGB(240, 200, 60))',
    ]),
  H.warn("Farbe 0 ist SCHWARZ, nicht „nimm die Palette“. Wer die Palette will, lässt das Argument weg oder übergibt -1."),
  H.cmd("CHART_VALUE", 'CHART_VALUE(diagramm, wert)',
    "Setzt den EINEN Wert eines Tachos, einer Leiste oder einer LED-Kette. Für diese Arten ist das der richtige Befehl – CHART_ADD legt Kategorien an und lässt den Zeiger auf 0 stehen.",
    [
      'DIM t AS CHART',
      't = CHART_NEW("tacho", 20, 20, 200, 200)',
      'CHART_SET_NUM(t, "min", 0.0)',
      'CHART_SET_NUM(t, "max", 8000.0)',
      'CHART_VALUE(t, 4200.0)',
    ]),

  H.h2("Daten: mehrere Reihen"),
  H.p("Sobald du zwei Kurven vergleichen oder Balken gruppieren willst, brauchst du benannte Reihen. CHART_SERIES legt eine an und liefert ihren Index; alle weiteren Befehle sprechen die Reihe über diesen Index an."),
  H.cmd("CHART_SERIES", 'CHART_SERIES(diagramm, name$[, farbe])',
    "Legt eine Datenreihe an und liefert ihren Index (0, 1, 2 …). Der Name landet in der Legende.",
    [
      'DIM c AS CHART',
      'c = CHART_NEW("linie", 20, 20, 400, 200)',
      'DIM ein AS INTEGER : ein = CHART_SERIES(c, "Einnahmen")',
      'DIM aus AS INTEGER : aus = CHART_SERIES(c, "Ausgaben")',
    ]),
  H.cmd("CHART_DATA", 'CHART_DATA(diagramm, reihe, werte)',
    "Setzt alle Werte einer Reihe auf einmal (ARRAY OF FLOAT oder TUPLE) – der schnellste Weg, wenn die Zahlen schon vorliegen.",
    [
      'DIM woche AS ARRAY OF FLOAT',
      'woche = [42.0, 51.0, 38.0, 60.0, 47.0]',
      'CHART_DATA(c, ein, woche)',
    ]),
  H.cmd("CHART_PUSH", 'CHART_PUSH(diagramm, reihe, wert)',
    "Hängt EINEN Wert hinten an. Zusammen mit der Eigenschaft „fenster“ entsteht daraus eine mitlaufende Live-Kurve: ältere Werte fallen vorne heraus.",
    [
      'CHART_SET_NUM(c, "fenster", 120)     \' nur die letzten 120 Werte zeigen',
      '\' ... im Game-Loop:',
      'CHART_PUSH(c, ein, FPS())',
    ]),
  H.cmd("CHART_SET_POINT · CHART_GET", 'CHART_SET_POINT(diagramm, reihe, punkt, wert)   CHART_GET(diagramm, reihe, punkt)',
    "Ändern bzw. lesen einen einzelnen Punkt einer Reihe.",
    [
      'CHART_SET_POINT(c, ein, 2, 55.0)',
      'PRINT CHART_GET(c, ein, 2)',
    ], { out: ["55.0"] }),
  H.cmd("CHART_LABEL", 'CHART_LABEL(diagramm, punkt, text$)',
    "Beschriftet einen Punkt (die x-Achse bei Linien/Balken, das Kuchenstück bei Kuchen).",
    [
      'CHART_LABEL(c, 0, "Mo")',
      'CHART_LABEL(c, 1, "Di")',
    ]),
  H.cmd("CHART_COUNT · CHART_SERIES_COUNT", 'CHART_COUNT(diagramm)   CHART_SERIES_COUNT(diagramm)',
    "Anzahl der Punkte je Reihe bzw. Anzahl der Reihen.",
    [
      'PRINT CHART_SERIES_COUNT(c)',
    ], { out: ["2"] }),
  H.cmd("CHART_CLEAR", 'CHART_CLEAR(diagramm)',
    "Löscht alle Daten, behält aber Aussehen und Einstellungen – gedacht für „neu befüllen“ statt „neu anlegen“.",
    [
      'CHART_CLEAR(c)',
    ]),
  H.cmd("CHART_STAT", 'CHART_STAT(diagramm, reihe, kennzahl$)',
    "Kennzahl einer Reihe, ohne selbst zu rechnen: „anzahl“, „summe“, „mittel“, „min“, „max“. Nicht-endliche Werte (NaN) bleiben dabei außen vor.",
    [
      'PRINT CHART_STAT(c, ein, "max")',
      'PRINT CHART_STAT(c, ein, "mittel")',
    ]),

  H.h2("Aussehen: vier Setter statt vierzig Befehle"),
  H.p("Ein Diagramm hat rund fünfzig Stellschrauben. Statt für jede einen eigenen Befehl zu haben, gibt es vier Setter – nach dem Typ des Werts sortiert. Ein unbekannter Schlüssel ist ein Fehler, der dir die gültigen aufzählt; ein Tippfehler bleibt also nicht stumm."),
  H.cmd("CHART_SET", 'CHART_SET(diagramm, eigenschaft$, wert$)',
    "Alles, was ein Text ist: titel, einheit, achse_x, achse_y, legende (aus/oben/unten/links/rechts), ausrichtung (senkrecht/waagerecht), werte (aus/innen/aussen), wertanzeige (aus/innen/pille/blase/am_zeiger), zifferblatt (ring/segmente/striche/baender), punktform (kreis/quadrat/raute/dreieck).",
    [
      'CHART_SET(c, "titel", "Wocheneinnahmen")',
      'CHART_SET(c, "einheit", " G")',
      'CHART_SET(c, "legende", "unten")',
    ]),
  H.cmd("CHART_SET_NUM", 'CHART_SET_NUM(diagramm, eigenschaft$, wert)',
    "Alles, was eine Zahl ist: min, max, innenradius, ecken, polster, gitter (ABSTAND der Gitterlinien, nicht ihre Anzahl), nachkomma, striche, unterstriche, linien_dicke, animation, fenster, schatten, deckkraft …",
    [
      'CHART_SET_NUM(c, "min", 0.0)',
      'CHART_SET_NUM(c, "max", 100.0)',
      'CHART_SET_NUM(c, "nachkomma", 1)',
    ]),
  H.cmd("CHART_SET_COLOR", 'CHART_SET_COLOR(diagramm, eigenschaft$, farbe)',
    "Alles, was eine Farbe ist: hintergrund, rahmen, gitter, text, titel, achse, zeiger, flaeche, verlauf, schatten – und der gerichtete Skalen-Verlauf skala_von / skala_mitte / skala_bis.",
    [
      'CHART_SET_COLOR(c, "hintergrund", RGB(20, 24, 34))',
      'CHART_SET_COLOR(c, "titel", RGB(255, 220, 120))',
    ]),
  H.cmd("CHART_SET_FLAG", 'CHART_SET_FLAG(diagramm, eigenschaft$, an)',
    "Alles, was ein Schalter ist: rahmen, gitter_x, gitter_y, prozent, flaeche, punkte, glatt, null_linie, stapel, verlauf, treppe, fadenkreuz, hover, tooltip.",
    [
      'CHART_SET_FLAG(c, "glatt", TRUE)      \' weiche Kurve statt Kanten',
      'CHART_SET_FLAG(c, "flaeche", TRUE)    \' Fläche unter der Linie füllen',
    ]),
  H.tip("Zwei Kurvenformen schließen sich aus", "„glatt“ und „treppe“ vertragen sich nicht – setzt du beides, gewinnt die Treppe."),

  H.h2("Themen und Paletten"),
  H.cmd("CHART_THEME", 'CHART_THEME(diagramm, thema$)',
    "Setzt Hintergrund-, Text-, Gitter- und Datenfarben in einem Zug: „dunkel“, „hell“, „neon“ oder „pastell“.",
    [
      'CHART_THEME(c, "dunkel")',
    ]),
  H.cmd("CHART_PALETTE", 'CHART_PALETTE(diagramm, farben)',
    "Eigene Farbreihe für die Datenreihen bzw. Kuchenstücke (ARRAY OF INTEGER oder TUPLE). Sie wird der Reihe nach durchlaufen und wiederholt sich.",
    [
      'DIM p AS ARRAY OF INTEGER',
      'p = [RGB(80, 190, 255), RGB(255, 170, 60), RGB(120, 220, 130)]',
      'CHART_PALETTE(c, p)',
    ]),
  H.note("Die Palette ist kategorial – sie unterscheidet Dinge. Für einen Verlauf von „wenig“ nach „viel“ gibt es die eigene Farbrolle skala_von / skala_mitte / skala_bis; eine interpolierte Palette gäbe nur einen Regenbogen ohne Richtung."),

  H.h2("Farbzonen für Tacho, Leiste und LED"),
  H.cmd("CHART_ZONE", 'CHART_ZONE(diagramm, von, bis, farbe[, name$])',
    "Färbt einen Wertebereich der Skala ein – grün/gelb/rot statt bloßer Zahlen. Mit Namen wird die Zone zusätzlich entlang des Bogens beschriftet.",
    [
      'DIM t AS CHART',
      't = CHART_NEW("tacho", 20, 20, 240, 240)',
      'CHART_SET_NUM(t, "min", 0.0)',
      'CHART_SET_NUM(t, "max", 8000.0)',
      'CHART_ZONE(t, 0.0, 5000.0, RGB(70, 200, 110), "NORMAL")',
      'CHART_ZONE(t, 5000.0, 6500.0, RGB(240, 200, 60), "ACHTUNG")',
      'CHART_ZONE(t, 6500.0, 8000.0, RGB(230, 90, 90), "ROT")',
      'CHART_VALUE(t, 4200.0)',
    ]),
  H.cmd("CHART_ZONE_CLEAR", 'CHART_ZONE_CLEAR(diagramm)',
    "Entfernt alle Zonen.",
    [
      'CHART_ZONE_CLEAR(t)',
    ]),
  H.tip("Zonen gewinnen gegen den Verlauf", "Wo eine Farbzone liegt, gilt ihre Farbe – der Skalen-Verlauf kommt nur dort zum Zug, wo keine Zone definiert ist."),

  H.h2("Die Maus: Hervorhebung, Sprechblase, Klick"),
  H.p("CHART_DRAW wertet die Maus selbst aus – du brauchst keinen zusätzlichen Aufruf. Was darunter liegt, hebt sich hervor; mit dem Schalter „tooltip“ erscheint eine Sprechblase mit Name und Wert. Abgefragt wird danach:"),
  H.cmd("CHART_HOVER · CHART_HOVER_SERIES", 'CHART_HOVER(diagramm)   CHART_HOVER_SERIES(diagramm)',
    "Index des Punkts unter der Maus bzw. seiner Reihe – beide -1, wenn die Maus daneben liegt.",
    [
      'CHART_SET_FLAG(c, "hover", TRUE)',
      'CHART_SET_FLAG(c, "tooltip", TRUE)',
      '\' ... nach CHART_DRAW:',
      'IF CHART_HOVER(c) >= 0 THEN',
      '    PRINT "Punkt " + STR$(CHART_HOVER(c))',
      'END IF',
    ]),
  H.cmd("CHART_HOVER_LABEL$ · CHART_HOVER_VALUE", 'CHART_HOVER_LABEL$(diagramm)   CHART_HOVER_VALUE(diagramm)',
    "Beschriftung und Wert des Punkts unter der Maus – bequemer, als beides selbst nachzuschlagen.",
    [
      'IF CHART_HOVER(c) >= 0 THEN',
      '    TEXT(10, 10, CHART_HOVER_LABEL$(c) + ": " + STR$(CHART_HOVER_VALUE(c)))',
      'END IF',
    ]),
  H.cmd("CHART_CLICKED · CHART_CLICKED_SERIES", 'CHART_CLICKED(diagramm)   CHART_CLICKED_SERIES(diagramm)',
    "Nur im Bild des Klicks der getroffene Punkt bzw. seine Reihe, sonst -1 – dasselbe Muster wie GUI_CLICKED.",
    [
      'IF CHART_CLICKED(c) >= 0 THEN',
      '    PRINT "Angeklickt: " + CHART_HOVER_LABEL$(c)',
      'END IF',
    ]),

  H.h2("Ein vollständiges Beispiel"),
  H.p("Eine Live-Kurve der Bildrate mit gleitendem Fenster, weicher Linie und gefüllter Fläche – zwölf Zeilen, und sie läuft."),
  H.code([
    'IMPORT "chart"',
    'SCREEN(640, 400, "Bildrate", 1)',
    '',
    'DIM c AS CHART',
    'c = CHART_NEW("linie", 20, 20, 600, 300)',
    'DIM r AS INTEGER : r = CHART_SERIES(c, "Bilder/s")',
    'CHART_SET(c, "titel", "Bildrate")',
    'CHART_SET_NUM(c, "fenster", 180)      \' die letzten 3 Sekunden',
    'CHART_SET_NUM(c, "min", 0.0)',
    'CHART_SET_NUM(c, "max", 70.0)',
    'CHART_SET_FLAG(c, "glatt", TRUE)',
    'CHART_SET_FLAG(c, "flaeche", TRUE)',
    'CHART_THEME(c, "dunkel")',
    '',
    'WHILE NOT QUITREQUESTED()',
    '    IF KEYPRESSED(27) THEN BREAK',
    '    CHART_PUSH(c, r, FPS())',
    '    CLS(RGB(12, 16, 24))',
    '    CHART_DRAW(c)',
    '    FLIP()',
    'WEND',
  ]),
  H.tip("Nur das Zeichnen braucht ein Fenster", "Alles außer CHART_DRAW rechnet ohne Fenster. Du kannst ein Diagramm also aufbauen und auswerten, bevor überhaupt ein SCREEN existiert."),
];
