module.exports = (H) => [
  H.chapter("Modul: scene"),
  H.p("Ein Spiel besteht aus mehreren Abschnitten: Hauptmenü, das eigentliche Spiel, ein Pause-Bildschirm, Game Over. Das scene-Modul hilft, sauber zwischen solchen Zuständen zu wechseln. Es verwaltet einen Stapel von Szenen (jede mit Namen) und gibt jeder Szene ihren eigenen kleinen Datenspeicher – etwa für Punkte und Leben. So bleibt dein Game-Loop übersichtlich: Du schaust nur, welche Szene gerade oben liegt, und zeichnest entsprechend."),

  H.h2("Szenen wechseln"),
  H.p("Es gibt zwei Arten zu wechseln. SCENE_SWITCH ersetzt den ganzen Stapel – ein endgültiger Wechsel ohne Rückweg (Menü → Spiel). SCENE_PUSH legt eine Szene OBEN DRAUF, ohne die darunter zu verlieren (Pause über dem laufenden Spiel); SCENE_POP nimmt sie wieder weg und macht die darunterliegende wieder aktiv."),
  H.cmd("SCENE_SWITCH · SCENE_PUSH · SCENE_POP", 'SCENE_SWITCH(name$)   SCENE_PUSH(name$)   SCENE_POP()',
    "SCENE_SWITCH wirft den Stapel weg und startet bei name$. SCENE_PUSH legt name$ oben drauf (die alte Szene bleibt erhalten). SCENE_POP entfernt die oberste und macht die vorherige aktiv.",
    [
      'IMPORT "scene"',
      'SCENE_SWITCH("playing")    \' Spiel starten (kein Zurück)',
      'SCENE_PUSH("pause")        \' Pause über das Spiel legen',
      'SCENE_POP()                \' Pause schließen -> zurück ins Spiel',
    ]),
  H.cmd("SCENE_CURRENT · SCENE_DEPTH", 'SCENE_CURRENT()   SCENE_DEPTH()',
    "SCENE_CURRENT liefert den Namen der obersten (aktiven) Szene (oder \"\" bei leerem Stapel), SCENE_DEPTH die Anzahl der Szenen im Stapel. Über SCENE_CURRENT verzweigt dein Game-Loop.",
    [
      'SELECT CASE SCENE_CURRENT()',
      '    CASE "menu"    : \' Menü zeichnen',
      '    CASE "playing" : \' Spiel zeichnen',
      '    CASE "pause"   : \' Pause-Overlay zeichnen',
      'END SELECT',
    ]),

  H.h2("Daten pro Szene"),
  H.p("Jede Szene hat ihren eigenen Datenspeicher (per Schlüssel-Text). Du legst dort Werte ab, die nur diese Szene betreffen – etwa den Punktestand im „playing“-Zustand. Wichtig: Eine frisch per PUSH oder SWITCH erzeugte Szene startet mit einem LEEREN Speicher; der Speicher einer darunterliegenden Szene bleibt bei PUSH/POP erhalten."),
  H.cmd("SCENE_SET_INT … · SCENE_GET_INT …", 'SCENE_SET_INT(key$, wert)   SCENE_GET_INT(key$)   (auch FLOAT/STRING/BOOL)',
    "SET legt einen Wert in der aktuellen Szene ab, GET liest ihn. Es gibt je eine Variante für INT, FLOAT, STRING und BOOL. SCENE_GET_* ist strikt – fehlt der Schlüssel, gibt es einen Fehler.",
    [
      'SCENE_SET_INT("score", 0)',
      'SCENE_SET_INT("lives", 3)',
      'SCENE_SET_INT("score", SCENE_GET_INT("score") + 100)',
      'PRINT SCENE_GET_INT("score")',
    ], { out: ["100"] }),
  H.cmd("SCENE_GET_INT_OR …", 'SCENE_GET_INT_OR(key$, default)   (auch FLOAT/STRING/BOOL)',
    "Wie SCENE_GET_*, aber mit Rückfallwert: Fehlt der Schlüssel, kommt default statt eines Fehlers. Praktisch für optionale Werte.",
    [
      'DIM hi AS INTEGER',
      'hi = SCENE_GET_INT_OR("highscore", 0)   \' 0, falls nie gesetzt',
    ]),

  H.h2("Im Game-Loop"),
  H.p("Ein Spiel mit Menü, Spiel und Pause sieht im Kern so aus – die aktive Szene bestimmt, was passiert:"),
  H.code([
    'IMPORT "scene"',
    'SCENE_SWITCH("menu")',
    '',
    'WHILE NOT QUITREQUESTED()',
    '    CLS()',
    '    SELECT CASE SCENE_CURRENT()',
    '        CASE "menu"',
    '            TEXT(20, 20, "Enter = Start")',
    '            IF KEYPRESSED(KEY_RETURN) THEN',
    '                SCENE_SWITCH("playing")',
    '                SCENE_SET_INT("score", 0)',
    '            END IF',
    '        CASE "playing"',
    '            TEXT(20, 20, "Punkte: " + STR$(SCENE_GET_INT("score")))',
    '            IF KEYPRESSED(KEY_ESCAPE) THEN SCENE_PUSH("pause")',
    '        CASE "pause"',
    '            TEXT(20, 20, "PAUSE - Enter = weiter")',
    '            IF KEYPRESSED(KEY_RETURN) THEN SCENE_POP()',
    '    END SELECT',
    '    FLIP()',
    'WEND',
  ]),
  H.h2("Daten je Szene ablegen"),
  H.p("Jede Szene hat ihren eigenen kleinen Datenspeicher – der Punktestand des Levels, die gewählte Schwierigkeit, ob der Schlüssel schon eingesammelt wurde. Beim Verlassen der Szene bleibt er erhalten, beim Zurückkehren steht alles wieder da."),
  H.cmd("SCENE_SET_FLOAT · SCENE_SET_STRING · SCENE_SET_BOOL", 'SCENE_SET_FLOAT(schluessel$, wert)   SCENE_SET_STRING(schluessel$, text$)   SCENE_SET_BOOL(schluessel$, wahr)',
    "Legen einen Wert unter einem Namen in der AKTUELLEN Szene ab (neben dem bereits gezeigten SCENE_SET_INT).",
    [
      'SCENE_SET_FLOAT("zeit", 12.5)',
      'SCENE_SET_STRING("levelname", "Waldweg")',
      'SCENE_SET_BOOL("schluessel_gefunden", TRUE)',
    ]),
  H.cmd("SCENE_GET_FLOAT · SCENE_GET_STRING · SCENE_GET_BOOL", 'SCENE_GET_FLOAT(schluessel$)   SCENE_GET_STRING(schluessel$)   SCENE_GET_BOOL(schluessel$)',
    "Lesen den Wert zurück. Fehlt der Schlüssel, kommt der Standardwert des Typs (0.0, leerer Text, FALSE).",
    [
      'PRINT SCENE_GET_STRING("levelname")',
    ]),
  H.cmd("SCENE_GET_FLOAT_OR · SCENE_GET_STRING_OR · SCENE_GET_BOOL_OR", 'SCENE_GET_FLOAT_OR(schluessel$, ersatz)   SCENE_GET_STRING_OR(schluessel$, ersatz$)   SCENE_GET_BOOL_OR(schluessel$, ersatz)',
    "Dasselbe mit selbst gewähltem Ersatzwert – die sauberere Variante, wenn 0 oder FALSE eine gültige Antwort wäre und du „gar nicht gesetzt“ davon unterscheiden willst.",
    [
      'DIM schwierigkeit AS STRING',
      'schwierigkeit = SCENE_GET_STRING_OR("modus", "normal")',
    ]),
  H.cmd("SCENE_HAS_KEY · SCENE_DELETE · SCENE_HAS · SCENE_RESET", 'SCENE_HAS_KEY(schluessel$)   SCENE_DELETE(schluessel$)   SCENE_HAS(szene$)   SCENE_RESET()',
    "SCENE_HAS_KEY prüft, ob ein Wert gesetzt ist, SCENE_DELETE entfernt ihn. SCENE_HAS fragt, ob eine Szene dieses Namens überhaupt auf dem Stapel liegt. SCENE_RESET räumt alles ab – Stapel und Daten – der saubere Neustart nach „Spiel beenden“.",
    [
      'IF NOT SCENE_HAS_KEY("startzeit") THEN SCENE_SET_FLOAT("startzeit", GET_TIME())',
      'IF SCENE_HAS("pause") THEN PRINT "Pause liegt im Stapel"',
    ]),
  H.tip("Push für Overlays, Switch für Wechsel", "Merke: PUSH/POP für etwas, das ÜBER dem Bisherigen liegt und danach zurückkehrt (Pause, Inventar, Dialog). SWITCH für einen echten Wechsel ohne Rückweg (Menü → Spiel → Game Over). Beim Szenenwechsel solltest du auch laufende Timer aufräumen (TIMER_CLEAR, Kapitel „timer“)."),
];
