module.exports = (H) => [
  H.chapter("Modul: astar"),
  H.p("Wie findet ein Gegner den Weg zum Spieler, wenn Wände im Weg stehen? Das astar-Modul beantwortet genau das: Es sucht auf einem Kachelgitter den kürzesten Weg von A nach B um Hindernisse herum (mit dem bekannten A*-Algorithmus). Du legst ein Gitter an, markierst die Wände, rufst die Suche – und liest den gefundenen Pfad Schritt für Schritt aus."),
  H.figure("62_astar.png", "A* in Aktion: der kürzeste Pfad (gelb) vom Start (grün) zum Ziel (rot) führt diagonal und um die L-förmige Wand herum."),

  H.h2("Gitter & Wände"),
  H.cmd("ASTAR_NEW · ASTAR_SET_WALL · ASTAR_IS_WALL", 'ASTAR_NEW(breite, höhe)   ASTAR_SET_WALL(g, x, y)   ASTAR_IS_WALL(g, x, y)',
    "ASTAR_NEW erstellt ein Gitter (anfangs überall passierbar) und liefert ein ASTAR_GRID. ASTAR_SET_WALL macht eine Kachel unpassierbar, ASTAR_IS_WALL fragt ab, ob eine Kachel eine Wand ist.",
    [
      'IMPORT "astar"',
      'DIM grid AS ASTAR_GRID',
      'grid = ASTAR_NEW(15, 10)',
      'ASTAR_SET_WALL(grid, 5, 3)     \' eine Wand-Kachel',
      'PRINT ASTAR_IS_WALL(grid, 5, 3)',
    ], { out: ["TRUE"] }),
  H.cmd("ASTAR_SET_DIAGONAL", 'ASTAR_SET_DIAGONAL(g, erlaubt)',
    "Schaltet diagonale Bewegung an oder aus. Standardmäßig läuft der Pfad nur orthogonal (oben/unten/links/rechts); mit TRUE darf er auch diagonal gehen, was meist kürzere, natürlichere Wege ergibt.",
    [
      'ASTAR_SET_DIAGONAL(grid, TRUE)',
    ]),

  H.h2("Suchen & auslesen"),
  H.cmd("ASTAR_FIND", 'ASTAR_FIND(g, sx, sy, ex, ey)',
    "Sucht den kürzesten Weg von (sx, sy) nach (ex, ey) und legt ihn intern ab. Liefert TRUE, wenn ein Weg existiert, sonst FALSE (Ziel unerreichbar).",
    [
      'DIM ok AS BOOLEAN',
      'ok = ASTAR_FIND(grid, 0, 0, 14, 9)',
    ]),
  H.cmd("ASTAR_PATH_LEN · ASTAR_PATH_X · ASTAR_PATH_Y", 'ASTAR_PATH_LEN(g)   ASTAR_PATH_X(g, idx)   ASTAR_PATH_Y(g, idx)',
    "Nach erfolgreicher Suche liest du den Pfad aus: PATH_LEN ist die Anzahl der Wegpunkte (Start UND Ziel eingeschlossen), PATH_X/PATH_Y die Koordinaten des Wegpunkts idx. So führst du einen Gegner Kachel für Kachel entlang.",
    [
      'DIM g AS ASTAR_GRID',
      'g = ASTAR_NEW(5, 1)',
      'ASTAR_FIND(g, 0, 0, 3, 0)',
      'PRINT ASTAR_PATH_LEN(g)              \' 4: (0,0)(1,0)(2,0)(3,0)',
      'PRINT ASTAR_PATH_X(g, 1)            \' x des 2. Wegpunkts',
    ], { out: ["4", "1"] }),
  H.note("Der Pfad enthält Start- UND Zielpunkt. Bei einem direkten Nachbarschritt ist ASTAR_PATH_LEN also 2. Den ersten Schritt eines Gegners holst du dir folglich aus Index 1 (Index 0 ist seine aktuelle Position)."),

  H.h2("Einen Gegner steuern"),
  H.p("Typisch lässt du die Suche nur ab und zu laufen (nicht jeden Frame – das kostet) und bewegst den Gegner dann entlang der Wegpunkte. Skizze:"),
  H.code([
    'IMPORT "astar"',
    'DIM grid AS ASTAR_GRID',
    'grid = ASTAR_NEW(20, 15)',
    'ASTAR_SET_WALL(grid, 5, 5)   \' ... Wände aus dem Level ...',
    'ASTAR_SET_DIAGONAL(grid, TRUE)',
    '',
    '\' Weg vom Gegner zum Spieler suchen:',
    'IF ASTAR_FIND(grid, gegner_tx, gegner_ty, spieler_tx, spieler_ty) THEN',
    '    IF ASTAR_PATH_LEN(grid) >= 2 THEN',
    '        DIM nx AS INTEGER',
    '        DIM ny AS INTEGER',
    '        nx = ASTAR_PATH_X(grid, 1)   \' nächster Schritt',
    '        ny = ASTAR_PATH_Y(grid, 1)',
    '        \' ... Gegner Richtung (nx, ny) bewegen ...',
    '    END IF',
    'END IF',
  ]),
  H.tip("Gitter und Welt", "Das astar-Gitter denkt in Kacheln (0, 1, 2 …), deine Spielwelt in Pixeln. Rechne zwischen beiden um: kachel = pixel \\ kachelgröße und zurück pixel = kachel * kachelgröße. Oft passt das Gitter genau zu deiner Tilemap (nächstes Kapitel)."),
];
