module.exports = (H) => [
  H.chapter("Modul: tiled"),
  H.p("Größere Level malt man nicht im Code, sondern in einem Karten-Editor. Das tiled-Modul lädt Karten im verbreiteten Tiled-Format (als JSON) – egal ob du sie im Programm Tiled oder im mitgelieferten dhtilemap-Editor erstellt hast. Eine Karte besteht aus einem oder mehreren Ebenen (Layern) aus Kacheln, dazu optional Objekt-Ebenen für Spawn-Punkte und Zonen. Jede Kachel kann eigene Eigenschaften tragen (etwa „fest“ oder „Stachel“)."),
  H.figure("63_tiled.png", "Eine geladene Tiled-Karte (30×10 Kacheln): Boden, schwebende Plattformen und Münzen – per TILED_TILE_AT gezeichnet."),

  H.h2("Karte laden & Maße"),
  H.cmd("TILED_LOAD", 'TILED_LOAD(pfad$)',
    "Lädt eine Tiled-Karte (JSON) und liefert eine TILED_MAP. Die im Karten-Datei angegebenen Tileset-Bilder werden relativ zur Karte gefunden.",
    [
      'IMPORT "tiled"',
      'DIM lvl AS TILED_MAP',
      'lvl = TILED_LOAD("levels/level1.json")',
    ]),
  H.cmd("TILED_WIDTH/HEIGHT · TILED_TILE_WIDTH/HEIGHT", 'TILED_WIDTH(m)   TILED_HEIGHT(m)   TILED_TILE_WIDTH(m)   TILED_TILE_HEIGHT(m)',
    "WIDTH/HEIGHT liefern die Kartengröße in Kacheln, TILE_WIDTH/HEIGHT die Pixelgröße einer Kachel. Damit rechnest du zwischen Kachel- und Pixelkoordinaten um.",
    [
      'PRINT TILED_WIDTH(lvl); " x "; TILED_HEIGHT(lvl)   \' z. B. 30 x 10',
      'PRINT TILED_TILE_WIDTH(lvl)                         \' z. B. 16',
    ]),

  H.h2("Kacheln lesen & setzen"),
  H.cmd("TILED_TILE_AT · TILED_TILE_SET", 'TILED_TILE_AT(m, layer, tx, ty)   TILED_TILE_SET(m, layer, tx, ty, gid)',
    "TILED_TILE_AT liefert die GID (Kachelnummer) an Position (tx, ty) einer Ebene – 0 bedeutet „leer“. TILED_TILE_SET schreibt eine Kachel (gid 0 löscht sie) – nützlich, um z. B. eine eingesammelte Münze aus der Karte zu entfernen.",
    [
      'DIM gid AS INTEGER',
      'gid = TILED_TILE_AT(lvl, 0, 5, 8)',
      'IF gid > 0 THEN TILED_TILE_SET(lvl, 0, 5, 8, 0)   \' Kachel entfernen',
    ]),
  H.p("Zum Zeichnen läufst du über alle Kacheln, holst die GID und stempelst den passenden Ausschnitt des Tileset-Bildes – genau das ergibt das Bild oben:"),
  H.code([
    'DIM ts AS IMAGE',
    'ts = LOADIMAGE("assets/tiles.png")   \' Tileset (4 Spalten, 16x16)',
    'DIM tx AS INTEGER',
    'DIM ty AS INTEGER',
    'FOR ty = 0 TO TILED_HEIGHT(lvl) - 1',
    '    FOR tx = 0 TO TILED_WIDTH(lvl) - 1',
    '        DIM gid AS INTEGER',
    '        gid = TILED_TILE_AT(lvl, 0, tx, ty)',
    '        IF gid > 0 THEN',
    '            DIM i AS INTEGER',
    '            i = gid - 1                       \' GID -> Tileset-Index',
    '            DRAWIMAGEPART(ts, (i MOD 4) * 16, (i \\ 4) * 16, 16, 16, tx * 16, ty * 16)',
    '        END IF',
    '    NEXT',
    'NEXT',
  ]),

  H.h2("Kachel-Eigenschaften"),
  H.cmd("TILED_TILE_PROP_… · TILED_TILE_HAS_PROP", 'TILED_TILE_PROP_BOOL(m, gid, key$)   (auch INT/FLOAT/STRING)   TILED_TILE_HAS_PROP(m, gid, key$)',
    "Lesen eine im Editor gesetzte Eigenschaft einer Kachelart (über ihre GID). So markierst du etwa feste Kacheln mit „solid“ = TRUE oder Münzen mit „pickup“ = TRUE und fragst das im Spiel ab.",
    [
      'IF TILED_TILE_PROP_BOOL(lvl, gid, "solid") THEN',
      '    \' diese Kachel blockt den Spieler',
      'END IF',
    ]),

  H.h2("Objekt-Ebenen"),
  H.p("Neben Kacheln können Karten Objekte enthalten – Punkte oder Rechtecke mit Namen, Typ und eigenen Eigenschaften, etwa Spawn-Punkte, Trigger oder Zonen. Sie liegen in Objekt-Ebenen und werden über ihren Ebenennamen abgefragt."),
  H.cmd("TILED_OBJECT_COUNT · TILED_OBJECT_…", 'TILED_OBJECT_COUNT(m, ebene$)   TILED_OBJECT_X / _Y / _NAME(m, ebene$, idx) …',
    "TILED_OBJECT_COUNT liefert die Anzahl der Objekte einer Objekt-Ebene; mit den weiteren TILED_OBJECT_-Funktionen liest du Position, Name, Typ und Eigenschaften jedes Objekts aus – etwa um Gegner an den im Editor gesetzten Stellen zu erzeugen.",
    [
      'DIM n AS INTEGER',
      'n = TILED_OBJECT_COUNT(lvl, "spawns")',
      '\' ... über die n Objekte laufen und Gegner platzieren ...',
    ]),
  H.note("Für Editor- oder Generierungs-Aufgaben gibt es Massen-Operationen: TILED_FILL_RECT (Rechteck füllen), TILED_REPLACE (eine GID gegen eine andere tauschen), TILED_COUNT_GID (zählen) und TILED_FLOOD_FILL (Eimer-Füllung) – sie ändern viele Kacheln in einem Aufruf."),
  H.h2("Ebenen erkunden"),
  H.p("Eine Tiled-Karte besteht aus mehreren Ebenen – Boden, Deko, Kollision, dazu Objekt-Ebenen. Diese Befehle laufen sie durch, ohne dass du die Namen fest ins Programm schreiben musst."),
  H.cmd("TILED_LAYER_COUNT · TILED_LAYER_NAME · TILED_LAYER_INDEX · TILED_LAYER_TYPE", 'TILED_LAYER_COUNT(m)   TILED_LAYER_NAME(m, i)   TILED_LAYER_INDEX(m, name$)   TILED_LAYER_TYPE(m, i)',
    'Zählen, benennen und suchen. TILED_LAYER_INDEX liefert die Nummer zu einem Namen (-1, wenn es ihn nicht gibt), TILED_LAYER_TYPE unterscheidet "tilelayer" von "objectgroup".',
    [
      'DIM i AS INTEGER',
      'FOR i = 0 TO TILED_LAYER_COUNT(karte) - 1',
      '    PRINT TILED_LAYER_NAME(karte, i) + " (" + TILED_LAYER_TYPE(karte, i) + ")"',
      'NEXT',
      'DIM boden AS INTEGER',
      'boden = TILED_LAYER_INDEX(karte, "Boden")',
    ]),
  H.cmd("TILED_LAYER_WIDTH · TILED_LAYER_HEIGHT", 'TILED_LAYER_WIDTH(m, i)   TILED_LAYER_HEIGHT(m, i)',
    "Größe einer Ebene in Kacheln – nicht jede Ebene muss so groß sein wie die Karte.",
    [
      'PRINT TILED_LAYER_WIDTH(karte, boden)',
    ]),

  H.h2("Objekte: Startpunkte, Trigger, Zonen"),
  H.p("Neben den Kacheln kann eine Karte OBJEKTE enthalten – im Editor als Rechtecke oder Punkte gesetzt. Damit legt der Level-Designer fest, wo der Spieler startet, wo Gegner erscheinen oder welcher Bereich eine Falle auslöst, ohne dass du Koordinaten ins Programm schreibst."),
  H.cmd("TILED_OBJECT_NAME · TILED_OBJECT_TYPE · TILED_OBJECT_Y · TILED_OBJECT_WIDTH · TILED_OBJECT_HEIGHT", 'TILED_OBJECT_NAME(m, ebene$, i)   TILED_OBJECT_TYPE(m, ebene$, i)   TILED_OBJECT_Y(m, ebene$, i)   TILED_OBJECT_WIDTH(m, ebene$, i)   TILED_OBJECT_HEIGHT(m, ebene$, i)',
    "Lesen die Eigenschaften eines Objekts einer Objekt-Ebene (zusammen mit TILED_OBJECT_COUNT und TILED_OBJECT_X). Name und Typ vergibst du im Editor.",
    [
      'DIM n AS INTEGER',
      'FOR n = 0 TO TILED_OBJECT_COUNT(karte, "Spawns") - 1',
      '    IF TILED_OBJECT_TYPE(karte, "Spawns", n) = "gegner" THEN',
      '        gegner_setzen(TILED_OBJECT_X(karte, "Spawns", n), _',
      '                      TILED_OBJECT_Y(karte, "Spawns", n))',
      '    END IF',
      'NEXT',
    ]),
  H.cmd("TILED_OBJECT_PROP_STRING/INT/FLOAT/BOOL", 'TILED_OBJECT_PROP_STRING(m, ebene$, i, name$)   TILED_OBJECT_PROP_INT(...)   TILED_OBJECT_PROP_FLOAT(...)   TILED_OBJECT_PROP_BOOL(...)',
    "Eigene Eigenschaften eines Objekts, im Editor frei vergeben – etwa wie viel Schaden eine Falle macht oder in welches Level eine Tür führt. So steckt die Spielbalance in der Karte statt im Quelltext.",
    [
      'DIM schaden AS INTEGER',
      'schaden = TILED_OBJECT_PROP_INT(karte, "Fallen", n, "schaden")',
      'DIM ziel AS STRING',
      'ziel = TILED_OBJECT_PROP_STRING(karte, "Tueren", n, "ziel_level")',
    ]),
  H.cmd("TILED_TILE_PROP_STRING/INT/FLOAT", 'TILED_TILE_PROP_STRING(m, gid, name$)   TILED_TILE_PROP_INT(m, gid, name$)   TILED_TILE_PROP_FLOAT(m, gid, name$)',
    "Dasselbe für einzelne KACHEL-Arten: Im Tileset legst du je Kachel Eigenschaften fest (solid, damage, Reibung …), hier liest du sie über die Kachel-Nummer (gid) aus.",
    [
      'DIM gid AS INTEGER',
      'gid = TILED_TILE(karte, boden, kx, ky)',
      'IF TILED_TILE_PROP_INT(karte, gid, "damage") > 0 THEN leben = leben - 1',
    ]),

  H.h2("Tilesets"),
  H.cmd("TILED_TILESET_COUNT · TILED_TILESET_IMAGE · TILED_TILESET_FIRSTGID", 'TILED_TILESET_COUNT(m)   TILED_TILESET_IMAGE(m, i)   TILED_TILESET_FIRSTGID(m, i)',
    "Eine Karte kann mehrere Tilesets benutzen. Jedes bringt eine Bilddatei mit und beginnt bei einer bestimmten Kachel-Nummer (firstgid). Willst du selbst zeichnen, suchst du zu einer gid das Tileset mit dem größten firstgid, der noch kleiner oder gleich der gid ist.",
    [
      'DIM t AS INTEGER',
      'FOR t = 0 TO TILED_TILESET_COUNT(karte) - 1',
      '    PRINT TILED_TILESET_IMAGE(karte, t) + " ab gid " + STR$(TILED_TILESET_FIRSTGID(karte, t))',
      'NEXT',
    ]),
  H.tip("Karten erstellen", "Du musst Tiled-Karten nicht von Hand als JSON schreiben: Der mitgelieferte Editor dhtilemap malt Kacheln, verwaltet Ebenen und Eigenschaften und speichert genau das Format, das TILED_LOAD liest. Zum Abprüfen von Boden und Wänden passt das tile_collide-Modul (nächstes Kapitel) perfekt dazu."),
];
