module.exports = (H) => [
  H.chapter("Modul: tile_collide"),
  H.p("Eine Tiled-Karte (voriges Kapitel) zeichnet sich nicht von selbst auf Kollision. Das tile_collide-Modul liefert genau das fehlende Stück: Es schiebt eine rechteckige Spielfigur gegen die festen Kacheln einer Karte und stoppt sie sauber an Boden und Wänden – die Grundlage jeder Plattformer-Bewegung. Du musst die Kollisionslogik also nicht selbst schreiben."),
  H.figure("64_tilecollide.png", "Der rote Spieler-Block ist über TILE_SWEEP_Y gefallen und exakt auf der Boden-Kachelreihe gelandet."),

  H.h2("Bewegen mit Kollision: die Achsen-Sweeps"),
  H.p("Der Trick: Man bewegt nicht in beide Richtungen gleichzeitig, sondern getrennt – erst horizontal, dann vertikal. Jeder Sweep nimmt die aktuelle Box und eine gewünschte Verschiebung und liefert die NEUE, korrigierte Position plus die Information, ob dabei etwas getroffen wurde."),
  H.cmd("TILE_SWEEP_X · TILE_SWEEP_Y", 'TILE_SWEEP_X(map, layer, x, y, w, h, dx)   TILE_SWEEP_Y(map, layer, x, y, w, h, dy)',
    "Verschiebt die Box (x, y, w, h) um dx bzw. dy und stoppt sie an festen Kacheln. Jeder liefert ein Tupel (neue_position, getroffen): Element 0 ist die korrigierte X- bzw. Y-Position, Element 1 ist TRUE, wenn eine Wand im Weg war.",
    [
      'IMPORT "tile_collide"',
      'DIM r AS TUPLE',
      'r = TILE_SWEEP_Y(level, 0, px, py, PW, PH, vy)',
      'py = r[0]                  \' korrigierte Y-Position',
      'IF r[1] THEN vy = 0.0      \' gelandet -> Fallen stoppen',
    ]),
  H.cmd("TILE_IS_SOLID", 'TILE_IS_SOLID(map, layer, tx, ty)',
    "Prüft, ob die Kachel an (tx, ty) fest ist (Kachelkoordinaten). Praktisch für eigene Abfragen. Kacheln AUSSERHALB der Karte gelten als fest – so kann der Spieler nicht aus dem Level fallen, ohne dass du es extra abfangen musst.",
    [
      'IF TILE_IS_SOLID(level, 0, tx, ty) THEN \' hier ist Wand',
    ]),

  H.h2("Wann ist eine Kachel fest?"),
  H.p("Das Modul kennt zwei Wege, „fest“ zu bestimmen. Hat irgendeine Kachelart im Tileset eine Eigenschaft solid (im Editor gesetzt), zählt genau die als fest – so kannst du in derselben Ebene feste Böden und durchlässige Deko mischen. Hat das Tileset gar keine solid-Eigenschaft, gilt jede belegte Kachel (GID > 0) als fest – dann legst du üblicherweise eine eigene „collision“-Ebene nur mit Wänden an."),
  H.note("Faustregel: Für gemischte Ebenen (Boden fest, Gras-Deko durchlässig) im Editor das solid-Flag auf die festen Kacheln setzen. Für eine reine Wand-Ebene reicht die Convention „GID > 0 = fest“ ganz ohne Eigenschaften."),

  H.h2("Plattformer-Bewegung im Game-Loop"),
  H.p("Das volle Muster: horizontale Eingabe sweepen, dann Schwerkraft auf die vertikale Geschwindigkeit geben und vertikal sweepen. Trifft der Y-Sweep auf Boden, ist die Figur gelandet (Sprung wieder erlauben)."),
  H.code([
    'IMPORT "tile_collide"',
    'WHILE NOT QUITREQUESTED()',
    '    \' 1) horizontal',
    '    DIM vx AS FLOAT',
    '    vx = INPUT_AXIS("links", "rechts") * 2.0',
    '    DIM rx AS TUPLE',
    '    rx = TILE_SWEEP_X(level, 0, px, py, PW, PH, vx)',
    '    px = rx[0]',
    '',
    '    \' 2) Schwerkraft + vertikal',
    '    vy = vy + 0.4',
    '    DIM ry AS TUPLE',
    '    ry = TILE_SWEEP_Y(level, 0, px, py, PW, PH, vy)',
    '    py = ry[0]',
    '    DIM am_boden AS BOOLEAN',
    '    am_boden = ry[1]',
    '    IF am_boden THEN vy = 0.0',
    '    IF am_boden AND INPUT_PRESSED("springen") THEN vy = -7.0',
    '',
    '    \' ... Karte + Spieler zeichnen ...',
    '    FLIP()',
    'WEND',
  ]),
  H.tip("Der Dreiklang fürs Platformer-Spiel", "tiled lädt das Level, tile_collide lässt den Spieler darauf laufen, und das controller-Modul (nächstes Kapitel) verpackt Sprung-Komfort wie Coyote-Zeit und Sprung-Puffer obendrauf. Zusammen ergeben sie ein vollständiges Jump-’n’-Run-Fundament."),
];
