module.exports = (H) => [
  H.chapter("Modul: controller"),
  H.p("Mit tile_collide kannst du eine Figur über eine Karte bewegen. Das controller-Modul setzt eine fertige, gut anfühlende Plattformer-Steuerung obendrauf: Laufen, Springen, Schwerkraft – und vor allem die kleinen Komfort-Tricks, die ein Jump-’n’-Run angenehm machen (Coyote-Zeit, Sprung-Puffer, variable Sprunghöhe). Du fütterst pro Frame nur die Eingabe hinein und rufst ein Update; um Physik und Kollision kümmert sich das Modul."),
  H.figure("65_controller.png", "Der Character-Controller ist auf die Karte gefallen und steht – CHAR_ON_GROUND ist TRUE."),

  H.h2("Anlegen & der Drei-Schritt-Loop"),
  H.cmd("CHAR_NEW", 'CHAR_NEW(x, y, breite, höhe)',
    "Erzeugt einen Character-Controller mit Startposition und Kollisionsgröße. Liefert ein CHAR_CONTROLLER-Handle.",
    [
      'IMPORT "controller"',
      'DIM held AS CHAR_CONTROLLER',
      'held = CHAR_NEW(50.0, 100.0, 12.0, 14.0)',
    ]),
  H.cmd("CHAR_SET_INPUT · CHAR_UPDATE", 'CHAR_SET_INPUT(c, achse_x, sprung_gedrückt, sprung_gehalten)   CHAR_UPDATE(c, map, layer)',
    "CHAR_SET_INPUT übergibt die Eingabe dieses Frames: achse_x ist -1/0/+1 (links/rechts), sprung_gedrückt das einmalige Drücken, sprung_gehalten das Halten (für variable Sprunghöhe). CHAR_UPDATE berechnet dann Geschwindigkeit, kollidiert mit der Karte und setzt die Position. Mehr braucht es pro Frame nicht.",
    [
      'INPUT_UPDATE()',
      'CHAR_SET_INPUT(held, INPUT_AXIS("links","rechts"), _',
      '               INPUT_PRESSED("springen"), INPUT_HELD("springen"))',
      'CHAR_UPDATE(held, lvl, 0)',
    ]),

  H.h2("Zustand abfragen"),
  H.cmd("CHAR_X · CHAR_Y · CHAR_VX · CHAR_VY", 'CHAR_X(c)   CHAR_Y(c)   CHAR_VX(c)   CHAR_VY(c)',
    "Liefern Position und Geschwindigkeit der Figur – damit zeichnest du dein Sprite an die richtige Stelle.",
    [
      'DRAWIMAGE(sprite, CHAR_X(held), CHAR_Y(held))',
    ]),
  H.cmd("CHAR_ON_GROUND · CHAR_ON_WALL_LEFT/RIGHT", 'CHAR_ON_GROUND(c)   CHAR_ON_WALL_LEFT(c)   CHAR_ON_WALL_RIGHT(c)',
    "Sagen, ob die Figur gerade auf dem Boden steht bzw. an einer Wand anliegt – nützlich für die Animationswahl (stehen/laufen/fallen) oder für Wandsprünge.",
    [
      'IF CHAR_ON_GROUND(held) THEN \' laufen/stehen-Animation',
      'IF NOT CHAR_ON_GROUND(held) THEN \' Sprung/Fall-Animation',
    ]),

  H.h2("Spielgefühl einstellen"),
  H.p("Die Voreinstellungen fühlen sich schon gut an, aber du kannst alles justieren. Drei davon machen den Unterschied zwischen „hakelig“ und „flüssig“:"),
  H.bulletRich("Coyote-Zeit  ", "– kurz nach dem Verlassen einer Kante darf man noch springen (verzeiht zu spätes Drücken)."),
  H.bulletRich("Sprung-Puffer  ", "– drückt man kurz VOR der Landung Sprung, wird der Sprung gemerkt und beim Aufsetzen ausgelöst."),
  H.bulletRich("Variable Sprunghöhe  ", "– kurz getippt = kleiner Hüpfer, gehalten = hoher Sprung (wie bei Mario)."),
  H.cmd("CHAR_SET_MOVE_SPEED · _JUMP_VELOCITY · _GRAVITY", 'CHAR_SET_MOVE_SPEED(c, v)   CHAR_SET_JUMP_VELOCITY(c, v)   CHAR_SET_GRAVITY(c, g)',
    "Stellen Lauftempo, Sprungkraft und Schwerkraft ein. So machst du die Figur flinker, den Sprung höher oder die Fallbeschleunigung stärker.",
    [
      'CHAR_SET_MOVE_SPEED(held, 2.5)',
      'CHAR_SET_JUMP_VELOCITY(held, 7.0)',
      'CHAR_SET_GRAVITY(held, 0.3)',
    ]),
  H.cmd("CHAR_SET_COYOTE_TIME · _JUMP_BUFFER · _VARIABLE_JUMP", 'CHAR_SET_COYOTE_TIME(c, frames)   CHAR_SET_JUMP_BUFFER(c, frames)   CHAR_SET_VARIABLE_JUMP(c, an)',
    "Schalten die Komfort-Tricks. Die Zeiten sind in Frames (Standard je 6 ≈ 100 ms). COYOTE_TIME(c, 0) macht die Steuerung streng (Souls-like); VARIABLE_JUMP(c, FALSE) gibt jedem Sprung dieselbe Höhe.",
    [
      'CHAR_SET_COYOTE_TIME(held, 6)',
      'CHAR_SET_JUMP_BUFFER(held, 6)',
      'CHAR_SET_VARIABLE_JUMP(held, TRUE)',
    ]),

  H.h2("Eingreifen: Position & Geschwindigkeit setzen"),
  H.cmd("CHAR_SET_POS · CHAR_SET_VX · CHAR_SET_VY", 'CHAR_SET_POS(c, x, y)   CHAR_SET_VX(c, v)   CHAR_SET_VY(c, v)',
    "Setzen Position bzw. Geschwindigkeit direkt – CHAR_SET_POS zum Versetzen (Respawn, Tür), CHAR_SET_VX/VY für Rückstoß bei Treffern oder einen Wandsprung.",
    [
      'IF getroffen THEN',
      '    CHAR_SET_VX(held, richtung * 4.0)   \' Knockback',
      '    CHAR_SET_VY(held, -3.0)             \' kleiner Hüpfer hoch',
      'END IF',
    ]),

  H.h2("Die ganze Steuerung"),
  H.p("Pro Frame sind es nur drei Aufrufe – Eingabe lesen, hineingeben, updaten –, der Rest ist Zeichnen:"),
  H.code([
    'IMPORT "controller"',
    'DIM held AS CHAR_CONTROLLER',
    'held = CHAR_NEW(50.0, 100.0, 12.0, 14.0)',
    '',
    'WHILE NOT QUITREQUESTED()',
    '    INPUT_UPDATE()',
    '    CHAR_SET_INPUT(held, INPUT_AXIS("links", "rechts"), _',
    '                   INPUT_PRESSED("springen"), INPUT_HELD("springen"))',
    '    CHAR_UPDATE(held, lvl, 0)',
    '',
    '    CLS()',
    '    \' ... Karte zeichnen ...',
    '    DRAWIMAGE(sprite, CHAR_X(held), CHAR_Y(held))',
    '    FLIP()',
    'WEND',
  ]),
  H.tip("Der Plattformer-Baukasten", "tiled (Level) + tile_collide (Kollision) + controller (Steuerung) + sprite/animfsm (Figur) ergeben zusammen ein komplettes Jump-’n’-Run. Du verbindest fertige Module, statt alles selbst zu schreiben – genau dafür ist Teil V da."),
];
