module.exports = (H) => [
  H.chapter("Modul: vec2"),
  H.p("Position, Geschwindigkeit, Richtung – in 2D-Spielen rechnest du ständig mit Paaren aus x und y. Das vec2-Modul fasst so ein Paar zu einem 2D-Vektor zusammen und gibt dir die passende Mathematik dazu: addieren, skalieren, Länge messen, normalisieren, Abstand und mehr. Ein schöner Bonus: Die Operatoren +, -, * und / sind für Vektoren überladen, du rechnest also fast wie mit Zahlen. Vektoren sind unveränderlich – jede Rechnung liefert einen neuen Vektor."),
  H.figure("66_vec2.png", "Vektoren als Pfeile: v + w (gelb) ist die Summe von v (blau) und w (grün) – berechnet mit dem +-Operator."),

  H.h2("Erstellen & Bestandteile"),
  H.cmd("VEC2_NEW · VEC2_X · VEC2_Y", 'VEC2_NEW(x, y)   VEC2_X(v)   VEC2_Y(v)',
    "VEC2_NEW erzeugt einen Vektor aus x und y; VEC2_X/VEC2_Y lesen die beiden Anteile wieder heraus.",
    [
      'IMPORT "vec2"',
      'DIM v AS VEC2',
      'v = VEC2_NEW(3.0, 4.0)',
      'PRINT VEC2_X(v); " "; VEC2_Y(v)',
    ], { out: ["3.0 4.0"] }),

  H.h2("Rechnen mit Operatoren"),
  H.p("Statt jede Komponente einzeln zu addieren, schreibst du einfach v + w. Genauso funktionieren - (Differenz) und * (Skalieren mit einer Zahl). PRINT zeigt einen Vektor als Vec2(x, y)."),
  H.cmd("+  -  *  (überladen)", 'v + w   v - w   v * skalar',
    "Die arithmetischen Operatoren sind für Vektoren überladen: Addition/Subtraktion komponentenweise, Multiplikation mit einer Zahl skaliert (verlängert/verkürzt). Auch = und <> vergleichen zwei Vektoren.",
    [
      'DIM v AS VEC2',
      'DIM w AS VEC2',
      'v = VEC2_NEW(3.0, 4.0)',
      'w = VEC2_NEW(1.0, 2.0)',
      'PRINT v + w',
      'PRINT v * 2.0',
    ], { out: ["Vec2(4.0, 6.0)", "Vec2(6.0, 8.0)"] }),

  H.h2("Länge, Richtung, Abstand"),
  H.cmd("VEC2_LENGTH · VEC2_NORMALIZE", 'VEC2_LENGTH(v)   VEC2_NORMALIZE(v)',
    "VEC2_LENGTH liefert die Länge (den Betrag) eines Vektors. VEC2_NORMALIZE liefert einen Vektor gleicher Richtung, aber Länge 1 – die „reine Richtung“, ideal um danach mit einem Tempo zu multiplizieren.",
    [
      'DIM v AS VEC2',
      'v = VEC2_NEW(3.0, 4.0)',
      'PRINT VEC2_LENGTH(v)',
      'DIM r AS VEC2',
      'r = VEC2_NORMALIZE(v)',
      'PRINT ROUND(VEC2_X(r), 2); " "; ROUND(VEC2_Y(r), 2)',
    ], { out: ["5.0", "0.6 0.8"] }),
  H.cmd("VEC2_DISTANCE · VEC2_DOT", 'VEC2_DISTANCE(a, b)   VEC2_DOT(a, b)',
    "VEC2_DISTANCE misst den Abstand zwischen zwei Punkten (Vektoren). VEC2_DOT ist das Skalarprodukt – nützlich, um Winkel/Ausrichtung zu beurteilen (positiv = ähnliche Richtung).",
    [
      'PRINT ROUND(VEC2_DISTANCE(v, w), 3)',
      'PRINT VEC2_DOT(v, w)',
    ], { out: ["2.828", "11.0"] }),
  H.note("Weitere nützliche Funktionen: VEC2_LERP (zwischen zwei Vektoren interpolieren), VEC2_PERP (senkrechter Vektor), VEC2_REFLECT (an einer Fläche spiegeln), VEC2_ANGLE / VEC2_FROM_ANGLE (Richtung ↔ Winkel), VEC2_CROSS (Kreuzprodukt-Z)."),

  H.h2("Typisches Muster: in eine Richtung bewegen"),
  H.p("Ein Klassiker: ein Geschoss soll zum Ziel fliegen. Richtung berechnen, normalisieren, mit dem Tempo skalieren – dank Operatoren in wenigen Zeilen:"),
  H.code([
    'IMPORT "vec2"',
    'DIM pos AS VEC2',
    'DIM ziel AS VEC2',
    'pos  = VEC2_NEW(100.0, 100.0)',
    'ziel = VEC2_NEW(300.0, 180.0)',
    '',
    'DIM richtung AS VEC2',
    'richtung = VEC2_NORMALIZE(ziel - pos)   \' reine Richtung (Länge 1)',
    'DIM tempo AS FLOAT',
    'tempo = 4.0',
    'pos = pos + richtung * tempo            \' pro Frame ein Stück fliegen',
  ]),
  H.cmd("VEC2_ZERO · VEC2_LENGTH_SQ", 'VEC2_ZERO()   VEC2_LENGTH_SQ(v)',
    "VEC2_ZERO ist der Nullvektor als Startwert. VEC2_LENGTH_SQ liefert die QUADRIERTE Länge – ohne Wurzel und damit schneller. Für Vergleiche („ist der Gegner näher als 100 Pixel?“) reicht das völlig, du vergleichst dann mit dem Quadrat der Entfernung.",
    [
      'IF VEC2_LENGTH_SQ(gegner_pos - spieler_pos) < 100.0 * 100.0 THEN angreifen()',
    ]),
  H.tip("vec2 oder einzelne Zahlen?", "Für eine einzelne Position reichen oft zwei FLOAT-Variablen (px, py). Sobald du aber richtungsbasiert rechnest – normalisieren, Abstände, Reflektion –, machen Vektoren den Code kürzer und klarer. Für 3D gibt es das Schwester-Modul m3d (nächstes Kapitel) mit VEC3 und mehr."),
  H.h2("Winkel, Drehen, Spiegeln"),
  H.cmd("VEC2_ANGLE · VEC2_FROM_ANGLE", "VEC2_ANGLE(v)   VEC2_FROM_ANGLE(winkel, laenge)",
    "Der Weg zwischen Vektor und Winkel. VEC2_ANGLE liefert den Winkel im Bogenmaß, von der x-Achse aus gezählt; VEC2_FROM_ANGLE baut aus Winkel und Länge wieder einen Vektor. Zusammen sind das Polar- und Kartesische Koordinaten.",
    [
      'IMPORT "vec2"',
      "DIM v AS VEC2",
      "v = VEC2_FROM_ANGLE(RAD(45.0), 10.0)",
      "PRINT DEG(VEC2_ANGLE(v))       ' 45",
    ]),
  H.tip("So zielt ein Geschoss", "Richtung als Winkel ausrechnen ist umständlich; ein Vektor vom Schützen zum Ziel, normalisiert und mal Geschwindigkeit, ist derselbe Gedanke in einer Zeile. VEC2_FROM_ANGLE braucht man dort, wo der Winkel schon feststeht – bei einem Streuschuss oder einem rotierenden Geschützturm."),
  H.cmd("VEC2_PERP", "VEC2_PERP(v)",
    "Dreht den Vektor um 90 Grad gegen den Uhrzeigersinn: aus (x, y) wird (-y, x). Das ist die Senkrechte auf einer Richtung – die Normale einer Wand, die Seitwärtsbewegung zu einer Blickrichtung, die Breite eines Strichs entlang seines Verlaufs.",
    [
      "DIM richtung AS VEC2",
      "DIM seitlich AS VEC2",
      "richtung = VEC2_NEW(1.0, 0.0)",
      "seitlich = VEC2_PERP(richtung)      ' zeigt nach unten",
    ]),
  H.cmd("VEC2_REFLECT", "VEC2_REFLECT(v, n)",
    "Spiegelt einen Vektor an einer Normalen – der Abprall eines Balls an einer Wand, ohne die Trigonometrie von Hand. Die Normale muss normalisiert sein.",
    [
      "DIM tempo AS VEC2",
      "DIM wand AS VEC2",
      "tempo = VEC2_NEW(3.0, -2.0)",
      "wand = VEC2_NEW(0.0, 1.0)           ' Boden",
      "tempo = VEC2_REFLECT(tempo, wand)   ' (3, 2)",
    ]),
  H.cmd("VEC2_LERP", "VEC2_LERP(a, b, t)",
    "Interpoliert zwischen zwei Vektoren: t = 0 liefert a, t = 1 liefert b, 0.5 die Mitte. Damit gleitet eine Kamera weich zum Ziel, statt zu springen.",
    [
      "DIM kamera AS VEC2",
      "DIM ziel AS VEC2",
      "kamera = VEC2_NEW(0.0, 0.0)",
      "ziel = VEC2_NEW(100.0, 50.0)",
      "kamera = VEC2_LERP(kamera, ziel, 0.1)   ' pro Bild ein Zehntel naeher",
    ]),
  H.cmd("VEC2_CROSS", "VEC2_CROSS(a, b)",
    "Das Kreuzprodukt zweier 2D-Vektoren – in zwei Dimensionen eine einzelne Zahl, kein Vektor. Ihr Vorzeichen sagt, auf welcher Seite b von a liegt: positiv heißt links, negativ rechts, null heißt parallel. Genau das braucht ein Gegner, der wissen will, ob er nach links oder rechts drehen muss.",
    [
      "DIM blick AS VEC2",
      "DIM zum_ziel AS VEC2",
      "blick = VEC2_NEW(1.0, 0.0)",
      "zum_ziel = VEC2_NEW(1.0, 1.0)",
      "IF VEC2_CROSS(blick, zum_ziel) > 0.0 THEN",
      '    PRINT "Ziel liegt links"',
      "END IF",
    ]),
];
