module.exports = (H) => [
  H.chapter("Modul: vec2"),
  H.p("Position, Geschwindigkeit, Richtung – in 2D-Spielen rechnest du ständig mit Paaren aus x und y. Das vec2-Modul fasst so ein Paar zu einem 2D-Vektor zusammen und gibt dir die passende Mathematik dazu: addieren, skalieren, Länge messen, normalisieren, Abstand und mehr. Ein schöner Bonus: Die Operatoren +, -, * und / sind für Vektoren überladen, du rechnest also fast wie mit Zahlen. Vektoren sind unveränderlich – jede Rechnung liefert einen neuen Vektor."),
  H.figure("66_vec2.png", "Vektoren als Pfeile: v + w (gelb) ist die Summe von v (blau) und w (grün) – berechnet mit dem +-Operator."),

  H.h2("Erstellen & Bestandteile"),
  H.cmd("VEC2_NEW · VEC2_X · VEC2_Y", 'VEC2_NEW(x, y)   VEC2_X(v)   VEC2_Y(v)',
    "VEC2_NEW erzeugt einen Vektor aus x und y; VEC2_X/VEC2_Y lesen die beiden Anteile wieder heraus.",
    [
      'IMPORT "vec2"',
      'DIM v AS VEC2',
      'v = VEC2_NEW(3.0, 4.0)',
      'PRINT VEC2_X(v); " "; VEC2_Y(v)',
    ], { out: ["3.0 4.0"] }),

  H.h2("Rechnen mit Operatoren"),
  H.p("Statt jede Komponente einzeln zu addieren, schreibst du einfach v + w. Genauso funktionieren - (Differenz) und * (Skalieren mit einer Zahl). PRINT zeigt einen Vektor als Vec2(x, y)."),
  H.cmd("+  -  *  (überladen)", 'v + w   v - w   v * skalar',
    "Die arithmetischen Operatoren sind für Vektoren überladen: Addition/Subtraktion komponentenweise, Multiplikation mit einer Zahl skaliert (verlängert/verkürzt). Auch = und <> vergleichen zwei Vektoren.",
    [
      'DIM v AS VEC2',
      'DIM w AS VEC2',
      'v = VEC2_NEW(3.0, 4.0)',
      'w = VEC2_NEW(1.0, 2.0)',
      'PRINT v + w',
      'PRINT v * 2.0',
    ], { out: ["Vec2(4.0, 6.0)", "Vec2(6.0, 8.0)"] }),

  H.h2("Länge, Richtung, Abstand"),
  H.cmd("VEC2_LENGTH · VEC2_NORMALIZE", 'VEC2_LENGTH(v)   VEC2_NORMALIZE(v)',
    "VEC2_LENGTH liefert die Länge (den Betrag) eines Vektors. VEC2_NORMALIZE liefert einen Vektor gleicher Richtung, aber Länge 1 – die „reine Richtung“, ideal um danach mit einem Tempo zu multiplizieren.",
    [
      'DIM v AS VEC2',
      'v = VEC2_NEW(3.0, 4.0)',
      'PRINT VEC2_LENGTH(v)',
      'DIM r AS VEC2',
      'r = VEC2_NORMALIZE(v)',
      'PRINT ROUND(VEC2_X(r), 2); " "; ROUND(VEC2_Y(r), 2)',
    ], { out: ["5.0", "0.6 0.8"] }),
  H.cmd("VEC2_DISTANCE · VEC2_DOT", 'VEC2_DISTANCE(a, b)   VEC2_DOT(a, b)',
    "VEC2_DISTANCE misst den Abstand zwischen zwei Punkten (Vektoren). VEC2_DOT ist das Skalarprodukt – nützlich, um Winkel/Ausrichtung zu beurteilen (positiv = ähnliche Richtung).",
    [
      'PRINT ROUND(VEC2_DISTANCE(v, w), 3)',
      'PRINT VEC2_DOT(v, w)',
    ], { out: ["2.828", "11.0"] }),
  H.note("Weitere nützliche Funktionen: VEC2_LERP (zwischen zwei Vektoren interpolieren), VEC2_PERP (senkrechter Vektor), VEC2_REFLECT (an einer Fläche spiegeln), VEC2_ANGLE / VEC2_FROM_ANGLE (Richtung ↔ Winkel), VEC2_CROSS (Kreuzprodukt-Z)."),

  H.h2("Typisches Muster: in eine Richtung bewegen"),
  H.p("Ein Klassiker: ein Geschoss soll zum Ziel fliegen. Richtung berechnen, normalisieren, mit dem Tempo skalieren – dank Operatoren in wenigen Zeilen:"),
  H.code([
    'IMPORT "vec2"',
    'DIM pos AS VEC2',
    'DIM ziel AS VEC2',
    'pos  = VEC2_NEW(100.0, 100.0)',
    'ziel = VEC2_NEW(300.0, 180.0)',
    '',
    'DIM richtung AS VEC2',
    'richtung = VEC2_NORMALIZE(ziel - pos)   \' reine Richtung (Länge 1)',
    'DIM tempo AS FLOAT',
    'tempo = 4.0',
    'pos = pos + richtung * tempo            \' pro Frame ein Stück fliegen',
  ]),
  H.cmd("VEC2_ZERO · VEC2_LENGTH_SQ", 'VEC2_ZERO()   VEC2_LENGTH_SQ(v)',
    "VEC2_ZERO ist der Nullvektor als Startwert. VEC2_LENGTH_SQ liefert die QUADRIERTE Länge – ohne Wurzel und damit schneller. Für Vergleiche („ist der Gegner näher als 100 Pixel?“) reicht das völlig, du vergleichst dann mit dem Quadrat der Entfernung.",
    [
      'IF VEC2_LENGTH_SQ(gegner_pos - spieler_pos) < 100.0 * 100.0 THEN angreifen()',
    ]),
  H.tip("vec2 oder einzelne Zahlen?", "Für eine einzelne Position reichen oft zwei FLOAT-Variablen (px, py). Sobald du aber richtungsbasiert rechnest – normalisieren, Abstände, Reflektion –, machen Vektoren den Code kürzer und klarer. Für 3D gibt es das Schwester-Modul m3d (nächstes Kapitel) mit VEC3 und mehr."),
];
