module.exports = (H) => [
  H.chapter("Modul: json"),
  H.p("JSON ist das Standardformat, um strukturierte Daten als Text auszutauschen – Spielstände, Konfigurationsdateien, Antworten von Webdiensten. Das json-Modul liest solchen Text ein und lässt dich bequem über eine Pfad-Notation auf einzelne Felder zugreifen, ohne selbst Klammern zu zählen."),
  H.pmix([
    "Stell dir ein JSON-Dokument wie eine Schachtel mit beschrifteten Fächern vor: Ein ",
    [' Objekt ', true],
    " hat benannte Felder (",
    ['{"name": "Anna"}', true],
    "), ein ",
    [' Array ', true],
    " ist eine nummerierte Liste (",
    ['["a", "b"]', true],
    "). Beide dürfen ineinander verschachtelt sein. Du sprichst ein Feld tief im Inneren mit einem Pfad an – Punkt für Punkt von außen nach innen.",
  ]),

  H.h2("Einlesen: JSON_PARSE und JSON_LOAD"),
  H.p("JSON_PARSE liest einen String, JSON_LOAD eine Datei. Beide liefern ein JSON_HANDLE – den Griff, über den alle weiteren Befehle das Dokument ansprechen. Innerhalb eines Drachenhauch-String-Literals müssen Anführungszeichen verdoppelt werden (\"\" steht für ein \")."),
  H.cmd("JSON_PARSE · JSON_LOAD", 'JSON_PARSE(text$)   JSON_LOAD(pfad$)',
    "Wandelt JSON-Text bzw. eine JSON-Datei in ein JSON_HANDLE um. Bei ungültigem JSON (fehlende Klammer, Komma am Ende …) bricht der Befehl mit einem Fehler ab – am besten mit TRY/CATCH absichern.",
    [
      'IMPORT "json"',
      'DIM j AS JSON_HANDLE',
      'j = JSON_PARSE("{""hp"":100,""name"":""Held""}")',
      'PRINT JSON_GET_INT(j, "hp")',
      'PRINT JSON_GET_STRING(j, "name")',
    ], { out: ["100", "Held"] }),

  H.h2("Die Pfad-Notation"),
  H.p("Ein Pfad beschreibt den Weg zu einem Wert. Felder eines Objekts trennst du mit Punkt, Array-Einträge sprichst du über ihren Index an – ebenfalls mit Punkt. Ein leerer Pfad \"\" meint die Wurzel selbst."),
  H.bulletRich("\"user.name\"", " – Feld name im Unter-Objekt user."),
  H.bulletRich("\"hobbies.0\"", " – der erste Eintrag (Index 0) des Arrays hobbies."),
  H.bulletRich("\"items.2.titel\"", " – Feld titel des dritten Array-Eintrags."),

  H.h2("Werte lesen: die typsicheren Getter"),
  H.p("Für jeden Grundtyp gibt es einen eigenen Getter. Er liefert genau diesen Typ zurück – passt der Wert im Dokument nicht dazu, gibt es einen Fehler. So fällt ein Tippfehler in der Datenstruktur sofort auf, statt sich still durchzuschleichen."),
  H.cmd("JSON_GET_STRING · _INT · _FLOAT · _BOOL", 'JSON_GET_STRING(h, pfad$)   JSON_GET_INT(h, pfad$)   JSON_GET_FLOAT(h, pfad$)   JSON_GET_BOOL(h, pfad$)',
    "Liest den Wert am Pfad als String, Ganzzahl, Kommazahl bzw. Wahrheitswert. JSON_GET_INT akzeptiert auch glatte Floats (5.0 → 5), lehnt 3.14 aber ab.",
    [
      'IMPORT "json"',
      'DIM doc AS STRING',
      'doc = "{""user"":{""name"":""Anna"",""alter"":30,""aktiv"":true},""score"":98.5}"',
      'DIM j AS JSON_HANDLE',
      'j = JSON_PARSE(doc)',
      'PRINT JSON_GET_STRING(j, "user.name")',
      'PRINT JSON_GET_INT(j, "user.alter")',
      'PRINT JSON_GET_BOOL(j, "user.aktiv")',
      'PRINT JSON_GET_FLOAT(j, "score")',
    ], { out: ["Anna", "30", "TRUE", "98.5"] }),

  H.h2("Arrays durchlaufen: JSON_LEN"),
  H.p("Bei einer Liste willst du oft jeden Eintrag besuchen. JSON_LEN verrät die Länge des Arrays am Pfad; den Index hängst du dann als Text an den Pfad an."),
  H.cmd("JSON_LEN", 'JSON_LEN(h, pfad$)',
    "Liefert die Anzahl der Einträge eines Arrays (bzw. der Felder eines Objekts) am Pfad. Mit einer FOR-Schleife läufst du sie der Reihe nach durch.",
    [
      'IMPORT "json"',
      'DIM j AS JSON_HANDLE',
      'j = JSON_PARSE("{""hobbies"":[""Lesen"",""Code"",""Musik""]}")',
      'DIM i AS INTEGER',
      'FOR i = 0 TO JSON_LEN(j, "hobbies") - 1',
      '    PRINT JSON_GET_STRING(j, "hobbies." + STR$(i))',
      'NEXT',
    ], { out: ["Lesen", "Code", "Musik"] }),

  H.h2("Vorhandensein & Typ prüfen"),
  H.p("Nicht jedes Feld ist immer da, und manchmal weißt du den Typ nicht im Voraus. JSON_HAS prüft die Existenz, JSON_TYPE nennt die Art des Werts."),
  H.cmd("JSON_HAS", 'JSON_HAS(h, pfad$)',
    "TRUE, wenn am Pfad ein Wert existiert, sonst FALSE. Ideal für optionale Felder.",
    [
      'IMPORT "json"',
      'DIM j AS JSON_HANDLE',
      'j = JSON_PARSE("{""name"":""Anna""}")',
      'PRINT JSON_HAS(j, "name")',
      'PRINT JSON_HAS(j, "email")',
    ], { out: ["TRUE", "FALSE"] }),
  H.cmd("JSON_TYPE", 'JSON_TYPE(h, pfad$)',
    'Liefert den Typ am Pfad als String: "object", "array", "string", "number", "boolean", "null" – oder "missing", wenn der Pfad nicht existiert. Praktisch im SELECT CASE.',
    [
      'IMPORT "json"',
      'DIM j AS JSON_HANDLE',
      'j = JSON_PARSE("{""alter"":30,""tags"":[1,2]}")',
      'PRINT JSON_TYPE(j, "alter")',
      'PRINT JSON_TYPE(j, "tags")',
      'PRINT JSON_TYPE(j, "fehlt")',
    ], { out: ["number", "array", "missing"] }),

  H.h2("Zurück zu Text: JSON_STRINGIFY und JSON_PRETTY"),
  H.p("Manchmal willst du ein eingelesenes Dokument wieder als Text ausgeben – kompakt zum Speichern, oder schön eingerückt zum Anschauen."),
  H.cmd("JSON_STRINGIFY · JSON_PRETTY", 'JSON_STRINGIFY(h)   JSON_PRETTY(h)',
    "STRINGIFY erzeugt kompakten JSON-Text (eine Zeile, ohne Leerzeichen), PRETTY denselben Inhalt mit Einrückung und Zeilenumbrüchen.",
    [
      'IMPORT "json"',
      'DIM j AS JSON_HANDLE',
      'j = JSON_PARSE("{""hp"":100,""name"":""Held""}")',
      'PRINT JSON_PRETTY(j)',
    ], { out: ['{', '  "hp": 100,', '  "name": "Held"', '}'] }),

  H.h2("Fehler abfangen"),
  H.p("Daten von außen sind selten perfekt. Greifst du auf ein Feld mit dem falschen Getter zu oder ist das JSON kaputt, bricht der Befehl ab. Mit TRY/CATCH bleibt dein Programm trotzdem stehen und kann sinnvoll reagieren."),
  H.code([
    'IMPORT "json"',
    'DIM j AS JSON_HANDLE',
    'j = JSON_PARSE("{""name"":""Anna""}")',
    'TRY',
    '    DIM x AS INTEGER',
    '    x = JSON_GET_INT(j, "name")   \' name ist ein String!',
    'CATCH e',
    '    PRINT "Konnte alter nicht als Zahl lesen"',
    'END TRY',
  ], { out: ["Konnte alter nicht als Zahl lesen"] }),

  H.h2("JSON schreiben"),
  H.p("Lange ließ sich JSON hier nur lesen. Wer eines schreiben wollte, klebte Zeichenketten zusammen – und brach am ersten Anführungszeichen in einem Namen. Ein Handle ist deshalb veränderbar."),
  H.cmd("JSON_NEW_OBJECT · JSON_NEW_ARRAY", "JSON_NEW_OBJECT()   JSON_NEW_ARRAY()",
    "Legt ein leeres Objekt bzw. ein leeres Array an – der Anfang jedes selbst gebauten Dokuments.",
    [
      'IMPORT "json"',
      "DIM h AS JSON_HANDLE",
      "h = JSON_NEW_OBJECT()",
    ]),
  H.cmd("JSON_SET_STRING · JSON_SET_INT · JSON_SET_FLOAT · JSON_SET_BOOL · JSON_SET_NULL", "JSON_SET_STRING(h, pfad$, wert$)   JSON_SET_INT(h, pfad$, wert)",
    "Setzt ein Feld – legt es an, wenn es fehlt, und ersetzt es sonst. Fehlende Zwischenstufen entstehen als Objekt von selbst; genau deshalb ist ein tiefer Pfad ein Aufruf und nicht drei.",
    [
      'JSON_SET_STRING(h, "name", "Anna")',
      'JSON_SET_INT(h, "alter", 30)',
      'JSON_SET_BOOL(h, "aktiv", TRUE)',
      'JSON_SET_STRING(h, "adresse.ort", "Koeln")',
      "PRINT JSON_STRINGIFY(h)",
    ]),
  H.cmd("JSON_APPEND_STRING · JSON_APPEND_INT · JSON_APPEND_FLOAT · JSON_APPEND_BOOL · JSON_APPEND_JSON", "JSON_APPEND_STRING(h, pfad$, wert$)",
    "Hängt einen Wert an das Array am angegebenen Pfad an. Der leere Pfad meint hier das Dokument selbst – so füllt man ein frisch angelegtes Array.",
    [
      'IMPORT "json"',
      "DIM posten AS JSON_HANDLE",
      "posten = JSON_NEW_ARRAY()",
      'JSON_APPEND_STRING(posten, "", "Schraube")',
      'JSON_APPEND_STRING(posten, "", "Mutter")',
      "PRINT JSON_STRINGIFY(posten)",
    ]),
  H.cmd("JSON_SET_JSON", "JSON_SET_JSON(h, pfad$, andere)",
    "Hängt ein ganzes Dokument als Teilbaum ein – und zwar als Kopie. Ein JSON-Baum kann sich keinen Teilbaum mit einem anderen teilen; spätere Änderungen an der Quelle schlagen also nicht durch.",
    [
      'IMPORT "json"',
      "DIM h AS JSON_HANDLE",
      "DIM posten AS JSON_HANDLE",
      "h = JSON_NEW_OBJECT()",
      "posten = JSON_NEW_ARRAY()",
      'JSON_APPEND_STRING(posten, "", "Schraube")',
      'JSON_SET_JSON(h, "posten", posten)',
      'JSON_APPEND_STRING(h, "posten", "Unterlegscheibe")',
      "PRINT JSON_STRINGIFY(h)",
    ]),
  H.cmd("JSON_REMOVE · JSON_KEYS", "JSON_REMOVE(h, pfad$)   JSON_KEYS(h, pfad$)",
    "JSON_REMOVE entfernt ein Feld und sagt, ob dort etwas war. JSON_KEYS liefert die Feldnamen eines Objekts – damit lässt sich ein Objekt durchlaufen, dessen Aufbau man nicht kennt.",
    [
      'IMPORT "json"',
      "DIM h AS JSON_HANDLE",
      "DIM schluessel AS ARRAY OF STRING",
      "DIM i AS INTEGER",
      'h = JSON_PARSE("{""ort"":""Koeln"",""plz"":""50667""}")',
      'schluessel = JSON_KEYS(h, "")',
      "FOR i = 0 TO LEN(schluessel) - 1",
      '    PRINT schluessel[i]; " = "; JSON_GET_STRING(h, schluessel[i])',
      "NEXT",
    ]),
  H.warn("Ein Zahl-Segment legt nichts an. Ein Pfad wie \"posten.0\" auf einem frischen Dokument könnte ein Array meinen oder ein Objekt mit dem Schlüssel \"0\" – beides ist gültiges JSON, und die falsche Wahl fällt erst dem Empfänger auf. Statt zu raten sagt die Meldung, wie ein Array entsteht: mit JSON_NEW_ARRAY anlegen und mit JSON_APPEND_* füllen.",
    "Arrays entstehen nicht von selbst"),
  H.note("Der leere Pfad meint beim Schreiben NICHT die Wurzel. Beim Lesen tut er das; beim Setzen hieße er „das ganze Dokument wegwerfen“, und eine versehentlich leere Variable darf das nicht – JSON_SET_* lehnt ihn ab. Bei JSON_APPEND_* ist er erlaubt, dort geht nichts verloren, und meint das Dokument selbst.",
    "Merke"),

  H.tip("Konfigurationsdateien", "Ein typisches Muster: Spiel-Einstellungen in einer settings.json ablegen und beim Start mit JSON_LOAD lesen. Prüfe mit FILEEXISTS, ob die Datei da ist, und fülle sonst Standardwerte – so läuft das Spiel auch beim allerersten Start. Zum dauerhaften Speichern von Spielständen ist das save-Modul (Kapitel 61) bequemer, weil es das Schreiben gleich mit erledigt."),
];
