module.exports = (H) => [
  H.chapter("Modul: db"),
  H.p("Sobald ein Spiel mehr Daten verwalten muss als ein paar Variablen – eine Bestenliste, ein Inventar, Quest-Fortschritte über viele Sitzungen – lohnt sich eine echte Datenbank. Das db-Modul bindet SQLite ein: eine vollständige SQL-Datenbank, die ihre Daten in einer einzigen Datei hält (oder ganz im Arbeitsspeicher). Du brauchst keine Installation und keinen Server."),
  H.note("Dieses Kapitel setzt Grundkenntnisse in SQL voraus (CREATE TABLE, INSERT, SELECT, UPDATE, DELETE). Eine vollständige SQL-Einführung sprengt den Rahmen; die hier gezeigten Befehle reichen aber für die allermeisten Spiel-Anwendungen, und du kannst die SQL-Strings 1:1 übernehmen und anpassen."),

  H.h2("Verbinden und wieder schließen"),
  H.p('DB_OPEN öffnet (oder erstellt) eine Datenbank und liefert eine DB_CONN-Verbindung. Als Pfad nimmst du einen Dateinamen für eine dauerhafte Datenbank oder den besonderen Wert ":memory:" für eine flüchtige Datenbank, die nur im Arbeitsspeicher lebt und beim Programmende verschwindet (ideal zum Ausprobieren). Am Ende schließt DB_CLOSE die Verbindung.'),
  H.cmd("DB_OPEN · DB_CLOSE", 'DB_OPEN(pfad$)   DB_CLOSE(conn)',
    'Öffnet/erstellt die Datenbank, gibt eine DB_CONN zurück. ":memory:" = flüchtige In-Memory-DB. DB_CLOSE gibt die Verbindung am Programmende frei.',
    [
      'IMPORT "db"',
      'DIM con AS DB_CONN',
      'con = DB_OPEN(":memory:")',
      'DB_EXEC(con, "CREATE TABLE scores (name TEXT, score INTEGER)")',
      'PRINT "Tabelle angelegt"',
      'DB_CLOSE(con)',
    ], { out: ["Tabelle angelegt"] }),

  H.h2("Schreiben: DB_EXEC mit Parameter-Binding"),
  H.p("DB_EXEC führt jedes SQL-Statement aus, das keine Zeilen zurückliefert – also CREATE, INSERT, UPDATE, DELETE. Werte setzt du niemals direkt in den SQL-String ein, sondern schreibst ein Fragezeichen ? als Platzhalter und übergibst den Wert als weiteres Argument. Das ist sicherer (kein „SQL-Injection“) und kümmert sich um Anführungszeichen und Sonderzeichen automatisch."),
  H.cmd("DB_EXEC", 'DB_EXEC(conn, sql$ [, wert1, wert2, ...])',
    "Führt ein SQL-Statement aus; jedes ? im SQL wird der Reihe nach durch die folgenden Werte ersetzt. Rückgabe ist die Anzahl betroffener Zeilen. Erlaubte Wert-Typen: INTEGER, FLOAT, STRING, BOOLEAN (als 0/1) und NIL (wird zu SQL-NULL).",
    [
      'IMPORT "db"',
      'DIM con AS DB_CONN',
      'con = DB_OPEN(":memory:")',
      'DB_EXEC(con, "CREATE TABLE scores (name TEXT, score INTEGER)")',
      'DB_EXEC(con, "INSERT INTO scores VALUES (?, ?)", "Anna", 95)',
      'DB_EXEC(con, "INSERT INTO scores VALUES (?, ?)", "Bert", 88)',
      'DIM rc AS INTEGER',
      'rc = DB_EXEC(con, "UPDATE scores SET score = score + 10 WHERE name = ?", "Anna")',
      'PRINT rc, "Zeile(n) geaendert"',
    ], { out: ["1 Zeile(n) geaendert"] }),
  H.cmd("DB_LAST_ROWID", 'DB_LAST_ROWID(conn)',
    "Liefert die rowid (interne Zeilennummer) der zuletzt eingefügten Zeile – praktisch, um eine gerade erzeugte ID weiterzuverwenden.",
    [
      'IMPORT "db"',
      'DIM con AS DB_CONN',
      'con = DB_OPEN(":memory:")',
      'DB_EXEC(con, "CREATE TABLE scores (name TEXT, score INTEGER)")',
      'DB_EXEC(con, "INSERT INTO scores VALUES (?, ?)", "Anna", 95)',
      'DB_EXEC(con, "INSERT INTO scores VALUES (?, ?)", "Bert", 88)',
      'PRINT "Letzte rowid:", DB_LAST_ROWID(con)',
    ], { out: ["Letzte rowid: 2"] }),

  H.h2("Lesen: DB_QUERY und die Ergebnis-Schleife"),
  H.p("Ein SELECT liefert Zeilen – dafür gibt es DB_QUERY. Das Ergebnis ist ein DB_RESULT, eine Art Cursor. Du holst die Zeilen einzeln: DB_NEXT rückt zur nächsten Zeile vor und liefert TRUE, solange es eine gibt. Innerhalb der Schleife liest du die Spalten mit den typisierten DB_GET_*-Befehlen über ihren 0-basierten Index (Spalte 0 = erste Spalte im SELECT)."),
  H.cmd("DB_QUERY · DB_NEXT · DB_GET_* · DB_CLOSE_RESULT", 'DB_QUERY(conn, sql$ [, ...])   DB_NEXT(r)   DB_GET_STRING/INT/FLOAT/BOOL(r, idx)   DB_CLOSE_RESULT(r)',
    "DB_QUERY startet die Abfrage, DB_NEXT geht Zeile für Zeile durch (TRUE = es gibt eine Zeile), die DB_GET_*-Befehle lesen die Spalten der aktuellen Zeile. Am Ende gibt DB_CLOSE_RESULT den Cursor frei.",
    [
      'IMPORT "db"',
      'DIM con AS DB_CONN',
      'con = DB_OPEN(":memory:")',
      'DB_EXEC(con, "CREATE TABLE scores (name TEXT, score INTEGER)")',
      'DB_EXEC(con, "INSERT INTO scores VALUES (?, ?)", "Anna", 95)',
      'DB_EXEC(con, "INSERT INTO scores VALUES (?, ?)", "Bert", 88)',
      'DIM r AS DB_RESULT',
      'r = DB_QUERY(con, "SELECT name, score FROM scores ORDER BY score DESC")',
      'WHILE DB_NEXT(r)',
      '    PRINT DB_GET_STRING(r, 0), DB_GET_INT(r, 1)',
      'WEND',
      'DB_CLOSE_RESULT(r)',
    ], { out: ["Anna 95", "Bert 88"] }),

  H.h2("Fehlende Werte: NULL"),
  H.p("In SQL bedeutet NULL „kein Wert“. Die DB_GET_*-Befehle liefern bei NULL einen Standardwert (0, 0.0, \"\", FALSE). Willst du echtes Fehlen erkennen, fragst du vorher mit DB_IS_NULL."),
  H.cmd("DB_IS_NULL", 'DB_IS_NULL(r, idx)',
    "TRUE, wenn die Spalte in der aktuellen Zeile NULL ist. So unterscheidest du „leer/0“ von „nicht gesetzt“.",
    [
      'IMPORT "db"',
      'DIM con AS DB_CONN',
      'con = DB_OPEN(":memory:")',
      'DB_EXEC(con, "CREATE TABLE users (name TEXT, email TEXT)")',
      '\' email weggelassen -> bleibt NULL',
      'DB_EXEC(con, "INSERT INTO users (name) VALUES (?)", "Anna")',
      'DIM r AS DB_RESULT',
      'r = DB_QUERY(con, "SELECT name, email FROM users")',
      'IF DB_NEXT(r) THEN',
      '    PRINT DB_GET_STRING(r, 0)',
      '    IF DB_IS_NULL(r, 1) THEN PRINT "(keine Email)"',
      'END IF',
      'DB_CLOSE_RESULT(r)',
    ], { out: ["Anna", "(keine Email)"] }),

  H.h2("Spalten erkunden: DB_COL_COUNT / DB_COL_NAME"),
  H.cmd("DB_COL_COUNT · DB_COL_NAME", 'DB_COL_COUNT(r)   DB_COL_NAME(r, idx)',
    "Anzahl und Namen der Spalten eines Ergebnisses – nützlich für generische Ausgaben oder Debug-Werkzeuge.",
    [
      'IMPORT "db"',
      'DIM con AS DB_CONN',
      'con = DB_OPEN(":memory:")',
      'DB_EXEC(con, "CREATE TABLE scores (name TEXT, score INTEGER)")',
      'DIM r AS DB_RESULT',
      'r = DB_QUERY(con, "SELECT name, score FROM scores")',
      'DIM i AS INTEGER',
      'FOR i = 0 TO DB_COL_COUNT(r) - 1',
      '    PRINT i, DB_COL_NAME(r, i)',
      'NEXT',
      'DB_CLOSE_RESULT(r)',
    ], { out: ["0 name", "1 score"] }),

  H.h2("Transaktionen: alles oder nichts"),
  H.p("Normalerweise wird jedes DB_EXEC sofort dauerhaft gespeichert. Manchmal gehören aber mehrere Änderungen zusammen und sollen nur gemeinsam gültig werden – etwa Gold abziehen UND Gegenstand einbuchen. DB_BEGIN startet eine Transaktion, DB_COMMIT schreibt alles auf einmal fest, DB_ROLLBACK verwirft im Fehlerfall alles. Zusammen mit TRY/CATCH bleibt die Datenbank so immer konsistent."),
  H.cmd("DB_BEGIN · DB_COMMIT · DB_ROLLBACK", 'DB_BEGIN(conn)   DB_COMMIT(conn)   DB_ROLLBACK(conn)',
    "Klammern mehrere Statements zu einer Einheit. Bei einem Fehler im TRY-Block macht DB_ROLLBACK alle Änderungen seit DB_BEGIN rückgängig.",
    [
      'DB_BEGIN(con)',
      'TRY',
      '    DB_EXEC(con, "UPDATE konto SET gold = gold - ?", 50)',
      '    DB_EXEC(con, "INSERT INTO inventar VALUES (?)", "Schwert")',
      '    DB_COMMIT(con)',
      'CATCH e',
      '    DB_ROLLBACK(con)',
      '    PRINT "Kauf fehlgeschlagen, zurueckgerollt"',
      'END TRY',
    ]),

  H.cmd("DB_GET_FLOAT · DB_GET_BOOL", 'DB_GET_FLOAT(r, spalte)   DB_GET_BOOL(r, spalte)',
    "Die restlichen Spalten-Typen neben DB_GET_INT und DB_GET_STRING – Kommazahlen (Preise, Zeiten) und Wahrheitswerte.",
    [
      'PRINT DB_GET_FLOAT(res, 2)',
    ]),
  H.tip("Sauber arbeiten", "Drei Gewohnheiten ersparen viel Ärger: (1) Schema mit „CREATE TABLE IF NOT EXISTS …“ anlegen, dann ist mehrfaches Programm-Starten ungefährlich. (2) Jedes DB_RESULT nach Gebrauch mit DB_CLOSE_RESULT schließen. (3) Werte immer per ? binden, nie in den SQL-String hineinbauen. Für ganz einfache Spielstände (ein paar Zahlen und Strings) ist übrigens das save-Modul aus Kapitel 61 leichtgewichtiger – db lohnt sich, sobald es um Listen, Suchen und Sortieren geht."),
  H.h2("Abfragen im Hintergrund"),
  H.p("Eine Abfrage über eine große Tabelle hält das Programm an, bis sie fertig ist – im Fenster heißt das ein Ruckler oder eine Sekunde Stillstand. Dafür gibt es dieselbe Abfrage zum Nachsehen statt zum Warten, mit demselben Muster wie bei HTTP und TASK."),
  H.cmd("DB_QUERY_START · DB_QUERY_READY · DB_QUERY_RESULT", "DB_QUERY_START(datei$, sql$[, params…])   DB_QUERY_READY(auftrag)   DB_QUERY_RESULT(auftrag)",
    "DB_QUERY_START öffnet die Datei selbst und startet die Abfrage im Hintergrund; es liefert sofort eine Auftragsnummer. DB_QUERY_READY fragt nach, DB_QUERY_RESULT holt das DB_RESULT ab und gibt den Platz frei.",
    [
      'IMPORT "db"',
      "DIM auftrag AS INTEGER",
      "DIM erg AS DB_RESULT",
      'auftrag = DB_QUERY_START("spiel.db", "SELECT * FROM bestenliste ORDER BY punkte DESC")',
      "",
      "WHILE NOT QUITREQUESTED()",
      "    CLS()",
      "    IF auftrag >= 0 AND DB_QUERY_READY(auftrag) THEN",
      "        erg = DB_QUERY_RESULT(auftrag)",
      "        auftrag = -1",
      "    END IF",
      "    FLIP()",
      "WEND",
    ]),
  H.cmd("DB_QUERY_CANCEL · DB_QUERY_PENDING", "DB_QUERY_CANCEL(auftrag)   DB_QUERY_PENDING()",
    "Eine Abfrage verwerfen bzw. zählen, wie viele noch offen sind. Eine unbekannte Nummer bei DB_QUERY_CANCEL ist wirkungslos.",
    [
      "PRINT DB_QUERY_PENDING()",
    ]),
  H.note("Die Auftragsnummer auf -1 zu setzen, sobald das Ergebnis abgeholt ist, ist kein Schmuck: Ohne das würde die Schleife im nächsten Bild erneut abholen wollen – und die Nummer gibt es dann nicht mehr.",
    "Merke"),
];
