module.exports = (H) => [
  H.chapter("Modul: regex"),
  H.p("Reguläre Ausdrücke (kurz „Regex“) sind eine kleine Sprache, um Muster in Text zu beschreiben: „eine Folge von Ziffern“, „ein Wort gefolgt von einer Zahl“, „alles zwischen zwei Klammern“. Überall, wo INSTR und SPLIT zu schwach werden – Highscore-Zeilen zerlegen, Eingaben prüfen, Texte umschreiben – ist regex das richtige Werkzeug."),
  H.pmix([
    "Ein Muster ist selbst ein String, der Sonderzeichen enthält. ",
    ['\\d', true],
    " steht für eine Ziffer, ",
    ['+', true],
    " für „ein- oder mehrmals“ – ",
    ['\\d+', true],
    " bedeutet also „eine oder mehr Ziffern“. Solche Bausteine kombinierst du zu beliebig genauen Mustern.",
  ]),

  H.h2("Die wichtigsten Muster-Bausteine"),
  H.bulletRich("\\d  \\w  \\s", " – eine Ziffer · ein Wortzeichen (Buchstabe/Ziffer/_) · ein Leerzeichen/Tab. Großgeschrieben (\\D \\W \\S) jeweils das Gegenteil."),
  H.bulletRich(".", " – ein beliebiges Zeichen."),
  H.bulletRich("[abc]  [a-z]  [^x]", " – eins aus der Menge · ein Bereich · alles außer x."),
  H.bulletRich("*  +  ?", " – null oder mehr · ein oder mehr · null oder eins."),
  H.bulletRich("{n}  {n,m}", " – genau n bzw. zwischen n und m Wiederholungen."),
  H.bulletRich("( … )", " – eine Capture-Gruppe (merkt sich den Treffer-Teil)."),
  H.bulletRich("^  $   a|b", " – Anfang · Ende · „a oder b“."),
  H.note("In GameBasic-Strings ist der Backslash KEIN Sonderzeichen – du schreibst das Muster also direkt als \"\\d+\", nicht \"\\\\d+\". Das macht Regex-Strings angenehm lesbar."),

  H.h2("Prüfen: MATCH, TEST und FIND"),
  H.p("Drei Befehle beantworten unterschiedliche Fragen. REGEX_MATCH verlangt, dass das Muster den GESAMTEN Text abdeckt. REGEX_TEST fragt nur, ob das Muster irgendwo vorkommt. REGEX_FIND liefert den ersten passenden Textausschnitt zurück."),
  H.cmd("REGEX_MATCH · REGEX_TEST · REGEX_FIND", 'REGEX_MATCH(text$, muster$)   REGEX_TEST(text$, muster$)   REGEX_FIND(text$, muster$)',
    "MATCH = passt das ganze Wort? (BOOLEAN). TEST = kommt es irgendwo vor? (BOOLEAN). FIND = liefert den ersten Treffer als String (leerer String, wenn nichts passt – kein NIL-Check nötig).",
    [
      'IMPORT "regex"',
      'PRINT REGEX_MATCH("123", "\\d+")',
      'PRINT REGEX_MATCH("123 hi", "\\d+")',
      'PRINT REGEX_TEST("123 hi", "\\d+")',
      'PRINT REGEX_FIND("Punkte: 456 von 999", "\\d+")',
    ], { out: ["TRUE", "FALSE", "TRUE", "456"] }),

  H.h2("Alle Treffer sammeln: FIND_ALL"),
  H.p("REGEX_FIND_ALL liefert ein ARRAY OF STRING mit allen (nicht überlappenden) Treffern – ideal, um etwa alle Zahlen aus einer Zeile zu ziehen."),
  H.cmd("REGEX_FIND_ALL", 'REGEX_FIND_ALL(text$, muster$)',
    "Gibt alle Treffer als ARRAY OF STRING zurück. Enthält das Muster Klammern (eine Capture-Gruppe), wird der Inhalt dieser Gruppe gesammelt – nicht der ganze Treffer.",
    [
      'IMPORT "regex"',
      'DIM nums AS ARRAY OF STRING',
      'nums = REGEX_FIND_ALL("Hp: 80, Mp: 30, Lv: 5", "\\d+")',
      'DIM i AS INTEGER',
      'FOR i = 0 TO LEN(nums) - 1',
      '    PRINT nums[i]',
      'NEXT',
    ], { out: ["80", "30", "5"] }),
  H.cmd("FIND_ALL mit Capture-Gruppe", 'REGEX_FIND_ALL(text$, "vor (gruppe) nach")',
    "Mit Klammern extrahierst du gezielt einen Teil jedes Treffers. Hier wird nur die IP-Adresse hinter „ip “ herausgezogen, nicht das „ip “ selbst.",
    [
      'IMPORT "regex"',
      'DIM ips AS ARRAY OF STRING',
      'ips = REGEX_FIND_ALL("ip 10.0.0.1, fw 192.168.1.1", "ip (\\d+\\.\\d+\\.\\d+\\.\\d+)")',
      'PRINT ips[0]',
    ], { out: ["10.0.0.1"] }),

  H.h2("Ersetzen: REPLACE und REPLACE_ONCE"),
  H.p("REGEX_REPLACE ersetzt alle Treffer durch einen Ersatztext, REGEX_REPLACE_ONCE nur den ersten. Im Ersatztext beziehst du dich mit \\1, \\2 … auf die Capture-Gruppen des Musters – so kannst du Textteile umstellen."),
  H.cmd("REGEX_REPLACE · REGEX_REPLACE_ONCE", 'REGEX_REPLACE(text$, muster$, ersatz$)   REGEX_REPLACE_ONCE(text$, muster$, ersatz$)',
    "Ersetzt alle bzw. nur den ersten Treffer. \\1, \\2 … im Ersatz stehen für die gefundenen Gruppen.",
    [
      'IMPORT "regex"',
      'PRINT REGEX_REPLACE("Hello WORLD", "WORLD", "GameBasic")',
      'PRINT REGEX_REPLACE("Anna 30, Bob 25", "(\\w+) (\\d+)", "\\2 (\\1)")',
      'PRINT REGEX_REPLACE_ONCE("ha ha ha", "ha", "OK")',
    ], { out: ["Hello GameBasic", "30 (Anna), 25 (Bob)", "OK ha ha"] }),

  H.h2("Zerlegen: REGEX_SPLIT"),
  H.p("REGEX_SPLIT ist wie SPLIT, nur dass die Trennstelle ein Muster ist. So zerlegst du z. B. an beliebig viel Whitespace oder an Kommas mit optionalen Leerzeichen drumherum."),
  H.cmd("REGEX_SPLIT", 'REGEX_SPLIT(text$, muster$)',
    "Teilt den Text an jedem Treffer des Musters und liefert die Stücke als ARRAY OF STRING.",
    [
      'IMPORT "regex"',
      'DIM parts AS ARRAY OF STRING',
      'parts = REGEX_SPLIT("a, b , c,d", "\\s*,\\s*")',
      'PRINT LEN(parts)',
      'PRINT parts[0]; "|"; parts[1]; "|"; parts[2]; "|"; parts[3]',
    ], { out: ["4", "a|b|c|d"] }),

  H.warn("Rust-Regex: keine Lookarounds/Backrefs IM Muster", "Die native Runtime nutzt die Rust-Regex-Engine. Sie deckt alle obigen Bausteine ab, unterstützt aber KEINE Lookaheads/Lookbehinds ((?=…), (?<=…)) und keine Rückverweise (\\1) IM Muster selbst. Im ERSATZ-Text von REGEX_REPLACE sind \\1, \\2 dagegen erlaubt (wie oben gezeigt). Bei einem ungültigen Muster bricht der Befehl mit einer Fehlermeldung ab."),
  H.tip("Muster einmal, Nutzung oft", "regex merkt sich jedes übersetzte Muster (Pattern-Cache). Du kannst dasselbe Muster also bedenkenlos in einer Schleife über tausende Zeilen verwenden – es wird nur einmal aufgebaut. Praktische Einsätze: Eingabe-Validierung (Datum \"\\d{4}-\\d{2}-\\d{2}\", E-Mail-Grobcheck), Highscore-Parser, Chat-Wortfilter (REGEX_REPLACE der bösen Wörter durch \"***\")."),
];
