module.exports = (H) => [
  H.chapter("Modul: audio (fortgeschritten)"),
  H.p("Kapitel 46 hat die Grundlagen gezeigt: Töne und Sounds laden und abspielen. Das audio-Modul kann aber noch viel mehr. Es ist eine vollständige Audio-Engine (auf Basis von Kira), die auf einem eigenen Thread läuft – dein Game-Loop kann also ruckeln, ohne dass der Klang stottert. Dieses Kapitel zeigt die fortgeschrittenen Werkzeuge: einzelne Kanäle steuern, Stereo-Panorama bewegen, Sounds als Samples in Tonhöhen spielen, und Echtzeit-Effekte wie Hall, Echo oder Filter auf ganze Bus-Gruppen legen."),
  H.note("Klang lässt sich im Buch nicht abdrucken – probiere die Beispiele am besten selbst aus. Die meisten Befehle hier liefern keine Konsolen-Ausgabe; sie wirken auf das, was du hörst."),

  H.h2("Kanäle: AUDIO_PLAY und seine Steuerung"),
  H.p("Wenn du einen Sound mit AUDIO_PLAY startest, bekommst du eine Kanal-Nummer (INTEGER) zurück. Über diese Nummer steuerst du genau diese eine laufende Wiedergabe – anhalten, fortsetzen, lauter/leiser, Tonhöhe ändern – während andere Sounds unbeeinflusst weiterlaufen."),
  H.cmd("AUDIO_PLAY · AUDIO_STOP · AUDIO_IS_PLAYING", 'AUDIO_PLAY(sound [, loops, vol, ...])   AUDIO_STOP(ch)   AUDIO_IS_PLAYING(ch)',
    "AUDIO_PLAY startet einen Sound und liefert seine Kanal-Nummer. AUDIO_STOP beendet diesen Kanal, AUDIO_IS_PLAYING prüft, ob er noch klingt.",
    [
      'IMPORT "audio"',
      'DIM s AS SOUND',
      's = AUDIO_TONE(440.0, 400, "square", 0.5)',
      'DIM ch AS INTEGER',
      'ch = AUDIO_PLAY(s)',
      'PRINT AUDIO_IS_PLAYING(ch)',
      'AUDIO_STOP(ch)',
    ], { out: ["TRUE"] }),
  H.cmd("AUDIO_PAUSE · AUDIO_RESUME", 'AUDIO_PAUSE(ch)   AUDIO_RESUME(ch)   AUDIO_PAUSE_ALL()   AUDIO_RESUME_ALL()',
    "Hält einen Kanal an, ohne ihn zu beenden, und setzt ihn später an derselben Stelle fort. Die _ALL-Varianten wirken auf alle Kanäle (gut für ein Pause-Menü).",
    [
      'AUDIO_PAUSE(ch)',
      '\' ... Spiel pausiert ...',
      'AUDIO_RESUME(ch)',
    ]),
  H.cmd("AUDIO_SET_VOLUME · AUDIO_GET_VOLUME · AUDIO_PITCH", 'AUDIO_SET_VOLUME(ch, v)   AUDIO_GET_VOLUME(ch)   AUDIO_PITCH(ch, faktor)',
    "Lautstärke (0..1) eines Kanals setzen/lesen und die Tonhöhe live ändern: faktor 2.0 = eine Oktave höher und doppelt so schnell, 0.5 = eine Oktave tiefer. (AUDIO_VOLUME ist ein Alias für AUDIO_SET_VOLUME.)",
    [
      'AUDIO_SET_VOLUME(ch, 0.6)',
      'AUDIO_PITCH(ch, 1.5)   \' höher und schneller',
    ]),

  H.h2("Stereo-Panorama"),
  H.p("Mit dem Panorama legst du fest, ob ein Klang eher links oder rechts kommt – etwa damit ein Gegner von der Seite hörbar ist, aus der er angreift. Die Position reicht von -1 (ganz links) über 0 (Mitte) bis +1 (ganz rechts)."),
  H.cmd("AUDIO_PAN_POS · AUDIO_PAN_SLIDE · AUDIO_AUTOPAN", 'AUDIO_PAN_POS(ch, p)   AUDIO_PAN_SLIDE(ch, von, nach, dauer_ms)   AUDIO_AUTOPAN(ch, periode_s [, tiefe])',
    "PAN_POS setzt die Position sofort, PAN_SLIDE fährt sie über eine Zeitspanne von „von“ nach „nach“ (vorbeiziehendes Objekt), AUTOPAN lässt den Klang dauerhaft sanft hin- und herwandern.",
    [
      'AUDIO_PAN_POS(ch, -0.5)          \' halb links',
      'AUDIO_PAN_SLIDE(ch, -1.0, 1.0, 800)  \' zieht von links nach rechts',
    ]),

  H.h2("Klang selbst erzeugen: AUDIO_SFX"),
  H.p("AUDIO_SFX ist ein kleiner Synthesizer im Stil klassischer 8-Bit-Soundchips: aus einer Wellenform plus Hüllkurve, Tonhöhen-Verlauf und Vibrato baust du Lauf-, Sprung-, Treffer- oder Münz-Geräusche – ganz ohne Audiodatei. (Der Sound-Generator gbsfx exportiert genau solche Aufrufe.)"),
  H.cmd("AUDIO_SFX", 'AUDIO_SFX(wellenform$, freq, slide, atk, sus, dec, vib_tiefe, vib_speed, vol [, ...])',
    'Erzeugt einen SOUND. wellenform$ = "sine"/"square"/"saw"/"triangle"/"noise". freq = Start-Frequenz, slide = Tonhöhen-Drift, atk/sus/dec = Hüllkurve (Anstieg/Halten/Abklingen in Sekunden), vib_tiefe/vib_speed = Vibrato, vol = Lautstärke. Weitere optionale Argumente steuern Stereo-Breite, Pulsweite und Filter.',
    [
      'IMPORT "audio"',
      'DIM muenze AS SOUND',
      'muenze = AUDIO_SFX("square", 600.0, 800.0, 0.0, 0.05, 0.15, 0.0, 0.0, 0.5)',
      'AUDIO_PLAY(muenze)',
    ]),
  H.cmd("AUDIO_LOFI", 'AUDIO_LOFI(sound [, bits [, cutoff_hz]])',
    "Gibt einem frisch erzeugten Sound (TONE/NOISE/SFX/SAMPLE) einen körnigen Retro-Charakter: bit-crush (Standard 8 bit) plus ein weicher Tiefpass-Filter (Standard 3300 Hz) – der typische Amiga/Lo-Fi-Sound.",
    [
      'DIM s AS SOUND',
      's = AUDIO_TONE(220.0, 400, "saw", 0.4)',
      'AUDIO_LOFI(s, 8, 3300.0)',
      'AUDIO_PLAY(s)',
    ]),

  H.h2("Samples: einen Klang in Tonhöhen spielen"),
  H.p("Ein Sample ist eine kurze Aufnahme (z. B. ein einzelner Klavieranschlag), die du in beliebigen Tonhöhen abspielst – das Prinzip eines Samplers. SAMPLE_PLAY transponiert die Aufnahme um eine Anzahl Halbtöne. Kurze One-Shots eignen sich für Drums und Treffer, mit einer Loop-Region (SAMPLE_SET_LOOP) lassen sich gehaltene Töne erzeugen."),
  H.cmd("SAMPLE_LOAD · SAMPLE_PLAY · SAMPLE_SET_LOOP · SAMPLE_LEN", 'SAMPLE_LOAD(pfad$)   SAMPLE_PLAY(sample, halbtoene, vol [, dur_ms])   SAMPLE_SET_LOOP(sample, start, ende)   SAMPLE_LEN(sample)',
    "LOAD lädt eine Audiodatei als SAMPLE. PLAY spielt sie um halbtoene transponiert (0 = Originaltonhöhe, 12 = eine Oktave höher) und gibt eine Kanal-Nummer zurück. SET_LOOP markiert eine Schleifenregion, LEN liefert die Länge in Samples.",
    [
      'IMPORT "audio"',
      'DIM piano AS SAMPLE',
      'piano = SAMPLE_LOAD("assets/piano_c.wav")',
      'SAMPLE_PLAY(piano, 0, 0.8)    \' Grundton C',
      'SAMPLE_PLAY(piano, 7, 0.8)    \' eine Quinte höher (G)',
    ]),

  H.h2("Musik steuern"),
  H.p("Über PLAYMUSIC (Kapitel 46) hinaus kannst du laufende Musik fein steuern: pausieren, fortsetzen, mit Ein-/Ausblendung stoppen, die Abspielposition abfragen oder die Tonhöhe verziehen. Auch Tracker-Module (.mod/.xm) werden in Echtzeit gestreamt."),
  H.cmd("AUDIO_MUSIC_PAUSE/RESUME/STOP · _POSITION", 'AUDIO_MUSIC_PAUSE()   AUDIO_MUSIC_RESUME()   AUDIO_MUSIC_STOP([fade_out_ms])   AUDIO_MUSIC_POSITION()',
    "Pausiert/setzt die Musik fort, stoppt sie (optional mit Ausblendung in Millisekunden) und liefert mit POSITION die aktuelle Abspielzeit in Sekunden (FLOAT) – z. B. um eine Lichtshow zur Musik zu synchronisieren.",
    [
      'PLAYMUSIC("level1.ogg", -1, 0.7)   \' aus Kap. 46',
      'PRINT AUDIO_MUSIC_POSITION()        \' Sekunden seit Start',
      'AUDIO_MUSIC_STOP(1000)              \' über 1 s ausblenden',
    ]),
  H.cmd("AUDIO_MUSIC_SET_VOLUME · AUDIO_MUSIC_PITCH", 'AUDIO_MUSIC_SET_VOLUME(v)   AUDIO_MUSIC_PITCH(faktor)',
    "Lautstärke (0..1) und Tonhöhe/Tempo der Musik live anpassen – etwa Musik leiser drehen, während eine Stimme spricht, oder sie in Zeitlupe verlangsamen.",
    [
      'AUDIO_MUSIC_SET_VOLUME(0.4)',
      'AUDIO_MUSIC_PITCH(0.8)   \' tiefer und langsamer',
    ]),

  H.cmd("AUDIO_MUSIC_LOAD · AUDIO_MUSIC_PLAY · AUDIO_MUSIC_QUEUE", 'AUDIO_MUSIC_LOAD(pfad$)   AUDIO_MUSIC_PLAY([wiederholungen[, fade_in_ms[, easing$]]])   AUDIO_MUSIC_QUEUE(pfad$)',
    "Der zweistufige Weg statt PLAYMUSIC: erst laden, dann starten – so kannst du ein Stück im Ladebildschirm vorbereiten und später ohne Verzögerung anspielen. AUDIO_MUSIC_QUEUE hängt ein Stück an, das automatisch folgt, wenn das laufende endet (Intro → Hauptthema).",
    [
      'AUDIO_MUSIC_LOAD("musik/level1.ogg")',
      'AUDIO_MUSIC_PLAY(-1, 1500, "inout")   \' endlos, 1,5 s weich einblenden',
      'AUDIO_MUSIC_QUEUE("musik/level1_loop.ogg")',
    ]),
  H.cmd("AUDIO_MUSIC_VOLUME · AUDIO_MUSIC_GET_VOLUME · AUDIO_MUSIC_GET_PITCH · AUDIO_MUSIC_BUSY", 'AUDIO_MUSIC_VOLUME(v)   AUDIO_MUSIC_GET_VOLUME()   AUDIO_MUSIC_GET_PITCH()   AUDIO_MUSIC_BUSY()',
    "Die Abfrage-Seite: aktuelle Lautstärke und Tonhöhe auslesen (etwa um sie in den Optionen anzuzeigen), und prüfen, ob überhaupt Musik läuft. AUDIO_MUSIC_VOLUME ist der kürzere Name für AUDIO_MUSIC_SET_VOLUME.",
    [
      'IF NOT AUDIO_MUSIC_BUSY() THEN naechstes_stueck()',
      'PRINT AUDIO_MUSIC_GET_VOLUME()',
    ]),

  H.h2("Kanäle verwalten"),
  H.cmd("AUDIO_INIT · AUDIO_NUM_CHANNELS · AUDIO_SET_NUM_CHANNELS", 'AUDIO_INIT([frequenz[, kanaele[, puffer]]])   AUDIO_NUM_CHANNELS()   AUDIO_SET_NUM_CHANNELS(n)',
    "Die Tonausgabe startet von selbst, sobald du etwas abspielst – AUDIO_INIT brauchst du nur, wenn du sie vorher mit eigenen Werten einrichten willst. Voreingestellt sind 16 gleichzeitige Kanäle; reicht das bei vielen Effekten nicht, erhöhst du sie.",
    [
      'PRINT AUDIO_NUM_CHANNELS()',
      'AUDIO_SET_NUM_CHANNELS(32)',
      'PRINT AUDIO_NUM_CHANNELS()',
    ], { out: ["16", "32"] }),
  H.cmd("AUDIO_BUSY_CHANNELS · AUDIO_STOP_ALL", 'AUDIO_BUSY_CHANNELS()   AUDIO_STOP_ALL()',
    "AUDIO_BUSY_CHANNELS zählt die gerade klingenden Kanäle – nützlich, um bei Massen-Explosionen nicht jeden Treffer einzeln zu vertonen. AUDIO_STOP_ALL bricht alles ab, der saubere Schnitt beim Szenenwechsel.",
    [
      'IF AUDIO_BUSY_CHANNELS() < 8 THEN AUDIO_PLAY(treffer)',
      'AUDIO_STOP_ALL()',
    ]),

  H.h2("Mixer-Busse: ganze Gruppen regeln"),
  H.p('Alle Klänge laufen über drei Busse: "sfx" (Effekte, Samples, Synth), "music" (Musik) und "master" (die Summe von beidem). Über den Bus regelst du eine ganze Gruppe auf einmal – klassisch getrennte Regler für „Effekte“ und „Musik“ im Optionsmenü.'),
  H.cmd("AUDIO_BUS_VOLUME · AUDIO_BUS_GET_VOLUME", 'AUDIO_BUS_VOLUME(bus$, vol)   AUDIO_BUS_GET_VOLUME(bus$)',
    'Setzt/liest die Lautstärke (0..1) eines Busses. bus$ = "sfx", "music" oder "master".',
    [
      'IMPORT "audio"',
      'AUDIO_BUS_VOLUME("music", 0.5)',
      'PRINT AUDIO_BUS_GET_VOLUME("music")',
    ], { out: ["0.5"] }),

  H.h2("Echtzeit-Effekte pro Bus"),
  H.p("Auf jeden Bus lässt sich eine Kette von Effekten legen, die in Echtzeit rechnen – du kannst ihre Werte jederzeit ändern. Damit verleihst du einem Höhlen-Level Hall, einem Funkgerät einen Bandpass-Filter oder einem Bosskampf eine verzerrte Kante. Alle Effekte sind neutral, bis du sie aktivierst."),
  H.cmd("AUDIO_REVERB · AUDIO_DELAY", 'AUDIO_REVERB(bus$, mix [, feedback [, damping]])   AUDIO_DELAY(bus$, mix [, feedback [, time_ms]])',
    "REVERB legt einen Raum-/Hall-Effekt auf den Bus (mix = Anteil 0..1). DELAY ist ein Echo mit einstellbarer Verzögerungszeit – die Zeit ist zur Laufzeit veränderbar.",
    [
      'AUDIO_REVERB("sfx", 0.3)            \' etwas Hall',
      'AUDIO_DELAY("sfx", 0.25, 0.4, 300.0) \' Echo, 300 ms',
    ]),
  H.cmd("AUDIO_FILTER · AUDIO_DISTORTION", 'AUDIO_FILTER(bus$, cutoff_hz [, resonance])   AUDIO_DISTORTION(bus$, amount [, mix])',
    "FILTER ist ein Tiefpass (lässt nur Frequenzen unter cutoff_hz durch – dumpfer Klang, klassischer „Acid“-Sweep). DISTORTION fügt Übersteuerung/Fuzz hinzu.",
    [
      'AUDIO_FILTER("master", 1200.0)   \' alles wird dumpfer',
      'AUDIO_DISTORTION("sfx", 0.5)     \' angeraut',
    ]),
  H.cmd("AUDIO_COMPRESSOR · AUDIO_EQ", 'AUDIO_COMPRESSOR(bus$, threshold_db, ratio [, makeup_db])   AUDIO_EQ(bus$, freq_hz, gain_db [, q])',
    "COMPRESSOR drückt laute Spitzen zusammen und macht den Klang gleichmäßiger (ratio<=1 = aus). EQ hebt oder senkt einen Frequenzbereich an (gain_db: positiv = lauter, negativ = leiser, 0 = neutral).",
    [
      'AUDIO_COMPRESSOR("master", -12.0, 4.0)',
      'AUDIO_EQ("sfx", 1000.0, 6.0)   \' Mitten anheben',
    ]),

  H.h2("Bus-Einstellungen sichern: AUDIO_PUSH und AUDIO_POP"),
  H.p("Alle Bus-Einstellungen sind global – Lautstärke, Balance, Filter, Hall, Echo, Verzerrer, Kompressor, EQ. Legst du für eine Höhle einen Hall auf den Master und vergisst ihn beim Verlassen, hallt auch das Menü. Statt jede Zeile von Hand zurückzunehmen, legst du den ganzen Zustand auf einen Stapel."),
  H.cmd("AUDIO_PUSH · AUDIO_POP · AUDIO_DEPTH", "AUDIO_PUSH()   AUDIO_POP()   AUDIO_DEPTH()",
    "AUDIO_PUSH sichert alle Bus-Einstellungen, AUDIO_POP holt sie zurück, AUDIO_DEPTH liefert die Stapeltiefe. Ein POP ohne PUSH ist ein Fehler.",
    [
      "AUDIO_PUSH()",
      'AUDIO_REVERB("master", 0.6, 0.8)   \' Hoehle: nass und dunkel',
      'AUDIO_FILTER("master", 900.0)',
      "szene_hoehle()",
      "AUDIO_POP()                        ' trocken wie vorher",
    ]),
  H.warn("Hast du mit AUDIO_MODULATE einen LFO auf einen Bus-Wert gelegt, den ein AUDIO_POP zurückschreibt, endet die Modulation an dieser Stelle – beide beschreiben denselben Regler, und der letzte gewinnt. Das ist kein Fehler, sondern eine Folge davon, wie die Werte zusammenlaufen; wer die Modulation behalten will, setzt sie nach dem POP neu.", "Eine laufende Modulation wird dabei abgelöst"),
  H.note("Das Gegenstück für die Grafik heißt GFX_PUSH / GFX_POP und sichert Licht, Nebel, Kamera, Schatten, Schrift und den Post-Effekt – siehe Kapitel 42."),

  H.h2("Sample-genaues Timing: AUDIO_CLOCK"),
  H.p("Eine Uhr, die vom Audio-Thread selbst getrieben wird – nicht von deinem (ungenaueren) Game-Loop. Damit planst du Sounds exakt auf einen musikalischen Takt statt „ungefähr jetzt“. Praktisch für Rhythmusspiele oder Musik-synchronisierte Effekte."),
  H.cmd("AUDIO_CLOCK_NEW · AUDIO_CLOCK_START · AUDIO_CLOCK_TICKING", 'AUDIO_CLOCK_NEW(ticks_pro_sekunde) -> AUDIO_CLOCK   AUDIO_CLOCK_START(clock)   AUDIO_CLOCK_TICKING(clock) AS BOOLEAN',
    "AUDIO_CLOCK_NEW legt eine Uhr an (startet pausiert). AUDIO_CLOCK_START startet sie. AUDIO_CLOCK_TICKING verrät, ob sie gerade läuft. Aus einem BPM-Wert rechnest du dir die Tick-Rate selbst um: bpm / 60.0 * unterteilungen.",
    [
      'IMPORT "audio"',
      'DIM clk AS AUDIO_CLOCK',
      'clk = AUDIO_CLOCK_NEW(4.0)   \' 4 Ticks pro Sekunde',
      'PRINT AUDIO_CLOCK_TICKING(clk)',
      'AUDIO_CLOCK_START(clk)',
      'PRINT AUDIO_CLOCK_TICKING(clk)',
    ], { out: ["FALSE", "TRUE"] }),
  H.cmd("AUDIO_CLOCK_PAUSE · AUDIO_CLOCK_STOP · AUDIO_CLOCK_REMOVE", 'AUDIO_CLOCK_PAUSE(clock)   AUDIO_CLOCK_STOP(clock)   AUDIO_CLOCK_REMOVE(clock)',
    "PAUSE hält die Uhr an (Ticks bleiben stehen, START setzt fort). STOP setzt sie auf 0 zurück und hält an. REMOVE gibt die Uhr endgültig frei.",
    [
      'AUDIO_CLOCK_PAUSE(clk)',
      'PRINT AUDIO_CLOCK_TICKING(clk)',
      'AUDIO_CLOCK_STOP(clk)',
      'AUDIO_CLOCK_REMOVE(clk)',
    ], { out: ["FALSE"] }),
  H.cmd("AUDIO_CLOCK_SET_SPEED · AUDIO_CLOCK_TICKS", 'AUDIO_CLOCK_SET_SPEED(clock, ticks_pro_sekunde)   AUDIO_CLOCK_TICKS(clock) AS INTEGER',
    "SET_SPEED ändert das Tempo einer laufenden Uhr (z. B. bei einem Tempowechsel im Stück). AUDIO_CLOCK_TICKS liefert die Anzahl vergangener Ticks seit dem Start – dein Zähler für „welcher Takt ist gerade dran“.",
    [
      'AUDIO_CLOCK_SET_SPEED(clk, 8.0)   \' doppeltes Tempo',
      'PRINT AUDIO_CLOCK_TICKS(clk) >= 0',
    ], { out: ["TRUE"] }),
  H.cmd("AUDIO_PLAY_AT", 'AUDIO_PLAY_AT(sound, clock, ticks [, volume [, loops]]) -> AUDIO_CHANNEL',
    "Plant den Start eines Sounds exakt auf den angegebenen Tick der Uhr – vom Audio-Thread selbst ausgelöst, nicht durch dein Frame-Timing. So klingt ein Hi-Hat-Sample exakt im Takt, statt je nach Framerate leicht zu schwanken.",
    [
      'IMPORT "audio"',
      'DIM s AS SOUND',
      's = AUDIO_TONE(440.0, 300, "square", 0.4)',
      'DIM ch AS INTEGER',
      'ch = AUDIO_PLAY_AT(s, clk, 8)   \' startet exakt auf Tick 8',
      'PRINT ch >= 0',
    ], { out: ["TRUE"] }),

  H.h2("Räumliches Audio: Listener & Emitter"),
  H.p("Für 2D-/3D-Spiele mit Ortsgefühl: Ein Listener ist das „Ohr“ der Szene (meist an Kamera oder Spielfigur gebunden), ein Emitter eine Klangquelle irgendwo in der Welt. Kira übernimmt selbst die Berechnung von Panning und Lautstärke-Abnahme mit der Entfernung – du musst nichts selbst rechnen."),
  H.cmd("AUDIO_LISTENER_NEW · AUDIO_LISTENER_SET_POSITION · AUDIO_LISTENER_SET_ORIENTATION", 'AUDIO_LISTENER_NEW(x, y, z) -> AUDIO_LISTENER   AUDIO_LISTENER_SET_POSITION(listener, x, y, z)   AUDIO_LISTENER_SET_ORIENTATION(listener, yaw_grad)',
    "Legt einen Listener an der Position (x, y, z) an – meist die Kameraposition. SET_POSITION bewegt ihn (jeden Frame aktualisieren). SET_ORIENTATION dreht seine Blickrichtung um die Y-Achse (Yaw in Grad) – für den typischen Top-Down- oder Third-Person-Blick reicht das, ohne volle 3D-Rotation.",
    [
      'IMPORT "audio"',
      'DIM ohr AS AUDIO_LISTENER',
      'ohr = AUDIO_LISTENER_NEW(0.0, 0.0, 0.0)',
      'AUDIO_LISTENER_SET_POSITION(ohr, 1.0, 0.0, 0.0)',
      'AUDIO_LISTENER_SET_ORIENTATION(ohr, 90.0)',
      'PRINT "ok"',
    ], { out: ["ok"] }),
  H.cmd("AUDIO_EMITTER_NEW · AUDIO_EMITTER_SET_POSITION", 'AUDIO_EMITTER_NEW(listener, x, y, z [, min_dist [, max_dist]]) -> AUDIO_EMITTER   AUDIO_EMITTER_SET_POSITION(emitter, x, y, z)',
    "Legt eine Klangquelle an, gebunden an einen Listener. Innerhalb von min_dist ist sie voll laut, ab max_dist nicht mehr hörbar – dazwischen linear leiser. SET_POSITION bewegt die Quelle (z. B. einen fahrenden Gegner).",
    [
      'DIM quelle AS AUDIO_EMITTER',
      'quelle = AUDIO_EMITTER_NEW(ohr, 5.0, 0.0, 0.0, 1.0, 20.0)',
      'AUDIO_EMITTER_SET_POSITION(quelle, 6.0, 0.0, 0.0)',
      'PRINT "ok"',
    ], { out: ["ok"] }),
  H.cmd("AUDIO_PLAY_ON", 'AUDIO_PLAY_ON(sound, emitter [, loops [, volume [, fade_in_ms [, easing$]]]]) -> AUDIO_CHANNEL',
    "Spielt einen Sound auf einem Emitter statt auf dem normalen sfx-Bus ab – Panning und Entfernungs-Lautstärke laufen automatisch. Der zurückgegebene Kanal steuerst du danach ganz normal mit AUDIO_STOP/AUDIO_SET_VOLUME/....",
    [
      'DIM s AS SOUND',
      's = AUDIO_TONE(440.0, 300, "square", 0.4)',
      'DIM ch AS INTEGER',
      'ch = AUDIO_PLAY_ON(s, quelle)',
      'PRINT AUDIO_IS_PLAYING(ch)',
    ], { out: ["TRUE"] }),
  H.cmd("AUDIO_EMITTER_REMOVE · AUDIO_LISTENER_REMOVE", 'AUDIO_EMITTER_REMOVE(emitter)   AUDIO_LISTENER_REMOVE(listener)',
    "Geben Emitter bzw. Listener wieder frei – aufräumen, wenn eine Klangquelle oder Szene nicht mehr gebraucht wird.",
    [
      'AUDIO_EMITTER_REMOVE(quelle)',
      'AUDIO_LISTENER_REMOVE(ohr)',
      'PRINT "ok"',
    ], { out: ["ok"] }),

  H.h2("Modulatoren: Klänge, die sich von selbst bewegen"),
  H.p("Ein Tremolo, ein Wobble-Bass oder ein Filter-Sweep bedeutet: ein Wert bewegt sich ständig. Du könntest ihn pro Frame selbst ausrechnen – dann hängt der Klang aber an der Bildrate und stottert, sobald das Spiel ruckelt. Modulatoren laufen stattdessen auf dem AUDIO-Thread: sample-genau, unabhängig davon, was das Spiel gerade tut, und ohne dass dein Programm pro Frame irgendetwas nachrechnet."),
  H.p("Es gibt zwei Sorten. Ein LFO schwingt endlos (für alles Wiederkehrende), ein Tweener fährt einmalig von einem Wert zum anderen (für Übergänge). Beide liefern denselben Handle-Typ AUDIO_MOD."),
  H.cmd("AUDIO_LFO_NEW · AUDIO_LFO_SET · AUDIO_LFO_WAVEFORM", 'AUDIO_LFO_NEW(wellenform$, hz[, amplitude[, mitte]])   AUDIO_LFO_SET(mod[, hz[, amplitude[, mitte]]])   AUDIO_LFO_WAVEFORM(mod, wellenform$)',
    'Erzeugt einen Schwinger. wellenform$ ist "sine", "triangle", "saw" oder "pulse", hz die Geschwindigkeit (4.0 = viermal pro Sekunde). Amplitude und Mitte legen den Wertebereich fest (voreingestellt schwingt er zwischen -1 und +1). Die beiden Setter ändern einen laufenden LFO, ohne ihn neu anzulegen.',
    [
      'IMPORT "audio"',
      'DIM lfo AS AUDIO_MOD',
      'lfo = AUDIO_LFO_NEW("sine", 4.0)',
      'AUDIO_LFO_SET(lfo, 6.0)              \' schneller',
      'AUDIO_LFO_WAVEFORM(lfo, "triangle")',
    ]),
  H.cmd("AUDIO_TWEENER_NEW · AUDIO_TWEENER_TO", 'AUDIO_TWEENER_NEW([startwert])   AUDIO_TWEENER_TO(mod, ziel[, dauer_ms[, easing$]])',
    'Ein Tweener hält einen Wert und fährt ihn auf Ansage zu einem neuen – etwa einen Filter langsam öffnen, wenn der Spieler auftaucht. easing$ ist "linear", "in", "out" oder "inout".',
    [
      'DIM tw AS AUDIO_MOD',
      'tw = AUDIO_TWEENER_NEW(0.0)',
      'AUDIO_TWEENER_TO(tw, 1.0, 800, "inout")',
    ]),
  H.cmd("AUDIO_MODULATE · AUDIO_MOD_REMOVE", 'AUDIO_MODULATE(bus$, ziel$, mod, min, max)   AUDIO_MOD_REMOVE(mod)',
    'Verbindet einen Modulator mit einem Bus. ziel$ ist "volume" (Tremolo), "pan" (Auto-Pan), "filter", "resonance", "reverb" oder "distortion". Der Wertebereich des Modulators wird dabei auf min…max abgebildet – ein LFO zwischen -1 und +1 bei min=0.4/max=1.0 lässt die Lautstärke also zwischen 40 % und 100 % pendeln. AUDIO_MOD_REMOVE löst die Verbindung wieder.',
    [
      'AUDIO_MODULATE("sfx", "volume", lfo, 0.4, 1.0)      \' Tremolo',
      'AUDIO_MODULATE("music", "filter", tw, 200.0, 8000.0) \' Filter oeffnet',
      'AUDIO_MOD_REMOVE(lfo)',
    ]),
  H.cmd("AUDIO_BUS_PAN", 'AUDIO_BUS_PAN(bus$, position)',
    "Verschiebt einen ganzen Bus im Stereobild (-1 = links, 0 = Mitte, +1 = rechts). Bis dahin ließ sich nur ein einzelner Kanal pannen; damit legst du etwa die gesamte Musik leicht nach links, während die Effekte mittig bleiben.",
    [
      'AUDIO_BUS_PAN("music", -0.3)',
    ]),
  H.note("Weil die Modulatoren auf dem Audio-Thread laufen, bleiben Tremolo, Vibrato, Wobble-Bass, Auto-Pan und Filter-Sweeps auch dann sauber, wenn die Bildrate einbricht – genau der Unterschied zu einer selbst gebauten Lösung im Game-Loop. Eine vollständige Demo ist examples/150_audio_modulatoren.gb."),

  H.tip("Spektrum für Visualizer: AUDIO_FFT", "Mit AUDIO_FFT(array) füllst du ein ARRAY OF FLOAT mit den aktuellen Frequenz-Stärken der Gesamtausgabe. Daraus baust du Balken-Visualizer oder lässt Effekte „zur Musik tanzen“. Zusammen mit den Bus-Effekten und den Kira-Streaming-Funktionen deckt das audio-Modul alles ab, was ein Spiel klanglich braucht – von einem einzelnen Piepton bis zum dynamischen Soundtrack."),
];
