module.exports = (H) => [
  H.chapter("Modul: net"),
  H.p("Mit dem net-Modul reden Programme über das Netzwerk miteinander – für einen Chat, eine Highscore-Abfrage oder ein Mehrspieler-Spiel im LAN. Es bietet die beiden klassischen Transportarten TCP und UDP. Wichtig für Spiele: Alle Verbindungen sind standardmäßig „nicht-blockierend“ – ein Lesebefehl kehrt sofort zurück, auch wenn gerade nichts da ist, sodass dein Game-Loop nie einfriert."),
  H.note("Netzwerk ist ein großes Thema; dieses Kapitel zeigt die Bausteine und ein lauffähiges Beispiel auf demselben Rechner (über die Adresse 127.0.0.1, „localhost“). Für echtes Spiel über mehrere Geräte kommen Firewall- und IP-Fragen dazu, die den Rahmen sprengen."),

  H.h2("TCP oder UDP?"),
  H.bulletRich("TCP", " – verbindungsorientiert, zuverlässig: Alles kommt vollständig und in der richtigen Reihenfolge an. Richtig für Chat, rundenbasierte Spiele, Lobby-Anmeldung."),
  H.bulletRich("UDP", " – verbindungslos, schnell: Einzelne Pakete können verloren gehen oder die Reihenfolge tauschen, dafür ist es flink. Richtig für ständige Positions-Updates in Action-Spielen, wo das nächste Paket den Verlust ohnehin überholt."),

  H.h2("TCP: Server und Client"),
  H.p("Ein TCP-Server lauscht mit NET_TCP_LISTEN auf einem Port. NET_TCP_ACCEPT holt eine wartende Verbindung ab – oder liefert NIL, wenn gerade niemand verbindet (das prüfst du mit IS_NIL). Ein Client baut die Verbindung mit NET_TCP_CONNECT auf. Über die fertige Verbindung schickst du Text mit NET_SEND und liest mit NET_RECV."),
  H.cmd("NET_TCP_LISTEN · NET_TCP_ACCEPT · NET_LISTENER_PORT", 'NET_TCP_LISTEN(port)   NET_TCP_ACCEPT(lst)   NET_LISTENER_PORT(lst)',
    "LISTEN öffnet einen Server-Socket (Port 0 = das Betriebssystem wählt einen freien, abfragbar mit NET_LISTENER_PORT). ACCEPT gibt eine neue NET_SOCKET-Verbindung zurück – oder NIL, wenn keine wartet (mit IS_NIL(x) oder x <> NIL prüfen).",
    [
      'IMPORT "net"',
      'DIM lst AS NET_LISTENER',
      'lst = NET_TCP_LISTEN(7000)',
      'DIM client AS NET_SOCKET',
      'client = NET_TCP_ACCEPT(lst)',
      'IF NOT IS_NIL(client) THEN',
      '    PRINT "Neuer Spieler:", NET_PEER_ADDR(client)',
      'END IF',
    ]),
  H.cmd("NET_TCP_CONNECT · NET_SEND · NET_RECV", 'NET_TCP_CONNECT(host$, port)   NET_SEND(sock, text$)   NET_RECV(sock, max_bytes)',
    "CONNECT verbindet zum Server (5 s Anschluss-Zeitlimit). NET_SEND verschickt Text und gibt die gesendete Byte-Zahl zurück. NET_RECV liest bis zu max_bytes und liefert leeren String, wenn (noch) nichts da ist. Alles UTF-8.",
    [
      'IMPORT "net"',
      'DIM sock AS NET_SOCKET',
      'sock = NET_TCP_CONNECT("127.0.0.1", 7000)',
      'NET_SEND(sock, "Hallo Server")',
      'DIM antwort AS STRING',
      'antwort = NET_RECV(sock, 1024)   \' leer, wenn noch nichts kam',
    ]),
  H.cmd("NET_PEER_ADDR · NET_CLOSE · NET_CLOSE_LISTENER", 'NET_PEER_ADDR(sock)   NET_PEER_PORT(sock)   NET_CLOSE(sock)   NET_CLOSE_LISTENER(lst)',
    "PEER_ADDR/PEER_PORT verraten die Gegenstelle einer Verbindung. NET_CLOSE schließt eine Verbindung, NET_CLOSE_LISTENER den Server-Socket – beides am Ende aufräumen.",
    [
      'PRINT NET_PEER_ADDR(sock); ":"; NET_PEER_PORT(sock)',
      'NET_CLOSE(sock)',
    ]),

  H.h2("Ein vollständiges Beispiel auf einem Rechner"),
  H.p("Server und Client können im selben Programm laufen – praktisch zum Ausprobieren. Hier verbindet sich ein Client, schickt eine Nachricht, und der Server liest sie. Die kurzen SLEEP-Pausen geben dem Betriebssystem Zeit, die Daten zuzustellen."),
  H.code([
    'IMPORT "net"',
    'DIM lst AS NET_LISTENER',
    'lst = NET_TCP_LISTEN(0)                         \' freien Port nehmen',
    'DIM c AS NET_SOCKET',
    'c = NET_TCP_CONNECT("127.0.0.1", NET_LISTENER_PORT(lst))',
    'SLEEP(50)',
    'DIM s AS NET_SOCKET',
    's = NET_TCP_ACCEPT(lst)                         \' die Verbindung annehmen',
    'NET_SEND(c, "Hallo Server")',
    'SLEEP(50)',
    'PRINT NET_RECV(s, 1024)',
    'NET_CLOSE(c) : NET_CLOSE(s) : NET_CLOSE_LISTENER(lst)',
  ], { out: ["Hallo Server"] }),

  H.h2("UDP: schnelle Pakete"),
  H.p("UDP kennt keine feste Verbindung. Ein Socket bindet (NET_UDP_BIND) sich an einen Port zum Empfangen, oder wird mit NET_UDP_OPEN nur zum Senden geöffnet. Jedes Paket adressierst du beim Senden einzeln mit Ziel-Host und -Port. Nach einem Empfang verrät NET_UDP_LAST_FROM, von wem das Paket kam."),
  H.cmd("NET_UDP_BIND · NET_UDP_OPEN · NET_UDP_PORT", 'NET_UDP_BIND(port)   NET_UDP_OPEN()   NET_UDP_PORT(sock)',
    "BIND bindet einen UDP-Socket an einen Port (0 = freier Port). OPEN erstellt einen Socket nur zum Senden. NET_UDP_PORT liefert den gebundenen Port.",
    [
      'IMPORT "net"',
      'DIM srv AS NET_UDP',
      'srv = NET_UDP_BIND(6000)        \' empfängt auf Port 6000',
      'DIM cli AS NET_UDP',
      'cli = NET_UDP_OPEN()            \' sendet nur',
    ]),
  H.cmd("NET_UDP_SEND · NET_UDP_RECV · NET_UDP_LAST_FROM", 'NET_UDP_SEND(sock, host$, port, text$)   NET_UDP_RECV(sock, max_bytes)   NET_UDP_LAST_FROM(sock)',
    'SEND verschickt ein Paket an host$:port. RECV liest das nächste Paket (leer, wenn keins da ist). NET_UDP_LAST_FROM liefert die Absender-Adresse des zuletzt empfangenen Pakets als STRING "host:port".',
    [
      'IMPORT "net"',
      'DIM srv AS NET_UDP',
      'srv = NET_UDP_BIND(0)',
      'DIM cli AS NET_UDP',
      'cli = NET_UDP_OPEN()',
      'NET_UDP_SEND(cli, "127.0.0.1", NET_UDP_PORT(srv), "POS 10 20")',
      'SLEEP(50)',
      'PRINT NET_UDP_RECV(srv, 256)',
      'PRINT NET_UDP_LAST_FROM(srv)',
    ], { out: ["POS 10 20", "127.0.0.1:<port>"] }),
  H.note('NET_UDP_LAST_FROM gibt einen STRING der Form "host:port" zurück (z. B. "127.0.0.1:63332"), nicht zwei getrennte Werte. Den Host-Teil holst du dir bei Bedarf mit SPLIT(adr, ":")[0].'),

  H.cmd("NET_IS_CONNECTED", "NET_IS_CONNECTED(sock) AS BOOLEAN",
    "Verrät, ob eine TCP-Verbindung noch als offen gilt. Wird FALSE, sobald ein Lese- oder Schreibversuch das Schließen der Gegenseite erkannt hat – praktisch für eine schnelle Vorab-Prüfung, bevor du NET_SEND/NET_RECV aufrufst.",
    [
      'IMPORT "net"',
      'DIM lst AS NET_LISTENER',
      'lst = NET_TCP_LISTEN(0)',
      'DIM c AS NET_SOCKET',
      'c = NET_TCP_CONNECT("127.0.0.1", NET_LISTENER_PORT(lst))',
      'SLEEP(50)',
      'DIM s AS NET_SOCKET',
      's = NET_TCP_ACCEPT(lst)',
      'PRINT NET_IS_CONNECTED(c)',
      'NET_CLOSE(c) : NET_CLOSE(s) : NET_CLOSE_LISTENER(lst)',
    ], { out: ["TRUE"] }),

  H.h2("Nicht-blockierend – der Schlüssel für Spiele"),
  H.p("Alle Lese- und Annahme-Befehle (RECV, ACCEPT, UDP_RECV) kehren sofort zurück: Ist nichts da, liefern sie leeren Text bzw. NIL. So fragst du das Netzwerk einmal pro Frame ab, ohne den Loop anzuhalten. Willst du ausnahmsweise warten, bis Daten kommen, setzt du mit NET_SET_TIMEOUT (bzw. NET_UDP_SET_TIMEOUT) ein Zeitlimit – Vorsicht im Game-Loop, denn das hält den Frame an."),
  H.note("NET_TCP_ACCEPT liefert NIL, wenn gerade keine Verbindung wartet. NIL ist ein ganz normaler Wert (Literal), den du direkt schreiben und vergleichen kannst – prüfe also mit IF NOT IS_NIL(client) THEN … oder gleichbedeutend mit IF client <> NIL THEN …."),
  H.h2("cloud – Spielstände und Bestenlisten auf einem Server"),
  H.p("Selbst Sockets zu programmieren lohnt sich für ein eigenes Protokoll. Für die beiden häufigsten Fälle – „Spielstand liegt auf dem Server“ und „weltweite Bestenliste“ – gibt es das cloud-Modul: Es spricht über HTTP mit einem kleinen Server, dessen Referenz-Umsetzung unter cloudserver/ im Projekt liegt (du kannst ihn auf einem Raspberry Pi im Heimnetz oder bei einem Anbieter laufen lassen)."),
  H.cmd("CLOUD_CONFIGURE", 'CLOUD_CONFIGURE(adresse$, api_schluessel$)',
    "Legt Serveradresse und das geteilte Geheimnis fest. Muss VOR allen anderen CLOUD_- und LEADERBOARD_-Aufrufen stehen, sonst kommt eine klare Fehlermeldung.",
    [
      'IMPORT "cloud"',
      'CLOUD_CONFIGURE("http://192.168.1.20:8787", "mein-api-key")',
    ]),
  H.cmd("CLOUD_SAVE · CLOUD_LOAD · CLOUD_LAST_ERROR$", 'CLOUD_SAVE(spieler_id$, daten$)   CLOUD_LOAD(spieler_id$)   CLOUD_LAST_ERROR$()',
    "CLOUD_SAVE legt einen beliebigen Text unter einer Spieler-Kennung ab (üblich ist JSON aus dem json-Modul) und überschreibt dabei den vorherigen Stand. CLOUD_LOAD holt ihn zurück.",
    [
      'CLOUD_SAVE(spieler_id, JSON_STRINGIFY(stand))',
      'DIM roh AS STRING',
      'roh = CLOUD_LOAD(spieler_id)',
    ]),
  H.warn("Leerer Spielstand heißt nicht immer „neuer Spieler“", "CLOUD_LOAD wirft bei einem Fehler absichtlich keinen Laufzeitfehler – „noch nichts gespeichert“ und „Server nicht erreichbar“ sehen beide wie ein leerer Text aus. Unterscheiden kannst du sie nur über CLOUD_LAST_ERROR$: leer bedeutet echter Erstbesuch, gefüllt bedeutet Fehler. Wer das übergeht, überschreibt bei einer Netzstörung fröhlich den Spielstand mit einem frischen Anfang."),
  H.code([
    'DIM stand AS STRING',
    'stand = CLOUD_LOAD(spieler_id)',
    'IF stand = "" THEN',
    '    IF CLOUD_LAST_ERROR$() <> "" THEN',
    '        PRINT "Cloud nicht erreichbar -- lokalen Spielstand nutzen"',
    '    ELSE',
    '        PRINT "Neuer Spieler, frischer Start"',
    '    END IF',
    'END IF',
  ]),
  H.cmd("LEADERBOARD_SUBMIT · LEADERBOARD_FETCH", 'LEADERBOARD_SUBMIT(liste$, name$, punkte[, kleiner_ist_besser])   LEADERBOARD_FETCH(liste$, n[, aufsteigend])',
    "SUBMIT reicht ein Ergebnis ein und liefert TRUE, wenn es ein neuer persönlicher Bestwert war – pro Liste und Name wird nur der beste Wert behalten. Mit kleiner_ist_besser = TRUE zählt der niedrigste Wert (Speedrun-Zeiten). FETCH holt die besten n Einträge als ARRAY OF TUPLE aus (name$, punkte).",
    [
      'LEADERBOARD_SUBMIT("highscores", spieler_name, 4200.0)',
      '',
      'DIM top AS ARRAY OF TUPLE',
      'top = LEADERBOARD_FETCH("highscores", 10)',
      'DIM i AS INTEGER',
      'FOR i = 0 TO LEN(top) - 1',
      '    TEXT(20, 40 + i * 18, STR$(i + 1) + ". " + top[i][0] + "  " + NUMFMT$(top[i][1]))',
      'NEXT',
    ]),

  H.cmd("NET_UDP_CLOSE", 'NET_UDP_CLOSE(sock)',
    "Schließt einen UDP-Socket und gibt den Anschluss wieder frei – das Gegenstück zu NET_UDP_BIND.",
    [
      'NET_UDP_CLOSE(sock)',
    ]),
  H.tip("Daten haben keine Grenzen", "TCP ist ein Strom, kein Paket-Versand: Zwei NET_SEND können beim Empfänger als ein NET_RECV ankommen – oder umgekehrt. Wenn du abgegrenzte Nachrichten brauchst, schick die Länge voraus (z. B. vierstellig) oder beende jede Nachricht mit einem Trennzeichen wie Zeilenumbruch und setze sie beim Empfänger wieder zusammen."),
];
