module.exports = (H) => [
  H.chapter("Modul: html"),
  H.p("Das html-Modul holt Daten aus dem Web: eine Webseite oder eine API abrufen (HTTP_GET), Daten hochladen (HTTP_POST), eine Datei herunterladen (HTTP_DOWNLOAD). Dazu kommen Helfer, um Texte für URLs aufzubereiten und einfaches HTML zu zerlegen. Damit baust du Online-Bestenlisten, holst tägliche Inhalte oder lädst Zusatz-Assets aus dem Netz."),
  H.note("HTTP-Aufrufe brauchen einen Moment und können fehlschlagen (kein Netz, Server weg). Führe sie nicht mitten im Render-Loop aus, sonst stockt das Bild – und sichere sie mit TRY/CATCH ab. Das Zeitlimit liegt bei 10 Sekunden."),

  H.h2("Daten abrufen: HTTP_GET"),
  H.p("HTTP_GET ruft eine Adresse auf und liefert die Antwort als Text. HTTP_STATUS verrät danach den HTTP-Statuscode (200 = OK, 404 = nicht gefunden …). Bei einem Fehler-Status oder Verbindungsproblem bricht der Aufruf ab – fang ihn mit TRY/CATCH."),
  H.cmd("HTTP_GET · HTTP_STATUS", 'HTTP_GET(url$)   HTTP_STATUS()',
    "GET ruft die URL ab und gibt den Antwort-Text zurück (UTF-8). HTTP_STATUS liefert den Statuscode der letzten Antwort – auch nach einem Fehler noch lesbar.",
    [
      'IMPORT "html"',
      'DIM page AS STRING',
      'page = HTTP_GET("https://example.com")',
      'PRINT "Status:", HTTP_STATUS()',
      'PRINT "Bytes:", LEN(page) > 0',
    ], { out: ["Status: 200", "Bytes: TRUE"] }),
  H.cmd("HTTP_POST · HTTP_HEADER", 'HTTP_POST(url$, body$)   HTTP_HEADER(name$)',
    "POST sendet body$ an die URL (z. B. um einen Highscore einzutragen) und gibt die Antwort zurück. HTTP_HEADER liest einen Antwort-Header der letzten Anfrage; Namen sind groß/klein egal.",
    [
      'IMPORT "html"',
      'DIM antwort AS STRING',
      'antwort = HTTP_POST("https://api.example.com/score", "name=Anna&pts=900")',
      'PRINT HTTP_HEADER("Content-Type")',
    ]),
  H.cmd("HTTP_DOWNLOAD", 'HTTP_DOWNLOAD(url$, pfad$)',
    "Lädt eine Datei direkt auf die Festplatte und gibt die Byte-Anzahl zurück. Für Binärdaten (Bilder, Sounds) immer DOWNLOAD statt GET nehmen – GET würde die Bytes als Text verfälschen.",
    [
      'IMPORT "html"',
      'DIM bytes AS INTEGER',
      'bytes = HTTP_DOWNLOAD("https://example.com/sprite.png", "assets/sprite.png")',
      'PRINT bytes, "Bytes geladen"',
    ]),

  H.h2("Fehler abfangen"),
  H.p("Weil ein Netzwerkaufruf jederzeit scheitern kann, gehört er in einen TRY/CATCH-Block. Nach einem Fehler-Status ist HTTP_STATUS noch lesbar, sodass du gezielt reagieren kannst."),
  H.code([
    'IMPORT "html"',
    'TRY',
    '    DIM resp AS STRING',
    '    resp = HTTP_GET("https://api.example.com/fehlt")',
    'CATCH e',
    '    IF HTTP_STATUS() = 404 THEN',
    '        PRINT "Adresse gibt es nicht."',
    '    ELSE',
    '        PRINT "Netzwerkfehler:", e',
    '    END IF',
    'END TRY',
  ]),

  H.h2("URLs aufbereiten: URL_ENCODE / URL_DECODE"),
  H.p("In einer Web-Adresse dürfen viele Zeichen (Leerzeichen, &, ?, Umlaute) nicht direkt vorkommen. URL_ENCODE verwandelt einen Text in eine sichere Form, URL_DECODE macht es rückgängig. Das brauchst du, sobald du Suchbegriffe oder Namen in eine URL einbaust."),
  H.cmd("URL_ENCODE · URL_DECODE", 'URL_ENCODE(text$)   URL_DECODE(text$)',
    "ENCODE ersetzt Sonderzeichen durch %XX-Sequenzen (Leerzeichen → %20, & → %26). DECODE löst sie wieder auf.",
    [
      'IMPORT "html"',
      'PRINT URL_ENCODE("hallo welt & co")',
      'PRINT URL_DECODE("hallo%20welt%20%26%20co")',
    ], { out: ["hallo%20welt%20%26%20co", "hallo welt & co"] }),

  H.h2("HTML zerlegen"),
  H.p("Antworten von Webseiten sind oft HTML – Text gemischt mit Formatierungs-Tags. Drei Helfer holen die nützlichen Teile heraus: HTML_TEXT entfernt alle Tags und liefert reinen Lesetext, HTML_FIND_ALL sammelt den Inhalt aller Tags einer Sorte, HTML_GET_ATTR zieht ein Attribut (etwa die Ziel-Adresse eines Links) aus einem Tag."),
  H.cmd("HTML_TEXT", 'HTML_TEXT(html$)',
    "Streift alle Tags weg und wandelt HTML-Sonderschreibweisen zurück (&amp; → &). Block-Elemente wie <p> erzeugen einen Zeilenumbruch; <script>/<style> werden übersprungen.",
    [
      'IMPORT "html"',
      'PRINT HTML_TEXT("<p>Hallo <b>Welt</b></p><p>Zeile&amp;2</p>")',
    ], { out: ["Hallo Welt", "Zeile&2"] }),
  H.cmd("HTML_FIND_ALL", 'HTML_FIND_ALL(html$, tag$)',
    "Liefert den Innen-Inhalt aller Vorkommen eines Tags als ARRAY OF STRING. Gleichnamige verschachtelte Tags werden korrekt zugeordnet.",
    [
      'IMPORT "html"',
      'DIM items AS ARRAY OF STRING',
      'items = HTML_FIND_ALL("<ul><li>Apfel</li><li>Birne</li></ul>", "li")',
      'PRINT LEN(items)',
      'PRINT items[0]; "|"; items[1]',
    ], { out: ["2", "Apfel|Birne"] }),
  H.cmd("HTML_GET_ATTR", 'HTML_GET_ATTR(tag_html$, attribut$)',
    "Holt den Wert eines Attributs aus dem ersten Tag im übergebenen Schnipsel – z. B. das href eines Links. Versteht doppelte, einfache und unquotierte Werte.",
    [
      'IMPORT "html"',
      "PRINT HTML_GET_ATTR(\"<a href='https://example.com'>x</a>\", \"href\")",
    ], { out: ["https://example.com"] }),

  H.h2("Alles zusammen: eine Überschrift aus dem Web"),
  H.p("Abruf und HTML-Zerlegung greifen ineinander: Seite holen, gewünschte Tags sammeln, Text herausziehen."),
  H.code([
    'IMPORT "html"',
    'DIM page AS STRING',
    'page = HTTP_GET("https://example.com")',
    'DIM h AS ARRAY OF STRING',
    'h = HTML_FIND_ALL(page, "h1")',
    'PRINT HTML_TEXT(h[0])',
  ], { out: ["Example Domain"] }),

  H.h2("Beliebige Anfragen und dauerhafte Kopfzeilen"),
  H.cmd("HTTP_REQUEST", "HTTP_REQUEST(methode$, url$[, rumpf[, kopfzeilen]])",
    "Für alles, was über GET und POST hinausgeht: PUT, DELETE, PATCH – mit eigenem Rumpf und eigenen Kopfzeilen. Die Kopfzeilen übergibst du als MAP OF STRING.",
    [
      'IMPORT "html"',
      "DIM kopf AS MAP OF STRING",
      "DIM antwort AS STRING",
      'MAPPUT(kopf, "Content-Type", "application/json")',
      'antwort = HTTP_REQUEST("PUT", "https://api.example.com/dinge/7", "{""name"":""Anna""}", kopf)',
      "PRINT HTTP_STATUS()",
    ]),
  H.warn("HTTP_REQUEST rät keinen Content-Type. Welchen Typ ein Rumpf hat, weiß nur der Aufrufer; ein falsch geratenes application/json wäre schlimmer als gar keines. Wer JSON schickt, setzt die Kopfzeile also selbst.",
    "Merke"),
  H.cmd("HTTP_SET_HEADER · HTTP_CLEAR_HEADERS", "HTTP_SET_HEADER(name$, wert$)   HTTP_CLEAR_HEADERS()",
    "Setzt eine Kopfzeile für alle folgenden Aufrufe des Moduls – der übliche Weg für einen Anmelde-Token, den man nicht bei jedem Aufruf wiederholen will. Eine Kopfzeile, die beim einzelnen Aufruf mitgegeben wird, gewinnt gegen die dauerhafte; zweimal derselbe Name ersetzt, statt sich zu häufen.",
    [
      'HTTP_SET_HEADER("Authorization", "Bearer abc123")',
      'PRINT HTTP_GET("https://api.example.com/profil")',
      "HTTP_CLEAR_HEADERS()          ' wieder abmelden",
    ]),
  H.cmd("HTTP_BYTES", "HTTP_BYTES()",
    "Der rohe Rumpf der letzten Antwort als BUFFER. Der gewöhnliche Rückgabewert ist Text, und dabei werden nicht dekodierbare Bytes ersetzt – bei einem Bild oder einer Zip-Datei bliebe davon nichts Brauchbares.",
    [
      'IMPORT "html"',
      "DIM egal AS STRING",
      "DIM bild AS BUFFER",
      'egal = HTTP_REQUEST("GET", "https://example.com/logo.png")',
      "bild = HTTP_BYTES()",
      'WRITEALL_BYTES("logo.png", bild)',
    ]),
  H.note("HTTP_BYTES gehört – wie HTTP_STATUS und HTTP_HEADER – zur letzten Antwort und funktioniert nach jedem Aufruf. Nach einem fehlgeschlagenen ist es leer, und nicht etwa noch die vorige Antwort. Wer eine große Datei nur speichern will, nimmt weiterhin HTTP_DOWNLOAD: Das schreibt direkt auf die Platte, ohne sie in den Speicher zu holen.",
    "Merke"),

  H.h2("Abrufe im Hintergrund"),
  H.p("HTTP_GET hält das ganze Programm an, bis die Antwort da ist. In einem Fenster heißt das: keine Maus, keine Taste, kein Neuzeichnen. Ein mittlerer Abruf dauert etwa 200 Millisekunden – rund zwölf ausgefallene Bilder, und bei schlechter Verbindung wartet das Fenster bis zur Zeitgrenze von zehn Sekunden. Für alles, was in einer Schleife läuft, gibt es denselben Abruf zum Nachsehen statt zum Warten."),
  H.cmd("HTTP_GET_START · HTTP_REQUEST_START", "HTTP_GET_START(url$)   HTTP_REQUEST_START(methode$, url$[, rumpf[, kopfzeilen]])",
    "Startet den Abruf im Hintergrund und liefert sofort eine Abruf-Nummer.",
    [
      "DIM abruf AS INTEGER",
      'abruf = HTTP_GET_START("https://api.example.com/scores")',
    ]),
  H.cmd("HTTP_READY · HTTP_RESULT", "HTTP_READY(abruf)   HTTP_RESULT(abruf)",
    "HTTP_READY fragt nach, ob die Antwort da ist, und wartet nicht. HTTP_RESULT holt den Rumpf ab und gibt den Platz frei – dabei werden auch HTTP_STATUS, HTTP_HEADER und HTTP_BYTES gesetzt, also beim Abholen und nicht beim Starten.",
    [
      "WHILE NOT QUITREQUESTED()",
      "    IF HTTP_READY(abruf) THEN",
      "        PRINT HTTP_RESULT(abruf)",
      "    END IF",
      "    FLIP()",
      "WEND",
    ]),
  H.cmd("HTTP_CANCEL · HTTP_PENDING · HTTP_URL$", "HTTP_CANCEL(abruf)   HTTP_PENDING()   HTTP_URL$(abruf)",
    "Einen Abruf verwerfen, zählen wie viele offen sind, und nachsehen welche Adresse zu einer Abruf-Nummer gehört. Eine unbekannte Nummer bei HTTP_CANCEL tut nichts – so muss man nicht Buch führen.",
    [
      "PRINT HTTP_PENDING()",
    ]),
  H.cmd("HTTP_TIMEOUT", "HTTP_TIMEOUT(sekunden)",
    "Die Zeitgrenze für alle folgenden Aufrufe, 1 bis 600 Sekunden. Ohne Angabe sind es zehn.",
    [
      "HTTP_TIMEOUT(30)",
    ]),

  H.tip("APIs liefern meist JSON", "Die meisten modernen Web-Schnittstellen antworten nicht mit HTML, sondern mit JSON. Dann kombinierst du html mit dem json-Modul (Kapitel 68): Die Antwort von HTTP_GET steckst du direkt in JSON_PARSE und liest die Felder mit JSON_GET_*. HTML zerlegen brauchst du nur, wenn du echte Webseiten „abgrasen“ (scrapen) willst."),
];
