module.exports = (H) => [
  H.chapter("Modul: ecs"),
  H.p("Ein Entity-Component-System (ECS) ist eine andere Art, Spielobjekte zu organisieren. Statt jede Spielfigur als Objekt mit Methoden zu bauen (wie in Kapitel 20), zerlegst du sie in pure Daten und schreibst die Logik getrennt davon. Das klingt erst ungewohnt, ist aber das Modell, mit dem moderne Engines tausende Objekte flüssig bewegen."),

  H.h2("Das mentale Modell: Daten statt Objekte"),
  H.pmix([
    "Drei Begriffe tragen das ganze System. Eine ",
    [' Entity ', true],
    " ist nur eine Nummer – ein Namensschild, das für „ein Ding im Spiel“ steht, ganz ohne Inhalt. Ein ",
    [' Component ', true],
    " ist ein benannter Wert, den du an eine Entity heftest: ",
    ['"px" = 100.0', true],
    ", ",
    ['"hp" = 30', true],
    ". Ein ",
    [' System ', true],
    " schließlich ist eine Schleife, die alle Entities mit bestimmten Components bearbeitet – z. B. „bewege alles, was eine Position UND eine Geschwindigkeit hat“.",
  ]),
  H.p("Der Gewinn: Eine Entity kann beliebig zusammengesetzt werden. Ein Stein hat nur „Position“, ein Gegner zusätzlich „Geschwindigkeit“ und „Leben“, ein Bonus noch „einsammelbar“. Du musst keine Klassenhierarchie planen – du steckst Components zusammen wie Bausteine. Und weil gleichartige Daten dicht beieinander liegen, lassen sie sich blitzschnell in Massen verarbeiten."),

  H.h2("Welt und Entities"),
  H.p("Alles lebt in einer Welt (ECS_WORLD). Darin erzeugst du Entities; jede liefert eine eindeutige Nummer ≥ 1 zurück. Du kannst Entities zerstören, ihren Zustand abfragen und zählen."),
  H.cmd("ECS_NEW_WORLD · ECS_NEW_ENTITY · ECS_COUNT", 'ECS_NEW_WORLD()   ECS_NEW_ENTITY(w)   ECS_COUNT(w)',
    "NEW_WORLD erzeugt eine leere Welt, NEW_ENTITY eine neue Entity (gibt ihre ID zurück), ECS_COUNT zählt die lebenden Entities.",
    [
      'IMPORT "ecs"',
      'DIM w AS ECS_WORLD',
      'w = ECS_NEW_WORLD()',
      'DIM spieler AS INTEGER',
      'spieler = ECS_NEW_ENTITY(w)',
      'DIM gegner AS INTEGER',
      'gegner = ECS_NEW_ENTITY(w)',
      'PRINT ECS_COUNT(w)',
    ], { out: ["2"] }),
  H.cmd("ECS_DESTROY · ECS_ALIVE", 'ECS_DESTROY(w, ent)   ECS_ALIVE(w, ent)',
    "DESTROY entfernt eine Entity samt all ihren Components (TRUE, wenn es sie gab). ECS_ALIVE prüft, ob eine Entity noch lebt.",
    [
      'IMPORT "ecs"',
      'DIM w AS ECS_WORLD',
      'w = ECS_NEW_WORLD()',
      'DIM e AS INTEGER',
      'e = ECS_NEW_ENTITY(w)',
      'ECS_DESTROY(w, e)',
      'PRINT ECS_ALIVE(w, e)',
    ], { out: ["FALSE"] }),

  H.h2("Components anheften und lesen"),
  H.p("Für jeden Datentyp gibt es einen Add-Befehl. Der Component-Name ist ein String – er wird zur Laufzeit angelegt, du musst nichts vorab deklarieren. Heftest du denselben Namen erneut an, wird der Wert überschrieben."),
  H.cmd("ECS_ADD_INT/FLOAT/STRING/BOOL/OBJ", 'ECS_ADD_FLOAT(w, ent, name$, wert)   ECS_ADD_INT/STRING/BOOL/OBJ(...)',
    "Hängt einen benannten Wert an eine Entity. ADD_OBJ nimmt beliebige Werte (eigene Klassen, Maps, Arrays). Der Typ wird beim Anheften geprüft.",
    [
      'IMPORT "ecs"',
      'DIM w AS ECS_WORLD',
      'w = ECS_NEW_WORLD()',
      'DIM p AS INTEGER',
      'p = ECS_NEW_ENTITY(w)',
      'ECS_ADD_FLOAT(w, p, "px", 100.0)',
      'ECS_ADD_INT(w, p, "hp", 30)',
      'ECS_ADD_STRING(w, p, "name", "Hero")',
      'PRINT ECS_GET_STRING(w, p, "name")',
    ], { out: ["Hero"] }),
  H.cmd("ECS_GET_* · ECS_GET_OR_* · ECS_HAS · ECS_REMOVE", 'ECS_GET_INT(w, ent, name$)   ECS_GET_OR_INT(w, ent, name$, default)   ECS_HAS(w, ent, name$)   ECS_REMOVE(w, ent, name$)',
    "GET_* liest einen Component (Fehler, wenn die Entity ihn nicht hat). GET_OR_* liefert stattdessen einen Standardwert. ECS_HAS prüft die Existenz, ECS_REMOVE entfernt einen einzelnen Component.",
    [
      'IMPORT "ecs"',
      'DIM w AS ECS_WORLD',
      'w = ECS_NEW_WORLD()',
      'DIM p AS INTEGER',
      'p = ECS_NEW_ENTITY(w)',
      'ECS_ADD_INT(w, p, "hp", 30)',
      'PRINT ECS_HAS(w, p, "mana")',
      'PRINT ECS_GET_OR_INT(w, p, "mana", -1)',
    ], { out: ["FALSE", "-1"] }),

  H.h2("Systeme: über Components abfragen"),
  H.p("Ein System fragt mit ECS_QUERY alle Entities ab, die eine bestimmte Kombination von Components besitzen, und arbeitet sie ab. Das ist der Kern des Musters: Logik wirkt auf „alles, was diese Daten hat“, egal welcher Art das Spielobjekt sonst ist. Das Ergebnis ist ein ARRAY OF INTEGER mit Entity-IDs."),
  H.cmd("ECS_QUERY · ECS_QUERY2 · ECS_QUERY3", 'ECS_QUERY(w, name$)   ECS_QUERY2(w, n1$, n2$)   ECS_QUERY3(w, n1$, n2$, n3$)',
    "Liefert die IDs aller Entities, die alle genannten Components besitzen. QUERY2/QUERY3 verlangen 2 bzw. 3 Components gleichzeitig (Schnittmenge).",
    [
      'IMPORT "ecs"',
      'DIM w AS ECS_WORLD',
      'w = ECS_NEW_WORLD()',
      'DIM p AS INTEGER',
      'p = ECS_NEW_ENTITY(w)',
      'ECS_ADD_FLOAT(w, p, "px", 0.0)',
      'ECS_ADD_FLOAT(w, p, "vx", 5.0)',
      'DIM mover AS ARRAY OF INTEGER',
      'mover = ECS_QUERY2(w, "px", "vx")',
      'DIM i AS INTEGER',
      'FOR i = 0 TO LEN(mover) - 1',
      '    DIM e AS INTEGER',
      '    e = mover[i]',
      '    ECS_ADD_FLOAT(w, e, "px", ECS_GET_FLOAT(w, e, "px") + ECS_GET_FLOAT(w, e, "vx"))',
      'NEXT',
      'PRINT ECS_GET_FLOAT(w, p, "px")',
    ], { out: ["5.0"] }),

  H.h2("Bulk-Operationen: Massen blitzschnell"),
  H.p("Der Query-Loop oben ist verständlich, aber bei tausenden Entities langsam – pro Entity fallen mehrere Befehlsaufrufe an. Für die heißen Pfade gibt es Bulk-Befehle, die eine ganze Component-Schicht in EINEM Aufruf verarbeiten. Sie sind um ein Vielfaches schneller (realistisch das 40-Fache)."),
  H.cmd("ECS_INTEGRATE_FLOAT · ECS_SCALE_FLOAT · ECS_CLAMP_FLOAT", 'ECS_INTEGRATE_FLOAT(w, ziel$, delta$)   ECS_SCALE_FLOAT(w, ziel$, faktor)   ECS_CLAMP_FLOAT(w, ziel$, lo, hi)',
    "INTEGRATE addiert delta auf ziel für alle Entities mit beiden Components (klassisch Position += Geschwindigkeit). SCALE multipliziert (z. B. Reibung), CLAMP begrenzt auf einen Bereich (z. B. am Bildrand).",
    [
      'IMPORT "ecs"',
      'DIM w AS ECS_WORLD',
      'w = ECS_NEW_WORLD()',
      'DIM p AS INTEGER',
      'p = ECS_NEW_ENTITY(w)',
      'ECS_ADD_FLOAT(w, p, "px", 100.0)',
      'ECS_ADD_FLOAT(w, p, "vx", 5.0)',
      'ECS_INTEGRATE_FLOAT(w, "px", "vx")   \' px += vx fuer alle',
      'PRINT ECS_GET_FLOAT(w, p, "px")',
    ], { out: ["105.0"] }),
  H.cmd("ECS_REMOVE_DEAD · ECS_COUNT_WITH · ECS_FILL_*", 'ECS_REMOVE_DEAD(w, name$, grenze)   ECS_COUNT_WITH(w, name$)   ECS_FILL_FLOAT/INT(w, ziel$, wert)',
    "REMOVE_DEAD zerstört alle Entities, deren Component ≤ grenze ist (z. B. hp ≤ 0). COUNT_WITH zählt die Halter eines Components in konstanter Zeit. FILL setzt alle Werte auf denselben Wert (Reset).",
    [
      'IMPORT "ecs"',
      'DIM w AS ECS_WORLD',
      'w = ECS_NEW_WORLD()',
      'DIM a AS INTEGER',
      'a = ECS_NEW_ENTITY(w)',
      'ECS_ADD_INT(w, a, "hp", 0)',
      'DIM b AS INTEGER',
      'b = ECS_NEW_ENTITY(w)',
      'ECS_ADD_INT(w, b, "hp", 50)',
      'ECS_REMOVE_DEAD(w, "hp", 0)',
      'PRINT ECS_COUNT_WITH(w, "hp")',
    ], { out: ["1"] }),

  H.h2("Weitere Component-Typen und Abfragen"),
  H.cmd("ECS_ADD_BOOL · ECS_ADD_OBJ · ECS_GET_BOOL · ECS_GET", 'ECS_ADD_BOOL(w, e, name$, wert)   ECS_ADD_OBJ(w, e, name$, objekt)   ECS_GET_BOOL(w, e, name$)   ECS_GET(w, e, name$)',
    "Neben Zahlen und Text kannst du auch Wahrheitswerte und beliebige Objekte an eine Entity hängen – etwa eine Klassen-Instanz oder ein Sprite-Handle. ECS_GET liest ein Objekt-Component zurück.",
    [
      'ECS_ADD_BOOL(welt, e, "unsichtbar", FALSE)',
      'ECS_ADD_OBJ(welt, e, "sprite", held_sprite)',
    ]),
  H.cmd("ECS_GET_OR_FLOAT · ECS_GET_OR_STRING · ECS_GET_OR_BOOL", 'ECS_GET_OR_FLOAT(w, e, name$, ersatz)   ECS_GET_OR_STRING(w, e, name$, ersatz$)   ECS_GET_OR_BOOL(w, e, name$, ersatz)',
    "Lesen mit Ersatzwert, falls die Entity dieses Component gar nicht hat – so sparst du dir die Abfrage mit ECS_HAS davor.",
    [
      'DIM tempo AS FLOAT',
      'tempo = ECS_GET_OR_FLOAT(welt, e, "speed", 1.0)',
    ]),
  H.cmd("ECS_INTEGRATE_INT · ECS_FILL_INT", 'ECS_INTEGRATE_INT(w, ziel$, delta$)   ECS_FILL_INT(w, ziel$, wert)',
    "Die INTEGER-Varianten der Bulk-Befehle: INTEGRATE addiert ein Component auf ein anderes (für alle Entities, die beide haben), FILL setzt ein ganzes Component auf einen festen Wert. Ein Aufruf statt einer Schleife über tausende Entities.",
    [
      'ECS_INTEGRATE_INT(welt, "punkte", "punkte_pro_tick")',
      'ECS_FILL_INT(welt, "getroffen", 0)',
    ]),
  H.tip("Wann ECS, wann Klassen?", "Für eine Handvoll unterschiedlicher Objekte (Spieler, ein Boss, ein paar Menüs) sind Klassen (Kapitel 20) übersichtlicher. ECS spielt seine Stärke aus, sobald du SEHR VIELE gleichartige Dinge hast – Geschosse, Partikel, Gegnerschwärme. Dann ein Spiel-System als Bulk-Op zu schreiben statt als Klassen-Schleife ist der Unterschied zwischen flüssigen 1000 Objekten und Ruckeln. Beide Stile lassen sich im selben Spiel mischen."),
];
