module.exports = (H) => [
  H.chapter("Hardware: serial, usb, wifi, bt"),
  H.p("Die letzten vier Module verbinden Drachenhauch mit der physischen Welt: Daten von einem Mikrocontroller lesen (serial), einen selbstgebauten Controller ansprechen (usb), das WLAN verwalten (wifi) oder einen Bluetooth-Sensor auslesen (bt). Sie sind nicht für jedes Spiel gedacht, eröffnen aber spannende Bastel-Projekte – etwa ein Spiel, das auf einen echten Knopf oder einen Temperatursensor reagiert."),
  H.warn("Diese vier Module sind im Standard-dhrt NICHT enthalten. Rufst du eine ihrer Funktionen auf, kommt eine klare Meldung mit der Bau-Anweisung. Du brauchst einen Hardware-Build: python rust\\build_runtime.py --hardware. Außerdem hat jedes Modul eigene Voraussetzungen (Treiber, Plattform), die unten genannt sind. Die folgenden Beispiele sind daher nicht gegen die Laufzeit „abgedruckt“ – sie zeigen die Verwendung.", "Spezial-Build nötig"),
  H.note("Fast alle Abfrage-Funktionen liefern hier mehrzeilige oder komma-getrennte STRINGs (Listen von Geräten/Netzen). Du zerlegst sie mit SPLIT (Kapitel „Strings im Detail“) in ein Array und gehst die Einträge durch."),

  H.h2("serial – Mikrocontroller (Arduino, ESP32)"),
  H.p("Serielle Kommunikation ist der Klassiker, um mit einem Arduino oder ESP32 zu reden: Du öffnest den COM-Port, schickst Befehle und liest die gesendeten Messwerte zeilenweise. Alle Lesebefehle sind durch einen Timeout abgesichert (Standard 1 Sekunde)."),
  H.cmd("SERIAL_PORTS · SERIAL_OPEN · SERIAL_CLOSE", 'SERIAL_PORTS()   SERIAL_OPEN(port$, baud)   SERIAL_CLOSE(h)',
    "PORTS listet die verfügbaren COM-Ports (komma-getrennt). OPEN öffnet einen Port mit der Baudrate (z. B. 9600) und gibt ein SERIAL_HANDLE zurück. CLOSE schließt ihn.",
    [
      'IMPORT "serial"',
      'PRINT "Ports:", SERIAL_PORTS()',
      'DIM ard AS SERIAL_HANDLE',
      'ard = SERIAL_OPEN("COM3", 9600)',
    ]),
  H.cmd("SERIAL_WRITE · SERIAL_READ · SERIAL_READLINE · SERIAL_AVAILABLE", 'SERIAL_WRITE(h, text$)   SERIAL_READLINE(h)   SERIAL_READ(h, n)   SERIAL_AVAILABLE(h)',
    "WRITE schickt Text (gibt die Byte-Zahl zurück). READLINE liest bis zum Zeilenende, READ bis zu n Bytes. SERIAL_AVAILABLE verrät, wie viele Bytes schon im Eingang warten – so liest du nur, wenn etwas da ist.",
    [
      'IMPORT "serial"',
      'DIM ard AS SERIAL_HANDLE',
      'ard = SERIAL_OPEN("COM3", 9600)',
      'SERIAL_WRITE(ard, "LED AN" + CHR$(10))',
      'IF SERIAL_AVAILABLE(ard) > 0 THEN',
      '    PRINT "Sensor:", SERIAL_READLINE(ard)',
      'END IF',
      'SERIAL_CLOSE(ard)',
    ]),

  H.h2("usb – HID-Geräte (Controller, Macro-Pads)"),
  H.p("Über USB-HID sprichst du Eingabegeräte an, die sich als „Human Interface Device“ melden: Macro-Pads, selbstgebaute Controller, Programmer-Boards. Du findest ein Gerät über seine Hersteller-/Produkt-Nummer (VID/PID) und tauschst dann rohe Datenpakete aus."),
  H.cmd("USB_LIST · USB_OPEN · USB_PRODUCT · USB_MANUFACTURER", 'USB_LIST()   USB_OPEN(vid, pid)   USB_PRODUCT(h)   USB_MANUFACTURER(h)',
    "LIST nennt alle HID-Geräte (mehrzeilig, je Zeile vid:pid|Produkt|Hersteller). OPEN öffnet eines per VID/PID und gibt ein USB_HANDLE zurück; PRODUCT/MANUFACTURER lesen die Klartext-Namen.",
    [
      'IMPORT "usb"',
      'PRINT USB_LIST()',
      'DIM pad AS USB_HANDLE',
      'pad = USB_OPEN(&H16C0, &H27DB)   \' VID/PID als Hex',
      'PRINT USB_PRODUCT(pad)',
    ]),
  H.cmd("USB_WRITE · USB_READ · USB_CLOSE", 'USB_WRITE(h, daten$)   USB_READ(h, n, timeout_ms)   USB_CLOSE(h)',
    "WRITE sendet ein Datenpaket, READ liest bis zu n Bytes (mit Zeitlimit in Millisekunden). Die Bytes werden als Zeichen behandelt – mit ASC/CHR$ rechnest du sie in Zahlen um. CLOSE gibt das Gerät frei.",
    [
      'IMPORT "usb"',
      'DIM pad AS USB_HANDLE',
      'pad = USB_OPEN(&H16C0, &H27DB)',
      'DIM bericht AS STRING',
      'bericht = USB_READ(pad, 8, 100)   \' 8 Bytes, max 100 ms warten',
      'IF LEN(bericht) > 0 THEN PRINT "Taste:", ASC(bericht[0])',
      'USB_CLOSE(pad)',
    ]),

  H.h2("wifi – WLAN verwalten"),
  H.p("Das wifi-Modul steuert die WLAN-Verbindung über das jeweilige Betriebssystem-Bordmittel, ganz ohne Zusatz-Bibliothek: netsh unter Windows, nmcli unter Linux, networksetup/airport unter macOS. Du kannst Netze scannen, die aktuelle Verbindung und Signalstärke abfragen oder dich mit SSID und Passwort verbinden."),
  H.note("Der Windows-Pfad (netsh) ist der am längsten erprobte. Die Linux- und macOS-Backends sind neuer und bisher nicht auf echter Hardware verifiziert – bei Problemen lohnt ein Blick in die Fehlermeldung, die Rückgabe von netsh/nmcli/networksetup wird meist direkt durchgereicht."),
  H.cmd("WIFI_AVAILABLE · WIFI_CURRENT · WIFI_SIGNAL · WIFI_SCAN", 'WIFI_AVAILABLE()   WIFI_CURRENT()   WIFI_SIGNAL()   WIFI_SCAN()',
    "AVAILABLE prüft, ob ein WLAN-Adapter da ist. CURRENT liefert die aktuelle SSID (leer = nicht verbunden), SIGNAL die Stärke 0..100. SCAN listet erreichbare Netze (mehrzeilig ssid|signal, nach Stärke sortiert).",
    [
      'IMPORT "wifi"',
      'IF WIFI_AVAILABLE() THEN',
      '    PRINT "Verbunden mit:", WIFI_CURRENT()',
      '    PRINT "Signal:", WIFI_SIGNAL()',
      '    PRINT WIFI_SCAN()',
      'END IF',
    ]),
  H.cmd("WIFI_CONNECT · WIFI_DISCONNECT · WIFI_PROFILES · WIFI_DELETE_PROFILE", 'WIFI_CONNECT(ssid$, passwort$)   WIFI_DISCONNECT()   WIFI_PROFILES()   WIFI_DELETE_PROFILE(name$)',
    "CONNECT legt ein Profil an und verbindet, DISCONNECT trennt. PROFILES listet gespeicherte Netze, DELETE_PROFILE entfernt eines.",
    [
      'IMPORT "wifi"',
      'WIFI_CONNECT("MeinNetz", "geheim123")',
    ]),

  H.h2("bt – Bluetooth Low Energy (Sensoren)"),
  H.p("Mit bt liest du BLE-Geräte aus: Pulsmesser, Thermometer, Wearables, Maker-Boards mit BLE-Chip. Du scannst nach Geräten, verbindest dich über die Adresse und greifst dann auf „Charakteristiken“ zu – das sind die einzelnen Datenpunkte, die ein Gerät über seine Dienste (Services) anbietet."),
  H.cmd("BT_SCAN · BT_CONNECT · BT_IS_CONNECTED · BT_DISCONNECT", 'BT_SCAN(timeout_sek)   BT_CONNECT(addr$)   BT_IS_CONNECTED(h)   BT_DISCONNECT(h)',
    "SCAN sucht für timeout_sek Sekunden und listet gefundene Geräte (addr|name|rssi). CONNECT verbindet über die Adresse und gibt ein BT_HANDLE zurück; IS_CONNECTED prüft den Zustand.",
    [
      'IMPORT "bt"',
      'PRINT BT_SCAN(5.0)',
      'DIM dev AS BT_HANDLE',
      'dev = BT_CONNECT("AA:BB:CC:DD:EE:FF")',
      'PRINT BT_IS_CONNECTED(dev)',
    ]),
  H.cmd("BT_SERVICES · BT_CHARACTERISTICS · BT_READ · BT_WRITE", 'BT_SERVICES(h)   BT_CHARACTERISTICS(h, service$)   BT_READ(h, char_uuid$)   BT_WRITE(h, char_uuid$, daten$)',
    "SERVICES listet die UUIDs der Dienste, CHARACTERISTICS die Datenpunkte eines Dienstes. READ liest den Wert einer Charakteristik (Bytes als Zeichen), WRITE schreibt einen.",
    [
      'IMPORT "bt"',
      'DIM dev AS BT_HANDLE',
      'dev = BT_CONNECT("AA:BB:CC:DD:EE:FF")',
      'DIM wert AS STRING',
      'wert = BT_READ(dev, "00002a37-0000-1000-8000-00805f9b34fb")',
      'PRINT "Puls:", ASC(wert[1])',
      'BT_DISCONNECT(dev)',
    ]),

  H.h2("firmata – Arduino-Pins direkt steuern"),
  H.p("Mit dem serial-Modul redest du über ein selbst ausgedachtes Textprotokoll mit dem Mikrocontroller – du musst also auf beiden Seiten programmieren. Firmata dreht das um: Du lädst EINMAL den fertigen Sketch StandardFirmata auf das Board (in der Arduino-IDE unter Datei → Beispiele → Firmata), und danach steuerst du die Pins direkt aus Drachenhauch. Kein eigener Sketch, kein Protokoll-Basteln."),
  H.cmd("FIRMATA_PORTS · FIRMATA_OPEN · FIRMATA_IS_OPEN · FIRMATA_CLOSE", 'FIRMATA_PORTS()   FIRMATA_OPEN(port$, baud)   FIRMATA_IS_OPEN(h)   FIRMATA_CLOSE(h)',
    "FIRMATA_PORTS listet die verfügbaren seriellen Anschlüsse (dieselben wie SERIAL_PORTS). StandardFirmata läuft üblicherweise mit 57600 Baud.",
    [
      'IMPORT "firmata"',
      'PRINT FIRMATA_PORTS()',
      'DIM board AS FIRMATA_HANDLE',
      'board = FIRMATA_OPEN("COM3", 57600)',
    ]),
  H.cmd("FIRMATA_PIN_MODE", 'FIRMATA_PIN_MODE(h, pin, modus)',
    "Legt fest, was ein Pin tun soll. Die Modus-Werte sind die rohen Firmata-Nummern: 0 = Eingang, 1 = Ausgang, 2 = Analog-Eingang, 3 = PWM, 11 = Eingang mit internem Pullup-Widerstand.",
    [
      'FIRMATA_PIN_MODE(board, 13, 1)      \' Pin 13 als Ausgang (LED)',
      'FIRMATA_PIN_MODE(board, 2, 11)      \' Taster mit Pullup',
    ]),
  H.cmd("FIRMATA_DIGITAL_WRITE · FIRMATA_DIGITAL_READ", 'FIRMATA_DIGITAL_WRITE(h, pin, wert)   FIRMATA_DIGITAL_READ(h, pin)',
    "An oder aus: schreiben schaltet den Pin, lesen liefert seinen Zustand als BOOLEAN. Ein Taster mit Pullup liefert FALSE, wenn er GEDRÜCKT ist (er zieht den Pin auf Masse) – das verwirrt beim ersten Mal.",
    [
      'FIRMATA_DIGITAL_WRITE(board, 13, TRUE)     \' LED an',
      'IF NOT FIRMATA_DIGITAL_READ(board, 2) THEN PRINT "Taster gedrueckt"',
    ]),
  H.cmd("FIRMATA_ANALOG_WRITE · FIRMATA_ANALOG_READ", 'FIRMATA_ANALOG_WRITE(h, pin, wert)   FIRMATA_ANALOG_READ(h, kanal)',
    "ANALOG_WRITE gibt einen PWM-Wert (0–255) aus – LED dimmen, Motor regeln; der Pin muss dafür im Modus 3 stehen. ANALOG_READ liest einen Analogwert (0–1023 auf einem Uno).",
    [
      'FIRMATA_PIN_MODE(board, 9, 3)              \' PWM',
      'FIRMATA_ANALOG_WRITE(board, 9, 128)        \' halbe Helligkeit',
      'PRINT FIRMATA_ANALOG_READ(board, 0)        \' Poti an A0',
    ]),
  H.warn("Schreiben und Lesen sprechen NICHT dieselbe Nummer für denselben Pin: FIRMATA_PIN_MODE, DIGITAL_WRITE/READ und ANALOG_WRITE nehmen die digitale Pin-Nummer (9, 13 …), FIRMATA_ANALOG_READ dagegen den Analog-KANAL (A0 = 0, A1 = 1 …). Das ist eine Eigenheit des Firmata-Protokolls selbst, kein Drachenhauch-Sonderweg. Analog-Pin und -Kanal sind zusätzlich auf 0–15 begrenzt.", "Zwei verschiedene Nummerierungen"),
  H.cmd("FIRMATA_UPDATE", 'FIRMATA_UPDATE(h)',
    "Muss einmal pro Frame aufgerufen werden – erst dann werden die vom Board gemeldeten Pin-Zustände eingelesen. Dasselbe Muster wie INPUT_UPDATE oder TIMER_UPDATE: ohne UPDATE bleiben die Lese-Befehle auf ihrem alten Wert stehen.",
    [
      'WHILE NOT QUITREQUESTED()',
      '    FIRMATA_UPDATE(board)',
      '    IF NOT FIRMATA_DIGITAL_READ(board, 2) THEN springe()',
      '    FLIP()',
      'WEND',
    ]),
  H.note("Firmata deckt Pin-Ein-/Ausgabe ab – Digital, Analog und PWM. I2C-Sensoren, Servos, Schrittmotoren oder OneWire-Thermometer gehören nicht dazu; dafür schreibst du weiterhin einen eigenen Sketch und redest per serial mit ihm."),

  H.h2("mqtt – Nachrichten mit dem IoT-Netz austauschen"),
  H.p("MQTT ist das im Maker- und IoT-Bereich verbreitetste Nachrichtenprotokoll: Geräte schicken Nachrichten an ein „Thema“ (Topic) auf einem Vermittler (Broker), und wer dieses Thema abonniert hat, bekommt sie. Damit steuerst du einen ESP32 aus deinem Spiel heraus – oder lässt umgekehrt einen Sensor dein Spiel steuern."),
  H.cmd("MQTT_CONNECT · MQTT_IS_CONNECTED · MQTT_DISCONNECT", 'MQTT_CONNECT(host$, port, client_id$[, keepalive_s[, benutzer$[, passwort$]]])   MQTT_IS_CONNECTED(h)   MQTT_DISCONNECT(h)',
    "Verbindet sich mit einem Broker (öffentlich etwa test.mosquitto.org, oder ein eigener Mosquitto im Heimnetz). Die client_id$ muss auf dem Broker eindeutig sein.",
    [
      'IMPORT "mqtt"',
      'DIM m AS MQTT_HANDLE',
      'm = MQTT_CONNECT("192.168.1.50", 1883, "drachenhauch-spiel")',
      'IF NOT MQTT_IS_CONNECTED(m) THEN PRINT "Broker nicht erreichbar"',
    ]),
  H.cmd("MQTT_PUBLISH · MQTT_SUBSCRIBE", 'MQTT_PUBLISH(h, topic$, inhalt$[, behalten])   MQTT_SUBSCRIBE(h, topic$)',
    "PUBLISH schickt eine Nachricht an ein Thema; mit behalten = TRUE merkt der Broker sie sich für später hinzukommende Empfänger. SUBSCRIBE abonniert ein Thema – Platzhalter sind erlaubt (+ für eine Ebene, # für alle darunter).",
    [
      'MQTT_PUBLISH(m, "spiel/punkte", STR$(punkte))',
      'MQTT_SUBSCRIBE(m, "wohnzimmer/+/temperatur")',
    ]),
  H.cmd("MQTT_UPDATE · MQTT_NEXT_MESSAGE · MQTT_MESSAGE_TOPIC · MQTT_MESSAGE_PAYLOAD", 'MQTT_UPDATE(h)   MQTT_NEXT_MESSAGE(h)   MQTT_MESSAGE_TOPIC(h)   MQTT_MESSAGE_PAYLOAD(h)',
    "MQTT_UPDATE holt einmal pro Frame die eingetroffenen Nachrichten ab (und hält nebenbei die Verbindung am Leben). Danach holst du sie einzeln ab: MQTT_NEXT_MESSAGE rückt zur nächsten vor und liefert FALSE, wenn keine mehr da ist – dasselbe Cursor-Muster wie DB_NEXT beim Datenbank-Modul.",
    [
      'MQTT_UPDATE(m)',
      'WHILE MQTT_NEXT_MESSAGE(m)',
      '    PRINT MQTT_MESSAGE_TOPIC(m) + " = " + MQTT_MESSAGE_PAYLOAD(m)',
      'WEND',
    ]),
  H.note("Umgesetzt ist MQTT 3.1.1 mit QoS 0 – die Stufe, die praktisch alle ESP32-Beispiele verwenden: Nachrichten werden einmal geschickt, ohne Empfangsbestätigung. Nicht dabei sind QoS 1/2, Testamente (Last Will) und verschlüsselte Verbindungen (TLS)."),

  H.cmd("SERIAL_IS_OPEN · SERIAL_FLUSH · SERIAL_TIMEOUT", 'SERIAL_IS_OPEN(h)   SERIAL_FLUSH(h)   SERIAL_TIMEOUT(h, sekunden)',
    "SERIAL_IS_OPEN prüft die Verbindung (ein abgezogenes USB-Kabel merkt man sonst erst beim Lesen). SERIAL_FLUSH schiebt gepufferte Daten sofort hinaus, SERIAL_TIMEOUT legt fest, wie lange ein Lesevorgang höchstens wartet.",
    [
      'SERIAL_TIMEOUT(h, 0.1)          \' hoechstens 100 ms warten',
      'IF NOT SERIAL_IS_OPEN(h) THEN PRINT "Board abgezogen"',
    ]),
  H.cmd("USB_OPEN_PATH · USB_SERIAL", 'USB_OPEN_PATH(pfad$)   USB_SERIAL(h)',
    "USB_OPEN_PATH öffnet ein Gerät über seinen Systempfad statt über Hersteller- und Produkt-Nummer – nötig, wenn zwei baugleiche Geräte angeschlossen sind. USB_SERIAL liefert die Seriennummer, um sie auseinanderzuhalten.",
    [
      'PRINT USB_SERIAL(h)',
    ]),
  H.tip("Roh-Bytes verstehen", "Hardware schickt selten fertigen Text, sondern rohe Bytes – jede Position im empfangenen STRING ist ein Byte von 0 bis 255. Mit ASC(s[i]) holst du den Zahlenwert eines Bytes, mit CHR$(n) baust du eines zum Senden. Welche Bytes welche Bedeutung haben, steht im Datenblatt des Geräts (bei Standard-BLE-Sensoren in der offiziellen GATT-Spezifikation). Damit endet die Modul-Tour – im Anhang findest du Nachschlage-Tabellen zu allen Befehlen, Tasten und Farben."),
];
