module.exports = (H) => [
  H.chapter("Hardware: serial, usb, wifi, bt"),
  H.p("Die letzten vier Module verbinden GameBasic mit der physischen Welt: Daten von einem Mikrocontroller lesen (serial), einen selbstgebauten Controller ansprechen (usb), das WLAN verwalten (wifi) oder einen Bluetooth-Sensor auslesen (bt). Sie sind nicht für jedes Spiel gedacht, eröffnen aber spannende Bastel-Projekte – etwa ein Spiel, das auf einen echten Knopf oder einen Temperatursensor reagiert."),
  H.warn("Spezial-Build nötig", "Diese vier Module sind im Standard-gbrt NICHT enthalten. Rufst du eine ihrer Funktionen auf, kommt eine klare Meldung mit der Bau-Anweisung. Du brauchst einen Hardware-Build: python rust\\build_runtime.py --hardware. Außerdem hat jedes Modul eigene Voraussetzungen (Treiber, Plattform), die unten genannt sind. Die folgenden Beispiele sind daher nicht gegen die Laufzeit „abgedruckt“ – sie zeigen die Verwendung."),
  H.note("Fast alle Abfrage-Funktionen liefern hier mehrzeilige oder komma-getrennte STRINGs (Listen von Geräten/Netzen). Du zerlegst sie mit SPLIT (Kapitel 16) in ein Array und gehst die Einträge durch."),

  H.h2("serial – Mikrocontroller (Arduino, ESP32)"),
  H.p("Serielle Kommunikation ist der Klassiker, um mit einem Arduino oder ESP32 zu reden: Du öffnest den COM-Port, schickst Befehle und liest die gesendeten Messwerte zeilenweise. Alle Lesebefehle sind durch einen Timeout abgesichert (Standard 1 Sekunde)."),
  H.cmd("SERIAL_PORTS · SERIAL_OPEN · SERIAL_CLOSE", 'SERIAL_PORTS()   SERIAL_OPEN(port$, baud)   SERIAL_CLOSE(h)',
    "PORTS listet die verfügbaren COM-Ports (komma-getrennt). OPEN öffnet einen Port mit der Baudrate (z. B. 9600) und gibt ein SERIAL_HANDLE zurück. CLOSE schließt ihn.",
    [
      'IMPORT "serial"',
      'PRINT "Ports:", SERIAL_PORTS()',
      'DIM ard AS SERIAL_HANDLE',
      'ard = SERIAL_OPEN("COM3", 9600)',
    ]),
  H.cmd("SERIAL_WRITE · SERIAL_READLINE · SERIAL_AVAILABLE", 'SERIAL_WRITE(h, text$)   SERIAL_READLINE(h)   SERIAL_READ(h, n)   SERIAL_AVAILABLE(h)',
    "WRITE schickt Text (gibt die Byte-Zahl zurück). READLINE liest bis zum Zeilenende, READ bis zu n Bytes. SERIAL_AVAILABLE verrät, wie viele Bytes schon im Eingang warten – so liest du nur, wenn etwas da ist.",
    [
      'IMPORT "serial"',
      'DIM ard AS SERIAL_HANDLE',
      'ard = SERIAL_OPEN("COM3", 9600)',
      'SERIAL_WRITE(ard, "LED AN" + CHR$(10))',
      'IF SERIAL_AVAILABLE(ard) > 0 THEN',
      '    PRINT "Sensor:", SERIAL_READLINE(ard)',
      'END IF',
      'SERIAL_CLOSE(ard)',
    ]),

  H.h2("usb – HID-Geräte (Controller, Macro-Pads)"),
  H.p("Über USB-HID sprichst du Eingabegeräte an, die sich als „Human Interface Device“ melden: Macro-Pads, selbstgebaute Controller, Programmer-Boards. Du findest ein Gerät über seine Hersteller-/Produkt-Nummer (VID/PID) und tauschst dann rohe Datenpakete aus."),
  H.cmd("USB_LIST · USB_OPEN · USB_PRODUCT", 'USB_LIST()   USB_OPEN(vid, pid)   USB_PRODUCT(h)   USB_MANUFACTURER(h)',
    "LIST nennt alle HID-Geräte (mehrzeilig, je Zeile vid:pid|Produkt|Hersteller). OPEN öffnet eines per VID/PID und gibt ein USB_HANDLE zurück; PRODUCT/MANUFACTURER lesen die Klartext-Namen.",
    [
      'IMPORT "usb"',
      'PRINT USB_LIST()',
      'DIM pad AS USB_HANDLE',
      'pad = USB_OPEN(&H16C0, &H27DB)   \' VID/PID als Hex',
      'PRINT USB_PRODUCT(pad)',
    ]),
  H.cmd("USB_WRITE · USB_READ · USB_CLOSE", 'USB_WRITE(h, daten$)   USB_READ(h, n, timeout_ms)   USB_CLOSE(h)',
    "WRITE sendet ein Datenpaket, READ liest bis zu n Bytes (mit Zeitlimit in Millisekunden). Die Bytes werden als Zeichen behandelt – mit ASC/CHR$ rechnest du sie in Zahlen um. CLOSE gibt das Gerät frei.",
    [
      'IMPORT "usb"',
      'DIM pad AS USB_HANDLE',
      'pad = USB_OPEN(&H16C0, &H27DB)',
      'DIM bericht AS STRING',
      'bericht = USB_READ(pad, 8, 100)   \' 8 Bytes, max 100 ms warten',
      'IF LEN(bericht) > 0 THEN PRINT "Taste:", ASC(bericht[0])',
      'USB_CLOSE(pad)',
    ]),

  H.h2("wifi – WLAN verwalten (nur Windows)"),
  H.p("Das wifi-Modul steuert die WLAN-Verbindung unter Windows (es nutzt die eingebaute netsh-Schnittstelle, keine Zusatz-Bibliothek). Du kannst Netze scannen, die aktuelle Verbindung und Signalstärke abfragen oder dich mit SSID und Passwort verbinden."),
  H.cmd("WIFI_AVAILABLE · WIFI_CURRENT · WIFI_SIGNAL · WIFI_SCAN", 'WIFI_AVAILABLE()   WIFI_CURRENT()   WIFI_SIGNAL()   WIFI_SCAN()',
    "AVAILABLE prüft, ob ein WLAN-Adapter da ist. CURRENT liefert die aktuelle SSID (leer = nicht verbunden), SIGNAL die Stärke 0..100. SCAN listet erreichbare Netze (mehrzeilig ssid|signal, nach Stärke sortiert).",
    [
      'IMPORT "wifi"',
      'IF WIFI_AVAILABLE() THEN',
      '    PRINT "Verbunden mit:", WIFI_CURRENT()',
      '    PRINT "Signal:", WIFI_SIGNAL()',
      '    PRINT WIFI_SCAN()',
      'END IF',
    ]),
  H.cmd("WIFI_CONNECT · WIFI_DISCONNECT · WIFI_PROFILES", 'WIFI_CONNECT(ssid$, passwort$)   WIFI_DISCONNECT()   WIFI_PROFILES()   WIFI_DELETE_PROFILE(name$)',
    "CONNECT legt ein Profil an und verbindet, DISCONNECT trennt. PROFILES listet gespeicherte Netze, DELETE_PROFILE entfernt eines.",
    [
      'IMPORT "wifi"',
      'WIFI_CONNECT("MeinNetz", "geheim123")',
    ]),

  H.h2("bt – Bluetooth Low Energy (Sensoren)"),
  H.p("Mit bt liest du BLE-Geräte aus: Pulsmesser, Thermometer, Wearables, Maker-Boards mit BLE-Chip. Du scannst nach Geräten, verbindest dich über die Adresse und greifst dann auf „Charakteristiken“ zu – das sind die einzelnen Datenpunkte, die ein Gerät über seine Dienste (Services) anbietet."),
  H.cmd("BT_SCAN · BT_CONNECT · BT_IS_CONNECTED", 'BT_SCAN(timeout_sek)   BT_CONNECT(addr$)   BT_IS_CONNECTED(h)   BT_DISCONNECT(h)',
    "SCAN sucht für timeout_sek Sekunden und listet gefundene Geräte (addr|name|rssi). CONNECT verbindet über die Adresse und gibt ein BT_HANDLE zurück; IS_CONNECTED prüft den Zustand.",
    [
      'IMPORT "bt"',
      'PRINT BT_SCAN(5.0)',
      'DIM dev AS BT_HANDLE',
      'dev = BT_CONNECT("AA:BB:CC:DD:EE:FF")',
      'PRINT BT_IS_CONNECTED(dev)',
    ]),
  H.cmd("BT_SERVICES · BT_CHARACTERISTICS · BT_READ · BT_WRITE", 'BT_SERVICES(h)   BT_CHARACTERISTICS(h, service$)   BT_READ(h, char_uuid$)   BT_WRITE(h, char_uuid$, daten$)',
    "SERVICES listet die UUIDs der Dienste, CHARACTERISTICS die Datenpunkte eines Dienstes. READ liest den Wert einer Charakteristik (Bytes als Zeichen), WRITE schreibt einen.",
    [
      'IMPORT "bt"',
      'DIM dev AS BT_HANDLE',
      'dev = BT_CONNECT("AA:BB:CC:DD:EE:FF")',
      'DIM wert AS STRING',
      'wert = BT_READ(dev, "00002a37-0000-1000-8000-00805f9b34fb")',
      'PRINT "Puls:", ASC(wert[1])',
      'BT_DISCONNECT(dev)',
    ]),

  H.tip("Roh-Bytes verstehen", "Hardware schickt selten fertigen Text, sondern rohe Bytes – jede Position im empfangenen STRING ist ein Byte von 0 bis 255. Mit ASC(s[i]) holst du den Zahlenwert eines Bytes, mit CHR$(n) baust du eines zum Senden. Welche Bytes welche Bedeutung haben, steht im Datenblatt des Geräts (bei Standard-BLE-Sensoren in der offiziellen GATT-Spezifikation). Damit endet die Modul-Tour – im Anhang findest du Nachschlage-Tabellen zu allen Befehlen, Tasten und Farben."),
];
