module.exports = (H) => [
  H.chapter("Modul: midi"),
  H.p("Drachenhauch bringt einen Tracker mit, einen Sampler, einen Synthesizer und einen Notenblatt-Editor – aber bis hierher konnte kein angeschlossenes Keyboard etwas davon ansteuern. Genau diese Brücke schlägt das midi-Modul: Es liest Noten von einem Instrument und schickt welche hinaus."),
  H.p("MIDI überträgt keine Töne, sondern Ereignisse: „Taste 60 mit Stärke 100 gedrückt“. Was daraus klingt, entscheidet der Empfänger. Deshalb kannst du ein Keyboard als Eingabegerät für dein Spiel benutzen, ohne dass darin ein einziger Ton vorkommt – und umgekehrt einen Synthesizer ansteuern, ohne selbst Klang zu erzeugen."),
  H.warn("Das Modul steckt nur in Bauten mit --hardware. Ob dein dhrt es hat, sagt die zweite Zeile von dhrt --version. Zwei Befehle sind ausgenommen: MIDI_NOTE_NAME$ und MIDI_NOTE_FREQ rechnen nur um und stehen in jedem Bau – für eine Notenanzeige oder einen Ton aus einer Notennummer brauchst du also kein Gerät.",
    "Hardware-Modul"),

  H.h2("Anschlüsse finden"),
  H.cmd("MIDI_IN_COUNT · MIDI_OUT_COUNT", "MIDI_IN_COUNT()   MIDI_OUT_COUNT()",
    "Liefert, wie viele MIDI-Eingänge bzw. -Ausgänge das System kennt. Ein Keyboard erscheint als Eingang, ein Synthesizer als Ausgang; viele Geräte sind beides.",
    [
      'IMPORT "midi"',
      'PRINT "Eingänge: "; MIDI_IN_COUNT()',
      'PRINT "Ausgänge: "; MIDI_OUT_COUNT()',
    ]),
  H.cmd("MIDI_IN_NAME$ · MIDI_OUT_NAME$", "MIDI_IN_NAME$(i)   MIDI_OUT_NAME$(i)",
    "Der Name des i-ten Anschlusses, so wie das Gerät sich meldet. Damit baust du eine Auswahlliste, statt eine Nummer zu raten.",
    [
      "DIM i AS INTEGER",
      "FOR i = 0 TO MIDI_IN_COUNT() - 1",
      '    PRINT i; ": "; MIDI_IN_NAME$(i)',
      "NEXT",
    ]),
  H.tip("Zum Ausprobieren brauchst du kein Gerät", "Windows bringt von Haus aus einen MIDI-Ausgang mit, den Microsoft GS Wavetable Synth. Damit kannst du das Senden testen – und du hörst es sogar."),

  H.h2("Öffnen und schließen"),
  H.cmd("MIDI_IN_OPEN · MIDI_OUT_OPEN", "MIDI_IN_OPEN(i)   MIDI_OUT_OPEN(i)",
    "Öffnet den Anschluss mit der Nummer i und liefert ein Handle (MIDI_IN bzw. MIDI_OUT), das alle weiteren Befehle brauchen.",
    [
      "DIM tastatur AS MIDI_IN",
      "tastatur = MIDI_IN_OPEN(0)",
    ]),
  H.cmd("MIDI_IN_CLOSE · MIDI_OUT_CLOSE", "MIDI_IN_CLOSE(h)   MIDI_OUT_CLOSE(h)",
    "Schließt den Anschluss wieder und gibt ihn für andere Programme frei. Nach dem Schließen ist jeder weitere Zugriff auf das Handle ein Fehler im Klartext – kein stilles Nichts.",
    [
      "MIDI_IN_CLOSE(tastatur)",
    ]),

  H.h2("Noten empfangen"),
  H.p("Empfangen läuft über einen Cursor, genau wie bei db und mqtt: MIDI_NEXT holt die nächste Nachricht in einen Zwischenspeicher, und die übrigen Befehle lesen daraus. So brauchst du keine Rückruf-Funktion, und es läuft nichts nebenher."),
  H.cmd("MIDI_NEXT · MIDI_PENDING", "MIDI_NEXT(h)   MIDI_PENDING(h)",
    "MIDI_NEXT holt die nächste Nachricht und liefert TRUE, wenn eine da war (FALSE heißt: nichts angekommen). MIDI_PENDING sagt, wie viele noch warten.",
    [
      "WHILE MIDI_NEXT(tastatur)",
      "    PRINT MIDI_NOTE(tastatur)",
      "WEND",
    ]),
  H.note("Die Schleife ist wichtig – ein einzelnes MIDI_NEXT je Bild reicht nicht: In einem Sechzigstel einer Sekunde können mehrere Nachrichten angekommen sein, ein Akkord sind schon drei. Wer nur eine je Bild abholt, hinkt bei schnellem Spiel immer weiter hinterher.",
    "Merke"),
  H.cmd("MIDI_IS_NOTE_ON · MIDI_IS_NOTE_OFF · MIDI_IS_CC", "MIDI_IS_NOTE_ON(h)   MIDI_IS_NOTE_OFF(h)   MIDI_IS_CC(h)",
    "Sagt, was für eine Nachricht gerade im Zwischenspeicher liegt: eine angeschlagene Note, eine losgelassene, oder ein Regler.",
    [
      "WHILE MIDI_NEXT(tastatur)",
      "    IF MIDI_IS_NOTE_ON(tastatur) THEN",
      '        PRINT "an:  "; MIDI_NOTE_NAME$(MIDI_NOTE(tastatur))',
      "    ELSEIF MIDI_IS_NOTE_OFF(tastatur) THEN",
      '        PRINT "aus: "; MIDI_NOTE_NAME$(MIDI_NOTE(tastatur))',
      "    END IF",
      "WEND",
    ]),
  H.warn("Die meisten Instrumente schicken gar kein „Note aus“. Sie schicken ein Note-an mit Anschlagstärke 0 – das ist im Protokoll ausdrücklich erlaubt und spart ein Byte. MIDI_IS_NOTE_OFF fängt beide Formen ab. Wer stattdessen selbst auf MIDI_STATUS prüft, bekommt Töne, die nie aufhören.",
    "Die häufigste Falle"),
  H.cmd("MIDI_NOTE · MIDI_VELOCITY", "MIDI_NOTE(h)   MIDI_VELOCITY(h)",
    "Die Notennummer (0 bis 127, wobei 60 das eingestrichene C ist) und die Anschlagstärke (0 bis 127). Die Stärke ist der Ausdruck des Spielers – sie eignet sich für Lautstärke, aber genauso für alles andere, was kräftiger ausfallen soll.",
    [
      "DIM laut AS FLOAT",
      "IF MIDI_IS_NOTE_ON(tastatur) THEN",
      "    laut = MIDI_VELOCITY(tastatur) / 127.0",
      '    PRINT "Note "; MIDI_NOTE(tastatur); " mit "; laut',
      "END IF",
    ]),
  H.cmd("MIDI_CC_NUMBER · MIDI_CC_VALUE", "MIDI_CC_NUMBER(h)   MIDI_CC_VALUE(h)",
    "Bei einer Regler-Nachricht: welcher Regler (Nummer) und wie weit er steht (0 bis 127). Nummer 7 ist üblicherweise die Lautstärke, 1 das Modulationsrad.",
    [
      "IF MIDI_IS_CC(tastatur) THEN",
      "    IF MIDI_CC_NUMBER(tastatur) = 1 THEN",
      '        PRINT "Modulationsrad: "; MIDI_CC_VALUE(tastatur)',
      "    END IF",
      "END IF",
    ]),
  H.cmd("MIDI_CHANNEL", "MIDI_CHANNEL(h)",
    "Der Kanal, auf dem die Nachricht kam – 1 bis 16, so wie es auf jedem Gerätedisplay steht. Im Protokoll stehen dort 0 bis 15; die Umrechnung nimmt dir das Modul ab.",
    [
      'PRINT "Kanal "; MIDI_CHANNEL(tastatur)',
    ]),
  H.cmd("MIDI_STATUS · MIDI_DATA1 · MIDI_DATA2", "MIDI_STATUS(h)   MIDI_DATA1(h)   MIDI_DATA2(h)",
    "Die drei rohen Bytes der Nachricht. Brauchst du selten – aber wenn dein Gerät etwas schickt, wofür es keinen eigenen Befehl gibt (Pitch-Bend, Aftertouch, Programmwechsel), kommst du hier heran.",
    [
      'PRINT HEX$(MIDI_STATUS(tastatur)); " "; MIDI_DATA1(tastatur)',
    ]),
  H.note("Uhr-, Active-Sensing- und SysEx-Nachrichten lässt das Modul weg. Ein Keyboard schickt davon Dutzende je Sekunde, und keine davon ist eine Note – sie würden deine Schleife fluten. Der Puffer fasst 1024 unabgeholte Nachrichten; läuft er über, fällt die älteste weg. Wer live spielt, will den aktuellen Anschlag sehen, nicht den von vor zehn Sekunden.",
    "Was nicht durchkommt"),

  H.h2("Noten senden"),
  H.cmd("MIDI_NOTE_ON · MIDI_NOTE_OFF", "MIDI_NOTE_ON(h, kanal, note, anschlag)   MIDI_NOTE_OFF(h, kanal, note)",
    "Schlägt eine Note an bzw. lässt sie los. Der Ton klingt, bis das Aus kommt – ein vergessenes MIDI_NOTE_OFF ist ein hängender Ton, den auch das Programmende nicht beendet.",
    [
      'IMPORT "midi"',
      "DIM synth AS MIDI_OUT",
      "synth = MIDI_OUT_OPEN(0)",
      "MIDI_NOTE_ON(synth, 1, 60, 100)     ' C4 anschlagen",
      "SLEEP(400)",
      "MIDI_NOTE_OFF(synth, 1, 60)",
      "MIDI_OUT_CLOSE(synth)",
    ]),
  H.cmd("MIDI_CC", "MIDI_CC(h, kanal, nr, wert)",
    "Schickt eine Regler-Nachricht. Damit steuerst du am Zielgerät Lautstärke (Nummer 7), Panorama (10) oder was das Gerät sonst anbietet.",
    [
      "MIDI_CC(synth, 1, 7, 90)      ' Lautstärke auf 90",
    ]),
  H.cmd("MIDI_SEND", "MIDI_SEND(h, status, d1, d2)",
    "Schickt eine rohe Nachricht aus drei Bytes – für alles, wofür es keinen eigenen Befehl gibt.",
    [
      "MIDI_SEND(synth, 224, 0, 96)   ' Pitch-Bend, Kanal 1",
    ]),
  H.warn("Note, Anschlag und Reglerwerte müssen zwischen 0 und 127 liegen, Kanäle zwischen 1 und 16. Ein größerer Wert setzt im Protokoll das oberste Bit und würde als völlig andere Nachricht gelesen – deshalb lehnt das Modul ihn ab, statt still etwas anderes zu tun. Geprüft wird, bevor das Gerät überhaupt angesprochen wird.",
    "Wertebereiche"),

  H.h2("Notennummern umrechnen"),
  H.cmd("MIDI_NOTE_NAME$ · MIDI_NOTE_FREQ", "MIDI_NOTE_NAME$(note)   MIDI_NOTE_FREQ(note)",
    "Macht aus einer Notennummer einen lesbaren Namen (60 wird zu C4) oder eine Frequenz in Hertz (69 wird zu 440.0). Die Frequenz ist die Brücke zu AUDIO_TONE. Beide Befehle brauchen kein Gerät und stehen in jedem Bau.",
    [
      'IMPORT "midi"',
      "PRINT MIDI_NOTE_NAME$(60)      ' C4",
      "PRINT MIDI_NOTE_FREQ(69)       ' 440.0",
    ]),
  H.note("Die Oktavzählung folgt der verbreiteten Konvention: Note 60 heißt C4. Manche Hersteller nennen dieselbe Note C3 – das ist eine andere Zählweise, kein Fehler. Und Note 71 heißt hier H, nicht B.",
    "Merke"),

  H.h2("Ein Keyboard zum Klingen bringen"),
  H.p("Das kürzeste sinnvolle Programm: Noten vom Instrument lesen und mit dem eingebauten Synthesizer hörbar machen. Mehr als diese Schleife braucht es nicht."),
  H.code([
    'IMPORT "midi"',
    'IMPORT "audio"',
    "",
    "DIM tastatur AS MIDI_IN",
    "DIM hz AS FLOAT",
    "tastatur = MIDI_IN_OPEN(0)",
    "",
    'SCREEN(400, 120, "MIDI")',
    "WHILE NOT QUITREQUESTED()",
    "    WHILE MIDI_NEXT(tastatur)",
    "        IF MIDI_IS_NOTE_ON(tastatur) THEN",
    "            hz = MIDI_NOTE_FREQ(MIDI_NOTE(tastatur))",
    '            AUDIO_TONE(hz, 300, "sine")',
    "            CLS(BLACK)",
    "            TEXT(20, 50, MIDI_NOTE_NAME$(MIDI_NOTE(tastatur)), WHITE)",
    "        END IF",
    "    WEND",
    "    FLIP()",
    "WEND",
    "MIDI_IN_CLOSE(tastatur)",
  ]),

  H.h2("Was das Modul nicht kann"),
  H.bullet("Kein SysEx – gerätespezifische Klangdaten bleiben außen vor, weder senden noch empfangen."),
  H.bullet("Keine MIDI-Uhr und keinen MIDI-Timecode. Wer zu einer Uhr laufen will, findet in audio mit AUDIO_CLOCK_NEW eine eigene, die sogar genauer ist."),
  H.bullet("Keine .mid-Dateien lesen oder schreiben. Für Musik von der Platte gibt es PLAYMUSIC (auch für .mod und .xm) und den Tracker."),
  H.bullet("Keinen virtuellen Anschluss, den andere Programme sehen."),
];
