module.exports = (H) => [
  H.chapter("Module: zeit & geld"),
  H.p("Zwei Module, die auf denselben Gedanken hinauslaufen: Es gibt Dinge, die als Text oder als Kommazahl fast richtig funktionieren – und genau deshalb schwer zu findende Fehler machen. Ein Datum als Zeichenkette lässt sich nicht vergleichen. Ein Preis als FLOAT verliert Cent. Beide Module machen daraus eine Größe, mit der man rechnen kann."),

  H.h2("Modul zeit: ein Zeitpunkt ist eine Zahl"),
  H.p("DATE$() und TIME$() liefern Text – gut zum Anzeigen, unbrauchbar zum Rechnen. Sobald ein Programm „eine Viertelstunde vor Anpfiff“, „noch 2:15 h“ oder „welcher Wochentag ist das“ wissen will, braucht es Zahlen."),
  H.p("Ein Zeitpunkt ist hier ein INTEGER: Sekunden seit dem 1. Januar 1970, in Ortszeit. Mehr steckt nicht dahinter, und das ist der ganze Trick. Später heißt größer, also ist der Vergleich einfach ein >. Rechnen heißt addieren: eine Viertelstunde sind 15 * 60. Und Monatsenden, Jahreswechsel und Schaltjahre stecken in der Umrechnung, nicht in deinem Programm."),

  H.h2("Zeitpunkte lesen und schreiben"),
  H.cmd("ZEIT_JETZT", "ZEIT_JETZT()",
    "Der aktuelle Zeitpunkt als Zahl. Das ist der Anfang von fast jedem Programm mit Datum.",
    [
      'IMPORT "zeit"',
      "PRINT ZEIT_TEXT$(ZEIT_JETZT())",
    ]),
  H.cmd("ZEIT_PARSE · ZEIT_LESBAR", "ZEIT_PARSE(text$)   ZEIT_LESBAR(text$)",
    "ZEIT_PARSE macht aus Text einen Zeitpunkt. Es versteht die Schreibweisen, die einem in Datenbanken und Web-Schnittstellen begegnen. Unlesbares bricht mit Klartext ab, statt still eine -1 zu liefern – ein kaputtes Datum fiele sonst erst viel später als unsinniges Ergebnis auf. Wo Eingaben unsicher sind, fragt ZEIT_LESBAR vorher, ohne abzubrechen.",
    [
      'IMPORT "zeit"',
      'PRINT ZEIT_TEXT$(ZEIT_PARSE("2026-08-28 20:30:00"))   \' Normalform',
      'PRINT ZEIT_TEXT$(ZEIT_PARSE("2026-08-28T20:30:00Z"))  \' ISO mit Zeitzone',
      'PRINT ZEIT_TEXT$(ZEIT_PARSE("2026-08-28"))            \' nur Datum = 00:00:00',
      "",
      'IF ZEIT_LESBAR("naechsten Dienstag") THEN',
      '    PRINT "geht"',
      "ELSE",
      '    PRINT "Bitte als JJJJ-MM-TT hh:mm eingeben."',
      "END IF",
    ]),
  H.cmd("ZEIT_TEXT$", "ZEIT_TEXT$(zeit)",
    "Der Zeitpunkt als Text in der Normalform JJJJ-MM-TT hh:mm:ss – die Umkehrung von ZEIT_PARSE. Diese Form sortiert SQLite als Textspalte richtig, du kannst Zeitpunkte also so in die Datenbank schreiben und wieder herausrechnen.",
    [
      "PRINT ZEIT_TEXT$(ZEIT_JETZT())",
    ]),
  H.cmd("ZEIT_AUS_TEILEN", "ZEIT_AUS_TEILEN(jahr, monat, tag[, stunde[, minute[, sekunde]]])",
    "Baut einen Zeitpunkt aus Einzelwerten – wenn die Zahlen aus einem Formular, einer Tabelle oder drei Eingabefeldern kommen und du sie nicht erst zu Text zusammenkleben willst.",
    [
      'IMPORT "zeit"',
      "DIM a AS INTEGER",
      "a = ZEIT_AUS_TEILEN(2026, 8, 28, 20, 30)",
      "PRINT ZEIT_TEXT$(a)",
    ]),

  H.h2("Mit Zeit rechnen"),
  H.cmd("ZEIT_PLUS · ZEIT_DIFF", "ZEIT_PLUS(zeit, sekunden)   ZEIT_DIFF(zeit, frueher)",
    "ZEIT_PLUS verschiebt einen Zeitpunkt um Sekunden (negativ heißt zurück). ZEIT_DIFF liefert den Abstand zweier Zeitpunkte in Sekunden – negativ, wenn der erste früher liegt.",
    [
      'IMPORT "zeit"',
      "DIM anstoss AS INTEGER",
      "DIM schluss AS INTEGER",
      'anstoss = ZEIT_PARSE("2026-08-28 20:30:00")',
      "schluss = ZEIT_PLUS(anstoss, -15 * 60)     ' Tippschluss",
      'PRINT "Tippschluss: "; ZEIT_TEXT$(schluss)',
      'PRINT "Vorlauf: "; ZEIT_DIFF(anstoss, schluss); " s"',
    ]),
  H.cmd("ZEIT_DAUER$", "ZEIT_DAUER$(sekunden)",
    "Macht aus einer Sekundenzahl eine lesbare Spanne und wählt dabei die Einheit nach der Größe: 45 s, 12 min, 2:15 h, 3 Tage. Negative Werte bekommen ein „vor“ davor – dieselbe Funktion beantwortet damit „noch wie lange“ und „wie lange her“.",
    [
      'IMPORT "zeit"',
      "PRINT ZEIT_DAUER$(45)         ' 45 s",
      "PRINT ZEIT_DAUER$(8100)       ' 2:15 h",
      "PRINT ZEIT_DAUER$(259200)     ' 3 Tage",
      "PRINT ZEIT_DAUER$(-3600)      ' vor 1:00 h",
    ]),

  H.h2("Teile lesen und anzeigen"),
  H.cmd("ZEIT_TEIL · ZEIT_WOCHENTAG", "ZEIT_TEIL(zeit, feld$)   ZEIT_WOCHENTAG(zeit)",
    "ZEIT_TEIL holt ein einzelnes Feld heraus: jahr, monat, tag, stunde, minute oder sekunde. ZEIT_WOCHENTAG zählt ab Montag (1) bis Sonntag (7) – so bleibt ein Wochenende zusammenhängend, statt über die 1 zu springen.",
    [
      'IMPORT "zeit"',
      "DIM a AS INTEGER",
      'a = ZEIT_PARSE("2026-08-28 20:30:00")',
      'PRINT ZEIT_TEIL(a, "jahr")     \' 2026',
      'PRINT ZEIT_TEIL(a, "stunde")   \' 20',
      "PRINT ZEIT_WOCHENTAG(a)        ' 5 = Freitag",
    ]),
  H.cmd("ZEIT_FORMAT$", "ZEIT_FORMAT$(zeit, muster$)",
    "Zeigt einen Zeitpunkt nach einem Muster an. Die Platzhalter sind deutsch: JJJJ für das Jahr, MM für den Monat, TT für den Tag, hh:mm:ss für die Uhrzeit, WT für den kurzen und WTAG für den ausgeschriebenen Wochentag. Ein leeres Muster liefert die Normalform.",
    [
      'IMPORT "zeit"',
      "DIM a AS INTEGER",
      'a = ZEIT_PARSE("2026-08-28 20:30:00")',
      'PRINT ZEIT_FORMAT$(a, "TT.MM.JJJJ")              \' 28.08.2026',
      'PRINT ZEIT_FORMAT$(a, "WT TT.MM. hh:mm")         \' Fr 28.08. 20:30',
      'PRINT ZEIT_FORMAT$(a, "WTAG, TT.MM.JJJJ hh:mm")  \' Freitag, ...',
    ]),

  H.h2("Ein Countdown im Fenster"),
  H.p("Ein Zeitpunkt als Zahl, jede Sekunde neu angezeigt – mehr braucht ein Countdown nicht."),
  H.code([
    'IMPORT "zeit"',
    "",
    "DIM anstoss AS INTEGER",
    "DIM rest AS INTEGER",
    'anstoss = ZEIT_PARSE("2026-08-28 20:30:00")',
    "",
    'SCREEN(400, 120, "Anpfiff")',
    "WHILE NOT QUITREQUESTED()",
    "    CLS(RGB(20, 24, 32))",
    "    rest = ZEIT_DIFF(anstoss, ZEIT_JETZT())",
    "    IF rest > 0 THEN",
    '        TEXT(20, 30, "Anpfiff in " + ZEIT_DAUER$(rest), WHITE)',
    "    ELSE",
    '        TEXT(20, 30, "Laeuft seit " + ZEIT_DAUER$(-rest), GREEN)',
    "    END IF",
    '    TEXT(20, 60, ZEIT_FORMAT$(anstoss, "WTAG, TT.MM.JJJJ hh:mm"), GRAY)',
    "    FLIP()",
    "WEND",
  ]),
  H.warn("MILLIS() ist etwas anderes und lässt sich nicht umrechnen. Es ist die Stoppuhr für Frame-Zeiten und Timer, nicht die Uhr an der Wand. Wer MILLIS() / 1000 mit ZEIT_JETZT() vergleicht, liegt um den Zeitzonen-Versatz daneben – in Mitteleuropa also um zwei Stunden. Für Datum und Uhrzeit immer ZEIT_JETZT().",
    "Nicht verwechseln"),
  H.note("Zeitpunkte sind Ortszeit. Wer über Zeitzonen hinweg vergleicht, speichert den Text, nicht die Zahl. Und ein Tag ist nicht immer 86400 Sekunden – an den zwei Umstellungstagen im Jahr sind es 23 oder 25 Stunden. ZEIT_PLUS(t, 86400) addiert exakt 86400 Sekunden, was an diesen Tagen nicht dieselbe Uhrzeit am Folgetag ist. Wenn es auf die Uhrzeit ankommt, über ZEIT_TEIL und ZEIT_AUS_TEILEN gehen.",
    "Zwei Fallstricke"),

  H.h2("Modul geld: ein Betrag als eigener Wert"),
  H.p("Für Geld gibt es zwei Wege. CENT, EURO$ und ROUND_HALF_UP (Kapitel „Mathematik“) sind eine Rechenweise: Man rechnet in ganzen Cent und muss daran denken. Das Modul geld macht daraus einen Typ, und der denkt mit."),
  H.code([
    'IMPORT "geld"',
    "DIM preis AS GELD",
    'preis = GELD_NEU("19,99")',
    "PRINT preis * 3          ' 59,97 €",
  ]),
  H.p("In Cent gerechnet ist ein Betrag ein INTEGER wie jeder andere – nichts hindert daran, versehentlich eine Kommazahl dazuzuaddieren. Ein GELD lässt sich nicht mit einer gewöhnlichen Zahl vermischen: preis + 1.0 ist ein Fehler. Dafür muss man GELD_NEU oder GELD_ZAHL schreiben und weiß dann, was man tut. Genau diese Fehlermeldung ist der Unterschied."),

  H.h2("Beträge erzeugen und ausgeben"),
  H.cmd("GELD_NEU · GELD_AUS_CENT", "GELD_NEU(betrag)   GELD_AUS_CENT(cent)",
    "GELD_NEU nimmt Text in deutscher Schreibweise (\"19,99\", \"1.234,56\") oder eine Zahl. GELD_AUS_CENT nimmt ganze Cent, wie sie aus einer Datenbank kommen.",
    [
      'IMPORT "geld"',
      "DIM a AS GELD",
      "DIM b AS GELD",
      'a = GELD_NEU("1.234,56")',
      "b = GELD_AUS_CENT(1999)",
      "PRINT a",
      "PRINT b",
    ]),
  H.cmd("GELD_TEXT$", "GELD_TEXT$(g[, symbol$])",
    "Der Betrag als Text in deutscher Schreibweise. Ohne Angabe steht das Euro-Zeichen dahinter; ein eigenes Symbol geht auch.",
    [
      'PRINT GELD_TEXT$(a)',
      'PRINT GELD_TEXT$(a, "CHF")',
    ]),
  H.cmd("GELD_CENT · GELD_ZAHL", "GELD_CENT(g)   GELD_ZAHL(g)",
    "Der Weg wieder hinaus. GELD_CENT liefert ganze Cent (kaufmännisch gerundet, verlustfrei) – so gehört ein Betrag in eine Datenbank oder eine JSON-Datei. GELD_ZAHL liefert eine Kommazahl; ab da ist es wieder ungenau, aber Diagramme und Tabellen brauchen es so.",
    [
      "PRINT GELD_CENT(b)      ' 1999",
      "PRINT GELD_ZAHL(b)      ' 19.99",
    ]),

  H.h2("Rechnen"),
  H.p("Zwischen zwei Beträgen gehen + und -, mit einer gewöhnlichen Zahl gehen * und /. Ein Betrag geteilt durch einen Betrag ergibt ein Verhältnis als Kommazahl. Verglichen wird mit = <> < > <= >= – und zwar exakt, nicht ungefähr."),
  H.cmd("GELD_RUNDEN · GELD_ABS", "GELD_RUNDEN(g[, stellen])   GELD_ABS(g)",
    "GELD_RUNDEN rundet kaufmännisch, ohne Angabe auf zwei Stellen. GELD_ABS wirft das Vorzeichen weg.",
    [
      'IMPORT "geld"',
      "DIM netto AS GELD",
      'netto = GELD_NEU("0,29")',
      "PRINT netto * 0.19                  ' 0,0551 €",
      "PRINT GELD_RUNDEN(netto * 0.19)     ' 0,06 €",
    ]),
  H.note("Innen ist ein GELD in Hundertstel-Cent gespeichert – vier Nachkommastellen, nicht zwei. Steuersätze und Rabatte erzeugen Zwischenergebnisse mit mehr Stellen, und PRINT zeigt die Stellen, die wirklich da sind. Ein noch nicht gerundetes Zwischenergebnis gleich als „0,06 €“ auszugeben wäre bequem und irreführend – man sähe ihm nicht mehr an, dass es noch nicht gerundet ist. Gerundet wird also bewusst, dort wo ein Betrag ausgewiesen wird.",
    "Warum vier Stellen"),
  H.note("Auch die Multiplikation mit einem Faktor läuft ganzzahlig: Der Faktor wird in seine Ziffern zerlegt und dann wert * 19 / 100 gerechnet. Der Umweg über Fließkomma wäre genau die Ungenauigkeit, gegen die dieser Typ antritt.",
    "Merke"),
  H.cmd("GELD_TEILEN", "GELD_TEILEN(g, anzahl)",
    "Teilt einen Betrag auf, ohne einen Cent zu verlieren. 10,00 € durch drei sind nicht dreimal 3,33 € – ein Cent bliebe liegen. Die ersten Teile bekommen den Rest.",
    [
      'IMPORT "geld"',
      "DIM t AS ARRAY OF GELD",
      't = GELD_TEILEN(GELD_NEU("10,00"), 3)',
      "PRINT t[0]      ' 3,34 €",
      "PRINT t[1]      ' 3,33 €",
      "PRINT t[2]      ' 3,33 €",
    ]),
  H.tip("Von Hand vergisst man diesen Rest fast immer", "Eine Rechnung, die auf drei Personen aufgeteilt wird, geht selten glatt auf. Wer selbst durch drei teilt und rundet, verliert je nach Richtung einen Cent oder erfindet einen – und beides fällt erst beim Kassensturz auf. Das ist einer der Gründe, warum sich für Geld ein eigener Typ lohnt."),

  H.h2("Grenzen des Typs"),
  H.bullet("Keine Währung im Wert. Ein GELD ist ein Betrag, kein „19,99 €“ – wer mit mehreren Währungen rechnet, hält sie selbst auseinander."),
  H.bullet("Kein Literal: preis = 19.99 weist einer GELD-Variablen nichts zu, sondern ist ein Fehler. Es braucht GELD_NEU. Das ist Absicht – ohne diese Strenge wäre die Trennung, für die es den Typ gibt, sofort wieder weg."),
  H.bullet("GELD mal GELD gibt es nicht. Euro mal Euro wären Quadrat-Euro."),
  H.bullet("Nach außen wird es wieder eine Zahl: xlsx, json und chart kennen kein GELD. Dorthin geht es als GELD_CENT (verlustfrei) oder GELD_ZAHL."),
];
