module.exports = (H) => [
  H.chapter("Module: pdf & xlsx"),
  H.p("Zwei Module für den Weg nach draußen: eine druckfertige Seite und eine abgabefertige Tabelle. Beide schreiben nur – sie lesen keine fremden Dateien. Das klingt nach einer Einschränkung, ist aber der Zuschnitt: Ein Programm, das Rechnungen stellt oder Auswertungen ausspuckt, braucht genau diese Richtung."),

  H.h2("Modul pdf: Millimeter, von oben"),
  H.p("PDF selbst rechnet in Punkten und von unten. Wer eine Rechnung setzt, denkt aber in „25 mm vom oberen Rand“ – also rechnet dieses Modul so und dreht die Achse beim Schreiben um. Nur die Schriftgröße bleibt in Punkten, weil sie jeder so kennt."),
  H.code([
    'IMPORT "pdf"',
    "DIM p AS PDF",
    "p = PDF_NEW()                          ' A4 hoch",
    'PDF_FONT(p, "helvetica-fett", 18)',
    'PDF_TEXT(p, 20, 25, "Rechnung 4711")   \' 20 mm links, 25 mm oben',
    "PDF_LINE(p, 20, 36, 190, 36)",
    'PDF_SAVE(p, "rechnung.pdf")',
    "PDF_CLOSE(p)",
  ]),

  H.h2("Dokument und Seiten"),
  H.cmd("PDF_NEW", "PDF_NEW([größe$[, ausrichtung$]])",
    "Legt ein neues Dokument an und liefert ein PDF-Handle. Ohne Angabe A4 hoch; sonst a3 bis a6, letter oder legal, dazu hoch oder quer.",
    [
      'IMPORT "pdf"',
      "DIM p AS PDF",
      'p = PDF_NEW("a5", "quer")',
    ]),
  H.cmd("PDF_PAGE · PDF_PAGE_COUNT", "PDF_PAGE(p)   PDF_PAGE_COUNT(p)",
    "PDF_PAGE beginnt eine neue Seite, PDF_PAGE_COUNT sagt, wie viele es bisher sind. Ein frisches Dokument hat bereits eine Seite – der erste PDF_PAGE-Aufruf erzeugt also die zweite.",
    [
      "PDF_PAGE(p)",
      "PRINT PDF_PAGE_COUNT(p)",
    ]),
  H.cmd("PDF_PAGE_WIDTH · PDF_PAGE_HEIGHT", "PDF_PAGE_WIDTH(p)   PDF_PAGE_HEIGHT(p)",
    "Das Seitenmaß in Millimetern. Damit setzt du etwas an den rechten Rand, ohne die Zahlen der einzelnen Papierformate im Kopf zu haben.",
    [
      "DIM rechts AS FLOAT",
      "rechts = PDF_PAGE_WIDTH(p) - 20.0",
    ]),
  H.cmd("PDF_TITLE", "PDF_TITLE(p, titel$)",
    "Setzt den Titel in den Dokument-Angaben – das ist der Text, den ein PDF-Leser in seiner Fensterleiste zeigt.",
    [
      'PDF_TITLE(p, "Rechnung 4711")',
    ]),

  H.h2("Schrift, Farbe, Strich"),
  H.p("Schrift, Größe, Farbe und Strichstärke sind Einstellungen des Dokuments, nicht der Seite – sie gelten nach einem PDF_PAGE weiter."),
  H.cmd("PDF_FONT", "PDF_FONT(p, schrift$, größe_pt)",
    "Wählt eine der vierzehn Standard-Schriften und die Größe in Punkt. Zur Auswahl stehen helvetica, times und courier – jeweils auch als -fett, -kursiv und -fett-kursiv – dazu symbol und zapfdingbats.",
    [
      'PDF_FONT(p, "helvetica", 11)',
      'PDF_FONT(p, "courier-fett", 10)',
    ]),
  H.cmd("PDF_COLOR · PDF_LINE_WIDTH", "PDF_COLOR(p, farbe)   PDF_LINE_WIDTH(p, mm)",
    "Farbe (als RGB wie in der Grafik) und Strichstärke in Millimetern. Die Farbe gilt für Text, Striche und Flächen gleichermaßen.",
    [
      "PDF_COLOR(p, RGB(40, 40, 40))",
      "PDF_LINE_WIDTH(p, 0.3)",
    ]),
  H.note("Jeder PDF-Leser bringt diese vierzehn Schriften mit – es wird nichts eingebettet. Genau daran hängt der Aufwand eines PDF-Erzeugers: Eine eigene Schriftdatei einzubetten hieße, ihre Tabellen zu zerlegen, Untermengen zu bilden und einen ganzen Font neu aufzubauen.",
    "Warum nur vierzehn"),

  H.h2("Setzen und zeichnen"),
  H.cmd("PDF_TEXT", "PDF_TEXT(p, x, y, text$)",
    "Setzt Text an eine Stelle, gemessen in Millimetern von links und von oben.",
    [
      'PDF_TEXT(p, 20, 60, "Sehr geehrte Damen und Herren,")',
    ]),
  H.cmd("PDF_LINE · PDF_RECT · PDF_RECT_FILL", "PDF_LINE(p, x1, y1, x2, y2)   PDF_RECT(p, x, y, b, h)   PDF_RECT_FILL(p, x, y, b, h)",
    "Eine Linie, ein Rechteck als Umriss, ein Rechteck als Fläche – mehr Geometrie gibt es nicht, und für ein Formular braucht es auch nicht mehr.",
    [
      "PDF_LINE(p, 20, 36, 190, 36)",
      "PDF_COLOR(p, RGB(235, 235, 235))",
      "PDF_RECT_FILL(p, 20, 100, 170, 8)     ' Zeilenhinterlegung",
    ]),
  H.cmd("PDF_TEXT_WIDTH", "PDF_TEXT_WIDTH(p, text$)",
    "Die Breite eines Textes in Millimetern – die Voraussetzung dafür, etwas rechtsbündig zu setzen. Das geht nur bei Courier (und seinen Schnitten): Dort ist jedes Zeichen genau 600 Tausendstel der Schriftgröße breit, das ist die Bauart der Schrift und keine Schätzung. Bei Helvetica und Times meldet der Aufruf einen Fehler, statt zu raten.",
    [
      "PDF_FONT(p, \"courier\", 10)",
      "DIM t AS STRING",
      't = "1.234,56"',
      "PDF_TEXT(p, 188 - PDF_TEXT_WIDTH(p, t), 120, t)",
    ]),
  H.tip("Beschriftungen in Helvetica, Zahlenspalten in Courier", "Damit lassen sich die Beträge exakt rechtsbündig setzen – und nebenbei sieht eine Zahlenspalte in einer dicktengleichen Schrift ohnehin besser aus, weil die Stellen untereinander stehen."),
  H.warn("Der Text geht als cp1252 ins PDF. Deutsch, Französisch und Spanisch sind damit abgedeckt, ohne eine Schrift einzubetten. Ein Zeichen, das cp1252 nicht kennt – ein Emoji, Griechisch, Kyrillisch – ist ein Fehler und wird nicht still durch ein Fragezeichen ersetzt. Auf einer Rechnung ist ein stumm verschwundenes Zeichen schlimmer als eine Meldung.",
    "Umlaute und Sonderzeichen"),

  H.h2("Speichern"),
  H.cmd("PDF_SAVE · PDF_CLOSE", "PDF_SAVE(p, pfad$)   PDF_CLOSE(p)",
    "PDF_SAVE schreibt die Datei, PDF_CLOSE gibt den Speicher frei. Zwei Zusagen gelten dabei: Dieselbe Eingabe ergibt dieselbe Datei – es wird kein Erstellungsdatum hineingeschrieben, was Prüfungen vergleichbar und einen Versionsverlauf lesbar macht. Und die Inhalte sind gepackt, eine Seite kostet also auch bei viel Text kaum etwas.",
    [
      'PDF_SAVE(p, "rechnung.pdf")',
      "PDF_CLOSE(p)",
    ]),
  H.note("Was fehlt: Bilder, Tabellen-Automatik, Zeilenumbruch, Seitenzahlen, Verschlüsselung, eingebettete Schriften. Das ist ein Setzkasten, kein Textsatzsystem – wer eine Seite baut, positioniert selbst. Für ein Formular mit festem Aufbau und wechselnden Zahlen ist das genau richtig; für einen fließenden Bericht mit Umbruch wäre es zu wenig.",
    "Die Grenze"),

  H.h2("Modul xlsx: Auswertungen als Excel-Mappe"),
  H.p("CSV gab es schon, und zum bloßen Weitergeben von Daten reicht es. Was CSV nicht kann: mehrere Blätter, eine fette Kopfzeile, Spaltenbreiten, Zahlen- und Datumsformate – und vor allem Text von Zahl unterscheiden. Eine Postleitzahl wie 01067 wird beim Öffnen einer CSV in Excel zu 1067. Alles zusammen ist der Unterschied zwischen einer Datenliste und einer abgabefertigen Auswertung."),
  H.note("Das Modul schreibt nur. Zum Lesen einer Tabelle ist CSV der Weg – Excel exportiert es, und Drachenhauch liest auch die cp1252-Fassung, die dabei herauskommt. Ein xlsx-Leser müsste geteilte Zeichenketten und Formatvorlagen auflösen; das wäre ein eigenes Modul für einen Fall, den CSV schon deckt.",
    "Nur schreibend"),

  H.h2("Mappe und Blätter"),
  H.cmd("XLSX_NEW", "XLSX_NEW([blattname$])",
    "Legt eine neue Mappe an und liefert ein XLSX-Handle. Ohne Angabe heißt das erste Blatt Tabelle1.",
    [
      'IMPORT "xlsx"',
      "DIM x AS XLSX",
      'x = XLSX_NEW("Umsatz")',
    ]),
  H.cmd("XLSX_SHEET · XLSX_SHEET_COUNT", "XLSX_SHEET(x, name$)   XLSX_SHEET_COUNT(x)",
    "XLSX_SHEET legt ein weiteres Blatt an – und macht es zum aktiven, alle folgenden Schreibbefehle landen dort. Blattnamen dürfen höchstens 31 Zeichen haben und keines der Zeichen enthalten, die Excel verbietet; geprüft wird das hier, nicht erst beim Öffnen.",
    [
      'XLSX_SHEET(x, "Details")',
      "PRINT XLSX_SHEET_COUNT(x)     ' 2",
    ]),

  H.h2("Zellen füllen"),
  H.cmd("XLSX_SET · XLSX_SET_NUM", "XLSX_SET(x, zeile, spalte, text$)   XLSX_SET_NUM(x, zeile, spalte, zahl)",
    "Schreibt eine Text- bzw. eine Zahlzelle. Der Unterschied ist genau der, den CSV nicht machen kann: Was du als Text schreibst, bleibt Text – auch eine Postleitzahl mit führender Null.",
    [
      'IMPORT "xlsx"',
      "DIM x AS XLSX",
      'x = XLSX_NEW("Umsatz")',
      'XLSX_SET(x, 0, 0, "Kunde")',
      'XLSX_SET(x, 0, 1, "Betrag")',
      'XLSX_SET(x, 1, 0, "Schrauben & Muttern GmbH")',
      "XLSX_SET_NUM(x, 1, 1, 1234.5)",
    ]),
  H.warn("Zeile und Spalte zählen ab 0, wie überall in Drachenhauch. Excel selbst zählt ab 1 und benennt Spalten mit Buchstaben: (0, 0) ist also A1, und (0, 26) ist AA1.",
    "Zwei Zählweisen"),
  H.cmd("XLSX_SET_DATE", "XLSX_SET_DATE(x, zeile, spalte, zeit[, muster$])",
    "Schreibt eine Datumszelle. Ein Datum ist in Excel eine Zahl mit Format – der Befehl nimmt Sekunden wie das Modul zeit (und wie FILETIME), rechnet sie in Excels Tageszählung um und setzt das Format. Ohne ihn stünde in der Zelle die nackte Tageszahl.",
    [
      'IMPORT "zeit"',
      "XLSX_SET_DATE(x, 1, 2, ZEIT_JETZT())",
      'XLSX_SET_DATE(x, 2, 2, ZEIT_JETZT(), "DD.MM.YYYY hh:mm")',
    ]),

  H.h2("Gestalten"),
  H.cmd("XLSX_BOLD · XLSX_BOLD_ROW", "XLSX_BOLD(x, zeile, spalte[, an])   XLSX_BOLD_ROW(x, zeile[, an])",
    "Setzt eine Zelle oder eine ganze Zeile fett – letzteres ist der übliche Griff für die Kopfzeile.",
    [
      "XLSX_BOLD_ROW(x, 0)",
    ]),
  H.cmd("XLSX_FORMAT · XLSX_COL_WIDTH", "XLSX_FORMAT(x, zeile, spalte, muster$)   XLSX_COL_WIDTH(x, spalte, breite)",
    "Das Zahlenformat einer Zelle und die Breite einer Spalte (in Zeichen). Das Muster ist Excels eigene Schreibweise und wird unverändert in die Datei geschrieben – was Excel dort versteht, versteht es auch hier.",
    [
      'XLSX_FORMAT(x, 1, 1, "#,##0.00")',
      'XLSX_FORMAT(x, 2, 1, "0.00 ""EUR""")',
      "XLSX_COL_WIDTH(x, 0, 28)",
    ]),
  H.note("Die Gestaltung überlebt eine neue Zuweisung: Wer erst schreibt und dann fett setzt, kann den Wert danach ändern, ohne alles zu wiederholen.",
    "Merke"),

  H.h2("Speichern"),
  H.cmd("XLSX_SAVE · XLSX_CLOSE", "XLSX_SAVE(x, pfad$)   XLSX_CLOSE(x)",
    "Schreibt die Mappe und gibt danach den Speicher frei.",
    [
      'XLSX_SAVE(x, "auswertung.xlsx")',
      "XLSX_CLOSE(x)",
    ]),
  H.p("Keine Formeln, keine Diagramme, keine Farben, keine Rahmen: Das ist ein Schreiber für Auswertungen, kein Tabellenprogramm. Wer rechnen will, rechnet im Programm und schreibt das Ergebnis."),
];
