module.exports = (H) => [
  H.chapter("Module: xml & ini"),
  H.p("Zwei Dateiformate, zwei entgegengesetzte Erwartungen. XML kommt fast immer aus einem fremden Programm – deshalb liest das Modul streng und meldet, was nicht stimmt. Eine INI-Datei bearbeitet ein Mensch mit dem Editor – deshalb überspringt jenes Modul eine kaputte Zeile und macht weiter. Dieselbe Entscheidung, in verschiedene Richtungen begründet."),

  H.h2("Modul xml: nur lesend"),
  H.p("Rechnungen, Ausfuhrlisten, GPX-Spuren, SVG, die Antwort einer älteren Web-Schnittstelle. Bei JSON war das Schreiben die Lücke – ein Programm baut ständig JSON-Rümpfe für Web-Schnittstellen. Bei XML ist es umgekehrt: Der Fall ist fast immer „Daten kommen aus einem fremden System“, und einen XML-Baum selbst zu bauen ist die Ausnahme."),

  H.h2("Einlesen"),
  H.cmd("XML_PARSE · XML_LOAD", "XML_PARSE(text$)   XML_LOAD(pfad$[, kodierung$])",
    "Liest XML aus einer Zeichenkette bzw. aus einer Datei und liefert ein Handle auf die Wurzel. Die Kodierung gibst du wie bei allen Dateibefehlen an; die encoding-Angabe in der XML-Deklaration selbst wird nicht ausgewertet.",
    [
      'IMPORT "xml"',
      "DIM d AS XML_HANDLE",
      'd = XML_PARSE("<r nr=\'7\'><kunde>Meier</kunde></r>")',
      'PRINT XML_NAME$(d)                \' r',
    ]),
  H.cmd("XML_NAME$ · XML_TEXT$", "XML_NAME$(k)   XML_TEXT$(k[, pfad$])",
    "Der Name des Elements und sein Text. XML_TEXT$ nimmt auch gleich einen Pfad, du musst also nicht erst dorthin springen.",
    [
      'PRINT XML_TEXT$(d, "kunde")       \' Meier',
    ]),
  H.note("Gemischter Inhalt behält seine Reihenfolge: <p>Hallo <b>schöne</b> Welt</p> liefert genau „Hallo schöne Welt“. Das klingt selbstverständlich, ist es aber nicht – wer Text und Kind-Elemente getrennt einsammelt, bekommt „Hallo  Weltschöne“. Bei Daten-XML fällt dieser Fehler nie auf und bei Fließtext sofort.",
    "Merke"),
  H.cmd("XML_ATTR$ · XML_ATTR_NAMES", "XML_ATTR$(k, name$[, vorgabe$])   XML_ATTR_NAMES(k)",
    "Ein Attribut lesen bzw. alle Attributnamen als ARRAY OF STRING holen. Ein fehlendes Attribut ist kein Fehler, sondern liefert die Vorgabe – eine fremde Datei lässt weg, was sie nicht braucht, und das ist der Normalfall.",
    [
      'PRINT XML_ATTR$(d, "nr")          \' 7',
      'PRINT XML_ATTR$(d, "waehrung", "EUR")',
    ]),

  H.h2("Im Baum navigieren"),
  H.p("Pfade schreibt man wie bei JSON, nur mit Schrägstrich statt Punkt – so steht es in jedem XML-Beispiel."),
  H.cmd("XML_HAS · XML_FIND", "XML_HAS(k, pfad$)   XML_FIND(k, pfad$)",
    "XML_HAS fragt, ob es den Pfad gibt; XML_FIND springt dorthin. Ein fehlender Pfad ist bei XML_FIND ein Fehler und bei XML_HAS die Antwort FALSE – also erst fragen, dann springen.",
    [
      'IF XML_HAS(d, "kunde") THEN',
      '    PRINT XML_TEXT$(XML_FIND(d, "kunde"))',
      "END IF",
    ]),
  H.cmd("XML_COUNT · XML_AT", "XML_COUNT(k, pfad$)   XML_AT(k, pfad$, i)",
    "Gibt es einen Namen mehrfach, zählt XML_COUNT die Treffer und XML_AT holt den i-ten (ab 0). XML_FIND und XML_TEXT$ nehmen dagegen immer den ersten.",
    [
      'IMPORT "xml"',
      "DIM d AS XML_HANDLE",
      "DIM p AS XML_HANDLE",
      "DIM i AS INTEGER",
      'd = XML_LOAD("rechnung.xml")',
      'FOR i = 0 TO XML_COUNT(d, "posten/p") - 1',
      '    p = XML_AT(d, "posten/p", i)',
      '    PRINT XML_ATTR$(p, "menge"); "x "; XML_TEXT$(p)',
      "NEXT",
    ]),
  H.warn("Ein Pfad, der bei mehreren gleichnamigen Elementen raten würde, wäre der sicherste Weg, beim zweiten Datensatz etwas anderes zu bekommen. Deshalb nimmt XML_FIND immer den ersten – und für alle anderen gibt es XML_COUNT und XML_AT.",
    "Warum immer der erste"),
  H.cmd("XML_CHILD_COUNT · XML_CHILD", "XML_CHILD_COUNT(k)   XML_CHILD(k, i)",
    "Für einen Baum, dessen Aufbau du nicht kennst: alle Kinder der Reihe nach durchlaufen, statt nach Namen zu suchen.",
    [
      'IMPORT "xml"',
      "DIM d AS XML_HANDLE",
      "DIM i AS INTEGER",
      'd = XML_PARSE("<r><a>1</a><b>2</b></r>")',
      "FOR i = 0 TO XML_CHILD_COUNT(d) - 1",
      '    PRINT XML_NAME$(XML_CHILD(d, i)); " = "; XML_TEXT$(XML_CHILD(d, i))',
      "NEXT",
    ]),

  H.h2("XML schreiben, wenn es sein muss"),
  H.cmd("XML_ESCAPE$", "XML_ESCAPE$(text$)",
    "Ersetzt die fünf Sonderzeichen, an denen Handarbeit sonst bricht. Wer XML schreiben muss, klebt es zusammen und schützt die Werte damit.",
    [
      'IMPORT "xml"',
      "DIM kunde AS STRING",
      'kunde = "Schrauben & Muttern"',
      'PRINT "<name>" + XML_ESCAPE$(kunde) + "</name>"',
    ]),
  H.note("Gelesen werden Elemente, Attribute (mit beiden Anführungszeichen), Text, selbstschließende Elemente, die fünf benannten Entities sowie Zeichen in der Form &#65; und &#x41;. Die XML-Deklaration, Kommentare und DOCTYPE werden übersprungen, CDATA wörtlich übernommen. Namensräume bleiben im Namen: <ns:titel> heißt hier ns:titel, und xmlns ist ein gewöhnliches Attribut.",
    "Was gelesen wird"),
  H.warn("Gelesen wird streng: Ein nicht geschlossenes Element bricht mit einer Meldung ab, die die Zeile nennt. Das ist anders als beim ini-Modul nebenan – und mit Absicht. Eine XML-Datei kommt aus einem anderen Programm; ein fehlendes Ende ist dort kein Tippfehler, sondern meist ein Zeichen, dass die Übertragung abgebrochen ist. Stilles Weiterlesen wäre dann die schlechteste Antwort.",
    "Streng, nicht nachsichtig"),

  H.h2("Modul ini: eine Datei, die ein Mensch anfasst"),
  H.p("JSON und CSV gab es schon. Für eine Datei, die jemand von Hand bearbeitet, ist beides unhandlich: JSON verzeiht kein Komma zu viel, CSV hat keine benannten Felder. INI ist seit Jahrzehnten genau dafür da."),
  H.p("Das Modul hat keinen eigenen Handle-Typ. Eine INI-Datei ist hier eine MAP OF STRING mit Punkt-Schlüsseln: Aus dem Abschnitt [fenster] und der Zeile breite=1280 wird der Eintrag \"fenster.breite\" mit dem Wert \"1280\". Damit braucht das Modul vier Befehle statt zwei Dutzend Getter und Setter – MAPGETOR, MAPPUT, MAPKEYS und VAL können das alles schon."),
  H.cmd("INI_PARSE · INI_LOAD", "INI_PARSE(text$)   INI_LOAD(pfad$[, kodierung$])",
    "Liest INI aus einer Zeichenkette bzw. einer Datei und liefert eine MAP OF STRING. INI_PARSE(\"\") ist der übliche Griff, wenn es noch keine Einstellungsdatei gibt.",
    [
      'IMPORT "ini"',
      "DIM cfg AS MAP OF STRING",
      'IF FILEEXISTS("einstellungen.ini") THEN',
      '    cfg = INI_LOAD("einstellungen.ini")',
      "ELSE",
      '    cfg = INI_PARSE("")',
      "END IF",
    ]),
  H.cmd("INI_TEXT$ · INI_SAVE", "INI_TEXT$(m)   INI_SAVE(pfad$, m[, kodierung$])",
    "Macht aus der MAP wieder INI-Text bzw. schreibt sie direkt in eine Datei. Abschnitte kommen in der Reihenfolge ihres ersten Auftretens, Schlüssel in ihrer eigenen – eine gelesene und wieder geschriebene Datei sieht aus wie vorher, statt bei jedem Durchlauf neu gemischt zu werden.",
    [
      'IMPORT "ini"',
      "DIM cfg AS MAP OF STRING",
      'cfg = INI_PARSE("[fenster]" + CHR$(10) + "breite=1280")',
      'MAPPUT(cfg, "fenster.titel", "Mein Spiel")',
      'INI_SAVE("einstellungen.ini", cfg)',
      "PRINT INI_TEXT$(cfg)",
    ]),
  H.h2("Einstellungen laden und zurückschreiben"),
  H.p("Das übliche Muster in voller Länge. MAPGETOR liefert die Vorgabe, wenn ein Schlüssel fehlt – bei einer Einstellungsdatei ist das der Normalfall und deshalb kein Fehler."),
  H.code([
    'IMPORT "ini"',
    "",
    "DIM cfg AS MAP OF STRING",
    "DIM breite AS INTEGER",
    "DIM titel AS STRING",
    "",
    'IF FILEEXISTS("einstellungen.ini") THEN',
    '    cfg = INI_LOAD("einstellungen.ini")',
    "ELSE",
    '    cfg = INI_PARSE("")',
    "END IF",
    "",
    'breite = VAL(MAPGETOR(cfg, "fenster.breite", "1280"))',
    'titel  = MAPGETOR(cfg, "fenster.titel", "Mein Spiel")',
    "",
    "SCREEN(breite, 720, titel)",
    "",
    "' ... und beim Beenden zurückschreiben",
    'MAPPUT(cfg, "fenster.breite", STR$(SCREENWIDTH()))',
    'INI_SAVE("einstellungen.ini", cfg)',
  ]),
  H.note("Ein Semikolon oder eine Raute am Zeilenanfang ist ein Kommentar – mittendrin nicht, sonst ließe sich ein Pfad wie C:/a;C:/b nicht speichern. Ein Gleichheitszeichen im Wert bleibt stehen (formel=a=b+c ergibt a=b+c). Anführungszeichen um einen Wert fallen weg, der Leerraum darin bleibt: Das ist der einzige Weg, führende Leerzeichen zu behalten.",
    "Was gelesen wird"),
  H.tip("Kaputte Zeilen halten nicht auf", "Eine Zeile ohne Gleichheitszeichen wird übersprungen, statt den Programmstart abzubrechen. Das ist Absicht: Eine Einstellungsdatei bearbeitet ein Mensch, oft kein Programmierer. Bei JSON dagegen ist eine kaputte Datei fast immer ein Fehler des Programms – und dort bricht das Lesen ab."),
];
