module.exports = (H) => [
  H.chapter("Module: httpd & smtp"),
  H.p("Ein kleiner Webserver und ein E-Mail-Versand. Zusammen mit pdf und xlsx schließen sie die Kette, die in Programmen fürs Büro und für die Werkstatt am häufigsten verlangt wird: einen Bericht bauen und ihn rausschicken – oder ihn im Heimnetz zum Anschauen bereitstellen."),

  H.h2("Modul httpd: ein Webserver im Takt der Hauptschleife"),
  H.p("Für die Bedienoberfläche einer Steuerung, ein Messwert-Blatt im Heimnetz, eine Fernbedienung fürs eigene Programm. Mit mqtt, firmata, serial und net an Bord fehlte für „meine Heizungssteuerung hat eine kleine Weboberfläche“ genau ein Baustein – und es war der kleinste von allen, weil NET_TCP_LISTEN schon darunter liegt."),

  H.h2("Server starten und anhalten"),
  H.cmd("HTTPD_START · HTTPD_PORT · HTTPD_STOP", "HTTPD_START(port[, bind$])   HTTPD_PORT(s)   HTTPD_STOP(s)",
    "HTTPD_START öffnet den Server auf einem Port und liefert ein HTTPD-Handle; eine 0 lässt das Betriebssystem einen freien Port wählen, den HTTPD_PORT dann nennt. HTTPD_STOP beendet ihn wieder.",
    [
      'IMPORT "httpd"',
      "DIM s AS HTTPD",
      "s = HTTPD_START(8080)",
      'PRINT "laeuft auf Port "; HTTPD_PORT(s)',
    ]),

  H.h2("Anfragen annehmen"),
  H.cmd("HTTPD_ACCEPT", "HTTPD_ACCEPT(s)",
    "Fragt, ob eine Anfrage anliegt. Der Aufruf kehrt sofort zurück, wenn niemand anklopft – die Hauptschleife läuft also weiter, auch in einem Spiel mit sechzig Bildern je Sekunde. Dasselbe Muster wie INPUT_UPDATE, TIMER_UPDATE und MQTT_UPDATE: ein Aufruf je Runde.",
    [
      "WHILE NOT QUITREQUESTED()",
      "    IF HTTPD_ACCEPT(s) THEN",
      '        HTTPD_SEND(s, 200, "text/plain", "ok")',
      "    END IF",
      "    SLEEP(10)",
      "WEND",
    ]),
  H.cmd("HTTPD_METHOD$ · HTTPD_PATH$", "HTTPD_METHOD$(s)   HTTPD_PATH$(s)",
    "Die Anfrageart (GET, POST und so weiter) und der angefragte Pfad – letzterer ohne den Frageteil dahinter.",
    [
      'IF HTTPD_METHOD$(s) = "POST" THEN',
      '    PRINT "Formular an "; HTTPD_PATH$(s)',
      "END IF",
    ]),
  H.cmd("HTTPD_QUERY$ · HTTPD_HEADER$ · HTTPD_BODY$", "HTTPD_QUERY$(s, name$)   HTTPD_HEADER$(s, name$)   HTTPD_BODY$(s)",
    "Ein Wert aus dem Frageteil der Adresse (bereits aufgelöst, also ohne Prozentzeichen), eine Kopfzeile (Groß- und Kleinschreibung ist egal) und der Rumpf einer POST-Anfrage.",
    [
      "DIM grad AS FLOAT",
      'grad = VAL(HTTPD_QUERY$(s, "grad"))',
      'PRINT HTTPD_HEADER$(s, "User-Agent")',
    ]),

  H.h2("Antworten"),
  H.cmd("HTTPD_SEND", "HTTPD_SEND(s, code, typ$, inhalt$)",
    "Antwortet mit einem Statuscode, einem Inhaltstyp und dem Inhalt – und schließt die Verbindung. Auf jede angenommene Anfrage gehört genau eine Antwort.",
    [
      'HTTPD_SEND(s, 200, "text/html; charset=utf-8", "<h1>Hallo</h1>")',
      'HTTPD_SEND(s, 404, "text/plain; charset=utf-8", "nicht da")',
    ]),
  H.cmd("HTTPD_SEND_DIR", "HTTPD_SEND_DIR(s, ordner$[, start$])",
    "Liefert den angefragten Pfad aus einem Ordner aus: löst ihn innerhalb des Ordners auf, rät den Inhaltstyp aus der Endung und antwortet. Ein Pfad auf einen Ordner bekommt index.html (oder was als start$ dasteht). Eine fehlende Datei wird zu 404 und liefert FALSE – sie ist der Alltag eines Servers und darf das Programm nicht anhalten.",
    [
      "IF HTTPD_ACCEPT(s) THEN",
      '    IF NOT HTTPD_SEND_DIR(s, "web") THEN',
      '        PRINT "nicht gefunden: "; HTTPD_PATH$(s)',
      "    END IF",
      "END IF",
    ]),
  H.cmd("HTTPD_SEND_FILE", "HTTPD_SEND_FILE(s, code, pfad$)",
    "Liefert eine bestimmte Datei aus. Gedacht für den Fall, dass das Programm entscheidet, welche Datei rausgeht – dort steht kein fremder Pfad im Spiel.",
    [
      'HTTPD_SEND_FILE(s, 200, "berichte/august.pdf")',
    ]),
  H.warn("Nimm HTTPD_SEND_DIR, nicht Handarbeit. Die naheliegende Zeile HTTPD_SEND_FILE(s, 200, \"web\" + HTTPD_PATH$(s)) lässt sich mit einer Anfrage auf /../../geheim.txt aus dem Ordner herausführen und liefert dann irgendeine Datei vom Rechner aus. HTTPD_SEND_DIR lehnt jeden Pfadteil mit zwei Punkten ab – dazu Doppelpunkte und umgekehrte Schrägstriche, die unter Windows ein Laufwerk meinen könnten – und antwortet mit 403.",
    "Der Pfad aus der Anfrage ist fremder Text"),

  H.h2("Eine Steuerung mit Weboberfläche"),
  H.code([
    'IMPORT "httpd"',
    "",
    "DIM s AS HTTPD",
    "DIM grad AS FLOAT",
    "s = HTTPD_START(8080)",
    "grad = 21.5",
    "",
    "WHILE NOT QUITREQUESTED()",
    "    IF HTTPD_ACCEPT(s) THEN",
    '        IF HTTPD_PATH$(s) = "/setzen" THEN',
    '            grad = VAL(HTTPD_QUERY$(s, "grad"))',
    '            HTTPD_SEND(s, 200, "text/plain; charset=utf-8", "ok")',
    "        ELSE",
    '            HTTPD_SEND(s, 200, "text/html; charset=utf-8", "<h1>" + STR$(grad) + " Grad</h1>")',
    "        END IF",
    "    END IF",
    "    SLEEP(10)",
    "WEND",
    "HTTPD_STOP(s)",
  ]),
  H.note("Kein HTTPS – wer Verschlüsselung braucht, stellt einen fertigen Server davor. Kein Keep-Alive, eine Verbindung je Anfrage. Eine Anfrage je HTTPD_ACCEPT, nacheinander: Zwei Browser gleichzeitig werden bedient, nur eben der Reihe nach. Der Rumpf wird ganz in den Speicher gelesen, höchstens 8 MiB – zum Hochladen großer Dateien taugt der Server nicht. Und eine angefangene Anfrage darf 50 ms brauchen, dann wird sie fallengelassen: Jede Millisekunde hier ist eine, die das Programm nicht zeichnet.",
    "Grenzen – und warum"),

  H.h2("Modul smtp: E-Mail verschicken"),
  H.p("Das Gegenstück zu xlsx und pdf: Dort entsteht die Auswertung, hier geht sie raus. Eine Nachricht wird Stück für Stück zusammengesetzt und am Ende abgeschickt."),

  H.h2("Nachricht und Server"),
  H.cmd("SMTP_NEW · SMTP_CLOSE", "SMTP_NEW()   SMTP_CLOSE(m)",
    "Legt eine neue Nachricht an bzw. gibt sie wieder frei.",
    [
      'IMPORT "smtp"',
      "DIM m AS SMTP",
      "m = SMTP_NEW()",
    ]),
  H.cmd("SMTP_SERVER", "SMTP_SERVER(m, host$, port[, sicherheit$])",
    "Wohin die Nachricht eingeliefert wird. Die Sicherheit ist starttls (erst im Klartext verbinden, dann hochschalten – Port 587), tls (von der ersten Sekunde an verschlüsselt – Port 465) oder keine (Port 25). Ohne Angabe entscheidet der Port: 465 wird tls, 25 wird keine, alles andere starttls.",
    [
      'SMTP_SERVER(m, "smtp.beispiel.de", 587)',
      'SMTP_SERVER(m, "smtp.beispiel.de", 465, "tls")',
    ]),
  H.cmd("SMTP_LOGIN", "SMTP_LOGIN(m, benutzer$, kennwort$)",
    "Die Anmeldung am Server. Weglassen heißt: ohne Anmeldung einliefern. Angemeldet wird mit AUTH PLAIN, sonst mit AUTH LOGIN – die zwei Verfahren, die jeder Server kann.",
    [
      'SMTP_LOGIN(m, "hans@beispiel.de", "geheim")',
    ]),
  H.warn("Ein Kennwort geht nicht unverschlüsselt ins Netz: SMTP_LOGIN zusammen mit \"keine\" ist ein Fehler – außer der Server ist localhost, denn ein Relay auf demselben Rechner ohne TLS ist der Normalfall. Diese Regel kommt aus dem Modul selbst, nicht vom Server. Ohne sie gäbe ein vertippter Port das Kennwort still preis. OAuth2 gibt es nicht; Anbieter, die es verlangen, brauchen stattdessen ein App-Kennwort.",
    "Anmeldung"),

  H.h2("Absender, Empfänger, Inhalt"),
  H.cmd("SMTP_FROM · SMTP_TO · SMTP_CC · SMTP_BCC", "SMTP_FROM(m, adresse$[, name$])   SMTP_TO(m, adresse$[, name$])   SMTP_CC(m, adresse$[, name$])   SMTP_BCC(m, adresse$)",
    "Absender und Empfänger. SMTP_TO und SMTP_CC lassen sich mehrfach aufrufen, für jeden weiteren Empfänger einmal. Die Blindkopie steht nur im Umschlag und nicht in den Kopfzeilen – sonst wäre sie keine.",
    [
      'SMTP_FROM(m, "hans@beispiel.de", "Abteilung Zahlen")',
      'SMTP_TO(m, "chefin@beispiel.de")',
      'SMTP_CC(m, "buero@beispiel.de")',
    ]),
  H.cmd("SMTP_SUBJECT · SMTP_TEXT · SMTP_HTML", "SMTP_SUBJECT(m, betreff$)   SMTP_TEXT(m, text$)   SMTP_HTML(m, html$)",
    "Betreff und Inhalt. Text und HTML schließen sich nicht aus: Wer beide setzt, verschickt beide Fassungen, und der Leser zeigt die an, die er kann. Wer nur eine setzt, bekommt eine einteilige Nachricht – es wird nichts künstlich verschachtelt.",
    [
      'SMTP_SUBJECT(m, "Auswertung August")',
      'SMTP_TEXT(m, "Guten Tag," + CHR$(10) + CHR$(10) + "anbei die Zahlen.")',
    ]),
  H.cmd("SMTP_ATTACH", "SMTP_ATTACH(m, pfad$[, name$])",
    "Hängt eine Datei an, mehrfach aufrufbar. Die Art des Anhangs kommt aus der Dateiendung – aus derselben Tabelle, die auch httpd benutzt. Mit name$ kann der Anhang beim Empfänger anders heißen als auf der Platte.",
    [
      'SMTP_ATTACH(m, "auswertung.xlsx")',
      'SMTP_ATTACH(m, "tmp/r4711.pdf", "Rechnung 4711.pdf")',
    ]),

  H.h2("Prüfen und abschicken"),
  H.cmd("SMTP_MESSAGE$", "SMTP_MESSAGE$(m)",
    "Liefert genau die Zeichen, die sonst über die Leitung gingen – ohne zu senden. Das ist der Weg, eine Nachricht zu prüfen, wenn man keinen Mailserver hat, und der Weg, sie stattdessen in eine Datei zu schreiben.",
    [
      'WRITEALL("nachricht.eml", SMTP_MESSAGE$(m))',
    ]),
  H.cmd("SMTP_SEND · SMTP_TIMEOUT", "SMTP_SEND(m)   SMTP_TIMEOUT(m, ms)",
    "SMTP_SEND schickt die Nachricht ab. SMTP_TIMEOUT setzt die Frist je Schritt der Unterhaltung mit dem Server; ohne Angabe sind es 30 Sekunden.",
    [
      "SMTP_TIMEOUT(m, 10000)",
      "SMTP_SEND(m)",
      "SMTP_CLOSE(m)",
    ]),

  H.h2("Bericht bauen und rausschicken"),
  H.code([
    'IMPORT "smtp"',
    "",
    "DIM m AS SMTP",
    "m = SMTP_NEW()",
    "",
    'SMTP_SERVER(m, "smtp.beispiel.de", 587)          \' 587 -> STARTTLS',
    'SMTP_LOGIN(m, "hans@beispiel.de", "geheim")',
    "",
    'SMTP_FROM(m, "hans@beispiel.de", "Abteilung Zahlen")',
    'SMTP_TO(m, "chefin@beispiel.de")',
    'SMTP_SUBJECT(m, "Auswertung August")',
    'SMTP_TEXT(m, "Guten Tag," + CHR$(10) + CHR$(10) + "anbei die Zahlen.")',
    'SMTP_ATTACH(m, "auswertung.xlsx")',
    "",
    "SMTP_SEND(m)",
    "SMTP_CLOSE(m)",
  ]),
  H.note("Umlaute im Betreff und im Namen werden kodiert, sonst dürfte dort nur ASCII stehen. Der Rumpf geht als base64 hinaus, auch reiner Text: SMTP hat zwei Fallen – Zeilen über 998 Zeichen und Zeilen, die mit einem Punkt anfangen – und base64 schließt beide auf einmal.",
    "Was hinter den Kulissen passiert"),
  H.warn("Ein Zeilenumbruch in Betreff, Name oder Adresse ist ein Fehler. Er wäre eine zusätzliche Kopfzeile – ein Betreff mit eingebautem Umbruch und einem Bcc dahinter schickt sonst eine stille Kopie. Ihn still zu entfernen wäre die schlechtere Antwort: Dann verschwindet ein Stück Betreff, ohne dass es jemand merkt.",
    "Warum ein Umbruch abgelehnt wird"),
  H.p("Grenzen: Nur senden – Postfächer lesen gehört nicht dazu. Kein OAuth2. Keine Zeitzone, die Datumszeile steht in UTC (ohne Zeitzonen-Datenbank ließe sich die Verschiebung des Rechners nicht benennen, und eine falsche Angabe wäre schlimmer als eine ehrliche). Und ein Anhang liegt vollständig im Speicher, kodiert nochmal ein Drittel größer – für Auswertungen kein Thema, für ein Videoarchiv schon."),
];
