module.exports = (H) => [
  H.chapter("Fremde Bibliotheken: DECLARE … LIB"),
  H.p("Drachenhauch bringt viel mit – Grafik, Ton, Datenbank, Netz, PDF, Hardware. Was trotzdem fehlt, liegt oft schon als C-Bibliothek auf dem Rechner: eine Funktion der Windows-API, die es nicht als Befehl gibt, die Bibliothek eines Messgeräts, die C-Bibliothek des Systems. Mit einer DECLARE-Zeile rufst du sie direkt auf, so wie es VB, FreeBASIC und PureBasic seit jeher können."),
  H.warn("Fremder Code läuft ohne Netz. Ein falscher Zeiger, eine falsche Signatur oder ein Fehler in der Bibliothek beendet das ganze Programm – ohne CATCH und ohne Zeilennummer. Was Drachenhauch prüfen kann (Zahl der Argumente, Typen, Wertebereiche), prüft es; was in der Bibliothek passiert, nicht. Für eine Bibliothek, der du nicht traust, steht am Ende des Kapitels ein Ausweg.", "Vorsicht"),

  H.h2("Eine Funktion deklarieren"),
  H.p("Die Zeile nennt den Namen, die Bibliothek, die Parameter mit ihren C-Typen und – bei einer FUNCTION – den Rückgabetyp. Danach rufst du die Funktion auf wie eine eigene:"),
  H.code([
    'DECLARE FUNCTION strlen LIB "c" (s AS TEXT) AS ZEIGER',
    'DECLARE FUNCTION hypot LIB "m" (x AS FLOAT, y AS FLOAT) AS FLOAT',
    '',
    'PRINT strlen("Drachenhauch")',
    'PRINT hypot(3.0, 4.0)',
  ]),
  H.code(["12", "5.0"], { out: true }),
  H.p("\"c\" ist die C-Bibliothek des Systems, \"m\" ihre Mathematik – beide gibt es unter Windows, Linux und macOS, das Beispiel läuft also überall. Andere Namen werden zur Datei des Systems: \"user32\" wird user32.dll, \"sqlite3\" unter Linux libsqlite3.so und unter macOS libsqlite3.dylib. Gesucht wird neben dem Programm, neben dhrt und dann dort, wo das System sucht."),
  H.bullet("Ohne ALIAS ist der Name zugleich der in der Bibliothek – mit der Schreibweise aus deinem Quelltext, denn in einer Bibliothek zählt Groß/klein: GetTickCount64, nicht gettickcount64."),
  H.bullet("Mit ALIAS darf die Funktion im Programm anders heißen: DECLARE FUNCTION Bytes LIB \"kernel32\" ALIAS \"lstrlenA\" (s AS TEXT) AS LONG."),
  H.bullet("Eine SUB ohne Rückgabe heißt DECLARE SUB. Die Zeile gehört auf die oberste Ebene des Programms; wo genau, ist egal."),
  H.bullet("--check zählt die Argumente schon beim Übersetzen und warnt vor einem Argument, dessen Typ sicher nicht passt. Hover und Zur Definition kennen die Zeile."),

  H.h2("Die Typen"),
  H.p("Die Typen von Drachenhauch sagen nicht, wie breit eine Zahl in C ist. Darum gibt es in der DECLARE-Zeile eigene Typwörter:"),
  H.table([
    ["BYTE / UBYTE", "int8_t / uint8_t", "INTEGER"],
    ["SHORT / USHORT", "int16_t / uint16_t", "INTEGER"],
    ["LONG / ULONG", "int32_t / uint32_t, Windows-DWORD", "INTEGER"],
    ["INTEGER", "int64_t", "INTEGER"],
    ["ZEIGER (PTR)", "void*, size_t, HWND", "INTEGER"],
    ["SINGLE", "float", "FLOAT"],
    ["FLOAT", "double", "FLOAT"],
    ["BOOLEAN", "int (0 = falsch)", "BOOLEAN"],
    ["TEXT (CSTR)", "const char*, UTF-8", "STRING"],
    ["WTEXT (WSTR)", "const wchar_t* (Windows: UTF-16)", "STRING"],
    ["BUFFER", "Zeiger auf die Bytes des Puffers", "BUFFER"],
  ], { headers: ["in DECLARE", "in C", "in Drachenhauch"], mono: [0] }),
  H.p("Ein Wert, der nicht passt, ist ein Fehler: 2^40 für LONG bricht ab, statt still abgeschnitten zu werden, und eine Kommazahl für LONG ebenso. Ein Text wird für den Aufruf kopiert; ein Nullzeichen mitten darin ist ein Fehler, denn C sähe nur den Anfang."),
  H.tip("Vorsicht mit long: in C ist es unter Windows 32 Bit breit, unter Linux und macOS 64 Bit. Dort schreibst du INTEGER. size_t ist immer ZEIGER.", "long ist nicht gleich long"),

  H.h2("Ausgabeparameter mit BYREF"),
  H.p("Viele C-Funktionen liefern einen zweiten Wert über einen Zeiger zurück. BYREF vor einem Zahlentyp übergibt einen Zeiger auf eine Kopie und schreibt sie nach dem Aufruf in deine Variable zurück:"),
  H.code([
    'DECLARE FUNCTION strtod LIB "c" (s AS TEXT, BYREF ende AS ZEIGER) AS FLOAT',
    '',
    'DIM ende AS INTEGER',
    'PRINT strtod("2.5 Meter", ende)',
    'PRINT ende <> 0',
  ]),
  H.code(["2.5", "TRUE"], { out: true }),

  H.h2("Structs und Texte über BUFFER"),
  H.p("Ein C-Struct ist ein Stück Speicher. Das gibt es in Drachenhauch schon: einen BUFFER. Du legst ihn in der richtigen Größe an, übergibst ihn, und die Bibliothek schreibt hinein. Die Felder liest du mit BUFFER_GET_U16 und seinen Geschwistern – ihre Lage samt Ausrichtung rechnest du selbst. Unter Windows sieht das so aus:"),
  H.code([
    'DECLARE SUB GetSystemTime LIB "kernel32" (zeit AS BUFFER)',
    '',
    'DIM st AS BUFFER',
    'st = BUFFER_NEW(16)            \' SYSTEMTIME: acht WORD',
    'GetSystemTime(st)',
    'PRINT "Jahr "; BUFFER_GET_U16(st, 0); ", Monat "; BUFFER_GET_U16(st, 2)',
  ]),
  H.p("Genauso kommen Texte zurück, die eine Funktion schreibt: GetComputerNameW füllt einen Puffer mit UTF-16-Zeichen und nennt die Länge über BYREF. Das ganze Programm steht in den Beispielen als 206_fremde_bibliotheken.dh."),

  H.h2("Zeiger, die eine Bibliothek liefert"),
  H.p("Manche Funktionen geben keinen Wert zurück, sondern einen Zeiger auf Speicher, der der Bibliothek gehört – einen Text, den du danach freigeben sollst, oder ein Stück Bytes. Den Zeiger nimmst du als ZEIGER entgegen; drei Befehle machen daraus etwas, mit dem Drachenhauch arbeiten kann:"),
  H.table([
    ["TEXT_AUS_ZEIGER$(zeiger [, breit])", "Text bis zum Nullzeichen, UTF-8 oder mit breit = TRUE als wchar_t"],
    ["BUFFER_AUS_ZEIGER(zeiger, laenge)", "so viele Bytes in einen neuen BUFFER"],
    ["BUFFER_ZEIGER(puffer)", "die Adresse der Bytes eines BUFFER, für ein Struct-Feld"],
  ], { headers: ["Befehl", "liefert"], mono: [0] }),
  H.code([
    'DECLARE FUNCTION malloc LIB "c" (n AS ZEIGER) AS ZEIGER',
    'DECLARE FUNCTION strcpy LIB "c" (ziel AS ZEIGER, quelle AS TEXT) AS ZEIGER',
    'DECLARE SUB free LIB "c" (z AS ZEIGER)',
    '',
    'DIM z AS INTEGER',
    'z = malloc(16)                   \' 16 Bytes, die der C-Bibliothek gehoeren',
    'strcpy(z, "Grüße")',
    'PRINT TEXT_AUS_ZEIGER$(z)',
    'PRINT BUFFER_LEN(BUFFER_AUS_ZEIGER(z, 8))',
    'free(z)',
  ]),
  H.code(["Grüße", "8"], { out: true }),
  H.p("Alle drei kopieren: Was herauskommt, hängt nicht mehr am Speicher der Bibliothek, und free darf ihn danach freigeben. Die acht Bytes sind die sieben von „Grüße“ in UTF-8 und das Nullzeichen dahinter."),
  H.warn("Die Befehle vertrauen dem Zeiger. Ein falscher oder schon freigegebener Zeiger beendet das Programm wie jeder Fehler in fremdem Code, eine zu große Länge liest über das Ende hinaus. Geprüft werden nur der Nullzeiger und die Länge.", "Vorsicht"),
  H.p("BUFFER_ZEIGER braucht man, wenn ein Struct ein Feld hat, das auf einen anderen Puffer zeigt – ein char* ist auf einem 64-Bit-System acht Bytes breit:"),
  H.code([
    '\' struct { const char* name; int32_t laenge; } -- 16 Bytes',
    'DIM name AS BUFFER',
    'name = BUFFER_CONCAT(BUFFER_FROM_STRING("Drache"), BUFFER_NEW(1))',
    'DIM s AS BUFFER',
    's = BUFFER_NEW(16)',
    'BUFFER_SET_I64(s, 0, BUFFER_ZEIGER(name))',
    'BUFFER_SET_I32(s, 8, 6)',
    'PRINT TEXT_AUS_ZEIGER$(BUFFER_GET_I64(s, 0))',
  ]),
  H.code(["Drache"], { out: true }),
  H.tip("Der Zeiger aus BUFFER_ZEIGER gilt, solange der Puffer seine Größe behält. BUFFER_RESIZE legt die Bytes woanders hin – danach zeigt ein gemerkter Zeiger ins Leere.", "Nicht vergrößern"),

  H.h2("Wenn die Bibliothek fehlt"),
  H.p("Geladen wird erst beim ersten Aufruf. Ein Programm, das den Zweig nie nimmt, läuft auch ohne die Bibliothek – und fehlt sie oder die Funktion darin, ist das ein gewöhnlicher Laufzeitfehler, den CATCH abfängt:"),
  H.code([
    'DECLARE FUNCTION messen LIB "messgeraet" () AS FLOAT',
    '',
    'TRY',
    '    PRINT messen()',
    'CATCH e',
    '    PRINT "Kein Messgerät da."',
    'END TRY',
  ]),

  H.h2("Das Programm weitergeben"),
  H.p("dhrt --export nimmt jede Bibliothek mit, die neben dem Programm liegt, und legt sie neben die exportierte Exe – dort sucht die Laufzeit zuerst. Für eine Systembibliothek wie kernel32 oder die C-Bibliothek ist das nicht nötig; eine fremde, die nicht daneben liegt, nennt der Export als Hinweis, damit du sie selbst mitgibst."),

  H.h2("Unsichere Bibliotheken"),
  H.p("Einer Bibliothek, die abstürzen könnte, gibst du einen eigenen Prozess: Du rufst sie in einem Auftrag mit TASK_START auf (Kapitel „Programme, Aufträge & Umgebung“). Stürzt der Auftrag ab, bekommt dein Programm beim Abholen mit TASK_RESULT$ einen Fehler – „der Auftrag ist abgestuerzt“ – und läuft weiter."),
  H.note("Noch nicht dabei sind Rückrufe (eine Bibliothek, die eine Funktion deines Programms aufruft), Structs als Wert und Funktionen mit variabler Argumentzahl wie printf. Im Browser gibt es keine fremden Bibliotheken."),
];
