module.exports = (H) => [
  H.chapter("Fremde Bibliotheken: DECLARE … LIB"),
  H.p("Drachenhauch bringt viel mit – Grafik, Ton, Datenbank, Netz, PDF, Hardware. Was trotzdem fehlt, liegt oft schon als C-Bibliothek auf dem Rechner: eine Funktion der Windows-API, die es nicht als Befehl gibt, die Bibliothek eines Messgeräts, die C-Bibliothek des Systems. Mit einer DECLARE-Zeile rufst du sie direkt auf, so wie es VB, FreeBASIC und PureBasic seit jeher können."),
  H.warn("Fremder Code läuft ohne Netz. Ein falscher Zeiger, eine falsche Signatur oder ein Fehler in der Bibliothek beendet das ganze Programm – ohne CATCH und ohne Zeilennummer. Was Drachenhauch prüfen kann (Zahl der Argumente, Typen, Wertebereiche), prüft es; was in der Bibliothek passiert, nicht. Für eine Bibliothek, der du nicht traust, steht am Ende des Kapitels ein Ausweg.", "Vorsicht"),

  H.h2("Eine Funktion deklarieren"),
  H.p("Die Zeile nennt den Namen, die Bibliothek, die Parameter mit ihren C-Typen und – bei einer FUNCTION – den Rückgabetyp. Danach rufst du die Funktion auf wie eine eigene:"),
  H.code([
    'DECLARE FUNCTION strlen LIB "c" (s AS TEXT) AS ZEIGER',
    'DECLARE FUNCTION hypot LIB "m" (x AS FLOAT, y AS FLOAT) AS FLOAT',
    '',
    'PRINT strlen("Drachenhauch")',
    'PRINT hypot(3.0, 4.0)',
  ]),
  H.code(["12", "5.0"], { out: true }),
  H.p("\"c\" ist die C-Bibliothek des Systems, \"m\" ihre Mathematik – beide gibt es unter Windows, Linux und macOS, das Beispiel läuft also überall. Andere Namen werden zur Datei des Systems: \"user32\" wird user32.dll, \"sqlite3\" unter Linux libsqlite3.so und unter macOS libsqlite3.dylib. Gesucht wird neben dem Programm, neben dhrt und dann dort, wo das System sucht."),
  H.bullet("Ohne ALIAS ist der Name zugleich der in der Bibliothek – mit der Schreibweise aus deinem Quelltext, denn in einer Bibliothek zählt Groß/klein: GetTickCount64, nicht gettickcount64."),
  H.bullet("Mit ALIAS darf die Funktion im Programm anders heißen: DECLARE FUNCTION Bytes LIB \"kernel32\" ALIAS \"lstrlenA\" (s AS TEXT) AS LONG."),
  H.bullet("Heißt die Bibliothek nicht überall gleich, stehen mehrere Namen durch | getrennt: LIB \"libgtk-3-0.dll|libgtk-3.so.0\" – der erste, der sich laden lässt, gilt. Damit nicht jede Zeile die ganze Liste trägt, darf hinter LIB auch eine CONST stehen: CONST GTK = \"…\" und dann LIB GTK."),
  H.bullet("Eine SUB ohne Rückgabe heißt DECLARE SUB. Die Zeile gehört auf die oberste Ebene des Programms; wo genau, ist egal."),
  H.bullet("--check zählt die Argumente schon beim Übersetzen und warnt vor einem Argument, dessen Typ sicher nicht passt. Hover und Zur Definition kennen die Zeile."),

  H.h2("Die Typen"),
  H.p("Die Typen von Drachenhauch sagen nicht, wie breit eine Zahl in C ist. Darum gibt es in der DECLARE-Zeile eigene Typwörter:"),
  H.table([
    ["BYTE / UBYTE", "int8_t / uint8_t", "INTEGER"],
    ["SHORT / USHORT", "int16_t / uint16_t", "INTEGER"],
    ["LONG / ULONG", "int32_t / uint32_t, Windows-DWORD", "INTEGER"],
    ["INTEGER", "int64_t", "INTEGER"],
    ["ZEIGER (PTR)", "void*, size_t, HWND", "INTEGER"],
    ["SINGLE", "float", "FLOAT"],
    ["FLOAT", "double", "FLOAT"],
    ["BOOLEAN", "int (0 = falsch)", "BOOLEAN"],
    ["TEXT (CSTR)", "const char*, UTF-8", "STRING"],
    ["WTEXT (WSTR)", "const wchar_t* (Windows: UTF-16)", "STRING"],
    ["BUFFER", "Zeiger auf die Bytes des Puffers", "BUFFER"],
  ], { headers: ["in DECLARE", "in C", "in Drachenhauch"], mono: [0] }),
  H.p("Ein Wert, der nicht passt, ist ein Fehler: 2^40 für LONG bricht ab, statt still abgeschnitten zu werden, und eine Kommazahl für LONG ebenso. Ein Text wird für den Aufruf kopiert; ein Nullzeichen mitten darin ist ein Fehler, denn C sähe nur den Anfang."),
  H.tip("Vorsicht mit long: in C ist es unter Windows 32 Bit breit, unter Linux und macOS 64 Bit. Dort schreibst du INTEGER. size_t ist immer ZEIGER.", "long ist nicht gleich long"),

  H.h2("Ausgabeparameter mit BYREF"),
  H.p("Viele C-Funktionen liefern einen zweiten Wert über einen Zeiger zurück. BYREF vor einem Zahlentyp übergibt einen Zeiger auf eine Kopie und schreibt sie nach dem Aufruf in deine Variable zurück:"),
  H.code([
    'DECLARE FUNCTION strtod LIB "c" (s AS TEXT, BYREF ende AS ZEIGER) AS FLOAT',
    '',
    'DIM ende AS INTEGER',
    'PRINT strtod("2.5 Meter", ende)',
    'PRINT ende <> 0',
  ]),
  H.code(["2.5", "TRUE"], { out: true }),

  H.h2("Structs: STRUCT … LAYOUT C"),
  H.p("Ein C-Struct ist ein Stück Speicher mit Feldern an festen Stellen. Du beschreibst ihn mit STRUCT name LAYOUT C und denselben Typwörtern wie in der DECLARE-Zeile; wo jedes Feld liegt – samt der Lücken, die C für die Ausrichtung lässt –, rechnet Drachenhauch aus. Unter Windows sieht das so aus:"),
  H.code([
    'STRUCT SYSTEMTIME LAYOUT C',
    '    jahr AS USHORT',
    '    monat AS USHORT',
    '    wochentag AS USHORT',
    '    tag AS USHORT',
    '    stunde AS USHORT',
    '    minute AS USHORT',
    '    sekunde AS USHORT',
    '    ms AS USHORT',
    'END STRUCT',
    '',
    'DECLARE SUB GetSystemTime LIB "kernel32" (zeit AS SYSTEMTIME)',
    '',
    'DIM st AS SYSTEMTIME',
    'GetSystemTime(st)',
    'PRINT "Jahr "; st.jahr; ", Monat "; st.monat',
  ]),
  H.p("DIM legt einen BUFFER in genau der Größe des Structs an, voller Nullen; er geht ohne Umweg an die Bibliothek, und st.monat liest das Feld an seiner Stelle. Ein Struct kann Felder von Elementen haben, Text fester Breite und andere Structs:"),
  H.code([
    'STRUCT Punkt LAYOUT C',
    '    x AS LONG',
    '    y AS LONG',
    'END STRUCT',
    '',
    'STRUCT Linie LAYOUT C',
    '    farbe AS UBYTE',
    '    ende[2] AS Punkt',
    '    name AS TEXT * 16',
    '    gewicht AS FLOAT',
    'END STRUCT',
    '',
    'DIM l AS Linie',
    'l.ende[1].x = 40',
    'l.name = "Diagonale"',
    'PRINT l.ende[1].x, l.name',
    'PRINT SIZEOF(Linie), OFFSETOF(Linie, name)',
  ]),
  H.code(["40 Diagonale", "48 20"], { out: true }),
  H.bullet("SIZEOF und OFFSETOF sind feste Zahlen, schon beim Übersetzen gerechnet. Nach farbe bleiben drei Bytes frei, damit ende auf einer durch vier teilbaren Stelle liegt; vor gewicht vier, für die acht Bytes des FLOAT."),
  H.bullet("Ein Wert, der nicht ins Feld passt, ist ein Fehler – wie in der DECLARE-Zeile –, ebenso ein Index außerhalb und ein zu langer Text."),
  H.bullet("PACK 1 hinter LAYOUT C lässt die Lücken weg, für Dateiformate und die wenigen APIs, die gepackt sind."),
  H.bullet("Ein Struct ist ein BUFFER, also eine Referenz: b = a teilt die Bytes. Umgekehrt liest du jeden Puffer durch eine Lage, indem du ihn einer Struct-Variable zuweist."),
  H.p("Texte, die eine Funktion schreibt, kommen genauso zurück: GetComputerNameW füllt einen Puffer mit UTF-16-Zeichen und nennt die Länge über BYREF. Das ganze Programm steht in den Beispielen als 206_fremde_bibliotheken.dh."),

  H.h2("Structs als Wert"),
  H.p("Ein Parameter AS Punkt ist in C ein Punkt* – die Funktion bekommt die Adresse deiner Bytes. Manche Funktionen wollen den Struct aber selbst, als Wert, oder geben einen zurück. Dafür steht BYVAL vor dem Parameter, und die Rückgabe heißt einfach wie der Struct. Die komplexen Zahlen der C-Bibliothek sind so ein Fall:"),
  H.code([
    'STRUCT Komplex LAYOUT C',
    '    re AS FLOAT',
    '    im AS FLOAT',
    'END STRUCT',
    'DECLARE FUNCTION csqrt LIB "m" (BYVAL z AS Komplex) AS Komplex',
    '',
    'DIM z AS Komplex',
    'z.re = -4',
    'DIM w AS Komplex',
    'w = csqrt(z)',
    'PRINT w.re, w.im',
  ]),
  H.code(["0.0 2.0"], { out: true }),
  H.bullet("Die Funktion bekommt eine Kopie; was sie daran ändert, siehst du nicht. Die Rückgabe ist ein neuer Struct, den du einer Variable seines Typs zuweist."),
  H.bullet("Wie ein Struct als Wert reist – in Registern, auf dem Stapel oder als Zeiger auf eine Kopie –, legt jedes System anders fest. Drachenhauch hält sich an die Regeln von Windows, Linux und macOS; im Programm siehst du davon nichts."),

  H.h2("Zeiger, die eine Bibliothek liefert"),
  H.p("Manche Funktionen geben keinen Wert zurück, sondern einen Zeiger auf Speicher, der der Bibliothek gehört – einen Text, den du danach freigeben sollst, oder ein Stück Bytes. Den Zeiger nimmst du als ZEIGER entgegen; drei Befehle machen daraus etwas, mit dem Drachenhauch arbeiten kann:"),
  H.table([
    ["TEXT_AUS_ZEIGER$(zeiger [, breit])", "Text bis zum Nullzeichen, UTF-8 oder mit breit = TRUE als wchar_t"],
    ["BUFFER_AUS_ZEIGER(zeiger, laenge)", "so viele Bytes in einen neuen BUFFER"],
    ["BUFFER_ZEIGER(puffer)", "die Adresse der Bytes eines BUFFER, für ein Struct-Feld"],
  ], { headers: ["Befehl", "liefert"], mono: [0] }),
  H.code([
    'DECLARE FUNCTION malloc LIB "c" (n AS ZEIGER) AS ZEIGER',
    'DECLARE FUNCTION strcpy LIB "c" (ziel AS ZEIGER, quelle AS TEXT) AS ZEIGER',
    'DECLARE SUB free LIB "c" (z AS ZEIGER)',
    '',
    'DIM z AS INTEGER',
    'z = malloc(16)                   \' 16 Bytes, die der C-Bibliothek gehoeren',
    'strcpy(z, "Grüße")',
    'PRINT TEXT_AUS_ZEIGER$(z)',
    'PRINT BUFFER_LEN(BUFFER_AUS_ZEIGER(z, 8))',
    'free(z)',
  ]),
  H.code(["Grüße", "8"], { out: true }),
  H.p("Alle drei kopieren: Was herauskommt, hängt nicht mehr am Speicher der Bibliothek, und free darf ihn danach freigeben. Die acht Bytes sind die sieben von „Grüße“ in UTF-8 und das Nullzeichen dahinter."),
  H.warn("Die Befehle vertrauen dem Zeiger. Ein falscher oder schon freigegebener Zeiger beendet das Programm wie jeder Fehler in fremdem Code, eine zu große Länge liest über das Ende hinaus. Geprüft werden nur der Nullzeiger und die Länge.", "Vorsicht"),
  H.p("BUFFER_ZEIGER braucht man, wenn ein Struct ein Feld hat, das auf einen anderen Puffer zeigt – ein char* ist ein ZEIGER-Feld:"),
  H.code([
    'STRUCT Eintrag LAYOUT C',
    '    name AS ZEIGER',
    '    laenge AS LONG',
    'END STRUCT',
    '',
    'DIM name AS BUFFER',
    'name = BUFFER_CONCAT(BUFFER_FROM_STRING("Drache"), BUFFER_NEW(1))',
    'DIM e AS Eintrag',
    'e.name = BUFFER_ZEIGER(name)',
    'e.laenge = 6',
    'PRINT TEXT_AUS_ZEIGER$(e.name), SIZEOF(Eintrag)',
  ]),
  H.code(["Drache 16"], { out: true }),
  H.tip("Der Zeiger aus BUFFER_ZEIGER gilt, solange der Puffer seine Größe behält. BUFFER_RESIZE legt die Bytes woanders hin – danach zeigt ein gemerkter Zeiger ins Leere.", "Nicht vergrößern"),

  H.h2("Wenn die Bibliothek fehlt"),
  H.p("Geladen wird erst beim ersten Aufruf. Ein Programm, das den Zweig nie nimmt, läuft auch ohne die Bibliothek – und fehlt sie oder die Funktion darin, ist das ein gewöhnlicher Laufzeitfehler, den CATCH abfängt:"),
  H.code([
    'DECLARE FUNCTION messen LIB "messgeraet" () AS FLOAT',
    '',
    'TRY',
    '    PRINT messen()',
    'CATCH e',
    '    PRINT "Kein Messgerät da."',
    'END TRY',
  ]),

  H.h2("Rückrufe: die Bibliothek ruft dich"),
  H.p("Manche Bibliotheken rufen zurück: qsort sortiert beliebige Daten und fragt für jedes Paar, welches Element zuerst kommt; EnumWindows meldet jedes offene Fenster einzeln. Der Parameter dafür steht in der DECLARE-Zeile so, wie der Rückruf aussieht – mit FUNCTION(...) AS typ oder SUB(...):"),
  H.code([
    'DECLARE SUB qsort LIB "c" (feld AS BUFFER, n AS ZEIGER, groesse AS ZEIGER, _',
    '                           vergleich AS FUNCTION(a AS ZEIGER, b AS ZEIGER) AS LONG)',
    '',
    'FUNCTION zahlBei(z AS INTEGER) AS INTEGER',
    '    RETURN BUFFER_GET_I32(BUFFER_AUS_ZEIGER(z, 4), 0)',
    'END FUNCTION',
    '',
    'FUNCTION vergleiche(a AS INTEGER, b AS INTEGER) AS INTEGER',
    '    RETURN SGN(zahlBei(a) - zahlBei(b))',
    'END FUNCTION',
    '',
    'DIM b AS BUFFER',
    'b = BUFFER_NEW(12)',
    'BUFFER_SET_I32(b, 0, 42)',
    'BUFFER_SET_I32(b, 4, -7)',
    'BUFFER_SET_I32(b, 8, 13)',
    'qsort(b, 3, 4, vergleiche)',
    'PRINT BUFFER_GET_I32(b, 0), BUFFER_GET_I32(b, 4), BUFFER_GET_I32(b, 8)',
    'qsort(b, 3, 4, FUNCTION(a, b) SGN(zahlBei(b) - zahlBei(a)))',
    'PRINT BUFFER_GET_I32(b, 0), BUFFER_GET_I32(b, 4), BUFFER_GET_I32(b, 8)',
  ]),
  H.code(["-7 13 42", "42 13 -7"], { out: true }),
  H.p("qsort gibt deiner Funktion zwei Zeiger auf Elemente; BUFFER_AUS_ZEIGER liest die vier Bytes dahinter. Übergeben wird die Funktion mit ihrem Namen ohne Klammern – genauso gut eine gebundene Methode (zaehler.eins, das Objekt kommt mit) oder ein Lambda wie im zweiten Aufruf."),
  H.bullet("In den Klammern stehen die C-Typen, die der Rückruf bekommt, mit oder ohne Namen. Erlaubt sind Zahlen, ZEIGER, BOOLEAN und TEXT; zurück gibt er eine Zahl, einen ZEIGER oder BOOLEAN – oder als SUB(...) nichts."),
  H.bullet("Passt die Zahl der Parameter deiner Funktion nicht, ist das ein Fehler, bevor die Bibliothek überhaupt gerufen wird."),
  H.bullet("Ein Fehler in deiner Funktion kommt beim Aufruf der Bibliothek an, sobald sie fertig ist – abfangbar mit CATCH. Bis dahin bekommt sie von jedem weiteren Rückruf eine 0."),
  H.bullet("Ein Rückruf bleibt gültig, bis das Programm endet; die Bibliothek darf ihn sich merken und später rufen."),
  H.tip("Ruft eine Bibliothek aus einem eigenen Faden zurück (CreateThread, pthread_create, manche Treiber), läuft deine Funktion nicht: Drachenhauch-Code läuft nur auf dem Faden des Programms. Der Rückruf liefert dann 0, und der nächste Aufruf einer Bibliothek meldet es.", "Nur ein Faden"),

  H.h2("Beliebig viele Argumente: ..."),
  H.p("Manche C-Funktionen nehmen beliebig viele Werte – printf und seine Geschwister, g_object_set in GTK. In der DECLARE-Zeile steht dafür ... am Ende der Parameter; welcher C-Typ ein weiterer Wert ist, ergibt sich aus dem Wert selbst:"),
  H.code([
    'DECLARE FUNCTION sprintf LIB "msvcrt|c" (ziel AS BUFFER, format AS TEXT, ...) AS LONG',
    '',
    'DIM b AS BUFFER',
    'b = BUFFER_NEW(128)',
    'sprintf(b, "%d Drachen, %.1f Meter, %s", 3, 4.5, "feuerrot")',
    'PRINT TEXT_AUS_ZEIGER$(BUFFER_ZEIGER(b))',
  ]),
  H.code(["3 Drachen, 4.5 Meter, feuerrot"], { out: true }),
  H.bullet("INTEGER und BOOLEAN gehen als ganze Zahl, FLOAT als double, ein Text als char*, ein BUFFER als Zeiger und NIL als Nullzeiger."),
  H.bullet("Unter Windows liegt die printf-Familie in msvcrt und nicht in der C-Bibliothek ucrtbase – daher die zwei Namen \"msvcrt|c\"."),
  H.bullet("Ob die Werte zum Format passen, prüft niemand: ein %s für eine Zahl ist einer der Abstürze vom Anfang des Kapitels."),

  H.h2("Eine ganze Oberfläche: GTK"),
  H.p("Mit DECLARE und Rückrufen lässt sich sogar GTK benutzen, die Bibliothek, mit der unter Linux die meisten Programme ihre Fenster zeichnen. Fenster, Knöpfe und Eingabefelder sind ZEIGER; ein Signal wie \"clicked\" verbindest du mit g_signal_connect_data und einer SUB deines Programms, und gtk_main dreht die Schleife von GTK, bis gtk_main_quit kommt. Das Beispiel 207_gtk.dh zeigt ein Fenster mit Eingabefeld, zwei Knöpfen und einer Beschriftung."),
  H.tip("g_signal_connect, wie es in jeder GTK-Anleitung steht, ist in C nur ein Makro. Gerufen wird g_signal_connect_data – und weil jedes Signal einen anderen Rückruf hat, bekommt jede Form eine eigene DECLARE-Zeile mit ALIAS auf dieselbe C-Funktion.", "Makros gibt es nicht"),

  H.h2("Das Programm weitergeben"),
  H.p("dhrt --export nimmt jede Bibliothek mit, die neben dem Programm liegt, und legt sie neben die exportierte Exe – dort sucht die Laufzeit zuerst. Für eine Systembibliothek wie kernel32 oder die C-Bibliothek ist das nicht nötig; eine fremde, die nicht daneben liegt, nennt der Export als Hinweis, damit du sie selbst mitgibst."),

  H.h2("Unsichere Bibliotheken"),
  H.p("Einer Bibliothek, die abstürzen könnte, gibst du einen eigenen Prozess: Du rufst sie in einem Auftrag mit TASK_START auf (Kapitel „Programme, Aufträge & Umgebung“). Stürzt der Auftrag ab, bekommt dein Programm beim Abholen mit TASK_RESULT$ einen Fehler – „der Auftrag ist abgestuerzt“ – und läuft weiter."),
  H.note("Noch nicht dabei sind Bitfelder, ein Struct als Wert in einem Rückruf und Funktionen mit va_list wie vprintf. Im Browser gibt es keine fremden Bibliotheken."),
];
