module.exports = (H) => [
  H.part("Teil VI — Eine Demo bauen"),
  H.chapter("Was eine Demo ist – und was sie zusammenhält"),
  H.p("In Teil IV hast du ein Spiel gebaut, in Teil V ein Modul nach dem anderen kennengelernt. Zum Abschluss kommt etwas anderes: eine Demo. Das ist ein Programm, das nichts tut, außer vorzuführen, was die Maschine kann – ein durchlaufendes Stück aus Bild und Musik, Szene für Szene. Diese Form gibt es seit den Achtzigern; sie heißt Demoszene, und sie hat einen guten Teil dessen hervorgebracht, was heute selbstverständlich in Spielen steckt."),
  H.p("Warum das als Abschlusskapitel taugt: Eine Demo zwingt dich, alles gleichzeitig zu beherrschen – Zeit, Ton, 2D, 3D, Physik, Shader – und sie verzeiht keine Schlamperei bei der einen Sache, auf die es wirklich ankommt: dass Bild und Musik zusammengehören. Genau davon handelt dieses Kapitel."),
  H.figure("80_demo_titel.png", "Die Titelszene der mitgelieferten Demo: Plasma im Post-Effekt, ein Sinus-Scroller und Spektrum-Säulen, die auf der echten Musik tanzen."),
  H.p("Die vollständige Demo liegt als gbdemo/gbdemo.dh bei. Starte sie ruhig zuerst und lies dann weiter – es ist leichter zu verstehen, was du schon gesehen hast. Mit den Zifferntasten springst du in eine Szene, mit A bis K spielst du Klänge, und M schaltet zwischen acht gemeinfreien Musikstücken um."),
  H.code([
    "dhrun.py gbdemo\\gbdemo.dh",
  ]),

  H.h2("Die zwei Bausteine, die alles tragen"),
  H.p("Fast jeder Anfänger baut die Bild-Musik-Kopplung falsch herum: Er zählt Sekunden mit einer eigenen Uhr mit und hofft, dass es zur Musik passt. Es passt nie lange. Sobald die Bildrate schwankt – und sie schwankt immer –, laufen die beiden Uhren auseinander, und nach zwei Minuten sitzt der Szenenwechsel mitten im Takt statt darauf."),
  H.p("GameBasic hat für beide Hälften des Problems einen eigenen Befehl. Zusammen sind sie das Rückgrat jeder Demo:"),
  H.cmd("AUDIO_MUSIC_POSITION", "AUDIO_MUSIC_POSITION() AS FLOAT",
    "Die Sekunde IM STÜCK, nicht seit Programmstart. Sie kommt aus dem Abspielen selbst – hängt der Ablaufplan daran, kann er gar nicht gegen die Musik verrutschen.",
    [
      'AUDIO_MUSIC_LOAD("assets/music/stardust_jam.mod")',
      'AUDIO_MUSIC_PLAY(-1, 1200)      \' endlos, 1,2 s eingeblendet',
      '',
      'DIM zeit AS FLOAT',
      'zeit = AUDIO_MUSIC_POSITION()   \' <- die Uhr der Demo',
    ]),
  H.cmd("AUDIO_FFT", "AUDIO_FFT(arr)",
    "Füllt ein dimensioniertes ARRAY OF FLOAT mit den Bandpegeln des Klangs, der GERADE ZU HÖREN IST. Nicht der Noten in einer Datei – des fertigen Mixes, inklusive aller Effekte.",
    [
      'DIM spek[32] AS FLOAT           \' muss dimensioniert sein!',
      'AUDIO_FFT(spek)',
      'PRINT spek[0]                   \' unterstes Band = Bass',
    ]),
  H.note("Das Array muss vorher eine Größe haben. AUDIO_FFT füllt so viele Bänder, wie hineinpassen – ein DIM ohne Größe meldet einen Fehler."),
  H.p("Der Unterschied zwischen „ich rechne mir etwas aus, das ungefähr wie Musik aussieht“ und „ich lese, was gerade klingt“ ist der ganze Unterschied zwischen einer netten Animation und einer Demo. Alles, was in unserer Demo pulsiert, pulsiert auf diesen 32 Zahlen."),

  H.h2("Das Gerüst: ein Ablaufplan aus Sekunden"),
  H.p("Eine Demo ist eine Liste von Szenen mit Zeitmarken. Mehr nicht. Der ganze Ablauf steckt in ein paar Konstanten und einer IF-Kette – und weil die Zeit aus der Musik kommt, sitzt jeder Schnitt, wo er soll:"),
  H.code([
    "' Szenen-Grenzen in Sekunden des Stücks",
    "CONST T1 AS FLOAT = 42.0        ' Titel",
    "CONST T2 AS FLOAT = 84.0        ' Sternenflug",
    "CONST T3 AS FLOAT = 128.0       ' Würfelfeld",
    "' ... bis T8",
    "",
    "WHILE NOT QUITREQUESTED()",
    "    zeit = AUDIO_MUSIC_POSITION()",
    "    CLS(&H05070C)",
    "",
    "    IF zeit < T1 THEN",
    "        szene_titel()",
    "    ELSEIF zeit < T2 THEN",
    "        szene_sterne()",
    "    ELSEIF zeit < T3 THEN",
    "        szene_wuerfel()",
    "    END IF",
    "",
    "    FLIP()",
    "WEND",
  ]),
  H.p("Jede Szene ist eine SUB, die genau ein Bild zeichnet. Sie merkt sich nichts über die Zeit – sie schaut auf zeit und auf das Spektrum und malt daraus das aktuelle Bild. Das klingt streng, macht aber jede Szene für sich verständlich und einzeln testbar."),
  H.tip("Kapitel-Sprünge einbauen", "Beim Entwickeln willst du nicht jedes Mal vier Minuten warten, bis deine Szene dran ist. Führe eine Variable versatz ein und rechne zeit = AUDIO_MUSIC_POSITION() + versatz. Dann springen die Zifferntasten 1–8 direkt in eine Szene, indem sie versatz passend setzen. In der mitgelieferten Demo ist das eingebaut – und es hat beim Bauen jede Menge Zeit gespart."),

  H.h2("Weich ein- und ausblenden"),
  H.p("Harte Schnitte wirken billig. Jede Szene bekommt deshalb einen Wert zwischen 0 und 1, mit dem am Anfang aufgeblendet und am Ende abgeblendet wird. Die Funktion dafür ist so klein wie unspektakulär:"),
  H.code([
    "FUNCTION randblende(t AS FLOAT, dauer AS FLOAT, rand AS FLOAT) AS FLOAT",
    "    DIM v AS FLOAT",
    "    v = 1.0",
    "    IF t < rand THEN v = t / rand",
    "    IF t > dauer - rand THEN v = (dauer - t) / rand",
    "    IF v < 0.0 THEN v = 0.0        ' begrenzen!",
    "    IF v > 1.0 THEN v = 1.0",
    "    RETURN v",
    "END FUNCTION",
  ]),
  H.warn("Die beiden Begrenzungs-Zeilen sind kein Zierrat. Ohne sie wird der Wert beim Überlaufen negativ – und wenn du damit eine Farbe multiplizierst, kommt Unsinn heraus. Genau dieser Fehler steckte in der ersten Fassung der Demo."),

  H.h2("Den Schlag finden"),
  H.p("Vieles soll nicht dauernd wabern, sondern auf den Schlag passieren: ein Blitz, ein Partikel-Ausbruch, ein geworfener Ball. Dafür brauchst du eine Schlagerkennung. Das Prinzip ist einfach – Bass deutlich über seinem eigenen Durchschnitt – aber es gibt dabei eine Falle, die fast jeder einmal baut:"),
  H.code([
    "' Zwei Wege, absichtlich getrennt:",
    "'   glatt[]  hält Spitzen und fällt langsam nach -> ruhige Säulen",
    "'   roh      ist das ungeglättete Bild dieses Augenblicks",
    "AUDIO_FFT(spek)",
    "DIM roh AS FLOAT",
    "roh = 0.0",
    "FOR k = 0 TO 5",
    "    IF spek[k] > glatt[k] THEN",
    "        glatt[k] = spek[k]                      ' schnell hoch",
    "    ELSE",
    "        glatt[k] = glatt[k] * 0.86 + spek[k] * 0.14   ' langsam runter",
    "    END IF",
    "    roh = roh + spek[k]",
    "NEXT",
    "roh = roh / 6.0",
    "",
    "' Schlag = ROHER Bass über seinem gleitenden Mittel, mit Sperrzeit",
    "bass_lang = bass_lang * 0.94 + roh * 0.06",
    "beat = FALSE",
    'IF roh > bass_lang * 1.18 AND roh > 0.12 AND COOLDOWN("beat", 170) THEN',
    "    beat = TRUE",
    "END IF",
  ]),
  H.warn("Die Schlagerkennung muss auf den ROHEN Werten liegen. Die nachfallende Glättung, die die Säulen ruhig aussehen lässt, bügelt genau die Spitzen weg, auf die es ankommt: In der ersten Fassung der Demo stand der geglättete Bass konstant bei 0,90 gegen ein Mittel von 0,75 – die Bedingung „deutlich über dem Mittel“ konnte nie zutreffen, und es flog nie ein Ball. Führe beides getrennt: glatt[] fürs Bild, roh für den Schlag."),
  H.p("COOLDOWN aus dem timer-Modul ist hier genau richtig: Es liefert nur dann TRUE, wenn seit dem letzten TRUE genug Zeit vergangen ist. Ohne diese Sperre meldet die Erkennung denselben Schlag über mehrere Bilder hinweg."),

  H.h2("Ein Shader für alle Szenen"),
  H.p("Der letzte Baustein ist der Post-Effekt. POSTFX schickt das fertige Bild durch einen Fragment-Shader, bevor es auf dem Bildschirm landet – dort entstehen Glimmen, Vignette, Plasma und Tunnel. Statt für jede Szene einen eigenen Shader zu laden, nimmt die Demo einen einzigen und schaltet ihn über ein Uniform um:"),
  H.code([
    "DIM sh AS INTEGER",
    'sh = SHADER_LOAD("assets/shaders/demo.fs")',
    'SHADER_SET2(sh, "resolution", BREITE, HOEHE)',
    "",
    "' ... jedes Bild, direkt vor FLIP:",
    'SHADER_SET(sh, "time", zeit)',
    'SHADER_SET(sh, "bass", bass)',
    'SHADER_SET(sh, "fade", blende)',
    'SHADER_SET(sh, "mode", modus)   \' 0 Glanz, 1 Plasma, 2 Tunnel, 3 CRT',
    "POSTFX(sh)",
  ]),
  H.note("POSTFX bekommt das FERTIGE Bild. Einen Hintergrund kann der Shader deshalb nur dort einblenden, wo das Bild dunkel ist – die Demo zeichnet ihre Szenen auf Schwarz, und der Shader füllt die dunklen Stellen mit Plasma oder Tunnel. Wer das nicht bedenkt, wundert sich, warum sein „Hintergrund“ über allem liegt."),
  H.warn("Wenn dein Shader die Nachbarpixel abtastet – jedes Glimmen tut das –, dann klemme die Abtastpunkte ein HALBES Texel vom Rand entfernt. Auf 0..1 zu klemmen reicht nicht: Genau auf der Kante mischt die bilineare Filterung die letzte Zeile mit der ersten, und der helle Inhalt vom unteren Rand blutet oben wieder herein. In der Demo war das als Reihe Farbfetzen in der obersten Pixelzeile zu sehen."),

  H.h2("Was du jetzt kannst"),
  H.bulletRich("AUDIO_MUSIC_POSITION ", "als Uhr nehmen – nie eine eigene mitzählen."),
  H.bulletRich("AUDIO_FFT ", "lesen und daraus Bass, Mitten und Höhen bilden."),
  H.bulletRich("Schlag erkennen ", "auf den rohen Werten, mit COOLDOWN als Sperre."),
  H.bulletRich("Szenen ", "als SUBs, die aus zeit und Spektrum genau ein Bild malen."),
  H.bulletRich("POSTFX ", "mit einem Shader für alles, umgeschaltet über ein Uniform."),
  H.p("Im nächsten Kapitel gehen wir die acht Szenen der Demo einzeln durch – jede zeigt eine andere Ecke der Laufzeit."),
];
