module.exports = (H) => [
  H.chapter("Die acht Szenen – und was in jeder steckt"),
  H.p("Jede Szene der Demo führt eine andere Ecke der Laufzeit vor. Hier ist der Kern jeder einzelnen: das Bild, die entscheidende Technik und der Stolperstein, über den man dabei fällt. Nachbauen kannst du jede für sich – das Gerüst aus dem letzten Kapitel reicht dafür."),

  H.h2("1 · Titel: Plasma, Scroller, Säulen"),
  H.p("Die Titelszene ist reine Zweidimensionalität und trotzdem der beste Beweis, dass alles zusammenhängt: Die Säulen sind das Spektrum, das Logo wächst auf dem Schlag, und der Plasma-Hintergrund atmet mit dem Bass. Der Sinus-Scroller – Text, der als Welle durchs Bild läuft – ist so alt wie die Demoszene selbst und in sechs Zeilen gebaut:"),
  H.code([
    "DIM sx AS FLOAT",
    "sx = BREITE - (zeit - 2.0) * 210.0        ' läuft nach links",
    "DIM k AS INTEGER",
    "FOR k = 0 TO LEN(SCROLLTEXT) - 1",
    "    DIM px AS FLOAT",
    "    px = sx + k * 26.0",
    "    IF px > -40.0 AND px < BREITE + 40.0 THEN",
    "        DIM py AS FLOAT",
    "        py = HOEHE * 0.68 + SIN(px * 0.012 + zeit * 2.0) * 42.0",
    "        mtext(INT(px), INT(py), MID$(SCROLLTEXT, k, 1), 0.72, farbe)",
    "    END IF",
    "NEXT",
  ]),
  H.note("Die Höhe hängt an px, nicht an k – deshalb bleibt die Welle im Raum stehen, während der Text hindurchläuft. Hinge sie an k, liefe die Welle mit dem Text mit, und der Effekt wäre weg."),

  H.h2("2 · Sternenflug: 1400 Streifen in einem Aufruf"),
  H.figure("81_demo_sterne.png", "Jeder Stern wird zweimal projiziert – vorher und jetzt. Die Strecke dazwischen ist der Streifen."),
  H.p("Sterne fliegen auf dich zu: Jeder hat eine Tiefe z, die kleiner wird, und wird zentral projiziert – je näher, desto weiter außen und heller. Der Trick für den Warp-Effekt ist, jeden Stern ZWEIMAL zu projizieren: an seiner Position vor diesem Bild und an seiner jetzigen. Die Strecke dazwischen ist der Streifen, und je schneller (also je mehr Bass), desto länger."),
  H.code([
    "stz[k] = stz[k] - (0.30 + bass * 2.4) * dt   ' Bass = Tempo",
    "",
    "' zweimal projizieren: vorher (ax,ay) und jetzt (bx,by)",
    "ax = BREITE / 2.0 + stx[k] / z_vor  * BREITE * 0.46",
    "bx = BREITE / 2.0 + stx[k] / stz[k] * BREITE * 0.46",
    "lx1[k] = INT(ax) : lx2[k] = INT(bx)",
    "",
    "LINES(lx1, ly1, lx2, ly2, lc)      ' EIN Aufruf für 1400 Streifen",
  ]),
  H.warn("LINES, PLOTS, BOXES und CIRCLES zeichnen ohne Stückzahl IMMER das ganze Array. Wer einen Puffer fest dimensioniert und pro Bild nur teilweise füllt, bekommt die alten Werte der restlichen Plätze mitgezeichnet – in der ersten Fassung der Demo waren das Sterne von vorgestern, die überall herumstanden. Entweder du gibst die Stückzahl als letztes Argument mit, oder du schiebst unbenutzte Plätze selbst aus dem Bild (Koordinate -10)."),

  H.h2("3 · Würfelfeld: 1600 Würfel, drei Draw-Calls"),
  H.figure("81_demo_wuerfel.png", "Ein 40×40-Gitter aus Würfeln. Der Abstand zur Mitte wählt das Frequenzband – so läuft die Welle von innen nach außen mit der Musik."),
  H.p("Hier zeigt sich, wofür GPU-Instancing da ist: 1600 Würfel, jeder mit eigener Position, Höhe und Drehung – und trotzdem nur drei Zeichenbefehle. MODEL_INSTANCED nimmt ein ganzes Array von Matrizen und schickt es in einem Rutsch an die Grafikkarte."),
  H.code([
    "DIM mats[1600] AS MAT4",
    "DIM mcol[1600] AS INTEGER",
    "",
    "' pro Würfel: Position + Drehung in EINE Matrix",
    "mats[idx] = MAT4_MUL(MAT4_TRANSLATE(wx, hoch, wz), _",
    "                     QUAT_TO_MAT4(QUAT_FROM_AXIS_ANGLE(0, 1, 0, winkel)))",
    "mcol[idx] = farbe_des_rings",
    "",
    "MODEL_INSTANCED(mesh_box, mats, mcol, idx)",
  ]),
  H.note("Das vierte Argument ist ein Farb-ARRAY. Die Laufzeit gruppiert danach und setzt einen Draw-Call je VERSCHIEDENER Farbe ab – nicht je Würfel. Drei Farben für 1600 Würfel sind also drei Aufrufe. Wer 1600 verschiedene Farben braucht, bekommt auch 1600 Aufrufe; dafür wäre ein Farbverlauf im Shader die bessere Antwort."),
  H.tip("Höhe aus dem Spektrum", "Der Abstand jedes Würfels zur Mitte wählt sein Frequenzband: ring = INT(SQR(wx*wx + wz*wz) * 0.55) MOD 32. Dadurch läuft die Welle als Ring von innen nach außen – viel organischer, als wenn jeder Würfel dasselbe Band nähme."),

  H.h2("4 · PBR unter echtem Himmel"),
  H.figure("81_demo_pbr.png", "Neun Kugeln, Rauheit von 0,03 (Spiegel – man sieht die Landschaft darin) bis 0,85 (matt). Das Panorama ist gleichzeitig Licht und Hintergrund."),
  H.p("Diese Szene packt die schwerste Artillerie aus: Ein echtes HDR-Panorama liefert das Umgebungslicht UND den sichtbaren Hintergrund, jede Kugel hat ihr eigenes Material, und die Sonne wirft Schatten."),
  H.code([
    'LIGHT_ENV_HDR("assets/ibl_env.hdr", 1.0)   \' Umgebungslicht aus dem Panorama',
    "SKYBOX(TRUE)                                ' dasselbe Panorama als Hintergrund",
    "SHADOW_ENABLE(2048)",
    "SHADOW_AREA(14.0, 40.0)",
    "",
    "' Rauheit von spiegelnd bis matt über den Ring verteilt",
    "FOR kk = 0 TO 8",
    "    kugeln[kk] = MESH_SPHERE(0.62, 40, 40)",
    "    MODEL_LIT(kugeln[kk])",
    "    MODEL_PBR(kugeln[kk], 1.0, 0.03 + kk / 8.0 * 0.82)",
    "NEXT",
  ]),
  H.warn("Licht, Himmel, Schatten und Dunst sind GLOBALER Zustand. Wer sie in einer Szene einschaltet, muss sie beim Szenenwechsel wieder ausschalten – sonst zieht der HDR-Himmel auch hinter der nächsten Szene auf. Die Demo hat dafür eine SUB szene_start(n), die bei jedem Wechsel einmal aufräumt."),
  H.tip("Der Boden muss zum Spiegelbild passen", "Wer eine spiegelnde Kugel vor einen einfarbigen Boden stellt, erzeugt einen Widerspruch: In der Kugel sieht man Gelände, darunter eine Farbfläche. Der Boden der Demo trägt deshalb eine prozedurale Struktur (GENTEX_CELLULAR als Diffuse-Map) und läuft per LIGHT_FOG in den Horizont aus. Beachte dabei: MESH_PLANE kachelt seine Textur NICHT – sie wird einmal über die ganze Ebene gespannt. Auf 400 Einheiten Breite wird daraus wieder eine Farbfläche; 130 Einheiten plus Dunst sehen richtig aus."),

  H.h2("5 · Physik: ein Logo, das zusammenfällt"),
  H.figure("81_demo_physik.png", "Das Logo steht aus Klötzen da, im Hintergrund regnet es Trümmer. Getroffen wird nur, was auch getroffen wird: Das B steht noch."),
  H.p("physics2d ist kein Kollisions-Werkzeugkasten, sondern ein echter Starrkörper-Löser (Rapier). Schwerkraft, Stapeln, Reibung und Abprallen rechnet die Laufzeit; die Demo baut nur auf und schaut zu. Die Buchstaben stehen als Muster im Quelltext – ein Doppelkreuz wird ein Klotz:"),
  H.code([
    'logo_g[0] = "#####"',
    'logo_g[1] = "#...."',
    'logo_g[2] = "#...."',
    'logo_g[3] = "#.###"',
    "' ...",
    "",
    "' aus dem Muster Klötze machen -- erst einmal STATISCH",
    'IF MID$(zeile, c, 1) = "#" THEN',
    "    kid[nk] = PHYS2D_ADD_BOX(welt, x0 + c * KLOTZ, y0 + r * KLOTZ, _",
    "                             KLOTZ / 2 - 1, KLOTZ / 2 - 1, FALSE, 0.05)",
    "END IF",
  ]),
  H.p("Das FALSE ist der Kern der Szene. Baut man die Buchstaben gleich beweglich, fällt der Querbalken des G in dem Moment herunter, in dem die Szene beginnt – man sieht das Logo nie. Es steht deshalb statisch da und wird erst umgeschaltet, wenn eine Kugel wirklich ankommt:"),
  H.code([
    "' beim Einschlag: nur DIESEN Buchstaben beweglich machen",
    "FOR k = 0 TO n_logo - 1",
    "    IF kbuchstabe[k] = getroffen THEN PHYS2D_SET_DYNAMIC(welt, kid[k], TRUE)",
    "NEXT",
  ]),
  H.warn("Zwei Fehler stecken hier dicht beieinander, und beide sehen aus wie Physik-Fehler, sind aber Logik-Fehler. Erstens: Wer beim ABSCHUSS der Kugel umschaltet statt beim Einschlag, lässt das Logo eine halbe Sekunde zu früh fallen – es sieht aus, als kippe es von selbst. Zweitens: Wer alle Klötze auf einmal umschaltet, reißt auch den Buchstaben um, den niemand angefasst hat. Merke dir pro Klotz, zu welchem Buchstaben er gehört."),
  H.tip("Menge macht Eindruck", "Der eigentliche Wow-Effekt dieser Szene ist nicht das Logo, sondern der Trümmerregen dahinter: Derselbe Löser rechnet nebenbei ein paar hundert weitere Körper, die sich am Boden zu Haufen stapeln. Gezeichnet wird in zwei Durchgängen – erst der Hintergrund, dann das Logo –, sonst legen sich die kleinen Klötze darüber."),

  H.h2("6 · Tunnel: Schweife aus einem Render-Target"),
  H.figure("81_demo_tunnel.png", "Der Tunnel kommt aus dem Post-Effekt, der Ring aus dem Spektrum – und die verblassenden Schweife aus einem Render-Target, das stehen bleibt."),
  H.p("Der Tunnel selbst ist Shader-Arbeit: eine 1/r-Abbildung, der klassische Demo-Tunnel. Davor liegt ein Ring, dessen Radius Band für Band aus dem Spektrum kommt – die Musik als Gestalt. Interessant ist, wie die Schweife entstehen:"),
  H.code([
    "' TRUE = der Inhalt bleibt über das Bild hinaus stehen",
    "rt_ring = RENDERTARGET_NEW(BREITE, HOEHE, TRUE)",
    "",
    "' ... jedes Bild:",
    "RENDERTARGET_BEGIN(rt_ring)",
    '    BLEND_MODE("mult")                       \' verblassen statt löschen',
    "    BOX(0, 0, BREITE, HOEHE, RGB(214, 214, 220))",
    '    BLEND_MODE("alpha")',
    "    SPLINE(ringx, ringy, farbe, breite)      ' der neue Ring",
    "RENDERTARGET_END()",
  ]),
  H.note("Ein Render-Target wird normalerweise vor jedem Bild geleert. Mit TRUE bleibt es stehen – das ist die Voraussetzung für Schweife. Verblassen geht dabei NICHT durch Selbst-Zeichnen (ein Target kann sich nicht selbst zeichnen), sondern durchs Multiplizieren mit einem dunklen Grau."),
  H.warn("Ein Spektrum-Ring braucht ein GESPIEGELTES Spektrum. Legt man die Bänder einfach rundherum, stoßen Band 31 (Höhen, klein) und Band 0 (Bass, groß) direkt aneinander – ein Sprung von über 150 Pixeln zwischen zwei Nachbarpunkten, aus dem die Catmull-Rom-Kurve einen weit hinausschießenden Zacken macht. Lass das Spektrum die eine Hälfte hoch- und gespiegelt wieder herunterlaufen."),

  H.h2("7 · Klangfarben: die Effektkette bei der Arbeit"),
  H.figure("81_demo_klang.png", "Ein Tiefpass fährt herunter – und die rechten Säulen verschwinden wirklich, weil sie das echte Spektrum HINTER der Effektkette sind."),
  H.p("Die einzige Szene, in der die Demo den Klang anfasst. Sie geht in sechs Stufen durch die Effektkette: Tiefpass-Sweep, Wobble (ein LFO auf dem Filter), Echo, Hall, Verzerrer und Auto-Pan."),
  H.code([
    'AUDIO_FILTER("music", cutoff, 0.55)          \' Tiefpass, leicht resonant',
    "",
    "' Wobble: ein LFO fährt den Filter -- auf dem AUDIO-Thread",
    'lfo = AUDIO_LFO_NEW("sine", 5.5)',
    'AUDIO_MODULATE("music", "filter", lfo, 260.0, 5200.0)',
    "",
    'AUDIO_DELAY("music", 0.42, 0.55, 300)        \' Echo',
    'AUDIO_REVERB("music", 0.55, 0.88, 0.25)      \' Hall',
    'AUDIO_DISTORTION("music", 0.45, 0.7)         \' Overdrive',
  ]),
  H.p("Der Punkt daran: Nach dem Setzen rechnet das Programm nichts mehr nach. Die Audio-Schicht fährt Modulatoren und Effekte selbst, sample-genau – ein Filter-Sweep läuft also unbeirrt weiter, auch wenn die Bildrate einbricht."),
  H.tip("Der Beweis steht im Bild", "Weil die Säulen das echte Spektrum hinter der Kette zeigen, sieht man den Filter arbeiten. Nachgemessen an der Demo: Die Summe der oberen zwölf Bänder fällt von 0,79 (bei 7200 Hz Cutoff) auf 0,13 (bei 460 Hz), während der Bass unverändert bei 3,8 bis 5,6 bleibt. Faktor sechs – das ist keine Animation, das ist der Filter."),
  H.warn("Effekte hängen am Bus und bleiben hängen. Wer sie beim Verlassen der Szene nicht auf neutral zurücksetzt, lässt den Rest der Demo durch den Verzerrer laufen."),

  H.h2("8 · Abspann: Klang, der wirklich kreist"),
  H.figure("81_demo_abspann.png", "Ein Drahtgitter-Ring, der Abspann – und ein Punkt, der die Schallquelle zeigt: Der Ping wandert hörbar um dich herum."),
  H.p("Zum Ausklang etwas Ruhiges – und ein letzter Trick, den man nur mit Lautsprechern versteht. Der Ping im Abspann kreist wirklich um den Zuhörer: Die Laufzeit rechnet Panorama und Entfernungsdämpfung selbst, das Programm setzt nur die Position."),
  H.code([
    "' Ohr im Ursprung, Quelle kreist in 6 Metern Abstand",
    "ohr = AUDIO_LISTENER_NEW(0.0, 0.0, 0.0)",
    "quelle = AUDIO_EMITTER_NEW(ohr, 6.0, 0.0, 0.0, 1.0, 22.0)",
    'ping = AUDIO_SFX("sine", 660.0, 0.15, 0.005, 0.05, 0.45, 0.0, 0.0, 0.5)',
    "",
    "' jedes Bild: Quelle weiterdrehen, ab und zu anschlagen",
    "AUDIO_EMITTER_SET_POSITION(quelle, COS(w) * 6.0, 0.0, SIN(w) * 6.0)",
    'IF COOLDOWN("ping", 2400) THEN AUDIO_PLAY_ON(ping, quelle, 0, 0.55)',
  ]),
  H.note("Der leuchtende Punkt auf dem Bild zeigt nur, wo der Klang gerade steht. Ohne diese Beschriftung bleibt der schönste Effekt unbemerkt – das ist eine allgemeine Lehre: Was man nicht sieht, hält man für nicht vorhanden."),

  H.h2("Die Klang-Tastatur"),
  H.p("Quer durch alle Szenen liegt noch etwas: Acht Klänge auf den Tasten A bis K, jederzeit spielbar. Keiner davon ist eine Datei – jeder ist EINE Zeile:"),
  H.code([
    "' Wellenform, Frequenz, Slide, Attack, Sustain, Decay,",
    "' Vibrato-Tiefe, Vibrato-Tempo, Lautstärke [, SID-Erweiterungen]",
    'klang[0] = AUDIO_SFX("sine", 150, -110, 0, 60, 220, 0, 0, 0.9)          \' Kick',
    'klang[1] = AUDIO_SFX("noise", 900, -300, 0, 40, 180, 0, 0, 0.7)        \' Snare',
    'klang[3] = AUDIO_SFX("saw", 1200, -900, 0, 140, 120, 0, 0, 0.6, _',
    "                     0.0, 0.5, 0.0, 0.0, 5000, -9000, 0.75)           ' Laser",
  ]),
  H.p("Die letzten Argumente sind die SID-Erweiterungen: Pulsbreite, Pulsbreiten-Modulation und ein resonanter Filter-Sweep. Damit lässt sich der Charakter alter Heimcomputer-Klangchips nachbauen – der Laser oben ist ein Sägezahn, dessen Filter in 140 Millisekunden von 5000 Hz nach unten rauscht."),

  H.h2("Zum Schluss"),
  H.p("Eine Demo ist die ehrlichste Prüfung für eine Laufzeit: Sie lässt sich nicht durch ein hübsches Standbild bestehen. Alles muss gleichzeitig laufen, ineinandergreifen und auf die Musik hören. Wenn du dieses Kapitel durchgearbeitet hast, kennst du nicht nur die Befehle – du weißt, wie man sie zu etwas zusammensetzt, das mehr ist als die Summe seiner Teile."),
  H.tip("Nimm sie auseinander", "Der Quelltext der Demo liegt vollständig bei (gbdemo/gbdemo.gb) und ist durchkommentiert – gerade an den Stellen, an denen beim Bauen etwas schiefging. Ändere die Szenengrenzen, tausche das Musikstück, häng eine neunte Szene an. Genau so hat die Demoszene immer funktioniert."),
];
