// Beispiel-Galerie fuer den Web-Playground.
//
// Bewusste Regel: **kein Programm hier darf eine Datei laden.** Die Galerie
// laeuft in jedem Build, auch in einem ohne `assets/`-Paket -- ein
// LOADIMAGE/AUDIO_MUSIC_LOAD wuerde dort ins Leere greifen. Alles, was hier zu
// sehen ist, rechnet die Runtime selbst aus.
//
// Neues Beispiel: Eintrag mit `name` (Knopfbeschriftung) und `src` (Quelle)
// anhaengen. Kurz halten -- die Galerie soll zum Lesen einladen, nicht zum
// Scrollen.
window.GB_BEISPIELE = [
  {
    name: "Hallo",
    src: [
      'PRINT "Hallo Welt!"',
      'DIM i AS INTEGER',
      'FOR i = 1 TO 5',
      '    PRINT STR$(i) + " zum Quadrat ist " + STR$(i * i)',
      'NEXT',
    ].join("\n"),
  },
  {
    name: "Plasma",
    src: [
      "' Farbverlauf pro Pixelblock -- klassisches Demo-Motiv.",
      'SCREEN(320, 200, "Plasma", 2)',
      "DIM t AS FLOAT",
      "DIM x AS INTEGER",
      "DIM y AS INTEGER",
      "DIM v AS FLOAT",
      "WHILE NOT QUITREQUESTED()",
      "    t = t + 0.03",
      "    FOR y = 0 TO 49",
      "        FOR x = 0 TO 79",
      "            v = SIN(x * 0.15 + t) + SIN(y * 0.19 - t) + SIN((x + y) * 0.11 + t)",
      "            BOX(x * 4, y * 4, x * 4 + 3, y * 4 + 3, RGB(128 + INT(SIN(v) * 127.0), 40, 128 + INT(COS(v * 1.3) * 127.0)))",
      "        NEXT",
      "    NEXT",
      "    FLIP()",
      "WEND",
    ].join("\n"),
  },
  {
    name: "Sternenflug",
    src: [
      "' PLOTS zeichnet alle Sterne in EINEM Aufruf statt in einer Schleife.",
      'SCREEN(480, 300, "Sterne", 1)',
      "CONST N AS INTEGER = 700",
      "DIM sx[N] AS FLOAT",
      "DIM sy[N] AS FLOAT",
      "DIM sz[N] AS FLOAT",
      "DIM px[N] AS INTEGER",
      "DIM py[N] AS INTEGER",
      "DIM farbe[N] AS INTEGER",
      "DIM i AS INTEGER",
      "DIM h AS INTEGER",
      "RANDOMIZE(7)",
      "FOR i = 0 TO N - 1",
      "    sx[i] = RND() * 2.0 - 1.0",
      "    sy[i] = RND() * 2.0 - 1.0",
      "    sz[i] = RND() * 0.9 + 0.1",
      "NEXT",
      "WHILE NOT QUITREQUESTED()",
      "    CLS(&H050810)",
      "    FOR i = 0 TO N - 1",
      "        sz[i] = sz[i] - 0.006",
      "        IF sz[i] < 0.05 THEN sz[i] = 1.0",
      "        px[i] = 240 + INT(sx[i] / sz[i] * 240.0)",
      "        py[i] = 150 + INT(sy[i] / sz[i] * 150.0)",
      "        h = 255 - INT(sz[i] * 130.0)",
      "        farbe[i] = RGB(h, h, 255)",
      "    NEXT",
      "    PLOTS(px, py, farbe, N)",
      "    FLIP()",
      "WEND",
    ].join("\n"),
  },
  {
    name: "3D + Licht",
    src: [
      "' Braucht WebGL 2 -- Beleuchtung und PBR laufen im Browser.",
      'IMPORT "g3d"',
      'SCREEN(480, 300, "3D", 1)',
      "LIGHT_ENABLE()",
      "LIGHT_AMBIENT(&H303848, 0.6)",
      "LIGHT_DIRECTIONAL(-0.5, -0.8, -0.4, &HFFE0B0)",
      "LIGHT_ENV(&H6090E0, &H201810, 1.0)",
      "DIM kugel AS INTEGER",
      "kugel = MESH_SPHERE(1.0, 24, 24)",
      "MODEL_LIT(kugel)",
      "MODEL_PBR(kugel, 0.9, 0.2)",
      "DIM t AS FLOAT",
      "WHILE NOT QUITREQUESTED()",
      "    t = t + 0.01",
      "    CLS(&H0A0E16)",
      "    CAMERA3D(SIN(t) * 6.0, 2.0, COS(t) * 6.0, 0.0, 0.0, 0.0, 45.0)",
      "    MODEL(kugel, -1.8, 0.0, 0.0, 1.0, &HFF7040)",
      "    MODEL(kugel, 1.8, 0.0, 0.0, 1.0, &H70A0FF)",
      "    CUBE(0.0, 0.0, 0.0, 1.2, 1.2, 1.2, &H80FF80)",
      "    GRID3D(12, 1.0)",
      "    FLIP()",
      "WEND",
    ].join("\n"),
  },
  {
    name: "Physik",
    src: [
      "' Echte Starrkoerper-Physik (Rapier2D) -- Klick wirft einen Ball.",
      'IMPORT "physics2d"',
      'SCREEN(480, 320, "Physik", 1)',
      "DIM welt AS PHYS2D_WORLD",
      "welt = PHYS2D_NEW()",
      "PHYS2D_ADD_BOX(welt, 240.0, 310.0, 240.0, 10.0, FALSE, 0.4)",
      "PHYS2D_ADD_BOX(welt, 20.0, 160.0, 10.0, 160.0, FALSE, 0.4)",
      "PHYS2D_ADD_BOX(welt, 460.0, 160.0, 10.0, 160.0, FALSE, 0.4)",
      "DIM i AS INTEGER",
      "FOR i = 0 TO 11",
      "    PHYS2D_ADD_CIRCLE(welt, 120.0 + i * 20.0, 40.0 + i * 12.0, 10.0, TRUE, 0.6)",
      "NEXT",
      "WHILE NOT QUITREQUESTED()",
      "    IF MOUSE_HIT(1) THEN",
      "        PHYS2D_ADD_CIRCLE(welt, MOUSEX() * 1.0, MOUSEY() * 1.0, 10.0, TRUE, 0.7)",
      "    END IF",
      "    PHYS2D_STEP(welt, 1.0 / 60.0)",
      "    CLS(&H101820)",
      "    BOX(10, 300, 470, 320, &H30506A)",
      "    FOR i = 3 TO PHYS2D_COUNT(welt) - 1",
      "        CIRCLE(INT(PHYS2D_BODY_X(welt, i)), INT(PHYS2D_BODY_Y(welt, i)), 10, &HFFB040)",
      "    NEXT",
      "    TEXT(12, 12, \"Klick wirft einen Ball\", &HFFFFFF)",
      "    FLIP()",
      "WEND",
    ].join("\n"),
  },
  {
    name: "Klang + Spektrum",
    src: [
      "' Im Browser ist nichts zu HOEREN -- aber das Spektrum ist echt:",
      "' der Mix wird vollstaendig gerechnet, nur nicht ausgegeben.",
      'SCREEN(480, 300, "Spektrum", 1)',
      "DIM ton AS SOUND",
      "DIM spek[32] AS FLOAT",
      "DIM i AS INTEGER",
      "DIM t AS INTEGER",
      "ton = AUDIO_TONE(220.0, 4000, \"saw\", 0.7)",
      "AUDIO_PLAY(ton, -1, 0.8)",
      "WHILE NOT QUITREQUESTED()",
      "    t = t + 1",
      "    IF t MOD 90 = 0 THEN",
      "        AUDIO_FILTER(\"sfx\", 300.0 + RND() * 4000.0, 2.0)",
      "    END IF",
      "    AUDIO_FFT(spek)",
      "    CLS(&H0A0E16)",
      "    FOR i = 0 TO 31",
      "        BOX(i * 15 + 2, 290 - INT(spek[i] * 260.0), i * 15 + 13, 290, RGB(60 + i * 6, 200 - i * 4, 255))",
      "    NEXT",
      "    TEXT(12, 12, \"AUDIO_FFT -- echtes Spektrum, stumm\", &HFFFFFF)",
      "    FLIP()",
      "WEND",
    ].join("\n"),
  },
];
